### ISSUE TITLE
[JS] Problem with grunt serve not reloading js

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/game-project#10]
I had a problem with grunt serve this morning as well.  When I am running grunt serve, HTML and CSS will automatically update on the browser.  However, when I make changes to JS (and save), grunt serve won't update and I need to restart grunt serve (takes a long time).  I thought I was just having problems with bootstrap, but I realized it happened to my tic tac toe project too.  I don't think this was happening prior to today :(

Is there any way to fix this?  Constantly re-running grunt serve is slow.

How I tested whether js was updating on the browser:  I had a never-ending loop, and when I removed it from my js file, it wouldn't go away.

With loop:

```
let newGame = function() {
  $('.board').children().on('click', function() {
    while (turnCount <= 8) {
      if ($(this).hasClass('disable')) {
        alert('Select a different box!');
      } else if (turnCount === 0) {
        $(this).text('x');
        $(this).last().addClass('disable');
        turnCount++;
      } else {
        $(this).text('o');
        $(this).last().addClass('disable');
        turnCount++;
      }
    }
  });
};
```

Without loop:

```
let newGame = function() {
  $('.board').children().on('click', function() {

      if ($(this).hasClass('disable')) {
        alert('Select a different box!');
      } else if (turnCount === 0) {
        $(this).text('x');
        $(this).last().addClass('disable');
        turnCount++;
      } else {
        $(this).text('o');
        $(this).last().addClass('disable');
        turnCount++;
      }

  });
};
```

**Comment by RealWeeks** [comment]
I'm going to give you a hack solution which will probably save me about an hour debugging and you sitting there.  Goto the repo we used today or the template repo, use that instead. paste your code/markup/styles in there... Plus you can install bootstrap-sass too.

**Comment by jrhorn424** [comment]
I updated Celena's template installation in her project and nuked `node_modules`. The problem is still persisting. No JS file triggers a rebuild. I can't reproduce this issue on my machine.

I'll continue doing research tonight. I'm willing to pick up with debugging tomorrow as well, but I also welcome others to give debugging a shot.

**Comment by RealWeeks** [comment]
@seatuna was this issue resolved?  If so please close, if not please comment further on how we can help.

**Comment by jrhorn424** [comment]
This was a bug with `fsevents` on OS X. We followed every [debugging step](http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai) suggested, but for us the key was renaming every folder in the file hierarchy from the home folder down to the project.

For example, for a path of `$HOME/wdi/projects/ttt`, start by renaming `wdi -> wdi2 -> wdi`. Then, rename `projects`, and finally rename `ttt`. Restart `grunt serve` and try to change something in a JS or Sass file.
