### ISSUE TITLE
ajax issues

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#101]
Getting an error when trying to sign-up:

Object {readyState: 4, responseText: "Cannot POST /undefined/sign-up↵", status: 404, statusText: "Not Found"}

Not sure what an undefined sign-up means

**Comment by Jcornmanhomonoff** [comment]
Getting same error with sign-in

**Comment by laurenfazah** [comment]
Looks like part of the URL you're hitting is undefined. Try to find where that's concatenated together and trace your steps backwards.

**Comment by RealWeeks** [comment]
Undefined means you didn't properly define something, find that line and try putting a debugger before of after it and trace your steps backwards like @laurenfazah said.

**Comment by Jcornmanhomonoff** [comment]
I'm not sure what is undefined. I checked where I'm concatenating my urls together and I don't see any errors.

**Comment by RDegnen** [comment]
post the code for where you are concating them

**Comment by laurenfazah** [comment]
Well, what should be in place of the undefined part of the URL? Figuring that out should lead you towards finding out where undefined is coming from.

**Comment by Jcornmanhomonoff** [comment]
``` js
const app = require('../app-data.js');

const signUp = (success, failure, data) => {
  $.ajax({
    method:'POST',
    url: app.api + '/sign-up',
    data,
  })
  .done(success)
  .fail(failure);
};

const signOut = (success, failure) => {
  $.ajax({
    method:'DELETE',
    url: app.api + '/sign-out/' + app.user.id,
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  })
  .done(success)
  .fail(failure);
};

const signIn = (success, failure, data) => {
  // debugger;
  $.ajax({
    method:'POST',
    url: app.api + '/sign-in',
    data: data,
  })
  .done(success)
  .fail(failure);
};


module.exports = {
  signUp,
  signIn,
  signOut,
};
```

**Comment by RDegnen** [comment]
what is app.api returning if you console.log it

**Comment by Jcornmanhomonoff** [comment]
Had to reference app.app.api or export app as single object
