### ISSUE TITLE
error on console log

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#105]
i'm having an issue with my sign up api -

I'm getting this error in my console.log

```
client?cd17:5Uncaught TypeError: Cannot read property 'replace' of null(anonymous function) @ client?cd17:5(anonymous function) @ client?cd17:96__webpack_require__ @ bootstrap 20c717b…:50(anonymous function) @ bootstrap 20c717b…:93__webpack_require__ @ bootstrap 20c717b…:50(anonymous function) @ bootstrap 20c717b…:93(anonymous function) @ bootstrap 20c717b…:93
index.js:14asdfasdf
```

**Comment by RealWeeks** [comment]
What are you console.log(ing)?

**Comment by RDegnen** [comment]
what are you trying to console.log

**Comment by pvdri** [comment]
consoling on my chrome browser

**Comment by RealWeeks** [comment]
Not where (browser vs atom), what (object/...). paste in the code where you have the console.log.

**Comment by pvdri** [comment]
const addHandlers = () => {

  $('#sign-up').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this);
    console.log(data);
    authApi.signUp(authUi.signupSuccess, authUi.failure, data);
  });

**Comment by pvdri** [comment]
'use strict';

const signUp = (success, failure, data) => {
  $.ajax({
    'method': 'POST',
    'url': 'http://tic-tac-toe.wdibos.com/sign-up',
     data,
  }).done(success)
  .fail(failure);
};

**Comment by pvdri** [comment]
'use strict';

const app = require('../app-data.js');

const signupSuccess = (data) => {
  app.user = data.user;
};

const success = (data) => {
  console.log(data);
};

const failure = (error) => {
  console.error(error);
};

module.exports = {
  failure,
  success,
  signupSuccess,
};

**Comment by RealWeeks** [comment]
you have multiple console.logs in the snippits which one is the error referring to?

**Comment by pvdri** [comment]
when i enter my email, password, and password confirmation, this error shows up on my browser inspect console

**Comment by RealWeeks** [comment]
tabled until linter errors corrected

**Comment by pvdri** [comment]
linter cleared

**Comment by RealWeeks** [comment]
resolved console.log issue.  Issue now with data being passed.
