### ISSUE TITLE
Class

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#106]
Curious how to reference player class....hard to explain. Visuals help...

**Comment by RDegnen** [comment]
you have to be more specific

**Comment by Jcornmanhomonoff** [comment]
if ($('#cell1').hasClass('player-o')

Where player-o is, I want it to be either o or x

**Comment by RealWeeks** [comment]
So you want to change a class? append a class? I'm not sure what your want to do .hasClass already references a class

**Comment by Jcornmanhomonoff** [comment]
I'm trying to clarify a winning function. I want to say is either player fulfills the following, then they win.

``` js
if ($('#cell1').hasClass('player-o') && $('#cell2').hasClass('player-o') && $('#cell3').hasClass('player-o')
```

**Comment by RealWeeks** [comment]
That looks as if it should work, what are you trying to change? Have you tested this? what happens?

**Comment by Jcornmanhomonoff** [comment]
It does work. But I want it to be player-o or player-x instead of specifying one. I don't want to have to write two separate functions and then a third to choose between the two.

**Comment by J-Weeks** [comment]
have you tried the or operator (||)

**Comment by RealWeeks** [comment]
You have to make a really big if/else or write that separate function... maybe find a coding magic lamp that does it for you?

**Comment by RealWeeks** [comment]
Possible other solutions: restructure your code.  Either way there is not magic answer.

**Comment by Jcornmanhomonoff** [comment]
Making 2 functions
