### ISSUE TITLE
sign up

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#107]
my sign up is currently frozen and I'm receiving any error messages

**Comment by RealWeeks** [comment]
What does frozen mean?

**Comment by pvdri** [comment]
there's no action

**Comment by RealWeeks** [comment]
so when you click submit nothing happens? or the page won't budge? or the page refreshed with that data gone? Please elaborate.

**Comment by pvdri** [comment]
nothing happens - nothing is reported in the console

**Comment by RDegnen** [comment]
Make sure the right function is being called

**Comment by RealWeeks** [comment]
^ to add on to what @RDegnen said put a debugger in the function and when testing it out in the browser notice if it hits the debugger you put in or not

**Comment by pvdri** [comment]
it is hitting the debugger

**Comment by RealWeeks** [comment]
Cool so it's getting into the function. can you paste the snippet? dont forget to wrap you code in 3 backticks (```)

**Comment by pvdri** [comment]
```

'use strict';

const getFormFields = require('../../../lib/get-form-fields');

const authApi = require('./api');
const authUi = require('./ui');

const addHandlers = () => {

  $('#sign-up').on('submit', function (event) {
    event.preventDefault();
    debugger;
    let data = getFormFields(this);
    authApi.signUp(authUi.signupSuccess, authUi.failure, data);
  });

  $('#log-in').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this);
    authApi.signIn(authUi.signinSuccess, authUi.failure, data);
  });


  // $('#start').on('submit', function (event) {
  //   event.preventDefault();
  //   let data = getFormFields(this);
  //   authApi.signUp(authUi.success, authUi.failure, data);
  // });

```

**Comment by RDegnen** [comment]
post your sign-up ajax request

**Comment by RealWeeks** [comment]
when your debugger hits what is the value of "this"

**Comment by pvdri** [comment]
not sure what you mean about 'this''

ajax request..

``` js
const signUp = (success, failure, data) => {
  event.preventDefault();
  $.ajax({
    method: 'POST',
    url: 'http://tic-tac-toe.wdibos.com/sign-up',
    data: data,
  }).done(success)
  .fail(failure);
};
```

**Comment by RDegnen** [comment]
Good thats what I wanted to see. What is the error message you get when you send that post request to the server? Also you don't need `event.preventDefault()` in your function

**Comment by pvdri** [comment]
client?cd17:5Uncaught TypeError: Cannot read property 'replace' of null(anonymous function) @ client?cd17:5(anonymous function) @ client?cd17:96__webpack_require__ @ bootstrap 33da82d…:50(anonymous function) @ bootstrap 33da82d…:93__webpack_require__ @ bootstrap 33da82d…:50(anonymous function) @ bootstrap 33da82d…:93(anonymous function) @ bootstrap 33da82d…:93

**Comment by RealWeeks** [comment]
@pvdri this looks like a repeat of #118 and possibly #102 please close unless these are different issues.

**Comment by RDegnen** [comment]
Please close
