### ISSUE TITLE
GIT confusion Unstored work

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/game-project#11]
My current problem is I have done work on a branch and the work is not complete but i would like to save it and continue back on it later. I am afraid I will lose my work. I need to change my current branch and create a new one OR open a current one. Damn ADHD!

**Comment by gaand** [comment]
You can commit the work with a comment indicating it's incomplete and then create a new branch.

If the work is in separate files losing your work is not a huge risk.

**Comment by GA-MEB** [comment]
You can also use `git stash` if you don't want to commit it yet - for instance, if it's not working.
https://git-scm.com/book/en/v1/Git-Tools-Stashing

**Comment by RealWeeks** [comment]
@erdesi90562 is this resolved?

**Comment by edesilets** [comment]
Just half resolved. I need to recover my stash.

**Comment by edesilets** [comment]
http://www.gitguys.com/topics/temporarily-stashing-your-work/

Resolved.
