### ISSUE TITLE
Array storage

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#110]
Having trouble understanding where to begin with the arrays that we're using to store x's and o's. Any direction would be helpful.

**Comment by RealWeeks** [comment]
Use arrays to store x's and o's

**Comment by RealWeeks** [comment]
Seriously though, have you tried yet? this is too general. What about storage with array's do you need help understanding?

**Comment by Jcornmanhomonoff** [comment]
I don't necessarily understand what I'm doing with it.

**Comment by Jcornmanhomonoff** [comment]
I understand that there's an empty array and we need to store our clicks in the array. I'm not sure how to do that.

**Comment by RDegnen** [comment]
You can always access an index of an array and assign it a new value

**Comment by RealWeeks** [comment]
How do you store anything in an array? Seriously give me an example of how to store something in an array at a specific index

**Comment by Jcornmanhomonoff** [comment]
push but that adds to the end

**Comment by Jcornmanhomonoff** [comment]
Getting help elsewhere
