### ISSUE TITLE
Request Review and Discussion about Internet Play

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/game-project#115]
Thanks!

**Comment by RealWeeks** [comment]
@gaand

**Comment by gaand** [comment]
Let's meet at 11:15.  In the workspace, or elsewhere if you prefer.

**Comment by soynog** [comment]
Great, I'll come find you in a few minutes. Thanks!

**Comment by gaand** [comment]
Wait to close until we meet.  This way I'm assigned to the open issue.

**Comment by laurenfazah** [comment]
@soynog could you close this if you've met with @gaand?

**Comment by soynog** [comment]
Oh, right! Sorry, slipped my mind.

**Comment by soynog** [comment]
I put resource-watcher.js in my repo and it's throwing me a linter error: It says "EventSource is not defined". Should I be worried about that?

Here's the offending line of code:

``` js
  var es = new EventSource(url);
```

**Comment by RealWeeks** [comment]
@soynog Please Open a new issue for this

**Comment by soynog** [comment]
okeydokey
