### ISSUE TITLE
Ui issues

### ISSUE THREAD

**Issue by natdjerf** [ga-wdi-boston/game-project#119]
I keep coming into an issue with my UI; after sign in, if I use jQuery to hide the button, I get post errors for no token for create game, though it's clear a game has been created in the console log, with a valid token and id. If I remove the hide feature, I can successfully create a game. 

Right now, the hide/show buttons are on my ui success checkers.

**Comment by RDegnen** [comment]
Can you post the code where you are hiding the button?

**Comment by RealWeeks** [comment]
Bootstrap has a class called either hide or hidden which does exactly what you think it does.  You can append this class to the desired place.  This is probably a better way and will most likely solve your problem.

**Comment by natdjerf** [comment]
I only use bootstrap for the nav bar. 
The below is working in terms of hiding/showing at the right time but just causing the post issue.

``` js
const signInSuccess = (data) => {
  app.user = data.user;
  $('#create-game').show();
  $('#sign-in').hide();
  $('#sign-up').hide();
  console.log(data);

};
```

**Comment by RealWeeks** [comment]
@natdjerf Bootstrap is included in the template meaning you have accesses to it's classes and methods throughout your project.  I think this is a better way.

**Comment by RDegnen** [comment]
Also, I don't think that signInSuccess is the best place to access the DOM from, maybe move that code to your index.js file?

**Comment by RealWeeks** [comment]
http://stackoverflow.com/questions/18568736/how-to-hide-element-using-twitter-bootstrap-3-and-show-it-using-jquery

**Comment by natdjerf** [comment]
Got it, I will try making a new file to house it. 

But, now when I removed all the hide requests, now I am getting fails only when creating a game after signing up a new user. I am seeing successfully signed up a new user, but when I click created game it's saying unauthorized? 

``` js
const signUpSuccess = (data) => {
  app.user = data.user;
  console.log(data);
};

const signInSuccess = (data) => {
  app.user = data.user;
  console.log(data);
};

const signOutSuccess = (data) => {
  app.user = null;
  console.log(data);
  console.log('signed out');
};

const changePasswordSuccess = () => {
  console.log('Password changed');
};

const createGameSuccess = (data) => {
  app.game = data.game;
  console.log(data);
};
```

Showing a new user created, but a token access denied when creating a game?
ui.js:7 Object {user: Object}user: Object__proto__: Object
events.js:39 game started
jquery.js:9203 POST http://tic-tac-toe.wdibos.com/games 401 (Unauthorized)send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684createGame @ api.js:48(anonymous function) @ events.js:38jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
ui.js:42 Object {readyState: 4, responseText: "HTTP Token: Access denied.↵", status: 401, statusText: "Unauthorized"}

**Comment by laurenfazah** [comment]
Have you made progress with this? jQuery's `hide()` is close to CSS's `display:none` in that it removes elements from the DOM. Therefore form data could be removed from your access once they're hidden.

**Comment by laurenfazah** [comment]
Are you sending the token in an authorization header?

**Comment by natdjerf** [comment]
Yes. It works when after signing in, and after a user has been created, but not when a user signs up and creates a game in one swoop:
Is timing a factor? I'm seeing new user token created right away, which is what is being called in the create game post. And it's successful if the user has been created.

``` js
const createGame = (success, failure, data) => {
  $.ajax({
    method: 'POST',
    url: app.api + '/games',
    headers:{
      Authorization : 'Token token=' + app.user.token,
    },
    data,
  }).done(success)
    .fail(failure);
  };
```

**Comment by natdjerf** [comment]
@laurenfazah No I removed it all for now. I'll try the display none or bootstraps methods when I figure this  out.

**Comment by natdjerf** [comment]
resolved! We think. Sign up doesn't return a token :expressionless: so you have to sign up AND sign in. 

thanks!

**Comment by RealWeeks** [comment]
@natdjerf please close if resolved.
