### ISSUE TITLE
AJAX data

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#121]
Having difficulty determining how to use/read this. Trying to create new game.

``` js
{
  "game": {
    "id": 3,
    "cells": ["","","","","","","","",""],
    "over": false,
    "player_x": {
      "id": 1,
      "email": "and@and.com"
    },
    "player_o": null
  }
}
```

**Comment by laurenfazah** [comment]
The API docs state that this is the response body expected from a successful post call.

**Comment by laurenfazah** [comment]
The docs also state: "The create action expects a POST with an empty body (e.g '' or '{}' if JSON)."

**Comment by Jcornmanhomonoff** [comment]
Do we need to define what a game is somewhere in our code because we need to reference it in the api.js file?

**Comment by laurenfazah** [comment]
You should have a place to save your game response once it's returned from the AJAX request, the same way you should have set up with your sign in for users. All you should need before making a POST request for a new game is that user 1 signed in.
