### ISSUE TITLE
css float issue

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#122]
i have forms set with two classes. One for what the form does exactly, for example class="sign-out-p1", and another class for just the player:  class="p1"   So its looks like class="sign-out-p1" "p1". When i try to float right with "sign-out-p1" in css it works fine but when i try to float all items for a player right or left through using the more general class "p1" it doesnt work.

**Comment by louarnos** [comment]
nevermind.

**Comment by louarnos** [comment]
Jk now its putting items below each other even when I label the classes class="sign-in-p1 p1"

**Comment by louarnos** [comment]
I mean i could float every form field for each player. Just seems silly to do it that way when I want all p1 on left and all p2 on right

**Comment by laurenfazah** [comment]
So multiple classes should always be separated by a space within the one class attribute value. For example: class="class1 class2 class3".

**Comment by louarnos** [comment]
Didnt assign classes correctly.
