### ISSUE TITLE
Switch turns issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#123]
having trouble with my appproach to switching turns between players.

**Comment by RealWeeks** [comment]
What have you tried?

**Comment by ghost** [comment]
I had it in traditional javascript using document.turn between functions. That's no longer rendering as you predicted before. Now I'm trying to adapt the switch using jquery.

**Comment by RealWeeks** [comment]
can you paste any code you've been working on so I can see what you've done and we can go from there.

**Comment by laurenfazah** [comment]
Don't overcomplicate it for yourself - feel free to use something you're comfortable with. Perhaps increasing a number value on each turn and using that counter to determine whose turn it is.

**Comment by ghost** [comment]
gotcha. thanks!
