### ISSUE TITLE
Game update failure

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/game-project#124]
I'm getting a 400 error when I try to update the game. Here is my AJAX call 

``` js
const updateGame = (success, failure) => {
 $.ajax({
   method: 'PATCH',
   url: app.api + 'games/' + resources.gameID,
   processData: false,
   data: {
  "game": {
    "cell": {
      "index": resources.sendIndex,
      "value": resources.sendValue
    },
    "over": false
  }
},
   headers:{
     Authorization: "Token token=" + users.player1.authToken,
   }
 }).done(success)
 .fail(failure);
};
```

'resources'  is a file where I have some variables and functions I wanted to keep global, and when a user signs in I save their token to a user object - users.player1.authToken,

this is the error I get back 

```
Object {readyState: 4, responseText: "", status: 400, statusText: "Bad Request"
```

and it works when I send it to httpbin, so theres that

**Comment by laurenfazah** [comment]
Looks like there could be a typo in the Authorization region...

**Comment by laurenfazah** [comment]
Are you positive `users.player1.authToken` is set?

**Comment by philschoof** [comment]
Yep, it console.logs

**Comment by gaand** [comment]
``` diff
-    processData: false,
```

There's no need to send `over: false`.  Send `over: true` when the game ends.

Also, the quotes in the data object should be generating a linter warning that you should correct.

**Comment by RDegnen** [comment]
What are the values of `resources.sendIndex` and `resources.sendValue`?

**Comment by philschoof** [comment]
There actually aren't any linter errors on the page. How should I change the quotes?

resources.sendIndex is the index for the placed piece, and resources.sendValue is the string "X" or "O"

**Comment by laurenfazah** [comment]
What does your AJAX request look like now?

**Comment by philschoof** [comment]
```
 $.ajax({
   method: 'PATCH',
   url: app.api + 'games/' + resources.gameID,
   processData: false,
   data: {
  "game": {
    "cell": {
      "index": resources.sendIndex,
      "value": resources.sendValue
    },
  }
},
   headers:{
     Authorization: "Token token=" + users.player1.authToken,
   }
 }).done(success)
 .fail(failure);
```

**Comment by laurenfazah** [comment]
Ah, @gaand's comment was to remove `processData: false` as well.

**Comment by philschoof** [comment]
that did it. thanks
