### ISSUE TITLE
reading id

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#126]
Hello - I'm getting an error that it can't read the app.user.id

const signOut = (success, failure) => {
  event.preventDefault();
  $.ajax({
    method: 'DELETE',
    url: app.api + '/sign-out/' + app.user.id,
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  }).done(success)
  .fail(failure);
};

**Comment by laurenfazah** [comment]
Have you console.logged `app.user.id`? What is it coming back as?

**Comment by RealWeeks** [comment]
check your syntax

**Comment by pvdri** [comment]
api.js:27 Uncaught TypeError: Cannot read property 'id' of undefinedsignOut @ api.js:27(anonymous function) @ events.js:41jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549

**Comment by RealWeeks** [comment]
what's on line 27 in api.js?

**Comment by pvdri** [comment]
url: app.api+'/sign-out/'+app.user.id,

**Comment by RealWeeks** [comment]
Your error is in this line, use debuggers to test out what the app object is

**Comment by laurenfazah** [comment]
If it's saying it cannot read `id` of `undefined,  it is likely that`app.user` is what is undefined.

**Comment by pvdri** [comment]
ok thank you - will look into this...

**Comment by laurenfazah** [comment]
Discussed with Arif - this is outside the scope of the core requirements of the project, so we are closing.
