### ISSUE TITLE
Starting AJAX

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#127]
I've been trying to start writing the AJAX and I have no idea where to begin.  I'd like to begin with the Sign Up form, but don't know how to go about that.

**Comment by RDegnen** [comment]
You can always refer to the AJAX lessons from last week

**Comment by laurenfazah** [comment]
Yup, should look very similar to the flow we had for api-token-auth.

**Comment by susandaiute** [comment]
Doing that now, thanks!

**Comment by susandaiute** [comment]
Ok, I think I'm in a better spot now, but I'm having trouble making sure all the require file paths are right.
For example, in events.js I have 

`const getFormFields = require('../../../lib/get-form-fields');`

but the folders etc. that I have set up look more like:
tictactoe/assets/scripts/events.js  and
tictactoe/lib/get-form-fields.js

To require get-form-fields from events.js would I require like:
`const getFormFields = require(.../lib/get-form-fields');`?

**Comment by RealWeeks** [comment]
there is an easy way to test this, put in a debugger right after it then in your chrome console try to call it.  It would usually throw an error anyway if something wasn't required right and you were trying to use it.

**Comment by RDegnen** [comment]
close `const getFromFields = require('../../lib/get-form-fields');` I think would work

**Comment by susandaiute** [comment]
I think it's all set!  Thanks!!
