### ISSUE TITLE
When I try to start a new game after having already played one, game thinks user1 is not logged in.

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#129]
It may be one of my conditionals for starting the game. Here are my actions when the game is complete:

```
  if (win) {
    $('.title').text(' ' + winner + ' Wins!!!');
    game.inProgress = false;
    console.log(winner + ' wins!!!');
  }else if (tie) {
    $('.title').text('Its a Tie!!!');
    game.inProgress = false;
    console.log('Its a tie!!!');
  }
};

```

And here are my actions on starting a new game: 

```
$('#start-game').on('submit', function (event) {
    event.preventDefault();
    if (user1.user && (!game.inProgress)) {
      $('.box .marked').removeClass('marked');
      $('.box').text('');
      createGame.createGame(ui.gameCreationSuccess, ui.gameCreationFailure);
      game.inProgress = true;
    }else {
      $('h3').css('visibility', 'visible');
      setTimeout(function () {
        $('h3').css('visibility', 'hidden');
      }, 1000);
    }
  });
};
```

Once a new game has started this is how the game reacts when a box is clicked:

```
  $('.box').on('click', function (event) {
    event.preventDefault();
    if (user1.user && (!$(this).hasClass('marked')) && game.inProgress) {
      let $currentBox = $(this);
      play.play($currentBox);
    }else if (!user1.user) {
      $('h3').css('visibility', 'visible');
      setTimeout(function () {
        $('h3').css('visibility', 'hidden');
      }, 1000);
    }
  });
```

I'm not convinced my remove marked class actions is working correctly.

**Comment by RealWeeks** [comment]
After you complete a game logged in does it recognize user1 as being logged in?

**Comment by RealWeeks** [comment]
When you've determined that put a debugger right after you open up the start-game click handler, is user1 logged in there?

**Comment by RealWeeks** [comment]
``` js
  if (win) {
    $('.title').text(' ' + winner + ' Wins!!!');
    game.inProgress = false;
    console.log(winner + ' wins!!!');
  }else if (tie) {
    $('.title').text('Its a Tie!!!');
    game.inProgress = false;
    console.log('Its a tie!!!');
  }
};
```

does this have an else? are your linters clean?

**Comment by louarnos** [comment]
If I console log user1 when I declare the winner it knows user1s info

**Comment by RDegnen** [comment]
whats the exact error message?

**Comment by louarnos** [comment]
all clean.... there is no error message. My second condition executes saying printing on the screen that login is needed for gameplay.... thats the showing of h3

**Comment by louarnos** [comment]
It acts really funny. hard to explain. Some tiles are markable. others arnt. Which leads me to believe the remove class statement is operating correctly.

**Comment by louarnos** [comment]
no else on that jason

**Comment by louarnos** [comment]
is that bad?

**Comment by RealWeeks** [comment]
put the debugger after you open up sign-in, is the user logged in then?

**Comment by RDegnen** [comment]
Im thinking it must be in your conditional if user1 infact exists

**Comment by louarnos** [comment]
I'm not sure where you want the debugger. I'm console logging user1 in my signInSuccess. seems fine.

**Comment by RealWeeks** [comment]
@RDegnen but after he plays the game the user object still exists, I thought the problem is at some point the user object gets removed

**Comment by louarnos** [comment]
Also console logging at a win or a tie shows user1 exists.

**Comment by RealWeeks** [comment]
Issue targeting selector

**Comment by louarnos** [comment]
thanks json {}
