### ISSUE TITLE
issue starting new game

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#130]
I'm trying to pull a function from index.js and send it via ajax.... i've tried to console.log the data but I'm not getting anything

  $('#start').on('submit', function (event) {
    event.preventDefault();
    let data = startover.gametatus();
    console.log(data)
    authApi.signUp(authUi.success, authUi.failure, data);
  });

**Comment by laurenfazah** [comment]
Is `#start` the ID on a form?

**Comment by pvdri** [comment]
yes

**Comment by RDegnen** [comment]
try putting a debugger in there to see if it fires when you call the submit handler

**Comment by pvdri** [comment]
nope - the debugger is not firing

**Comment by RealWeeks** [comment]
Please paste in your form

**Comment by RDegnen** [comment]
So that means that your not properly firing that event, or your JS can't capture it

**Comment by RealWeeks** [comment]
Also, is the DOM ready when this fires?

**Comment by pvdri** [comment]
yes, I believe the dom is ready, because other things are working......  but I'm not sure why i'm not properly firing
