### ISSUE TITLE
Undefined function, AJAX

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#133]
In my index.js file, I have:
`const authEvents = require('./events.js');`

`
$(document).ready(function() {
  authEvents.addHandlers();
});`

When I run the page, I get the error that authEvents is undefined.

**Comment by susandaiute** [comment]
Never mind, that's fixed.  But now it's saying api is not defined.

``` javascript
const getFormFields = require('../../lib/get-form-fields');
const authEvents = require('./events.js');
const libraryApi = require('./api');
const ui = require('./ui');
require('./example');
require('./gameplay');

//Sign Up

$(() => {
  $('#signUpForm').on('submit', function (e) {
    let data = getFormFields(this);
    e.preventDefault();
    let text = $('#exampleInputEmailsignUp').val();
    api.myRequest(data, ui.success, ui.failure);
  });
});
```

**Comment by gaand** [comment]
Careful with identifiers:

``` diff
- const libraryApi = require('./api');
+ const api = require('./api');
```

**Comment by susandaiute** [comment]
Would it be possible to schedule a one-on-one regarding AJAX?

**Comment by gaand** [comment]
Is your request in response to my comment?

If not, is this issue closed?  AJAX is a large topic, can you be more specific?

**Comment by susandaiute** [comment]
Regarding your comment, I made the fix you suggested, but now it it saying that `api.myRequest` is not a function.

To narrow down on Ajax, I'm having trouble getting the Sign Up to work.

**Comment by susandaiute** [comment]
The complete collection of current errors:

index.js:37 Uncaught TypeError: api.myRequest is not a function(anonymous function) @ index.js:37jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
jquery.js:9203 POST http://tic-tac-toe.wdibos.com/sign-up send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684signUp @ api.js:6(anonymous function) @ events.js:12jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
localhost/:1 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
ui.js:20 Object {readyState: 0, status: 0, statusText: "error"}

**Comment by gaand** [comment]
Okay.  So far, these aren't AJAX issues.

Are you exporting `myRequest` from the file `./api`?

**Comment by susandaiute** [comment]
Actually, it's from `forms.md`.  I just added a require.  I'll see if it works.

**Comment by susandaiute** [comment]
So I just added `require('../../spec/forms.');
`
and everything broke.

**Comment by susandaiute** [comment]
Worked!
