### ISSUE TITLE
Button elements changing position when text is present or not

### ISSUE THREAD

**Issue by cuprous** [ga-wdi-boston/game-project#134]
I'm adding and removing text from <button> elements as a way to handle the playing board. The buttons have fixed dimensions (100px x 100px or something like that), but when text is added to or taken away from the button, the button changes position vertically.

I can't seem to troubleshoot this or determine what is causing the behavior.

Any thoughts?

Thanks.

**Comment by RDegnen** [comment]
It could be your padding, trying messing around with the box model and the `box-sizing:` css property

**Comment by cuprous** [comment]
The buttons maintain the same size before and after they move. It doesn't appear to be related to the margin setting, either. I can't tell what is causing the position to change using the inspect element function in Chrome.

Update: it has to do with the line-height property. Trying to deal with this now.

**Comment by RealWeeks** [comment]
I think @louarnos had a similar problem in #125

**Comment by cuprous** [comment]
Thanks. I'm going to go with an approach that I knew worked earlier. Just going to avoid the bootstrap column deal and float my buttons in a fixed-width container so they end up in a 3x3 configuration. It doesn't solve this specific issue.

Can I close this out now?

**Comment by RealWeeks** [comment]
Yep

**Comment by cuprous** [comment]
Looked at #125 and ensured line-height was set to button height, but the jumping behavior is still happening.

Update: when comparing the buttons with and without text in the Chrome inspector, there seem to be no differences in attributes aside from the lack of text content.

**Comment by cuprous** [comment]
I think it has to do with bootstraps treatment of buttons, possibly?

I'm just going to go with floated divs to hold my board slots rather than buttons.
