### ISSUE TITLE
Large linter errors showing up in atom

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#135]
everytime I switch my tab in atom really large errors show up in the top right of my page. They say problems are reported

**Comment by RDegnen** [comment]
you might need to update your linter packages

**Comment by gaand** [comment]
You probably also want to quit atom and restart from the command line.

**Comment by louarnos** [comment]
ok should i update esformatter? Its the only thing that says it needs an update.

**Comment by RealWeeks** [comment]
No, try reopening atom from the command line and see if it's the same issue

**Comment by louarnos** [comment]
seems to be gone.
