### ISSUE TITLE
Project Requirements Check?

### ISSUE THREAD

**Issue by cuprous** [ga-wdi-boston/game-project#138]
@gaand May I have a sit down with you to check if my project in its current state meets the satisfactory level requirements for the project?

**Comment by gaand** [comment]
Happy to meet and have you walk me through it.

Before that, here's a checklist:
- [ ] turn based
- [ ] correctly determines win, lose, draw
- [ ] sign-up
- [ ] sign-in 
- [ ] sign-out 
- [ ] change-password
- [ ] create game on api
- [ ] update game on api
- [ ] retrieve game or games from api and display
- [ ] deployed to GitHub pages

If you think those are all checked off then we'll set a time.  Okay?

**Comment by cuprous** [comment]
I think all of those are complete, but I'll need your input whether the final requirement (retrieve game or games) is met.

Does 2:45 PM work for you?

**Comment by gaand** [comment]
2:50?  Done.

**Comment by cuprous** [comment]
@gaand I'm good to meet whenever you are.
