### ISSUE TITLE
Project Requirements Check

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#139]
Would like to see if i meet all the requirements. Also have questions about lesson hosting on github. Is there documentation for this?

**Comment by RealWeeks** [comment]
Yes, you went over it with @RDegnen in html-css

**Comment by louarnos** [comment]
The day we did bootstrap sass? All the days run together.

**Comment by laurenfazah** [comment]
https://github.com/ga-wdi-boston/html-css

**Comment by louarnos** [comment]
thank you

**Comment by RealWeeks** [comment]
@louarnos where are you now? did you still want that check?

**Comment by louarnos** [comment]
sure

**Comment by louarnos** [comment]
need to update API with game over. Make get user games print # of games. and push to gh-pages
