### ISSUE TITLE
404 When I go to my gh url for my game

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#142]
I branched my gh-pages branch off of a fully updated master branch, which I believe caused issues.

**Comment by louarnos** [comment]
I'm bad and I feel bad.

**Comment by RealWeeks** [comment]
What steps did you take?

**Comment by louarnos** [comment]
all of them

**Comment by louarnos** [comment]
lol

**Comment by RealWeeks** [comment]
list them

**Comment by RealWeeks** [comment]
everything you wrote in your terminal

**Comment by louarnos** [comment]
ok its up without styling now.... which means i probably didnt comment the gitignore correclty

**Comment by louarnos** [comment]
k all done
