### ISSUE TITLE
typo on game-project-api page?

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#143]
there is no ID afterpaatch

Verb    URI Pattern Controller#Action
POST    /sign-up    users#signup
POST    /sign-in    users#signin
DELETE  /sign-out/:id   users#signout
PATCH   /change-password    users#changepw
GET /games  games#index
POST    /games  games#create
GET /games/:id  games#show
PATCH   /games/:id  games#update
GET /games/:id/watch    games#watch

**Comment by RealWeeks** [comment]
Can you elaborate? I don't understand. I don't think theirs a typo

**Comment by pvdri** [comment]
there is no ID after password....

also, can't get my change password to work

Object {credentials: Object, submit: "change password"}
tic-tac-toe.wdibos.com/change-password/397:1 PATCH http://tic-tac-toe.wdibos.com/change-password/397 
localhost/:1 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/change-password/397. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
ui.js:20 Object {readyState: 0, status: 0, statusText: "error"}failure @ ui.js:20fire @ jquery.js:3187self.fireWith @ jquery.js:3317done @ jquery.js:8787(anonymous function) @ jquery.js:9143

**Comment by gaand** [comment]
You are correct:

``` diff
- PATCH /change-password users#changepw
+ PATCH /change-password/:id users#changepw
```

**Comment by RealWeeks** [comment]
Please, one issue per thread @pvdri this helps up keep questions/issues isolated so if other developers have the same issue they can search closed issues.  Please close this and open a new one with your question.
