### ISSUE TITLE
change password

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#145]
issues getting my change password to work...

Object {credentials: Object, submit: "change password"}
tic-tac-toe.wdibos.com/change-password/397:1 PATCH http://tic-tac-toe.wdibos.com/change-password/397 
localhost/:1 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/change-password/397. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
ui.js:20 Object {readyState: 0, status: 0, statusText: "error"}failure @ ui.js:20fire @ jquery.js:3187self.fireWith @ jquery.js:3317done @ jquery.js:8787(anonymous function) @ jquery.js:9143

**Comment by laurenfazah** [comment]
How is this different from #141? If they are not different, one needs to be closed.
