### ISSUE TITLE
resource-watcher.js has an error

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/game-project#146]
I put resource-watcher.js in my repo and it's throwing me a linter error: It says "EventSource is not defined". Should I be worried about that?

Here's the offending line of code:

``` js
  var es = new EventSource(url);
```

**Comment by gaand** [comment]
Yes, because it's a linter error.  No, because it's not an actual error.

I've updated the source file to suppress this issue.

**Comment by soynog** [comment]
Excellent. Thx!
