### ISSUE TITLE
Online multiplayer question

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/game-project#148]
In the API docs, it says:

> Because watch implements a streaming source of data, we'll use a wrapper around the html5 object EventSource to handle the events sent.

Does the wrapper go in its own script file, and would the GameWatcher go with it?  I'm just unclear on how to get started structuring this code in with the rest of what I have.

**Comment by gaand** [comment]
Do you mean the definition of resourceWatcher, or the object it returns?

**Comment by sjf125** [comment]
Just edited my comment

**Comment by gaand** [comment]
Save the resource watcher file in your project and then add

``` js
module.exports = resourceWatcher;
```

to the end.  `require` the function wherever you're using it to create the gameWatcher, e.g.

``` js
const resourceWatcher = require('./resource-watcher-0.1.0.js');
```

PS - I think it's better to clarify in new comments rather than editing existing comments.

**Comment by sjf125** [comment]
ok thank you!
