### ISSUE TITLE
Trouble with git hub pages

### ISSUE THREAD

**Issue by olivia-leach** [ga-wdi-boston/game-project#151]
Did the following, with no errors, but there's nothing on my github.io site.

```
git branch gh-pages
git checkout gh-pages
git merge master
```

In .gitignore file, deleted the lines *bundle.js and vendor.js

```
grunt build.
```

Added & commit

```
git push origin gh-pages
```

Site looks like this: http://olivia-leach.github.io/

:(

**Comment by laurenfazah** [comment]
Is that the URL it is telling you it's at in the repository's settings?

**Comment by olivia-leach** [comment]
ah-ha! no it wasn't. thank you!!
