### ISSUE TITLE
Broken images on github pages

### ISSUE THREAD

**Issue by olivia-leach** [ga-wdi-boston/game-project#152]
But they work on my localhost.

Not all the images are broken. Just a few.

**Comment by laurenfazah** [comment]
Image links, please?

**Comment by laurenfazah** [comment]
And as a bonus, could you paste the console error for the broken image link(s)?

**Comment by olivia-leach** [comment]
https://www.dropbox.com/s/9bja9jhj87jxdcn/Screenshot%202016-04-07%2016.44.10.png?dl=0

**Comment by laurenfazah** [comment]
Oh sorry, the image tag with the link in it.

**Comment by olivia-leach** [comment]
``` js
    $(this).prepend('<img id="marker" class="marker" src="assets/images/' + app.turn + '.png" />');
```

**Comment by olivia-leach** [comment]
is it because i just realized the quotes are wrong around the src image?

**Comment by laurenfazah** [comment]
Likely a case sensitivity issue - Olivia is going to update and that should clear the issue up.

**Comment by olivia-leach** [comment]
Fixing the case-sensitivity fixed the problem.
