### ISSUE TITLE
pushing to git hub

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#153]
I am able to run my program on my local host, but unable to see the program on github (even when I grunt build) in my settings and page...

**Comment by RDegnen** [comment]
in the html/css class I listed instructions on how to push to github pages. Follow those. https://github.com/ga-wdi-boston/html-css

**Comment by laurenfazah** [comment]
I see your project on its GitHub page, so I'm assuming this is resolved. Please close if so.
