### ISSUE TITLE
Error with AJAX

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#155]
getting this error & not sure why:

client?cd17:47 ./assets/scripts/example.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/Jessica1/wdi/projects/tic-tac-toe-2/assets/scripts/example.js'
    at Error (native)
 @ ./spec/example.spec.js 3:14-50

**Comment by RDegnen** [comment]
did you stop your grunt server?

**Comment by Jcornmanhomonoff** [comment]
I deleted an empty file I wasn't aware the directory needed. Added it back and problem was solved.
