### ISSUE TITLE
Ajax Update Password fields

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#156]
I'm working on sending a PATCH request to update a user's password.  In the modal, I have the fields Email, Old Password, and New Password, but I'm not sure if there's anything I need to do with those.  For example, how does the server know which is the old password and which is the new?  Maybe this is a dumb question haha

Here's the code I have for it:

``` javascript

<!-- Modal updatePassword -->
    <div class="modal fade update" id="update" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Update Password</h4>
          </div>
          <div class="modal-body">
            <form name="updatePassword" id="updatePassword">
              <div class="form-group">
                <label for="exampleInputEmailUpdate">Email address</label>
                <input type="email" name="credentials[email]" value="an@example.email" class="form-control grabthis" id="exampleInputEmail1" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="InputPasswordUpdateOld">Old Password</label>
                <input type="password" name="credentials[password]" value="an example password" class="form-control" id="exampleInputPasswordSignUp" placeholder="Password">
              </div>
              <div class="form-group">
                <label for="InputPasswordUpdateNew">New Password</label>
                <input type="password" name="credentials[password]" value="an example password" class="form-control" id="exampleInputPasswordSignUp" placeholder="Password">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </form>
          </div>
        </div>
      </div>
    </div>
```

and

``` javascript
$('#updatePassword').on('submit', function (event) {
    let data = getFormFields(this);
    event.preventDefault();
    authApi.updatePassword(authUi.signInSuccess, authUi.failure, data);
  });

```

and finally,

``` javascript
const updatePassword = (success, failure, form, id) => {
$.ajax({
  method : 'PATCH',
  url: app.api + '/change-password/:' + app.user.id,
  processData: false,
  data:form,
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
}).done(success)
.fail(failure);
console.log('patch worked');
};

```

Thank you!

**Comment by susandaiute** [comment]
And I'm getting this for errors:

PATCH http://tic-tac-toe.wdibos.com/change-password/:408 
localhost/:1 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/change-password/:408. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
ui.js:20 Object {readyState: 0, status: 0, statusText: "error"}

**Comment by laurenfazah** [comment]
Two things I see - looks like there's a typo in the endpoint you're using for your PATCH endpoint.
Also, check the API docs for updating password. The object needs to be slightly customized - you'll need to build the JSON object yourself before sending it. Thus, you can name and take the fields separately and work with that.

**Comment by susandaiute** [comment]
Which is the endpoint?

**Comment by laurenfazah** [comment]
http://tic-tac-toe.wdibos.com/change-password/:408 (as you have it)

**Comment by susandaiute** [comment]
When you refer to the API docs, do you mean the repo Game-Project-API or something online?

Also, not sure what the typo is.  Is it the 408?

**Comment by RDegnen** [comment]
repo Game-Project-API

**Comment by laurenfazah** [comment]
That colon - in documentation, it's indicative of a variable to be replaced :)

And yes, from the game-project-api docs: The changepw action expects a PATCH of passwords specifying the old and new.

**Comment by susandaiute** [comment]
I deleted the colon and my game turned into Tetris.  I'm not even kidding. The squares are moving around and making shapes and shit.

**Comment by susandaiute** [comment]
It works! Major thanks to Lauren...some thanks to Ross.
