### ISSUE TITLE
Atom -"failed to spawn scss-lint"

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/game-project#16]
The error messages pasted below:

![image](https://cloud.githubusercontent.com/assets/8867447/12785471/ad25a990-ca5a-11e5-8eda-da23e2446c5e.png)

**Comment by RealWeeks** [comment]
@erdesi90562 if your linter is still having issues @apalmer0

**Comment by GA-MEB** [comment]
Problem: `scss-lint` was renamed to `scss_lint`, but they both have the same executable (`scss-lint`) and this was causing the wrong one to be called.

Fix:

``` bash
gem uninstall scss-lint
gem uninstall scss_lint
gem install scss_lint
```

It may also be a good idea to uninstall and reinstall the Atom extension.

``` bash
apm uninstall linter-scss-lint
apm install linter-scss-lint
```

When you finish, restart Atom and everything should work.

**Comment by jrhorn424** [comment]
Restart atom _from the command line_
