### ISSUE TITLE
404 error in browser after deploying

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#161]
I've deployed my project, but when I go to the url:
susandaiute.github.io/tictactoe/
I get a 404 error.

**Comment by laurenfazah** [comment]
Did you just deploy? It takes some time to propogate.

**Comment by susandaiute** [comment]
Oh ok! Yep, just did it.

**Comment by laurenfazah** [comment]
Did it work? Make sure you ran grunt build and followed all those steps if it didn't.
