### ISSUE TITLE
CSS - Can't load background image from file

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/game-project#169]
This one works:
background-image: url('http://wallpaperstock.net/wallpapers/thumbs1/32826wide.jpg');

It can't find this one:
  background-image: url('../images/beach.jpg');

AND with the first one, the linter hates it and says i should exclude the protocol and domain

**Comment by RDegnen** [comment]
Have you made sure your path to the image is correct?

**Comment by berziiii** [comment]
if you're loading it from your index.html, you shouldn't need to back out a directory because you're in your root. I'd check your path again. Also, I'd make sure your images folder is in your assets folder.

**Comment by berziiii** [comment]
Also, check your index.js file. You may need to require your images folder there.

**Comment by MishaHerscu** [comment]
do you mean index.js or index.scss? i didn't know i had to reference any css stuff in index.js.

also - should i put the background-image styling into the body tag in index.html or in the body selector in the scss file? right now it is in the body selector in theme.scss.

one other question - should we have any actual selectors and styles in index.css or just imports?

i don't import the images folder into index.scss, but the path should let the scss go get the file right?

**Comment by MishaHerscu** [comment]
maybe src() instead of url()? that is preventing the error about not finding it, but it isn't doing anything now

**Comment by berziiii** [comment]
You're right. I mis identified where the path should be. IF you're loading it from your scss file, then the path should load it. Check the path again. Are you viewing the application from localhost:8080?

**Comment by MishaHerscu** [comment]
yes, from localhost. also check the last comment i added on src vs url

**Comment by berziiii** [comment]
src will be for html, url is from your style sheet. Check this out and make sure your property is correct for `background`

https://css-tricks.com/almanac/properties/b/background-image/

**Comment by RDegnen** [comment]
You can also look at https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

**Comment by MishaHerscu** [comment]
thanks, checking those links now

**Comment by MishaHerscu** [comment]
i think it is the right way for a normal HTML and CSS...could it have something to do with SCSS/Bootstrap?

one other thing, i forgot to add the actual error:

index.scss:6 Uncaught Error: Cannot find module "../images/beach.jpg"

i am a little confused about it thinking it is looking for a module, is that the same as a file?

**Comment by MishaHerscu** [comment]
maybe i need to set it as a var, i'll try that now

**Comment by MishaHerscu** [comment]
nope

**Comment by RDegnen** [comment]
I'll assign

**Comment by berziiii** [comment]
Post-bundle path is different than pre-bundle. example: `/assets/images/name_of_image.jpg`

**Comment by MishaHerscu** [comment]
thanks!!!

**Comment by jrhorn424** [comment]
I don't see a clear resolution here. I remember what it was, but could you post your final code for this, Misha?

**Comment by MishaHerscu** [comment]
Shoot! Sorry I was traveling and just got back. I think you guys solved it in another thread, but my code is below. I'll also be up for the next few hours if anyone wants to talk. The issue was that in webpack.js we had to add jpg (and png) as options (or that is my understanding, brian explained it to me when he fixed it)

in theme.scss, the body selector is the following, where $beach-background was defined elsewhere as:

`$beach-background: '../images/beach.jpg';`

`body {
  background-color: shade($paper-white, 0%);
  background-image: url($beach-background);
  color: $paper-white;
  font-family: $san-serif-family;
  font-size: $font-size;
  line-height: $line-height;
  margin: auto;
  opacity: 0%;
  padding: auto;
}`

that should work. The key change was in the webpack file, like brian sent out:

line 53 of webpack.js is now:

```
    `  test: /\.(ttf|eot|svg|jpg|png)(\?v=[0-9]\.[0-9]\.[0-9])?$/,`
```

the whole file is:

`
'use strict';

let webpack = require('webpack');
let path = require('path');

module.exports = {
  options: {
    entry: {
      bundle: './index.js',
      specs: './spec/_all.js',
      vendor: ['jquery', 'bootstrap-sass'],
    },

```
output: {
  path: './',
  filename: '[name].js'
},

plugins: [
  new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
  new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery",
    "window.jQuery": "jquery"
  })
],

module: {
  loaders: [
    {
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel',
      query: {
        presets: ['es2015']
      }
    },
    {
      test: /\.css/,
      loader: 'style!css',
      includePaths: [path.resolve(__dirname, "./node_modules")]
    },
    {
      test: /\.scss/,
      loader: 'style!css!sass',
      includePaths: [path.resolve(__dirname, "./node_modules")]
    },
    {
      test: /\.woff[\d]?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: "url-loader?limit=10000&mimetype=application/font-woff"
    },
    {
      test: /\.(ttf|eot|svg|jpg|png)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: "file-loader"
    },
    {
      test: /\.(hbs|handlebars)$/,
      loader: 'handlebars-loader'
    },
    {
      test: /\.html\.(hbs|handlebars)$/,
      loader: 'handlebars-loader!html'
    }
  ]
},

stats: {
  colors: true,
  modules: true,
  reasons: true
}
```

  },

  build: {
    failOnError: true,
    watch: false,
    keepalive: false
  }
};

`

**Comment by MishaHerscu** [comment]
on github, the file is here, in case i got it wrong above:

https://github.com/MishaHerscu/game-project-client/blob/gh-pages/grunt/webpack.js

the rest of my stuff is here:

https://github.com/MishaHerscu/game-project-client

**Comment by jrhorn424** [comment]
Cool, thanks for the links! Mind closing again?

PS - You don't have to open an issue for me to get notifications about it. :smile:

**Comment by MishaHerscu** [comment]
Ah okay, didn't know that.
