### ISSUE TITLE
Using a callback to iterate through possible winners

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/game-project#17]
I have posted the code for my getWinner function below. It iterates nicely through all the winning combos. I know that I want to use .every() to see if the elements in newArray are equal to X or O in my const. I've read through the docs and know that I need to set the current value of my callback function to newArray[ j ]. I can't define that before the getWinner because it doesn't know what [ j ] is yet but I also can't define it within the block once [ j ] has been established. I don't even know if I'm making any sense. I feel like I'm SO CLOSE.

```
const board = ['', '', '', '', '', '', '', '', ''];
let winning = [
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8],
  [0, 4, 8],
  [2, 4, 6]
];

let getWinner = function() {
    for (let i = 0; i < winning.length; i++) {
    let newArray = winning[i];
       for (let j = 0; j < newArray.length; j++) {
  }
} return;
};

$(document).ready(function() {
  $('#board').find('td').click(function() {
    if (turnCount % 2 === 0) {
      $(this).text('X');
      board[event.target.id] = 'X';
    } else {
      $(this).text('O');
      board[event.target.id] = 'O';
    }
    console.log(board);
    turnCount++;
    getWinner();
    if (turnCount >= 9) {
      window.alert("Cats game. Please play again.");
    }
  });
});
```

**Comment by RealWeeks** [comment]
@kpie89 I remember this this. Lets talk.

**Comment by gaand** [comment]
I don't think you want to use `every`.  I think you want to check if each value in newArray is set to the same value `'x'` or `'o'`.

**Comment by RealWeeks** [comment]
@kpie89 I see @gaand responded. Work with his information and comment further is you need assistance.

**Comment by gaand** [comment]
Sorry, if each value used as an index for board is set to the same value.  If that's not clear, let me know.

**Comment by gaand** [comment]
@kpie89 If that is clear, and you get it working, please close the issue.  Thanks.

**Comment by kpie89** [comment]
The thing that is tripping me up about @gaand solution is that I am trying to compare an array (board) to a nested array (
