### ISSUE TITLE
Ajax is not working it just refreshes the page, maybe problem causes by merging repos from yesterday?

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/game-project#170]
Issue Description:
- I looked if my code from api-token-auth worked since it should be the same code. 
- Since it worked I compared my code with that, but its identical
- Yesterday Brian and I merged my original repo with the api-token-auth manually. Maybe something went wrong there.

[ error message, if one exists ]

Just getting this, no matter what I do:
abstract-xhr.js:132 XHR finished loading: GET "http://localhost:8080/sockjs-node/info?t=1464794827896".

[ things you've tried to fix the problem ]
- I had a modal already in my html and thought, that might messes things up, so I commented that out and tried it- failed
- walked over the code with Matt and Ruben, asked Andres and Tina if they have an idea

[ the last point at which the app was working ]
- never at my project but it works at the training material

**Comment by payne-chris-r** [comment]
What is the default behavior of a button click?

**Comment by esthercordova** [comment]
refresh the page?

**Comment by berziiii** [comment]
Check to make sure you don't have the same `id` named for different things. You may have used the same `id` on your project code as we used in the api-token-auth code-along. It may be registering the id to something that doesn't have `event.preventDefault()` on it.

**Comment by RDegnen** [comment]
Is there another error message in red?

**Comment by esthercordova** [comment]
I took the modal out and basically just have the code like it is in the api-token-auth.

**Comment by esthercordova** [comment]
no

**Comment by payne-chris-r** [comment]
Talked to Esther, the issue doesn't have to do with the merged repos, it has to do with calling the right jQuery selector. She's working on setting that up properly now.

**Comment by payne-chris-r** [comment]
The issue of refreshing the page on click has been resolved.
