### ISSUE TITLE
Grunt / Git

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/game-project#172]
I am having trouble pushing my gh-pages branch. It kind of works, but it can't find an image asset. I think it is related to the same issue as before with the different path post grunt, but I thought my doing grunt build before pushing solved that and it doesn't.

**Comment by RDegnen** [comment]
hmm I remember running into this before, I think adding a `./` before the image file path fixed it. For some reason localhost and gh-pages seem to disagree on the image paths, or webpack is doing something to it with build

**Comment by RDegnen** [comment]
Sorry actually i dont think the last comment was correct

**Comment by RDegnen** [comment]
Is it the image that is being loaded from your scss file?

**Comment by berziiii** [comment]
final image path needed to be the final url. `'http://<github_user_name>.github.io/assets/images/<name_of_image>"`

**Comment by MishaHerscu** [comment]
Thanks!

**Comment by RDegnen** [comment]
@MishaHerscu if this is resolved please close

**Comment by MishaHerscu** [comment]
The answer ended up being that webpack needed to allow jpg and png formats. If any student is reading this and is having trouble, ask a teacher how to make this fix. It is quick but it might be hard to find without help.

**Comment by berziiii** [comment]
You need to alter a line in your webpack.js file to bundle .jpg and .png files. To find this file, hit cmd p and search for webpack.js. Once your in the file,  find the line that has 

``` diff
// edited by @jrhorn424

-test: /\.(ttf|eot|svg) ...
+test: /\.(ttf|eot|svg|jpg|png) ...
```

Keeping everything else there then save the file. This is telling your webpack to load any .jpg and .png files.

**Comment by berziiii** [comment]
Your image path will remain a relative path to access the file either in your HTML or scss file

**Comment by jrhorn424** [comment]
Thanks. @berziiii please use fenced code blocks in the future. If want to see how I created that diff, click edit on your comment and that will show the Markdown used to achieve it.
