### ISSUE TITLE
JS, jQuery.ajax() - joinGame 

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/game-project#174]
Here is my function:

``` js
const joinGame = function(gameId, authToken){
  return $.ajax({
    url: app.host + '/games/' + gameId,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + authToken,
    },
    data: {},
  });
};
```

I pass the gameId of the game I want to join, and the authToken of the owner of that game.

I think that I may need to give two authTokens somehow, so it knows who I am, and that I have permission, but I don't see a sample for this query anywhere. Am I missing something in the docs?

Thanks.

**Comment by gaand** [comment]
The user joining a game is not the user who created the game. Anyone except the creator can join a game that hasn't already been joined.

**Comment by MishaHerscu** [comment]
Thanks. It is working now. I didn't realize you don't need the other person's auth key.

**Comment by gaand** [comment]
If this is resolved, please close the issue. Thanks.

**Comment by MishaHerscu** [comment]
thanks, sorry about that
