### ISSUE TITLE
Requirement Wording Could Be Clearer

### ISSUE THREAD

**Issue by erinsul** [ga-wdi-boston/game-project#175]
Line "Switch turns between X and O (or whichever markers you select)" could be clearer that the logic needs to make the switch automatic, not that the switch is a choice.

**Comment by berziiii** [comment]
prompted by consultant team to open. Please leave open until addressed.

**Comment by RealWeeks** [comment]
@berziiii I'm going to close but please reopen if you have concerns. I think this is more a question about the game of tic tac toe than a clarification of the requirements.

**Comment by jrhorn424** [comment]
Did @gaand ask you to close this?

**Comment by RealWeeks** [comment]
@jrhorn424 Discussed with @gaand and deemed unnecessary change. Please reopen if you want to discuss/change the repo.
