### ISSUE TITLE
It's disturbing to leave Player O as null

### ISSUE THREAD

**Issue by erinsul** [ga-wdi-boston/game-project#176]
I think a bunch of us (or, Arielle and me, at least) tried to get player O signed in because we felt like it couldn't be okay to leave Player O as null. I REALIZE the documentation does say Player X cannot be Player O, and the initial object returned has Player O as null, but the documentation also details a way to join as Player O, and it's not exactly labeled as "this is bonus material!!". I think it could be clearer that 1) leaving "null" in your object (at player o) is actually okay!!! and 2) That all those details on how to POST player O into the game are actually just bonus and totally fine to completely ignore.

**Comment by berziiii** [comment]
prompted by consultant team to open. Please leave open until addressed. Majority of documentation on API reference player_O vs null.

**Comment by jrhorn424** [comment]
@berziiii Could you elaborate more, or just again? I'm not getting something.

**Comment by berziiii** [comment]
We had to address confusion on whether leaving `player_o = null` or if a second user needed to join a game. Chris, Ross and I said that if there is a question, to file it as an issue and we said we would leave it open so @jrhorn424, @gaand and the rest of team could determine if there is a clear way to word the requirements. More of a discussion around a possible enhancement. We clarified this in front of the room to prevent additional confusion but wanted to leave open so it could be discussed between the consultant team.

**Comment by RealWeeks** [comment]
@ga-wdi-boston/core Antony and myself think this is a bit unnecessary, but if strong opinions are out there please voice them.

**Comment by gaand** [comment]
@ga-wdi-boston/core I'm closing this.  If anyone strongly disagrees with that, please reopen with a comment as to how they believe it can be handled.  I do not see what needs to be added given the API documents.  Please feel free to disagree.
