### ISSUE TITLE
Jquery/JS - trying to access multiple HTML element ID's 

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/game-project#177]
No linters. Have talked to multi students.
Tried .data method, .attr, and event.target. Event.target got me the whole element, I just want the id so I can store it in an array. .attr and .data have given ID to first element in collection.

**Comment by RDegnen** [comment]
Can you post the jquery code that you are trying to access the id with? and the html your trying to access?

**Comment by computingbets** [comment]
```
<div class="row">
        <div class="col-xs-4" id="cellZero">o</div>
        <div class="col-xs-4" id="cellOne">x</div>
        <etc to id="cellEight>
```

Handler

``` js
  $('.col-xs-4').on('click', onMove);
};

const onMove = function (event) {
  event.preventDefault();
  let id = $(".col-xs-4").attr("id");  
 / let id +$(".col-xs-4").data(cellID, 1) //which may work but I might have to do this for each div in the class, also an issue
  console.log(id);
};
```

**Comment by RDegnen** [comment]
You are trying to access the id by a class which you have on multiple html elements, instead of accessing the id directly.

**Comment by RDegnen** [comment]
You are trying to access the id by using a class that you have on multiple html elements. What do you think the value of `this` is when you click on an element?

**Comment by computingbets** [comment]
correct. is there a way to select an any id in a collection or would i have to hard code each div directly?

**Comment by RDegnen** [comment]
Sorry I removed my first comment, look at the one above

**Comment by computingbets** [comment]
any id on a collection triggered by the event click

**Comment by RDegnen** [comment]
its the value of the html element, which will have an id if you put one there

**Comment by computingbets** [comment]
right. i think the idea of using this to refer to the collection is really strong. I may be syntactically using this incorrectly. Here is one way i tried using this

``` js
 const onMove = function (event) {
  event.preventDefault();
  let id = event.target
  let idd = this.attr("id");
  console.log(id);
  console.log(idd);
};
```

but this leads to an error that says this.attr is not a function

``` js
combinding let id = event.target.this.attr("id")
```

leads to 'Cannot read property 'attr' of undefined'

**Comment by payne-chris-r** [comment]
Be careful when using `this` you might not be getting what you think you are! What did the console produce with these:
console.log(id);
console.log(idd);
Does it just blow up with `this.attr is not a function`?

**Comment by RDegnen** [comment]
ill assign

**Comment by jrhorn424** [comment]
What was the resolution? @RDegnen @logicmyth
