### ISSUE TITLE
sign-Up/ Sign-In/ Change Password / Log Out are refreshing page and no longer connecting to server

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/game-project#178]
24 hours ago, I was successfully making POST, GET, DELETE requests using my sign-up, sign-in, changepassword buttons.

now, upon hitting button, the page refreshes and changes URL to this : 

http://localhost:8080/?credentials%5Bemail%5D=mjb&credentials%5Bpassword%5D=mjb&submit=Sign+in%21

Not sure what's going on...  I thought it was calling wrong api url, but I've double checked that with others and I have the same thing to their working product.  

any help ? 

thanks,
matt :)

**Comment by mattb5** [comment]
My game board and logic successfully done done so I'm really in need of getting the sign-in to work prior to working on the the game api material.

**Comment by payne-chris-r** [comment]
I see an "and" in your issue Subject Line. One thing at a time, young padawan.

**Comment by payne-chris-r** [comment]
In all seriousness though, why would the page be refreshing?

**Comment by mattb5** [comment]
Sorry, master ;-)

Let's start with just refreshing the page - upon clicking of these buttons, the URL changes to this address listed above.

**Comment by mattb5** [comment]
i do have the "event.preventDefault()" method, in each click handler method.  I thought that would prevent page from refreshing..

**Comment by RDegnen** [comment]
did you change anything in your ajax requests?

**Comment by mattb5** [comment]
i have not... yesterday i was toying with postman to send some requests to the server....  but did not change anything in my AJAX code.

**Comment by RDegnen** [comment]
can you post the code to your click handler and ajax?

**Comment by mattb5** [comment]
``` js
const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp);
};

const onSignUp = function (event){
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signUp(data)
  .done(ui.success)
  .fail(ui.failure);
};

const signUp = (data) => {
  return $.ajax (
  {
  url: app.host + '/sign-up',
  method: 'POST',
  data: data
  }
);
};
```

**Comment by mattb5** [comment]
hey chris - does this mean i should meet you in person?  should i come now?

**Comment by payne-chris-r** [comment]
Matt, please close this issue if it's resolved. Thanks!

**Comment by mattb5** [comment]
is resolved :)  thanks chris!!

**Comment by jrhorn424** [comment]
@mattb5 @payne-chris-r What was the resolution of this issue?

**Comment by mattb5** [comment]
Solution was that I had an "On document Ready" jquery function in another page so I had to add my events.js handlers in that document ready in order for them to become clickable again.
