### ISSUE TITLE
Github branch is freaking out, man

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/game-project#179]
I'm attempting to add commits to my Events branch on my repo Game-Project-Client.  I had originally named the repo tic-tac-toe and then changed it.  When I try to commit and push the Events.js file to my repo, here's what I see in Terminal:

``` sh
#edited by @jrhorn424
~/wdi/projects/tic_tac_toe (events)$ git push 
fatal: The current branch events has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin events

~/wdi/projects/tic_tac_toe (events)$ git push origin events
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 781 bytes | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/andreasantarl/Game-Project-Client.git
To git@github.com:andreasantarl/tic-tac-toe.git
   69bd241..78950f6  events -> events
~/wdi/projects/tic_tac_toe (events)$ git push --set-upstream origin events
Branch events set up to track remote branch events from origin by rebasing.
Everything up-to-date
```

I'm not sure how to fix this, and my code reverted back to the starter code that we began with so I don't see any of the updates I've made.

**Comment by berziiii** [comment]
Because the remote is not set to the same place now. You have to reset the remote path to be the new directory name, type `git remote -v` and see what is says. Is it the same of the repo you have changed or the old name?

**Comment by andreasantarl** [comment]
It's the old name.

**Comment by berziiii** [comment]
grab the new SSH link for the repo and then type `git remote add origin <new SSH clone link>`

**Comment by andreasantarl** [comment]
Failed.  Should I be doing this in a branch or in the master?

~/wdi/projects/tic_tac_toe (events)$ git remote add origin git@github.com:andreasantarl/Game-Project-Client.git
fatal: remote origin already exists.

**Comment by RDegnen** [comment]
what room are you in? So i can come assist

**Comment by andreasantarl** [comment]
I'm in the first floor lounge.
With the cool kids.

**Comment by berziiii** [comment]
May have to remove your .git and redo 'git init'

**Comment by berziiii** [comment]
Ross will assist

**Comment by payne-chris-r** [comment]
Great issue subject line!

**Comment by andreasantarl** [comment]
It's happening again!!! All of my code reverted to the starter code.  No error messages, though.

**Comment by berziiii** [comment]
Can you share what happened? What did you do to get things to revert? please share what you did prior to noticing things reverted.

**Comment by andreasantarl** [comment]
I made updates to my events.js file.  Attempted to add and commit that file (successfully), pushed the commit to that branch (events) and then I refreshed my localhost.  All of the UI changed back to the starter code that we had, as opposed to the updates that I'd made.  Here's the terminal sequence of events:

``` sh
# edited by @jrhorn424
~/wdi/projects/tic_tac_toe (events)$ git add assets/scripts/auth/events.js
~/wdi/projects/tic_tac_toe (events)$ git commit
[events 4e809ea] Prevents clicking new tiles once game is won
 1 file changed, 38 insertions(+), 26 deletions(-)
~/wdi/projects/tic_tac_toe (events)$ git push origin events
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 940 bytes | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
To git@github.com:andreasantarl/Game-Project-Client.git
   c8c7475..4e809ea  events -> events
```

**Comment by andreasantarl** [comment]
It appears that the git repo is correct.

**Comment by RDegnen** [comment]
did you accidentally change branches?

**Comment by andreasantarl** [comment]
I didn't change anything after we met.

**Comment by berziiii** [comment]
merged events branch into master and rebased event branch from master. Now working. Please close @andreasantarl

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @andreasantarl

**Comment by jrhorn424** [comment]
@berziiii I deleted your comment. Never ever delete `.git` unless you talk to a senior consultant first.

**Comment by jrhorn424** [comment]
For future reference:

```
fatal: remote origin already exists.
```

Indicates that the remote with the name `origin` is already in the repository. If you want to change the URL that `origin` points to, you have to remove it first with `git remote remove` and then add the correct URL with `git remote add`.

**Comment by jrhorn424** [comment]
> merged events branch into master and rebased event branch from master. Now working. Please close @andreasantarl

Please don't do things in that order, @berziiii. Instead,

``` sh
(on events branch) git rebase master # this updates the events branch with anything that was on master before

(on master branch) git merge events # this brings changes from events back into master

# now events is obsolete since master has everything
(on master branch) git branch -d events
```
