### ISSUE TITLE
Javascript - preventing click from toggling between X and O 

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/game-project#180]
Hey guys, 

I've successfully added an event handler that allows users to click on the divs that make up the game board. However, a user can click on a div that already contains either an 'X' or an 'O' and that will change it. 

I tried defining a variable as an empty string and using an IF statement to console log and see if the function jumps into the ELSE IF condition. In the browser, though, it console logs 'make a valid move' every time a user clicks.  

``` js
let turnCount = 0;
let player1 = 'X';
let player2 = 'O';
let empty = ' ';
const makeAMove = function (event) {
    event.preventDefault();
    if ($(this).val() !== empty) {
      console.log('Make a valid move');
    } else if (turnCount % 2 === 0) {
        $(this).text(player1);
      } else {
          $(this).text(player2);
        }
      turnCount++;
};
```

**Comment by RDegnen** [comment]
Have you tried checking for `$(this).val() === player1` or player2? Alternatively you could try applying a class or other attribute to the clicked div's and checking against that. Also, make sure the value of this is what your expecting it to be by using a debugger in that function.

**Comment by berziiii** [comment]
`$(this).val()` looks for an input or value of something. The way your function is written, you need to see what `$(this).text()` is. Please close this issue. Thanks @RoobScoobs.

**Comment by RoobScoobs** [comment]
Made the change from `$(this).val() !== empty) to ($(this).text() !== empty` in order for the function to recognize what was actually in that container

**Comment by RoobScoobs** [comment]
Thanks guys.

**Comment by jrhorn424** [comment]
Thanks for updating your issue, @RoobScoobs.

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @RoobScoobs
