### ISSUE TITLE
Can't delete style.css

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/game-project#181]
I'm trying to organize my files. i previously had my css in style.css but want to move it in index.scss now to conform with what we do in class.

It works without problems, but my api starts yelling at me. It tries for some reason to access the file that I deleted.

I solved it through having now am empty style.ss with all my css in index.scss but I would like to delete the empty file.

![screen shot 2016-06-02 at 11 46 09 am](https://cloud.githubusercontent.com/assets/13932794/15754762/c3e00560-28c7-11e6-8788-480627d4fd1b.png)

**Comment by payne-chris-r** [comment]
Can you figure out the "for some reason" piece of your `It tries for some reason to access the file that I deleted.` question? Why might it be looking for this file?

**Comment by esthercordova** [comment]
![screen shot 2016-06-02 at 1 52 06 pm](https://cloud.githubusercontent.com/assets/13932794/15755142/85ce767e-28c9-11e6-9b5d-8ad1aaa1b59b.png)

I deleted the reference on the html to the css but now I got the error back from yesterday...

**Comment by esthercordova** [comment]
I upstaged my files and am now back to normal, I will store my css files in scss and have an empty style.css file. It works this way. Is that ok?

**Comment by RDegnen** [comment]
have you looked to where you were loading that style.css file into your app

**Comment by esthercordova** [comment]
yes at the html file, but when I delete that I get the require thing. It seems unrelated to me, but somehow it's related.

**Comment by RDegnen** [comment]
Did you require that css file in your index.js file?

**Comment by esthercordova** [comment]
no

**Comment by esthercordova** [comment]
fixed

**Comment by jrhorn424** [comment]
What was the resolution? I assume it was:

> Did you require that css file in your index.js file?

But need confirmation, @esthercordova @RDegnen

**Comment by esthercordova** [comment]
Sorry, I can't recall the solution but I did require it- that wasnt the problem.
