### ISSUE TITLE
Having some issue with my html and css

### ISSUE THREAD

**Issue by jacobhereford** [ga-wdi-boston/game-project#182]
I had a board working and not too sure what happened but I cannot get the board back to the original.  I worked on it all morning and finally feel stuck.

**Comment by payne-chris-r** [comment]
Get a mac.

**Comment by jacobhereford** [comment]
lmao

**Comment by RDegnen** [comment]
Could you possibly narrow it down to when your board stopped working

**Comment by jacobhereford** [comment]
This morning lol I know thats not much help.  So whats broke is when you adjust the screen.  at xs its fine but once it gets bigger its no longer aligned

**Comment by RDegnen** [comment]
If you open up the console, is your css and html still the same as you remember at the spot where it breaks?

**Comment by jacobhereford** [comment]
Yeah it all looks the same, and I havent changed anything in it.  I think im just going to switch it around to a different way to do it.

**Comment by RDegnen** [comment]
still having issues?

**Comment by payne-chris-r** [comment]
Just talked to Jacob. He's good. Gonna close it.

**Comment by jrhorn424** [comment]
What was the actual problem and actual resolution? @payne-chris-r @RDegnen @jacobhereford
