### ISSUE TITLE
Change password ajax request returning 400

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/game-project#183]
Hey,

Been trying to debug but I keep getting a 400 error on my change password. I didn't alter it from API at all (I _think_). Dug through some closed issued but couldn't find anything of use. I'm stumped.

form html

``` html
<form id="change-password" class="collapse">
        <legend>Change Password</legend>
        <fieldset>
          <input type="password" name="passwords[old]" placeholder="old password">
          <input type="password" name="passwords[new]" placeholder="new password">
          <input type="submit" name="submit" value="change password!">
        </fieldset>
      </form>
```

handler and click event

``` js
const onChangePassword = (event) => {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.changePassword(data)
    .done(ui.success)
    .fail(ui.failure);
};

$('#change-password').on('submit', onChangePassword);
```

ajax

``` js
const changePassword = (data) => {
  return $.ajax({
    url: app.host + '/change-password/' + app.user.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data
  });
};
```

*edit holy formatting batman

**Comment by RDegnen** [comment]
Does the data that your sending match what the API is expecting?

**Comment by lcurran** [comment]
I think so. The object that I get in the console on sign in looks right, and the path to the token should be correct.

**Comment by RDegnen** [comment]
can you post the error

**Comment by lcurran** [comment]
error
<img width="1319" alt="screen shot 2016-06-02 at 4 02 54 pm" src="https://cloud.githubusercontent.com/assets/15129578/15759165/bc60ccfc-28db-11e6-8850-7b5ab3d911e0.png">
user object
<img width="822" alt="screen shot 2016-06-02 at 4 03 13 pm" src="https://cloud.githubusercontent.com/assets/15129578/15759164/bc5fad18-28db-11e6-831f-985453f7e197.png">

**Comment by RDegnen** [comment]
it looks like you have an extra `/` in your url after the .com

**Comment by lcurran** [comment]
still happening after I fixed the app file :(
<img width="1332" alt="screen shot 2016-06-02 at 4 11 32 pm" src="https://cloud.githubusercontent.com/assets/15129578/15759466/b6b44846-28dc-11e6-9b5f-6fa641dfcd4f.png">

**Comment by RDegnen** [comment]
does it work if you make a curl request?

**Comment by payne-chris-r** [comment]
Are you sure the password[old] matches the password in the db?

**Comment by jrhorn424** [comment]
What was the resolution for this? @lcurran @RDegnen @payne-chris-r

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Do **not** paste images. Instead, copy and paste errors and code.

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @lcurran

**Comment by lcurran** [comment]
I was using a new password that was the same as the old password. 

Sent from my T-Mobile 4G LTE Device

-------- Original message --------
