### ISSUE TITLE
Temperamental Require Route 

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/game-project#184]
I am trying to import files into other js files. 
gameLogic.js is in my root and I'm trying to import it into assets/scripts/auth.

const gameLogic = require('../../../gameLogic.js');
error gives me cannot find module ('../../../gameLogic.js)

**Comment by payne-chris-r** [comment]
Can you screenshot your file structure in Atom? My guess is you're referencing the wrong filepath, but I need to see it.

**Comment by computingbets** [comment]
![image](https://cloud.githubusercontent.com/assets/18650954/15760097/b13ea192-28df-11e6-8cf1-20640ffb0996.png)

**Comment by computingbets** [comment]
as well as 
![image](https://cloud.githubusercontent.com/assets/18650954/15760141/e8274394-28df-11e6-9977-6c78851ae1c0.png)

**Comment by RDegnen** [comment]
did you export gamelogic?

**Comment by computingbets** [comment]
just some of the functions. can i / should I module.export the whole file?

**Comment by payne-chris-r** [comment]
Can you show us the bottom of your gamelogic.js file (in particular the module.exports section)?

**Comment by computingbets** [comment]
![image](https://cloud.githubusercontent.com/assets/18650954/15760516/932685f6-28e1-11e6-9f0d-64e1385782ec.png)

**Comment by RDegnen** [comment]
I think you might have a circular dependency. try and take the requirment of events out of the top of gamelogic and see what happens

**Comment by computingbets** [comment]
still cant find module gameLogic

**Comment by berziiii** [comment]
Would any of your `require` functions happen to be in a `$(document).ready()` function? This is what Matt had that @payne-chris-r helped spot.

**Comment by RDegnen** [comment]
is this still acting up?

**Comment by computingbets** [comment]
I copied my gameLogic into events.js so importing logic is not an issue right now. However, my index.js could not find module "./auth/events.js". I reloaded the game and it does not have module issues at the moment, so I can close it for now. Thanks for checking in w/ me!

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Do **not** paste images. Instead, copy and paste errors and code.

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @logicmyth
