### ISSUE TITLE
Javascript - using jquery with arrays? 

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/game-project#185]
Hey guys, 

Back at it again with the issue filer...

My console returned the following error – Uncaught TypeError: Cannot read property 'text' of undefined. 

I'm wondering if it does not make any sense to use jquery with FOR loops and arrays like in the code below.

``` js
const winGame = function () {
  let winCombos = [$('.row.1'), $('.row.2'), $('.row.3'), $('.col-1'), $('.col-2'), $('.col-3'), $('.diag-1'), $('.diag-2')];
  for (let i = 0, max = winCombos.length; i <= max; i++) {
    if (winCombos[i].text() === player1) {
      console.log('X Won!');
    }
  }
 };
```

**Comment by RDegnen** [comment]
its saying that `winCombos[i]` is undefined. If you put a debbuger right after where you declare the winCombos array, is winCombos or any of its elements defined in the console?

**Comment by RoobScoobs** [comment]
winCombos is defined. Looks like it's recognized as an array containing 8 elements.

**Comment by berziiii** [comment]
Moving callbacks around helped call function but logic needs work. Leaving open until more updates are available.

**Comment by payne-chris-r** [comment]
Is winCombos[i] is defined throughout the entire for loop?

**Comment by payne-chris-r** [comment]
@roobscoops is this resolved? Can you close if it is??

**Comment by jrhorn424** [comment]
Please note what the resolution actually is before closing an issue @RoobScoobs. Thanks. What was the resolution for this issue?
