### ISSUE TITLE
Create new game api: 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/game-project#186]
![screen shot 2016-06-02 at 7 19 03 pm](https://cloud.githubusercontent.com/assets/13932794/15764188/fb3103f0-28f6-11e6-9bba-2e31f37e972f.png)

I am trying to create a new game in the api. I created a user and signed in. Works. Then I connected my newGame button with a click handler in events.js. My POST request is not getting allowed: localhost/:1 XMLHttpRequest cannot load.

I don't quite understand my error. What is it unhappy with. I'm passing the token in the ajax. Why am I having no access?

**Comment by esthercordova** [comment]
issue solved, got help from help from my husband.

**Comment by jrhorn424** [comment]
What was the actual resolution for this issue? @esthercordova

**Comment by esthercordova** [comment]
Something was wrong with the header line I passed in. But I can't recall anything more specific. Sorry.
