### ISSUE TITLE
convert associative array to simple array of its values javascript 

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/game-project#188]
![screen shot 2016-06-03 at 10 46 40 am](https://cloud.githubusercontent.com/assets/13932794/15782486/8a9a0b14-2978-11e6-8f99-7f8f0d935f8c.png)

I can convert my associative array in a simple array, which is necessary for the api, but with push it doesnt update the array fields, it just puts it every time on the end - so that I end up with a super long array.

I tried for loop but I am not sure what to do that every time some clicks the associated array updates a simple array.

**Comment by esthercordova** [comment]
I think I need to use an array method like foreach or so, I tried around but I dont get it to work.

**Comment by esthercordova** [comment]
I need to do that before I can work on PATCH - right?

**Comment by berziiii** [comment]
Firstly, where is `var` coming from in your loop? We are using `let`. Also, I need to see more about where `'unclicked'` is being called from and how everything ties together. The idea of push will add values to an array. Not change them.

**Comment by esthercordova** [comment]
I thought js.fiddle maybe doesnt like let.... 

I need something that converts the array and then updates it.

**Comment by esthercordova** [comment]
I need more input here, please!

**Comment by payne-chris-r** [comment]
Esther, what have you tried googling? Have you looked at the docs for 'forEach'?

**Comment by esthercordova** [comment]
I have indeed tried googling... I also tried forEach. Roos and I found a solution. Thanks.

**Comment by jrhorn424** [comment]
What was the solution? Please do not close issues without noting what fixed the issue. @esthercordova @RDegnen

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Do **not** paste images. Instead, copy and paste errors and code.

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @esthercordova

**Comment by esthercordova** [comment]
![screen shot 2016-06-06 at 9 16 11 am](https://cloud.githubusercontent.com/assets/13932794/15823144/65e90e72-2bc7-11e6-9ac0-bb149c4c1d63.png)

This is the solution. Ross helped me to figure it out.
