### ISSUE TITLE
need help with PATCH

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/game-project#189]
I need help to get started with PATCH, I don't know where to start... It's not a good issue but it's my issue.

**Comment by payne-chris-r** [comment]
You're right, it's not a great issue, but that's ok! What's the first step? What's the problem you're running into?

**Comment by esthercordova** [comment]
I think I need my array to be an simple array instead of an associative array. So I'm working on that, thats the other issue. Ross is coming now and will help me. Is taht the right approach?

**Comment by payne-chris-r** [comment]
If the API is expecting an array and you're sending it an object (associative array) it won't be happy, that's correct.

**Comment by esthercordova** [comment]
Ok, so I have now a simple array.

**Comment by payne-chris-r** [comment]
Good!

**Comment by esthercordova** [comment]
![screen shot 2016-06-03 at 12 35 08 pm](https://cloud.githubusercontent.com/assets/13932794/15785885/ae28cc6e-2987-11e6-9315-0723dd413d5f.png)

**Comment by esthercordova** [comment]
![screen shot 2016-06-03 at 12 38 24 pm](https://cloud.githubusercontent.com/assets/13932794/15785954/16ab9f46-2988-11e6-8932-92a975631861.png)

**Comment by esthercordova** [comment]
I need guidance in how to proceed.

**Comment by esthercordova** [comment]
So far I can create a game and find a game by its ID and find all games. What is the next step? On what should I work now? Is it Patch or Create or?

**Comment by payne-chris-r** [comment]
Did you resolve those errors? What is undefined? How would we figure that out?

**Comment by esthercordova** [comment]
no I'm just doing random things.

**Comment by jrhorn424** [comment]
> no I'm just doing random things.

I'm not sure if that was meant to be humorous. In any case, we should talk on Monday @esthercordova.
