### ISSUE TITLE
files link

### ISSUE THREAD

**Issue by kenvng** [ga-wdi-boston/game-project#19]
my files are linking to each other via html fine but when I put them up on git they won't link at all.
I used 
for scss

```
<link rel="stylesheet" href="assets/styles/index.scss">
```

or

```
<link rel="stylesheet" type="text/css" href="./assets/styles/index.scss"/>
```

and for js

```
<script src="./assets/scripts/example.js"></script>  or just deleted that line but nothing worked
```

THanks
Ken

**Comment by gaand** [comment]
If you pasted code, It's not showing up for me.

**Comment by RealWeeks** [comment]
Why are you linking to another style sheet? the template we gave you should already link to your scss file.

**Comment by RealWeeks** [comment]
also please note @kenvng I updated your original issue with backticks for clarity.

**Comment by jrhorn424** [comment]
Are you talking about gh-pages?

**Comment by RealWeeks** [comment]
@kenvng Please clarify the issue

**Comment by jrhorn424** [comment]
You should not have to add any `link` elements or `script` elements if you're using the js-template.
