### ISSUE TITLE
require('./ui.js') not working

### ISSUE THREAD

**Issue by shireen-bean** [ga-wdi-boston/game-project#190]
I have

``` js
//edited by @jrhorn424
const ui = require('./ui.js');
```

but non3 of the `ui.functions` will work.

I do not get any erros other than I can see that it cannot reference any of my `ui.functions`.

This is only in one script, I tried copying the absolute path to the ui.js ad that still didnt work.

**Comment by RDegnen** [comment]
is it returning you an empty object?

**Comment by shireen-bean** [comment]
Nope, it's just  behaving as if it doesn't exist. As if the ui.function wasn't even written in the spot. But if I replace the callback with the actual content in the call back then it works fine.

I can even move the call back around and it doesnt work but I can move the content around and it does work. So I know that it's just not referencing the document ui.js

**Comment by RealWeeks** [comment]
@RDegnen circular ref?

**Comment by RDegnen** [comment]
@J-Weeks methinks yes

**Comment by shireen-bean** [comment]
^ correct. circular ref.

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @shkherad
