### ISSUE TITLE
Bootstrap glyphicons not working when deployed

### ISSUE THREAD

**Issue by SarahHartwick** [ga-wdi-boston/game-project#192]
The glyph icons worked on my local serve but not when deployed to github pages, three errors below:

``` sh
# edited by @jrhorn424
sarahhartwick.github.io/:1 GET http://sarahhartwick.github.io/game-project-client/448c34a56d699c29117adc64c43affeb.woff2 404 (Not Found)

2016-06-03 13:46:02.270 sarahhartwick.github.io/:1 Failed to decode downloaded font: data:application/font-woff;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJmYTI3NzIzMjdmNTVkODE5ODMwMWZkYjhiY2ZjODE1OC53b2ZmIjs=

2016-06-03 13:46:02.271 sarahhartwick.github.io/:1 OTS parsing error: invalid version tag
```

**Comment by RealWeeks** [comment]
Hey @SarahHartwick please see this issue to solve your problem: https://github.com/ga-wdi-boston/full-stack-project/issues/307

**Comment by SarahHartwick** [comment]
Thank you, all set!

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @SarahHartwick
