### ISSUE TITLE
AJAX/Javascript - update a game 

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/game-project#193]
Hey guys, 

In trying to update the game status in the backend, I keep getting a 404 error. 

I build out my ajax request as the following: 

``` js
const updateGame = function (value) {
  return $.ajax ({
    url: app.host + '/games/' + app.user.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: value
  });
};
```

value is defined as:
`let value = $(event.target).text();`
This targets the container clicked on and retrieves either X or O.

updateGame then gets called in my makeAMove Function 

`api.updateGame(value)`

**Comment by RDegnen** [comment]
does what your sending to the API look like this?

```
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
```

**Comment by RDegnen** [comment]
And it looks like your sending a user id, not the id of the game to update

**Comment by RoobScoobs** [comment]
So after creating a game I see that it returns a game as an object. In order to retrieve a specific game should my URL read as:  app.host + '/games/' + game.id

**Comment by RoobScoobs** [comment]
Hmm... property of id is undefined

**Comment by payne-chris-r** [comment]
What do the api docs say?

**Comment by berziiii** [comment]
Check your UI. are you defining in your success function for create a new game assigning `app.game = data.game`

**Comment by RoobScoobs** [comment]
So a user can click new game, and the console logs the game object 

``` js
const onNewGame = function (event) {
  event.preventDefault();
  api.createGame()
  .done(ui.success)
  .fail(ui.failure);
};
```

Now I don't know why I can't retrieve a specific game redirecting the URL to  app.host + '/games/' + game.id

**Comment by RDegnen** [comment]
what does your ui.success function look like? that is where the new game data will be returned to

**Comment by RoobScoobs** [comment]
``` js
// edited by @jrhorn424
const success = (data) =>  {
  if(data) {
    console.log(data);
}
```

**Comment by RDegnen** [comment]
data will be the new game returned. you can grab the id there and set it as an app wide variable like brian said before

**Comment by berziiii** [comment]
Update was made. Can you close this @RoobScoobs? If you have other issues, open them. Thanks!

**Comment by berziiii** [comment]
@RoobScoobs, is this closed or open? If open, can you provide more context about what you've tried since yesterday? Thanks.

**Comment by RoobScoobs** [comment]
Got the index and value updating now! Thanks guys!

**Comment by jrhorn424** [comment]
Resolution? @RoobScoobs @berziiii @payne-chris-r @RDegnen
