### ISSUE TITLE
documentation requirement issue

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/game-project#194]
this is just following up on what i wrote in slack... just looking for some clarification.

From the requirements, 

"Visually display the results of retrieving game statistics, such as total games won by a user. (READ)"

I don't see anywhere in the documentation that visualizing the GET games statistics in console is not acceptable... wondering if to fully meet requirement we need to place the game statistics/history on the SPA itself or if "visually" seeing it in console is adequate.  

Thanks, 
Matt :)

**Comment by RDegnen** [comment]
Visually means by if someone who didn't know anything about the console could see game statistics. So somewhere on your page you need to display it, not in the console.

**Comment by mattb5** [comment]
gracias, Ross.
