### ISSUE TITLE
Patch request doesnt update over 

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/game-project#195]
I don't know how to make the PATCH request update the over to true once my game is over. I have a variable that is true or false depending on if its an active game or not. But it doesnt take it. 

Does it need to change? Or is it ok not to use over?

**Comment by jrhorn424** [comment]
@esthercordova What was the resolution for this?

**Comment by esthercordova** [comment]
I send a second request right after the game is finished and instead of updating the game state I just change the over to true.
