### ISSUE TITLE
requirement question

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/game-project#196]
from requirements: 

"Visually display the results of retrieving game statistics, such as total games won by a user. (READ)"

would displaying to SPA the total amount of games played by the user fulfill this requirement?

**Comment by berziiii** [comment]
Number of games played by a user through a get request is the basic requirement. This is different that displaying the ID of the game which was created and returned by the server in the post request. 

Obviously you can do more with the get request object that is returned but displaying the total number of games is the basic one.
