### ISSUE TITLE
The linter is terrible -- do these really need to be corrected?

### ISSUE THREAD

**Issue by shireen-bean** [ga-wdi-boston/game-project#199]
My grunt nag is not happy. Jeff said it needs to be clean but so many of these are not correctable. Also some of them point to a line, and make a complaint about something that does not even exist. 

I don't know how the linter expects me to fix some of my 'warnings':
How do I define the dollar sign?
How do I define 'require'? I tried and it crashed and burned.
It wants me to separate every css rule rather than grouping similar things all at once. Using 'body' here did not work.

```
h1, h2, h3, h4, h5, legend {
  color: $cadet-blue;
}
```

It doesn't like the use of 'let'. I doubt it like 'var' either.

```
const getFormFields = require('../../../lib/get-form-fields');
                               ^ 'require' is not defined.
      5 |const api = require('./api');
                     ^ 'require' is not defined.
      6 |const ui = require('./ui');
                    ^ 'require' is not defined.
      7 |const logic = require('./logic.js');
                       ^ 'require' is not defined.
     15 |  $('#new-game-modal').modal('hide');
           ^ '$' is not defined.
     20 |  $('.wrapper').on('submit','#index0', onMoveHere);
           ^ '$' is not defined.
     21 |  $('.wrapper').on('submit','#index1', onMoveHere);
           ^ '$' is not defined.
```

**Comment by RDegnen** [comment]
Is this your atom linter yelling or just grunt nag?

**Comment by berziiii** [comment]
From what I can see on github, you're missing several files that have information you need. such as .editorconfig, .jscsrc, .jshintrc, .jshinignore, .remarkrc. If you look at your Token Auth api material, you should see those files there. not sure how those files didn't come over when we used that as our template. Any ideas on where they went?

**Comment by shireen-bean** [comment]
Both. Atom yells at me and grunt nag quits halfway through cuz of too much yelling.

Just added in and pushed all the extra files I was missing and it got a bit better. They were missing because I hand copied and pasted everything over using finder which did some weird things

**Comment by berziiii** [comment]
First thing I'm noticing is that when you create a new game, it doesn't reset the turn counter. It keeps going up with every move. I'm looking at why on even games, it keeps the player the same.

**Comment by berziiii** [comment]
And just so you know, you should listen to your linter and nag. You're missing a lot of semi colons that could be causing issues.

**Comment by payne-chris-r** [comment]
Shireen doesn't believe in semi-colons... It's something I've noticed. ;-)

**Comment by shireen-bean** [comment]
all errors corrected.
Only thing hit was:

> > 1 error in 9 files
> > Warning: Task "jshint:all" failed. Use --force to continue.

**Comment by berziiii** [comment]
If adding those files helped with the linter problems, does that mean this is closed @shkherad? If so, please close and reopen if needed.

**Comment by jrhorn424** [comment]
FYI, the Finder doesn't show any files or folders that begin with a dot by default. You have to turn that on through the command line.

**Comment by jrhorn424** [comment]
I'm also under the impression `cp` doesn't touch dotfiles either without a special flag.
