### ISSUE TITLE
Organizing jquery code

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/game-project#20]
I'd like to organize the majority of my jquery-centric code into one "main" file, inside of which I would further organize jquery functions into object literals with names like "playerActions", "menuActions, etc. However, I'm having trouble implementing this model, and I worry that I may be missing something fundamental about how handlers are triggered by events within the browser.

In the code below, I'm trying to set up a simple listener that will log the details of a "square" when it is clicked. The goal is to retrieve the data attached to the clicked square -- row and column -- and pass it to the game logic to check for legality and, if legal, to change the game state. 

```
'use strict'

$(document).ready(

playerActions.moveMade();


);

let playerActions = {
  moveMade: function() {
    $(".square").on("click", function(e) {
      console.log(e);
    })
  }

}
```

**Comment by gaand** [comment]
Have a look at `example.js`.  Also, `require` in `index.js`.

Or paste what you've got in those files here.

**Comment by rchezrutt88** [comment]
```
require('./example');
require('./game-engine');
require('./jqueries');
require('./main')
```

I'm still really confused about how to call functions in my game-engine from my main file.

**Comment by jrhorn424** [comment]
Registration of click handlers usually needs to occur in a document-ready. The registration itself is not a `moveMade`. Instead, the call back is a `moveMade`. I think this makes more sense for what I infer is your goal:

``` js
let playerActions = {
  makeMove: function(event) {
      console.log(event);
  }
};

let init = function () {
  $('.square').on('click', playerActions.makeMove);
};

$(document).ready(init);
```

I've added semicolons in the right place, used single quotes instead of double, and renamed your main method to follow conventional method naming practice.

**Comment by jrhorn424** [comment]
If you've only got things related to pure logic in `game-engine`, you shouldn't be including your "main" stuff inside `game-engine`. Instead, you reference `game-engine` from your main. You use require in main to get a reference to game-engine, then in game-engine you ensure your exporting what you need over in main (or elsewhere).

**Comment by rchezrutt88** [comment]
If you've only got things related to pure logic in game-engine, you shouldn't be including your "main" stuff inside game-engine. Instead, you reference game-engine from your main.

Yes, this is my goal. I suppose I'm confused about how export and require work. What is the purpose of the index file? Do I need to include a require statement in every file that references resources in other files? Does that require statement need a corresponding export object in the file being referenced?

**Comment by gaand** [comment]
To reference all the other JavaScript.  Yes. Usually (not when just adding event handles in the document on ready).

Things exported are available as the return from require.

**Comment by rchezrutt88** [comment]
My main still isn't recognizing my initGame() function. This is how I have it set up: 

```
\\game-engine.js
module.exports = {
  initGame
}
```

```
\\main.js
require('./game-engine');
....
let init = function () {

  initGame();

  $('.square').on('click', playerActions.makeMove);
};

$(document).ready(init);

```

**Comment by gaand** [comment]
Assign the return value of `require('./game-engine');` to a constant.  The you can call it using `constant.initGame()`.

**Comment by rchezrutt88** [comment]
Got it. That works now. 

Still, I’m confused about the best way to structure the main file. I’m nervous about learning bad habits early on and I’m hoping for a nudge in the right direction in regard to best practices.

**Comment by rchezrutt88** [comment]
For instance, given this code 

``` js
let playerActions = {
  makeMove: function(event) {
      console.log(event);
  }
};

let init = function () {
  let game = gameEngine.initGame();
  $('.square').on('click', playerActions.makeMove);
};

$(document).ready(init);
```

the makeMove function will need a reference to the game object. I am unsure how to do this.

**Comment by gaand** [comment]
"Best" practice is context dependent.  An engine is often separated from a UI, separate from network code.  They are joined by callbacks and/or require or both.

Does that help?

**Comment by gaand** [comment]
Store the gameObject and pass it to makeMove?

**Comment by rchezrutt88** [comment]
Still. Con. Fused. Would you mind taking a look at my code after lunch?

**Comment by gaand** [comment]
Sure.

**Comment by rchezrutt88** [comment]
Cool.

I’m right behind this pillar.

**Comment by jrhorn424** [comment]
@rchezrutt88 Can this be closed?

**Comment by rchezrutt88** [comment]
@jrhorn424 I got frustrated and have been working on the css. Now I've returned to the source of my original confusion and it's like I'm seeing it for the first time--that is, I'm still fucking confused. 

I think I need someone to yell in my face about how event handlers work, because I can't for the life of me understand why this won't work. How do I pass the game and player objects to boardClick? 

```
let boardClick = function( event ) {
  let row = event.target.dataset['col'];
  let col = event.target.dataset['row'];
  event.data.game.makeMove(event.data.currentPlayer, row, col);



  currentPlayer === playerX ? currentPlayer = playerY : currentPlayer = playerY;
  console.log(currentPlayer);
}


$(function() {


  let game = gameEngine.Board()
  console.log(game);
  let playerX = gameEngine.Player('x');
  let playerY = gameEngine.Player('y');

  let currentPlayer = playerX;

  $( '.board' ).on('click', {game: game, currentPlayer: currentPlayer}, boardClick );



})
```

**Comment by GA-MEB** [comment]
@rchezrutt88 , can you create a separate issue for this?

**Comment by gaand** [comment]
The scope of `game` is the on ready handler.  You need to put the variable where it is visible to boardClick.

**Comment by rchezrutt88** [comment]
I understand that this is a scope problem. Either I need to declare boardClick somewhere where it’s visible to the event handler or I need to declare the game and player objects somewhere where they are accessible. I just don’t understand where that would be…

**Comment by gaand** [comment]
Talked through some scope issues.

@rchezrutt88 Please close this issue and open a new one if you need additional assistance.
