### ISSUE TITLE
Variable established in ui console log, when passed to api, is undefined

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/game-project#200]
I am trying to update my game state. I have isolated the game id by a ui function, proven successful by console log. 
![image](https://cloud.githubusercontent.com/assets/18650954/15807488/7ceb8bda-2b2d-11e6-8567-ffbb90257dc2.png)
The variable is returned in the same ui function. I then use the returned variable (by executing the function) in AJAX, in the url so it can locate the specific game. 
The AJAX url looks like this:
    url: app.host + "/games/" + ui.createSuccess(),

I also attempted to console.log(createdGame) in the api. Created game was defined in the ui but the api console.log is undefined.
So, to me, this points to some transfer property between ui and api.
const ui = require('./ui.js');
is at the top of my api and I do not have a DOM error saying it cannot read the module.

**Comment by logicmyth** [comment]
Now createdGame is undefined in the ui (variable in screenshot above)

**Comment by berziiii** [comment]
make sure the `./ui` file is required in your ajax file. 

Then in your ajax request, instead of calling `createSuccess()` you should call the name of the value you want.

`url: app.host + "/games/" + data.game.id`

**Comment by computingbets** [comment]
Okay. using the createdGame var got me undefined. Using ui.createdGame got me a 404. It says tictactoc/games/undefined.

**Comment by berziiii** [comment]
Did you export the createSuccess function in your ui file down in the `module.exports`?

**Comment by computingbets** [comment]
Shireen bypassed the ui to api by storing the id in a div class then using the div class instead of the ui variable presented to the api!

**Comment by jrhorn424** [comment]
These notes are for future developers referencing this issue:

Do **not** paste images. Instead, copy and paste errors and code.

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

CC for information only @ga-wdi-boston/core @logicmyth

**Comment by jrhorn424** [comment]
Probably best to avoid storing data as class names. Instead, use jQuery to grab data-attributes.
- https://api.jquery.com/data/
- http://stackoverflow.com/questions/5309926/how-to-get-the-data-id-attribute

@logicmyth @shkherad

**Comment by shireen-bean** [comment]
Yeah, I gave the board an Id in his html just so I knew where it was (before it just had a generic class="row") then I stored the gameId as a value attribute to the game board, and grabbed that value attribute later.

**Comment by shireen-bean** [comment]
^ above comment 
@jhorn424 @logicmyth
