### ISSUE TITLE
Javascript - reset the game board

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/game-project#201]
Hi guys, 

So far I've managed to clear the X's and O's from the board after a user creates a new game. 

``` js
const reset = function () {
   $('.box').empty();
 };

const onNewGame = function (event) {
  event.preventDefault();
  api.createGame()
  .done(ui.newGameSuccess)
  .fail(ui.failure);
  reset();
};
```

However, I still need to reset my variables. 

I have the following global variables:

``` js
// edited by @jrhorn424
let turnCount = 0;
let gameArray = ['','', '', '', '', '', '', '', ''];
```

I have a function that determines the player's turn based on incrementing the turnCount. I also have another function that fills the empty array, matching their position in the game board to the correct index. 

When a user creates a new game, I would like to completely revert to the initial state. 

Is it a matter of redefining the variables in the reset function?

**Comment by berziiii** [comment]
Yes. If you don't, `turnCount` will continue to climb with every box clicked by the user and the `gameArray` may never reset too.

So in one of you functions, probably the one where you create a new game, you'll reset the global variables back to the original state.

**Comment by RoobScoobs** [comment]
Okay, so after resetting the variables:

``` js
// edited by @jrhorn424
const reset = function () {
   let turnCountReset = 0;
   turnCount = turnCountReset;
   let gameArrayReset = ['','', '', '', '', '', '', '', ''];
   gameArray = gameArrayReset;
   $('.box').empty();
 };
```

I have a new TypeError which says that `gameArray.insert is not a function`.

I made the following function to add the X and O values to the game board, and it was working previously.

``` js
// edited by @jrhorn424
gameArray.insert = function (index, move) {
  this.splice(index, 1, move);
};
```

**Comment by jrhorn424** [comment]
``` js
const reset = function () {
   let turnCountReset = 0; // you can't use let here, it's already been defined globally according to your orginal post
   turnCount = turnCountReset;
   let gameArrayReset = ['','', '', '', '', '', '', '', '']; // same thing here
   gameArray = gameArrayReset; 
   $('.box').empty();
 };
```

Instead:

``` diff
const reset = function () {
-   let turnCountReset = 0; 
-   turnCount = turnCountReset;
+  turnCount = 0;
-   let gameArrayReset = ['','', '', '', '', '', '', '', ''];
-   gameArray = gameArrayReset; 
+  gameArray = ['','', '', '', '', '', '', '', ''];
   $('.box').empty();
 };
```

``` js
// Make sure this code is *below* or *required after* whatever does `let gameArray` 
gameArray.insert = function (index, move) {
  this.splice(index, 1, move);
};
```

**Comment by RoobScoobs** [comment]
Issue solved by defining a function that passes an array 

``` js

let insert = function (array, index, move) {
  array.splice(index, 1, move);
};

```
