### ISSUE TITLE
Make it explicit that developers must write their own game engine

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/game-project#202]
Instead of employing a node module.

To be clear, this hasn't happened yet. But I also don't want it to.

**Comment by RealWeeks** [comment]
@jrhorn424 @gaand I would say this is already covered by the following line in the requirement section: `Present working browser game, built by you, hosted on GitHub Pages.` Think it needs a more explicit callout?  Key there is`built by you`

**Comment by jrhorn424** [comment]
A "game" built by you can still use a logic engine built by someone else. I think it needs to be explicit.

I wouldn't want to have to deal with someone using, say, https://www.npmjs.com/package/tic-tac-toe-engine after the fact.

**Comment by RealWeeks** [comment]
@jrhorn424 Added in commit 0d61bee. Thoughts?

**Comment by gaand** [comment]
@J-Weeks Please see my comment on your commit.

Then I'm good with it if  @jrhorn424 concurs.

**Comment by RealWeeks** [comment]
@gaand fixed in latest commit e45ed33

**Comment by gaand** [comment]
@jrhorn424 I'm closing as this seems to address your concern.  If I'm mistaken, please reopen.  Thanks.
