### ISSUE TITLE
Grunt Serve is returning an error

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/game-project#204]
When I try to run Grunt serve from the repo where my game is I get the following error:
ERROR in dlopen(/Users/nataliagalynker/wdi/projects/tic-tac-toe-template/node_modules/node-sass/vendor/darwin-x64-46/binding.node, 1): no suitable image found.  Did find:
    /Users/nataliagalynker/wdi/projects/tic-tac-toe-template/node_modules/node-sass/vendor/darwin-x64-46/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 869936
 @ ./assets/styles/index.scss 4:14-122

**Comment by gaand** [comment]
It's likely that this error is from a previous error running `npm install`.

**Comment by laurenfazah** [comment]
To build on Antony's comment: did `npm install` complete successfully? If you're unsure, do you have a `node_modules` directory in the root of `js-template`? If so, delete that entire directory (`node_modules`) then rerun `npm install`. Do you still have errors from `grunt serve`?

**Comment by natGalynker** [comment]
Thank you, that last bit helped, there was a directory called that which I had to remove.

**Comment by gaand** [comment]
Did you rerun `npm install`?  Did it produce any errors?

**Comment by natGalynker** [comment]
No errors, once I deleted that directory, and re-ran npm install it was behaving properly. Thank you.

**Comment by RealWeeks** [comment]
@natGalynker Please close this issue if your problem was resolved.
