### ISSUE TITLE
jQuery library?

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/game-project#205]
Do we need to download jQuery library?

**Comment by gaand** [comment]
Are you using the `js-template`?

**Comment by NatasaPeic** [comment]
I don't use js-template.

**Comment by NatasaPeic** [comment]
Actually, yes. My apologies. I have all files, I just named it differently.

**Comment by NatasaPeic** [comment]
I asked that because jQuery code for clicking X and Os works within the view source but not from the browser.

**Comment by gaand** [comment]
Have you run `npm install` in the repository you created from the `js-template` as the instructions direct?

**Comment by NatasaPeic** [comment]
Yes. I have done that. My server is running.

**Comment by gaand** [comment]
And you are unable to use jQuery?

**Comment by NatasaPeic** [comment]
Correct. I was only testing jQuery. So, if I write my code in dev tools, and I click it on it, I assign a value, and it works. If I add that code in my main.js and refresh the page, and click on it, it doesn't work. 

I'm not sure if I make any sense.

**Comment by laurenfazah** [comment]
Where is the `main.js` file you're coding in?

**Comment by NatasaPeic** [comment]
It is within the folder where index.html is.
<img width="1680" alt="screen shot 2016-07-25 at 10 28 11 pm" src="https://cloud.githubusercontent.com/assets/19355037/17124163/24353f34-52b7-11e6-82f9-f9b49b78fc16.png">

**Comment by laurenfazah** [comment]
Ah, so that file where it is is not compiling with the rest of your JS files. You'll want to work within `assets/scripts/`, similar to how we did during the jquery-ajax lessons. If you move `main.js` there, look at `assets/scripts/index.js` to see how to load that new file into the JS manifesto.

**Comment by NatasaPeic** [comment]
Got it. Thank you!

**Comment by RealWeeks** [comment]
@NatasaPeic if your problem was resolved can you close the issue please?
