### ISSUE TITLE
can't connect to the endpoint 

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/game-project#206]
when I open the endpoint, it shows doesn't exist.

**Comment by RealWeeks** [comment]
If you simply click the link and open it in your browser it will take you to a rails error page. You are trying to access an API, so it doesn't have a view that is visible to the user (remember how APIs send JSON?). If you make a proper curl request or ajax request to this API endpoint you will be able to send/receive information in the form of JSON.

**Comment by RealWeeks** [comment]
Reference this for more information as well https://github.com/ga-wdi-boston/game-project-api
