### ISSUE TITLE
Sign-in/Sign-up is refreshing

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/game-project#207]
I made sure that preventDefault was called. There are no server issues or errors in the dev tools
I just pushed everything to my git repo page which is https://github.com/natGalynker/tic-tac-toe-game so everything should be up to date.

**Comment by RealWeeks** [comment]
I'm not going to read through all your code.  Please paste in the html for the form, also the click handler for it as well

**Comment by natGalynker** [comment]
I was able to fix the refreshing for everything except for the change player. But when I sign-up and click the Sign up button I get a 400 bad POST request. I can login, change password etc. But that request is bad. 

  <body class="container-fluid">
      <h1>Example</h1>
      <form id="sign-up">
        <fieldset>
          <legend>Sign up!</legend>
          <input type="text" name="credentials[player_name"
          placeholder="player name">
          <input type="text" name="credentials[email]" placeholder="e-mail">
          <input type="password" name="credentials[password]"
          placeholder="password">
          <input type="password" name="credentials[password_confirmation]"
          placeholder="confirm password">
          <input type="submit" name="submit" value="Sign up!">
        </fieldset>
      </form>
      <form id="sign-in">
        <fieldset>
          <legend>Sign in!</legend>
          <input type="text" name="credentials[email]" placeholder="e-mail">
          <input type="password" name="credentials[password]"
          placeholder="password">
          <input type="text" name="credentials[player_name]"
          placeholder="player">
          <input type="submit" name="submit" value="Sign in!">
        </fieldset>
      </form>
      <form id="change-password">
        <fieldset>
          <legend>Change password!</legend>
          <input type="password" name="passwords[old]"
          placeholder="old password">
          <input type="password" name="passwords[new]"placeholder="new password">
          <input type="submit" name="submit" value="Change Password!">
        </fieldset>
      </form>
      <form id="sign-out">
        <fieldset>
          <legend>Log Out!</legend>
          <input type="password" name="passwords[old]"
          placeholder="old password">
          <input type="password" name="passwords[new]"placeholder="new password">
          <input type="submit" name="submit" value="Logout!">
        </fieldset>
      </form>
      <form id="change-player">
        <fieldset>
          <legend>Change Player!</legend>
          <input type="text" name="player_name[old]"
          placeholder="new player">
          <input type="text" name="player_name[new]" placeholder="new player">
          <input type="password" name="credentials[password]"
          placeholder="old password">
          <input type="submit" name="submit" value="Update!">
        </fieldset>
      </form>

use strict';
const getFormFields = require(`../../../lib/get-form-fields`);

const api = require('./api');
const ui = require('./ui');

const onSignUp = function (event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.signUp(data)
  .done(ui.success)
  .fail(ui.failure);
};
const onSignIn = function (event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.signIn(data)
  .done(ui.signInSuccess)
  .fail(ui.failure);
};
const onChangePassword = function onChangePassword(event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.changePassword(data)
  .done(ui.success)
  .fail(ui.failure);
};
const onSignOut = function onSignOut(event) {
  event.preventDefault();
  api.SignOut()
  .done(ui.signOutSuccess)
  .fail(ui.failure);
};
const onChangePlayer = function onChangePlayer(event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.changePlayer(data)
  .done(ui.success)
  .fail(ui.failure);
};

const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp);
  $('#sign-in').on('submit', onSignIn);                                  //grab element from the dom with element
  $('#change-password').on('submit', onChangePassword);  //id on sign-up. Do some action with id
  $('sign-out').on('submit', onSignOut);  
  $('change-player').on('submit', onChangePlayer);  
};

module.exports = {
  addHandlers,
};

**Comment by laurenfazah** [comment]
Can you post your `signIn()` function living in api.js?

**Comment by natGalynker** [comment]
const signUp =  (data) => $.ajax({ 
    url: app.api + '/sign-up',
    method: 'POST',
    data,
});

const signIn = (data) => $.ajax({
  url: app.api + '/sign-in',
  method: 'POST',
  data,
});

**Comment by laurenfazah** [comment]
Is the data you're passing, being passed to `getFormFields`? Also, What does your sign-in form's HTML look like?

**Comment by natGalynker** [comment]
Yes. I have both the functions for signIn and SignOut being passed to getFormFileds:
const onSignUp = function (event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.signUp(data)
  .done(ui.success)
  .fail(ui.failure);
};
const onSignIn = function (event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.signIn(data)
  .done(ui.signInSuccess)
  .fail(ui.failure);
};

Corresponding HTML:
    `<form id="sign-up">
        <fieldset>
          <legend>Sign up!</legend>
          <input type="text" name="credentials[email]" placeholder="e-mail">
          <input type="password" name="credentials[password]"
          placeholder="password">
          <input type="password" name="credentials[password_confirmation]"
          placeholder="confirm password">
          <input type="submit" name="submit" value="Sign up!">
        </fieldset>
      </form>'
      '<form id="sign-in">
        <fieldset>
          <legend>Sign in!</legend>
          <input type="text" name="credentials[email]" placeholder="e-mail">
          <input type="password" name="credentials[password]"
          placeholder="password">
          <input type="submit" name="submit" value="Sign in!">
        </fieldset>
      </form>`

**Comment by gaand** [comment]
@natGalynker Please use fenced code blocks when pasting code fragments as suggested in the `project-issue-tracker-guide`.

**Comment by laurenfazah** [comment]
Could you console.log the data you're sending in your AJAX request?

``` js
const signIn = function(data) {
  console.log(data);
  return $.ajax({
    url: app.api + '/sign-in',
    method: 'POST',
    data,
  });
}
```

**Comment by natGalynker** [comment]
Sorry Antony. I will be doing that in the future. When I put that in console log nothing was printed out, same errors as previously :
jquery.js:9175 POST http://tic-tac-toe.wdibos.com/sign-up 400 (Bad Request)send @ jquery.js:9175ajax @ jquery.js:8656signUp @ api.js:7onSignUp @ handles.js:11dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-07-26 11:54:20.844 jquery.js:9175 XHR finished loading: POST "http://tic-tac-toe.wdibos.com/sign-up".send @ jquery.js:9175ajax @ jquery.js:8656signUp @ api.js:7onSignUp @ handles.js:11dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-07-26 11:54:20.849 ui.js:13 Object {readyState: 4, responseText: "", status: 400, statusText: "Bad Request"}abort: ( statusText )always: ()complete: ()done: ()error: ()fail: ()getAllResponseHeaders: ()getResponseHeader: ( key )overrideMimeType: ( type )pipe: ( /\* fnDone, fnFail, fnProgress _/ )progress: ()promise: ( obj )readyState: 4responseText: ""setRequestHeader: ( name, value )state: ()status: 400statusCode: ( map )statusText: "Bad Request"success: ()then: ( /_ fnDone, fnFail, fnProgress */ )**proto**: Objectfailure @ ui.js:13fire @ jquery.js:3187fireWith @ jquery.js:3317done @ jquery.js:8759(anonymous function) @ jquery.js:9123

**Comment by laurenfazah** [comment]
If nothing console.logged, I'm confused how it was able to still make an AJAX request. Let's walk through this in person after Outcomes.

**Comment by natGalynker** [comment]
The issue was resolved. The email which I was using to sign-up was abc@123.com which was already taken was why I was getting the bad POST request 400 error.
