### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/game-project#208]
I get an error on the page console
Module not found:Error: Cannot resolve 'file' or 'directory' ../app in /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/auth
here is the code in app.js :

'use strict';

const app = {
  api: 'http://tic-tac-toe.wdibos.com',
};

module.exports = app;

**Comment by laurenfazah** [comment]
Could you post the code from the file calling upon app.js? Looks like it's something from /tic-tac-toe/assets/scripts/auth

**Comment by EchoXin** [comment]
client?cd17:47 ./assets/scripts/auth/ui.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../app in /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/auth
resolve file
  /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app doesn't exist
  /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.webpack.js doesn't exist
  /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.web.js doesn't exist
  /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.js doesn't exist
  /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.json doesn't exist
resolve directory
  /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app/package.json doesn't exist (directory description file)
  /Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app doesn't exist (directory default file)
[/Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app]
[/Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.webpack.js]
[/Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.web.js]
[/Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.js]
[/Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/app.json]
 @ ./assets/scripts/auth/ui.js 3:10-27errors @ client?cd17:47sock.onmessage @ client?cd17:82EventTarget.dispatchEvent @ eventtarget.js:51(anonymous function) @ main.js:274SockJS._transportMessage @ main.js:272EventEmitter.emit @ emitter.js:50WebSocketTransport.ws.onmessage @ websocket.js:35

**Comment by EchoXin** [comment]
here is code in  <ui.js>

'use strict';

const app=require('../app');

const success = (data) => {
  console.log(data);
};

const failure = (error) => {
  console.error(error);
};

module.exports = {
  failure,
  success,
  app
};

**Comment by laurenfazah** [comment]
Looks like your `const app=require('../app');` line is not using a correct path to `app.js`. 

Does `app.js` live in the same folder as the file requiring it?

**Comment by EchoXin** [comment]
/Users/xinying/wdi/projects/tic-tac-toe/assets/scripts/auth/app.js

here is the full path of <app.js>
I think it is

**Comment by laurenfazah** [comment]
If it's in the same folder, you'd want to use `const app=require('./app');`

(`./` instead of `../`)

**Comment by EchoXin** [comment]
it works. Thank you so much!!!!!
