### ISSUE TITLE
JS Functions stopped working

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/game-project#21]
I recently installed Bootstrap and added a NAV bar to my HTML and CSS. Now my function:

```
let playerMove = function () {
  $('.box').on('click', function () {
    if(turn % 2 === 0) {
      $(this).text('X');
    }
    else {
      $(this).text('O');
    }
    turn++;
  });
};
```

no longer works. Before bootstrap was installed it would place an X on each box and alternate to an O after an X was placed. Now when I click on the box's nothing happens. It seems like the jQuery function is no longer grabbing the .box class in my html file which connects to all 9 of my boxes.

**Comment by jdamiron** [comment]
I have made no edits to the function itself since it was previously working.

**Comment by RealWeeks** [comment]
Open your chrome inspector and try to plug you jquery in there and see what it is grabbing.

**Comment by RealWeeks** [comment]
note: added backticks to original issue for clarity

**Comment by gaand** [comment]
When you click do you get messages in the console?

**Comment by jdamiron** [comment]
Solution: I declared a global variable and didnt refer back to it in the function.

let playGame = {
  'turn' = 0
}

ex: turn % 2 === 0, should be playGame.turn % 2 === 0.
