### ISSUE TITLE
cannot post to 'http://httpbin.org/post'

### ISSUE THREAD

**Issue by dvdpwll** [ga-wdi-boston/game-project#210]
I'm having trouble getting a POST through to httpbin.org/post.
Error says 404 Not found.

I've tested with curl and it works,

code:

app.js

```
const app = {
  api: 'http://httpbin.org/post',
};
```

api.js

```
const signUp = (data) => $.ajax({
    url: app.api,
    method: 'POST',
    data,
  });
```

events.js

```
const onSignUp = function () {
  $('#sign-up-modal').modal('show');
  $('#sign-up-submit').on('click',function(){

    let data = 'hello!!!!!';
    api.signUp(data)
      .done(ui.success)
      .fail(ui.failure);

    //close modal
    $('#sign-up-modal').modal('hide');
  });
};
```

**Comment by gaand** [comment]
Please post the corresponding `require` and `module.exports` code.

Also, what says  "404 not found"?  Do you know which of `ui.success` and  `ui.failure` are executing?

**Comment by gaand** [comment]
It looks like your code adds a click handler every time `onSignUp` executes.  This may be an unrelated issue.

**Comment by dvdpwll** [comment]
Errors:
Uncaught TypeError: Cannot read property 'done' of undefined @events.js:31
POST http://localhost:8080/ 404 (Not Found) @jquery.js:9175

ui.js:
neither success or failure is running, i put console.logs in both and nothing printed on the console.

app.js

```
'use strict';

const app = {
  api: 'http://httpbin.org/post',
};

module.exports = {
  app,
};
```

api.js

```
'use strict';
const app = require('./app');

const signUp = (data) => { $.ajax({
    url: app.api,
    method: 'POST',
    data,
  });
};

module.exports = {
  signUp,
};
```

events.js

```
'use strict';
const api = require('./api');
const ui = require('./ui');

const getFormFields = require('../../lib/get-form-fields');

//user sign up
const onSignUp = function () {
  //console.log('sign up');
  $('#sign-up-modal').modal('show');
  $('#sign-up-submit').on('click',function(){

    let data = 'hello!!!!!';
    api.signUp(data)
       .done(ui.success)
      .fail(ui.failure);

    //close modal
    $('#sign-up-modal').modal('hide');
  });
};

const addHandlers = () => {
  $('#sign-up').on('click', onSignUp);
};

module.exports = {
  addHandlers,
};

```

**Comment by dvdpwll** [comment]
ui.js

```
'use strict';

const app = require('./app');

const success = (data) => {
  console.log('yes');
  console.log(data);
};

const failure = (error) => {
  console.log('no');
  console.error(error);
};

module.exports = {
  success,
  failure,
};
```

**Comment by RealWeeks** [comment]
what's like 31 in event.js?

**Comment by RealWeeks** [comment]
the original line from where you got the error

**Comment by dvdpwll** [comment]
this is like 31 in events.js:

```
api.signUp(data).done(ui.success).fail(ui.failure);
```

but there's nothing wrong with it, I think.
data is just a string, 
.done just outputs the data (string), 
.fail just outputs the error.

but it doesn't even get to success or failure, b/c i have console logs in and they don't output to the console.
so for some reason it doesn't even run api.signUp

**Comment by gaand** [comment]
A fat arrow function with curly braces returns `undefined` without an explicit `return`.

**Comment by dvdpwll** [comment]
okay, i got rid of the curly braces, and that fixed the .done error. but it still says that httpbin/post is not found

**Comment by gaand** [comment]
Let's have a look.

**Comment by dvdpwll** [comment]
solution:
app.js

```
'use strict';

const app = {
  api: 'http://httpbin.org/post',
};

module.exports = app;
```

the module was outputting an object.

OR

api.js

```
'use strict';
const appVar = require('./app');

const signUp = (data) => { $.ajax({
    url: appVar.app.api,
    method: 'POST',
    data,
  });
};

module.exports = {
  signUp,
};
```

call the app object from the variable appVar

Thanks Antony!
