### ISSUE TITLE
error when sign up

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/game-project#212]
Here is the error when signing up

XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

**Comment by laurenfazah** [comment]
Did your rails server receive the POST request? This looks like your AJAX request was formatted incorrectly.

**Comment by RealWeeks** [comment]
Is there an error before that one? Usually that's the second error you get.

**Comment by gaand** [comment]
The 400 code is most often associated with an e-mails address already in use. 

It might also be mismatched password and password_confirmation.

**Comment by EchoXin** [comment]
it's the first error

 POST http://tic-tac-toe.wdibos.com/sign-up  jquery.js:9175

**Comment by laurenfazah** [comment]
What email are you signing up with? Have you tried it with a unique email address?

**Comment by EchoXin** [comment]
I just tried simple number, like email: 1 password:1

**Comment by laurenfazah** [comment]
The idea is what you're trying might be taken. You're connecting to the same API that hundreds of people have signed up with, so your code for `sign-up` is _probably_ good code, but you're getting a bad request error for not signing up with an email address that is new to the API

**Comment by EchoXin** [comment]
I tried my own email still doesn't work

**Comment by laurenfazah** [comment]
Okay then let's look at it together.

**Comment by EchoXin** [comment]
I have the submit button within a modal. the modal was dissmissed before the submit work. that the reason I can't sign up successful.
