### ISSUE TITLE
Board

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/game-project#214]
Board is clickable, but if I click twice on the same box, X turns into O and vice versa. Not sure how to solve that. 

Any guidance would be appreciated. 

![board](https://cloud.githubusercontent.com/assets/19355037/17152805/711b82be-5347-11e6-9345-5568daf64b02.jpg)

**Comment by gaand** [comment]
You need to store if a square has been clicked and disallow further clicks unless a new game has been created.

**Comment by NatasaPeic** [comment]
I understand what I need to do. But I'm not achieving that.

**Comment by gaand** [comment]
You could have the click handler check to see the value of a displayed square.  Also, you could store the state of the board in an array and check if it's been set (I would use a variation of this).  You can also remove click handlers using the `.off` jQuery method to prevent further clicks.

**Comment by laurenfazah** [comment]
To build on that, what is your jQuery code to set X or O to a square?

**Comment by NatasaPeic** [comment]
Great! off() method worked. Thank you!
