### ISSUE TITLE
how to make two users play?

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/game-project#215]
how can I make two users  play the same time? sign-in the first user, make the move, save the move and sign-out, then sign-in another user?

**Comment by laurenfazah** [comment]
Each player needs to be signed in once, no need to sign out. It's a PATCH request as described here: https://github.com/ga-wdi-boston/game-project-api#update to sign in 2nd player. The API docs then say how to update the game's states with either X or O values for player X or player O
