### ISSUE TITLE
For loop.

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/game-project#217]
I'm trying to use for loop with elements that I selected using jQuery. So, instead of writing multiple if statements, I want to use for loop in 4 directions. Horizontally, vertically and diagonally (in two directions).

Can I use for loop like this?

``` js

for (let i = 1; i < 3; i++) {

   if($("#R + i + C1") === "X" && $("#R + i + C1") === $("#R + i + C2") && $("#R + i + C1") === $("#R + i + C3")){

      console.log("X won!");
    }
```

I tried it, but it doesn't seem to work. How can I fix this?

**Comment by NatasaPeic** [comment]
This should work for all rows.

**Comment by laurenfazah** [comment]
You absolutely can use the loop like that, but be careful with your string concatenation! Look at what you have between double quotes.

**Comment by NatasaPeic** [comment]
Ok. Should I do this:

```
$("#R" + i + "C1")
```

Not sure if this makes sense...

**Comment by NatasaPeic** [comment]
```
$("#R + i " + "C1")
```

This might make more sense.

**Comment by NatasaPeic** [comment]
Neither option works for now...

**Comment by NatasaPeic** [comment]
If I didn't have jQuery, this would work: "R" + i + "1". (checked it)

Any advice would be appreciated.

**Comment by gaand** [comment]
I believe that this should work:

`$("#R" + i + "C1")`

Perhaps assign the string you're building to a variable and console log it?  That way you'll know if the element id you're building is correct.

**Comment by NatasaPeic** [comment]
String is successfully assigned before the for loop.  I checked it. Once loop is started it doesn't console.log my condition. I tried your suggestion too. 

I will try it again.

**Comment by gaand** [comment]
What shows in the console if you put this in the for loop:

``` js
let domId = '#R' + i + 'C1';
console.log(domId);
```

?

**Comment by laurenfazah** [comment]
Also, just a note on your conditional,  you have `if($("#R + i + C1") === "X"`

It is likely that you want to check `if($("#R + i + C1").text() === "X"` or the likes. Otherwise you're checking if the DOM element with at ID literally matches the string "X"

You might want to start with a smaller conditional in the `if` statement, then build up to a more complex one.

**Comment by NatasaPeic** [comment]
If I console.log(domId) I get #R1C1. I tried adding text() which makes sense, but it isn't working either.

If I console.log the value the same box before the for loop, I get whatever I clicked (X or O), but not after the for loop.

**Comment by NatasaPeic** [comment]
Got it! text() did the trick! Thank you!!

**Comment by gaand** [comment]
And you don't get #R2C1?  You should. 

Also, your for loop will stop too early. You could use `i <= 3` as the conditional.

**Comment by NatasaPeic** [comment]
Thank you. I will add i <= 3.

**Comment by NatasaPeic** [comment]
Yes. I got #R1C1 when I did console.log right after the for loop started. It works.
