### ISSUE TITLE
how to get the property of the object when use $.ajax

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/game-project#218]
I try to console.log the user's email, but I get undefined.

///js
 // const signIn = (data) => {
  let user= $.ajax({
    url: app.api +"/sign-in",
    method:'POST',
    data, 
  });
  console.log(user);
  console.log(user.email);
  return user;
};
///

**Comment by laurenfazah** [comment]
Is `user` a variable in the scope that you're trying to console log it from? `undefined` means it's trying to find `user`, but it is not defined in that scope.

**Comment by EchoXin** [comment]
find another way, never mind. Thank you!

**Comment by laurenfazah** [comment]
@EchoXin if this is solved, could you please summarize your solution and close the issue?
