### ISSUE TITLE
[bootstrap] javascript FAILING css PASSS

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/game-project#22]
@nwilcox11 and I have the same issue.

Bootstrap javascript fail after "installing" bootstrap with Jason. We copied and pasted code from BootStrap javascript fails.

Tests:
bootstrap components work. (navigation bar).
bootstrap javascript FAIL! (modals)
No error from grunt serve.

**Comment by RealWeeks** [comment]
to clarify bootstrap-sass right?

**Comment by gaand** [comment]
console errors?  grunt nag?

**Comment by edesilets** [comment]
> bootstrap-sass right?
> CORRECT
> console errors? grunt nag?
> console errors=NONE
> grunt nag=CLEAN

**Comment by GA-MEB** [comment]
'bootstrap-sass' was missing as a dependency (under `vendor`) in `webpack.js`

**Comment by erdesi90562** [comment]
see issue #5

**Comment by jrhorn424** [comment]
Here's the [installation checklist](https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass#install-bootstrap).
