### ISSUE TITLE
Creating an array

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/game-project#221]
I'm trying to push values in an empty array, but no success. When I console.log an array that I'm creating with each click (adding elements one by one using push), I get numbers instead of its value.

![array](https://cloud.githubusercontent.com/assets/19355037/17178455/893274ba-53e3-11e6-9099-be3885336fa7.jpg)

**Comment by laurenfazah** [comment]
Could you post your code for pushing the values into an array?

**Comment by NatasaPeic** [comment]
```
  cell.val("X");

            let newGame = gameBoard.push(cell.val());

            console.log(newGame);

```

cell is already defined and used it for clicking. It is equal to the box I clicked.

**Comment by laurenfazah** [comment]
Is this within a function? Could you post the whole function?

**Comment by NatasaPeic** [comment]
It is within:

```
$("#R1C1, #R1C2, #R1C3, #R2C1, #R2C2, #R2C3, #R3C1, #R3C2, #R3C3").click(function(){

      let cell = $(this);

      if(turn === "O"){

            turn = "X";

            cell.html("<span class='X'><b>X</b></span>");
            cell.val("X");

            let newGame = gameBoard.push(cell.val());

            console.log(newGame);

.........else statement etc.


```

**Comment by NatasaPeic** [comment]
I want to push the values in this array.

```
let gameBoard = [];
```

**Comment by NatasaPeic** [comment]
I'm not sure if I can do that. An array is outside of the function.

**Comment by laurenfazah** [comment]
Have you tried console.logging `cell.val()` to make sure it's what you want to push to the array?

Why are you creating the `newGame` variable? Does it not work to just `gameBoard.push(cell.val());` and `console.log(gameBoard)`?

**Comment by NatasaPeic** [comment]
![array](https://cloud.githubusercontent.com/assets/19355037/17178979/7d7da2fa-53e5-11e6-80ca-900cafefd8ee.jpg)

**Comment by NatasaPeic** [comment]
Yes. I have correct values.

**Comment by laurenfazah** [comment]
But that is from console.logging `newGame`, correct?

**Comment by NatasaPeic** [comment]
I'm creating a variable so I can test it with console.log

**Comment by NatasaPeic** [comment]
No. Console.log new game gives me numbers instead of values.

**Comment by NatasaPeic** [comment]
But if I test each box individually, I get correct values.

**Comment by laurenfazah** [comment]
Well, each time that code runs, `newGame` becomes a new array. It wouldn't continue to store more values as `gameBoard` would.

**Comment by NatasaPeic** [comment]
Oh, let me try that deleting that variable.

**Comment by NatasaPeic** [comment]
Great. Works!

**Comment by NatasaPeic** [comment]
But still not what I want. 

<img width="1664" alt="array push" src="https://cloud.githubusercontent.com/assets/19355037/17179109/0280d756-53e6-11e6-84c5-3b47feffd4df.png">

**Comment by NatasaPeic** [comment]
I would need to have an array with 9 elements, and one that aren't clicked should be empty.

**Comment by NatasaPeic** [comment]
I will try to work on it now. Thanks!

**Comment by laurenfazah** [comment]
Look into how to initialize an array with 9 values. You should then be able to update array by index with the tile clicked.

**Comment by NatasaPeic** [comment]
Thank you!
