### ISSUE TITLE
Help! My modal died 

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/game-project#222]
I have a modal that appears on the click of "Sign Out". Everything was working fine until I began on ajax requests.. but I haven't even started on Sign Out yet only the others. So I'm not sure why that modal is being affected.

**Comment by laurenfazah** [comment]
Code-wise, what have you changed since the modal was working?

**Comment by cdelsoin** [comment]
I've changed the bodies of my Sign Up and Change Password modal to match the code from our API Token Auth training. If I go back to my master branch everything works and I see no difference in code for sign-out

**Comment by laurenfazah** [comment]
Can you post the HTML for your modals? As well as any JS you may have that's involved with showing the modal?

**Comment by cdelsoin** [comment]
`
      <div class="modal fade sign-in-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Welcome! Sign in to get started!</h4>
            </div>

            <div class="modal-body">
                <form id="sign-up">
                  <fieldset>
                    <legend>Sign up!</legend>
                    <input type="text" name="credentials[email]" placeholder="e-mail">
                    <input type="password" name="credentials[password]" placeholder="password">
                    <input type="password" name="credentials[password_confirmation]" placeholder="password confirmation">
                    <input type="submit" class="new-user-button" name="submit" value="Sign up!">
                  </fieldset>
                </form>
                <br> 
                <form id="sign-in">
                  <fieldset>
                    <legend>Sign in!</legend>
                    <input type="text" name="credentials[email]" placeholder="e-mail">
                    <input type="password" name="credentials[password]" placeholder="password">
                    <input type="submit" class="sign-in-button" name="submit" value="Sign in!">
                  </fieldset>
                </form>
              </div>

            </div>
          </div>
        </div>
      </div>



      <div class="modal fade change-password-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Change your Password</h4>
            </div>

            <div class="modal-body">
              <form id="change-password">
                <fieldset>
                  <legend>Change Password</legend>
                  <input type="password" name="passwords[old]" placeholder="old password">
                  <input type="password" name="passwords[new]" placeholder="new password">
                  <input type="submit" class="change-password-button" name="submit" value="Change password!">
                </fieldset>
              </form>

          </div>
        </div>
      </div>



      <div class="modal fade sign-out-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">See ya later!</h4>
            </div>
            <div class="modal-body">
              <p>You've successfully signed out!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            </div>
          </div>
        </div>
      </div>

`

**Comment by cdelsoin** [comment]
``` html

<!-- SIGN IN MODAL -->
      <div class="modal fade sign-in-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Welcome! Sign in to get started!</h4>
            </div>

            <div class="modal-body">
                <form id="sign-up">
                  <fieldset>
                    <legend>Sign up!</legend>
                    <input type="text" name="credentials[email]" placeholder="e-mail">
                    <input type="password" name="credentials[password]" placeholder="password">
                    <input type="password" name="credentials[password_confirmation]" placeholder="password confirmation">
                    <input type="submit" class="new-user-button" name="submit" value="Sign up!">
                  </fieldset>
                </form>
                <br> <!-- just to add space between sign-up and sign-in -->
                <form id="sign-in">
                  <fieldset>
                    <legend>Sign in!</legend>
                    <input type="text" name="credentials[email]" placeholder="e-mail">
                    <input type="password" name="credentials[password]" placeholder="password">
                    <input type="submit" class="sign-in-button" name="submit" value="Sign in!">
                  </fieldset>
                </form>
              </div>

            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
<!-- END SIGN IN MODAL -->

<!-- CHANGE PASSWORD MODAL -->
      <div class="modal fade change-password-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Change your Password</h4>
            </div>

            <div class="modal-body">
              <form id="change-password">
                <fieldset>
                  <legend>Change Password</legend>
                  <input type="password" name="passwords[old]" placeholder="old password">
                  <input type="password" name="passwords[new]" placeholder="new password">
                  <input type="submit" class="change-password-button" name="submit" value="Change password!">
                </fieldset>
              </form>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
<!-- END CHANGE PASSWORD MODAL -->

<!-- SIGN OUT MODAL -->
      <div class="modal fade sign-out-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">See ya later!</h4>
            </div>
            <div class="modal-body">
              <p>You've successfully signed out!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
<!-- END SIGN OUT MODAL  -->

```

**Comment by cdelsoin** [comment]
``` js
'use strict';

const getFormFields = require(`../../../lib/get-form-fields`);

const api = require('./api');
const ui = require('./ui');


//Show and Hide modals on clicks
$(() => {
  $('.sign-in-modal').modal('show');

  $('#sign-in-nav').on('click', function(){
      $('.sign-in-modal').modal('show');
  });

  $('.new-user-button').on('click', function(){
      $('.sign-in-modal').modal('hide');
  });

  $('.sign-in-button').on('click', function(){
      $('.sign-in-modal').modal('hide');
  });

  $('#dropdown-change').on('click', function(){
      $('.change-password-modal').modal('show');
  });

  $('.change-password-button').on('click', function(){
      $('.change-password-modal').modal('hide');
  });

  $('#dropdown-sign-out').on('click', function(){
      $('.sign-out-modal').modal('show');
  });

});

//Modal functionality
const onSignUp = function (event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.signUp(data)
    .done(ui.success)
    .fail(ui.failure);
};

const onSignIn = function (event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.signIn(data)
    .done(ui.signInSuccess)
    .fail(ui.failure);
};

const onChangePassword = function onChangePassword(event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.changePassword(data)
    .done(ui.success)
    .fail(ui.failure);
};





const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp);
  $('#sign-in').on('submit', onSignIn);
  $('#change-password').on('submit', onChangePassword);
  // $('#sign-out').on('submit', onSignOut);
};

module.exports = {
  addHandlers,
};
```

**Comment by laurenfazah** [comment]
In your browser's developer console, what happens when you enter `$('.sign-out-modal').modal('show');`?

**Comment by gaand** [comment]
Have you tried using `git diff` to see what's changed?  This might help isolate problems.

Also, have you used an html pretty printer?  I use `tidy` (`brew install tidy-html5`).

**Comment by cdelsoin** [comment]
_face-palm_ I forgot to close a div under my change password modal. Thanks!
