### ISSUE TITLE
Show a game

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/game-project#223]
How do I pass game id in Ajax request?  It is an ID that was previously created by API.

app.id?

```
const onGetGame = function(event){

  event.preventDefault();

    let gameId = ? ;

    api.show(gameId)
    .done(ui.onSuccess)
    .fail(ui.onError);

};

```

Thank you!

**Comment by laurenfazah** [comment]
The game ID should come back from a successful POST request to `/games`, correct? Are you saving that ID anywhere once it is returned to you?

**Comment by NatasaPeic** [comment]
Correct. It comes back.

**Comment by laurenfazah** [comment]
Are you saving it anywhere? (The `app` object storing the API endpoint might be a good place to store information like this)

**Comment by NatasaPeic** [comment]
I'm saving it once user sign in. Yes.

**Comment by NatasaPeic** [comment]
And create a game obviously.

**Comment by laurenfazah** [comment]
Great. Have you tried accessing the ID from where it's saved to for your AJAX request?

**Comment by NatasaPeic** [comment]
Let me try something before I ask more questions. Thank you.

**Comment by NatasaPeic** [comment]
Hm. Getting 404 status code.

**Comment by laurenfazah** [comment]
Getting a 404 from doing what? And what does the 404 say?

**Comment by NatasaPeic** [comment]
<img width="485" alt="show_game" src="https://cloud.githubusercontent.com/assets/19355037/17190447/d5e89ade-5413-11e6-8311-73e2cf3a9b0c.png">

**Comment by laurenfazah** [comment]
Do you see the URL you're making a GET request from?

**Comment by laurenfazah** [comment]
By that I mean the URL right there next to the 404

**Comment by NatasaPeic** [comment]
This is the URL for GET request:

```
  url: app.api + '/games/' + id,
```

**Comment by NatasaPeic** [comment]
I see that it is undefined.

**Comment by laurenfazah** [comment]
Can I see your `app.api` object? Because for some reason your request is not going to the API endpoint (it's going to localhost:8080)

**Comment by NatasaPeic** [comment]
```
const show = (id) => $.ajax({

      method: 'GET',
      url: app.api + '/games/' + id,
      data: app.game,
});

```

**Comment by laurenfazah** [comment]
In you app file, can I see the `api` object? As in what `app.api` is calling upon in that `show` function

**Comment by NatasaPeic** [comment]
```

const

 app = {
  api:  'http://tic-tac-toe.wdibos.com',
};

module.exports = app;

```

**Comment by NatasaPeic** [comment]
And...

**Comment by laurenfazah** [comment]
Where are you storing the game ID to?

Also, looks like you're missing a token authorization header on your `show` AJAX request.

**Comment by NatasaPeic** [comment]
I will add headers. I stored it onSuccess function when user created a game.

**Comment by laurenfazah** [comment]
It's saved in the function? I'd suggest saving it to the `app` object.

`app.gameId = <game id from response data>`

Then you'll be able to access it from `show()` with

```
const show = () => $.ajax({
      method: 'GET',
      url: app.api + '/games/' + app.gameId,
});
```

**Comment by NatasaPeic** [comment]
Still getting 404 status code. But this time the issue is ID. So, there is the problem. I'm not saving it properly.

**Comment by laurenfazah** [comment]
Again, where are you saving it to?

**Comment by NatasaPeic** [comment]
onSuccess.

```
app.gameId = data.id;

```

**Comment by NatasaPeic** [comment]
Got it.

```
app.game = data.game
```

**Comment by NatasaPeic** [comment]
And then 

```
 url: app.api + '/games/' + app.game.id,
```

in Ajax request.

**Comment by NatasaPeic** [comment]
Thanks!
