### ISSUE TITLE
game update api data

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/game-project#224]
when updating the cell of the game, what kind of data should I use? should I use an array or object?

``` js
const update = function () {
  return $.ajax({
    url: app.api + '/games/' + app.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },

    data: {cells:['x','','','','','','','','']}
  });
};
```

**Comment by laurenfazah** [comment]
Hey Ying - when you wrap your code in backticks, use the ` key above the tab button on your keyboard. You can look at how I edited your comment for reference.

**Comment by laurenfazah** [comment]
But back to your issue, what is the API documentation asking you to send as data for a game update?

**Comment by EchoXin** [comment]
Sorry for that, I use the wrong character.
update a game's states
(This update action expects a PATCH with changes to an existing game)

so if it successful, the response will be like this:

{
  "game": {
    "id": 1,
    "cells": ["x","","","","","","","",""],
    "over":false,
    "player_x": {
      "id": 1,
      "email": "and@and.com"
      },
    "player_o": {
      "id": 3,
      "email":
      "dna@dna.com"
    }
  }
}

**Comment by laurenfazah** [comment]
Yes, that's the response. 

If you look just above that [here](https://github.com/ga-wdi-boston/game-project-api#update-a-games-states), this is the data body expected in the request you make:

``` js
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
```

**Comment by EchoXin** [comment]
it works !!!!! thank you so much!!!!!!!
