### ISSUE TITLE
Win check abnormality

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/game-project#225]
|o| |x|
| |o|x|
| |  |x|   gives me X Wins

| |o|x|
| |o|x|
| | | x|   gives me nothing

``` js
'use strict';

let gameBoardArray = [];
let counter = 0;

const checkWinner = function(){
  if(gameBoardArray[0] === gameBoardArray[1] && gameBoardArray[0] === gameBoardArray[2] ||
    gameBoardArray[0] === gameBoardArray[3] && gameBoardArray[0] === gameBoardArray[6] ||
    gameBoardArray[0] === gameBoardArray[4] && gameBoardArray[0] === gameBoardArray[8]){
      if(gameBoardArray[0] === 'X'){
        console.log('X Wins!');
      }else if(gameBoardArray[0] === 'O'){
        console.log('O Wins!');
      }
  }else if(gameBoardArray[2] === gameBoardArray[4] && gameBoardArray[2] === gameBoardArray[6] ||
    gameBoardArray[2] === gameBoardArray[5] && gameBoardArray[2] === gameBoardArray[8]){
      if(gameBoardArray[2] === 'X'){
        console.log('X Wins!');
      }else if(gameBoardArray[2] === 'O'){
        console.log('O Wins!');
      }
    }else if(gameBoardArray[3] === gameBoardArray[4] && gameBoardArray[3] === gameBoardArray[5]){
      if(gameBoardArray[3] === 'X'){
        console.log('X Wins!');
      }else if(gameBoardArray[3] === 'O'){
        console.log('O Wins!');
      }
    }else if(gameBoardArray[6] === gameBoardArray[7] && gameBoardArray[6] === gameBoardArray[8]){
      if(gameBoardArray[6] === 'X'){
        console.log('X Wins!');
      }else if(gameBoardArray[6] === 'O'){
        console.log('O Wins!');
      }
    }else if(gameBoardArray[1] === gameBoardArray[4] && gameBoardArray[1] === gameBoardArray[7]){
      if(gameBoardArray[1] === 'X'){
        console.log('X Wins!');
      }else if(gameBoardArray[1] === 'O'){
        console.log('O Wins!');
      }
      console.log('broke');
    }
    console.log('broke2');
};

const attachGameLogic = () => {
  let tempIndex;
  $('.game-tile').on('click', function(){
      $(this).off();
       if(counter % 2 === 0){
         $(this).text('X');
         counter++;
       }else{
         $(this).text('O');
         counter++;
     }
     tempIndex = $(this).attr('data-index');
     gameBoardArray[tempIndex] = $(this).text();
     console.log(gameBoardArray);
     checkWinner();
  });
};
```

**Comment by laurenfazah** [comment]
Before I dissect your `if` statement, have you console.logged `gameBoardArray` in both X win scenarios? If they log correctly, the issue likely lies in your conditionals, if they don't log correctly, the issue likely lies in how you're populating `gameBoardArray`.

**Comment by jordanallain** [comment]
Hmm well it should be the same X win scenario, both scenarios have three x's in the right-side column. The only difference is the placement of the O which I couldn't figure out why that would matter. The more times I try the game though the more instances I find of not getting a winner back so I am thinking that maybe I should scrap this whole set up and try to do something else.

**Comment by laurenfazah** [comment]
Well yeah X's would be in the same spot, but that doesn't mean that the tiles themselves couldn't be erroneously logged to the array. I'm just wondering if a log of `gameBoardArray` exactly matches the tiles marked on the gameboard in each scenario. Does that make sense?

**Comment by jordanallain** [comment]
ahh i see yes that makes sense. i'm a little confused about how my array is showing up in the console. 
[1: "O", 2: "X", 4: "O", 5: "X", 8: "X"]
is what gets printed when X should be winning in columns 2 5 and 8. it looks weird with the numbers inside the array like that i wasn't exactly sure what that meant but I assume it was just showing the index value before it.

**Comment by jordanallain** [comment]
["O", 2: "X", 4: "O", 5: "X", 8: "X"]

is what prints in the working scenario so just the first O is moved over one slot.

**Comment by laurenfazah** [comment]
The way this is printing is super confusing. Is that a copy-paste from the console? Does it look any different if you were to screenshot it?

**Comment by jordanallain** [comment]
looks just like that only some of the characters are different colors

**Comment by jordanallain** [comment]
<img width="429" alt="screen shot 2016-07-27 at 7 33 13 pm" src="https://cloud.githubusercontent.com/assets/18097107/17196223/05b46078-5431-11e6-88ad-b0fb7267d8d8.png">

**Comment by jordanallain** [comment]
the broke2 is just a console log to check where i am getting in the if else

**Comment by laurenfazah** [comment]
I believe this has to do with how you're initializing your array. I think you should use the array constructor (`new Array(9)`), to initialize it with 9 undefined values, then update them by index.

**Comment by jordanallain** [comment]
i changed

``` js
let gameBoardArray = [];
```

to

``` js
let gameBoardArray = new Array(9);
```

but got the same result, was that what you meant or did i have to change something elsewhere?

**Comment by gaand** [comment]
How are you setting values in the array?

**Comment by laurenfazah** [comment]
Yeah that's what I meant. But it's still logging the same? That's really strange.

**Comment by jordanallain** [comment]
i set the cells of the board to each have a data-index that corresponds to the index of the array. 
i.e.

``` html
<div data-index = '0' class="game-tile tile-a"></div>
```

then i set tempIndex to equal that number. then used it as the index value of the array to make it equal to the text in the cell.

``` js
     tempIndex = $(this).attr('data-index');
     gameBoardArray[tempIndex] = $(this).text();
```

**Comment by laurenfazah** [comment]
That looks like it should work fine. Ignoring the console.log() of the array, maybe the issue lies in your conditional. I'm going to comb a bit.

**Comment by jordanallain** [comment]
My thought is that the first if statement evaluates to true if the cells in the first column are all blank. So the if statement inside that checks if the value is x or o but neither of those would be true if the cells were blank even though they would be equal. So would that end my whole if statement?

**Comment by jordanallain** [comment]
Should I just put the rest of the if statement in another else if branching off the first part? Actually I will just try this and let you know.

**Comment by gaand** [comment]
Have you tried methodically walking through your logic with those two e ankles to see how the conditions differ?  I'm on my phone so it's a bit tough for me to follow the code.

**Comment by gaand** [comment]
Examples.

**Comment by jordanallain** [comment]
i believe what i said earlier was correct. in the first if statement i check to see if the values are the same, and if they are i check to see if they are all x or all o but if they are all blank it had nowhere else to go inside the if statement.

i altered it a bit and was able to make it recognize the X win scenario that it did not recognize earlier. it still is missing some but i think with this new knowledge i'll be able to also finagle the rest of the code to work....hopefully. i have to get on the train and go home now before i do all that though or i'll never get any dinner.

**Comment by gaand** [comment]
Eating is important.  Also sleeping.

We should chat in the morning about "hand simulating" a technique for checking your logic.

**Comment by jordanallain** [comment]
Sounds good sorry I got that issue in so late today.

**Comment by jordanallain** [comment]
Closing issue. I made an error in the logic of my If statement and I must refactor it completely.
