### ISSUE TITLE
Cannot get game tiles to show images

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/game-project#226]
I can't seem to figure out why my images are not popping up on my tiles once I click them.  

I've got the images that I'm using for my x's and o's each declared to it's own variable as such:

``` js

const toePic = ('../../toe-pic.jpg');
const ticTacPic = ('../../tic-tac-pic.jpg');

```

This is in my events.js folder.

I have click event connected to my function that should get this going, but I can seem to figure it out.  Here is my click event:

``` js

$('.game-tile').on('click', onMove);

```

The onMove function is as follows:

``` js

const onMove = function () {
  // console.log(toePic);
  let tile = $(this);
  tile.css("background-image" , toePic);
};

```

I feel like I've tried everything.  I get a response on my console when I do the console.log, but when I try and do the function I get no response.

**Comment by laurenfazah** [comment]
Have you looked into CSS's `background-image` property? The value it takes looks like this: `url("path/to/image.jpg")`.

**Comment by jlmitch1989** [comment]
I tried that also and it tells me url is undefined

**Comment by laurenfazah** [comment]
With webpack, you'll want to write out the path to the image from the root of the repository (assets/styles/toe-pic.jpg)

**Comment by jlmitch1989** [comment]
So I can't use the "../../" path like I did above?

**Comment by gaand** [comment]
Do you get any error messages in the chrome console?

**Comment by jlmitch1989** [comment]
![screen shot 2016-07-25 at 2 17 10 pm](https://cloud.githubusercontent.com/assets/19956362/17197149/1397179c-5438-11e6-9683-1aaebd81b4aa.png)

**Comment by jlmitch1989** [comment]
after changing my path for the picture to (assets/styles/toe-pic.jpg), and running the code, my console spits this out:

![screen shot 2016-07-27 at 8 23 30 pm](https://cloud.githubusercontent.com/assets/19956362/17197159/28b97a5c-5438-11e6-8973-d4ee82110c81.png)

**Comment by laurenfazah** [comment]
Can you show your `tile.css()` code as it currently is?

**Comment by jlmitch1989** [comment]
is this what you mean?

``` css

.title {
  margin-bottom: 5%;
  margin-left: -53px;
  overflow: hidden;
  text-align: center;
}


```

**Comment by laurenfazah** [comment]
Nope, the update of what you showed here before:

``` js
const onMove = function () {
  // console.log(toePic);
  let tile = $(this);
  tile.css("background-image" , toePic);
};
```

**Comment by jlmitch1989** [comment]
This is what I currently have:

``` js

const onMove = function () {
  // console.log(toePic);
  let tile = $(this);
  $(this).css("background-image" , "url(toePic)");
};
```

**Comment by laurenfazah** [comment]
Ah, so see how the 404 was trying to find an image at localhost:8080/toePic?

Look at your string concatenation. The variable `toePic` is getting lost to the string you're putting it in.

**Comment by jlmitch1989** [comment]
Well I tried url("toePic") and the console tells me the "url is undefined"

**Comment by laurenfazah** [comment]
The idea is we don't want `toePic` in quotes.  Something like:

``` js
const onMove = function () {
  // console.log(toePic);
  let tile = $(this);
  $(this).css("background-image" , "url(" + toePic + ")");
};
```

should get you closer.

**Comment by jlmitch1989** [comment]
Ok I did that but I'm still getting this error in my console:

![screen shot 2016-07-27 at 8 23 30 pm](https://cloud.githubusercontent.com/assets/19956362/17197459/e1ce400c-543a-11e6-9d6c-1eb00a4a5f44.png)

**Comment by laurenfazah** [comment]
It still seems to be taking the `toePic` variable as a literal string. How is `toePic` defined? Can you show me that updated code?

**Comment by jlmitch1989** [comment]
``` js
const toePic = ('assets/styles/toe-pic.jpg');
const ticTacPic = ('../../tic-tac-pic.jpg');

```

**Comment by laurenfazah** [comment]
In that case, I believe your strings are concatenating without the necessary quotations around the image path.

`"url(assets/styles/toe-pic.jpg)"`
instead of:
`"url('assets/styles/toe-pic.jpg')"`

Try a little single quote action:

`'url("' + toePic + '")';`

**Comment by jlmitch1989** [comment]
I tried this random picture from a url and it works:

"url(http://i.imgur.com/iVfCqyp.jpg)");

**Comment by gaand** [comment]
Not the alternation of quotes in @laurenfazah 's comment.  This is a way to get quotes into quoted strings.

**Comment by jlmitch1989** [comment]
I'm getting the same error in my console with both:

``` html
"url(assets/styles/toe-pic.jpg)"
'url("' + toePic + '")';
```

**Comment by laurenfazah** [comment]
It's still saying a 404 for localhost:8080/toePic? Are there any errors on your terminal window where `grunt serve` is running?

Could you save `'url("' + toePic + '")'` to a separate variable and pass that new variable to background image?

**Comment by jlmitch1989** [comment]
I figured it out with the help of a fellow developer!  I had "styles" in the path.  The true path for the image was ('assets/toe-pic.jpg') not ('assets/styles/toe-pic.jpg').  Of course it was something RIGHT IN FRONT OF MY FACE.  Thank you for the help!
