### ISSUE TITLE
PATCH

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/game-project#227]
If I successfully show my game, and I store the data onSuccess, can I use that data in my Ajax request for update?

```
const getSuccess = (data) => {

  app.game = data.game;
  console.log(data.game);

};
```

**Comment by NatasaPeic** [comment]
For Ajax request, can I pass data like this?

```
data: data.game,
```

**Comment by NatasaPeic** [comment]
I understand I need to pass my array for each move, index and value. I have an array that gets updated with each move. I could use that, putting key and values as separate variables, but I'm thinking if I can skip that.

**Comment by laurenfazah** [comment]
As long as you're updating that game object in some way that still matches what the API expects in the response, it should be fine. 

Have you tried this yet?

**Comment by NatasaPeic** [comment]
Yes. It doesn't work.

**Comment by gaand** [comment]
Please post the code from your patch.  Please include the data you're sending.

**Comment by NatasaPeic** [comment]
```
const update = () => $.ajax({

  method: 'PATCH',
  url: app.api + '/games/' + app.game.id,

  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
  data: app.game,
});

```

```
const getSuccess = (data) => {

  app.game = data.game;
  console.log(data.game);

};

```

**Comment by NatasaPeic** [comment]
I understand that data should look like this: 

```
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}

```

I have an array within my game logic that gets updated with each move. I tried making two separate variables, one for key(index) and one for value(value). I should be passing that as my data, but really not sure how to do that.

**Comment by laurenfazah** [comment]
Have you put a console log in your `update` function to see what `app.game` is structured like? (Before it's sent by AJAX)

**Comment by NatasaPeic** [comment]
Yes. There is a console.log when I show my game. 

```
const getSuccess = (data) => {

  app.game = data.game;
  console.log(data.game);

};
```

<img width="1108" alt="patch" src="https://cloud.githubusercontent.com/assets/19355037/17213992/e5e65958-54a4-11e6-80e1-47d170b3fade.png">

**Comment by gaand** [comment]
Your saved game does not match the format of the data required.  You need to construct an object formated as the PATCH request expects.

**Comment by laurenfazah** [comment]
So that log is your whole game object. It is different in structure from what the PATCH request looks requires. 

The PATCH object is really just updating the game array by index, and notifying whether the game is finished or not.

**Comment by laurenfazah** [comment]
Exactly as Antony said.

**Comment by NatasaPeic** [comment]
Ok. Thanks. Working on that.

**Comment by EchoXin** [comment]
<img width="580" alt="screen shot 2016-07-28 at 10 42 58 am" src="https://cloud.githubusercontent.com/assets/18298098/17216805/17c0fec8-54b0-11e6-92e7-46e8429a22b8.png">

is it the correct data format of the game object?

**Comment by laurenfazah** [comment]
@EchoXin That is the correct object for an entire game. Not the correct object for sending a PATCH request to update the game.

**Comment by NatasaPeic** [comment]
I'm finally able to extract keys and values from the array I'm creating(updating) after each click.

I would like to use those two variables in my Ajax request. 

I tried module export and I placed those two variables, but I get an error that said "variables aren't defined".

**Comment by gaand** [comment]
Please post the code that sets the variables and the `module.exports` statement.

**Comment by NatasaPeic** [comment]
```
    let index = cell.data("index");
    let value = cell.val();

                        console.log(index);
                        console.log(value);

```

This is the code that sets variables.

**Comment by NatasaPeic** [comment]
The code that updates an array is super long because I used if statements, but it works.
<img width="1256" alt="index_value" src="https://cloud.githubusercontent.com/assets/19355037/17229115/29781910-54e4-11e6-8a4c-a60389a19035.png">

**Comment by laurenfazah** [comment]
Have you tried passing the variables to the AJAX request function as parameters?

**Comment by NatasaPeic** [comment]
Yes. It said it wasn't defined.

**Comment by laurenfazah** [comment]
Where are those variables defined in relation to the function they'd be passed to? Can you post related code?

**Comment by NatasaPeic** [comment]
Those variables are within main.js. And I need them in api.js.

**Comment by laurenfazah** [comment]
Is main.js requiring api.js? Is api.js requiring main.js? Might you have a circular dependency?

**Comment by NatasaPeic** [comment]
Most likely... I will try to fix that. Thank you.

**Comment by NatasaPeic** [comment]
Summary:

Game is now updated on each click. I had my array updated on each click as well as variables (index and value) in main.js. 

api.js is now required in main.js.  So, I was able to use api.update() function in main.js while passing index and value that I previously got.

Like this:

``` main.js
                        let index = cell.data("index");
                        let value = cell.val();

                        api.update(index, value)
                        .done(ui.onUpdate)
                        .fail(ui.onError);

```

Then I passed those variables in update function within api.js

``` api.js
const update = (index, value) => $.ajax({

      method: 'PATCH',
      url: app.api + '/games/' + app.game.id,

      headers: {
      Authorization: 'Token token=' + app.user.token,
  },
      data: {
           "game": {
            "cell": {
           "index": index,
           "value": value,
                        },

  }
}
});
```

Thank you!!!!
