### ISSUE TITLE
PATCH issue with change password

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/game-project#228]
XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/change-password1210. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.

relevant JS:

```
const changePassword = (data) => $.ajax({
  url: app.api + '/change-password' + app.user.id,
  method: 'PATCH',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
    data,
});



const onChangePassword = function onChangePassword(event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.changePassword(data)
  .done(ui.success)
  .fail(ui.failure);
};



$('#change-password').on('submit', onChangePassword);
```

**Comment by laurenfazah** [comment]
Look closely at the URL you're making the request to: http://tic-tac-toe.wdibos.com/change-password1210

**Comment by natGalynker** [comment]
I don't see it.  Is it how I am doing the authorization header? I have tried checking it against the token auth training we did

**Comment by laurenfazah** [comment]
Nope, literally the URL you're making the request to. http://tic-tac-toe.wdibos.com/change-password1210

There is a typo there, but I want you to find it :)

**Comment by natGalynker** [comment]
Ive literally lined those two up  
http://tic-tac-toe.wdibos.com/sign-in
http://tic-tac-toe.wdibos.com/change-password1210
The only which I see which is different is there should be a / between password and id#

**Comment by laurenfazah** [comment]
That is correct. Have you tried making a request with that fixed?

**Comment by natGalynker** [comment]
Yes, I have tried adding it multiple times both inside and out of the quote. When I put it before the + sign it returned an OPTIONS error instead of PATCH that was the only difference

**Comment by laurenfazah** [comment]
Can you post your updated `changePassword()` function as well as the OPTIONS error?

**Comment by natGalynker** [comment]
```
const changePassword = (data) => $.ajax({
  url: app.api + '/change-password/'  + app.user.id,
  method: 'PATCH',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
    data,
});
```

this returned the PATCH error I first encountered

```
const changePassword = (data) => $.ajax({
  url: app.api + '/change-password' / + app.user.id,
  method: 'PATCH',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
    data,
});
```

returned this error: 
jquery.js:9175 OPTIONS http://tic-tac-toe.wdibos.comnan/ net::ERR_NAME_NOT_RESOLVEDsend @ jquery.js:9175ajax @ jquery.js:8656changePassword @ api.js:21onChangePassword @ handles.js:25dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-07-28 10:25:53.675 jquery.js:9175 XHR failed loading: PATCH "http://tic-tac-toe.wdibos.comnan/".send @ jquery.js:9175ajax @ jquery.js:8656changePassword @ api.js:21onChangePassword @ handles.js:25dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549

**Comment by laurenfazah** [comment]
You still need to concatenate that trailing slash in with the rest of your `/change-password` string. Right now, that's just a free floating slash.

**Comment by natGalynker** [comment]
I did. when I integrate it to follow the change-password, like so /change-password/' +app.user.id

PATCH error returns

**Comment by gaand** [comment]
What's the error?

**Comment by laurenfazah** [comment]
This returned the original error? This looks like it's properly concatenated. Could you please post the error returned from using this?

``` js
const changePassword = (data) => $.ajax({
  url: app.api + '/change-password/'  + app.user.id,
  method: 'PATCH',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
    data,
});
```

**Comment by natGalynker** [comment]
tic-tac-toe.wdibos.com/change-password/1210:1 PATCH http://tic-tac-toe.wdibos.com/change-password/1210 
2016-07-28 10:31:33.709 localhost/:1 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/change-password/1210. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

**Comment by natGalynker** [comment]
Oh, slightly different. 400 not 404

**Comment by RealWeeks** [comment]
what is data, can you paste in the console log or the response from a mirror JSON api?

**Comment by RealWeeks** [comment]
Console.log data after this line

``` js
const onChangePassword = function onChangePassword(event) {
  let data = getFormFields(this);
//what is data here
```

**Comment by laurenfazah** [comment]
Also worth logging `app.user.token` to make sure the Authorization header is properly working.

**Comment by natGalynker** [comment]
I think that is where the issue is. When I logged that just now, the token didn't print out

**Comment by gaand** [comment]
Without a token you'd get a 401.

**Comment by natGalynker** [comment]
got both the token and the id and the data all to print to console

**Comment by laurenfazah** [comment]
Can you post what the data object looks like?

**Comment by natGalynker** [comment]
``` js
Object {credentials: Object, password: Object, submit: "Update!"}
credentials
:
Object
email
:
"v@t.com"
__proto__
:
Object
password
:
Object
new
:
"123abc"
old
:
"abc123"
__proto__
:
Object
submit
:
"Update!"
__proto__
:
Object
__defineGetter__
:
__defineGetter__()
__defineSetter__
:
__defineSetter__()
__lookupGetter__
:
__lookupGetter__()
__lookupSetter__
:
__lookupSetter__()
constructor
:
Object()
hasOwnProperty
:
hasOwnProperty()
isPrototypeOf
:
isPrototypeOf()
propertyIsEnumerable
:
propertyIsEnumerable()
toLocaleString
:
toLocaleString()
toString
:
toString()
valueOf
:
valueOf()
get __proto__
:
__proto__()
set __proto__
:
__proto__()
```

**Comment by RealWeeks** [comment]
is data all of that? / do you format any of it to fit the api specifications for sending a patch to change-password?

**Comment by natGalynker** [comment]
nope just the username and passwords

**Comment by gaand** [comment]
Please post the html for the change password form.

**Comment by natGalynker** [comment]
```
<div class="modal fade" id="changePwModal" tabindex="-1" role="dialog" aria-labelledby="changeModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="changeModalLabel">Change Password</h4>
          </div>
          <div class="modal-body">
            <div class= "input-group">
              <form class="form-group" id="change-password">
                <input type="text" class="form-control email"
                name="credentials[email]" placeholder="e-mail">
                <input type="password" class="form-control password"
                name="password[old]" placeholder="old password">
                <input type="password" class="form-control confirm-password"
                name="password[new]"
                placeholder="confirm password">
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <input type="submit" class="change-password" name="submit" value="Update!">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
```

**Comment by laurenfazah** [comment]
From the API documentation:

> The changepw action expects a PATCH of `passwords` specifying the `old` and `new`.

Looks like you're feeding to the API `credentials` and `password` as data properties. I'd suggest tweaking your change password form to match what the API expects.

**Comment by natGalynker** [comment]
the only credentials are from the email field
the old password is being done by password[old]
the new by password[new] 
I can remove the email field.

**Comment by laurenfazah** [comment]
Correct, you don't need the email's credentials field. The token tells the API who the user is.

And yes, you're using `password[old]` and `password[new]`, but like I showed you the API documentation says, `passwords[old]` and `passwords[new]` are what are needed here. 

I want to strongly urge you to pay more attention to details here. The API (and code in general) can't interpret what you meant. It can only successfully receive data in the format that's been laid out in the documentation.

**Comment by natGalynker** [comment]
Issue Fixed!
