### ISSUE TITLE
Confusion on making a getWinner function

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/game-project#229]
I'm hitting a wall on trying to figure out how to make a function which gets the winner.  
Here's my game logic so far:

``` js

let counter = 1;

// GAME LOGIC
const onTurn = function () {
  let tile = $(this);
  if (tile.attr('style')) {
    return;
  }else {
    if (counter % 2) {
      //first person logic
      $(this).css("background-image" , 'url("' + ticTacPic + '")');
      console.log('first person');
    }else {
      //second person logic
      $(this).css("background-image" , 'url("' + toePic + '")');
      console.log('second person');
    }
      counter ++;
      console.log('The count is ' + counter);
    if (counter < 3) {
      return;
    }
    //Check for winner function
    const getWinner = function() {

    }
    }
};

```

I guess I just don't understand how I need to build this function, which has been my biggest issue since starting this program.

**Comment by gaand** [comment]
After each turn you want to check to see if the current player has won until a "cat's game".

So, getWinner could check the state of the board for three in a row.  

Handling a tie could happen there or in a different way.

**Comment by gaand** [comment]
I'm assuming onTurn is the click event handler for your "tiles".

**Comment by jlmitch1989** [comment]
This is my click event:

``` js
$('.game-tile').on('click', onTurn);
```

**Comment by gaand** [comment]
Right.  So after every click what do you want to do other than mark the tile?

You need to keep track or check for 3 in a row.

**Comment by jlmitch1989** [comment]
No I understand that I'm going to be looking for three in a row, three in a column, and three in a diagonal. I just don't understand how to build up a function that does so.

**Comment by gaand** [comment]
Start by building a function that just does one of those.

What does it need to know in order to check for three in a row?  

If you can see three in a row, can your code check for it?

**Comment by jlmitch1989** [comment]
If even or odd turns are in a row?

**Comment by RealWeeks** [comment]
@gaand I'm going to self-assign

**Comment by gaand** [comment]
Your setting the background image.  Could you set something else, on the element or in your code, to record which player has played which tile?

You could use a data attribute on the element or an array in your code.

**Comment by RealWeeks** [comment]
Discussed ways to figure out game logic and possible solutions. Encouraged Josh to make a list of things to do to check the the winner, then break that list into smaller subtasks and tackle the problem that way.  Also advised if he is spending a lot of time spinning his wheels to comment/open an issue.

**Comment by laurenfazah** [comment]
@jlmitch1989 I believe this is resolved, yes? Could you close when you can? Thanks!
