### ISSUE TITLE
Can't call .every on board array

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/game-project#23]
**Linter Output:**

```
Running "jshint:all" (jshint) task
>> 3 files lint free.

Running "jsonlint:all" (jsonlint) task
>> 6 files lint free.

Running "jscs:status" (jscs) task
>> 3 files without code style errors.

Done, without errors.
```

**Issue Description:**
I have an array created by calling the children of a div with the class of "board"
`var board = $('.board').children();`
I created a function to check a square to see if it is not blank:

```
  var squareIsFull = function squareIsFull(element) {
    return element !== '';
  };
```

Later, I tried to use .every inside if statement to see if the board is full and do something if so

```
    if (board.every(squareIsFull())) {
      tieBoard();
      return true;
    }
```

That throws an error:
`Uncaught TypeError: board.every is not a function`

This is the only thing that's not working. So far all the google results point me towards how to use every, but I think I'm using it correctly...

**Comment by jrhorn424** [comment]
`.every()` is defined by JavaScript ([Array.prototype.every()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)). We can only use it on arrays.

`.children()` is [defined by jQuery](https://api.jquery.com/children/). We can see that it return a [jQuery object](http://api.jquery.com/Types/#jQuery). jQuery objects are not arrays.

<img width="887" alt="_children_____jquery_api_documentation" src="https://cloud.githubusercontent.com/assets/388761/12793405/7c57536c-ca7e-11e5-8e93-5445c59cda81.png">

I don't know whether this is a "good" idea, but you could try using [.toArray()](https://api.jquery.com/toArray/).

Please close this issue if this helps you get unstuck.

**Comment by apalmer0** [comment]
Ah okay, thanks! Still stuck but now I've got some ideas.
