### ISSUE TITLE
Create Game AJAX function not working

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/game-project#230]
My AJAX function to create a new game isn't working when I try to test it in the Chrome console after signing in (which does work).

``` js
const createGame = function () {
  return $.ajax({
    url: 'http://tic-tac-toe.wdibos.com/games',
    headers: 'Authorization: Token token=997fe814b538a20727907e7a667a525a',
    method: 'POST',
    dataType: 'json',
    data: "{}",
  });
};
```

I receive the error 401 (Unauthorized).

I haven't made the token a variable yet (need to figure that out) but am replacing the token in the function with current token upon logging in.

What am I doing wrong?

**Comment by RealWeeks** [comment]
Is the hard coded token the exact same token you get right after logging in? IE; you didn't log in more than once, and this token isn't old?

**Comment by laurenfazah** [comment]
Since POST doesn't require a request body, I'd try making a request without `dataType` and `data` properties.

**Comment by RealWeeks** [comment]
also seems like the format for headers looks like this:

``` js
headers: {
    Authorization: 'Token token=' + app.user.token,
  },
```

**Comment by gabescarbrough** [comment]
``` js
const createGame = function () {
  return $.ajax({
    url: 'http://tic-tac-toe.wdibos.com/games',
    headers: {
    Authorization: 'Token token=' + '2e4743eb991a6abfe75ee859671a9203',
  },
    method: 'POST',
  });
};
```

Seems to have worked. Gave me a 201 created. The object it returned has a ton more info than the cURL request gave me though. What's up with that? I was comparing with Jordan and he was getting what I expected to get, which looks like what's in the docs.

**Comment by gabescarbrough** [comment]
And yes I'm using the token given upon login.

**Comment by laurenfazah** [comment]
What do you mean by "ton more info"? What does it look like?

**Comment by gabescarbrough** [comment]
If you come to the classroom I can show you. Tried to copy and paste but it doesn't format correctly.

**Comment by gabescarbrough** [comment]
Talked to Lauren and discovered I was getting more info than I expected because it wasn't being processed by the event handler.
