### ISSUE TITLE
win condition wont log 

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/game-project#231]
Ive tested my win condition in the console and it "works" but when I actually play the game it doesn't  log the win in the console. Ive tried return & console.log. ive written out all of the win conditions but they're all pretty similar to this.

``` js
let playerX = 'x';

const rowsWinnerX = function rowsWinnerX() {
  return (($('#tile1x1').text() === playerX) && ($('#tile1x2').text() === playerX) && ($('#tile1x3').text() === playerX)) ||
         (($('#tile2x1').text() === playerX) && ($('#tile2x2').text() === playerX) && ($('#tile2x3').text() === playerX)) ||
         (($('#tile3x1').text() === playerX) && ($('#tile3x2').text() === playerX) && ($('#tile3x3').text() === playerX));
};
```

**Comment by cdelsoin** [comment]
previously i tried this and it also didnt work.

``` js
const rowsWinnerX = function rowsWinnerX() {
  if (
    (($('#tile1x1').text() === playerX) && ($('#tile1x2').text() === playerX) && ($('#tile1x3').text() === playerX)) ||
    (($('#tile2x1').text() === playerX) && ($('#tile2x2').text() === playerX) && ($('#tile2x3').text() === playerX)) ||
    (($('#tile3x1').text() === playerX) && ($('#tile3x2').text() === playerX) && ($('#tile3x3').text() === playerX))
  ) {
  console.log('X is the Winner');
    }
};
```

**Comment by gaand** [comment]
How/where are you invoking `rowsWinnerX`?

**Comment by laurenfazah** [comment]
Do you have an `else` condition that you're logging a message in to make sure the conditional is being hit? Also, what is the value of `playerX`?

`return` won't print anything to your chrome console, `console.log` will.

**Comment by cdelsoin** [comment]
I've tried calling on it with this event listener 
$('.game-tile').on('click', rowsWinnerX());

**Comment by laurenfazah** [comment]
Try not invoking the function in the event listener (remove parens).

**Comment by cdelsoin** [comment]
i was hoping that this would work but nope

``` js
const rowsWinnerX = function() {
   if ( (*condition || condition || condition*) === true) {
     console.log('Winner!');
   }
};
```

**Comment by cdelsoin** [comment]
i removed the function from the event listener and it did not work

**Comment by RealWeeks** [comment]
post the listener you have now

**Comment by gaand** [comment]
Do you have an event handler for click on your tiles?  Does it set the text of the tiles?

Each click is a move and I think you want to check for a win after each move.

**Comment by cdelsoin** [comment]
``` js
let clicks = 0;

$('.game-tile').on('click', function(){
  $(this).off();
  if (clicks % 2 === 0) {
    $(this).text('x');
    clicks++;
  } else {
    $(this).text('o');
    clicks++;
  }
});
```

**Comment by gaand** [comment]
So, I think you want to check for a winner in something called from that function.

**Comment by RealWeeks** [comment]
Did what @gaand suggested. Seems to work well when I tested it, but @cdelsoin thinks there are underlying bugs.  As he progresses with it those will come more to light.

**Comment by laurenfazah** [comment]
@cdelsoin is this still an issue? Could you close if not? Feel free to ask further questions or reopen down the road should it persist.
