### ISSUE TITLE
JSON.parse not working, .stringify is working.  Why?

### ISSUE THREAD

**Issue by alex-braun** [ga-wdi-boston/game-project#232]
I am trying to get ahold JSON and turn it into an object.  .stringify is functioning when I alert a message, displaying a string, but .parse is giving me a  "Unexpected token o in JSON at position 1."

```
let jsonObject;
const gamesShow = (data) => $.ajax({
    // return $.ajax({
      url: app.api + '/games/',
      method: 'GET',
      data,
      headers: {
        Authorization: 'Token token=' + app.user.token,
      },
      success: function(data){
      jsonObject = JSON.parse(data);
      alert(jsonObject);
    }
  });

```

**Comment by RealWeeks** [comment]
You're sending JSON, so "data" here is already JSON. Take a look at the docs https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

**Comment by gaand** [comment]
This is not how we demonstrated this (using `success` is deprecated - You should use the `done` and `fail` methods as we did.), but jQuery parses the data from the response if it's JSON and creates a plain-old-javascript-object from it.

You can't parse a JavaScript object as if it were JSON.

**Comment by RealWeeks** [comment]
What he said ^

**Comment by alex-braun** [comment]
Ok.  I think I will go back to trying to get the info I need through my ui.js, as it should be easier, especially if it is already a JavaScript object.

Thanks
