### ISSUE TITLE
can't set game array back to empty when starting new game

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/game-project#237]
trying to clear the array that holds the x's and o's when i start a new game.

``` js
const onNewGame = function onNewGame(event){
  gameBoardArray = [];
  event.preventDefault();
  $('.game-tile').text('');
  $('.game-tile').data('val', '0');
  let data = {};
  api.newGame(data)
    .done(ui.newGameSuccess)
    .fail(ui.failure);
};
```

**Comment by jordanallain** [comment]
gameBoardArray is declared and values are set in another file, then i require it for this file so i was thinking it wasn't able to see that it was empty back in the original file but if i require it from this one it will be circular dependency.

**Comment by RealWeeks** [comment]
If you declare it in one file (file1) and require it in this file (the current one). gameBoardArray will be what it was in file1.

**Comment by RealWeeks** [comment]
Is what you're asking: How do I reset the gameboard with this function, in this file?

**Comment by jordanallain** [comment]
i think i figured it out. i just cleared the array after a win scenario becomes true.

**Comment by jordanallain** [comment]
:''''''''(
