### ISSUE TITLE
Message not showing

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/game-project#240]
For some reason, my message that needs to be displayed once X or O wins shows locally but not on github page. I pushed it properly, and followed all the steps.

I would appreciate any advice.

Thank you!

![gitpage](https://cloud.githubusercontent.com/assets/19355037/17236482/46d4d5ec-5517-11e6-8384-e71106e89ea4.jpg)
![local](https://cloud.githubusercontent.com/assets/19355037/17236486/4c54c932-5517-11e6-8f48-e7821e59208c.jpg)

**Comment by laurenfazah** [comment]
Are there console errors?

**Comment by NatasaPeic** [comment]
bundle file...

**Comment by NatasaPeic** [comment]
![error](https://cloud.githubusercontent.com/assets/19355037/17236643/8aa6a510-5518-11e6-976a-a15ad8ff8bd5.jpg)

**Comment by NatasaPeic** [comment]
Could that be something from earlier?

**Comment by NatasaPeic** [comment]
I deleted bundle and vendor from gitignore.

**Comment by laurenfazah** [comment]
Was it happening on your master branch?

**Comment by laurenfazah** [comment]
If it's not happening on your `master` branch, you should redo the `gh-pages` deploy instructions

**Comment by NatasaPeic** [comment]
I did it all over again.

**Comment by NatasaPeic** [comment]
It shows on master branch locally, yes.

**Comment by NatasaPeic** [comment]
So, should I do merging again?

**Comment by NatasaPeic** [comment]
Definitely errors for signing-up and all that. Which I don't get on master branch locally. I get all AJAX requests successfully returned even PATCH locally, but not on git page.

Something went wrong.

**Comment by laurenfazah** [comment]
I would redo all of the gh-pages-deployment-guide steps

**Comment by NatasaPeic** [comment]
I just did. Still errors.

**Comment by NatasaPeic** [comment]
![1](https://cloud.githubusercontent.com/assets/19355037/17237000/85ca4076-551b-11e6-93bf-6b90bd67a037.jpg)
![2](https://cloud.githubusercontent.com/assets/19355037/17237001/85caadfe-551b-11e6-9727-f5cb21f91325.jpg)

**Comment by NatasaPeic** [comment]
All set, but still errors on git page.

**Comment by laurenfazah** [comment]
After `grunt build` and before `git add .`, can you run `grunt status`?

**Comment by NatasaPeic** [comment]
Aborted due to warnings.

**Comment by NatasaPeic** [comment]
But I'm on gh-pages now.

**Comment by NatasaPeic** [comment]
In terminal.

**Comment by laurenfazah** [comment]
Is `Aborted due to warnings` coming from `git status`?

**Comment by NatasaPeic** [comment]
grunt status

**Comment by NatasaPeic** [comment]
git status gives me that directory is clean

**Comment by laurenfazah** [comment]
Sorry, I meant `git status` earlier

**Comment by NatasaPeic** [comment]
Git status is fine.
Nothing to commit.

**Comment by NatasaPeic** [comment]
Not sure what to think or do. Locally all works.

**Comment by laurenfazah** [comment]
Are you sure you did this?

> In your .gitignore file, comment out the lines *bundle.js and vendor.js so git no longer ignores those files e.g., # *bundle.js. Alternatively you can remove those lines altogether.

**Comment by NatasaPeic** [comment]
Yes.

**Comment by laurenfazah** [comment]
I'm not sure. I need to get to sleep, but we can look at it in the morning

**Comment by NatasaPeic** [comment]
Thank you. I need to get on my train, or I will be stuck here. 

Good night! And thank you! I will be here at 8.

**Comment by NatasaPeic** [comment]
I made a few changes to my master again, and redo all the process again. I checked status right grunt build (before add and commit) as you told me to, and now I see that bundle.js file was modified. I stopped there because I'm not sure if I should add it or not.

![bundle](https://cloud.githubusercontent.com/assets/19355037/17246202/8f02adb2-5558-11e6-9b0e-365cc920a53e.jpg)

**Comment by NatasaPeic** [comment]
I didn't modified bundle.js

**Comment by NatasaPeic** [comment]
Summary:

We all were having this error.

Slack message from Antony on project channel.

Antony Donovan [8:54 AM]  
Please try this as the API url:  https://aqueous-atoll-85096.herokuapp.com
