### ISSUE TITLE
ajax not working on deployed site 

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/game-project#244]
9285 Mixed Content: The page at 'https://cdelsoin.github.io/tic-tac-toe-game/#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://aqueous-atoll-85096.herokuapp.com/sign-in'. This request has been blocked; the content must be served over HTTPS.

**Comment by cdelsoin** [comment]
everythings when I have them on my localhost

**Comment by laurenfazah** [comment]
Check out the error - it's saying it needs to load over HTTPS.

This is the API we sent out for you: https://aqueous-atoll-85096.herokuapp.com/
This is the endpoint you're using: http://aqueous-atoll-85096.herokuapp.com/

Slight difference!

**Comment by gaand** [comment]
@cdelsoin Is this resolved?  If so, please close.  Thanks.

**Comment by cdelsoin** [comment]
it is
