### ISSUE TITLE
After game resets, game only marks as player x

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/game-project#245]
I am pretty sure I know in what function the error is caused, but because I really do not really understand what I need to do in the Dev Tools Debugger in chrome and moreso, what to look for so that I can find where the code is breaking. 

What happens is that the game is working well when the page is up and running, prints win conditions, or tie. Reloads the page when the refresh button is pressed. After it is pressed it begins play as Player x and won't ever play as the other player.

I managed to fix the bug that made this behavior happen after a win condition. It will play and display game after game as long as the outcome is a win. But if a tie is reached...it will go into the perpetual marking of x stage.

**Comment by laurenfazah** [comment]
So this is after a tie and after the browser's refresh button is triggered?

**Comment by natGalynker** [comment]
Yes, after a tie, and after the refresh button is pressed. Regardless of the number of games played before the tie happens which a winner is declared.

**Comment by gaand** [comment]
@natGalynker Is this still an open issue?
