### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#248]
Still getting 'require not defined' issue. Checked for circular dependencies, but that doesn't seem to be a problem. `require is not defined` is literally the message I'm getting. I've Googled it but I haven't gotten a straight answer. Searched closed issues. This issue has been addressed but it doesn't solve my particular problem.

Grunt nag reveals that certain bits of code are defined and never used (and vice versa) but this is because I worked out the game logic before putting it in this template in which concerns are split into different files; that is precisely WHY I need 'require' to work. Tried debugger as well, and it did not help. 

I'm stumped on this one. :-/

**Comment by jrhorn424** [comment]
Thanks for filing, @julie1013. Since we spent some time debugging this yesterday, let's sit down and try to gather more information together.

**Comment by jrhorn424** [comment]
We're still debugging this. For now, @julie1013 is re-organizing her code (several imports weren't needed) and fixing linter warnings.

**Comment by julie1013** [comment]
@jrhorn424 Still more issues, even after reorganizing code and fixing linter warnings. I got this:

`2016-09-07 11:22:37.836 index.js:3 Uncaught ReferenceError: require is not defined`
and this, I suppose as a logical result:
`index.js:10Uncaught TypeError: events.setUpHandlers is not a function`

However, the good news is that my board is appearing again. :-/

**Comment by jrhorn424** [comment]
@julie1013 This might sound odd, but could you delete everything in that buffer and re-type it by hand? I think there might be an issue from copying and pasting. I'll continue to research the issue as well.

**Comment by julie1013** [comment]
The issue was that I was linking to JavaScript and CSS files from my HTML page, and this was throwing everything off.

**Comment by jrhorn424** [comment]
Specifically, @julie1013 was linking directly to `assets/scripts/index.js` **in addition to** including `bundle.js` in the `<head>`.
