### ISSUE TITLE
Bootstrap Modal not appearing on button press

### ISSUE THREAD

**Issue by hantungy** [ga-wdi-boston/game-project#249]
**Linter Output:**

Running "jshint:all" (jshint) task

> > 3 files lint free.

Running "jsonlint:all" (jsonlint) task

> > 6 files lint free.

Running "jscs:status" (jscs) task

> > 3 files without code style errors.
> > 
> > ```
> > ```

**Issue:**

I am trying to get a modal to appear when the sign up button is pressed. The modal does not appear when the button is clicked in the UI. I copied and pasted the code from the bootstrap website and targeted the modal by id with the sign up button I created. I think the problem has to do with my button being within a form. I tried taking the button out of the form tags and it works perfectly fine. Also the button is nested within a navbar.

``` html
<!-- navigation bar with Sign Up button targeting myModal-->
<nav class="navbar">
        <form class="form-inline">
          <div class="form-group">
            <label for="input-email">Email address</label>
            <input type="email" class="form-control" id="input-email" placeholder="Email">
          </div>
          <div class="form-group">
            <label for="input-password">Password</label>
            <input type="password" class="form-control" id="input-password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-default btn-lg active" data-toggle="modal" data-target="#myModal">Sign Up</button>
          <button type="submit" class="btn btn-primary btn-lg active">Sign In</button>
        </form>
      </nav>

<!-- modal code with id set to myModal-->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
```

**Comment by payne-chris-r** [comment]
1) Who is this? 
2) Show me the `js` code please!
3) I really like putting 

``` js
$("<insert-selector-here>").on('click', function(){
    console.log("You clicked the <insert-selector> button ");
};
```

My guess is you've either forgotten a `#`, you've used the same `id` twice, or the button doesn't exist at the time you're trying to attach the click handler.

**Comment by jrhorn424** [comment]
@hantungy We need to see the JavaScript as well. Please look at #222, #219, #216, #212, and #156.

**Comment by hantungy** [comment]
Sorry guys, it's me Herberto! I will add a profile pic soon. I'm not sure which js file you guys are referring to, I'm using a bootstrap plug-in. Shouldn't the js code all be in the bootstrap package?

**Comment by payne-chris-r** [comment]
You posted `HTML`. I see no `js`.

**Comment by payne-chris-r** [comment]
(Not sure if that answered your question, but HTML can't run functions for you)

**Comment by jrhorn424** [comment]
@hantungy Ah, I see, so you don't have any custom JavaScript on those buttons?

Did you look at the linked issues I posted? Some of the JavaScript in those issues might help. I'm pretty sure the issue boils down to the handlers bootstrap registers for opening modals.

What have you Googled to debug the issue? Do you have any open articles or documentation you're referencing, other than the bootstrap docs?

Have you spoken to anyone else about modals? I'd be surprised if none of your colleagues were using them.

**Comment by jrhorn424** [comment]
@laurenfazah Do you have any notion of what might be going on here?

**Comment by gaand** [comment]
I suggest a check of the html with `tidy` for completeness.

**Comment by laurenfazah** [comment]
This looks correct and should work without any additional jQuery. 

Do you by chance have multiple modals/elements in index.html using the same `id="myModal"`?

And yes, definitely check your HTML with tidy to ensure all tags are properly opened/closed.

**Comment by hantungy** [comment]
Right Jeff, I do not have custom Javascript for the button. I am using the code on the bootstrap website for creating a modal. From what I understand, when a div is assigned a class from the bootstrap api, it should run the JavaScript code in that library? It definitely works when I created a button outside of my navbar.

**Comment by hantungy** [comment]
*outside navbar > form-inline

**Comment by laurenfazah** [comment]
Ah. Where did the `type="submit"` on your modal launch buttons come from?

**Comment by hantungy** [comment]
@laurenfazah Yes I only have one id named "myModal"

**Comment by hantungy** [comment]
it was the code from the bootstrap website

**Comment by laurenfazah** [comment]
I highly doubt that. I'd compare your buttons tasked with launching your modal with the buttons doing the same in Bootstrap's documentation.

**Comment by hantungy** [comment]
I just started and only have two buttons. I only assign one of those buttons to myModal. My other button doesn't do anything yet.

**Comment by jrhorn424** [comment]
@hantungy Lauren is trying to give you a debugging step.

**Comment by hantungy** [comment]
@laurenfazah you were right, the type was incorrect. It should be "button" instead of "submit". Thanks so much! Sorry for the confusion guys!

**Comment by payne-chris-r** [comment]
@hantungy please sum up the solution to your issue and close this issue thread.

**Comment by hantungy** [comment]
I was able to get the modal to appear in response to a click to my sign up button by changing my button type from "button" to "submit".

**Comment by jrhorn424** [comment]
Thanks @hantungy!
