### ISSUE TITLE
Issue with sign-out button

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/game-project#25]
So I created my sign out button (the last step of my api auth yay!) and when I run my page the console logs "cannot read property 'id' of undefined." It references line 84 of my JS. 

Line 84 reads as follows: 
`url: myApp.baseUrl + '/sign-out/' + myApp.user.id,`

I have declared myApp and this same line works for the change password function. I made sure that all my ID's are matching and I see no reason why this shouldn't work. Even a second set of eyes would be amazing. 

The docs are confusing because this issue seems relatively broad in scope.

**Comment by RealWeeks** [comment]
put a debugger before the ajax request and post the myApp object and myApp.user object

**Comment by GA-MEB** [comment]
> "cannot read property 'id' of undefined."

This means that the thing `id` is attached to -- i.e. `myApp.user` -- is undefined. Even if `myApp` is defined, its `user` property could still be undefined.

That the error occurs just before `id` (and _not_ just before `user`) seems to line up with your comment that you did in fact define `myApp`.

**Comment by RealWeeks** [comment]
@MattB-GA-Boston I assume he defined myApp.user.id at some point earlier.  @kpie89 is that correct?

**Comment by kpie89** [comment]
Yes. myApp.uder.id works nicely in when user wants to change passwork

**Comment by gaand** [comment]
Please show the line where you assign the user property.
