### ISSUE TITLE
[JS] Separation of concerns in game logic

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/game-project#250]
No errors, but a question:

I've been attempting to follow the rough separation of concerns across different .js files that we used in the api-token-auth training and apply that to my game logic. I currently have an assets/scripts/game directory that contains:
- events.js (requires api & ui)
- api.js (requires assets/scripts/app)
- ui.js (requires assets/scripts/app)

Right now, the rough flow for taking a turn is:
- add a click handler to the cell (events.js)
- that click handler calls a function in events.js that checks a predicate function in ui.js to see whether the cell is empty (whether this is a valid possible move)
- if the predicate returns true, the click handler calls a function in api.js that makes a PATCH request
- if that request succeeds, within the `.done()` method, events.js calls a function in ui.js that does a couple of things:
  - updates some data in app
  - repaints the game board in the browser (a separate function that is called)
  - checks to see whether the move is a winning move (a separate function that is called, that itself calls several functions)

The next step is to submit another PATCH request to mark the game as being over, but I'm having trouble figuring out from which file I should trigger that request. (At the end of the list above, I'm still "in" ui.js, and I don't want to make a call to api.js from ui.js because circular dependencies are bad.)

I'd welcome some advice on whether I'm headed down the right path with respect to structuring my files/separating my functionality into appropriately modular functions.

**Comment by rhjones** [comment]
Relevant code:
- [assets/scripts/game/events.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/game/events.js)
  - click handler is registered in `addHandlers()` on line 28
  - callback (`onClickCell()`) is defined on lines 13-24
- [assets/scripts/game/api.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/game/api.js)
  - `onClickCell()` calls `api.takeTurn()`, which is defined on lines 23-42
- [assets/scripts/game/ui.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/game/ui.js)
  - `onClickCell()` in events.js calls `ui.isEmpty()`, which is defined on lines 26-31
  - if `api.takeTurn()` succeeds, events.js calls `ui.takeTurnSuccess`, which is defined on lines 94-120 and in turn calls:
    - `markCell()` (lines 84-92)
    - `checkWin()` (lines 68-82)
      - `checkWin()` calls `checkRows()` (lines 33-41), `checkCols()` (lines 43-51), and `checkDiagonals()` (lines 53-66)

**Comment by payne-chris-r** [comment]
So, it shouldn't check "ui". You should have an object that stores the current state of the game (which is where the game-logic should check). The `ui.js` file should be strictly for UI concerns (changing colors, appearance, etc). In fact, if I'm not mistaken, you already have a circular dependency if `api.js` is checking `ui.js` which is calling something in `api.js`...

**Comment by rhjones** [comment]
Thanks, @payne-chris-r. I'll refactor and let you know if I still have questions.

**Comment by jrhorn424** [comment]
Kudos on an exemplary issue.

Chris is spot-on that `ui` (ideally) shouldn't be the coordinating mechanism for your moves. Have you thought about making a `moves` file or folder just for that particular feature? It could coordinate among `game` `ui`, `events`, etc. Another option would be to handle that feature inside `assets/scripts/index.js`, but that's less-than-ideal, IMO.

**Comment by rhjones** [comment]
Thanks, @jrhorn424 & @payne-chris-r. I've moved the following functions out of ui.js into a new file ([assets/scripts/game/game-logic.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/game/game-logic.js)):
- `isEmpty()`
- `createGameSuccess()`
- `takeTurnSuccess()`
- `checkWin()`
- row/col/diagonal win condition checks

Current dependencies within the assets/scripts/game folder:
- events.js requires api.js, ui.js, and game-logic.js
- api.js requires app.js and game.js (game.js is a new file that contains a single object with current game data)
- ui.js requires game.js
- game-logic.js requires game.js and ui.js 

I'm still not sure how to connect things without causing a circular dependency so that if a move returns "true" from one of the win conditions (currently being evaluated in game-logic.js), I trigger a new API call.

**Comment by rhjones** [comment]
I may have figured this out:

In events.js:

``` js
const onClickCell = () => {
  event.preventDefault();
  let cell = $(event.target);
  let id = cell.data('id');
  if (gameLogic.isEmpty(id)) {
    api.takeTurn(id)
      .done(makeMove)
      .fail(ui.failure);
  } else {
    // cell is taken
  }
};
```

`makeMove()` is also defined in events.js:

``` js
const makeMove = (data) => {
  let result = gameLogic.takeTurnSuccess(data);
  // if takeTurnSuccess, which checks for win conditions, returns a win, then:
  api.endGame()
    .done()
    .fail();
};
```

So rather than having the callback within `api.takeTurn.done()` call something from another file, it calls a function within events.js that then calls on game-logic to evaluate whether the move is a win, and if so, calls on api.js to make the PATCH to set the game's `over` property to `true`.

Please let me know if I'm not on the right track. Thanks!

**Comment by jrhorn424** [comment]
This looks great! One small suggestion: `assets/scripts/game/game-logic.js` is a bit redundant. Perhaps `assets/scripts/game/logic.js` instead?

Thanks for linking and using proper formatting!

**Comment by rhjones** [comment]
Excellent—thanks!
