### ISSUE TITLE
ui.js:25 Uncaught TypeError: events.setUpHandlers is not a function

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#251]
Game is working perfectly, except after somebody wins and restarts, it won't set up the event handlers. Yes, I exported the function from 'events', and yes I set up a 'require'. But even though I can set up the handlers on the first round, it won't let me do it after someone wins (in the original version of the game that I did over the weekend this wasn't an issue, so I'm guessing there's some kind of "miscommunication" between files). Here's the error exactly:

```
# edited by @jrhorn424 - code block delimiters must be followed by a newline
ui.js:25 Uncaught TypeError: events.setUpHandlers is not a function
```

Relevant code:

from my logic file:

``` js
// edited by @jrhorn424 - code block delimiters must be followed by a newline
// also, please use extensions in the opening delimiter

const restartGameData = function(){
  board.splice(0,board.length);
  initializeBoard(board);
  whoseTurn = 0;
  winner = null;
};
```

from my ui file:

``` js
// edited by @jrhorn424 - code block delimiters must be followed by a newline
// also, please use extensions in the opening delimiter

const restartGameUi = function(){
  $('.board').empty();
  drawBoard(logic.board);
  events.setUpHandlers();
};
```

**Comment by payne-chris-r** [comment]
Please format both code blocks like this and repost:

from my logic file:

``` js
const restartGameData = function(){ 
    board.splice(0, board.length); 
    initializeBoard(board); 
    whoseTurn = 0;
    winner = null; 
};
```

**Comment by julie1013** [comment]
They were. I don’t know why it’s showing up like that.

**Comment by julie1013** [comment]
from my logic file:

```const restartGameData = function(){ 
        board.splice(0, board.length); 
        initializeBoard(board); 
        whoseTurn = 0;
        winner = null; 
};```

from my ui file:

```const restartGameUi = function(){ 
        $('.board').empty(); 
        drawBoard(logic.board); 
        events.setUpHandlers(); 
}```

**Comment by julie1013** [comment]
from my logic file:

``` js
const restartGameData = function(){ 
    board.splice(0,board.length);
    initializeBoard(board); 
    whoseTurn = 0; 
    winner = null; };
// edited by @jrhorn424 - don't end code blocks with an extension
```

from my ui file:

``` js
const restartGameUi = function(){ 
    $('.board').empty(); 
    drawBoard(logic.board); 
    events.setUpHandlers(); 
};
// edited by @jrhorn424 - don't end code blocks with an extension
```

**Comment by payne-chris-r** [comment]
FYI, it's better to comment directly on github, not from email ;-).
SO, your issue is this:
Game is working perfectly, except after somebody wins and restarts, it won't set up the event handlers. Yes, I exported the function from 'events', and yes I set up a 'require'. But even though I can set up the handlers on the first round, it won't let me do it after someone wins (in the original version of the game that I did over the weekend this wasn't an issue, so I'm guessing there's some kind of "miscommunication" between files). Here's the error exactly:

```
# edited by @jrhorn424 - please use fenced code blocks for error messages
ui.js:25 Uncaught TypeError: events.setUpHandlers is not a function
```

Relevant code:

from my logic file:

``` js
const restartGameData = function(){ 
    board.splice(0, board.length); 
    initializeBoard(board); 
    whoseTurn = 0;
    winner = null; 
};
```

from my ui file:

``` js
const restartGameUi = function(){ 
    $('.board').empty();
    drawBoard(logic.board); 
    events.setUpHandlers(); 
};
```

**Comment by payne-chris-r** [comment]
So, question: 
When do the event handlers get added? In `document-ready`?

**Comment by julie1013** [comment]
THey get added there at first, but I also call that function again at the end of the game when someone wins and the game restarts.

**Comment by julie1013** [comment]
OK, I think I've figured out what the problem is. That function calls something in ui by using ui... but then that function is called within a function in ui, so I think it doesn't like that. Does this mean I either have to write a "sequel" function or call the function some other way?

**Comment by julie1013** [comment]
Rewriting parts of the code with objects.

**Comment by jrhorn424** [comment]
@payne-chris-r I'm assuming this is closed due to a conversation you had? Can you elaborate why you suggested this particular refactoring, and what the diagnosis of the original issue was in your opinion?
