### ISSUE TITLE
[AJAX/API/JS?] updateGame response partially updates, then fully updates game

### ISSUE THREAD

**Issue by abeers** [ga-wdi-boston/game-project#253]
So I had an issue, resolved it, and would like to post this to help anyone else who may come across the same problem.
## The Goal

I wanted to make one API call to update the game with an object that contained the updated `index` and `value` of the last cell clicked, as well as the `over` state of the updated local game. Once a game is won, no other cells should be clickable.
## The Symptoms

I was able to start games and play them normally until someone won. I have an alert set up to say "Congratulations Player X/O" when a win condition is met. If one player got three in a row, the alert would pop up as expected. However, if another cell was clicked (aka "the extra cell"), that cell would update and the alert would pop up again. After that, no other cells were clickable.
### Asynchronocity/Timing of Clicks

My first thought was that I was clicking the extra cell too quickly after the winning cell. Maybe the API request, my alert, and other functions were still running when I clicked the extra cell. This may cause the event handler to fire again, updating the board one extra time before locking up the other cells.

This one was debunked fairly quickly by simply waiting 30 seconds after clicking the winning cell, clicking an extra cell, and watching the same behavior occur.
### AJAX/API

I then wondered if there was something going on with the actual API call. This seemed to be the only place something could've been going wrong, as the app was obviously updating the game, checking win conditions, and locking up the clickability of the other cells correctly, even if it was at the wrong time.

At first glance, my data seemed to be fine. There were no errors and the API was obviously doing something with my data, so formatting wasn't the issue. Maybe it was the API's fault. By using `console.log(data)` in my `onUpdateSuccess` function that uses a `data` parameter, I could see what the response was returning. To my surprise, it was working...partially. After clicking the winning cell, the `cells` array was updated per my request, but the `over` state did not change. Because I only lock up the other cells after the game is over, this is why my game allowed another click. However, on the extra cell click, the `cells` array and the `over` state were both updated correctly.

This made zero sense to me. How could it take the same data twice, but return different things? Well, it can't...
### Synchronosity/I dun goofed

So what data was I passing in? Using `console.log(data)` immediately before my API call showed me exactly what was happening. The data I was passing in did not have `over: true` in it, it had `over: false`. So I had to look at how I was building the `data` object, and the problem showed itself.
## The Issue

``` js
const onUpdateGame = function (event) {
  event.preventDefault();

  // THIS IS THE PROBLEM!!! This function builds the data object that I pass in my request.
  let data = buildUpdateDataFromClick(event);

  let index = $(event.target).data('id');

  // This if statement doesn't allow any cells to be clicked if the game is over or an 
  // invalid cell is selected
  if (!app.user.currentGame.over && logic.isValidMove(index)) {
    let indexWins = $('[data-id=' + index + ']').data('win-conditions');

    // THIS IS THE OTHER HALF OF THE PROBLEM!!! This function updates my win 
    // conditions object that is used to determine if the game is over
    logic.incrementGameConditions(indexWins, app.player);

    //My API call
    api.updateGame(data)
      .done(ui.updateGameSuccess, ui.renderGameBoard)
      .fail(ui.failure);

    //This is where the alert comes from
    if(logic.isGameWin()) {
      ui.winningCelebration(app.player);
    } else if (logic.isGameTie()) {
      ui.tieCelebration();
    } else {
      logic.changePlayer();
    }
  }
};
```

As you can see above, the `data` object was built too early. I build the `data` object (which has an `isGameOver` function that determines if the game is over in it), then I do stuff that affects the object that `isGameOver` checks, then I make my API call, then I fire the celebratory alert. A lot of things happen, but the largest problem is that I didn't build my `data` object immediately before the API call, so it was out of date, and I got very strange results.
## The Solution

``` js
const onUpdateGame = function (event) {
  event.preventDefault();
  let index = $(event.target).data('id');

  if (!app.user.currentGame.over && logic.isValidMove(index)) {
    let indexWins = $('[data-id=' + index + ']').data('win-conditions');
    logic.incrementGameConditions(indexWins, app.player);

    // FIXED!!! This is now building data that reflects the new game conditions, which fixes
    // all of the issues
    let data = buildUpdateDataFromClick(event);

    api.updateGame(data)
      .done(ui.updateGameSuccess, ui.renderGameBoard)
      .fail(ui.failure);

    if(logic.isGameWin()) {
      ui.winningCelebration(app.player);
    } else if (logic.isGameTie()) {
      ui.tieCelebration();
    } else {
      logic.changePlayer();
    }
  }
};
```

Placing the data build in the appropriate spot (immediately above the API call) remedied the issue. After a few more tests and `console.log`s, I am comfortable stating that the issue has been fixed.
## The Moral

Make sure function calls are where you think they are and variables are what you think they are. If you're going to pass an argument into a function, try to define that argument as close to the function call as possible.

**Comment by jrhorn424** [comment]
A fantastic write up. This would an excellent blog post.

**Comment by gaand** [comment]
@abeers Thank you for this!
