### ISSUE TITLE
Atom linter warnings that don't appear to be code-related

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/game-project#254]
After downloading the template and copying/pasting previously written code into my new files, I seemed to be getting some linter warnings that I hadn't seen before. For instance, in my index.js file, I have (only) this in my code:

``` ext
// 'use strict';
// 
// const newDisplayLetter = require('./maingame');
// 
// $(document).ready(function () {
//   newDisplayLetter.displayLetter();
// });
```

Aside from the fact that my logic just doesn't work right now, I am getting the following warnings from atom's linter: 
W097 - use the function form of "use strict". at line 1 col 1.
W104 -'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). at line 3 col 1.

After reading other posted issues and googling, it seems as though I may have missed some files when downloading the template or am not using the correct version of something (it's basically been doing this since I started).

**Comment by payne-chris-r** [comment]
Did you move the folders around in `finder` and not using the terminal?

**Comment by knoddin** [comment]
I did do that at one point.

**Comment by payne-chris-r** [comment]
Yeahhh...

**Comment by payne-chris-r** [comment]
You need to set up https://github.com/ga-wdi-boston/js-template as a remote and checkout the files that you lost (all the files that start with a `.`) when you moved it in finder.

**Comment by payne-chris-r** [comment]
If you need help doing this, I'm happy to do so.

**Comment by jrhorn424** [comment]
For future reference, see my comments in #199.

**Comment by knoddin** [comment]
I moved the downloaded JS-template file via Finder (not good!) and lost some of the files that started with a dot. Re-downloaded the template and got the files I needed. Thank you!
