### ISSUE TITLE
Tidy trimming empty <tag> linter warning fix

### ISSUE THREAD

**Issue by wmcb91** [ga-wdi-boston/game-project#256]
Chris and I found a solution to a linter issue I encountered when using a bootstrap glyphicon in my project html similar to the example below.  The issue should only occur if you use only a glyphicon with no text content.

``` html
<button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
</button>
```

When I entered the code my linter gave me these warnings:

> tidy Warning trimming empty <span> at [location]
> tidy Warning trimming empty <button> at [location]

Since glyphicons are created inside nested `<spans>`, the linter does not register them as content when they are standalone. To satisfy the linter you can enter a comment in the span like below.

``` html
<button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="glyphicon glyphicon-align-left" aria-hidden="true"><!-- empty span --></span>
</button>
```

Hopefully this helps if you encounter the same issue.

**Comment by jrhorn424** [comment]
@wmcb91 Cool fix! You can leave a descriptive comment if it fits. Did you try just an empty comment? `<!-- -->`?

**Comment by wmcb91** [comment]
Leaving an empty comment works as well.
