### ISSUE TITLE
Having issues getting Sign In, Sign up etc to hide after form is filled out

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/game-project#257]
I am not getting an error message, but I am not getting the desired effect. So far I have tried

``` .js
const addHandlers = () => {
  $('#sign-in').on('submit', function(){
    $('sign-in').hide();
  });
}
```

I am using this code to hid the forms on launch. 

``` .js
$(() => {
  $('container').show();
  $('form').hide();
  authEvents.addHandlers();
});
```

**Comment by jrhorn424** [comment]
@rosmith76 Are you asking about modals? Modals should automatically close on submit, right @laurenfazah @berziiii?

**Comment by berziiii** [comment]
From what I'm seeing, you have an ID on the form you're submitting for sign-in, called `sign-in`. You're modal id will have to be something different. Like `sign-in-modal`. Check to make sure the ID's are different and you're calling the right ID in the right place. 

Also, you're not referencing an ID in the `$('sign-in').hide();` You need the `#`

**Comment by laurenfazah** [comment]
If the submit button is `type="submit"`, it will do that instead of dismissing the modal. jQuery would be needed in that case. 

From what you pasted, however, it appears as though you are using a selector called `sign-in`. I would assume that was meant to be a class or ID?

**Comment by jrhorn424** [comment]
@rosmith76 There is some example jQuery code in the following issues: #222, #219, #216, #212, and #156. You'll want to search those for a method that can help you dismiss a modal after submission of the form.

**Comment by jrhorn424** [comment]
Also, you'll need to be sensitive to your `input`'s or `button`'s `type` attribute, as noted in #249.

**Comment by rosmith76** [comment]
I am not doing to as a modal. @berziiii the missing # was the issue. 

``` .js
$('#sign-in').on('submit', function(){
    $('#sign-in').hide();
  });
```

This code worked the way I expected it to. The form is hidden, and the token is still valid, so I can change password, sign out etc.

**Comment by jrhorn424** [comment]
@rosmith76 Thanks for the update. If this is addressed can you close the issue? Thanks.

**Comment by rosmith76** [comment]
I tested all aspects of sign up/in/out and change password, and everything worked. I will close the issue.
