### ISSUE TITLE
[Bootstrap/AJAX] Modal button getting error from API?

### ISSUE THREAD

**Issue by tuckyeah** [ga-wdi-boston/game-project#258]
So I've gotten my sign-in/sign-up/change-pw/sign-out forms to all communicate with the API and get the correct responses. I want to add modals for each of those, so to start, I'm tackling getting the 'sign in' modal to work.

Based on the bootstrap documentation and our lesson in class on Tuesday about Bootstrap, I used the same code for the sign in modal we used in class and tried to hook it up to my 'sign in' button on my navbar. I've successfully gotten the click handler to work for that button, and I can even get a response back from the API, but it's the wrong one! 

I've kept all the code in my api.js and event handlers the same as when they worked successfully on the standard forms, but for some reason, it doesn't work on the modal. I've tried logging in with the same username/password combination on the form, and it works successfully, so I've narrowed the issue down to something going on with the modal or the event handler, I think.

The error I get back from the API reads as follows:

```
XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
```

The code for my modal looks like this (located at the bottom of index.html):

``` html
<!-- edited by @jrhorn424 - extensions are bare, no brackets ([html] -> html) -->
      <div class="modal fade" id="signInModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Sign in!</h4>
            </div>
            <div class="modal-body">
              <form class="form-horizontal" id="sign-in">
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-10">
                    <input type="email" class="form-control" id="inputEmail3" name = "credentials[email]"
                    placeholder="Email">
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer"> 
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="sign-in-modal-button">Sign in!</button>
            </div>
          </div>
        </div>
      </div>
```

Here's the link for the full index.html, in case that's helpful:
[index.html](https://github.com/tuckyeah/project-1/blob/master/index.html)

Finally, the function call for my event handler is written as:

``` js
// edited by @jrhorn424 - extensions are bare, no brackets ([js] -> js)
  $('#sign-in-modal-button').on('click', onSignIn);
```

All the code in the actual onSignIn function and in the API is the same as the working form, so I haven't provided it here, but it can be found in the following links:

```
edited by @jrhorn424 - please use bullets for lists
```
- [assets/scripts/auth/api.js](https://github.com/tuckyeah/project-1/blob/master/assets/scripts/auth/api.js)
- [assets/scripts/auth/events.js](https://github.com/tuckyeah/project-1/blob/master/assets/scripts/auth/events.js)
- [assets/scripts/auth/ui.js](https://github.com/tuckyeah/project-1/blob/master/assets/scripts/auth/ui.js)

Thanks!

**Comment by jrhorn424** [comment]
What happens if you make these changes:

``` diff
-  $('#sign-in-modal-button').on('click', onSignIn);
+  $('#sign-in').on('submit', onSignIn);
```

``` diff
<div class="modal-footer"> 
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
-  <button type="button" class="btn btn-primary" id="sign-in-modal-button">Sign in </button>
+  <input type="submit" class="btn btn-primary" id="sign-in-modal-button">Sign in </button>
</div>
```

**Comment by berziiii** [comment]
You also, from the code above, don't have a `name=credentials[password]` in your password input for the sign-in form.

**Comment by berziiii** [comment]
You also may need the `<input type=submit>` for the form submission to be wrapped in the `<form>` tags for it to work. Not sure but could be worth keeping in mind incase things still don't work correctly.

**Comment by jrhorn424** [comment]
1. Without a `<form>`, `submit` doesn't work. (fact)
2. If you have a form, you should have a submit. (best practice)

Great catches @berziiii

**Comment by jrhorn424** [comment]
Why do you have numbers in your id's, like `"inputPassword3"`? This is usually an anti-pattern (A Bad Thing :tm:).

**Comment by tuckyeah** [comment]
Success! I missed the `name=credentials[password]` and changed the button to an input form at the end of the form block. Now it works!

As for the numbers in the id's - those come from the Bootstrap code that I took from our lesson on Tuesday... I was afraid to mess with them in case it broke bootstrap or something, but I can tinker!

Thank you!
