### ISSUE TITLE
Trying to get curl request to work

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#259]
I think I might need a little refresher? Or maybe I'm missing a step?

I pasted this into the terminal:

`````` json
curl "http://tic-tac-toe.wdibos.com/" \
--include \
--request POST \
--header "Content-Type: application/json" \
--data $"{
 \"credentials\": {
   \"email\": \"email@example.com\",
   \"password\": \"lalala\",
   \"password_confirmation\": \"lalala\"
 }
}"

The message I got was: 
```<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>```
``````

**Comment by jrhorn424** [comment]
`404` means a route couldn't be found. Maybe something is wrong with your URL or your HTTP verb?

**Comment by jrhorn424** [comment]
Please review the endpoint documentation here: https://github.com/ga-wdi-boston/game-project-api

**Comment by berziiii** [comment]
As Jeff said, check your route. If you're trying to do any auth, or any request to a specific route,  you need to target the correct `http://tic-tac-toe.wdibos.com/<route>`.

**Comment by payne-chris-r** [comment]
@julie1013 did this help at all? Are you still stuck?

**Comment by julie1013** [comment]
Thanks. We're finishing up outcomes, so I haven't tried yet. I'll let you know.

**Comment by julie1013** [comment]
Yeah, I'm still stuck. What is the route for creating a new user account? That's what I'm trying to find in the documentation for this particular API.

**Comment by julie1013** [comment]
Just found sign-up. Still, adding that to the end of the URL doesn't work.

**Comment by jrhorn424** [comment]
> Just found sign-up. Still, adding that to the end of the URL doesn't work.

The thing that is currently blocking us is we don't know what your error message is. However, this is a symptom of not following process.

Whenever you say something doesn't work, try to get into the habit of providing us with more information. We try to be direct and precise, and it helps when you are as well.

It isn't clear from your issues that you're following the process we described in the [issue tracker guide](https://github.com/ga-wdi-boston/project-issue-tracker-guide). Please follow it step-by-step, starting with your response to this issue.

Provide all the information requested in the template found in the **second half** of the README only after doing the steps in the **first half**.

cc @ga-wdi-boston/core @m-owenquinn @austinc203

**Comment by julie1013** [comment]
I pasted this into the terminal:

`````` json
curl "http://tic-tac-toe.wdibos.com/sign-up" \
--include \
--request POST \
--header "Content-Type: application/json" \
--data {
  "credentials": {
    "email": "an@example.email",
    "password": "blablabla",
    "password_confirmation": "blablabla"
  }
}```

and got this:

```HTTP/1.1 400 Bad Request
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 08 Sep 2016 18:02:20 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
X-Request-Id: d2e29778-8997-458b-a67e-7092bb6a19ec
X-Runtime: 0.004836```

I don't know if I'm missing a step, but I did look at the documentation, and trying to follow the steps based on what we did in class. 
``````

**Comment by berziiii** [comment]
That user may already exist. Try a different email. Remember this is a live API so a very good posibility that `an@example.email` exists

**Comment by julie1013** [comment]
Tried with a different email. Got this:

`HTTP/1.1 400 Bad Request
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 08 Sep 2016 18:12:49 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
X-Request-Id: 388228a2-3b8b-4c4c-bcbc-789e7ccb2c56
X-Runtime: 0.006287`

```
~/WDI_Fall_2016/projects/template-tic-tac-toe (api)$   "credentials": {
-bash: credentials:: command not found
~/WDI_Fall_2016/projects/template-tic-tac-toe (api)$     "email": "catfail@catfailsforever.org",
-bash: email:: command not found
~/WDI_Fall_2016/projects/template-tic-tac-toe (api)$     "password": "blablabla",
-bash: password:: command not found
~/WDI_Fall_2016/projects/template-tic-tac-toe (api)$     "password_confirmation": "blablabla"
-bash: password_confirmation:: command not found
~/WDI_Fall_2016/projects/template-tic-tac-toe (api)$   }
-bash: syntax error near unexpected token `}'
~/WDI_Fall_2016/projects/template-tic-tac-toe (api)$ }
```

**Comment by berziiii** [comment]
You're curl request is formatted wrong. I can tell from your terminal output. 

please try this: 

``` sh
curl "http://tic-tac-toe.wdibos.com/sign-up" \
--include \
--request POST \
--header "Content-Type: application/json" \
--data '{
  "credentials": {
    "email": "catfail@catfailsforever.org",
    "password": "blablabla",
    "password_confirmation": "blablabla"
  }
}'
```

**Comment by julie1013** [comment]
It worked, thank you! Brian's solution worked!

**Comment by berziiii** [comment]
You were missiing single quotes around the `data` object.
