### ISSUE TITLE
Clarifying MVP requirements for Ajax

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/game-project#26]
Is saving the game state part of the basic requirements for this project, or is that a bonus feature?Just trying to budget the rest of my time remaining to work on my game. I understand that the login/logout functionality is required.

**Comment by MattB-GA-Boston** [comment]
Yes, it is a requirement; that's what's meant by "Use AJAX for data storage and retrieval".

**Comment by gaand** [comment]
Saving game state is required.

**Comment by GA-MEB** [comment]
Whoops, accidentally deleted my response. Yes, it's required. 

"Communicate with a back-end (which we'll provide for you) to store the state of your game."
