### ISSUE TITLE
having issues getting game board logic worked out

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/game-project#260]
I am really lost on where to go with game logic. 
game board

``` .html
    <div class="container">
      <section class="row">
        <article class="col-xs-4"></article>
        <article class="col-xs-4"></article>
        <article class="col-xs-4"></article>
      </section>
      <section class="row">
        <article class="col-xs-4"></article>
        <article class="col-xs-4"></article>
        <article class="col-xs-4"></article>
      </section>
      <section class="row">
        <article class="col-xs-4"></article>
        <article class="col-xs-4"></article>
        <article class="col-xs-4"></article>
      </section>
    </div>
```

event handler for board

``` .js
  $('.col-xs-4').on('click', onUpdateGame);
```

this is as far as I have gotten on onUpdateGame

``` .js
const onUpdateGame = function (event) {
  event.preventDefault();
  for (let i = 0; i < 10; i++) {

  }
};
```

I don't even know if I am on the right track.

**Comment by jrhorn424** [comment]
You don't need a loop. You're trying to do something with a single cell according to how you've attached your handler (a single handler on each tile or cell).

Try getting an X or an O to show up.

That's not game logic, BTW, that's ui. Game logic would be updating your model of the game board in memory. Do you have an object, or a constructor and prototype, for the Board or Cells?

**Comment by rosmith76** [comment]
This is all that I have in relation to the board. At this point I am just trying to get an x or an o show up. Not sure where to start on that.

**Comment by berziiii** [comment]
http://api.jquery.com/html/. May be a good place to start.

**Comment by payne-chris-r** [comment]
What Jeff is alluding to is something that a lot of developers have been missing as well. There is a difference between a local (in memory) representation of the data that constitutes "a game" and the visual representation of that game. 

For example, I might have an object stored in memory that is 

``` js
let myArr = [1,2,3,1,2,3];
```

but visually I want to represent that array on the screen such that if the value in the array is 1, I want a specific div to have a background color of red, if 2: blue, if 3: green.

``` js
// insert js and jquery that will modify background colors of divs based on value in myArr
```

See how there is actual data stored in memory (`myArr`), and I have javascript and jquery that handles how that array is interpreted and presented to the user?

**Comment by rosmith76** [comment]
I am still totally lost. its just not making any sense to me.

**Comment by berziiii** [comment]
Solved. @rosmith76 please post the solution we came to.

**Comment by rosmith76** [comment]
We came to a solution. The game board is now functional as far as X's and O's go. 
We updated event handlers on events.js

``` .js
const onUpdateGame = function (event) {
  event.preventDefault();
  let cell = $(this);
  logic.isValidMove(cell);
  //  valid move?
  // in valid move function, allow for a check, then update board state and board array
};
```

event handler

``` .js
  $('.col-xs-4').on('click', onUpdateGame);
```

We also created a new logic.js file for the game logic. 

``` .js
const board = ['','','','','','','','',''];

let turn = 0;

const updateBoard = function(cell) {
  let index = $(cell).data("id");
  if (turn %2 === 0) {
    $(cell).html('X');
    board[index] = 'x';
  }else {
    $(cell).html('O');
    board[index] = 'o';
  }
  turn++;
  console.log(turn);
  console.log(board);
  // horizontalWin();
};

const isValidMove = function(cell) {
  if ( $(cell).html() === "" ) {
    updateBoard(cell);
  } else {
    alert('Please make a valid move.');
  }
};
```
