### ISSUE TITLE
[JS] Separation of concerns when getting stats on all games

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/game-project#261]
Another conceptual question re: separation of concerns.

When the user logs in, I want to get a list of all of that user's finished games. I then want to evaluate these game to determine which are wins, losses, and draws, and display that information in a stats counter on the page.

Given that this chain of events is tied to an authentication action, I feel like I need to start this process in assets/scripts/auth/events.js. From there, I can make an API call through a function in assets/scripts/auth/api.js\* and display the stats counter using a function in assets/scripts/auth/ui.js.

The issue is that all of the code related to game logic—including evaluating wins/draws—is in assets/scripts/games, and I'm not sure how to tie this together.
- Making the API here feels a little awkward, since the URL includes `/games` instead of an auth-related URL.

**Comment by rhjones** [comment]
After thinking about this for a second, I decided to push forward with the following structure (please let me know if this is Bad Practice):
- in auth/events.js, on successful log in, make a call to a function in auth/api.js that gets all finished games associated with the authenticated user
- if that call succeeds, run a function in auth/ui.js called `displayStats()`
- require my game logic file within auth/ui.js. Use functions within this game logic file to calculate the stats, and pass the result back to auth/ui.js to display

**Comment by jrhorn424** [comment]
I can give better quality feedback after looking at the code. Please see me tomorrow morning at some point if we aren't slammed. This is low priority, but I think you could benefit from a light code review.

**Comment by rhjones** [comment]
Thanks, @jrhorn424. I'll look for you tomorrow if things aren't crazy on your end. 

As background, my current approach is:

My `onLogIn()` function in [auth/event.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/auth/events.js#) makes a call to `api.logIn()` in [auth/api.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/auth/api.js):

``` js
const onLogIn = (event) => {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.logIn(data)
    .done(logIn)
    .fail(ui.logInFailure);
};
```

The callback that's passed to `api.login().done()` is `logIn()`, in [auth/event.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/auth/events.js):

``` js
const logIn = (data) => {
  ui.logInSuccess(data);
  api.getFinishedGames()
    .done(ui.displayStats)
    .fail();
};
```

`logIn()` calls `ui.logInSuccess()` in [auth/ui.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/auth/ui.js), which hides the log in/log out options and shows the game board & game stats

`login()` also makes a call to `api.getFinishedGames()` in [auth/api.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/auth/api.js).

The callback that's passed to `api.getFinishedGames()` is `ui.displayStats()` in [auth/ui.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/auth/ui.js). That code requires my game logic file ([game/logic.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/game/logic.js)) to run, and looks like this:

``` js
const displayStats = (data) => {
  let stats = gameLogic.calculateGameStats(data);
  $('.win > .count').text(stats.wins);
  $('.lose > .count').text(stats.losses);
  $('.tie > .count').text(stats.ties);
};
```

[`calculateGameStats()`](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/game/logic.js#L114) takes the data returned from the `api.getFinishedGames()` function in [auth/api.js](https://github.com/rebekahheacock/tic-tac-toe/blob/master/assets/scripts/auth/api.js) and returns a `stats` object that contains a count of wins, losses, and tied games

**Comment by jrhorn424** [comment]
Thanks for providing the code examples and links! These is very clean and easy to read. If you still would like feedback, I _might_ be able to provide it this afternoon. I'm on the verge of losing my voice today. 😦

**Comment by rhjones** [comment]
I'd appreciate feedback at some point so I can make sure I'm correctly approaching the problem (and future problems), but I don't think it has to be before the project is turned in—things are working like I want them to, so it's not urgent.

Better to set up a one-on-one some time next week?

(Hope you feel better!)

**Comment by jrhorn424** [comment]
Sure, that sounds fine, and thanks. :smile:

**Comment by rhjones** [comment]
Great. Marking this as closed. Thanks!
