### ISSUE TITLE
getFormFields is not a function

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#262]
So I am trying to do the API. I referenced everything we did in class and asked someone for help.

This is the code that is crashing (and yes, I did require on get-form-fields):

``` js
const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signUp(data)
    .done(ui.onSignUpSuccess)
    .fail(ui.onError);
};
```

This is my error message:

``````
events.js:12 Uncaught TypeError: getFormFields is not a functiononSignUp @ events.js:12dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549```
``````

**Comment by berziiii** [comment]
Can you share what is on line 12 of events.js. Like the error states?

**Comment by julie1013** [comment]
It is in the code block I pasted... this:

``` js
let data = getFormFields(event.target);
```

**Comment by berziiii** [comment]
Can you show where you require `getFormFields`?

**Comment by julie1013** [comment]
In the same file, right here:

``` js
const getFormFields = require('../../../lib/get-form-fields');
```

**Comment by payne-chris-r** [comment]
3 things:
1) have you modified get-form-fields.js in anyway (either the code in the file or the location in the directory)?
2) are you sure the file path is correct?
3) is there anywhere else in your project that you've used get-form-fields yet?

**Comment by julie1013** [comment]
Closed. Not sure exactly what the issue was. There was something that messed things up a little when I changed a line in a file, but that was after I tried something as a shot in the dark to fix the issue. So I'm not sure what the original issue was.

**Comment by jrhorn424** [comment]
@julie1013 modified `get-form-fields.js` and changed how the function was exported. Good catch @berziiii  and @payne-chris-r.
