### ISSUE TITLE
created board, unsure how to process logic.

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/game-project#264]
I have created a dynamic board with HTML & javascript. Using the board I have, I have been trying to create different functions for different events. Firstly, I would like to apply an ID to each of my divs (tiles) that can be pushed into a new array (gameboard) upon a click (I have searched the internet for a way to do this but am not finding much that has been helpful to me for this particular approach). This is the gameboard that I would apply to the object to them be stored in the API. As I am writing this, I am realizing that maybe I do not need to iterate, since I am creating individual divs via JS, but I am not sure how to apply an id and then utilize each one in a new array and in a DRY kind of way. Relevant is below: 

``` HTML
//<div id="game-board" class = "game-board">
//</div>
```

``` JS
// const getFormFields = require('../../lib/get-form-fields');
// 
// let boardArray = [0,1,2,3,4,5,6,7,8];
// let newBoard = [];
// let game = {};
// let playerX = 1;
// 
// let gameboardID = document.getElementById("game-board");
// 
// const createBoard = function() {
//   for (let i = 0; i < boardArray.length; i++) {
//     let newTileDiv = document.createElement('div');
//     newTileDiv.className = 'tile';
//     newTileDiv[i] = boardArray[i];
//     newTileDiv.addEventListener('click', isXO);
//     gameboardID.appendChild(newTileDiv);
//     console.log("I am in createBoard");
//   }
// };

// const isXO = function(event){
//   event.preventDefault();
//   if (playerX === 1) {
//     this.innerHTML = "X";
//     playerX = 0;
//   }
//   else {
//     this.innerHTML = "O";
//     playerX = 1;
//   }
// };
// 
// module.exports = {
//   createBoard,
//   isXO,
// };

```

Other attempts I have considered but have commented out include:

``` JS
// const onTileClick = function(event){
//   event.preventDefault();
//   let data= getFormFields(event.target);
//   if (playerX === 1) {
//     this.innerHTML = "X";
//     gameObj.board.push($);
//     playerX = 0;
//   }
//     else {
//       this.innerHTML = "O";
//       playerX = 1;
//     }
// };
```

I have spoken with some of the cohort and I feel as though I'm on the right track, but implementing what I want to do is different than saying it out loud. I also read a issue #260 - and in re-reading it see that a solution has been posted in the last hour! His board is a bit different than mine, but I will continue to explore that. In the meantime, any guidance is appreciated. Thank you!

**Comment by berziiii** [comment]
@knoddin, if you are able to post a solution from our conversation this morning please do.

**Comment by knoddin** [comment]
working out the problem of adding IDs to my board using the setAttribute, which has worked!

``` js
// const createBoard = function() {
//   for (let i = 0; i < boardArray.length; i++) {
//     let newTileDiv = document.createElement('div');
//     newTileDiv.className = 'tile';
//     newTileDiv.setAttribute('data-id', i);
//     newTileDiv.addEventListener('click', isXO);
//     gameboardID.appendChild(newTileDiv);
//     console.log("I am in createBoard");
//   }
// };
```

I am also working on separating my functions.

**Comment by jrhorn424** [comment]
Glad this is working.

Side note: having terms like `Div` inside your variables is an antipattern. It ties your javascript to your HTML in an undesirable way. What if you wanted to switch all your `div`s to `article`s in the future? Your JS would be out of date and confusing because you made a change to your structural markup.

**Comment by knoddin** [comment]
Good point. Thanks for the tip!
