### ISSUE TITLE
Unable to get sign-out event to work

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#265]
Sign up and sign in work just fine. However, I am getting errors for sign-out.

Relevant code:

handler:

`$('#sign-out').on('submit', events.onSignOut);`

function onSignOut in events file:

``` js
const onSignOut = function(event){
  event.preventDefault();
  // let data = getFormFields(event.target);
    api.signOut()
    .done(ui.signOutSuccess)
    .fail(ui.onError);
};
```

signOut in the api file:

``` js
const signOut = function() {
  let id = app.user.id;
  return  $.ajax({
    url: app.host + '/sign-out/' + id,
    method: "DELETE",
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};
```

It breaks, giving me this error:

`game-api.js:22 Uncaught TypeError: Cannot read property 'id' of undefined`

Line 22 is in the signout function above. It is:

``` js
let id = app.user.id;
```

I did a console.log on my sign in 

``` js
console.log(app.user.id)
```

and it showed the ID, just as I expected. So I'm not sure what is wrong here.

**Comment by laurenfazah** [comment]
In your `signOut` function, after `let id = app.user.id;`, could you `console.log(app)` and post the output after a sign out attempt?

**Comment by julie1013** [comment]
The `console.log(app)` doesn't give me anything, and I still get this response:

`game-api.js:22 Uncaught TypeError: Cannot read property 'id' of undefined`

**Comment by berziiii** [comment]
How are you requiring `app` in the api file? I remember you had a different name for that file and thus maybe you're missing a naming detail.

**Comment by julie1013** [comment]
No, I changed it back to app, and I made sure it was requiring. All the other events (sign up and sign in) are still working.

`const app = require('./game/app');`

**Comment by berziiii** [comment]
can you share where you're assigning `app.user`? Should be somewhere in the `ui.js`.

**Comment by julie1013** [comment]
I'm not sure what it is you're looking for. Do you mean what `app` is referencing?

**Comment by berziiii** [comment]
where do you have a similar line to `app.user = data.user`?

**Comment by julie1013** [comment]
No... where would I make this assignment?

**Comment by berziiii** [comment]
Go reference api-token-auth and see what happens when a successful signin occurs and the response that we get and how we manage it. It will be in ui.js and be part of the above point;

`app.user = data.user`.

**Comment by julie1013** [comment]
OK, so now I have made the change. These two functions in my ui file now say:

```
const onSignInSuccess = function (data) {
    app.user = data.user;
    console.log("You are now signed in", data);
};
```

```
const onSignOutSuccess = function(){
  console.log("You are now signed out!");
  app.user = null;
};
```

And that indeed works! Thank you!
