### ISSUE TITLE
Javascript - Error in Browser Console

### ISSUE THREAD

**Issue by james-coombs** [ga-wdi-boston/game-project#266]
I am getting the error: "Uncaught TypeError: api.newGame is not a function" in my browser console when attempting a 'POST' request for a new game.

I have a HTML button to create a new game.

```
// index.html
<button type="button" id="new-game-button" class="btn btn-default navbar-btn">New Game</button>
```

I have an event handler to select the HTML and call the onNewGame function in my game-logic/events file.

```
// index.js
'use strict';

require('./example');

const userEvents = require('./users/events');

const gameEvents = require('./game-logic/events');

$(() => {
  $('#createUser').on('submit', userEvents.onCreateUser);
  $('#signInUser').on('submit', userEvents.onSignInUser);
  $('#changePassword').on('submit', userEvents.onChangePassword);
  $('#sign-out-modal-button').on('click', userEvents.onSignOutUser);
  $('#new-game-button').on('click', gameEvents.onNewGame);
```

The onNewGame function gets called and clears the HTML in the specified elements, but stops at the line `api.newGame(data)` and I get the error in my browser console.

```
// events.js
'use strict';

const api = require('./api');

const ui = require('./ui');

const app = require('../app.js');

const onNewGame = function onNewGame (event) {
  event.preventDefault();
  $('.col-xs-4').html('');
  let data = {};
  api.newGame(data)
    .done(ui.newGameSuccess)
    .fail(ui.onError);
};
```

It should be continuing to my newGame function in api.js as seen below.

```
'use strict';

const app = require('../app');

const newGame = (data) =>{
  return $.ajax({
    url: app.host + '/games',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data,
  });
};
```

I am able to call all my other functions specified in index.js.
Debuggers placed before `api.newGame(data)` trigger, those placed after do not.

**Comment by berziiii** [comment]
are you exporting the `newGame` function from the `api.js` file?

**Comment by james-coombs** [comment]
Yes, this was in my `api.js`:
`module.export = {
  newGame,
};`

I just changed it to `module.exports = {
  newGame,
};`

and was able to make the post. Turns out that "s" was pretty important!

**Comment by james-coombs** [comment]
A spelling error withheld the newGame function from exporting from api.js.

`module.export = {
  newGame,
};`

was changed to:

`module.exports = {
  newGame,
};`
