### ISSUE TITLE
Trying to get values for updating the game on the server

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#269]
So in order to get the values to update the state of the game on the server, I figured I'd grab the ID of a cell, which is a number:

In play-handlers.js, I have this function:

``` js
const play = function (cell) {
    logic.player = logic.isPlayerTurn();
    logic.setCellData(cell, logic.player);
    ui.setCell(cell, logic.player);
    events.onUpdateBoard(cell);
    console.log(logic.currentGame.game.cells);
    if (logic.winCheck() || logic.tieCheck()) {
      $('.board').children().off();
      logic.currentGame.game.over = true;
      logic.scoreCounter();
      setTimeout(function () {
        console.log(logic.currentGame.game.cells);
        logic.restartGameData();
        $('.board div').children().remove();
        setUpHandlers();
      }, 3000);
    } else {
      logic.turnSwitch();
    }
  };
```

As you can see, it calls 

``` js
events.onUpdateBoard(cell)
```

the function fires:

``` js
const onUpdateBoard = function (cell) {
  console.log("on onUpdateBoard");
  let cellID = $(cell).attr('id');
  cellID = parseFloat(cellID);
  console.log(cellID);
  api.updateBoard(cellID)
  .done(ui.onUpdateBoardSuccess)
  .fail(ui.onError);
};
```

the console.log of cellID tells me that cellID is not a number. So needless to say it does not go beyond there! 

Error messages:

```
jquery.js:9175 OPTIONS http://tic-tac-toe.wdibos.comundefined/ net::ERR_NAME_NOT_RESOLVEDsend @ jquery.js:9175ajax @ jquery.js:8656updateBoard @ game-api.js:78onUpdateBoard @ events.js:67play @ play-handlers.js:11(anonymous function) @ play-handlers.js:35dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-09-09 16:38:27.571 jquery.js:9175 XHR failed loading: PATCH "http://tic-tac-toe.wdibos.comundefined/".send @ jquery.js:9175ajax @ jquery.js:8656updateBoard @ game-api.js:78onUpdateBoard @ events.js:67play @ play-handlers.js:11(anonymous function) @ play-handlers.js:35dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-09-09 16:38:27.571 ui.js:45 Object {readyState: 0, status: 0, statusText: "error"}onError @ ui.js:45fire @ jquery.js:3187fireWith @ jquery.js:3317done @ jquery.js:8759(anonymous function) @ jquery.js:9115
```

**Comment by jrhorn424** [comment]
Cell IDs are strings by default. If you use `data-id` instead of `id` in your HTML, you can use jQuery's `data` method to extract the number, and jQuery will automatically convert it for you.

See #268 and http://api.jquery.com/data/#data2.

@laurenallegra Has an example implementation in her game, but these docs should get you off the ground and solve the "not a number" problem.

**Comment by julie1013** [comment]
Changing all instances of id in the html to data-id... But there doesn't seem to be a way to concatenate the data-id thing. This is a problem as I need the id numbers to put images on the squares. 

For example, for set cell I have:

``` js
const setCell = function (cell, player) {
  $('#' + cell).html
    ('<img src = ../../assets/images/' + player + '.png style="width: 130px">')
      .off();
    logic.setCellData(cell, player);
};
```

But replacing '#' with 'data-id' doesn't work. I looked up ways to do the concatenation, and I'm not finding anything. Also tried `$(cell).data('id').` That didn't work either. Still can't see the images on the squares.

**Comment by julie1013** [comment]
Obviously what I REALLY need is the value of each cell number (x or o). So I realized the most direct way to do that was this:

`let data = logic.currentGame.game.cells[cell];`

and it works.

**Comment by laurenallegra** [comment]
## nice job, julie! glad your code is working. i’m coming in shortly so i;ll see you later.

Lauren Allegra Schwartz
lauren.allegra@gmail.com
