### ISSUE TITLE
Bootstrap Module not found

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/game-project#27]
`ERROR in multi vendor
Module not found: Error: Cannot resolve module 'bootstrap-scss' in /home/ajordon/wdi/projects/Tic-Tac-Toe
@ multi vendor`

I have updated my `package.json, webpack.js` and I have the bootstrap directory `node_modules/bootstrap-sass`
Still no luck

**Comment by GA-MEB** [comment]
It looks like you probably have a typo somewhere. Something is trying to call `boostrap-scss` instead of `bootstrap-sass`.

You said you checked webpack.js?

**Comment by ajordon** [comment]
Yes I have webpack.js

``` js
options: {
    entry: {
      bundle: './index.js',
      specs: './spec/_all.js',
      vendor: ['jquery', 'bootstrap-sass'],
    },
```

package.json

``` js
  "bootstrap-sass": "^3.3.6",
```

**Comment by ajordon** [comment]
I was looking at the wrong atom window. It was a spelling error in my webpack.js
