### ISSUE TITLE
I can't get the game board to lock after win condition is met 

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/game-project#270]
I was able to get the board to lock, but I had to call on a function before it was defined. I got the desired result, but I can see this leading to issues later. 
How I got it to work

``` .js
    const updateBoard = function(cell) {
      if (verticalWin() === true || horizontalWin() === true || diagonalWin() === true && isValidMove === true){
        console.log("locks board");
        return false;
      }
      let index = $(cell).data("id");
      if (turn %2 === 0) {
        $(cell).html('X');
        board[index] = 'x';
      }else {
        $(cell).html('O');
        board[index] = 'o';
      }
      turn++;
      console.log(board);
    };

    const isValidMove = function(cell) {
      if ( $(cell).html() === "" ) {
        updateBoard(cell);
      } else {
        alert('Please make a valid move.');
      }
    };
```

I tried to writw a function to lock the board. The console log worked, but since the function is not in  the update board function it didn't lock the board. 

``` .js
    const lockBoard = function() {
          if (verticalWin() === true) {
          console.log("lock");
        }else if (diagonalWin() === true) {
          console.log("lock");
        }else if (horizontalWin() === true) {
          console.log("lock");
        }
        return false;
      };
```

Is there a way I can either tie the lockBoard function back to the updateBoard function, or us the if statement without the circular reference?

**Comment by laurenfazah** [comment]
Have you tried calling lockBoard() from your updateBoard() function? 

As an alternative, may I suggest looking into CSS's pointer-events. It may provide a more simple "locking" solution.

**Comment by rosmith76** [comment]
Jeff helped me with a solution at the end of the day. I should be able to get everything working again tonight.
