### ISSUE TITLE
[CSS/Lint] - Lint Error for 'too specific' style selector, but needed to overwrite default bootstrap css?

### ISSUE THREAD

**Issue by tuckyeah** [ga-wdi-boston/game-project#272]
So I'm trying to overwrite the default bootstrap styling for navbar links, because the default one has a bunch of ugly padding and margins and stuff that I want to get rid of, but the default bootstrap rule for these navbar links is super specific and hard to find/overwrite/elbow aside.

I tried to overwrite the bootstrap rule directly by using the same selector that's in bootstrap's css:

``` [CSS]
.navbar-default .navbar-nav > li > a 
```

but then I got THIS linter error:

```
[SelectorDepth] Selector should have depth of applicability no greater than 3, but was 4. 
```

I tried  by writing my own rule with matching specificity in my own css:

``` [CSS]```
.navbar-nav > li.stacked > a
```

but then I got this Linter error:

```
[QualifyingElement] Avoid qualifying class selectors with an element.
```

I realize this is a pretty minor styling thing, and I can't seem to get rid of the linter error, or come up with a similar selector / solution that will make it happy. And it's driving me nuts!

Thanks in advance~

**Comment by laurenfazah** [comment]
Did .navbar-nav > li.stacked > a work for you? 

I believe that last linter error just wants li removed from li.stacked...maybe that'll help?

**Comment by tuckyeah** [comment]
No dice :( 

I tried:

.navbar-nav > li.stacked > a
.navbar-nav > li .stacked > a
.navbar-nav > .stacked li > a
.navbar-nav > .stacked > a

The first three result in the same linter errors as before (QualifyingElement for the first two and SelectorDepth for the third), and the last one apparently isn't specific enough to override the bootstrap styles. 

In addition to my own custom class of 'stacked,' I tried adding a custom ID to the HTML to target the links, but then my linter just yells at me for using an ID in my CSS. Sigh.

**Comment by jrhorn424** [comment]
The preferred way to override styling is to create a custom class and apply it where needed.

**Comment by jrhorn424** [comment]
I wouldn't worry too much. Don't use IDs for styling. Ever.

**Comment by tuckyeah** [comment]
Okie dokie - I just wanted to make sure it wasn't too big of a concern :) I'll leave it as is, or maybe see if I can add some more custom classes. Thanks!
