### ISSUE TITLE
[HTTP/HTTPS] Insecure XMLHttpRequest endpoint error on GH Pages

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/game-project#273]
My app is working locally: I can sign up, log in, change the password, log out, create a new game, play a multiple sequential games, and track a user's total wins/losses/ties.

When I deploy to GitHub Pages and try to log in, I get the following error:

```
vendor.bundle.js:9285 
Mixed Content: The page at 'https://rebekahheacock.github.io/tic-tac-toe/' was loaded over
HTTPS, but requested an insecure XMLHttpRequest endpoint  'http://tic-tac-toe.wdibos.com/sign-in'. 
This request has been blocked; the content must be served over HTTPS.
```

When I set app.host to `'https://tic-tac-toe.wdibos.com'` to try to fix this, I get this error on my local version and on GH pages:

`https://tic-tac-toe.wdibos.com/sign-in Failed to load resource: net::ERR_CONNECTION_REFUSED`

As of June, GitHub is [forcing all GitHub Pages on the github.io domain onto HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/). It doesn't look like our API supports HTTPS. Any thoughts on where to go from here?

**Comment by tuckyeah** [comment]
I get the exact same error when I try to sign in after I deployed 
(https://tuckyeah.github.io/project-1/)

My game works fine locally too. Sorry I don't have more advice, just wanted to chime in and say I'm in the same boat!

**Comment by jrhorn424** [comment]
This was expected. Excellent write-up, Rebekah.

Change your API host URL to https://aqueous-atoll-85096.herokuapp.com/ and then redeploy.

**Comment by rhjones** [comment]
Thanks, @jrhorn424. Using an API host that uses HTTPS fixed the issue.
