### ISSUE TITLE
Displaying who has won the game

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#276]
I wrote a function in my logic file to declare who has won the game:

``` js
const winnerDeclare = function (winner) {
  let declaration = "" + winner + " has won this round!";
  return declaration;
};
```

It works (taking winner from the winCheck function). In the interest of separation of concerns, I put a function in ui to display this declaration:

``` js
const displayWinner = function(){
  $('.display-winner').html(logic.winnerDeclare(logic.winner));
};
```

I did require from logic.js and I did export from logic.js. However, this keeps coming back as undefined. While keeping my concerns separate, is there a way to access the local variable in the function in the logic file?

I did try Googling this but nothing that would help is coming back.

**Comment by tuckyeah** [comment]
Try setting the a variable to the return of the logic.winnerDeclare in the displayWinner function, and then calling html passing it that variable?

So something like

```
const displayWinner = function () {
   let winner = logic.winnerDeclare(logic.winner);
   $('.display-winner').html(winner);
}
```

Just a thought! Hope this helps :)

**Comment by tuckyeah** [comment]
Or try returning only the winner from the declare winner function and making / displaying the string in the displayWinner function?

**Comment by julie1013** [comment]
Thanks, but none of these work. Ultimately the issue is that checking for a winner returns the winner variable, that variable is local. I can't access a local variable from that function in another file. And if I do it within the function that finds the winner-- that is, if I change it from this-- 

``` js
const winCheck = function () {
  return horizontalWin() || verticalWin() || diagonalWin();
};
```

to this:

``` js
const winCheck = function () {
 if (return horizontalWin() || verticalWin() || diagonalWin()) {
   $('.display-stats').html('' + winner + ' has won the game.');
}
```

For some reason it doesn't run all the other functions in here (which stop players from continuing to play after someone has won-- see  `wincheck` in there):

``` js
const play = function (cell) {
    logic.player = logic.isPlayerTurn();
    logic.setCellData(cell, logic.player);
    ui.setCell(cell, logic.player);
    events.onUpdateBoard(cell);
    console.log(logic.currentGame.game.cells);
    if (logic.winCheck() || logic.tieCheck()) {
      gameOver();
      $('.board').children().off();
      logic.scoreCounter();
      setTimeout(function () {
        logic.restartGameData();
        $('.board div').children().remove();
        setUpHandlers();
        $('.board div').css("pointer-events", "none");
      }, 3000);
    } else {
      logic.turnSwitch();
    }
  };
```

**Comment by julie1013** [comment]
Despite violation of separation of concerns, I ended up doing this in the logic file. Unless there's anything else you can suggest, I'm moving on to other requirements as I've been battling this one for the past day. So here is what I did:

``` js
const displayWinner = function () {
  if (winner === null) {
    $('.display-stats').html("It's a tie!");
  } else if (winner){
  $('.display-stats').html('' + winner + ' has won the game.');
  }
};
```

**Comment by jrhorn424** [comment]
Since this function:

``` js
const winnerDeclare = function (winner) {
  let declaration = "" + winner + " has won this round!";
  return declaration;
};
```

receives `winner` as an argument, and `winner` is a local variable in the `logic` file, declaring the winner variable at the top of the file and mutating it within `logic` would allow you to do this instead, without violating separation of concerns:

``` diff
- const winnerDeclare = function (winner) {
+ const winnerDeclare = function () {
  let declaration = "" + winner + " has won this round!";
  return declaration;
};

// elsewhere

const displayWinner = function(){
-  $('.display-winner').html(logic.winnerDeclare(logic.winner));
+  $('.display-winner').html(logic.winnerDeclare());
};
```
