### ISSUE TITLE
update board function is not passing data to server

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/game-project#278]
Workflow for this is log in, hit new game button
I have tried this a few different ways, and i get similar but different error messages with each
logic.js in game folder

``` .js
    const updateBoard = function(cell) {
      let index = $(cell).data('index');
      board[index] = player;
         let data = {};
        api.updateBoard(data)
          .done(ui.updateBoardSuccess)
          .fail(ui.failure);
    };
  const onCellClick = function (event){
      if (isValidMove(event.target)){
        placeMarker(event.target);
        updateBoard(event.target);
        changePlayer();
        diagonalWin();
        verticalWin();
        horizontalWin();
        boardFull();
        gameOver();
        catsGame();
        console.log(board);
      }
    };
```

api.js in game folder

``` .js
const updateBoard = (data) => {
  return $.ajax({
    url: app.host + '/update/games/:id',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};
```

error messages with this set 
tic-tac-toe.wdibos.com/update/games/:id:1 PATCH http://tic-tac-toe.wdibos.com/update/games/:id 
2016-09-11 16:24:18.787 localhost/:1 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/update/games/:id. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.
2016-09-11 16:24:18.787 jquery.js:9175 XHR failed loading: PATCH "http://tic-tac-toe.wdibos.com/update/games/:id".send @ jquery.js:9175ajax @ jquery.js:8656updateBoard @ api.js:28updateBoard @ logic.js:89onCellClick @ logic.js:136dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-09-11 16:24:18.788 ui.js:11 Object {readyState: 0, status: 0, statusText: "error"}

I also represented the link this way
api.js

``` .js
const updateBoard = (data) => {
  return $.ajax({
    url: app.host + '/update/'+ app.games.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};
```

the error message with this option
api.js:29 Uncaught TypeError: Cannot read property 'id' of undefined

my ui

``` .js
const updateBoardSuccess = (data) => {
  app.game = data.game;
  console.log(app.game);
};
```

**Comment by rosmith76** [comment]
I just had to remove a good chunk of this code because it broke the board function. 

``` .js
    const updateBoard = function(cell) {
      let index = $(cell).data('index');
      board[index] = player;
    };
```

This is what I have left. I am still having trouble getting game data to the server. I can sign in, get new game, then that's it.

**Comment by berziiii** [comment]
When data.game returns on successful board update, do you get the ID of the game? When you create a new game, you should be able to store the game id there. Check your responses to ensure you're storing the game ID once a game is created.

**Comment by rosmith76** [comment]
I do get an ID. 
Object {id: 20220, cells: Array[9], over: false, player_x: Object, player_o: null}
cells
:
Array[9]
id
:
20220
over
:
false
player_o
:
null
player_x
:
Object
**proto**
:
Object

**Comment by rosmith76** [comment]
new game api code

``` .js
const newGame = () => {
  let token = app.user.token;
  return $.ajax({
    url: app.host + '/games',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + token,
    }
  });
};
```

logic/events code

``` .js
    const onNewGame = function (event) {
        event.preventDefault();
        // let data = getFormFields(event.target);
        console.log("new game");
        let data = {};
        api.newGame(data)
          .done(ui.newGameSuccess)
          .fail(ui.failure);
      };
```

ui

``` .js
const newGameSuccess = (data) => {
  app.game = data.game;
  console.log(app.game);
};
```

**Comment by jrhorn424** [comment]
Please format your previous comment, as well as your original post.

**Comment by rosmith76** [comment]
how do I format a console result?

**Comment by jrhorn424** [comment]
Wrap it in three backticks and a new line, just like any other code block.

**Comment by jrhorn424** [comment]
This is your problem `url: app.host + '/update/games/:id',`. How do you grab a game ID out of memory and add it to the URL string?

**Comment by jrhorn424** [comment]
Any updates @rosmith76?

**Comment by rosmith76** [comment]
still working on it. got sidetracked with other stuff.

**Comment by rosmith76** [comment]
I can't figure out how to get the ID out of the game object I create when I start a new game.

**Comment by berziiii** [comment]
Back to my previous point on 'app.game', you should be able to store the id in the game object now living in the app file. Thus when you go to send a request with the game id, it would be something like:

host = app.host + '/<some route>/' + app.game.id

**Comment by berziiii** [comment]
Formatting broke from my phone,

host = app.host + '/games/' + app.game.id

**Comment by rosmith76** [comment]
That makes sense now, and it worked! Thanks
