### ISSUE TITLE
"data.option is not a function" in bootstrap.js errors when using a modal element

### ISSUE THREAD

**Issue by bullhead242** [ga-wdi-boston/game-project#279]
`grunt nag` output returns all style errors, but no errors regarding extra or missing syntax errors. 

To assign initial actions to a click on a game cell, i have created the `whenClicked` function. 

```
function whenClicked(event) {
  const cellIndex = parseInt(event.target.dataset.index);
  if (app.game.cells[cellIndex] === ""){
    $.fn.bootstrapBtn = bootstrapButton;
    switchTurn();
    return(cellIndex);
  } else {
    alert('NOPE');
  }
}
```

This contains a test for a move's validity, a condition should the move be invalid, and causes the next player's turn to begin which uses a function i have called `switchTurn`. 

```
const switchTurn = function() {
  if (player === 'X') {
    player = 'O';
  }else{
    player = 'X';
    $("#messages").modal("Hey it's player" + player + "'s turn!'" );
  }
};
```

Part the last part of the function contains a uses jQuery to find an DOM element with the ID of `message`, and uses the `.modal` method to add text to the element, which has been used in a similar way to display the email of the user, and the number of games played after logging in. 

The page loads, a user can be created or logged in and a new game begun without issue. The issue occurs after a click occurs inside the game board and the `whenClicked` function runs, which contains the `switchTurn` callback. The error in the browser is as follows:

```
bootstrap.js:1215 Uncaught TypeError: data[option] is not a function
(anonymous function) @ bootstrap.js:1215<br>
each @ jquery.js:365
each @ jquery.js:137
Plugin @ bootstrap.js:1209
switchTurn @ events.js:51
whenClicked @ events.js:58
dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549
```

I changed the `.modal` and moved the html related the element around a bit to no avail. A debugger run inside the `switchTurn` function where the `.modal` is called directs me to a section of `jquery.js` and `bootstrap.js`. 

When searching Google and StackOverflow for the error message, `data[option] is not a function`, the [first](http://stackoverflow.com/questions/8586306/bootstrap-modal-is-not-a-function) result pulls up some code with very vague usage instructions which I implemented to no avail. This post also referenced a potential conflict between Bootstrap and jQuery which led me to Google "bootstrap conflict with jquery" and came back with [another result](http://stackoverflow.com/questions/23428285/bootstrap-and-jqueryui-conflict) which mentioned using a `tooltip` function which I have not added or called. 

It seems I have stumbled into a conflict with the existing libraries, and I am not certain what steps I can take to remedy them, as the listed sections of `bootstrap.js` and `jquery.js` look to be above my proverbial pay grade. 

Thank you for taking the time. 
Pete

**Comment by jrhorn424** [comment]
> grunt nag output returns all style errors, but no errors regarding extra or missing syntax errors.

I'd really like you to have clean linter output before you present.

> ```
> $.fn.bootstrapBtn = bootstrapButton;
> ```

Explain in your own words what this line does.

> It seems I have stumbled into a conflict with the existing libraries

It's possible. I've never seen anyone use `.modal` to display information. Better UI would suggest having a messages div styled to call attention to it that exists as part of the view and can be seen while the player plays the game.

**Comment by jrhorn424** [comment]
Looks like `.modal` doesn't work like you were expecting. Please see the documentation: http://getbootstrap.com/javascript/#modals-methods

**Comment by jrhorn424** [comment]
Can you show me how you were using it successfully elsewhere? Code snippets?

**Comment by berziiii** [comment]
@bullhead242, where does his stand? Modals need an option to trigger it to show or hide. That's what @jrhorn424 may have been referencing. It appears you're trying to use a combination of jquery to render text into a modals body but you're missing a key option to get the modal to show.

**Comment by bullhead242** [comment]
@berziiii looking at the key option now. Will go back into the bootstrap documentation. 

Mostly, I didn't run into any other issues when using the modal which is attached to my "sign in" button. The `.modal` method was previously a `.text` and the #messages ID was tied to an `aside` element, but I felt the modal was more effective in notifying the user about invalid turns or finished games.

**Comment by bullhead242** [comment]
Issue resolved/ rendered irrelevant by adding `.text` to a new element available as a new sidebar element. 

I suspect issue was with the command to open the modal element instead of the element or any of the conent.
