### ISSUE TITLE
Button disappears when app is deployed

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#280]
When I run on localhost:8080, all my buttons are there and the game works perfectly.

When I tried deploying, the button "New Game" (which is hidden until the user signs in) is not there. But all the other stuff that's hidden until sign-in appears. The DOM shows that the button is there, but display is "none". Why? I don't know. I don't know why this happens, why everything is normal on localhost:8080 but not when I deploy the app. But I do know that I need to get this fixed ASAP because the game cannot be played if the "New Game" button doesn't work.

**Comment by nlkassad** [comment]
@julie1013 can you post up some links to the code that you think it might be related to the issue?

**Comment by laurenfazah** [comment]
What CSS selector is applying display:none to the element? You can check this in the styles console when you inspect the button(s) in the browser. 

Alternatively, something jQuery related could be setting your button(s) to hide().

**Comment by julie1013** [comment]
That's the thing, I DON'T know what code would be related to this issue, unless you mean specifically the html and css code. But as I've said, it works fine on localhost, but it doesn't work when I deploy it.

**Comment by jrhorn424** [comment]
Did you run `grunt build` before you deployed?

**Comment by julie1013** [comment]
Yes, and other students were standing around me to make sure I was doing it right (I asked them to). :)

**Comment by jrhorn424** [comment]
@julie1013 Stop thrashing and please do what @laurenfazah suggested. It's the right debugging step at this stage. None of us have enough information to help you debug.

You **have** to calm down and be ok with things not working. Everything will be figured out eventually.

**Comment by jrhorn424** [comment]
Following process is **especially** important during crisis mode. It is non-negotiable.

**Comment by julie1013** [comment]
Unfortunately now I can't even sign in anymore to see what the CSS on the button says. I get this error message while trying to sign in:

```
vendor.bundle.js:9285 Mixed Content: The page at 'https://julie1013.github.io/tic-tac-toe-template/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tic-tac-toe.wdibos.com/sign-in'. This request has been blocked; the content must be served over HTTPS.send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signIn @ bundle.js:520onSignIn @ bundle.js:382dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
2016-09-11 23:46:36.564 vendor.bundle.js:9285 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/sign-in. Failed to start loading.
```

**Comment by jrhorn424** [comment]
**One** error at a time. **One** change at a time. If a change doesn't fix something, **undo** that change before trying something else.

Have you done what @laurenfazah suggested? Is the 'New Game' button supposed to appear when you are not signed in?

**Comment by julie1013** [comment]
No, I didn't change anything. What's supposed to happen is that I sign in and the "new game" button appears. Before what was happening was I signed in and the button didn't appear like it was supposed to (but it did on localhost). But now that I'm home I turned on my computer again and tried to sign in, but that didn't work. I need to sign in to get to the stage where the app failed.

**Comment by jrhorn424** [comment]
> No, I didn't change anything.

So sign in never worked when deployed?

**Comment by jrhorn424** [comment]
Restart your server. Open a new private (incognito) tab and develop there. It keeps the cache clean. Try to reproduce the sign-in error and record _exact_ steps to reproduce, and add them to this issue.

If sign-in is working, record _exact_ steps to reproduce the the button not hidden error, then show me a screenshot of your web inspector open, the CSS panel open, and the hidden button selected in the DOM inspector.

**Comment by julie1013** [comment]
No, I mean sign in DID work when deployed, at least the last time I turned on my computer. But then I came home from GA, saw your message, turned on the computer and tried to login again. This time I get error messages. Actually I'm wonder now that since the sign in screen changes whether or not your login was successful (that was one thing I regret not having enough knowledge to work with, to give some kind of alert message that it doesn't work) that this is the heart of the issue. But again, it doesn't make sense, because every time I "sign in", all the other buttons and fields that should appear when I sign in do appear.

Restart the server? What do you mean? Again, it works fine on localhost:8080, if that's what you're referring to.

**Comment by jrhorn424** [comment]
Cancel `grunt serve`. Start it again.

**Comment by julie1013** [comment]
Wait, I'm losing you here... `grunt serve` is for localhost, isn't it? Or would you like me to restart the deploying process?

**Comment by jrhorn424** [comment]
Right! Sorry. Ignore that instruction. Thanks for your patience.

**Comment by jrhorn424** [comment]
Any updates?

**Comment by julie1013** [comment]
No, I was waiting for you... did I miss some instructions?

**Comment by jrhorn424** [comment]
Yes, please re-read starting about 40 minutes ago. Read carefully.

**Comment by julie1013** [comment]
You mean, this right?

```
Restart your server. Open a new private (incognito) tab and develop there. It keeps the cache clean. Try to reproduce the sign-in error and record exact steps to reproduce, and add them to this issue.

If sign-in is working, record exact steps to reproduce the the button not hidden error, then show me a screenshot of your web inspector open, the CSS panel open, and the hidden button selected in the DOM inspector.
```

Again, isn't that for localhost 8080? As I've said, that works fine. It's the issue with DEPLOYING. I posted the error message I got while signing in (as I've said, I'm wondering if the overall issue is that signing in isn't working, even though some of the hidden buttons appear when it LOOKS LIKE I've signed in).

**Comment by wmcb91** [comment]
Hi Julie,
You may have resolved this already, but I think your issue with the mixed content error when attempting to sign in is from your app still having `http://tic-tac-toe.wdibos.com` as your host and not `https://aqueous-atoll-85096.herokuapp.com`.  Try changing the host and committing then redeploying.  I know I had that issue serval times because I forgot to switch hosts when moving between gh-pages and localhost.

**Comment by nlkassad** [comment]
Good call Will! 
Julie it's worth double checking to see if that's updated in your app.js file. You can also check your console logs on your deployed application to see if you're getting any specific errors.

**Comment by julie1013** [comment]
Thanks, but I've tried changing the host. It didn't help.

**Comment by wmcb91** [comment]
Hi Julie,

Ok not I am almost certain we went through the same process and the issue is you're not really redeploying.  I was doing the same thing, thinking I was making the changes and pushing to gh-pages but absolutely nothing happened and I was baffled (and pissed), then I realized I may not have this whole 'redeploying' thing right.  My understanding is the process is like this.

``` md
Once you have your code in the master branch  looking the way you want in local
1. Checkout gh-Page
2. Merge master
3. Change host from HTTP to HTTPS url if it isn't already changed
4. Add & Commit
5. Grunt build
6. Add & commit (it will just show you edited bundle.js)
7. Git push origin gh-pages
```

I was skipping step 5 and 6 so even though I pushed to gitHub, nothing changed.  My best guess is that you are doing the same since your frustration so closely matched my own.  Good luck!

**Comment by julie1013** [comment]
Changing the host URL to this: `https://github.com/ga-wdi-boston/project-presentations` and redeploying solved the problem.

**Comment by jrhorn424** [comment]
@julie1013 Is that the correct URL? I don't want this to be confusing for future folks looking at this issue.

**Comment by julie1013** [comment]
No, that was an embarrassingly massive brain fart that probably came as a result of stress. I have absolutely no idea where I got the URL from. 
It's this: `https://aqueous-atoll-85096.herokuapp.com/`

**Comment by jrhorn424** [comment]
Thanks!

**Comment by julie1013** [comment]
![dolphin](https://cloud.githubusercontent.com/assets/14143334/18516932/bda8149c-7a68-11e6-8602-090fd428287f.jpg)
