### ISSUE TITLE
"It's a tie" displays no matter who wins.

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/game-project#282]
When I was in the process of fixing the issue in which the X and O didn't appear on the board, I discovered another issue-- that if you got a tie ON YOUR FIRST GAME, winner wasn't displayed. Brian helped me fix this; it looked like the issue was that I had forgotten to pass winner as a parameter to displayWin function. Why it worked with the other conditions? Who knows. So that appeared to fix it... But then later that evening (despite having not made any further changes) NO WINNERS were displaying. 

At what I admit were only shot-in-the-dark attempts, I tried declaring and calling the function WITHOUT using winner as a parameter/argument. In BOTH cases, it now declares a tie no matter who wins. Here is the relevant code:
From my logic file:

``` js
const horizontalWin = function () {
    if (currentGame.game.cells[0]  &&
        currentGame.game.cells[0] === currentGame.game.cells[1] &&
        currentGame.game.cells[0] === currentGame.game.cells[2]) {
      winner = currentGame.game.cells[0];
    } else if (currentGame.game.cells[3]  &&
              currentGame.game.cells[3] === currentGame.game.cells[4] &&
              currentGame.game.cells[3] === currentGame.game.cells[5]) {
      winner = currentGame.game.cells[3];
    } else if (currentGame.game.cells[6] &&
              currentGame.game.cells[6] === currentGame.game.cells[7] &&
              currentGame.game.cells[6] === currentGame.game.cells[8]) {
      winner = currentGame.game.cells[6];
    }
    return winner;
```

``` js
const verticalWin = function () {
    if (currentGame.game.cells[0] &&
        currentGame.game.cells[0] === currentGame.game.cells[3] &&
        currentGame.game.cells[0] === currentGame.game.cells[6]) {
      winner = currentGame.game.cells[0];
    } else if (currentGame.game.cells[1] &&
      currentGame.game.cells[1] === currentGame.game.cells[4] &&
      currentGame.game.cells[1] === currentGame.game.cells[7]) {
      winner = currentGame.game.cells[1];
    } else if (currentGame.game.cells[2] &&
              currentGame.game.cells[2] === currentGame.game.cells[5] &&
              currentGame.game.cells[2] === currentGame.game.cells[8]) {
      winner = currentGame.game.cells[2];
    }
    return winner;
  };
//checks for vertical setup for possible win

const diagonalWin = function () {
  if (currentGame.game.cells[4]) {
    if (currentGame.game.cells[4] === currentGame.game.cells[0] &&
      currentGame.game.cells[4] === currentGame.game.cells[8] ||
      currentGame.game.cells[4] === currentGame.game.cells[2] &&
      currentGame.game.cells[4] === currentGame.game.cells[6]) {
      winner = currentGame.game.cells[4];
    }
  }
  return winner;
};
```

``` js
const winCheck = function () {
  return horizontalWin() || verticalWin() || diagonalWin();
};
```

``` js
const tieCheck = function () {
  let count = 0;
  for (let i = 0; i < currentGame.game.cells.length; i++) {
    if (currentGame.game.cells[i] === 'x' || currentGame.game.cells[i] === 'o'){
      count++;
    }
  }
  return count === 9;
};
```

Here is the function where I've tried setting winner as an parameter in some attempts (why it has ever worked without it, I'm not sure). ALso, this is in logic because I couldn't figure out how to work my way around SOC issues.

``` js
const displayWinner = function () {
  if (winner === null) {
    $('.display-stats').html("It's a tie!");
  } else if (winner){
  $('.display-stats').html('' + winner + ' has won the game.');
  }
};
```

And finally, in the playHandlers file:

``` js
const play = function (cell) {
    logic.player = logic.isPlayerTurn();
    logic.setCellData(cell, logic.player);
    ui.setCell(cell, logic.player);
    events.onUpdateBoard(cell);
    if (logic.winCheck() || logic.tieCheck()) {
      gameOver();
      $('.board').children().off();
      logic.displayWinner();
      setTimeout(function () {
        logic.restartGameData();
        $('.board div').children().remove();
        $('.display-stats').html('');
        setUpHandlers();
        $('.board div').css("pointer-events", "none");
      }, 3000);
    } else {
      logic.turnSwitch();
    }
  };
```

``` js
const setUpHandlers = function () {
  $('.board div').on('click', function () {
    let targetCell = $(this).attr('id');
    targetCell = parseFloat(targetCell);
    if (logic.isVacantCell(targetCell)) {
      play(targetCell);
    }
  });
};
```

**Comment by julie1013** [comment]
Update: It gets more interesting. I just came home, and I played the game again on both my laptop and desktop. Everything is working as it should be. So why did it have the glitch earlier today? Is there some kind of significant delay between deployment and functioning? In any case, I'm happy about this development but also cautious about closing this issue right away.

**Comment by jrhorn424** [comment]
@julie1013 If you can reproduce the issue, please provide the exact steps to do so. If you can't reproduce, can we consider this closed?

**Comment by julie1013** [comment]
As I've said, I have tested this numerous times. It seems to be working. So yeah, it's closed. I am curious to know why WAITING a bit after it was deployed changed the function.

**Comment by jrhorn424** [comment]
> curious to know why WAITING a bit after it was deployed changed the function.

Oh, cool! I can answer that. When you deploy to gh-pages, GitHub copies your website to a bunch of different servers around the world so that now matter where your page is accessed, it's always got a low latency.

When you push new updates, not every server gets updated at the same time. It takes a while for all of the servers to get a new copy of your page. If I make changes and don't notice a difference, I usually wait five minutes. If it still isn't updated, I work on another feature and return to testing to the deployed app later. If it still isn't updated after an hour, **most of the time** I've made a mistake somewhere.

**Comment by julie1013** [comment]
Right, but I was seeing it do something that I had never programmed it to do, and then a little bit later it wasn't doing it anymore;.
