### ISSUE TITLE
PATCH - update game only works for player O

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/game-project#283]
I would like to call my api.updateGame function after each player's turn. It seems that I can successfully patch to the server after player O's turn, but not after player X. If I include the code after player X, I am unable to create a new game (which means I can't update a game). Here is the code, which I currently have commented out for player X: 

``` js
const onClick = function(){
  let tileClicked = $(this).attr('data-id');
  if (turns % 2 === 0) {
    player = 'x';
    this.innerHTML = '<img src = http://i.imgur.com/XvpQ5p5s.png>';
    gameBoard.insert(tileClicked, "X");
    turns++;
    // api.updateGame(tileClicked, player, over);
      // .done(ui.updateGameSuccess)
      // .fail(ui.failure);
    winCondition(gameBoard);
  }
  else {
    player = 'o';
    this.innerHTML = '<img src = http://i.imgur.com/bPWrglqs.png>';
    gameBoard.insert(tileClicked, "O");
    turns++;
    api.updateGame(tileClicked, player, over)
      .done(ui.updateGameSuccess)
      .fail(ui.failure);
    winCondition(gameBoard);
  }
};
```

Is there a way to place this so it targets both? Below, also, is my onNewGame code:

``` js
const onNewGame = function(event){
  event.preventDefault();
  clearBoard();
  let data = {};
    api.newGame(data)
    .done(ui.newGameSuccess)
    .fail(ui.failure);
};
```

**Comment by jrhorn424** [comment]
Can we see your `api.updateGame` definition?

**Comment by jrhorn424** [comment]
Move duplicated lines out of the `if` block. Instead of using `this.innerHTML`, use `$(this).html`.

What's a duplicated line? Well, you're going to fire an API request no matter what, so you should move that outside of the control flow and have it fire regardless of whose turn it is. You can set the player in the control flow, but you don't have to fire the API call there.

**Comment by knoddin** [comment]
``` js
const updateGame = (tileClicked, player, over) => {
  console.log(tileClicked, player, over);
  return $.ajax({
    url: app.host + '/games/' + app.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data:
    {
      "game": {
        "cell": {
          "index": tileClicked,
          "value": player
        },
        "over": over
      }
  }}
);};
```

**Comment by jrhorn424** [comment]
@knoddin Can you provide the error you're getting in the browser? In other words, how do you know it isn't working?

**Comment by knoddin** [comment]
I only know it isn't happening because I do not see my console.log("I am in update game") upon a successful patch. I am going to try to make that chunk of code more DRY and implement your suggestions above.

**Comment by knoddin** [comment]
I have rearranged my code and got rid of duplicate lines. As it is, if I leave the line

``` js
api.updateGame(tileClicked, player, over);
```

where it is, my new game button does not work and I cannot clear the board. If I remove it, I can create a new game. Here is that section in its entirety:

``` js
const onClick = function(){
  let tileClicked = $(this).attr('data-id');
  if (turns % 2 === 0) {
      player = 'X';
    }
    else {
      player = 'O';
    }
    $(this).html(player);
    gameBoard.insert(tileClicked, player);
    turns++;
    winCondition(gameBoard);
    // api.updateGame(tileClicked, player, over);
};
```

**Comment by jrhorn424** [comment]
Where is the `over` variable defined?

**Comment by knoddin** [comment]
It's defined globally and updated in winCondition(). If I console.log(tileClicked, player, over) in onClick, over does have a value.

**Comment by jrhorn424** [comment]
> I have rearranged my code and got rid of duplicate lines. As it is, if I leave the line
> where it is, my new game button does not work and I cannot clear the board. If I remove it, I can create a new game.

What is the error message you receive when the button fails to work? Can you confirm that the API call does indeed fire? Can you confirm that winCondition still fires?

**Comment by knoddin** [comment]
When refreshing a page, the console error says:
"Uncaught TypeError: Cannot read property 'id' of undefined" And this points to the api file where updateGame.js is located. 

I understand that the error is saying that it cannot read or find where the id is stored/location, but is that because I am not logged in and have not created a new game? The api code, as I have it, previously worked and I made a successful patch for player O (it displayed PATCH in console with a 200 code) when my code was arranged differently (prior to getting rid of duplicate lines). So I haven't changed the PATCH code at all - just moved it.

Currently, leaving it where it is (uncommented out) prevents newGame from working.

**Comment by knoddin** [comment]
Problem solved! I was calling my onClick function here:

``` js
$(document).ready(function () {
  authEvents.addHandlers();
  handlers.createBoard();
  handlers.addGameHandlers();
});
```

Which is not good since the onClick function is not an event handler! That has since been removed and the PATCH works. Thanks for your help, Jeff!

**Comment by jrhorn424** [comment]
Small correction: `onClick` is a click handler, but you don't invoke handlers directly. You attach them to the DOM with jQuery.

Thanks for posting your solution!
