### ISSUE TITLE
Get update game returning a 404 not found error. 

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/game-project#284]
Error message

``` .html
Object {readyState: 4, responseText: "{"message":"Not Found"}", responseJSON: Object, status: 404, statusText: "Not Found"}
abort
:
( statusText )
always
:
()
complete
:
()
done
:
()
error
:
()
fail
:
()
getAllResponseHeaders
:
()
getResponseHeader
:
( key )
overrideMimeType
:
( type )
pipe
:
( /* fnDone, fnFail, fnProgress */ )
progress
:
()
promise
:
( obj )
readyState
:
4
responseJSON
:
Object
responseText
:
"{"message":"Not Found"}"
setRequestHeader
:
( name, value )
state
:
()
status
:
404
statusCode
:
( map )
statusText
:
"Not Found"
success
:
()
then
:
( /* fnDone, fnFail, fnProgress */ )
__proto__
:
Object
```

ui code

``` .js
const onGetGame = function (event) {
  event.preventDefault();
  if (!app.user) {
    $('#game-message').text('You have to be logged in to get game stats');
    return;
  }
  api.getGame()
    .done(newGameSuccess)
    .fail(failure);
};
```

api code

``` .js
const getGame = () => {
  let token = app.user.token;
  return $.ajax({
    url: app.host + '/games/:id',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + token,
    }
  });
};
```

**Comment by rosmith76** [comment]
I am including my updateWins code, because I think it might be the root of the problem since I am getting a not found error.

api code 

``` .js
const updateWins = (data) => {
  return $.ajax({
    url: app.host + '/games/' + app.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};
```

out of ui from my on cell click function

``` .js
      let index = $(event.target).data('index');
      let player = logic.getCurrentPlayer();
      api.updateWins({
        "game": {
          "cell": {
            "index": index,
            "value": player
          },
          "over": over
        }
      });
    }
  }
```

**Comment by jrhorn424** [comment]
I think we might be looking at two different issues here. The minor issue, or at least the one not concerning your issue title, is with the GET request:

``` js
const getGame = () => {
  let token = app.user.token;
  return $.ajax({
    url: app.host + '/games/:id', // :eyes: here... can you find the problem?
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + token,
    }
  });
};
```

Your title suggests there's an issue with finding the game:

> Patch update game returning a 404 not found error.

It is unclear to me which AJAX request is causing this. Try fixing the `GET` request and see if the error goes away. If it doesn't, it's because `app.game.id` isn't correct in this code:

``` js
const updateWins = (data) => {
  return $.ajax({
    url: app.host + '/games/' + app.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};
```

**Comment by rosmith76** [comment]
My is a GET, not a PATCH. I edited the issue title Not sure why I have patch on the brain. I will look at the link and the documentation to see where I went wrong.

**Comment by rosmith76** [comment]
thanks @jrhorn424 I am no longer getting an error message. 
I have tried a few different options to display the game stats. 

api 

``` /js
const getGameSuccess = (data) => {
  app.game = data.game;
  $('#game-message').text('Your game stats are' );
  // console.log(app.game);
};

const onGetGame = function (event) {
  event.preventDefault();
  if (!app.user) {
    $('#game-message').text('You have to be logged in to get game stats');
    return;
  }
  api.getGame()
    .done(getGameSuccess)
    .fail(failure);
};
```

api

``` .js
const getGame = () => {
  return $.ajax({
    url: app.host + '/games',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    }
  });
};
```

assuming I need to return data here?

**Comment by payne-chris-r** [comment]
Is this resolved Robbe? If you're having an issue with your GET request that function is likely the issue... Have you tried running a curl script to see how it should be formatted?

**Comment by jrhorn424** [comment]
You don't need to return data there. The done method inside your onGetGame function registers a handler named onGetGameSuccess. That handler fires when the server returns 2xx with data. Inside that function is where you will find data to attach to the DOM.

**Comment by rosmith76** [comment]
I am no longer getting an error message when I hit get game button. I am trying to console log the output, and it undefinded? I am not sure where to go from here. 

``` .js
const getGameSuccess = (data) => {
  app.game = data.game;
  $('#game-message').text('Your game stats are' + (app.game));
  console.log(app.game);
};
```

**Comment by payne-chris-r** [comment]
I assume 'Your game stats are `undefined`' as well... If "data" is undefined that means you (or whatever function is calling it) isn't passing anything as an argument on invocation. I'm assuming this is a GET to `games/:id` and you're expecting a game back? Try a curl request or throw a log in further up the chain to see how your request is looking...

**Comment by rosmith76** [comment]
This action is an attempt to satisfy this requirement is the game. "Visually display the results of retrieving game statistics, such as total games won by a user. (READ)" 
The "Your game stats are undefined" is returning in the browser. Other than that I am not getting any error messages.

**Comment by payne-chris-r** [comment]
Meaning your browser is rendering those words? "Your game stats are undefined" ?? If that's the case it's because you're not handling the data you get back correctly, or you're trying to show something that is `undefined` in the eyes of javascript...

**Comment by rosmith76** [comment]
The browser actually displays the words "Your game stats are undefined" I am trying to show the game stats there.

**Comment by payne-chris-r** [comment]
Ok, why might it say that?

**Comment by rosmith76** [comment]
Because app.game is undefined. I am not sure how to fix this.

**Comment by jrhorn424** [comment]
``` js
const getGameSuccess = (data) => { // 👀 what the heck is data? maybe we can inspect it somehow?
  app.game = data.game;
  $('#game-message').text('Your game stats are' + (app.game));
  console.log(app.game);
};
```

**Comment by rosmith76** [comment]
I got it figured out.
