### ISSUE TITLE
I can't get the gameboard to clear without refreshing the page.

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/game-project#286]
When I hit start new game I get a empty array with a new game ID, but I can't get the board to clear. JS functions below

``` .js
const clearGameboard = function() {
  logic.board = ['','','','','','','','',''];
  $('col-xs-4').trigger('reset');
};
```

I call this function in new game success function

``` .js
const newGameSuccess = (data) => {
  console.log(data);
  app.game = data.game;
  console.log(app.game);
  clearGameboard();
  gameStarts();
};
```

**Comment by payne-chris-r** [comment]
What are you expecting `$('col-xs-4').trigger('reset');` to do exactly? I'm not too familiar with `trigger`, but I believe the code will try to run the 'reset' handler you've set up. Do you have a reset handler set up on `$('col-xs-4')`?

**Comment by rosmith76** [comment]
I was expecting to be able to reset the game squares with that function. I was trying to set up a reset handler on col-xs-4

**Comment by payne-chris-r** [comment]
I've never used `.trigger` before, but after looking at the documentation it looks like it "triggers" a specific handler. So unless you've set up a `.on('reset', function( ){ // })` somewhere, I don't think this is doing what you intend it to...

**Comment by rosmith76** [comment]
Can we set up a 1 on 1 to discuss later?

**Comment by payne-chris-r** [comment]
try looking at the jquery methods `.html` or `.text` and see if those might be what you're looking for.

**Comment by jrhorn424** [comment]
Chris is trying to say that in order for 

``` js
const clearGameboard = function() {
  logic.board = ['','','','','','','','',''];
  $('col-xs-4').trigger('reset'); // 👀 this line
};
```

to work, you would have had to do something like `.on('reset', function( ){ // })` somewhere (as opposed to a simple `on.('click', cb)`. This tells you jQuery can handle custom events. This seems like an approach that might cause confusion down the line.

Instead of `$('col-xs-4').trigger('reset'); // 👀 this line`, can you try using `.html` or `.text` to reset the DOM manually?

**Comment by rosmith76** [comment]
I was able to use a for loop to reset it.
