### ISSUE TITLE
PATCH - Update game does not work

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/game-project#287]
While I have read several closed issues, I cannot find what I am looking for. I would like to call my api.updateGame function after each player's turn. Here is the code:

events.js

``` .js
const onClickTile = function(event) {
    event.preventDefault();
    // let tile = $(this).attr('data-id');
    let tile = $(event.target);
    let id = tile.data('id');

    if ($(this).html() === '') {
      if (turnTracker % 2 === 0) {
        marker = "X";
        $(this).html('X');
        boardArray[id] = 'X';
        turnTracker++; //will become odd
            api.updateGame(id, marker, over1);
        checkForWin ();
        checkForDraw ();
        }
      else {
        marker = "O";
        $(this).html ('O');
        boardArray[id] = 'O';
        turnTracker++;
            api.updateGame(id, marker, over1);
            checkForWin ();
        checkForDraw ();
        }
        }
        else {
          showMessage('Not empty!');
        }
};
```

api.js

``` .js
const updateGame = (index, value, over1) => {
  return $.ajax({
    url: app.host + '/games/' + app.user.token,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: {
      'game': {
        'cell': {
          'index': index,
          'value': value,
        },
        'over': over1,
      }
    }
  });
};
```

ui.js

``` .js
const updateGameSuccess = (data) => {
  app.game = data.game;
  console.log(app.game);
};
```

The error message is:
jquery.js:9175 PATCH https://aqueous-atoll-85096.herokuapp.com/games/296325c30e431554a17d1c8e14c7a384 **404 (Not Found)**send @ jquery.js:9175ajax @ jquery.js:8656updateGame @ api.js:40onClickTile @ events.js:143dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-09-25 13:21:32.601 jquery.js:9175 XHR finished loading: PATCH "https://aqueous-atoll-85096.herokuapp.com/games/296325c30e431554a17d1c8e14c7a384".send @ jquery.js:9175ajax @ jquery.js:8656updateGame @ api.js:40onClickTile @ events.js:143dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549

I am calling this wrong but have tried many things and still nothing. Could it be my new game functions? With the code above, i can sign in, play, and press 'new game' clears the board. But after that I am not able to play anymore. I do get a game id each time I press 'new game'

Thanks for your guidance.

**Comment by payne-chris-r** [comment]
Try building a curl request and matching your ajax request up with that? Try hard coding WHICH game you're going to update. If the url is working for everything else except this function, see if you can deduce from the other functions that are working what you're doing differently in this one.

**Comment by viohlet** [comment]
Solution: I was calling my user id instead of my game id in my updateGame function in api. Changed it and it worked.
