### ISSUE TITLE
Clearboard function only partially working

### ISSUE THREAD

**Issue by BMorse09** [ga-wdi-boston/game-project#288]
I have a clearboard function that clears the board and display message after an outcome. However, I am unable to re-populate the board without refeshing the page and logging in again. 

**Here's my JS code for switching players and populating the gameboard:**

```
let gameBoardArray = ['', '', '', '', '', '', '', '', ''];
let gameOver = false;


  const changePlayer = () => {
      if (app.player === 'x') {
      app.player = 'o';
    }
      else if (app.player === 'o') {
      app.player = 'x';
    }
};

  const onNewGame = function (event) {
      event.preventDefault();
       $('.col-xs-4').html('');
       $("#gameOver").html('');
       let data = {};
       api.newGame(data)
      .done(ui.onNewGameSuccess)
      .fail(ui.onError);


  };

  const onPlaceX = function (event) {
        if(!gameOver){
        let id=this.id;
          event.preventDefault();
        if (app.player === 'x' && $(this).text() === ''){
            app.player = 'o';
        let cellclicked = event.target;

        if (gameBoardArray[id] === '') {
            gameBoardArray[id] = 'o';
              $(cellclicked).html('O');
            gameOver = win(gameBoardArray, id);
        if  (gameOver === true) {
              $("#gameOver").html('player O wins!');

        }
          } else {
        }

      } else if (app.player === 'o' && $(this).text() === ''){
                 app.player = 'x';
        let cellclicked = event.target;

        if (gameBoardArray[id] === '') {
            gameBoardArray[id] = 'x';
              $(cellclicked).html('X');
            gameOver = win(gameBoardArray, id);
        if (gameOver === true) {
              $("#gameOver").html('player X wins!');
              $("#new-game-button").html()

          }
        }
    }
  }
```

**My clearBoard function in events.js:**

```
const clearBoard = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  ui.clearBoard();

};
```

**My const addHandlers:**

```
$('#clear-board').on('submit', clearBoard);
```

**My new game button html:** 

```
<button type="button" id="new-game-button" class="btn btn-default">new game</button>

```

**In game/ui.js:**

```
const clearBoard = (data) => {
  app.game = data.game;
};

```

When the board is cleared and I hit my new game button, nothing happens. In my inspector, there are no error messages, but a POST request is logged every time I click the button, so something is in fact firing.

**Comment by jrhorn424** [comment]
I don't see where you're registering `onNewGame` as a handler. That's what's firing if my guess is correct. You've got a lot of disparate functions, and I don't know where they are called or registered.

Can you describe, in a bulleted, numbered list, exactly what should happen when you click the button? You should have a few different concerns here: the game board in the DOM, the game board in memory, and interacting with the API. You may also have other concerns, such as a resetting a turn counter, or whose turn it is.

**Comment by payne-chris-r** [comment]
Please close this issue or reformat it into a more specific one.
