### ISSUE TITLE
AJAX call to update game board returning 400 error

### ISSUE THREAD

**Issue by bullhead242** [ga-wdi-boston/game-project#289]
To assign value to the cells in the `app.game.cells` array, I have created the JS function `updateBoard` which contains an AJAX request. The code for this function is as follows: 

```
const updateBoard = () => {
  let gameId = app.game.id;
  let index = parseInt(event.target.dataset.index);
  let value = eventsGame.player;
  return $.ajax({
    url: app.host + '/games/' + gameId,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    data: {
      "game": {
        "cells": {
          "index": app.game.cells[index],
          "value": value,
          }
        }
      }
    }
  });
};
```

The local variables `gameId` `index` and `value` all return the expected values, which are the ID of the game being played currently, the index of the  game cell which has been clicked, and the value being added to that cell in the array which is the player whose turn it is currently. The `data` section of the function is literally copied from the API, and most of the AJAX section is pulling from it's neighboring functions with the exception of the URL and the variables assigned to handle the changing of address, such as `gameId`. The only linter error showing up is relating to a debugger, which is removed from the above code, I've shown it to a few people to get their thoughts and have stalled on this part. 

Any help would be appreciated in perpetuity throughout the universe. Thank yo.

**Comment by bullhead242** [comment]
it was a comma. A comma.

**Comment by jrhorn424** [comment]
To my eyes, the comma wasn't the problem.

``` diff
 return $.ajax({
    url: app.host + '/games/' + gameId,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
+   },
    data: {
      "game": {
        "cells": {
          "index": app.game.cells[index],
          "value": value,
          }
        }
      }
    }
```

**Comment by jrhorn424** [comment]
Glad you got it working though!

**Comment by bullhead242** [comment]
To be a bit more specific, the initial problem was because I had the rest
of the call nested inside of Faith, and moving the brace broke the code...
until I added the comma.

Another thing or two to debug and I'll be home free.
