### ISSUE TITLE
[Node] module.exports

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/game-project#29]
Not quite understanding why this isn't woking. ("it would be nice to have all of them export")

Error from browser : 

> jquery.js:13Uncaught TypeError: gameFunctions.winnerHorz is not a function

<img width="1680" alt="screen shot 2016-02-04 at 8 55 02 am" src="https://cloud.githubusercontent.com/assets/12851296/12816910/1b9cb536-cb1d-11e5-80f4-0cb9114f8d05.png">

i feel like module.exports should  look some thing like 
`module.exports = {
function-nickname? :  'function-name';
};`

**Comment by gaand** [comment]
Code snippets are generally superior to images.

To export all of the function you just need to list the constants name in an object literal assigned to `module.exports`.

**Comment by edesilets** [comment]
How do I export all without listing the constants name in the object literal? looks like `True` just doesn't work.

I am in debugging thats why i would like to know how to export all of them at once with minimal typing.

**Comment by gaand** [comment]
You have to list what you want exported in an object literal assigned to module,exports, e.g. 

``` js
module.exports = {
  exportOne,
  exportTwo,
};
```

**Comment by edesilets** [comment]
do i need to now require that file where i want to use that function or did web pack take care of that for me?

I have 
`
module.exports = {
 getPieceAt,
 setSquare,
 gameBoardReset,
 checkWinner,
 gameBoard,
};`

and my function that i am calling is undefined.

**Comment by jrhorn424** [comment]
Webpack makes it possible to require that file. You still have to require it where you want to use it's exported functions.

**Comment by erdesi90562** [comment]
I am not having any luck.
 This is at the top of my jQuery.js . `let gameFunctions = require('./myJavaScript'); game gameFunctions.winnerHorz('x');`

Bottom of the myJavaScript.js file.. 

`module.exports = {
 getPieceAt,
 setSquare,
 gameBoardReset,
 checkWinner,
 gameBoard,
};
`

**Comment by gaand** [comment]
The code you posted appears to have a syntax error.

The trailing `game`,

**Comment by edesilets** [comment]
You guys are great. I was calling out something that did not exist. @gaand  @jrhorn424
