### ISSUE TITLE
Migrating old template files to new properly named repo

### ISSUE THREAD

**Issue by Naki21** [ga-wdi-boston/game-project#291]
I would like to merge my template onto  a new repo with a proper name. Help me!

**Comment by raq929** [comment]
So, what you want to do is take files from an existing repo and copy them into your project repo.

If you do yet have a project repo:
Change to the directory you want, and use
`cp -a <path to of repo you want to copy> <name of new directory>`
You will have to set the upstream to a repo you create on github.
https://help.github.com/articles/changing-a-remote-s-url/

If you already have a project repo (with commits):

``` sh
git remote add auth <url of auth repo>
git fetch auth
```

If you want to copy all the files:
`git checkout auth/<branch name> '*'`

If you only want some of them: 
`git diff auth/<branch name> --name-status`
will give you a list of files.
`git checkout auth/<branch name> <name of file>`

**Comment by raq929** [comment]
If you feel like this issue has been fully addressed, please close it. If not, please ask questions!

**Comment by Naki21** [comment]
I have the branch in my new repo but how to i merge it to the master so I can work off of that one?

**Comment by raq929** [comment]
So, I think you mean you've added the remote? Did you checkout the files you want?
If yes, do a `git status` and you'll see a list of the files you added.
You can then commit them and merge your branch into master.

**Comment by Naki21** [comment]
it says the working tree is clean  and  HEAD detached at auth/training. It wont merge (unrelated histories)

**Comment by raq929** [comment]
Yeah, you checked out `auth/training` without a file name, which puts you in detached HEAD state. You should checkout your branch again, and then do `git checkout auth/training <name of file>` or `git checkout auth/training '*'` if you want everything.

**Comment by raq929** [comment]
You probably got a message like this, and you can do what it tells you to do: 

``` sh
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

```

**Comment by Naki21** [comment]
Solved the problem by burning down my nearly empty repo locally and on git hub. Followed the directions above. Created new local dir and copied the files locally. I then changed the origin of this new file to a new repo on git hub. Pushed the local files to git hub. Pushed the training branch. merged the training branch to master. Deleted training branch on git hub and locally. Crisis averted
