### ISSUE TITLE
HTML/CSS - How to craft a modal that pops up before showing the game board?

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/game-project#292]
I'm honestly open to Jason giving me a Google result that points me in the right direction.

I cannot for the life of me find out what I need to do to get a modal that shows up upon loading the page that you then sign in to in order to access the game. Is this possible using HTML/CSS/JS alone? I'd prefer not to have a navbar with a sign in function but rather a separate login in pop-up that forces user to register before allowing them to access the page. I don't want to continue working on the navbar if I can discard it in favor of a modal.

**Comment by raq929** [comment]
So, you have a function `$(document).ready` which runs things as soon as the document is up. I would simply use the bootstrap function to show the modal as the first thing in the `$(document).ready` function.

**Comment by BenGitsCode** [comment]
also, only because you asked http://bit.ly/2eNFm59

**Comment by kiraamaa** [comment]
LOL I didn't think of that, thank you!

**Comment by raq929** [comment]
Please close the issue if it's been resolved! :)

**Comment by gaand** [comment]
@kiraamaa With a solution, please.

Things to think about. will you still have change password, sign out?  Where will they go if you don't have a nav bar?

Also, won't you're modal on page load require the ability to sign up or in?

**Comment by kiraamaa** [comment]
You're right; it unnecessarily complicates things. I'll stick with the Bootstrap navbar and regular forms.
