### ISSUE TITLE
js w/ jquery -- linter errors on require and $

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/game-project#293]
errors read: "require is not defined" and "$ is not defined"

tried copying in .jshintrc etc from browser template, and adding

```html
<script src="vendor.bundle.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
```
do I need to do something else to import jquery?

**Comment by gaand** [comment]
Did you start with `browser-template` or `api-token-auth`?

**Comment by ioncrash** [comment]
with browser-template. Should it have been api-token-auth?

**Comment by gaand** [comment]
My question may have been poorly phrased. I wanted to check that you started with one of them, since you seem to be missing files included in both. Starting with either should be fine.

**Comment by gaand** [comment]
This may be a problem of copying. Hidden files, ones starting with `.`, aren't copied by default using `cp`.

**Comment by raq929** [comment]
Is jQuery actually not working when you run `grunt serve`, or is it just the linter that is complaining about these things?

**Comment by ioncrash** [comment]
just the linter. The code is working fine when I load it in the browser

**Comment by ioncrash** [comment]
is there a better way to copy?

**Comment by raq929** [comment]
`cp -a` will copy hidden files as well. But you said you did copy the `.jshintrc`. I would make sure you also copied the `.jshintignore`, `.editorconfig`, and `.remarkrc`.

**Comment by ioncrash** [comment]
I believe I did, yes. But I actually just got it working by starting over from the api-token-auth fork and copying all my code over from the old directory. Thank you!
