### ISSUE TITLE
Linter SCSS - Lint Process Execution Timeout

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/game-project#294]
Discussed this issue with Antony, he was giving me assistance but we ran out of time. Error had to do with the copying of the api-token-auth directory into another directory and the associated repositories.

**Comment by raq929** [comment]
Possibly related to #294. I assume you did copy the `.jshintignore`?

**Comment by raq929** [comment]
I mean #293

**Comment by gaand** [comment]
You can create a file in the root of your repository using this info and  the problem should go away.

https://github.com/ga-wdi-boston/browser-template/blob/f23f934244ee9f0a60086f36aedf14fd0dcae6e2/.scss-lint.yml

**Comment by raq929** [comment]
@callmelife If this has been resolved, please say what you did to resolve it (in your own words) and close the issue. Thanks!

**Comment by matthewgsommers** [comment]
Sorry about the late response, didn't see this message. The issue has not been resolved, I'm still getting the error. I added the file (.scss-lint.yml) to the root directory, as Antony instructed, but the error  is still happening. Same error: "[Linter-SCSS-Lint) Process execution time out".

**Comment by gaand** [comment]
This appears to be a resources issue.  4G memory, a mechanical hard drive, and a variety of open processes cause `scss-lint` to run for ? 4 seconds.  This exceeds atom's expectations.
