### ISSUE TITLE
What is the url for the back end api?

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/game-project#295]
How do we reach the api itself? Thank you!

**Comment by raq929** [comment]
What do you mean by 'reach the api'?

**Comment by raq929** [comment]
I think what you're looking for is in here: https://github.com/ga-wdi-boston/game-project/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20api%20url

**Comment by ioncrash** [comment]
ah, so it's 

https://aqueous-atoll-85096.herokuapp.com/ 

?

Ok thanks
