### ISSUE TITLE
Cannot get Boxes to be aligned correctly in my html and css

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/game-project#296]
```html 
<div class="container">

        <div class="row">
          <div class="col-xs-6 col-md-4 box"></div>
          <div class="col-xs-6 col-md-4 box">.col-xs-6 .col-md-4</div>
          <div class="col-xs-6 col-md-4 box">.col-xs-6 .col-md-4</div>
        </div>

        <div class="row">
          <div class="col-xs-6 col-md-4 box"></div>
          <div class="col-xs-6 col-md-4 box">.col-xs-6 .col-md-4</div>
          <div class="col-xs-6 col-md-4 box">.col-xs-6 .col-md-4</div>
        </div>

        <div class="row">
          <div class="col-xs-6 col-md-4 box"></div>
          <div class="col-xs-6 col-md-4 box">.col-xs-6 .col-md-4</div>
          <div class="col-xs-6 col-md-4 box">.col-xs-6 .col-md-4</div>
        </div>

          </div>
```

```css
.row {
  border-style: solid;
  width: 250px;
  height: 50px;
}
```

**Comment by BenGitsCode** [comment]
Please review [this](https://github.com/ga-wdi-boston/project-issue-tracker-guide#how-to-use-the-issue-tracker) and revise your issue.  I'm not sure what your question is here.

**Comment by Sphilippe7** [comment]
Sorry, My question is how do I get the boxes, using bootstrap, to show a proper 3x3 box for my tic tac toe. I know it is something I'm doing wrong and I tried a lot of different ways to get it. The code you see up top is my HTML and the code on the bottom is what I define it with in CSS.

**Comment by BenGitsCode** [comment]
So you have three rows here, and you want to keep those, but want to split each of those rows, into three more columns each, right?

I suggest opening up just your relevant html and css in a codepen like [this](http://codepen.io/benjamski/pen/QKeQGd) and experimenting with how you would split each of those rows into three columns instead of one long row. 

Does that make it easier to work on?

**Comment by Sphilippe7** [comment]
still not getting it to work.

**Comment by RealWeeks** [comment]
Well @Sphilippe7 on some screen sizes you will already have a 3x3 grid, on some others you won't.  You should fix that ;)

**Comment by RealWeeks** [comment]
@Sphilippe7 What have you tried to far?

**Comment by Sphilippe7** [comment]
I've tried changing the numbers and I've tried looking at the media queries. I'm stuck. @J-Weeks

**Comment by RealWeeks** [comment]
Post what you changed, we'll work through this.

**Comment by Sphilippe7** [comment]
This is what I have now

```
  <div class="container">

        <div class="row">
          <div class="col-xs-4 col-md-4 box">Box</div>
          <div class="col-xs-4 col-md-4 box">Box</div>
          <div class="col-xs-4 col-md-4 box">Box</div>
        </div>

        <div class="row">
          <div class="col-xs-4 col-md-4 box">2</div>
          <div class="col-xs-4 col-md-4 box">.col-xs-6 .col-md-4</div>
          <div class="col-xs-4 col-md-4 box">.col-xs-6 .col-md-4</div>
        </div>

        <div class="row">
          <div class="col-xs-4 col-md-4 box">3</div>
          <div class="col-xs-4 col-md-4 box">.col-4s-6 .col-md-4</div>
          <div class="col-xs-4 col-md-4 box">.col-xs-6 .col-md-4</div>
        </div>
      </div>
```

**Comment by RealWeeks** [comment]
That does make a 3x3 grid.  The issue lies in the CSS you added.

**Comment by RealWeeks** [comment]
``` css
.row {
  border-style: solid;
  width: 250px;
  height: 50px;
}
```

Here your expanding the width of the rows to a certain amount.  Do you want to specify the height and or width for each row or something else in your tic tac toe board?

**Comment by Sphilippe7** [comment]
it does not show a grid on my page, it shows them all stacked on top of each other vertically @J-Weeks

**Comment by RealWeeks** [comment]
See my last comment, your html is correct, your CSS is incorrect.  Answer this question: `Do you want to specify the height and or width for each row or something else in your tic tac toe board?`

**Comment by Sphilippe7** [comment]
I just tried replacing the CSS you sent and it still is not a 3x3 grid. I just want the grid to appear and then I will specify the height and width. As of now it is only three rows vertically.

**Comment by raq929** [comment]
I'll come take a look.

**Comment by Sphilippe7** [comment]
The problem was for some reason my vendor bundle at the top of my html file was deleted. After Rachel and I added it, all my bootstraps worked fine. Then I added classes to make the boxes. Thank you everyone.
