### ISSUE TITLE
js/ajax -- api returning same object passed to it

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/game-project#299]
when signing up to api, getting same object back that I'm passing to it. Here's what my debugger is showing right after I pass a request to the api:

```
const onSignUp = function(e){
  e.preventDefault();
  let email = $('#sign-up-email').val();
  let password = $('#sign-up-password').val();
  let confirmPassword = $('#confirm-password').val();
  let user = api.signUp(email, password, confirmPassword);
  debugger;
  $('#sign-up-modal').modal('hide');
};
```

here's my code for requesting from the api:

```js
const signUp = function(email, password, confirmPassword) {
    return $.ajax({
      url: app.host + '/sign-up',
      method: 'POST',
      data: {
        "credentials": {
          "email": email,
          "password": password
      }
    }
  });
};
```

**Comment by RealWeeks** [comment]
Suggestion, construct your data object outside of your ajax function

**Comment by RealWeeks** [comment]
also at the debugger what are the values of email, password, confirm password?

**Comment by RealWeeks** [comment]
also... TAKE A CLOSE LOOK AT `user` what are you trying to do there?

**Comment by ioncrash** [comment]
sorry, didn't see that the values weren't included. Debugger shows:

email = "bob@dave.com"
password = "bob"
confirmPassword = "bob"
user = Object {readyState: 1}, email = "bob@dave.com", password = "bob

user is just intended to hold the object that the ajax query returns to me so that I can look at it in the debugger

**Comment by RealWeeks** [comment]
`let user = api.signUp(email, password, confirmPassword);` is assignment

**Comment by RealWeeks** [comment]
Change that, then build your data object outside of your ajax function.

**Comment by ioncrash** [comment]
got it. Needed to use 

``` js
api.signIn(data)
    .then(ui.signInSuccess)
    .catch(ui.failure);
```

rather than returning the data to a variable and then updating
