### ISSUE TITLE
[JS] - Updating the board following a remote player's move

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/game-project#30]
What's the best way to refresh the board once a remote player has updated it? Waiting for a local user's click will mean the local player is always one move behind, and refreshing the page seems to defeat the purpose of using ajax.

**Comment by gaand** [comment]
Have a look at https://github.com/ga-wdi-boston/game-project-api#watch and then see what questions you have.

**Comment by gaand** [comment]
@apalmer0 Do you have any questions about using watch?

**Comment by apalmer0** [comment]
I understand what it's purpose is, I'm trying to figure out how to implement it now. What is a wrapper, and how do I use on in my app? Can I just add the code supplied into my app?

**Comment by gaand** [comment]
The example code should mostly work out of the box.  You need to have successfully logged in before you call resourceWatcher (so you can pass a valid token).  The change event runs when a player updates the watched game.

**Comment by apalmer0** [comment]
Awesome, thank you - going to try to add that now and see what happens!

**Comment by RealWeeks** [comment]
@apalmer0 was this issue resolved? If not please comment further and we'll gladly help, if so please close.
