### ISSUE TITLE
deployment onto github removes bootstrap styling 

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#301]
In my project repo, when I run grunt serve in the terminal, it displays the navbar like what was in class yesterday for bootstrap. However upon following the instructions for the deployment guide : https://github.com/ga-wdi-boston/gh-pages-deployment-guide I do not see in the github hosting what I see when I run grunt serve locally. The styling is messed up and going horizontal. In the instructions , it says to: In your .gitignore file, comment out the lines *bundle.js and vendor.js so git no longer ignores those files e.g., # *bundle.js. Alternatively you can remove those lines altogether.

I did this, and noticed when i look at the console, the browser sees that these files are missing. I tried removing them completed instead of commenting them out, to see if the comments were incorrect, but still am seeing the same error in the console. 
Here is the project so far deployed https://jbuzzanco.github.io/tic-tac-toe-temp/
I just wanted to deploy it early, as was suggested, even though I know I am not very far along in the project.

Also I feel like I do not know what to do at all as far as JavaScript goes. Specifically looking at the API I've looked at the https://github.com/ga-wdi-boston/library-api-guide for awhile now to see and review to put this in my game, but just don't really know how to start and feel like I am falling behind the others.

**Comment by raq929** [comment]
Please open a separate issue for javascript.

**Comment by raq929** [comment]
Did you do this step in the gh-deployment-guide repo?

In your .gitignore file, comment out the lines *bundle.js and vendor.js so git no longer ignores those files e.g., # *bundle.js. Alternatively you can remove those lines altogether.

This tells Git to no longer ignore those files so Git can track them.

**Comment by raq929** [comment]
Did you make a commit after commenting out the lines in your .gitignore?

**Comment by jbuzzanco** [comment]
Yes I did comment those lines out in .gitignore. Also tried removing them altogether and still got errors. I did add and commit after commenting out the lines in .gitignore.

**Comment by raq929** [comment]
I'll come take a look.

**Comment by jbuzzanco** [comment]
resolved by adding commented out files in .gitignore & committing. Pushed to the branch and refreshed the page. SHowing up now as locally.
