### ISSUE TITLE
Don't know how to start JS files

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#302]
I feel like I do not know what to do at all as far as JavaScript goes. Specifically looking at the API I've looked at the https://github.com/ga-wdi-boston/library-api-guide for awhile now to see and review to put this in my game, but just don't really know how to start and feel like I am falling behind the others.

**Comment by raq929** [comment]
Did you write user stories?

**Comment by jbuzzanco** [comment]
In pseudo code like in the scope study I wrote user stories if that's what you mean.

**Comment by raq929** [comment]
I talked with Joel about this. He's going to start with the auth part of the project, which we did in class. Then he will start going through his user stories and writing acceptance criteria for them. Then he will choose one and begin working on completing the acceptance criteria.

**Comment by raq929** [comment]
User stories aren't psuedo code. They are plain English. Take a look at this article for some examples. https://www.mountaingoatsoftware.com/agile/user-stories

**Comment by jbuzzanco** [comment]
This is probably a dumb question, but I am looking at this https://github.com/ga-wdi-boston/api-token-auth and have been for a while. Is this what I am supposed to use? It's just that I don't really know how to start to implement this into my project. Partly confusing because my sign in/up/out info is in my nav of the HTML. I've been looking and comparing these files to mine for a while now and just feel like I am not getting anywhere..

**Comment by raq929** [comment]
So, we implemented all of the authentication stuff in the ajax lessons that we did with Jason. I would look at the last repo of that series and start from there.

**Comment by raq929** [comment]
Also, make sure you have user stories first. If you're doing auth, your first one might be "As a user, I want to create an account (sign up)." What do you need to do as a developer to make that possible? 
The answer to that question is your acceptance criteria for the user story. 
Once you have user stories and acceptance criteria, you can start working on your project one step at a time.

**Comment by jbuzzanco** [comment]
Ok, yes I have been working on sign up actually. The user story would be for sign up: I want to put in my email and password and confirm that password. I do have it--I think in a correct way--for the HTML. However, I just am having trouble linking it with the JavaScript based off looking at https://github.com/ga-wdi-boston/api-token-auth.

``` HTML
<form class="sign-up-form" id="sign-up">
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="sign-up-email" placeholder="Email" name="credentials[email]">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password Confirmation">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </form>
```

**Comment by neugierige** [comment]
Joel, this sounds like a separate issue...

**Comment by jbuzzanco** [comment]
now working on separate issue to for sign-up part
