### ISSUE TITLE
Local site is in a debugger loop

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/game-project#304]
Whenever I refresh my local site the debugger is thrown.
I can hit play and the site loads normally
there are no errors in console
this happened after I went through steps to add the sign-in part of API
Asked a peer who was unsure of cause

**Comment by neugierige** [comment]
if I'm understanding you correctly, it seems like you have `debugger` somewhere in your code. have you located where it is/those are?

**Comment by akradin** [comment]
There is no debugger in my code

**Comment by akradin** [comment]
The solution to this lies in inspector tools in Chrome.

If, when you refresh your page, a debugger pops up when there is none in your code, check the sources in dev tools and make sure none of the numbers on the left side are highlighted. If they are, click on the highlighted number and it will resolve the issue.
