### ISSUE TITLE
Accidentally merged my j-query branch with gh-pages

### ISSUE THREAD

**Issue by Bowers96** [ga-wdi-boston/game-project#305]
I accidentally merged my j-query branch with my gh-pages branch and then I went on to git reset --hard 75c31bb because this was what I wanted to unmerge ~/wdi/projects/tic-tac-toe (gh-pages)$ git reflog I got a response HEAD is now at 75c31bb Merge branch 'j-query' into gh-pages

**Comment by BenGitsCode** [comment]
Revise your post to include more information—I know you just mentioned this to me, but your issue needs to adhere to the structure outlined [here](https://github.com/ga-wdi-boston/project-issue-tracker-guide#how-to-use-the-issue-tracker)

**Comment by BenGitsCode** [comment]
@Bowers96 including the shell snippet was ok, you just weren't stating the issue.

**Comment by BenGitsCode** [comment]
@Bowers96 can you post your solution/resolution and close this issue.

**Comment by Bowers96** [comment]
Yes, sorry.

**Comment by Bowers96** [comment]
Merge ended up not being a conflict, deleted gh-pages branch and re did the process over again.
