### ISSUE TITLE
Deployed and Everything went to shit....missing script files and bootstrap broke HELP

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/game-project#306]
Somewhere in messing with gh-pages and master branch to deploy I murdered my site. I see my commits in my branches but I'm scared to touch anything else.

**Comment by RealWeeks** [comment]
Ok, let's break this down.  What do you mean murdered, be specific.  Where do you see your commits, again specific. It's gonna be fine. Nothings been deleted.

**Comment by raq929** [comment]
@akadane87? How's it going?

**Comment by akadane87** [comment]
Its cool guys! I'm off the floor and out of the fetal position. Boostrap is still broke but I'm back to a place where I can start troubleshooting myself. Thanks @BenGitsCode
