### ISSUE TITLE
can't create rails server from game-project-api

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#307]
I ran through all of the steps here multiple times and still cannot get my rails server running on game-project-api https://github.com/ga-wdi-boston/library-api-guide 
I did create the .env file and input the string from ```bundle exec rake secret```

This is the error in the rails server that I am getting.
```
Exiting
/Users/Joel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `initialize': Address already in use - bind(2) for "::1" port 4741 (Errno::EADDRINUSE)
```
I have asked peers and have been googling the issue and still cannot figure out why rails server won't run.
http://stackoverflow.com/questions/31039998/address-already-in-use-bind2-errnoeaddrinuse
http://stackoverflow.com/questions/38460373/rails-5-address-already-in-use-bind2-for-127-0-0-1-port-3000

**Comment by gaand** [comment]
You don't need to create the API. It's already deployed. If you look in the closed issues you should see the URL you need to use.

**Comment by raq929** [comment]
Please also see my response to #302.

**Comment by jbuzzanco** [comment]
I don't really understand the responses. But I am guessing supposed to use this https://github.com/ga-wdi-boston/game-project/issues/295  in some way. Don't really know how to implement this /why I would use the URL. I am guessing the URL is what the rails server is on or something like that.

**Comment by gaand** [comment]
That's correct.  The game project api is already deployed and ready to use.  You just need to have your client use it.

**Comment by jbuzzanco** [comment]
now to figure that out.
