### ISSUE TITLE
JS sign-up token auth not working

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#308]
I've been trying to figure out for a while now why my "Sign Up" button is not working with the API. I tried putting a debugger in the event, but it does not seem to be even reaching that point in my code.  I tried "grunt test" (don't know if that would even be helpful in this situation), and it returned 0 issues. 

In the console, when I click the sign-up button, I fill out the required fields, and I don't get the Object with new user information. I don't get an error message either. 
I am inputting the code from HTML and JS auth directory as reference. Any guidance would be greatly appreciated. 

EVENTS.JS CODE for SIGN-UP:
```js

const getFormFields = require(`../../../lib/get-form-fields`);

const api = require('./api');
const ui = require('./ui');

const onSignUp = function (event) {
  let data = getFormFields(this);
  debugger;
  event.preventDefault();
  api.signUp(data)
    .then(ui.success)
    .catch(ui.failure);
};
```
API.JS CODE for SIGN UP:
```js
const signUp = (data) =>
  $.ajax({
    url: config.host + '/sign-up',
    method: 'POST',
    data,
  });
```

HTML WITH SIGN UP BUTTON / MODAL:

```html
      <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                SIGN UP!
              </button>

  <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="sign-up">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="sign-up">Sign Up!</h4>
          </div>
          <div class="modal-body">
            <form id="sign-up">
              <fieldset>
              <div class="form-group">
                <label for="sign-up-email">Email address</label>
                <input name="credentials[email]" type="text" value="email" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input name="credentials[password]" type="password" value="exampleInputPassword1" placeholder="Password">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Confirm Password</label>
                <input name="credentials[password_confirmation]" type="password" value="exampleInputPassword1" placeholder="Confirm Password">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
          </div>

```

MESSAGE I GET IN CONSOLE (Not sure how to format that properly) 
abstract-xhr.js:132 XHR finished loading: GET "http://localhost:7165/sockjs-node/info?t=1478047747339".AbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21

**Comment by gaand** [comment]
Have you run `tidy` on your HTML?

**Comment by jdaly04** [comment]
I haven't run tidy specifically, but I have removed all linter errors and am still not getting an Object with new user info in it.

**Comment by gaand** [comment]
I took this

> I tried putting a debugger in the event, but it does not seem to be even reaching that point in my code.

to mean your onSignUp isn't firing.   

Invalid html can prevent event handlers from being attach properly.  That's why I asked about running `tidy` on `index.html`.  `tidy` validates your html.  

Please try executing

``` sh
tidy index.html
```

from the command line in the root of your repository and post the result.  Thanks.

**Comment by raq929** [comment]
Can you also post the code where you register the click handler?

**Comment by jdaly04** [comment]
Ran tidy and got a return of no errors. 
"~/wdi/projects/tic-tac-toe-project (api)$ tidy index.html
Info: Document content looks like HTML5
No warnings or errors were found."

``` js
const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp);
  $('#sign-in').on('submit', onSignIn);
  $('#change-password').on('submit', onChangePassword);
  $('#signOut').on('submit', onSignOut);
};
```

Is that what you meant, Rachel??

**Comment by raq929** [comment]
Yes! Everything here looks reasonable to me. Come see me this morning and we'll get it sorted.

**Comment by raq929** [comment]
Are the other click handlers working?

**Comment by jdaly04** [comment]
They are not.

**Comment by jdaly04** [comment]
This issue was solved by invoking addHandlers, which I was not previously doing in index.js.

**Comment by jdaly04** [comment]
Another component to fixing this was changing my index.js file which I had set up incorrectly. Updating that file to the below code worked. 

``` js
'use strict';

const authEvents = require('./auth/events.js');

// On document ready
$(() => {
  authEvents.addHandlers();  //when your document is fully loaded, then this code will run. the DOM has been
                              // constructed. if you're trying to use an API, check the README doc to know
                              // what the specs are
});

```
