### ISSUE TITLE
Deploying Issues - Applying my changes to the master branch

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/game-project#309]
I've been trying to push my changes to the master branch so that I can deploy my website ( as instructed by the link Jason sent out) but nothing I've done has worked. After searching for the solution several times, I've attempted to push the changes to the master branch to no avail.  I'm hesitant to try anything else alone because I do not want to lose any work and/or create additional problems, as I've seen in other people's issue postings. Not sure if this issue was caused because of the confusion created by my linter error or not.

**Comment by BenGitsCode** [comment]
What isn't working? you're not able to merge your changes into master? Or you're not able to deploy? Show me the bash log of your attempts so I can understand what you've tried so far.

**Comment by raq929** [comment]
If this is resolved, please comment with what you did to resolve it and close the issue.

**Comment by matthewgsommers** [comment]
I was just able to figure it out, sorry for the unneeded issue!
