### ISSUE TITLE
buttons in header not displaying properly

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/game-project#31]
currently these div buttons located on my header:

  <header>
  <span>
    <div class="sign-up-nav">Sign Up</div>
    <div class="sign-in-nav">Sign In</div>
    <div class="change-password-nav">Change password</div>
  </span>
  </header>

are displaying as a block, each div is underneath each other. I am trying to to have them display inline so the buttons will be adjacent. Here is the CSS:

span {
  display: inline;
}

Why is it not working?

**Comment by jdamiron** [comment]
currently these div buttons located on my header:

`````` <header>
  <span>
    <div class="sign-up-nav">Sign Up</div>
    <div class="sign-in-nav">Sign In</div>
    <div class="change-password-nav">Change password</div>
  </span>
    <div class="navbar-top"></div>
  </header>```

are displaying as a block, each div is underneath each other. I am trying to to have them display inline so the buttons will be adjacent. Here is the CSS:

span {
display: inline;
}

Why is it not working?
``````

**Comment by jdamiron** [comment]
open header function is at the top, it wasn't forgotten.

**Comment by jdamiron** [comment]
tag**

**Comment by RealWeeks** [comment]
Are you using bootstrap-sass?

**Comment by jdamiron** [comment]
No i'm not, each button is a div box.

**Comment by RealWeeks** [comment]
open up your chrome inspector and play around with the stylings for the spans and divs for a bit.  After testing some things post what you tried if you're still having problems.

**Comment by RealWeeks** [comment]
@jdamiron Are you still having this issue?  Ask your fellow developers for aid. Some of them are very strong in CSS.  Don't get hung up on this unless your logic is complete.

**Comment by jrhorn424** [comment]
@jdamiron Is this issue resolved?

**Comment by jdamiron** [comment]
It's not necessary resolved, other classmates couldn't figure out how to make it work. I currently have them in line but the original CSS on those buttons aren't applied and I can't change them to the size that I'd like.

**Comment by RealWeeks** [comment]
@jdamiron Have you resolved this issue? / Do you still need assistance with this?  If so please close, if you still need a hand please respond.

**Comment by jdamiron** [comment]
No, I have not been able to display as inline elements and keep the CSS I have attached to those div blocks.

**Comment by RealWeeks** [comment]
@jdamiron work on getting the logic down first. Once that is set let's come back to this. I don't want to you focus on the aesthetic.
