### ISSUE TITLE
module remark-lint error message

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/game-project#310]
I'm attempting to get rid of all my linter error/warning messages, but don't know what I should do to fix this one.

```linter
Error: Cannot find module `remark-lint`at line 0 col 0
    at /Users/Peanut/.atom/packages/linter-markdown/node_modules/unified-engine/lib/file-pipeline/configure.js:68:19
    at /Users/Peanut/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:444:7
    at Array.forEach (native)
    at /Users/Peanut/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:443:13
    at /Users/Peanut/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:327:5
    at /Users/Peanut/.atom/packages/linter-markdown/node_modules/vfile-find-up/index.js:135:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```
I tried googling it and found an issue on GitHub, but wasn't sure if the 'issues' were the same.
Here's the link: https://github.com/AtomLinter/linter-markdown/issues/115.

**Comment by gaand** [comment]
Please don't let this linter error keep you from moving forward. We'll have a look this morning and see if we came get it cleared up. 

I think it's great that you being diligent about linter errors.

**Comment by gaand** [comment]
For now

``` sh
git rm .remarkrc
```

Solving this correctly may take some time.

**Comment by gaand** [comment]
@ielole Would you please close this if the above is sufficient for now?  Thanks.

**Comment by ielole** [comment]
thank you.
