### ISSUE TITLE
All my new files are gone

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/game-project#312]
After doing my 1st deploy yesterday, I am now back in my training branch and don't see any of the work I did on my training branch. Is this because it is now in my gh pages branch and I should work within that or does it not matter?

**Comment by neugierige** [comment]
I'll come take a look.

**Comment by Sphilippe7** [comment]
So my files are now all in the gh-pages branch. Everything looks fine, I will just continue to work in the gh-pages branch.
