### ISSUE TITLE
Git Help

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/game-project#313]
Not entirely sure when I should be creating new branches or merging to master
I have several branches all of which are on different stages of the project which impacts the usability

**Comment by BenGitsCode** [comment]
@akradin let's meet in 5 minutes.

**Comment by neugierige** [comment]
Typically, developers create what are called "feature branches." This means that each branch deals with 1 particular functionality or feature of your web app. I would go back to my user stories as a guide about how to delineate the features, but also keep in mind that you mostly want to keep different parts of your app separate from each other, i.e. the view vs api vs the business logic

**Comment by neugierige** [comment]
Try to come up with a list, and feel free to ask for feedback. Also, FYI, this is not a git-related issue.

**Comment by akradin** [comment]
Received input as to when to branch and when to merge branches into master

-Create appropriately titled branches for individual parts of projects
-Once they work, merge them into master
