### ISSUE TITLE
Linking JS with sign-up

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#316]
continuing from former issue: https://github.com/ga-wdi-boston/game-project/issues/302#issuecomment-257859136
I was looking at the solution for https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass/tree/solution as suggested, but this solution branch actually doesn't seem to have all that we did in class. It does not have the nav with sign up/in/out and the JS seems to reference something that isn't actually in the branch's html. After looking at this and my trainings branch I don't really know still how to link this to my project.

**Comment by RealWeeks** [comment]
This was intentional. I didn't want to do 40% of people's projects for them.

**Comment by RealWeeks** [comment]
Bootstrap was a lot of copy and paste if you remember.  Goto the bootstrap site and experiment. I also recommend asking your classmates for help on this. I think many of them would be happy to help.

**Comment by raq929** [comment]
Issue #308 might also be helpful.

**Comment by jbuzzanco** [comment]
Ok

**Comment by jbuzzanco** [comment]
I did try this , asked other people and still don't know why it is not working to save sign up email and password information. I am guessing its something wrong with my files not linking to HTML or something like that...when I go into the console after signing up it shows nothing related to what I put into the sign-up.

**Comment by RealWeeks** [comment]
Can you paste in the signup function?

**Comment by jbuzzanco** [comment]
events

``` js
const onSignUpUser = function (event) {
  let data = getFormFields(event.target);
  event.preventDefault();
  api.signUp(data)
  .done(ui.success)
  .fail(ui.failure);
};
```

api

``` js
const signUp = (data) => {
  return $.ajax({
    url: app.host + '/sign-up',
    method: 'POST',
    data: data
  });
};
```

**Comment by RealWeeks** [comment]
can you put a `debugger` right after you open `onSignUpUser`, then try to sign up and let me know if it gets stopped at the debugger.

**Comment by jbuzzanco** [comment]
Ok, no it didn't stop.

``` js
const signUp = (data) => {
  debugger;
  return $.ajax({
    url: app.host + '/sign-up',
    method: 'POST',
    data: data
  });
};
```

**Comment by jbuzzanco** [comment]
this didn't stop either 

``` js

const onSignUpUser = function (event) {
  debugger;
  let data = getFormFields(event.target);
  event.preventDefault();
  api.signUp(data)
  .done(ui.success)
  .fail(ui.failure);
};
```

**Comment by J-Weeks** [comment]
`onSignUpUser`

**Comment by RealWeeks** [comment]
paste in your click handler please :)

**Comment by jbuzzanco** [comment]
``` js
const addHandlers = () => {
  $('#sign-up').on('submit', onSignUpUser);
  $('#sign-in').on('submit', onSignInUser);
  $('#change-password').on('submit', onChangePassword);
  $('#sign-out-button').on('click', onSignOutUser);
};
```

**Comment by RealWeeks** [comment]
Cool, and your html

**Comment by RealWeeks** [comment]
First, your `scripts/index.js`, though

**Comment by jbuzzanco** [comment]
I don't have an index.js, I have made api, events, and ui (ui JS file is empty at the moment).
Maybe that is needed to call these or something? Here's the html.

``` HTML
<div class="sign-up-form" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SIGN UP/IN? <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <a>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                    Sign Up
                    </button>
                  </a>
                </li>
                <li><a href="#">Sign In</a>
          <input type="text" name="credentials[email]" placeholder="E-mail">
          <input type="password" name="credentials[password]" placeholder="password">
          <input type="submit" name="submit" value="Sign in!">
                </li>
                <li><a href="#">CHANGE PASSWORD</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">SIGN OUT</a></li>
              </ul>
            </li>
          </ul>
        </div>
```

**Comment by RealWeeks** [comment]
For an `.on('submit', callback)` you need an html `<form>`

**Comment by RealWeeks** [comment]
That form should had the class of the selector your targeting with `$('#sign-up').on('submit', onSignUpUser);`

**Comment by RealWeeks** [comment]
If a classmate is helping your further this information will be very useful for debugging

**Comment by RealWeeks** [comment]
Along with this your button type is currently:

`<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">`

they type needs to be submit like so:

`<button type="submit" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">`

**Comment by jbuzzanco** [comment]
I think it is a submit button

``` HTML
<form class="sign-up-form" id="sign-up">
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="sign-up-email" placeholder="Email" name="credentials[email]">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password Confirmation">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </form>
```

**Comment by J-Weeks** [comment]
Sorry was looking at your signIn, that needs to be corrected as well.  But you still don't have a `<form>` tag

**Comment by RealWeeks** [comment]
ok nice, so now show me your `scripts/index.js` I think we almost fixed this signup

**Comment by jbuzzanco** [comment]
Isn't it sign-up-form which just gets referenced in JS as

``` js
const addHandlers = () => {
  $('#sign-up-form').on('submit', onSignUpUser);
  $('#sign-in').on('submit', onSignInUser);
  $('#change-password').on('submit', onChangePassword);
  $('#sign-out-button').on('click', onSignOutUser);
};
```

**Comment by RealWeeks** [comment]
nice, i see you changed the selector too

**Comment by RealWeeks** [comment]
but is `sign-up-form` a class or an id?

**Comment by jbuzzanco** [comment]
class so

``` js
const addHandlers = () => {
  $('.sign-up-form').on('submit', onSignUpUser);
  $('#sign-in').on('submit', onSignInUser);
  $('#change-password').on('submit', onChangePassword);
  $('#sign-out-button').on('click', onSignOutUser);
};
```

**Comment by RealWeeks** [comment]
nice!!!!

**Comment by RealWeeks** [comment]
so now put that debugger in the onSignUpUser function again, and let's see if it get stopped when trying to sign in a user

**Comment by RealWeeks** [comment]
make sure to have the chrome console open as you do it to see any errors that may appear

**Comment by jbuzzanco** [comment]
It pauses upon signing up. There is an error saying: `jquery.js:9536 POST https://aqueous-atoll-85096.herokuapp.com//sign-up 400 (Bad Request)`

**Comment by RealWeeks** [comment]
yep, so that pause it good, it means it's now getting to that function.  Good error! What looks weird about that url to you?

**Comment by jbuzzanco** [comment]
awesome, so sort of getting somewhere. As for the url https://aqueous-atoll-85096.herokuapp.com//sign-up should
maybe it should only have one slash after `.com`?

**Comment by jbuzzanco** [comment]
I just tried removing that slash at the end of `.com` it shows the same error. So I do not know what is wrong with the url.

**Comment by RealWeeks** [comment]
Paste in your errors from the chrome console please

**Comment by jbuzzanco** [comment]
jquery.js:9536 POST https://aqueous-atoll-85096.herokuapp.com/sign-up 400 (Bad Request)

**Comment by RealWeeks** [comment]
I'm gonna take a look at this

**Comment by gaand** [comment]
Make sure to pick an unlikely e-mail address.

**Comment by jbuzzanco** [comment]
resolved by adding name element to html in the password. There was a element for email but not password. 

``` html
<input type="password" class="form-control" placeholder="Password" name="credentials[password]">
<input type="password" class="form-control" placeholder="Password Confirmation" name="credentials[password_confirmation]">
```
