### ISSUE TITLE
Rails Server wont load -- port 4741 (Errno::EADDRINUSE)

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/game-project#317]
Attempted solutions: Restarting terminal and reloading all pertinent install packs

Also I had noticed that my config.js file which would link my rails server to my project was missing which I added and did nor resolve the issue.

Upon googling the error stackover flow has some command line solutions to change ports but I would like to not mess with what I dont know with out supervision.

**Comment by BenGitsCode** [comment]
http://bit.ly/2eUBShn

**Comment by BenGitsCode** [comment]
When you say restart terminal, you mean you've completely quit and reopened the application?

**Comment by RealWeeks** [comment]
means you're running another server instance somewhere. Find it and shut it down.

**Comment by akadane87** [comment]
Yes. command Q'd out of terminal completely. Front end server is running fine. Where else could I be running a server if my Terminal has been completely shut down already?

**Comment by akadane87** [comment]
And I did google solutions already but I don't want to 'killall ruby' without full understanding what's attached to that command

**Comment by BenGitsCode** [comment]
That is what it means. You're saying you've completely quit the terminal, reopened it and that's the error you get when you run your rails server?

**Comment by akadane87** [comment]
Decided to not test locally anymore by accessing my rails server. In my app.js file I changed the url from the local 4741 address to the https://aqueous-atoll-85096.herokuapp.com/ to use the live api
