### ISSUE TITLE
Git merge to master conflict

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#318]
In trying to merge my most up-to-date branch with master, I'm getting this message: 

~/wdi/projects/tic-tac-toe-project (master)$ git merge api
Auto-merging index.html
CONFLICT (content): Merge conflict in index.html
Automatic merge failed; fix conflicts and then commit the result.

Don't want to move forward with updating in fear of losing files.

**Comment by raq929** [comment]
Can you make a note here of what we did to resolve this and close it?

**Comment by jdaly04** [comment]
I was able to resolve the conflict by going through the index.html and selecting the correct version for each conflict. Once I did that, I was able to successfully merge.
