### ISSUE TITLE
redepolyment steps

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/game-project#319]
Is it necessary to run grunt build each time you redeploy?

**Comment by raq929** [comment]
Yes!

**Comment by raq929** [comment]
`grunt build` will compile all of your files. If you don't run it (and commit the results) none of your changes will be reflected on your site.

**Comment by raq929** [comment]
(If this issue is resolved, please comment and close.) :)

**Comment by ielole** [comment]
Followed all of the instructions on https://github.com/ga-wdi-boston/gh-pages-deployment-guide starting at step 2.) for redeployment. Before following those steps, I'd merged the branches that I had been working on with master.
