### ISSUE TITLE
List/show games

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/game-project#32]
To demonstrate save.

**Comment by RealWeeks** [comment]
@jpfriedman18

**Comment by gaand** [comment]
https://github.com/ga-wdi-boston/game-project#deliverables

See the second list, _In order to get a satisfactory score, your app must:_

**Use AJAX for data storage and retrieval**

**Comment by J-Weeks** [comment]
Clarify repo instructions.

**Comment by RealWeeks** [comment]
@gaand clarified this in recent commit. Okay to close?

**Comment by gaand** [comment]
@J-Weeks: It's standard to include the commit hash in the comment so that a search is unnecessary.  If you include the commit hash, it can be clicked and the diff examined easily.

**Comment by RealWeeks** [comment]
corrected with commit 876a824bc2aa19dba661f088ff3f13830228ad92

Edited by @gaand to remove leading `#`

**Comment by gaand** [comment]
But without the `#` :-).
