### ISSUE TITLE
Extracting ID from Join Game API Response

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/game-project#320]
I've been struggling with trying to extract information from my Join Game Response but been hitting a wall for a few hours. Would be helpful if it's possible to talk through my approach.

**Comment by BenGitsCode** [comment]
What have you tried so far?

**Comment by raq929** [comment]
(Also, in the future, don't hit your head for more than 30 minutes before opening an issue.) :)

**Comment by coffeeisamazing** [comment]
I've tried accessing from store and data objects.

**Comment by coffeeisamazing** [comment]
To provide more background, the issue was that I was confusing some of the data parameters from the sample auth solution. The data that is passed to the API call that contains the user name and ID - is different than the data parameter being returned. The game ID can be assigned based on the game associated with this returned data parameter (which includes the game ID). I'll then be able to reference this game ID with my join game ajax call based on the store variable.
