### ISSUE TITLE
Deployment issue following merge conflict

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/game-project#321]
I tried to deploy my game after following the directions found at https://github.com/ga-wdi-boston/gh-pages-deployment-guide. While it says there is nothing to commit, and gh-pages is already up to date with master, and I've commented out the bundle and vendor files, the page still looks broken and I'm getting an error messages that says my GET requests for the bundle and vendor files are failing. 

I did have merge conflicts between my master, gh-pages, and working (html-css) branch that I initially thought were to blame but I was able to resolve them with Jason and have no issues locally. What else can I try?

**Comment by BenGitsCode** [comment]
Did you `grunt build`?

**Comment by RealWeeks** [comment]
also looking at github:

this is your .gitignore

```
tmp
dist
vendor.js
specs.js
*bundle.js
_SpecRunner.html
*.woff2
*.woff
*.svg
*.ttf
*.eot
```

**Comment by BenGitsCode** [comment]
```
tmp
dist
specs.js
_SpecRunner.html
*.woff2
*.woff
*.svg
*.ttf
*.eot
```

That's what I'm seeing in her gh-pages bundle, which should be correct.

**Comment by BenGitsCode** [comment]
@kiraamaa let's take a look at this after lunch

**Comment by kiraamaa** [comment]
I did run grunt build, and I did remove the files in my gh-pages bundles. I still have the files in my master and html-css bundles.

**Comment by kiraamaa** [comment]
I followed all of the directions step by step in the deployment guide.

**Comment by kiraamaa** [comment]
Nevermind! I think I didn't wait long enough for the server to load. It works now, after waiting 15 min+.

**Comment by RealWeeks** [comment]
@BenGitsCode You're assigned to this are you going to help out here?

**Comment by BenGitsCode** [comment]
I was waiting for that, I noticed it during lunch. 👍
