### ISSUE TITLE
Change password issue, the app.user.id is throwing an error

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/game-project#323]
My 'change password' function isnt working properly because the 'app.user.id' portion of the code is pointing in the wrong direction. I think the issue is stemming from missing notes from class review. 

const changePassword = function(data){
  return $.ajax({
    method: 'PATCH',
    url: app.host + '/change-password/' + app.user.id,
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};

**Comment by raq929** [comment]
What do you mean by 'pointing in the wrong direction'? When you run this code, do you get an error?

**Comment by RealWeeks** [comment]
`app.host` in most cases only holds a reference to the url. App points to a file that is required I'm assuming, and that file probably only contains a url.

**Comment by RealWeeks** [comment]
Put a `debugger` after you open the `changePassword` block and tell me what the value of both app and data are.

**Comment by matthewgsommers** [comment]
Is this what you're referring to? From the console after the debugger triggers:

const changePassword = function(data){
  debugger;
  return $.ajax({
    method: 'PATCH',
    url: app.host + '/change-password/' + app.user.id,
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};

**Comment by gaand** [comment]
What code runs on successful sign in?  Where do you store the user data?

**Comment by matthewgsommers** [comment]
The following happens on a successful sign in: 

const onSignIn = function(event){
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signIn(data)
  .done(ui.signInSuccess)
  .fail(ui.fail);
};

The user data is stored in store.js - correct?

In regards to the data returned from the debugger, its storing the object 'passwords'

**Comment by gaand** [comment]
Please post the code for `ui.signInSuccess`.

Since you're referencing `app`, not `store`, this may be the source of your issue.

**Comment by matthewgsommers** [comment]
Ok so I think I found part of the problem: the code above references 'ui.signInSuccess', but in my 'ui.js' file, its referenced as just 'success'. Changing now.

**Comment by RealWeeks** [comment]
@gaand I have experience with this issue. I'm going to assign I think there were some things I missed

**Comment by RealWeeks** [comment]
Recommended that @callmelife follow answering and asking questions to unlock this bug fix.  The slow walk would teach more in the long run then the fast walk there.

**Comment by matthewgsommers** [comment]
Ohhhh Ok now I understand why Antony was pointing me in the direction of 'ui.signInSucces', my problem is that it doesnt exist in the ui.js file!! I originally thought that I had to change 'ui.success' to 'ui.signInSuccess' but after looking at the various events I have in 'events.js' I figured it out that I need a constant in 'ui' for each of the event functions. This must have been a result of not having everything from class we reviewed this topic in.

**Comment by matthewgsommers** [comment]
Sign up, sign in, change password, and sign out all now work correctly. I was also able to get my game's functionality working by moving my JS into  assets/scripts/index.js. Big steps in the right direction.
