### ISSUE TITLE
Clarification of requirements: Do I need to be able to track both players' statistics?

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/game-project#324]
Do both users playing a game, on the same computer, both need to be logged in?
Do I need to be able to save both of their game statistics?
Can I have one of my players be a computer 'player'?

I've checked through the closed issues, but haven't found anything relating to my question.

**Comment by BenGitsCode** [comment]
@ielole take a look at the requirements of the project.

A computer player is required, multiple players is a bonus that you shouldn't put effort into until you've fulfilled all other requirements.

**Comment by BenGitsCode** [comment]
Does that make things clear?

**Comment by ielole** [comment]
I've reviewed all of the documentation, and didn't see the answer spelled out, explicitly, anywhere. I know that the paragraph under the 'goals' section tries to clarify the players, but I was still unsure.

**Comment by gaand** [comment]
@BenGitsCode I'm confused.  When I read, "A computer player is required", I think I need to build an AI.  @ielole You do not need to do that.

@ielole If you want two distinct players recorded, then yes.  You are allowed to just record games for a single logged in player (`X`).

**Comment by gaand** [comment]
Having two logged in players on one machine is not required.

**Comment by ielole** [comment]
Ok, thanks.

**Comment by BenGitsCode** [comment]
Sorry for confusing you, Antony's answer is more helpful and concise.
