### ISSUE TITLE
Git Merge Conflict

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/game-project#325]
This is Rick...

I am unable to merge my local 'dev' and 'master' branches.  This also is preventing me from pushing to my repo on Github. 

I receive the following error:
---------------------------------------------
fatal: Exiting because of an unresolved conflict.
~/wdi/projects/ttt_project (master)$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)
Changes to be committed:
	modified:   assets/scripts/auth/ui.js
	modified:   assets/scripts/config.js
	modified:   assets/scripts/index.js
	modified:   index.html
Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   assets/scripts/auth/api.js
	both modified:   assets/scripts/auth/events.js
-----------------------------------------------------------

I started to resolve the issues myself but realized I may do unintentional damage.

**Comment by BenGitsCode** [comment]
Will look at this now.

**Comment by raq929** [comment]
If this issue is resolved, please close it. Thanks!

**Comment by rickdean** [comment]
I followed Ben's advice and think I am good to go...  Thank you!
