### ISSUE TITLE
scss-linter errors

### ISSUE THREAD

**Issue by kmg1434** [ga-wdi-boston/game-project#326]
Every time I try and open and/or modify a .scss file I get two errors:

Uncaught Error: write EPIPE

BufferedProcessError: 
Failed to spawn command `scss-lint`. Make sure `scss-lint` is installed and on your PATH

I have tried reinstalling my linter package and linter-scss-lint package to no avail. After doing some research online I found this thread: 

https://github.com/AtomLinter/linter-scss-lint/issues/39

but I'm having a hard time following the solution as I cannot figure out where linter-scss-lint.coffee exists.

I have attached a screenshot for a better view of what's going on.

<img width="1018" alt="screen shot 2016-11-02 at 2 46 26 pm" src="https://cloud.githubusercontent.com/assets/20648046/19942889/9c41eb74-a10b-11e6-8267-da14bd688e3e.png">

**Comment by raq929** [comment]
Exciting! It looks like scss-lint might not have been installed during installfest. 
`gem install scss_lint`
then `apm install scss-lint`

**Comment by raq929** [comment]
Ah, after farther research, there was a breaking change in the linter recently. Go to atom and uninstall `linter-scss-lint`. Then follow the instructions above.

**Comment by kmg1434** [comment]
Thanks for the info! Are you sure that the gem command uses an underscore and the apm command uses a dash? Just making sure that wasn't a type-o. Thanks!

**Comment by kmg1434** [comment]
Well I tried both `apm install scss-lint` and `apm install scss_lint`

and both said `Request for package information failed: Not Found`

Not sure where to go from here.

**Comment by raq929** [comment]
Yes! Very sure. :) Ruby syntax is with underscores.

**Comment by kmg1434** [comment]
Ok after running `gem install scss_lint` all seems to be well after a second try at `apm install linter-scss-lint`. Thanks again!
