### ISSUE TITLE
[GIT] proper old branch handling.

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/game-project#33]
What is the industry standard for handling old branches?

see [Ethan's github branch network](https://github.com/erdesi90562/tickTackToe/network)

@J-Weeks

**Comment by RealWeeks** [comment]
Complex git issue, partially explained to me earlier involving multiple branches and merging / losing commit history and rebranching.

**Comment by jrhorn424** [comment]
Once branches are merged, you can safely delete them locally and on the remote.

**Comment by jrhorn424** [comment]
You've currently got a dangling branch `login`. If that code hasn't been merged in, but the functionality already exists in master, that branch can be removed as well. Make sense?
