### ISSUE TITLE
X in box distorts game board appearance

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#331]
I have created an onClick handler and am trying to get an "X" to appear in the box. The "X" is appearing, but it is distorting the individual square appearance on the board, and I'm not sure why.

The JS I have for the event handler is:
```js
const onClickSq1 = function () {
  $("#sq1").text('X');
};
```

Here is the "addHandler":
```js
$('#sq1').on('click', onClickSq1);
```
I'm not sure how to paste in what it's doing in the browser, but it's basically making that individual square height more than it should be (on the bottom border of that square).

**Comment by neugierige** [comment]
@jdaly04 this sounds like a styling issue. have you tried changing your font size?

**Comment by jdaly04** [comment]
That's what I was thinking, but there's not even a tag in my scss file for the "X" itself. I don't know how I would even refer to it, as it only exists in my events.js file as of now.

**Comment by neugierige** [comment]
Right, so you have no styling on it right now, and it's not giving you the behavior you want... So if I were you, I would put some styling on it, in order to achieve the effect you want, or at least to see how it can be manipulated. 

The other thing you could try is to simply put the character 'X' in the actual HTML and see what the size looks like. I would guess that it appears the same way as when you do the click.

**Comment by jdaly04** [comment]
I tried adding styling, and I did have an X in the HTML. The size of the actual "X" doesn't matter, it's just that it's distorting the square size.

**Comment by raq929** [comment]
Are you setting the height and width of the square? If you set them, they won't be able to move.
You could also set the font-size of the square, which will control the size of the x.

**Comment by jdaly04** [comment]
I had to re-arrange some of my scss style-sheet  as the click handler itself was not causing the problem, it was the styling that was the issue. I had to set a height and width for my box and also apply a font-size for the individual squares.
