### ISSUE TITLE
JQuery text update not firing

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/game-project#332]
Can anyone help me figure out why this jquery call isn't firing? The line of code directly before it is working, and a debugger I put right after also works.

```html
const theyWon = function() {
  currentGame.current.game.over = true;
  $('.box').off('click');
  $('#start-game-button').show();
  $('.status-row').text("Player " + currentGame.turn.toUpperCase() + " wins!");
  };
```

this similar call I make elsewhere works every time:

```html
const changePlayer = function() {
  if (currentGame.turn === 'x') {
    currentGame.turn = 'o';
  } else if (currentGame.turn === 'o') {
    currentGame.turn = 'x';
  }
  $('.status-row').text("Player " + currentGame.turn.toUpperCase() + " go!");
};
```

am I missing something?

**Comment by neugierige** [comment]
are you referring specifically to the `$('.status-row').text(...)` line?

**Comment by ioncrash** [comment]
yes sorry

the line
`$('.status-row').text("Player " + currentGame.turn.toUpperCase() + " wins!");`

does not fire

**Comment by neugierige** [comment]
try this: change the stuff inside `text` to a single string

**Comment by ioncrash** [comment]
tried it this way:

```
const theyWon = function() {
  currentGame.current.game.over = true;
  $('.box').off('click');
  $('#start-game-button').show();
  $('.status-row').text("Player X wins!");
  };
```

still no luck

**Comment by neugierige** [comment]
let me take a look

**Comment by neugierige** [comment]
@ioncrash don't forget to say to what happened!

**Comment by ioncrash** [comment]
The status bar was being updated again after this code fired! I added an if clause around the changePlayer function to solve!
