### ISSUE TITLE
Don't know how to start with game logic

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#333]
I've been looking through other issues and talking with others but don't really know how to get started on the game logic.  Sounds like a few other people are having / had trouble with this as well. I think it would have something to do with linking each of the boxes to an array or an object. Then displaying an x or o with a click handler. Just am not sure at all how to translate this to code..

**Comment by neugierige** [comment]
1) Go back to your user stories, figure out the functionality you want in your game. 
2) Do you remember the exercise we did modeling laptops as objects? Try to identify what objects you need, what properties/methods you need for each of them. 
3) Another way to think about it is to look at the HTML you currently have. Do you have event handlers on it? What should happen after those events happen?

**Comment by kfili** [comment]
I'm also confused where to start... so:
1) user stories: 
as a user I would like to:
-click on cell to make it display an X or O. (functionality: click empty cell-> cell displays X/O)
-make following moves. (
-not change a box that already has an X/O
...
2) objects: 
-cells on the board. 
-methods on cells, like change the cell contents on click.
Parameters: .... of functions?

3) I have event handlers on the cells but I don't think Joel does.

I think the events should execute functions that take into account the state of the game, and then Jquery should be used to manipulate the DOM to represent the new state of the game.

**Comment by raq929** [comment]
Cool. So if you take your first user story, click on a cell to make it display x or o, what are the steps you need to take in order to accomplish that story?

**Comment by raq929** [comment]
This is related to #334

**Comment by jbuzzanco** [comment]
My guess , I would say select the box with an id in the HTML. Then from that id, in the event handler, get JS to display onClick method referencing the id using this method http://www.w3schools.com/jsref/event_onclick.asp

**Comment by raq929** [comment]
So we're already using jQuery to handle click events in auth. You should
use that syntax to set a click handler on your game board.

**Comment by raq929** [comment]
So, you already have a bunch of click handlers set for auth, right? I would use that syntax to set a click handler on your game board.

**Comment by jbuzzanco** [comment]
Ok, I do have handlers for my auth and it is now working. So in the jquery it would be like a post method in the API probably. I don't know. The POST method would get it on the board from the ID i think, but don't know how I would reference the ID in jquery. If that's a way of doing this.

**Comment by raq929** [comment]
I think you're thinking in steps that are too big here. 
Before you make an API call, start by just setting a click handler on your game board. Look at issue #334, where I break it down even more.

**Comment by neugierige** [comment]
Joel, be sure to read the documentation for the API to understand what it's capable of handling. The ID you're speaking of, what is it attached to? What kind of an object?

**Comment by jbuzzanco** [comment]
I actually made the boxes for the tic tac toe board into div classes to try and create a click handler as was suggested. So they are attached to the div class as box-0, box-1, etc.
Not Sure why click handler is not working. I'm following the documentation to best I know how https://api.jquery.com/click/ http://api.jquery.com/on/
Here is the code

``` html
<div class="centered container">
      <div class="row">
        <div class="col-xs-4 col-md-4 centered box box-0">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-1">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-2">.col-md-8</div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-md-4 centered box box-3">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-4">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-5">.col-md-8</div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-md-4 centered box box-6">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-7">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-8">.col-md-8</div>
      </div>
    </div>
```

events.js

``` js
'use strict';
let clicked_box = function(){
  console.log('clicked');
};

$('.box-0').on("click", clicked_box);

$('.box-1').on("click", clicked_box);

$('.box-2').on("click", clicked_box);

$('.box-3').on("click", clicked_box);

$('.box-4').on("click", clicked_box);

$('.box-5').on("click", clicked_box);

$('.box-6').on("click", clicked_box);

$('.box-7').on("click", clicked_box);

$('.box-8').on("click", clicked_box);
```

also I should probably make this a different issue now I am guessing?
