### ISSUE TITLE
 Getting content into my board cells

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/game-project#334]
I've made my cells clickable, but now I am trying to get 'x'/'o' into those cells. I was planning on using if statements and for loops inside of my event handler functions to navigate an array, with an x, an o and an empty string, that was somehow related to my divs. I feel as though I'm floundering and should be using jquery and the DOM instead what I'm planning to use. I've started working on user stories, but I think that my approach is too simplistic. I would appreciate a bit of help with direction.

**Comment by raq929** [comment]
Well, your event handlers are jQuery, and they respond to DOM events. I don't think you're on the wrong track here. I'd say first write a handler that can put an x in a box. Then work on changing between x and o. If a problem seems overwhelming, try to break it down into two or more smaller problems. (Like, if writing a click handler that puts x in a box is too big, start with write a click handler that console.logs x when you click a box. Then work on placing x in the box.)
Does that get you started?

**Comment by ielole** [comment]
Yes it does. I'm gonna work on getting my click handler to place a x in a cell.
