### ISSUE TITLE
webpackJsonp is not defined(…) error

### ISSUE THREAD

**Issue by sujkid** [ga-wdi-boston/game-project#335]
My game app returns a webpackJsonp is not defined(…) error after I deploy into githu.. It works pretty fine locally.
I did comment out *bundle.js and vendor.js in the gitignore.js before i started deployment the first time.

**Comment by raq929** [comment]
Did you run grunt build, and commit bundle.js and vendor.js?

**Comment by raq929** [comment]
Did you merge master into gh-pages? If so, they might be uncommented out again.

**Comment by raq929** [comment]
(meanwhile, keep working locally)

**Comment by sujkid** [comment]
I grunt build, added and committed

**Comment by sujkid** [comment]
but only bundle.js

**Comment by sujkid** [comment]
i didn't have any vendor.js to add?

**Comment by gaand** [comment]
I think it's `vendor.bundle.js`

**Comment by sujkid** [comment]
So this is what I got when I git status after grunt build
    modified:   bundle.js
So i added and committed only bundle.js?

**Comment by gaand** [comment]
There are two bundled files that need to be added to your `gh-pages` branch, one is your code, `bundle.js` and the other is the vendor code, jQuery, bootstrap, etc, which I think is called `vendor.bundle.js`

**Comment by raq929** [comment]
After grunt build a second time, only bundle.js would have changed, so that seems right to me.
Is it working now? If not, what's happening on the deployed site?

**Comment by sujkid** [comment]
It's still not working.. My deployed site has no bootstrap at all.. so I guess it's something that Antony said.. I don't remember what my first grunt build did.

**Comment by gaand** [comment]
Is the vendor bundle on the `gh-pages` branch on GitHub?

**Comment by sujkid** [comment]
Yes, it's on both gh-pages and master branch

**Comment by raq929** [comment]
We're working on fixing this, it's not a problem with what you've done.

**Comment by raq929** [comment]
If Antony's fix worked #355    . !

**Comment by raq929** [comment]
Well. I blame my phone. Please close this issue if it has been resolved.

**Comment by sujkid** [comment]
Antony's fix in #355 resolved this issue
