### ISSUE TITLE
Trying to toggle between x and o based on number of clicks

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/game-project#336]
I think that the attempt below should maybe be two different functions with a callback. I know that [j] is undefined. I'm stuck with where to go next to actually get this function to work.

```js
let board = ['#sqa','#sqb','#sqc','#sqd','#sqe','#sqf','#sqg','#sqh','#sqi'];
let clickNumber = [1,2,3,4,5,6,7,8,9];

const placeSymbol = function () {
  for (let i = 0; i < clickNumber.length; i++){
    if (clickNumber[i] % 2 === 0) {
      $(board[j]).text('o');
      } else {
      $(board[j]).text('x');
    }
  }
};

```

**Comment by raq929** [comment]
I think you have the right idea here, and probably don't need a more complicated set up. In fact, this can be uncomplicated.
Here's what I think you're trying to do here.
1) keep track of which turn number it is
2) switch between x and o based on the turn number
3) set the text in the box based on the turn number

I don't think a for loop is what you want here, because it will loop 9 times every time you use it.
I would try a simpler approach. Have a variable that is just a counter (a number) and use an if statement like you did here in order to choose x or o.
Also think about when you want this code to run, what should trigger it.

**Comment by neugierige** [comment]
The fact that you are using a variable that's undefined is an indication that you need another variable. What do you want `i` to represent? What do you need `j` for? To me, it looks like you want separate functionalities.

**Comment by ielole** [comment]
Would either of you be willing to meet for a couple of minutes to talk this over?

**Comment by neugierige** [comment]
yes, glad to. where are you?

**Comment by ielole** [comment]
in the kitchen

**Comment by ielole** [comment]
I'm still stuck and don't know what to do.

**Comment by neugierige** [comment]
coming!

**Comment by raq929** [comment]
If this has been resolved, please write how you resolved it and close the issue.

**Comment by ielole** [comment]
I'm having a bit of trouble with the syntax of the .text(). My code keeps stopping when I try to view it locally. I've included what i have below.

``` js
const board = ['','','','','','','','',''];
//const turnNum = 0;
let turnNum = 0;
//for every div on the board
for (let i = 0; i <board.length; i++) {
  //if the text is not blank
  if ($(board[i].text()) !== '') {
    turnNum = turnNum + 1;
    //add one to turnNum
  }
}

```

**Comment by neugierige** [comment]
please update if this is resolved, or let us know how else it's not working

**Comment by ielole** [comment]
I'm trying to test different aspects of the three different blocks of code that we had talked about before, but I'm still having trouble putting my x/o in my board array.

**Comment by neugierige** [comment]
please share your code. what have you tried so far?

**Comment by raq929** [comment]
If this issue has been resolved, please comment and close it.

**Comment by ielole** [comment]
I'm still trying to figure out the if statement from above.

**Comment by ielole** [comment]
I created a different function, changePlayer, using some of the code from what's below 'turnNum', but it does something to break my putSymbol function. Also, I know that turnNum should be incremented by one after the click functions, but I'm not quite sure how to pull that off.

``` js
//let playerX;
//let playerO;
const board = ['','','','','','','','',''];
let turnNum = 0;
//for every div on the board
// for (let i = 0; i <board.length; i++) {
//   //if the text is not blank
//   if (board[i] === )) {
//     turnNum = turnNum + 1;
//     //add one to turnNum
//   }
// }


//create a function which increments playerTurn called changePlayer
let playerTurn;
const changePlayer = function() {
    if (turnNum % 2 === 0) {
      playerTurn = 1;
    turnNum = turnNum + 1;
    //console.log(playerX);
  } else {
      playerTurn = 2;
    turnNum = turnNum + 1;
    //console.log(playerO);
  }
};

// use turnNum % to determine which player
// let playerTurn;
//   if (turnNum % 2 === 0) {
//   playerTurn = 1;
//     console.log(playerX);
//   } else {
//     playerTurn = 2;
//     console.log(playerO);
//   }

const putSymbol = function(squareLetter, squareId) {
  if (playerTurn === 1) {
    $(squareLetter).text('x');
    board[squareId] = 'x';
  }  else {
    $(squareLetter).text('o');
    board[squareId] = 'o';
  }
};

const onAClick = function() {
  putSymbol('#sqa', 0);
};
```

**Comment by neugierige** [comment]
how do you know that `changePlayer` is breaking `putSymbol`?

As per our discussion this morning, we determined that turnNum should _not_ be incremented by clicks, but by another mechanism. Do you recall what that was?

**Comment by ielole** [comment]
When I comment out changePlayer and use the same information outside of a function I can use a debugger in putSymbol and see where the x or o is in the board array, but the debugger doesn't stop the code in when I use changePlayer.

I had forgotten that part of our discussion, but I think that I want to increment turnNum after the symbol, ie x or o is placed into the square.

**Comment by raq929** [comment]
I can come take a look when you get back.

**Comment by ielole** [comment]
Instead of evaluating turnNum by counting the number of times the board was clicked or how many elements in the board array were not null, I incremented turnNum after an 'x' or 'o' was placed in a square.

``` js
const board = ['','','','','','','','',''];
let turnNum = 4;

// use turnNum % to determine which player
//create a function which increments playerTurn called changePlayer
let playerTurn;
const changePlayer = function() {
    if (turnNum % 2 === 0) {
      playerTurn = 1;
  } else {
      playerTurn = 2;
  }
    turnNum = turnNum + 1;
};


const putSymbol = function(squareLetter, squareId) {
  if (playerTurn === 1) {
    $(squareLetter).text('x');
    board[squareId] = 'x';
  }  else {
    $(squareLetter).text('o');
    board[squareId] = 'o';
  }
  changePlayer();
};

const onAClick = function() {
  putSymbol('#sqa', 0);
};

```
