### ISSUE TITLE
subsequent deploys not showing properly

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/game-project#337]
when I first deployed it looked great, but when I redeployed just now the page looked like its css was removed.

https://ioncrash.github.io/working-project/

am I doing it wrong?

**Comment by raq929** [comment]
What did you do to redeploy?

**Comment by ioncrash** [comment]
I followed all the same steps again from 

https://github.com/ga-wdi-boston/gh-pages-deployment-guide

including a new grunt build

**Comment by raq929** [comment]
When you merged master into gh-pages pages, you may have reverted the .gitignore. Is bundle.js still uncommented?

**Comment by ioncrash** [comment]
It looks like this:

tmp
dist
# vendor.js
specs.js
# *bundle.js
_SpecRunner.html
*.woff2
*.woff
*.svg
*.ttf
*.eot

is that correct?

**Comment by ioncrash** [comment]
er... it looks like this

```
tmp
dist
# vendor.js
specs.js
# *bundle.js
_SpecRunner.html
*.woff2
*.woff
*.svg
*.ttf
*.eot
```

**Comment by raq929** [comment]
Yeah, you'll need to uncomment them, build, and commit.

**Comment by raq929** [comment]
If this worked, please comment with what you did, then close the issue.

**Comment by ioncrash** [comment]
sorry I was distracted. I'm still getting the same result

**Comment by raq929** [comment]
This seems to be a problem with the template. We're working on diagnosing and fixing.

**Comment by neugierige** [comment]
@ioncrash have you been able to update the template and get it to work again?

**Comment by ioncrash** [comment]
Just did per the new instructions. Thanks!
