### ISSUE TITLE
Most recent deploy issue

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#338]
I have deployed on several occasions with no issues. The las time I deployed, about 1.5 hours ago, I now have lost my styling. It looks like just plain text with no functionality working.

**Comment by raq929** [comment]
See issues #337 and #336

**Comment by jdaly04** [comment]
To give more detail on this somewhat impulsive issue posting (Sorry!), I have checked to ensure that I still have commented out bundle.js and vendor.js.

Link to my deployment site: [(https://jdaly04.github.io/tic-tac-toe-project/)]

**Comment by raq929** [comment]
Actually 336 is not relevant. Oops.

**Comment by jdaly04** [comment]
Hahaha no problem! I was actually JUST looking at Johnathan's issue ( I think it's Johnathan!) and saw your comment! I'm sorry for the double issue post! I think it was literally seconds between me looking at his issue and you commenting. I'll try this now (this being uncomment out bundle.js and vendor.js). Thanks for helping so late  =)

**Comment by raq929** [comment]
It seems like you're not the only person with this issue. Did you run grunt build? And commit afterwards? Keep going with the game logic and we'll sort it in the morning.

**Comment by jdaly04** [comment]
I'm in the kitchen area. I was late getting here, but my deployment is still not working properly.

**Comment by raq929** [comment]
This seems to be a problem with the template, not with something you're doing. We're working on a fix.

**Comment by raq929** [comment]
Please close this issue if it was resolved with #355

**Comment by jdaly04** [comment]
This issue was not resolved, but I have not yet tried using Antony's test to deploy my updated stuff. Will do that now and re-open the issue if it doesn't work.
