### ISSUE TITLE
Deployment issue with vendor bundle (reoccurrence)

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/game-project#339]
I believe this is a reoccurrence of https://github.com/ga-wdi-boston/game-project/issues/303. This had been (at least superficially) resolved and was working after switching to the gh-pages branch under settings for the repo.

**Error:**
Page is not loading properly on github pages but works fine locally.
https://coffeeisamazing.github.io/game-project/

```bash
2016-11-02 22:42:16.820 https://coffeeisamazing.github.io/game-project/vendor.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
2016-11-02 22:42:16.837 bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
```

**I've tried the following:**
- Ensuring linter and grunt nag are clean.
- Deleting gh-pages branch and restarting the process per the deployment guide.
- Removing the vendor bundle and bundle files and regenerating using grunt build.
- Switching target branch for pages to master and back to gh-pages again.

**Comment by coffeeisamazing** [comment]
Looks like the same as https://github.com/ga-wdi-boston/game-project/issues/338 and https://github.com/ga-wdi-boston/game-project/issues/335.

**Comment by joaufi** [comment]
I am having this exact same problem, and have followed the exact same steps that you. Talked with Rachel and it is perhaps a problem with Github and she said she would look into it.

**Comment by raq929** [comment]
This seems to be a problem with the template, not with something you're doing. We're working on diagnosing and fixing it. Keep working locally for now.

**Comment by neugierige** [comment]
@coffeeisamazing have you been able to resolve this? if so, please close and comment

**Comment by coffeeisamazing** [comment]
Resolved per solution provided in https://github.com/ga-wdi-boston/game-project/issues/355.
