### ISSUE TITLE
In which index.js file should we link/require the API authentication js file?

### ISSUE THREAD

**Issue by msyao** [ga-wdi-boston/game-project#34]
There are 2 index.js files in the project - 1 in the parent folder and 1 in assets/scripts/ folder.

I am unsure which file to require(' .js') the API authentication js file.

Thank you.

**Comment by GA-MEB** [comment]
When you run `grunt serve`, what it does is take all the files in your `assets` directory and combine them into one JS file and one CSS file. The `index.js` file in the root folder of your project is the finished product.

The takeaway from this is that any JS, CSS, or SASS you write should go into `assets`, so you should put the API JavaScript file into `assets` too and link to it from the `index.js` file in that directory.

**Comment by msyao** [comment]
Thank you Matt!

I will do that now.

**Comment by jrhorn424** [comment]
@MattB-GA-Boston That's not correct. `index.js` in root is not the bundle. That's `bundle.js`. The `index.js` file in the root is the main manifest: it delegates to the manifests inside `scripts` and `styles`. It also exposes jQuery to the browser window. That's all it does. It should not be edited.

The second paragraph of advice still holds. :+1:

**Comment by GA-MEB** [comment]
Ah! Sorry, my mistake - thanks for clearing that up, @jrhorn424.

**Comment by msyao** [comment]
Thank you guys!
Y'all so smart!
