### ISSUE TITLE
can't get on "click" method to work

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#340]
I actually made the boxes for the tic tac toe board into div classes to try and create a click handler as was suggested. So they are attached to the div class as box-0, box-1, etc.
Not Sure why click handler is not working. I'm following the documentation to best I know how https://api.jquery.com/click/ also http://api.jquery.com/on/
Here is the code

```html
<div class="centered container">
      <div class="row">
        <div class="col-xs-4 col-md-4 centered box box-0">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-1">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-2">.col-md-8</div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-md-4 centered box box-3">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-4">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-5">.col-md-8</div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-md-4 centered box box-6">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-7">.col-md-8</div>
        <div class="col-xs-4 col-md-4 centered box box-8">.col-md-8</div>
      </div>
    </div>
```
events.js
```js
'use strict';
let clicked_box = function(){
  console.log('clicked');
};

$('.box-0').on("click", clicked_box);

$('.box-1').on("click", clicked_box);

$('.box-2').on("click", clicked_box);

$('.box-3').on("click", clicked_box);

$('.box-4').on("click", clicked_box);

$('.box-5').on("click", clicked_box);

$('.box-6').on("click", clicked_box);

$('.box-7').on("click", clicked_box);

$('.box-8').on("click", clicked_box);
```

**Comment by raq929** [comment]
So, these are in events.js. Where are the click handlers for your auth? I suspect if you look at them you'll see that they are in a function that is exported and run in another file.

**Comment by jbuzzanco** [comment]
Auth is required in index.js. I tried requiring game/events.js which is where I'm trying to keep my game logic, but it's not getting the file properly I believe because nothing is happening.

``` js
const authEvents = require('./auth/events.js');

const gameEvents = require('./game/events.js');

// On document ready
$(() => {
  authEvents.addHandlers();
  gameEvents.addHandlers();

});
```

**Comment by jbuzzanco** [comment]
when I put it in the same auth file its working however I am not sure why, Suju helped show me to get it in auth working but I don't really know whats different other than it's in auth directory not game directory.

**Comment by jbuzzanco** [comment]
resolved. console.log('clicked') into the console. Refreshed the files and made sure game folder was put into index.js
