### ISSUE TITLE
Trying to make click function for "o"

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/game-project#344]
I already have a click handler for "X" but I've been trying to come up with an if statement to tie in "O" and none of them are working.

**Comment by RealWeeks** [comment]
Can you paste in what you have tried and what worked for x?

**Comment by Sphilippe7** [comment]
in my events file

```
const addXO = function (event) {
  event.preventDefault();
  $(event.target).text('x');
};

let player1 = x;
let player2 = o;

if(player1 

const addHandlers = () => {
  $('.sign-up-form').on('submit', onSignUp);
  $('.sign-in-form').on('submit', onSignIn);
  $('.sign-out-form').on('submit', onSignOut);
  $('.ttt-box > .row > div').on('click', addXO);
};
```

@RealWeeks

**Comment by RealWeeks** [comment]
Well it seems like your add XO function would be the place to do that.  You probably want to add something that increments every click and alternated between putting an X and an O.

**Comment by RealWeeks** [comment]
I would think that would involve some control flow (if/else) in that function

**Comment by Sphilippe7** [comment]
I know this is wrong but I don't know how to write the else/if statement

```
const addXO = function (event) {
  event.preventDefault();
  $(event.target).text('x');
else $(event.target).text('o');
};
```

**Comment by RealWeeks** [comment]
I want you to look this over and see their example on if/else

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else

**Comment by neugierige** [comment]
You're on the right track with an if-statement. How about also using a variable to represent the text that you want to set?

**Comment by raq929** [comment]
What's the status on this issue?

**Comment by Sphilippe7** [comment]
sorry I went to lunch then came back. I had to find a function that would work for this so I took it out of my events file and but it into my index.js file. Matt helped me come up with a function.
