### ISSUE TITLE
Need help with game logic

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#345]
I have the "toggle between two players. I'm trying to create a game move, but I'm now realizing my confusion lies in how I can translate my html grid "gameboard" to my js array. How can I make that array in JS understand that I want each index of the gameboard array to be the individual squares I have in HTML? 

Can someone potentially look at my code so far and help steer me in the right direction? I am in the kitchen.

**Comment by raq929** [comment]
I'll come by.

**Comment by jdaly04** [comment]
I realized that I can add some info into my event handlers to map each individual square to the appropriate index within my board array. I also had to export some of my variables from the game logic to make it accessible in my click-handlers file. 

For example:

``` js
const onClickSq1 = function () {
  gameUi.board[0] = 'x';
  $("#sq1").text('X');
};
```
