### ISSUE TITLE
Game Logic from on whiteboard

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#346]
as far as what is on the whiteboard today in classroom 4, there is a const board that is an empty array with 9 indexes. Which to my understanding is the 9 different spots on the board (correct me if I am wrong).  Then for the next parts with the .every method and the if statement I do not really know what that is doing. I believe Antony said to create a variable which is assigned to. I tried creating the logic a different way than this, but now am having a lot of issues with it so think this way may be better.
```
board.every((cell) =?
cell !== ''
);
```
 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

**Comment by RealWeeks** [comment]
I don't know who wrote that on the board, but Joel, my question to you is:

What is the question?

**Comment by jbuzzanco** [comment]
Antony wrote it this morning to try and help to explain the game logic to get started on it. I don't know what this is doing or why you would use it

``` js
board.every((cell) =?
cell !== ''
);
```

also what is after that I don't really understand with the array index of 0 , 1, 2, etc or how that works to get it working in my project, which I think I would have to understand what is before that in order to understand the if statement.

**Comment by neugierige** [comment]
Antony was demonstrating a way to check whether the board is empty by using the `.every` method: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

You absolutely do not _need_ to use this.

**Comment by neugierige** [comment]
The part that came after (`if (board[0] === 'x' && board[1] === 'x' && board[2] === 'x')`) was him demonstrating a way to check for wins in the game.

**Comment by raq929** [comment]
@jbuzzanco If this resolved the issue, please comment explaining the answer to your question in your own words, and close the issue.

**Comment by jbuzzanco** [comment]
So I still don't get it. I still am really confused. What is `cell` in 

``` js
board.every((cell) =>
cell !== ''
);
```

its not in the documentation from what i found so maybe it is more of a variable. Also how is the array index referencing the HTML boxes ? Maybe it would be better if someone would talk to me about it in person if someone thinks that is a good idea.

**Comment by raq929** [comment]
Every is a method that iterates through an array. It passes each element in the array to a callback function. In the callback above, Antony choose to call each element in the array cell. He could have chosen any name for that variable.

**Comment by jbuzzanco** [comment]
Ok so cell is a variable, but variables have to be defined. Where is `cell` defined?  Also for this part 

```
(if (board[0] === 'x' && board[1] === 'x' && board[2] === 'x'))
```

would it it be somewhere in the HTML like this for how it gets the location on the board? But it doesn't seem to be referencing html. Still don't really understand

**Comment by RealWeeks** [comment]
He didn't write that part of the code, defining board and cell would be something the developer would have to do at an earlier point.

**Comment by jbuzzanco** [comment]
Board was defined as an array with 9 empty indexes I thought. Cell I am not sure how it would get defined.

**Comment by RealWeeks** [comment]
Part of the project. That part is on you Joel, but think what a cell represents here.

**Comment by jbuzzanco** [comment]
It represents the individual part of the game board; one of 9 parts. So would that have to be referencing the HTML somehow? I don't know

**Comment by RealWeeks** [comment]
Correct, it is a reference to a cell in the gameboard.

**Comment by jbuzzanco** [comment]
I don't know how it can represent that gameboard box in the HTML after searching for it http://stackoverflow.com/questions/14845710/javascript-variable-access-in-html http://stackoverflow.com/questions/3452485/can-a-javascript-variable-be-used-in-plain-html

**Comment by neugierige** [comment]
Think back on previous lessons we have seen. How were we able to manipulate things in the DOM? How did we use variables to represent those objects?

**Comment by neugierige** [comment]
where are you right now?

**Comment by jbuzzanco** [comment]
by front lines

**Comment by raq929** [comment]
If this issue is resolved, please comment with how you resolved it and close the issue.

**Comment by BenGitsCode** [comment]
@jbuzzanco was this resolved ?

**Comment by jbuzzanco** [comment]
its not actually resolved. Still having trouble with check wins

**Comment by RealWeeks** [comment]
Joel, that is a separate issue, please close this one.  It seems that your other issue is being addressed here: https://github.com/ga-wdi-boston/game-project/issues/367

**Comment by jbuzzanco** [comment]
represent  index in html code with

``` html
data-index=0
data-index=1
data-index=2
```

all the way through the 9 spots
