### ISSUE TITLE
Game API - Questions on Update Functionality

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/game-project#347]
I have everything working up to the 'Update' game API functionality.  I have front end functionality that creates the game with a click event and API connection works.  I've been trying to now figure out how to update the created game via the API but am hitting a wall.

**Comment by RealWeeks** [comment]
Update corresponds to PATCH right? Sounds like you need a PATCH request

**Comment by rickdean** [comment]
I've been working on that...I'll keep going.

**Comment by RealWeeks** [comment]
@rickdean What do you have so far. What specifically are you struggling with? I'm trying to get you to narrow down your problem.

**Comment by raq929** [comment]
If you're hitting a wall, don't just keep going! Paste in your code so we can help. :)

**Comment by raq929** [comment]
Was this resolved? If yes, please tell us how you did it and close the issue.

**Comment by rickdean** [comment]
This is my code at the moment...  What I'm stuck on is how to 'kick off the game updates'.  I know it has to be initiated by an event (like the clicking of a box), and that was what I was hoping to achieve.  No linter errors but obviously not right....

const onUpdateGame = () => {
  event.preventDefault();
  api.updateGame()
    .done(ui.updateGameSuccess)
    .fail(ui.updateGameFailure);
};

const addHandlers = () => {
  $('.sign-up-form').on('submit', onSignUp);
  $('.sign-in-form').on('submit', onSignIn);
  $('.change-password-form').on('submit', onChangePassword);
  $('.sign-out-form').on('submit', onSignOut);
  $('.new-game').on('click', onCreateGame);
  $($boxes).on('click', onUpdateGame);

**Comment by RealWeeks** [comment]
well this is for sure incorrect `$($boxes).on('click', onUpdateGame);`

Look at that compared to this:

`$('.new-game').on('click', onCreateGame);`

**Comment by rickdean** [comment]
I'm getting closer.  At least now I get a '400 Bad Request' which is something....

**Comment by BenGitsCode** [comment]
@rickdean can you just add a comment with some details on the resolution?
