### ISSUE TITLE
reset/new game button

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/game-project#348]
going through API stuff with teammates, we've done the exact same code, but, my button will not reach the function (the first line of code to execute).  it doesn't even trigger a debugger.

**Comment by RealWeeks** [comment]
First, any linter errors?

Next, assuming those have been cleared up paste in the function.

**Comment by BenGitsCode** [comment]
Can you provide some code snippets? Namely the function in question and the html it's bound to.

**Comment by RealWeeks** [comment]
@BenGitsCode I think he should provide some code snippets, maybe paste in the function?

**Comment by RpRoderick** [comment]
<button type="button" class="btn btn-primary" id="reset">Reset</button>

**Comment by RpRoderick** [comment]
`<button type="button" class="btn btn-primary" id="reset">Reset</button>`

**Comment by RpRoderick** [comment]
``` js
const api = require('./api');
const ui = require('./ui');

const onCreateGame = function (event) {
  debugger;
  event.preventDefault();
  api.createGame()
    .then(ui.success)
    .catch(ui.failure);
};




const addHandlers = () => {
  $('#reset').on('click', onCreateGame);
};

module.exports = {
  addHandlers,

};
```

**Comment by RpRoderick** [comment]
``` js
const store = require('../store.js');


  const createGame = function () {
    $.ajax({
      url: store.host + '/games',
      method: 'POST',
      headers: {
        Authorization: 'Token token=' + store.user.token,
      },
      game: {}
    });
    };
```

**Comment by RealWeeks** [comment]
show me your document ready function and your html as well please

**Comment by RpRoderick** [comment]
``````
const store = require('../store.js');


  const createGame = function () {
    $.ajax({
      url: store.host + '/games',
      method: 'POST',
      headers: {
        Authorization: 'Token token=' + store.user.token,
      },
      game: {}
    });
    };```
``````

**Comment by RpRoderick** [comment]
that should be all

**Comment by RealWeeks** [comment]
Nope, need your document ready and html

**Comment by RpRoderick** [comment]
this is my auth index.js

```'use strict';

// user require with a reference to bundle the file and use it in this file
// var example = require('./example');

// use require without a reference to ensure a file is bundled
const authEvents = require('./auth/events');

$(() => {
  authEvents.addHandlers();
});```

**Comment by RpRoderick** [comment]
Oh, and only linter error is a forgotten debugger

**Comment by raq929** [comment]
It looks like you're adding the handlers for auth events, but your handlers for game related events are in a different file. You'll have to require that file in `index.js`, and execute the addHandlers there.

**Comment by neugierige** [comment]
@RpRoderick have you been able resolve this? please update

**Comment by RpRoderick** [comment]
ok, yes, index.js and requiring the proper file was the issue.  Raq929 was correct
