### ISSUE TITLE
Error after finishing ajax requests

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/game-project#35]
I just finished my 4 ajax requests. In my console I am getting this error now.

ERROR in ./assets/scripts/index.js
Module build failed: SyntaxError: /home/jeremiah/wdi/projects/temp2/tictactoe/assets/scripts/index.js: Assigning to rvalue (22:0)
20 | };
  21 | 

> 22 | $('.sign-up-submit') =  function(event) {
>      | ^
>   23 |   event.preventDefault();
>   24 |   let formData = new FormData(event.target);
>   25 |   $.ajax({

No idea what it means or how to fix, there is a carrot pointed to the $ representing jquery.

**Comment by MattB-GA-Boston** [comment]
Incorrect naming of fields - caused FormData to choke.

**Comment by jrhorn424** [comment]
The key part of this error message is the word "assigning". That tells me we need to look for assignment on the line that generated the error. Then we see that the function on the right gets assigned to... a return value. Oops! You can only assign values to declared variables, not to other values.
