### ISSUE TITLE
All of my local styling is gone

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#350]
Somehow all of my styling has disappeared from my local site. I have not touched the scss at all.

**Comment by raq929** [comment]
Fun! When this happened before, there was a syntax error in your code. Run grunt nag from your terminal and fix the errors. (Or look for it in the console.)

**Comment by jdaly04** [comment]
I was able to fix this by correcting syntax errors. I had an "else if" statement that was not checking for conditions!
