### ISSUE TITLE
Another problem with clicking on the Game board

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/game-project#352]
Now my problem is that the board only places X's and O's in one box.

**Comment by RealWeeks** [comment]
Can you post you code

**Comment by Sphilippe7** [comment]
```
let currentPlayer;
let count = 1;
//Game Board Positioning
let gameBoardArray = [["box", "box", "box"],["box", "box", "box"],["box", "box", "box"]];

$(".tl").click(function(){
  if (gameBoardArray[0][0] === "box") {
    if (count % 2 === 0) {
      currentPlayer = "Player1";
      $('.tl').text('x');
      gameBoardArray[0][0] = 'x';
    }
    else {
      currentPlayer = "Player2";
      $('.tl').text('o');
      gameBoardArray[0][0] = 'o';
    }
    count++;
  }
});

$(".tm").click(function(){
  if (gameBoardArray[0][1] === "box") {
    if (count % 2 === 0) {
      currentPlayer = "Player1";
      $('.tl').text('x');
      gameBoardArray[0][1] = 'x';
    }
    else {
      currentPlayer = "Player2";
      $('.tl').text('o');
      gameBoardArray[0][1] = 'o';
    }
    count++;
  }
});



const addXO = function (event) {
  event.preventDefault();
  if (count % 2 === 0){
    currentPlayer = "player 2";
}
  $(event.target).text('x');
  count++;
};
```

**Comment by RealWeeks** [comment]
So according to this line, this will always eval to true:

``` js
if (gameBoardArray[0][0] === "box") {
```

**Comment by RealWeeks** [comment]
every time it enters your function your array sets the gameboard, so it will always be

'let gameBoardArray = [["box", "box", "box"],["box", "box", "box"],["box", "box", "box"]];`

Every time this function is run

**Comment by RealWeeks** [comment]
also what does this line do `if (count % 2 === 0) {`

What does the `%` do, look it up. It may not be what you want

**Comment by Sphilippe7** [comment]
The % divides the count does it not? I figured I should keep count of the amount of turns. Should I get rid of it?

**Comment by RealWeeks** [comment]
Nope, look it up, it's called a `modulus`. There are a lot of things about this project you just kind of have to google to find out. We're trying to push you to be an independent coder by leading you to the answer instead of giving it to you.

**Comment by Sphilippe7** [comment]
I figured it out, Now I am on to the next step
