### ISSUE TITLE
Locallly, modal styling is not working

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#353]
I just went to confirm that my sign-up / sign-in / change password / sign-out modals are all still functioning properly and realized they are not functioning locally. The text is "invisible". When I highlight the entered text, it shows up, but I have no idea why it's not showing up properly. I have not touched scss or html, and I am not getting an error in the console.

**Comment by neugierige** [comment]
I'll come take a look. are you in the kitchen?

**Comment by neugierige** [comment]
you are not in the kitchen

**Comment by jdaly04** [comment]
I am by the FrontLines desk.

**Comment by neugierige** [comment]
please comment on what the fix was, and close if resolved

**Comment by jdaly04** [comment]
I had an issue where my body font-color was set to white, and because that was the only reference to font-color, it was cascading down to everything, including my modal button fonts.
