### ISSUE TITLE
Deployment fix - please leave open for now.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/game-project#355]
Make the following changes on your master branch and add `dependencies.js` to `gh-pages` rather than `vendor.bundle.js`.

```diff
diff --git a/.gitignore b/.gitignore
index 30b51df..ca4d28c 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,5 +1,6 @@
 tmp
 dist
+dependencies.js
 vendor.js
 specs.js
 *bundle.js
diff --git a/grunt/webpack.js b/grunt/webpack.js
index b79a5b8..f22c70c 100644
--- a/grunt/webpack.js
+++ b/grunt/webpack.js
@@ -17,7 +17,7 @@ module.exports = {
     },
 
     plugins: [
-      new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
+      new webpack.optimize.CommonsChunkPlugin('vendor', 'dependencies.js'),
       new webpack.ProvidePlugin({
         $: 'jquery',
         jQuery: 'jquery',
diff --git a/index.html b/index.html
index 4a30344..31d00b3 100644
--- a/index.html
+++ b/index.html
@@ -5,7 +5,7 @@
 
       <meta name="viewport" content="width=device-width, initial-scale=1">
 
-      <script src="vendor.bundle.js" type="text/javascript" charset="utf-8" defer></script>
+      <script src="dependencies.js" type="text/javascript" charset="utf-8" defer></script>
       <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
     </head>
     <body class="container-fluid">

```

**Comment by raq929** [comment]
People are now having similar issues with dependencies.js. I'm going to make a test case.

**Comment by raq929** [comment]
They were not commiting `dependcies.js` after running `grunt build`.

**Comment by sujkid** [comment]
Hi.. so I just did everything like what Antony said. and grunt build,
but my problem has not been resolved!
I still have errors in my even after the changes..

**Comment by raq929** [comment]
What are the errors? Did you add the files created after the build and commit them?

**Comment by sujkid** [comment]
Hi Rachel, the error is in #370 I mistakenly printed it here..

**Comment by ioncrash** [comment]
It looks like my deployment is not updating after I made some css adjustments.. should I expect a delay?

**Comment by raq929** [comment]
Answering for future cohorts, yes, there is often a delay after pushing to
gh-pages. Usually less than 5 minutes, sometimes much longer.

**Comment by jrhorn424** [comment]
Is this closable since `grunt deploy` is now a thing?

**Comment by gaand** [comment]
@jrhorn424 Yes.
