### ISSUE TITLE
Recurring ID issue

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/game-project#356]
On occasion, when I do a post to create a new game it gives me an id I've already had, not sure why. I've checked the issue against the game list, but I can't find an explanation.

**Comment by BenGitsCode** [comment]
Can you provide relevant code samples per [process](https://github.com/ga-wdi-boston/project-issue-tracker-guide#howtousetheissuetracker)?

**Comment by neugierige** [comment]
@treep78 have you made progress on this? is this still an issue?

**Comment by raq929** [comment]
If this this no longer an issue, please comment on what you did to fix it and close.

**Comment by treep78** [comment]
I resolved this issue with some help. I had forgotten that the game objects would be unordered so I was grabbing the last ID, but not the newest. I have since fixed it.
