### ISSUE TITLE
Broken Styles...Need for reset function.

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/game-project#357]
@RealWeeks and I couldn't figure it out earlier. Anyone else feel like taking a crack?

Problem:

Style sheet is clearly linked but can't be edited. No changes or over rides show up in dev tools or on the page.

**Comment by RealWeeks** [comment]
Woah, can't figure it out if not true. I can, but you should work on other things.  Styles after everything else.

**Comment by akadane87** [comment]
No disrespect brah! Need css for my reset function - dont care what it looks like but its requirement of the game, no? - just wanted to get it fixed before everyone leaves for the day. Will move on to api stuff in the mean time.

**Comment by RealWeeks** [comment]
your `.addClass()` works. I don't think you need CSS to work on the reset logic. I'm afraid you're falling down a rabbit hole, and I want you to avoid that.

**Comment by raq929** [comment]
What's the status of this issue?

**Comment by akadane87** [comment]
Now its only busted on deployment. Local works tho

**Comment by raq929** [comment]
See issue #355 for deployment.

**Comment by neugierige** [comment]
hey @akadane87, has this been resolved? can we close this now?

**Comment by akadane87** [comment]
Still not sure what happened back there but definitely hit issue #355 and started the deployment steps from scratch. Thanks all
