### ISSUE TITLE
Need help putting things in order

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/game-project#358]
I had help from people but I was not really understanding their methods. I googled a couple things and finally got to game logic to work on my own. Now I need help on going forward. I don't know whether I should make a new file for the API or work in the existing one I have in my auth folder. Also I would like someone to review my code because the first thing that appears on the board is "o" but it is recognized as Player 2 and "x" is Player 1

**Comment by RealWeeks** [comment]
I see this Stanley, I'm thinking of the best way to help

**Comment by RealWeeks** [comment]
@Sphilippe7 Ben is going to go over this with you

**Comment by Sphilippe7** [comment]
ok

**Comment by BenGitsCode** [comment]
We made some progress here and will touch base again shortly after today's end of day announcements.

**Comment by neugierige** [comment]
what's the status of this issue @Sphilippe7?

**Comment by neugierige** [comment]
hey @Sphilippe7 can we close this now?
