### ISSUE TITLE
[gitignore] - gh-pages-hosted site doesn't have css, javascript

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/game-project#36]
on branch gh-pages, i removed '*bundle.js' and 'vendor.js' from the gitignore file, added that file to stage, committed it, and pushed all of that using git push origin gh-pages. the hosted site lacks all css and javascript. 

i'm looking at http://apalmer0.github.io/tictactoe/index.html

in the console, the errors are:

```
http://apalmer0.github.io/tictactoe/vendor.bundle.js 
Failed to load resource: the server responded with a status of 404 (Not Found)
```

and 

```
http://apalmer0.github.io/tictactoe/bundle.js 
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by GA-MEB** [comment]
After you added and committed the altered `.gitignore` file, did you run `git status`?

**Comment by GA-MEB** [comment]
Taking something out of the `gitignore` tells Git that it can start watching those files, but you may not have actually committed them. That would explain why they aren't showing up.

**Comment by apalmer0** [comment]
Just tried again - 

re-introduced vendor.js/_bundle.js, 
added gitignore, 
committed change, 
removed vendor.js/_bundle.js, 
added gitignore
commited

git status says:

```
On branch gh-pages
nothing to commit, working directory clean

```

thoughts on what im missing?

**Comment by gaand** [comment]
I believe there's a build step for distribution.

**Comment by apalmer0** [comment]
sorry - is that step posted somewhere?

**Comment by apalmer0** [comment]
jason just came by - we ran 'grunt build' to update, then added/committed/pushed and it worked. thanks!
