### ISSUE TITLE
Having a hard time visually displaying the game statistics.

### ISSUE THREAD

**Issue by Bowers96** [ga-wdi-boston/game-project#360]
I'm not really sure how to go about this and need some help getting started with this. This is my last step to completing the basic requirements.

**Comment by raq929** [comment]
Cool. What statistics do you want to display? 
Basically, this requirement is checking that you can make a GET request to the server.

**Comment by Bowers96** [comment]
I would like to display the games one for the signed in user.

**Comment by BenGitsCode** [comment]
What have you tried so far @Bowers96

**Comment by Bowers96** [comment]
I have brainstormed what I would like to do and that is add to my existing JSON object a win counter as well as a games played counter and have that displayed on the webpage.

**Comment by raq929** [comment]
Alright. I would start by creating the win counter in the HTML. Next, figure out what API request you need to make to get the information you need.

**Comment by Bowers96** [comment]
I know I need a GET request to get a user's win count but how can I update it? I think I need a PATCH request but the only available PATCH request is for updating the password.

**Comment by RealWeeks** [comment]
Why do you want to update it?

**Comment by Bowers96** [comment]
The way I see it, every time a user wins a game I need to update the win count for that user.

**Comment by RealWeeks** [comment]
Read the API docs https://github.com/ga-wdi-boston/game-project-api I think you think you have to do something that you may not have to do (/ may not want / be able to).

**Comment by neugierige** [comment]
@Bowers96 is this ok to close??

**Comment by Bowers96** [comment]
Yes.
