### ISSUE TITLE
Issue with watch functions

### ISSUE THREAD

**Issue by kibs86** [ga-wdi-boston/game-project#361]
I'm trying to get the watchers working and running into some issues.  I've confirmed so far that I can create a game as Player 1 and join the game in another browser tab as Player 2.  Here are the steps I've gone through so far:

1. Copy resource-watcher-0.1.0.js to my project
2. Add the watcher object to my join success function
```
const joinGameSuccess = (data) => {
  app.game = data.game;
  $('.player2-message').text("Successfully joined");
  $('.player2-game').text("Game ID: " + app.game.id);
  
let gameWatcher = resourceWatcher.resourceWatcher(config.host + '/' + app.game.id + '/watch', {
        Authorization: 'Token token=' + store.user.token
  });

  gameWatcher.on('change', function (data) {
  console.log(data);
  if (data.game && data.game.cells) {
    const diff = changes => {
      let before = changes[0];
      let after = changes[1];
      for (let i = 0; i < after.length; i++) {
        if (before[i] !== after[i]) {
          return {
            index: i,
            value: after[i],
          };
        }
      }

      return { index: -1, value: '' };
    };

    let cell = diff(data.game.cells);
    $('#watch-index').val(cell.index);
    $('#watch-value').val(cell.value);
  } else if (data.timeout) { //not an error
    gameWatcher.close();
  }
});
```
Here's what I'm seeing in console log:
```
XHR finished loading: POST "https://aqueous-atoll-85096.herokuapp.com/sign-in".
8810

XHR finished loading: PATCH "https://aqueous-atoll-85096.herokuapp.com/games/8810".

GET https://aqueous-atoll-85096.herokuapp.com/8810/watch?token=BAhJIiVkM2E3NGUz…YWYxMWY0OTRjMWI1ZTVlMzQzNgY6BkVG--ebe4a9fddf014028ca37be40d25ba0305060151e 

an error has occurred with the stream Event {isTrusted: true, type: "error", target: EventSource, currentTarget: EventSource, eventPhase: 2…}bubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: EventSourceonerror: (e)onmessage: (e)onopen: nullreadyState: 2url: "https://aqueous-atoll-85096.herokuapp.com/8810/watch?token=BAhJIiVkM2E3NGUzZWZiYzlkYWYxMWY0OTRjMWI1ZTVlMzQzNgY6BkVG--ebe4a9fddf014028ca37be40d25ba0305060151e"withCredentials: false__proto__: EventSourcedefaultPrevented: falseeventPhase: 0isTrusted: truepath: Array[0]returnValue: truesrcElement: EventSourcetarget: EventSourcetimeStamp: 41465.535type: "error"__proto__: Event
```

The error message isn't very helpful.  All I can tell is the GET failed and then there was some sort of error.  I'm not sure if I'm even heading in the right direction with this.  Any guidance would be greatly appreciated!

**Comment by RealWeeks** [comment]
what is `config.host`?

**Comment by RealWeeks** [comment]
So I'm reading the API docs and see this line:

``` js
let gameWatcher = resourceWatcher('<server>/games/:id/watch', {
      Authorization: 'Token token=<token>'[,
      timeout: <timeout>]
});
```

The docs describe this as: `This function takes two parameters, the watch url and a configuration object which must contain the Authorization token, and may contain an optional timeout in seconds`

**Comment by kibs86** [comment]
It just stores the host name for the API

```
const config = {
  //host: 'http://localhost:4741',
  host: 'https://aqueous-atoll-85096.herokuapp.com',
};
```

**Comment by RealWeeks** [comment]
First thing I'm thinking is let's construct this url first and go from there so this is what I see in your code:
 `config.host + '/' + app.game.id + '/watch'`

and I compare that to the API docs

`<server>/games/:id/watch'`

**Comment by RealWeeks** [comment]
Try that, and tell me what happens.  (Let me know if I'm not making any sense too).

**Comment by kibs86** [comment]
Ah, ok...I don't have the /games piece.  I'll give that a shot!

**Comment by kibs86** [comment]
Now I'm getting an object back as expected!  Is the gameWatcher.on code provided just a template that we're expected to modify to work for our environment?

**Comment by RealWeeks** [comment]
Yup. I'm unsure of the extent of the modification necessary but it's yours to use.

**Comment by RealWeeks** [comment]
@kibs86 Can you close this since we resolved it?

**Comment by kibs86** [comment]
Thank you for your help!
