### ISSUE TITLE
Reversing commits - page is not functioning at all

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/game-project#362]
I really need help, I was working with another developer and we added come changes and my page is not working at all. Accidentally committed these changes when trying to apply the deploy changes. Is it possible to just go back to an older commit?

**Comment by matthewgsommers** [comment]
Also none of the errors brought up in the console are referencing pages I edited...

**Comment by raq929** [comment]
Where are you?

**Comment by matthewgsommers** [comment]
Class room 6

**Comment by matthewgsommers** [comment]
Rachel helped me - I thought some mysterious code was making my page explode while in reality it was the deploy update.
