### ISSUE TITLE
checkWinner not working for row

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#363]
I have created a checkWinner function and have put in a debugger, which is not being reached based on what I'm seeing in my console. 

Here is my JS code for checking if "X" has won in the top row only. I wanted to first solve this before moving on to other rows, columns, etc.:

```js

let board = ['', '', '', '', '', '', '', '', ''];
let player = '';
//let checkWin= function() {



let checkWin = function () {
 for (let i = 0; i < board.length; i++) {
   if (board.text[0] === "X" && board.text[1] === "X" && board.text[2] === "X") {
      console.log("x won");
    }
  }
};
```

Here is my event handler for clicking on a square:
```js
const onClickSq = function () {
  gameUi.board[0] = 'X';
  console.log(gameUi.player);
  if(gameUi.player === '' || gameUi.player === '1') {
    $(this).text('X');
    gameUi.player = "2";
  } else {
   $(this).text('O');
    gameUi.board[0] = 'x';
    gameUi.player = '1';
  }
};

```

I have exported game.js and also required it within my events.js file.

**Comment by jdaly04** [comment]
Rachel is helping me right now with this!!

**Comment by jbuzzanco** [comment]
also am having trouble with the checking the win conditions

**Comment by raq929** [comment]
@jbuzzanco if you're still having trouble, can you open an issue with your specific problem?

@jdaly04 Can you explain how this problem was actually a different problem and how you resolved it, and close the issue?

**Comment by jdaly04** [comment]
My problem was in my  event handler. I only had it set up to recognize the first square of my board game. What I did was create an array that refers to each individual square id (which is how I refer to the squares in my html). My event handler now looks like this:

``` js
// BEGIN GAME EVENTS -- Need to move to different file!
let sqIds = ["sq1", "sq2", "sq3", "sq4", "sq5", "sq6", "sq7", "sq8", "sq9"];
const onClickSq = function () {
  console.log(gameUi.player);
  if(gameUi.player === '' || gameUi.player === '1') {
    $(this).text('X');
    console.log($(this).attr('id'));
    gameUi.board[sqIds.indexOf($(this).attr('id'))] = 'X';
    gameUi.player = "2";
  } else {
   $(this).text('O');
    gameUi.board[0] = 'x';
    gameUi.player = '1';
  }
  gameUi.checkWin();
  debugger;
};
```
