### ISSUE TITLE
Struggling With API

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/game-project#364]
I have my index, show, and create functions all working. I can successfully create and show games but all of my arrays are empty. I think it is because I don't know how to successfully create the update function

**Comment by raq929** [comment]
What do you mean by 'all of my arrays are empty'?

**Comment by akradin** [comment]
linked function, still get error 404

**Comment by RealWeeks** [comment]
@raq929 asked my question `What do you mean by 'all of my arrays are empty?` that's too vague, can you be more specific. What arrays, where, what function?

**Comment by raq929** [comment]
@akradin can you post the relevant code? 
@RealWeeks He's trying to make a PATCH request to update the game board on the server.

**Comment by akradin** [comment]
Yup! sorry didn't see this.
I will post all the code bear with me.

We are sure this is a requirement, yeah? Asking because multiple people have said multiple things about this being required

**Comment by akradin** [comment]
API code for PATCH request

```
const updateGame = function(){
  return $.ajax({
    url: config.host + '/games/',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token,
    },
  });
};
```

turn PATCH request into a function to see if it is successful or an error

```
const onUpdateGame = function(e){
  e.preventDefault();
  game_api.updateGame()
    .then(game_ui.success)
    .catch(game_ui.failure);

};
```

and then I have a button in my UI that is supposed to output the console.log from the success function which is the same one from class

```
const success = (data) => {
  console.log(data);
};
```

**Comment by raq929** [comment]
This is required. 
Use AJAX for interacting with a provided API. Specifically, your app must:

Visually display the results of retrieving game statistics, such as total games won by a user. (READ)
Create new games on the server. (CREATE)
Update a game by storing new moves. (UPDATE)

**Comment by raq929** [comment]
Right now you're not sending any data with your PATCH request, so the server won't be able to update the game and will give you the 404.

**Comment by raq929** [comment]
What's your status on this?

**Comment by akradin** [comment]
Fix for this was creating index, value, and over and then pass these values into my relevant API functions which are onUpdateGame and updateGame
