### ISSUE TITLE
Deploying Issue

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/game-project#365]
My page is functioning properly locally & I've implemented the new deploy changes. All of my work has been done on gh-pages - I was instructed that if I git push origin gh-pages that it should deploy correctly but the page hasnt changed after several minutes.

**Comment by raq929** [comment]
I think we resolved this, if yes, comment with what you did and close the issue.

**Comment by matthewgsommers** [comment]
My page still isnt being deployed with the updates.

**Comment by RealWeeks** [comment]
Did you take a look at this: https://github.com/ga-wdi-boston/game-project/issues/355 ?

**Comment by matthewgsommers** [comment]
Issue resolved: I wasnt adding the changes from Antony's fix and I preserved history in master, deleted gh-pages, and then went through the process again.
