### ISSUE TITLE
Can't get win outcomes function to work.

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#367]
Stuck on it, debugger isn't going into if statement.

**Comment by BenGitsCode** [comment]
@jbuzzanco can you post the relevant code?

**Comment by jbuzzanco** [comment]
'use strict';

//file requirements
const api = require('./api');
const ui = require('./ui');
const store = require('../store');
const getFormFields = require('../../../lib/get-form-fields');

const addHandlers = function() {
$('.box').on('click', function(){
    store.turn = store.turn === "x"?"o":"x";
    $(this).html(store.turn);
  });
};

``` js
let winner = "x" || "o";
let board = ['','','','','','','','','',]

let checkWins = function () {
  debugger;
  if (board[0] === board[1] && board[1] === board[2]) {
    'x' === winner;
    console.log
  }
```

**Comment by BenGitsCode** [comment]
Ok so if that debugger isn't firing, we're never getting to checkWins. Where is that function called in your code?

**Comment by BenGitsCode** [comment]
Also have you taken a look at this similar issue? #363

**Comment by jbuzzanco** [comment]
so it would have to be 

```
module.exports = {
  addHandlers,
  checkWins,
};
```

also I have looked at that issue as well

**Comment by jdaly04** [comment]
Have you required the exact file name where you function is declared in your event handler file? Might be worth double checking that.

**Comment by BenGitsCode** [comment]
That's exporting checkWins for use in another file. Where is the function `checkWins()` being invoked?

**Comment by jbuzzanco** [comment]
I invoked the function and it's still not getting done.

``` js
let checkWins = function () {
  debugger;
  if (board[0] === board[1] && board[1] === board[2]) {
    'x' === winner;
    console.log
  }
  checkWins();
};
```

**Comment by raq929** [comment]
You are invoking the function within itself. That's not going to work.
When do you want to check if someone has won?

**Comment by jbuzzanco** [comment]
on click. so 

``` js
const addHandlers = function() {
$('.box').on('click', function(){
    store.turn = store.turn === "x"?"o":"x";
    $(this).html(store.turn);
  });
$('.box').on('click', checkWins);
};
```

however , this if statement is not right I believe. And devtools is not loading.

**Comment by raq929** [comment]
You're already inside the click handler, so you don't need to create another click handler inside it you just need to run the checkWins function.

``` js
const addHandlers = function() {
$('.box').on('click', function(){
    store.turn = store.turn === "x"?"o":"x";
    $(this).html(store.turn);
  });
 checkWins()
};
```

The above assumes that checkWins is in the same file. If it's not, you'll need to import it using require, and do `<whatever you named it>.checkWins()`

**Comment by jbuzzanco** [comment]
I'm not really sure what that meant but yes checkWins is in the same file. Now when I used that code it broke my gameboard so that it's not even showing up

**Comment by neugierige** [comment]
is your function still the code you pasted most recently? 

``` js
let checkWins = function () {
  debugger;
  if (board[0] === board[1] && board[1] === board[2]) {
    'x' === winner;
    console.log
  }
  checkWins();
};
```

if so, as you can see, the function calls itself, which would make it run an eternity

**Comment by jbuzzanco** [comment]
I also tried this after having other classmates llook at it but it's still not working

``` js
let checkWins = function() {
 if (board[0] === board[1] && board[2] === board[0] && !!board[0]) {
   console.log(turn + " Wins");
 }
};
```

**Comment by neugierige** [comment]
what do you mean by "not working"? is this function getting called at all? check with debugger or a console.log

**Comment by neugierige** [comment]
also, are you sure `!!board[0]` is doing what you intended?

**Comment by jbuzzanco** [comment]
checking array board by

``` js
let checkWins = function() {
  console.log(board)
  console.log(board[0] === board[1])
  console.log(board[2] === board[0])
  console.log(!!board[0])
 if (board[0] !== '' && board[0] === board[1] && board[2] === board[0]) {
   console.log(store.turn + " Wins");
 }
};
```
