### ISSUE TITLE
Trying to deploy has stopped my original master branch from working 

### ISSUE THREAD

**Issue by Naki21** [ga-wdi-boston/game-project#368]
I tried to follow the new deployment issue as written. I eventually got something to deploy but it was different than the last game i had working. I tried running it locally and now my game isn't functioning like it was before deployment. I don't know what went wrong. I made the changed to my master branch like the instructions said and then added dependencies.js to gh-pages. help please!

**Comment by RealWeeks** [comment]
Bro, chillax. It's all gone be okay and work fine. Help me help you what happened. Be descriptive. if you have the exact commands or console output that would be helpful too.

**Comment by raq929** [comment]
I took a look at this. We started stepping back through the commit history on master, but have not yet found where the problem was.

**Comment by Naki21** [comment]
Problem solved. Definitely had to do with my own code........
