### ISSUE TITLE
Locally run server module files not being found randomly. Refresh of page fixes it.

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/game-project#369]
When running a local server sometimes require'd (e.g. const require = require('./my_module') ) modules are not found. I just want to make sure that this problem won't be happening when deployed on GH pages randomly as well. So far I have tried refreshing my GitHub page a bunch to see if I can get the error to repeat when deployed but I cannot. 

The exact error I get locally is:
```
Uncaught Error: Cannot find module "./game-ui"
```

As I said, a page refresh usually takes care of the issue and everything works fine on next load. It is not always the same module. Should I be worried about this issue or is it potentially some quirk of webpack, maybe?

**Comment by raq929** [comment]
Inconsistent errors are the best errors! D:
This might be an issue with the local server. Have you tried shutting it down and spinning it up again?

**Comment by neugierige** [comment]
@joaufi what's the status on this issue?

**Comment by joaufi** [comment]
It seems reloading the local server did the trick. Thanks !
