### ISSUE TITLE
Unable to push to gh pages due to preexisting content

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/game-project#37]
Error: 

~/wdi/projects/jentictactoe (gh-pages)$ git push origin gh-pages
To git@github.com:jenweber/jentictactoe.git
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'git@github.com:jenweber/jentictactoe.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/jentictactoe (gh-pages)$     git push --set-upstream origin gh-pages
To git@github.com:jenweber/jentictactoe.git
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'git@github.com:jenweber/jentictactoe.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Issue Description:
I created a remote gh-pages about a week ago when I started working on this project. I just now updated my local gh-pages with my local master. Then when I tried to push my newly-updated local gh-pages to remote gh-pages, I got this error. I tried pushing from my local master to remote gh-pages and that didn't work either. I'm afraid to tangle it up further. Suggestions? How can I push to gh-pages?

**Comment by jrhorn424** [comment]
What was the resolution here? And what was the root cause?

**Comment by jenweber** [comment]
The resolution was a force push. I'm unsure of the root cause, but I suspect that I must have done something weird with the gh-pages remote repo last weekend in an attempt to get it to work with my css. I tried a ton of different things on my own before I got your message about gitignore.

**Comment by jrhorn424** [comment]
Thanks, @jenweber!
