### ISSUE TITLE
Error in vendor.bundle.js file

### ISSUE THREAD

**Issue by sujkid** [ga-wdi-boston/game-project#370]
Out of the blue, I have about 53 issues new issues in my project, all of them errors and warnings in my vendor.bundle.js file. 
All of the  errors are: 'missing "use strict" statement'.
I just did git status, and it shows that my vendor.bundle.js file has been modified, but I haven't touched it!  I haven't grunt build since last night either.

**Comment by raq929** [comment]
Please see #355

**Comment by neugierige** [comment]
@sujkid have you been able to update this? please close if this is resolved

**Comment by sujkid** [comment]
I haven't Lu, still figuring out #355

**Comment by neugierige** [comment]
what are you having trouble with?

**Comment by BenGitsCode** [comment]
@sujkid did you see my comment in the projects channel. I'm almost positive that's precisely the issue you're having.

**Comment by sujkid** [comment]
Hi Lu, Ben, so I'm running grunt build and making changes that Ben said in the project channel.
But Rachel just helped me figure out where to make these changes!!

**Comment by neugierige** [comment]
great, don't forget to say what you did, and close the issue

**Comment by sujkid** [comment]
Hi.. so I just did everything like what Antony said. and grunt build,
but my problem has not been resolved!
I still have errors the same even after the changes..

**Comment by BenGitsCode** [comment]
@sujkid can you paste the following for me:

In master branch, your `.gitignore` `grunt/webpack.js` and the head of your html

Same in gh-pages branch

**Comment by neugierige** [comment]
Suja, you need to be more specific. What errors are you having?

**Comment by sujkid** [comment]
ok great! so after the latest deployment, i lost all my changes in the branch i was working on!

**Comment by sujkid** [comment]
let me switch branches Ben.. just a sec

**Comment by sujkid** [comment]
master branch, .gitignore.js

tmp
dist
dependencies.js

# vendor.js

specs.js

# *bundle.js

_SpecRunner.html
*.woff2
*.woff
*.svg
*.ttf
*.eot

# Created by https://www.gitignore.io/api/node,osx,linux,windows,ruby,node,rails,express,ember

### Node

# Logs

logs
_.log
npm-debug.log_

# Runtime data

pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover

lib-cov

# Coverage directory used by tools like istanbul

coverage

# nyc test coverage

.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)

.grunt

# node-waf configuration

.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)

build/Release

# Dependency directories

node_modules
jspm_packages

# Optional npm cache directory

.npm

# Optional eslint cache

.eslintcache

# Optional REPL history

.node_repl_history

### OSX

*.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r

Icon

# Thumbnails

._*

# Files that might appear in the root of a volume

.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share

.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk

### Linux

*~

# temporary files which can be created if a process still has a handle open of a deleted file

.fuse_hidden*

# KDE directory preferences

.directory

# Linux trash folder which might appear on any partition or disk

.Trash-*

### Windows

# Windows image file caches

Thumbs.db
ehthumbs.db

# Folder config file

Desktop.ini

# Recycle Bin used on file shares

$RECYCLE.BIN/

# Windows Installer files

*.cab
*.msi
*.msm
*.msp

# Windows shortcuts

*.lnk

### Ruby

*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.

# .env

## Specific to RubyMotion:

.dat*
.repl_history
build/
*.bridgesupport
build-iPhoneOS/
build-iPhoneSimulator/

## Specific to RubyMotion (use of CocoaPods):

#

# We recommend against adding the Pods directory to your .gitignore. However

# you should judge for yourself, the pros and cons are mentioned at:

# https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

#

# vendor/Pods/

## Documentation cache and generated files:

/.yardoc/
/_yardoc/
/doc/
/rdoc/

## Environment normalization:

/.bundle/
/vendor/bundle
/lib/bundler/man/

# for a library or gem, you might want to ignore these files since the code is

# intended to run in multiple environments; otherwise, check them in:

# Gemfile.lock

# .ruby-version

# .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:

.rvmrc

### Node

# Logs

logs
_.log
npm-debug.log_

# Runtime data

pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover

lib-cov

# Coverage directory used by tools like istanbul

coverage

# nyc test coverage

.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)

.grunt

# node-waf configuration

.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)

build/Release

# Dependency directories

node_modules
jspm_packages

# Optional npm cache directory

.npm

# Optional eslint cache

.eslintcache

# Optional REPL history

.node_repl_history

### Rails

_.rbc
capybara-_.html
.rspec
/log
/tmp
/db/_.sqlite3
/db/_.sqlite3-journal
/public/system
/coverage/
/spec/tmp
*_.orig
rerun.txt
pickle-email-_.html

# TODO Comment out this rule if you are OK with secrets being uploaded to the repo

config/initializers/secret_token.rb

# Only include if you have production secrets in this file, which is no longer a Rails default

# config/secrets.yml

# dotenv

# TODO Comment out this rule if environment variables can be committed

.env

## Environment normalization:

/.bundle
/vendor/bundle

# these should all be checked in to normalize the environment:

# Gemfile.lock, .ruby-version, .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:

.rvmrc

# if using bower-rails ignore default bower_components path bower.json files

/vendor/assets/bower_components
*.bowerrc
bower.json

# Ignore pow environment settings

.powenv

# Ignore Byebug command history file.

.byebug_history

#!! ERROR: express is undefined. Use list command to see defined gitignore types !!#

### Ember

# see https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/gitignore

# compiled output

/dist
/tmp

# dependencies

/node_modules
/bower_components

# misc

/.sass-cache
/connect.lock
/coverage/*
/libpeerconnection.log
npm-debug.log
testem.log

**Comment by sujkid** [comment]
In master, grunt/webpack.js

```
'use strict';

let webpack = require('webpack');
let path = require('path');

module.exports = {
  options: {
    entry: {
      bundle: './index.js',
      specs: './spec/_all.js',
      vendor: ['jquery', 'bootstrap-sass'],
    },

    output: {
      path: './',
      filename: '[name].js',
    },

    plugins: [
      new webpack.optimize.CommonsChunkPlugin('vendor', 'dependencies.js'),
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery',
      }),
    ],

    module: {
      loaders: [
        {
          test: /\.js$/,
          exclude: /(node_modules|bower_components)/,
          loader: 'babel',
          query: {
            presets: ['es2015'],
          },
        },
        {
          test: /\.css/,
          loader: 'style!css',
          includePaths: [path.resolve(__dirname, './node_modules')],
        },
        {
          test: /\.scss/,
          loader: 'style!css!sass',
          includePaths: [path.resolve(__dirname, './node_modules')],
        },
        {
          test: /\.woff[\d]?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          loader: 'url-loader?limit=10000&mimetype=application/font-woff',
        },
        {
          test: /\.(ttf|eot|svg|png|jpg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          loader: 'file-loader',
        },
        {
          test: /\.(hbs|handlebars)$/,
          loader: 'handlebars-loader',
        },
        {
          test: /\.html\.(hbs|handlebars)$/,
          loader: 'handlebars-loader!html',
        },
      ],
    },

    stats: {
      colors: true,
      modules: true,
      reasons: true,
    },
  },

  build: {
    failOnError: true,
    watch: false,
    keepalive: false,
  },
};
```

**Comment by sujkid** [comment]
in gh-pages, .gitignore.js

```
tmp
dist
# dependencies.js
# vendor.js
specs.js
# *bundle.js
_SpecRunner.html
*.woff2
*.woff
*.svg
*.ttf
*.eot

# Created by https://www.gitignore.io/api/node,osx,linux,windows,ruby,node,rails,express,ember

### Node ###
# Logs
logs
*.log
npm-debug.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules
jspm_packages

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history


### OSX ###
*.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon


# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk


### Linux ###
*~

# temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*

# KDE directory preferences
.directory

# Linux trash folder which might appear on any partition or disk
.Trash-*


### Windows ###
# Windows image file caches
Thumbs.db
ehthumbs.db

# Folder config file
Desktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msm
*.msp

# Windows shortcuts
*.lnk


### Ruby ###
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.
# .env

## Specific to RubyMotion:
.dat*
.repl_history
build/
*.bridgesupport
build-iPhoneOS/
build-iPhoneSimulator/

## Specific to RubyMotion (use of CocoaPods):
#
# We recommend against adding the Pods directory to your .gitignore. However
# you should judge for yourself, the pros and cons are mentioned at:
# https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
#
# vendor/Pods/

## Documentation cache and generated files:
/.yardoc/
/_yardoc/
/doc/
/rdoc/

## Environment normalization:
/.bundle/
/vendor/bundle
/lib/bundler/man/

# for a library or gem, you might want to ignore these files since the code is
# intended to run in multiple environments; otherwise, check them in:
# Gemfile.lock
# .ruby-version
# .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:
.rvmrc


### Node ###
# Logs
logs
*.log
npm-debug.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules
jspm_packages

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history


### Rails ###
*.rbc
capybara-*.html
.rspec
/log
/tmp
/db/*.sqlite3
/db/*.sqlite3-journal
/public/system
/coverage/
/spec/tmp
**.orig
rerun.txt
pickle-email-*.html

# TODO Comment out this rule if you are OK with secrets being uploaded to the repo
config/initializers/secret_token.rb

# Only include if you have production secrets in this file, which is no longer a Rails default
# config/secrets.yml

# dotenv
# TODO Comment out this rule if environment variables can be committed
.env

## Environment normalization:
/.bundle
/vendor/bundle

# these should all be checked in to normalize the environment:
# Gemfile.lock, .ruby-version, .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:
.rvmrc

# if using bower-rails ignore default bower_components path bower.json files
/vendor/assets/bower_components
*.bowerrc
bower.json

# Ignore pow environment settings
.powenv

# Ignore Byebug command history file.
.byebug_history


#!! ERROR: express is undefined. Use list command to see defined gitignore types !!#

### Ember ###
# see https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/gitignore
# compiled output
/dist
/tmp

# dependencies
/node_modules
/bower_components

# misc
/.sass-cache
/connect.lock
/coverage/*
/libpeerconnection.log
npm-debug.log
testem.log
```

**Comment by sujkid** [comment]
in gh-pages, grunt/webpack.js

'use strict';

let webpack = require('webpack');
let path = require('path');

module.exports = {
  options: {
    entry: {
      bundle: './index.js',
      specs: './spec/_all.js',
      vendor: ['jquery', 'bootstrap-sass'],
    },

```
output: {
  path: './',
  filename: '[name].js',
},

plugins: [
  new webpack.optimize.CommonsChunkPlugin('vendor', 'dependencies.js'),
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    'window.jQuery': 'jquery',
  }),
],

module: {
  loaders: [
    {
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel',
      query: {
        presets: ['es2015'],
      },
    },
    {
      test: /\.css/,
      loader: 'style!css',
      includePaths: [path.resolve(__dirname, './node_modules')],
    },
    {
      test: /\.scss/,
      loader: 'style!css!sass',
      includePaths: [path.resolve(__dirname, './node_modules')],
    },
    {
      test: /\.woff[\d]?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url-loader?limit=10000&mimetype=application/font-woff',
    },
    {
      test: /\.(ttf|eot|svg|png|jpg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'file-loader',
    },
    {
      test: /\.(hbs|handlebars)$/,
      loader: 'handlebars-loader',
    },
    {
      test: /\.html\.(hbs|handlebars)$/,
      loader: 'handlebars-loader!html',
    },
  ],
},

stats: {
  colors: true,
  modules: true,
  reasons: true,
},
```

  },

  build: {
    failOnError: true,
    watch: false,
    keepalive: false,
  },
};

**Comment by sujkid** [comment]
i dont know why it printed out so weird

**Comment by gaand** [comment]
You don't need vendor.bundle.js anymore.

**Comment by sujkid** [comment]
should i delete that file from  my project?

**Comment by gaand** [comment]
`git rm vendor.bundle.js` On the `gh-pages` branch.

**Comment by sujkid** [comment]
Thanks Antony

**Comment by sujkid** [comment]
great! looks good now..
Thanks!

**Comment by neugierige** [comment]
@sujkid please remember to close the issue

**Comment by sujkid** [comment]
I did everything in #355 and deleted the vendor.bundle.js file
