### ISSUE TITLE
Visualizing statistics

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/game-project#374]
I'm having a hard time completing the AJAX requirements, specifically the requirement about visually displaying statistics for the user. I'm currently attempting to display how many games the user has played. 

In my index.html I have the following:
//This line is used to create a button which, when clicked, should display the number of games played:
<button class="getStats" type="button">Click Here to Get stats</button>
// This is the div used contain the amount of games played:
<div class="game-data"></div>

In my 'assets/scripts/index.js I have the following JQuery, which is targeting 'getStats' and pointing towards 'getGame' when clicked:
$('.getStats').on('click', getGame);

In 'assests/scripts/game/events.js' I have the following, which should be pointing towards 'ui.getGameSuccess' when correctly completed. 
const onGetGame = function (event) {
    event.preventDefault();
    let data = getFormFields(event.target);
    api.getGame(data)
    .done(ui.getGameSuccess)
    .fail(ui.fail);
  };

In 'assets/scripts/game/ui.js' I have the following, which should be inputing the game data into the div tag I made in my HTML to hold the game info. 

const getGameSuccess = function(data){
  $('.game-data').text('You have played ' + data.games.length + ' games!');
};

When I attempt to use the 'getStats' button in my HTML, my developer tool stops at the following line (within 'Jquery.js', which is a file that I have not touched at all): 

	handleObj.handler ).apply( matched.elem, args );

So needless to say I'm a bit confused.

**Comment by matthewgsommers** [comment]
I'm pretty sure that the two latter steps (onGetGame -> getGameSuccess) are correct, so in my mind that implies that the disconnect is somewhere between the click event in 'index.js' and 'onGetGame' in events.js. 

I've been attempting to use the debugger to track progress but the error I mentioned above has been consistent.

**Comment by gaand** [comment]
Please post the html for the div you're expecting to set with

``` js
const getGameSuccess = function (data) {
  $('.game-data').text('You have played ' + data.games.length + ' games!');
};
```

**Comment by matthewgsommers** [comment]
< div class="game-data"></div > 

I had to add the spaces next to the greater and less than symbols at the start and end of the lines because the code wasnt showing up in the text box - they arnt there in the actual code.

**Comment by raq929** [comment]
Are you sure getGameSuccess is firing? If you out a debugger in it, does it get to that point, or does the error occur earlier?

**Comment by neugierige** [comment]
@callmelife what's the status of this issue? can we close?

**Comment by matthewgsommers** [comment]
This issue is still open. I'm having a hard time figuring out where the issue associated with displaying the statistics is. 

I just tried Rachel's suggestion to put a debugger in getGameSuccess and the error occurred in a different file that I havent touched. 

Is anyone available for a 1 on 1 today? I could use some general advice on API.
