### ISSUE TITLE
Can't turn click events back on after winCheck goes through

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/game-project#379]
```   }  winCheck();
    if (world.ttt.gameOver) {
      $('td').off('click');
 console.log('you win');
    }
};

const onResetBoard = function () {
  $('td').html('');


//So, I need to turn $('td').off() (from line 92) back on HERE when I press reset.  I can't seem to do that
//.on does not work!
};
```

**Comment by raq929** [comment]
I would think about how you turned them 'on' in the first place. :)

**Comment by RpRoderick** [comment]
ARGH! I'm going to sleep but THIS ISN'T OVER!  I will solve the mystery of the clicks! I tried your solution.  Didn't work.  Actually when I comment out all relevant JS for my don't click anymore ()'s, they still turn off! How is that even possible?! I'll continue trying different solutions...for...the clicks...maybe we can go over it again?

**Comment by raq929** [comment]
I can take a look during 1:1s tomorrow.

**Comment by RpRoderick** [comment]
So, fixed it.  Turns out that .one as a jquery command isn't easy to use.  Using .one should be the same as using .on/.off, that's the whole point, however, turning the click events back on after .one has fired doesn't work the same as .on/.off, even though it should.  In summary, only use .one if you don't have to turn click events back on, i.e. if the event only needs to fire ONCE.  otherwise, use .off.
