### ISSUE TITLE
[JS] x's and o's not alternating correctly

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#385]
In my game, I've been trying to use different jQuery methods to try and get the boxes click on click using a .off method, .one method, .on method, etc as well as referencing with different HTML class names to try and get it to work and alternate x's to o's properly. I have gotten 'one step forward two steps back' with experimenting with different methods and have gotten further behind from trying to do this, as far as working progress with the game goes. I don't know why I am getting a bug where on the first game, it plays with only x's. Then the next, it alternates x's to only o's. 
I did have it working before to click x's and o's. I went back to that commit. In that commit, I wouldn't be able to click the same spot in the game board on the next spot. So i tried to fix that with .on, referencing the html box so it would work with on click. That didn't work. So I fixed that It can click on the same point upon the reset button, but now it is not alternating x's and o's correctly as I said earlier and I don't know why. What is causing this behaviour?

here is some relevant code in JS file
```js
let boxClick = function(){
    console.log('click');
    if (store.turn === "x"){
       store.turn = "o";
    } else {
       store.turn = "x";
    }

    $(this).html(store.turn);
    // $(this).off('click');
    // turns div's value to first click value
    // change board array to reflect changes in HTML
    store.win = store.win === ("x" && "x" && "x") || ("o" && "o" && "o");
    let index = $(this).data('index');
    // find the index of the box clicked --jQuery to reference the data-index in html
    // set board array of that index to store.turn
    boardArray[index] = store.turn;
    checkWins();
};


const reset = function(){
    boardArray = ['','','','','','','','',''];
    $.each($('.box'), function(index, element) {
        $(element).html('');
        $(element).one('click', boxClick);
      } ) ;
    $('.tic-tac-toe-board').show();
};

const addHandlers = function() {
  $('.box').one('click', boxClick);
  $('.reset').on('click', reset);
};

module.exports = {
  addHandlers,
  checkWins,
  reset

};
```

**Comment by raq929** [comment]
As I mentioned the other day, I think you need to figure out what `store.turn` is at various points in your code. Console log it. Is it changing when you expect it to? Do you have other code that affects it? Like perhaps in your reset button.

I don't think the 'two steps back' attitude is going to help you. We fixed a problem together the other day, which exposed or created a new problem. That's progress, and a new problem to work on. I know it may not feel like it, but new errors are a good thing!

**Comment by jbuzzanco** [comment]
Okay, I tried `console.log(store.turn);` after every `store.turn` in the `boxClick` function. I get in the console after one click on the first game:

```
events.js:73 x
2016-11-17 19:32:45.029 events.js:79 x
2016-11-17 19:32:45.029 events.js:83 x
2016-11-17 19:32:45.031 events.js:73 o
2016-11-17 19:32:45.032 events.js:79 o
2016-11-17 19:32:45.032 events.js:83 o
```

so this must mean store.turn is 6 values when it should only be one. However I defined it as only one as x on the first click and o as the second click here.  Is it changing in reset? However store.turn only explicitly changes changing as store.turn is only stated in boxClick function which is called back in reset function. 

``` js
if (store.turn === "x"){
       store.turn = "o";
    } else {
       store.turn = "x";
    }
```

Also good news , now at this point it is alternating x's and o's on the second time now, not always starting on x though. It wasn't doing that before. 😄

**Comment by raq929** [comment]
I'm wondering if maybe the click handler is firing twice. 
How many console logs did you have?

**Comment by raq929** [comment]
I think your reset function might need to turn off click handlers on every box before resetting them.

**Comment by jbuzzanco** [comment]
Hmm. different result for adding the .off method on the box. Its _almost_ what we want now. I had 6 console logs before upon one click in the first game. Still do now as I have not changed the amount of console logs in the game. Now upon winning a game, it does start x and alternate correctly to o, back and forth. However, it is starting on o on the game 2, but is alternating back and forth which is good 😃 . When you click reset before winning a game, it is not alternating, when you click reset after winning it alternates, and sometimes upon clicking reset before winning, it will alternate every second turn. 

Now sure why it is displaying x's and o's somewhat randomly, for this revision. Here is my code for reference (just added .off on box)

``` js
const reset = function(){
    boardArray = ['','','','','','','','',''];
    $('.box').off('click');
    $.each($('.box'), function(index, element) {
        $(element).html('');
        $(element).one('click', boxClick);
      } ) ;
    $('.tic-tac-toe-board').show();
};
```

**Comment by raq929** [comment]
How do you determine who goes first in the first game? I think your reset button should try to replicate the conditions you have on the first game.
What about your game is different when a game ends? That should help you figure out why reset works differently if clicked in the middle of a game than it does if the game is over. If it works correctly when the game is over, try to replicate those conditions in your reset function.

**Comment by jbuzzanco** [comment]
Hmm. So It seems to be a similar result defining who goes first with in the reset function. Now, it starts with x on the first game instead of o, which is good. However it sometimes starting on x in the next game, depending on when reset is clicked, seems to still be a random behaviour. Here is what I tried.

``` js
const reset = function(){
    boardArray = ['','','','','','','','',''];
    // $('.box').off('click');
    $.each($('.box'), function(index, element) {
        $(element).html('');
        $(element).one('click', boxClick);
      } ) ;
      if (store.turn === "x"){
         store.turn = "o";
      } else {
         store.turn = "x";
      }
    $('.tic-tac-toe-board').show();
};
```

**Comment by jbuzzanco** [comment]
resolved by removing reset function on document ready in `index.js`. Reset was firing as the document was loaded.

**Comment by raq929** [comment]
Good work!
