### ISSUE TITLE
404 error PATCH request - Update Game

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/game-project#388]
I've been looking at closed issues for a while trying to draw parallels between similar problems past developers have had. Based on what I'm seeing from other issues, my game id is potentially not being captured on "create game". 

Here is the error message:
aqueous-atoll-85096.herokuapp.com/games/undefined:1 PATCH https://aqueous-atoll-85096.herokuapp.com/games/undefined 404 (Not Found)

From this, I'm gathering that the game id is "undefined". 

CODE FOR GAME API UPDATE GAME:
```js
const updateGame = (data) =>
 $.ajax({
   url: config.host + '/games/' + store.gameData.game.id,
   method: 'PATCH',
   headers: {
     Authorization: 'Token token=' + store.user.token,
   },
   data,
  });
```

EVENT HANDLER FOR UPDATE GAME:
```js
const onUpdateGame = function () {
 let data = {
   "game": {
     "cell": {
       "index": store.gameData.game.index,
       "value": store.gameData.game.value,
     },
     "over": store.gameData.game.over,
   }
 };
  gameApi.updateGame(data)
    .then(gameUi.updateGameSuccess) //changed "create" to "update"
    .catch(gameUi.failure);
 };
```

GAME UI CODE FOR UPDATE GAME:
```js
const updateGameSuccess = (data) => {
  store.gameData.game = gameData.game;
};
```

ALSO HAVE THIS UPDATE GAME FUNCTION:
```js

const updateBoard = function(index, letter){
  store.gameData.game.cells[index] = letter;
};

let player = '';
```

NEW GAME FUNCTION:
```js
const newGame = function () {
 gameData= {
   game: {
     cells: board,
     over: false,
     value: '',
     index: 0,
     player_x: {
       id: store.user_id,
       email: store.user.email
     },
     player_o: {}
   }

 };
 store.gameData = gameData;
};
```

**Comment by raq929** [comment]
Looks like your game id is undefined. (`store.gameData.game.id`) I would look at how you're setting that data. You can also put a debugger in your API call and inspect store.gameData.

**Comment by raq929** [comment]
Can you post your code for createGame of the above doesn't help you figure it out?

**Comment by raq929** [comment]
You should have something along the lines of onCreateGameSuccess that stores game data after creating a game.

**Comment by jdaly04** [comment]
So part of my problem might also be that I have "create game" and "new game" functions right now. 

onCreateGame code:

``` js
const onCreateGame = function(event) {
  if (store.user) {
    gameLogic.newGame();
    event.preventDefault();
    gameApi.createGame(store.gameData)
      .then(gameUi.createGameSuccess)
      .catch(gameUi.failure);
  }
};
```

I also have this "create game" function:

``` js

const clickCreateGame = function() {
  $('.box').text('');
  $('.win').text('');
  gameLogic.resetGameBoard();
  gameLogic.player = '';
};
```

AND I have this newGame function:

``` js
const newGame = function () {
 gameData= {
   game: {
     cells: board,
     over: false,
     value: '',
     index: 0,
     player_x: {
       id: store.user_id,
       email: store.user.email
     },
     player_o: {}
   }

 };
 store.gameData = gameData;
};
```

**Comment by raq929** [comment]
So you should have to send any data to create the game. Can you post
createGameSuccess?

**Comment by jdaly04** [comment]
``` js
const createGameSuccess = (gameData) => {
  store.game = gameData.game;
};
```

**Comment by jdaly04** [comment]
PATCH is now working. I had to pass "index" and "value" to the function when invoking it.
