### ISSUE TITLE
[JS AJAX] Save game state "function is defined but never used" / "function is not defined"

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/game-project#39]
I have auth.js and tic-tac-toe.js

Errors received:
auth.js - saveGame is defined but never used
tic-tac-toe.js - saveGame is used but never defined

I've tried copying my ajax into tic-tac-toe.js but I still get both errors (not defined, and not used, but now both are in tic-tac-toe.js)

```
let saveGame = function (player, index) {
  $.ajax({
    url: myApp.baseUrl + '/games/' + myApp.user.id,
    // url: 'http://httpbin.org/post',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + myApp.user.token,
    },
    contentType: false,
    processData: false,
    data: {
  "game": {
    "cell": {
      "index": index,
      "value": player,
    },
    "over": false
  }
}
  }).done(function(data) {
    myApp.game = data.game;
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};
```

```
let move = function() {
  $('.box').on('click', function() {
    if(gameStatus === 'active') {
        if ($(this).text() !== '') {
          $('.messages').text('Select another box!');
        } else if (player === 'x') {
          $(this).text('x');
          saveGame('x', event.target.id);
        } else {
          $(this).text('o');
          saveGame('o', event.target.id);
        }
        checkWin();
        switchPlayer();
    }
  });
};
```

**Comment by GA-MEB** [comment]
The trick is `module.exports` / `require` - that's how you pass a reference to a function out of one file and into another.

Is `auth.js` exporting that function? Is `tic-tac-toe.js` requiring it?

**Comment by seatuna** [comment]
Now I get an additional error: createGame not defined

in auth.js
`module.exports = {
  createGame,
  saveGame
};`

in tic-tac-toe.js

```
require('./auth.js');
```

**Comment by RealWeeks** [comment]
They are in the same directories as well (is the path correct)?

**Comment by dumplingpuff** [comment]
I had the same issue and tried a lot of things with Lina.  We tried naming a simple variable named cat and tried to see if it would link to index.js and it didn't.
My code looks like
require('./member');`
and my member.js export looks like
module.exports = {
  cat: cat,
  gameData,
  joinGame,
  updateGame
};`

**Comment by RealWeeks** [comment]
@jrhorn424 is this similar to the issue Ethan had on Friday?

**Comment by seatuna** [comment]
Pasted auth.js contents into tic-tac-toe.js and fixed syntax errors.

**Comment by RealWeeks** [comment]
Require must be assigned to a variable.
