### ISSUE TITLE
cant push to repo on GA laptop 

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/game-project#391]
Hello,

Some of you may know I ran into some hard drive issues this week and have been working on a GA laptop. For reasons that aren't worth explaining I grabbed a zip version of my project and have been working off of that which Im assuming is the reason I can't push to any of my branches. Mostly I just want to redeploy today so in the interest of time I want to push my current local repository to a brand new repository. 

Attempted solutions: https://github.com/akadane87/tic-tac-bro-segundo (all of these)
Returned errors:
'''
~/downloads/tic-tac-bro-copy (game_api)$ git status
On branch game_api
Your branch is ahead of 'origin/game_api' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
~/downloads/tic-tac-bro-copy (game_api)$ git add .
~/downloads/tic-tac-bro-copy (game_api)$ git commit
On branch game_api
Your branch is ahead of 'origin/game_api' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
~/downloads/tic-tac-bro-copy (game_api)$ git remote add origin git@github.com:akadane87/tic-tac-bro-segundo.git
fatal: remote origin already exists.
~/downloads/tic-tac-bro-copy (game_api)$ git remote add origin git@github.com:akadane87/tic-tac-bro-three.git
fatal: remote origin already exists.
~/downloads/tic-tac-bro-copy (game_api)$ 
'''

Thanks!

**Comment by akadane87** [comment]
![screen shot 2016-11-20 at 2 56 46 pm](https://cloud.githubusercontent.com/assets/12720136/20465753/1c6f22aa-af33-11e6-973a-89fe1982de83.png)

**Comment by akadane87** [comment]
![screen shot 2016-11-20 at 2 57 37 pm](https://cloud.githubusercontent.com/assets/12720136/20465755/2332fa94-af33-11e6-9581-53e8d7aa65e7.png)

**Comment by gaand** [comment]
Is 

``` sh
git push origin game_api
```

not what you want to do?  

If not, you'll need to use a different name for the remote you're trying to add or change the url for the remote `origin`.

**Comment by raq929** [comment]
It already has a remote name origin, so you won't be able to add a remote with the same name. 

My recommendation is to push to your original repo. Click on the clone or download button, and choose the HTTP option. Copy the url.

You can then do `git remote add origin-http` (or whatever you want to call it)
You'll have to use your github username and password to push.

**Comment by akadane87** [comment]
I can't push to any branch right now --  which makes my github.com repo drastically different than my local one or else I would happily clone from that one.

I get the same error message when trying to push to a branch on either repo even after I've changed the remote name:

(new repo attempts)

```
~/downloads/tic-tac-bro-copy (game_api)$ git remote add origin git@github.com:akadane87/tic-tac-bro-segundo.git
fatal: remote origin already exists.
~/downloads/tic-tac-bro-copy (game_api)$ git remote add origin git@github.com:akadane87/tic-tac-bro-three.git
fatal: remote origin already exists.
~/downloads/tic-tac-bro-copy (game_api)$ git remote add original git@github.com:akadane87/tic-tac-bro-three.git
~/downloads/tic-tac-bro-copy (game_api)$ git push original game_api
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~/downloads/tic-tac-bro-copy (game_api)$ 
```

(old rep attempts)

```
~/downloads/tic-tac-bro (game_api)$ git push origin game_api
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I looked up the error message earlier today and it lead to me ssh key stuff...should I be toying with any of this or does it have the potential to mess things up further?

**Comment by akadane87** [comment]
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by raq929** [comment]
Right. That's why I told you to use HTTP rather than SSH above. It's not your laptop, so you don't want to configure it to use your SSH. 
If you use the HTTP option on the clone and download button, and add that as a remote (with a name other than origin), you should be able to push to it.

**Comment by akadane87** [comment]
Got it! Sorry for the confusion, wasn't sure why I was cloning an out of date repo. I will close and summarize. This turned 4 days of edits and organized commits into 1 very large commit - If I could ask you guys to consider this issue when evaluating my commit messages I would appreciate it. Thank you both for your help.

**Comment by akadane87** [comment]
Used http clone method to bring down an older version of my repo and swapped out the older assets2/ folder for the newer one I had locally that I was unable to push. Now I am linked and current with my github.com repo
