### ISSUE TITLE
[Git] merge & deployment issue

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/game-project#393]
I am having issue upon redeploying my project. I had my latest version on the branch testing. 
I added, commited and pushed that branch once it had the latest features. So then i wanted to deploy it. So I followed the deployment guide https://github.com/ga-wdi-boston/gh-pages-deployment-guide , to my understanding. I am figuring once you deploy some steps needed to be skipped be skipped which I didn't do this time of deploying. I am guessing it is with the `grunt build `step where I went wrong, possibly.

Here are steps I took to try and deploy to best of my memory, which went back to a older version of my project.
On testing branch with it up- to-date added/committed/pushed : 
git merge gh-pages
`git checkout gh-pages`
`git merge master`
made sure .gitignore files commented out
`grunt build`
added and commited and pushed gh-pages
finally went to my url to see it was a previous version of my project probably from a branch other than testing which was most up to date, and which I wanted to be merged to gh-pages to be deployed. Can you see why it was not merged correctly?

**Comment by BenGitsCode** [comment]
If you still have access to the terminal you can type `history` to print a history of your last (100 I think) commands entered, and we can see exactly the commands you used in that sequence. 

Did you follow the steps [here](https://github.com/ga-wdi-boston/game-project/issues/355)?

**Comment by jbuzzanco** [comment]
I followed the deployment guide as from my post above because I was told it was updated when there was a problem with it.
here is the history 100
```
411  atom .
  412  cd wdi/projects/
  413  ls
  414  cd tic-tac-toe-temp/
  415  atom .
  416  grunt serve
  417  git status
  418  git add assets/scripts/game/events.js 
  419  git status
  420  git commit
  421  git status
  422  git add assets/scripts/game/events.js 
  423  git commit
  424  git status
  425  git push origin testing
  426  cd wdi/studies/
  427  ls
  428  cd ../projects/
  429  ls
  430  cd game-project-api/
  431  atom .
  432  cd ..
  433  cd ls
  434  ls
  435  cd tic-tac-toe-temp/
  436  atom .
  437  cd wdi/projects/
  438  ls
  439  cd tic-tac-toe-temp/
  440  git status
  441  git push origin testing
  442  atom .
  443  atom .
  444  cd ../
  445  cd ../practices/
  446  ls
  447  git clone git@github.com:jbuzzanco/full-stack-project-practice.git
  448  cd full-stack-project-practice/
  449  git checkout -b response
  450  atom .
  451  quit chrome
  452  exit chrome
  453  cd wdi/projects/
  454  git status
  455  cd ..
  456  cd practices/
  457  ls
  458  cd full-stack-project-practice/
  459  git status
  460  git add practice.md 
  461  git commit
  462  git push origin response
  463  atom .
  464  cd wdi/projects/
  465  atom .
  466  cd tic-tac-toe-temp/
  467  atom .
  468  git status
  469  git merge gh-pages
  470  git checkout gh-pages
  471  git stauts
  472  git status
  473  grunt serve
  474  git status
  475  git add assets/scripts/game/events.js 
  476  git commit
  477  git status
  478  git push origin testing
  479  git merge gh-pages
  480  git merge gh-pages
  481  git checkout gh-pages
  482  git checkout master
  483  git status
  484  git push origin master
  485  git checkout gh-pages
  486  git merge master
  487  atom .gitignore 
  488  grunt build
  489  gi status
  490  git status
  491  git add bundle.js dependencies.js 
  492  git commit
  493  git push origin gh-pages
  494  atom .
  495  grunt serve
  496  grunt serve
  497  git checkout testing
  498  atom .
  499  grunt serve
  500  grunt serve
  501  cd wdi/projects/
  502  ls
  503  cd project-1-tic-tac-toe/
  504  git checkout testing
  505  git branch
  506  c d..
  507  cd ..
  508  cd tic-tac-toe-temp/
  509  atom .
  510  history 100
```

**Comment by BenGitsCode** [comment]
So this looks right, you followed these [steps](https://github.com/ga-wdi-boston/game-project/issues/355) right?

When did you actually run the deployment? It can take a few minutes or sometimes longer to update.

**Comment by jbuzzanco** [comment]
No I was running these steps https://github.com/ga-wdi-boston/gh-pages-deployment-guide
and locally my file is an older version now too.

**Comment by BenGitsCode** [comment]
Right, but you did [these](steps) first right? We announced this in the issue queue and also in class announcements?

**Comment by jbuzzanco** [comment]
No I did not for this deployment. I thought/heard that the deployment guide was updated so I followed that deployment guide only.

**Comment by jbuzzanco** [comment]
After this issue was put up I believe I heard that it was updated on the gh-pages deployment guide so I did not follow this issue again https://github.com/ga-wdi-boston/game-project/issues/355
but it sounds like youre suggesting that this is not the case and the deployment guide was not updated?

**Comment by jbuzzanco** [comment]
resolved by going back to previous commit 😄  and I merged the right way then instead of backwards
