### ISSUE TITLE
Problem with clearing/ reseting my board

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/game-project#394]
This is an error that I am getting in my console when I attempt to load this code.

ERROR in console

jQuery.Deferred exception: logictwo.clearBoard is not a function TypeError: logictwo.clearBoard is not a function
    at Object.createGameSuccess (http://localhost:7165/bundle.js:581:13)
    at mightThrow (http://localhost:7165/dependencies.js:3680:30)
    at process (http://localhost:7165/dependencies.js:3748:13) undefinedjQuery.Deferred.exceptionHook @ jquery.js:3846process @ jquery.js:3642

ERROR above

If I try to call this function in ui-board.js or events-board.js the page cannot load, it gets stuck on this function being called. If I call the function in logic.js, then the page loads normally, but it ends up happening at an less than ideal time. 

I've tried moving the function call to various locations within the onGamesSuccess and within the createGameSuccess, one is commented out when the other one is uncommented, but I get the error every time.

UI
```js

// const logictwo = require('./logic.js');

//creatGameSuccess
const createGameSuccess = (gameData) => {
  // $('.col-xs-4').on('click');
  store.game = gameData.game;

  $('.playerMessages').text("");
  $('.messages').text('NEW GAME');
  // debugger;
  // logictwo.clearBoard();
  $('#board').show();
  console.log(gameData);
};

```

EVENTS
```js

const logic = require('./logic.js');

const onCreateGame = function() {
  apiBoard.createGame(store.gameData)
    .then(uiBoard.createGameSuccess)
    .catch(uiBoard.createGameFailure);
    logic.clearBoard();
    $('#board').show();
};


```

```js

// // create a function to clear the board and associated array
const clearBoard = function() {
  // if (boardLock()) {
  board = ['','','','','','','','',''];
  turnNum = 0;
  $('#sqa').text('');
  $('#sqb').text('');
  $('#sqc').text('');
  $('#sqd').text('');
  $('#sqe').text('');
  $('#sqf').text('');
  $('#sqg').text('');
  $('#sqh').text('');
  $('#sqi').text('');

  $('#sqa').css('pointer-events', 'auto');
  $('#sqb').css('pointer-events', 'auto');
  $('#sqc').css('pointer-events', 'auto');
  $('#sqd').css('pointer-events', 'auto');
  $('#sqe').css('pointer-events', 'auto');
  $('#sqf').css('pointer-events', 'auto');
  $('#sqg').css('pointer-events', 'auto');
  $('#sqh').css('pointer-events', 'auto');
  $('#sqi').css('pointer-events', 'auto');
// ---------
//   for (let i = 0; i < board.length; i++) {
//     board[i] = '';
//   }
//   $('.col-xs-4').text('');
//    turnNum = 0;
  // }
};

module.exports = {
  addboardHandler,
  winnerCondition,
  gameOver,
  boardLock,
  clearBoard,
};

```

**Comment by raq929** [comment]
Can you push the branch you're working on and let me know what it's called? I think I need to look at the code here.

**Comment by ielole** [comment]
I just commited and pushed my working(html) branch to GitHub.

**Comment by raq929** [comment]
Looking at it now

**Comment by raq929** [comment]
Ok, so the problem with having it in events is that it's a circular dependency. Logic requires events requires logic... forever. 
Looking at the other option.

**Comment by ielole** [comment]
OK, I was wondering if that was the issue.

**Comment by raq929** [comment]
Yeah, either way you get a circular dependency.

**Comment by raq929** [comment]
When do you want this function to be called?

**Comment by raq929** [comment]
Oh. Wait, maybe not on the circular dependency. You're never exporting clearBoard.

**Comment by raq929** [comment]
`ui-board.js` requires `logic.js` requires `events-board.js` requires `ui-board.js`. So that's not going to work either. hmmm

**Comment by raq929** [comment]
Quick and dirty solution: move `createGameSuccess` into the file you are using it in. This requires some refactoring, most notably in how you handle board and turnNum. I might import store and use store.Board and store.turnNum instead (everywhere). Use find and replace. 

More refactoring required: Stop requiring `board-events` in your logic file. This is the better solution, ultimately, but probably requires moving more things. But maybe not. 

I'm on slack if you need more guidance.

**Comment by raq929** [comment]
Hm. Option 1 seems like less of an option, because you use it in your gameOver function.

**Comment by raq929** [comment]
OK. I think the best option right now might be to, in your `logic.js` file, 
1. Import the store object
1. change board and turnNum to store.board and store.turnNum, respectively
1. Move clearBoard to it's own file, (which also imports store) and use it where you need it. (except for in events.js. It still won't work there.)

**Comment by ielole** [comment]
Awesome! Thanks Rachel.

**Comment by ielole** [comment]
Left the function in the logic.js file...because it WORKS, instead of trying to get the board to clear at a different time.
