### ISSUE TITLE
Issue with my create game and new game failure functions

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/game-project#395]
These are my failure functions for createGameFailure

```js

const createGameFailure = () => {
  $('.messages').text('Please SIGN IN to PLAY a game.');
};

```

and getGamesFailure

```js

const getGamesFailure = () => {
  $('.messages').text('Please SIGN IN to view NUM of Games PLAYED.');
};

```

When the page first loads and click on either the 'Get Games' or the 'Play NEW Game' button, I get this error in the console:

api-board.js:20 Uncaught TypeError: Cannot read property 'token' of undefined(…)showIndex @ api-board.js:20onGetGames @ events-board.js:36dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009

I don't understand why my failure functions are not returning their messages.

The failure function messages for createGameFailure and getGamesFailure return after the user has logged out and the 'Get Games' and the 'Play NEW Game' are clicked, respectively.

**Comment by raq929** [comment]
Can you post the part of you code where you use those functions?

**Comment by ielole** [comment]
events-board.js
```js

'use strict';
// const logic = require('./logic.js');
// const allAccess = require('../auth/all-access.js');
const store = require('../store.js');
const apiBoard = require('./api-board.js');
const uiBoard = require('./ui-board.js');

const onCreateGame = function() {
  apiBoard.createGame(store.gameData)
    .then(uiBoard.createGameSuccess)
    .catch(uiBoard.createGameFailure);
    // logic.clearBoard();
    $('#board').show();
};

const onUpdatePlay = function(squareId, boardValue) {
    let gameData = {
      game: {
        cell: {
          index: squareId,
          value: boardValue
        },
        "over": false,
      }
    };
  console.log(gameData);
  store.gameData = gameData;
  apiBoard.updatePlay(gameData)
    .then(uiBoard.updateGameSuccess)
    .catch(uiBoard.failure);
};

const onGetGames = function() {
apiBoard.showIndex()
  .then(uiBoard.getGamesSuccess)
  .catch(uiBoard.getGamesFailure);
};

 const addGameHandler = () => {
  // when the create-game id is clicked, call the onCreateGame function
  $('#create-game').on('click', onCreateGame);
  $('#get-games').on('click', onGetGames);
 };

module.exports = {
  addGameHandler,
  onUpdatePlay,
  onGetGames,
};


```

**Comment by raq929** [comment]
Ah. I see what's going on. Your code is erroring before it gets to your failure message. When it tries to call the API, it looks for the token, can't find it, and errors.
I might move the error message code inside the click handler for the button, and do something like:
```
if(token) {
// Make API call
} else {
// Show error message
}

**Comment by ielole** [comment]
Hide the buttons using css display property and .show() after successful sign in. Also, had to hide the buttons after a successful sign out.
