### ISSUE TITLE
problem with PATCH request (game API), not getting a response from server

### ISSUE THREAD

**Issue by kfili** [ga-wdi-boston/game-project#396]
I have tried changing a lot of things in the updateGame function, as well as the function that calls updateGame. My code hits the debugger in my ui.updateGameSuccess function, so I know it gets that far.

In the function that calls updateGame, if I use 
.then and .catch instead of .done and .fail 
I then get an error where it says "api.updateGame is not a function"

From my game/api.js
```js
const updateGame = function(data){
  return $.ajax({
    method: 'PATCH',
    url: app.host + '/games/' + store.game.id,
    headers: {
        Authorization: 'Token token=' + store.user.token,
    },
    data,
  });
};
```

From my logic.js
the code I use to call the update game function starts at line 8
```js
const cellClick = function (e) {
  e.preventDefault();
    if (gState === 'go') {                        //gStateCheck
      if (board[$(this).data('cell')] === '' ) {  //cellCheck
          board[$(this).data('cell')] = turn;
          $(this).text(turn);       // sets X/O to a cell
          gState = isWin();         // returns true if win or draw state detected
          // store.index = $(this).data('cell');
          let data = {
            game: {
              index: 9,        //Test values
              value: 'x',
            },
          };
          api.updateGame(data)
          .done(ui.updateGameSuccess)
          .fail(ui.failure);
          if (gState !== 'go') {                  //winCheck
              if (gState === 'winX') {
                $('#status').text('Player X wins!!');
                store.game.over = true;
              } else if (gState === 'winO') {
                $('#status').text('Player O wins!!');
                store.game.over = true;
              } else {
                $('#status').text("Cat's Game.");
                store.game.over = true;
              }
            } else {
            switchTurn();           // switches a variable that = X or O
            }
          }
    } else if (gState !== 'go') {                 //resetGame
      emptyBoard();                 // clears the board array.
      gState = 'go';
      switchTurn();
      store.game.over = false;
      events.onCreateGame();
      }
  };
```

**Comment by raq929** [comment]
So, I understand the error you get when you use `.then` and `.catch`, but what is the error you get if you don't?
Are you importing the api at the top of this file?

**Comment by kfili** [comment]
I don't get an error or any sign of successful patch.

Others have shown me that in their console they get a message with 'PATCH' in blue text that shows patch success.

I have required the api file and if I put a debugger in the api.updateGame function, it does show me that the function is being called. One thing I'm not sure of is what kind of data I need to be sending... or if I need to use certain data to be creating games from before hand? My create game function does seem to be working and returning an object.

**Comment by raq929** [comment]
You may have different settings in your developer tools such that it's not showing network requests. You can check the network tab to see if the request went through. (It doesn't start recording requests until you open it.)
Check the API docs to see the format of the data you're sending. 
You don't need to send any data to create a game. :)

**Comment by kfili** [comment]
oh my goodness, i did have network requests hidden! Thanks! it now says:
```
XHR finished loading: PATCH "https://aqueous-atoll-85096.herokuapp.com/games/12640".
```
Does that mean I have fulfilled the PATCH game api requirement?  For good measure I updated the 'data' so it returns real values reflecting the game.
```
         let data = {
            game: {
              index: $(this).data('cell'),
              value: turn,
            },
          };
          api.updateGame(data)
          .done(ui.updateGameSuccess)
          .fail(ui.failure);
```

**Comment by raq929** [comment]
I think it does! Unless it errors, you're good to go!

**Comment by kfili** [comment]
Issue was fixed by unchecking "hide network messages" in chrome console .
