### ISSUE TITLE
JavaScript Grunt Nag Not Reflecting Changes

### ISSUE THREAD

**Issue by akgoode** [ga-wdi-boston/game-project#398]
validateQuoteMarks: Invalid quote mark found at assets/scripts/player.js :
     5 |  this.playerNumber = index;
     6 |  if (index === 1) {
     7 |    this.piece = "X";
-------------------------^
     8 |  } else {
     9 |    this.piece = "O";
validateQuoteMarks: Invalid quote mark found at assets/scripts/player.js :
     7 |    this.piece = "X";
     8 |  } else {
     9 |    this.piece = "O";
-------------------------^
    10 |  }
    11 |};
>> 30 code style errors found!

I'm going through my grunt nag code style errors and making changes on a branch called "nagfixes".  I received 30 errors initially, most of which were double quotes instead of single quotes, requireTrailingNewLines, and anonymousFunctionsRequireSpace.  I changed all the quote mark errors and a lot of the trailing new line errors and grunt nag still showed them as errors.  I thought that maybe grunt nag only worked on the master branch, so I merged these changes which I knew were correct into my master branch and ran grunt nag on them, but the errors still showed up as if I hadn't changed them.  Nowhere in any code in my file does my board.js file have single quotes, yet when grunt nag runs it still shows double quotes just like above.

**Comment by akgoode** [comment]
I created a new repository and copied my code to get rid of this problem.  Issue closed.

**Comment by jrhorn424** [comment]
The next time this happens, file an issue as you did this time, and notify me directly that `grunt nag` isn't working as you expect. I'll investigate. What you reported I am unable to reproduce, and I've never personally had an issue with `grunt nag`.

> I changed all the quote mark errors and a lot of the trailing new line errors and grunt nag still showed them as errors. 

That's definitely not the correct behavior of `grunt nag`, but there may have been another problem.

> I thought that maybe grunt nag only worked on the master branch

`grunt nag` works on files in a project folder. It does not matter which branch you are on.

> Nowhere in any code in my file does my board.js file have single quotes, yet when grunt nag runs it still shows double quotes just like above.

I'm guessing you mean nowhere does it have *double* quotes. In any case, this in particular makes me think something else was going on. I can't say what unless it happens again.

**Comment by akgoode** [comment]
Can I bring my computer over to show you right now?

I just got it to happen.

**Comment by jrhorn424** [comment]
Yes, please.

**Comment by akgoode** [comment]
Thanks Jeff!  Issue closed.

**Comment by jrhorn424** [comment]
This time around, the issue was that `"Authorization": ...` inside the headers object had quotes. The linter doesn't like it when keys are unnecessarily quoted.
