### ISSUE TITLE
git: unable to change branch

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/game-project#399]
I copied browser-template into a tic tac toe folder, created a new git repository and then pushed it in.  I then npm installed and checked out a branch called auth to copy the auth data, then merged it back to the master and tried to deploy it.  Deploy hit an error, and I cannot change branches any longer.

**Comment by gaand** [comment]
Please post errors.

**Comment by dsweetser** [comment]
as best I can summarize, everything in the node_modules directory is coming up with this issue:
	node_modules/yauzl/.travis.yml
	node_modules/yauzl/LICENSE
	node_modules/yauzl/README.md
	node_modules/yauzl/index.js
	node_modules/yauzl/package.json
Please move or remove them before you switch branches.
Aborting

**Comment by gaand** [comment]
Your copy most likely missed hidden files (files that start with `.`) and so you probably don't have  `.gitignore`.  If for some reason you can't follow the browser-template instructions exactly (e.g. you're starting on an existing git repository), you should look into `cp -a` (`man cp`).

**Comment by dsweetser** [comment]
added missing files to the branch, then was able to change back to master.

**Comment by jrhorn424** [comment]
>  copied browser-template into a tic tac toe folder

We ask you to rename the `browser-template` instead of copy it for this very reason.
