### ISSUE TITLE
Grunt serve error - cannot find "./assets/scripts/index.js"

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/game-project#40]
While trying to refactor my code in order to make a defined function be called from another file, I messed something up. 

ERROR in ./assets/scripts/example.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./assets/scripts/index.js in /Users/kevinpie/wdi/projects/tic-tac/ticky-tacky/assets/scripts
 @ ./assets/scripts/example.js 5:0-36

ERROR in ./assets/scripts/example.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./assets/styles/index.scss in /Users/kevinpie/wdi/projects/tic-tac/ticky-tacky/assets/scripts
 @ ./assets/scripts/example.js 6:0-37

The code is all there and I think I'm requiring the right files. But obviously not.

**Comment by GA-MEB** [comment]
Was trying to require the top-level `index.js` file from the assets-level `index.js` file. Moving the desired code into a separate file (`ajax.js`) and requiring that file fixed the issue.
