### ISSUE TITLE
config.js apiOrigins help?

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/game-project#400]
I copied the auth code from api-token-auth to the index.html, scripts/index.js, scripts/auth/api.js, scripts/auth/events.js, and scripts/auth/ui.js.  When I try to sign up, the console gives me this error:

XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jwaskow.github.io' is therefore not allowed access. The response had HTTP status code 400.

 I believe the source of this error is in the config.js file, which has this code:

```
const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com',
  },
};
```

In the browser-template repo the instructions say: "Developers should set config.apiOrigins.production (and config.apiOrigins.development if it differs from the default). With apiOrigins set, developers may rely on config.apiOrigin as the base for API URLs."

This leads me to believe I should change something in the config.js file, but the instructions don't say what it should be changed to.  Are we supposed to use "https://ga-wdi-boston.herokuapp.com" for this project or something different?

**Comment by jrhorn424** [comment]
Please see issue #273 for the correct API url.

**Comment by jrhorn424** [comment]
Also, when you're testing locally (don't deploy just to test api), see: https://github.com/ga-wdi-boston/browser-template/blob/master/lib/set-api-origin.js#L11

**Comment by jwaskow** [comment]
I changed the productions URL in apiOrigins to "https://aqueous-atoll-85096.herokuapp.com/" and it seems to be working.  Thanks!
