### ISSUE TITLE
"HTML-SCSS - Bootstrap- [Issues with page not displaying properly]"

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/game-project#401]
Issue Description:

I copied and pasted the code from all the files we worked on today in the  HTML-SCSS - Bootstrap repo, into my tic-tac-toe game project and none of the styling (borders and such).

I tried to troubleshoot it by comparing all the files in the SCSS-bootstrap repo and my tic-tac-toe game and making sure that they all matched. Not sure what I'm missing? Is there something in the HTML-SCSS - Bootstrap repo that is not in the tic-tac-toe one?

**Comment by BenGitsCode** [comment]
Please review [this](https://github.com/ga-wdi-boston/project-issue-tracker-guide#how-to-use-the-issue-tracker) more closely. 

If your question is: ` Is there something in the HTML-SCSS - Bootstrap repo that is not in the tic-tac-toe one?` The answer is: Yes, many things are different.

**Comment by BenGitsCode** [comment]
What is not working? Do you have any errors?

**Comment by BenGitsCode** [comment]
@AshlenPrice I think you mentioned to me that you resolved this issue, could you please close it with your solution? Thanks!

**Comment by AshlenPrice** [comment]
Issue resolved. My page formatting/style was not displaying, I fixed it by reviewing some of the code in my index.js file. I had and extra set of }); at the bottom. Once I removed them it worked.
