### ISSUE TITLE
Grunt Deploy not linking CSS to HTML

### ISSUE THREAD

**Issue by akgoode** [ga-wdi-boston/game-project#402]
I have successfully linked my CSS file to my HTML file and when I view the local file in my browser the CSS successfully modifies my HTML.  The same when I run grunt server.  However, when I run grunt deploy in the same directory the website that is hosted on github pages does not display linked CSS.  There is a 404 unauthorized error in the console that is the result of trying to fetch my CSS page and my JS page that are linked.

**Comment by akgoode** [comment]
I googled several different strings attempting to find a solution to this issue but the best I can come up with is that the path name to these files gets somehow modified when deployed to a live server?  I don't know enough about what is happening in grunt deploy to really make a solid guess.

**Comment by akgoode** [comment]
I imported my style.css file into the index.scss file and that added some of what I was hoping to add into my HTML, but my JS file still remains unlinked.

**Comment by jrhorn424** [comment]
> I imported my style.css file into the index.scss

Don't do this.

>I have successfully linked my CSS file to my HTML file

Why? Did you see the comment in browser template's index.html?

**Comment by jrhorn424** [comment]
https://github.com/ga-wdi-boston/browser-template/blob/master/index.html#L7

**Comment by akgoode** [comment]
I figured out that I should link my css to index.scss instead of to the HTML.  Closed.

**Comment by jrhorn424** [comment]
> I figured out that I should link my css to index.scss instead of to the HTML. Closed.

You shouldn't have to link anything. Will you please post your `index.html` and the contents of anything in `assets/styles`? A to a recently pushed branch will do. Thanks.

**Comment by akgoode** [comment]
Here is the link to my logic branch https://github.com/akgoode/tic-tac-toe/tree/logic

**Comment by jrhorn424** [comment]
Do not do this: https://github.com/akgoode/tic-tac-toe/blob/logic/index.html#L14

Read this: https://github.com/ga-wdi-boston/browser-template/blob/master/index.html#L7

**Comment by jrhorn424** [comment]
Delete that link in your index's head, then add all your styling (https://github.com/akgoode/tic-tac-toe/blob/logic/assets/styles/style.css) to `index.scss` instead.

**Comment by akgoode** [comment]
I made this change and it works locally.  Still have to push it to github pages to test.

**Comment by MicFin** [comment]
@akgoode please close if this is resolved

**Comment by akgoode** [comment]
Going to close for now.  Can't grunt deploy immediately.  Will reopen if needed.
