### ISSUE TITLE
Grunt Nag and JSON formatting

### ISSUE THREAD

**Issue by akgoode** [ga-wdi-boston/game-project#403]
Grunt nag complains about use of double-quotes in my files that contain AJAX requests and the headers and data that go inside of them.  It wants me to replace the double quotes with single quotes.  Don't know how I can resolve this without outside help.

**Comment by jrhorn424** [comment]
Please follow process. The issue template (from `project-issue-tracker-guide`) suggests pasting the code causing the issue, at the very least. There might be other information we want, as well.

**Comment by jrhorn424** [comment]
https://github.com/ga-wdi-boston/project-issue-tracker-guide#how-to-use-the-issue-tracker

**Comment by BenGitsCode** [comment]
@akgoode any change or resolution in this issue?

**Comment by jrhorn424** [comment]
I believe we resolved this and #398 at the same time.

**Comment by akgoode** [comment]
Yes we did.  I closed the other issue and forgot to close this one.  Sorry!
