### ISSUE TITLE
[Javascript] Grunt Nag Error

### ISSUE THREAD

**Issue by ddobson** [ga-wdi-boston/game-project#405]
When I run `grunt nag` I get the following error that I do not understand.

> Running "jscs:status" (jscs) task
> requireShorthandArrowFunctions: Use the shorthand arrow function form at assets/scripts/game/game.js :
>     23 |
>     24 |  this.compareArrays = function (playerSet, winSet) {
>     25 |    return (winSet.every((element) => {
> ----------------------------------------------^
>     26 |        return (playerSet.indexOf(element) >= 0);
>     27 |      })
> >> 1 code style errors found!

I am using an arrow function in my callback and I do not understand why this error is occurring. My code is working as intended in node terminal. The offending function looks like this:

```
this.compareArrays = function (playerSet, winSet) {
  return winSet.every((element) => {
    return (playerSet.indexOf(element) >= 0);
  });
};

**Comment by BenGitsCode** [comment]
Have you tried googling 'jscs requireShorthandArrowFunctions'?

**Comment by ddobson** [comment]
Yes. It took some digging but I think I just found it.  

https://github.com/jscs-dev/node-jscs/issues/2169 

Because the block evaluates to a single line it wants me to use arrow notation without the brackets. I stored the expression as a variable and returned that to get around this. 

Please close.

**Comment by BenGitsCode** [comment]
@ddobson you can close the issue yourself, only if there is a resolution to your initial question.

Good digging sir :+1:
