### ISSUE TITLE
Game-Project-api 

### ISSUE THREAD

**Issue by aneela06** [ga-wdi-boston/game-project#408]
![screen shot 2017-01-25 at 9 50 49 am](https://cloud.githubusercontent.com/assets/16885313/22295121/ceb2f318-e2e3-11e6-8acc-cb5c2a3a9298.png)
Everytime I run the bundle exec rails server the rails wont run. I tried putting in the token in and it still does not work. I tried following the steps in library-api.

**Comment by BenGitsCode** [comment]
From what directory are you trying to do this? I don't see why you would be running a rails server at any point for this project.

**Comment by aneela06** [comment]
I was running it through my localhost:4741.  I thought we needed it to connect all the backend.

**Comment by BenGitsCode** [comment]
Do you want to use the library-api for the game-project?

**Comment by jrhorn424** [comment]
@aneela06 Do you have a copy of the tic-tac-toe server? Or where you trying to connect to `library-api` in order to tic-tac-toe?

**Comment by jrhorn424** [comment]
See issue #400 and #273

**Comment by aneela06** [comment]
I thought we weren’t supposed to use the library API just the game project API.  My grunt serve works as well.

**Comment by aneela06** [comment]
Ill look at those 2.  Thanks.

**Comment by jrhorn424** [comment]
You never answered @BenGitsCode's question.

> From what directory are you trying to do this?

**Comment by aneela06** [comment]
The directory Im trying to do it from is the game-project-api.

**Comment by jrhorn424** [comment]
If you want to run a local server, that's fine, but you'll need to figure it out on your own for this project. Instead, you should use the following configuration:

```js
// assets/scripts/config.js
// ...

const config = {
  apiOrigins = {
    production: 'https://aqueous-atoll-85096.herokuapp.com',
    development: 'http://tic-tac-toe.wdibos.com',
  },
};

// ...
```

**Comment by aneela06** [comment]
Okay. Thank you.

**Comment by jrhorn424** [comment]
If this addresses your issue, please close.

**Comment by aneela06** [comment]
I will run a local server.

**Comment by jrhorn424** [comment]
@aneela06 Please come speak to me.

**Comment by jrhorn424** [comment]
> I will run a local server.

@aneela06 meant a local client server, even though the OP was about a local API server.

To be clear, you should not run a local API server for this project.
