### ISSUE TITLE
Game logic interaction with event handlers

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/game-project#410]
My game is currently running in a `while` loop, which calls some functions to check for a win or a tie at the end of each iteration, and if there is no win/tie, change the active player. My idea was to have a certain point in the loop where it expects the player to make a move, and checks if that move is valid.

To do this, my thought was that I add the handlers for the tiles only when a move is expected, and destroy them once a valid move has been made. Two questions:
Is this overcomplicating the engine, should I just have it able to accept moves at all times (so long as they are valid) and assign the token based on what the last token assigned was?
Will constantly creating and destroying handlers use a lot of memory or make the game run slower?

If it helps, the current game loop looks something like this (there is no DOM interaction of any kind yet)

```javascript
const newGame = function (playerOne, playerTwo) {

  // define game board, starting player and variable for game loop
  let gameBoard = new Array(9);
  let playerOneTurn = true;
  let gameOver = false;
  let currentPlayer = {};

  //enter game loop
  while (!gameOver) {
    // play game

    // set current player based on whose turn it is
    if (playerOneTurn) {
      currentPlayer = playerOne;
    } else {
      currentPlayer = playerTwo;
    }

    console.log(gameBoard);
    console.log(`${currentPlayer.name}, it is your turn! Pick a square to play.`);

    // move loop, create tile handlers here

    //check for winner
    if (states.winStateCheck(gameBoard, currentPlayer)) {
      console.log(`${currentPlayer.name} wins!`);
      gameOver = true;
    } else if (states.tieStateCheck(gameBoard, currentPlayer)) {
      console.log('Cat\'s game!');
      gameOver = true;
    } else {
      playerOneTurn = !playerOneTurn;
    }
  }
};
```

**Comment by jrhorn424** [comment]
What do you think will happen if you put a non-terminating while loop in the browser?

**Comment by jrhorn424** [comment]
Try opening this page: http://jsbin.com/wicazis

**Comment by jrhorn424** [comment]
I put a while loop in there.

**Comment by jrhorn424** [comment]
The browser already has a loop. When you register handlers or make AJAX requests, you're using it. It's called the **event loop** and I highly recommend not worrying about it for now. We're going to dive into it much more in Unit 3.

Just code the way we've shown you in the past two weeks, and don't over-complicate your code by getting clever. :wink:

Assuming you get ahead and you want to spend time figuring it out, check this: https://www.youtube.com/watch?v=8aGhZQkoFbQ

**Comment by samordonez** [comment]
I assume that page is meant to never load?

Ok, I'll scrap the while loop idea, I think some kind of turn counter makes more sense anyway.
