### ISSUE TITLE
module.exports throwing error

### ISSUE THREAD

**Issue by akgoode** [ga-wdi-boston/game-project#411]
My "module.exports" statement at the bottom of my ./assets/scripts/board.js file always throws an error in the browser.  It says "board.js:162 Uncaught ReferenceError: module is not defined
    at board.js:162".  I formatted it exactly like the way the other module.exports statements have been formatted in all of our other repositories.

I checked on google for the exact error that I kept getting in my console.  The most helpful site I found seemed to be https://www.sitepoint.com/understanding-module-exports-exports-node-js/ but it still didn't help me understand my problem. 

I tried several variations of this export statement.  My latest one is 
module.exports = {
  Board,
  boardInit,
};

Board is a constructor that creates a new board object.  boardInit is another function that I created so that I could avoid exporting the constructor function if possible.  All combinations of Board and boardInit resulted in a "uncaught reference error".

**Comment by jrhorn424** [comment]
Copy and paste your URL from the browser, please.

**Comment by akgoode** [comment]
Did you want the link to the branch on my github repo?

**Comment by jrhorn424** [comment]
No, I want to know what's in your browser's URL bar when you experience this error.

**Comment by akgoode** [comment]
I fixed this issue.  I had a <script> tag left over from when I wrote board.js and index.html outside of the browser template.  After I deleted this tag it worked and created my game board on my page.  Thank you for your help!

**Comment by jrhorn424** [comment]
Thanks for posting your resolution!
