### ISSUE TITLE
1 on 1

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/game-project#412]
If anyone has a minute, can I grab a one on one with someone later this afternoon to talk about my game logic and also testing things in node?

**Comment by BenGitsCode** [comment]
Could you be a little more specific? i.e. what about your game logic? This sounds like it may be two issues—one about your game logic, and another about specifically how to test that logic in node?

**Comment by laurpaik-zz** [comment]
Mostly the latter, since I'm having trouble seeing if my logic works because I'm blanking on properly testing it in node.

**Comment by BenGitsCode** [comment]
What have you tried? Could you show me some examples?

**Comment by laurpaik-zz** [comment]
ahh so I tried it two different ways... I have a game object with my array, and then some functions that (in theory) would assign 'x' or 'o' to a spot in the array depending on what the player is. My first attempt was to run the function I had, but when that didn't work I tried putting it inside the object and doing like game.yourMove, and when I say `game.yourMove` it tells me it's a function, but when I try `game.yourMove()` it tells me it's not a function.

**Comment by jrhorn424** [comment]
Post your exact output when you do both those commands. Actually, if you can paste everything you did in node, along with your code, that would be great.

**Comment by laurpaik-zz** [comment]
attemptOne: 
```node
  let gameBoard: [
    '', '', '',
    '', '', '',
    '', '', '',
  ];
const player = [
  'x',
  'o',
];

const yourMove = function () {
  for (let i = 0; i < player.length; i++) {
    for (let j=0; j < this.gameBoard.length; j++) {
      if (player[i] && this.gameBoard[j] === '') {
        this.gameBoard[j] = player[i];
      } else if (player[i] && this.gameBoard[j] !== '') {
        this.gameBoard[j] = this.gameBoard[j];
      }
    }
  }
  return this.gameBoard;
};
```node
node: 
```$ node
> const yourMove = require('./assets/scripts/index.js')
undefined
> const winnerIs = require('./assets/scripts/index.js')
undefined
> yourMove
{ yourMove: [Function: yourMove],
  winnerIs: [Function: winnerIs] }
> yourMove();
TypeError: yourMove is not a function
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> ~/wdi/projects/tic-tac-toe (editsTakeTwo)
```

**Comment by laurpaik-zz** [comment]
attemptTwo: 
```node
let game = {
  gameBoard: [
    '', '', '',
    '', '', '',
    '', '', '',
  ],
  player: 'x',

  setNextPlayer: function () {
    if (this.player === 'x') {
      this.player = 'o';
    } else {
      this.player = 'x';
    }
  },

  yourMove: function () {
    for (let i=0; i < this.gameBoard.length; i++) {
      if (this.player === 'x' && this.gameBoard[i] === '') {
        this.gameBoard[i] = 'x';
      } else if (this.player === 'x' && this.gameBoard[i] !== '') {
        this.gameBoard[i] = this.gameBoard[i];
      }
    }
    return this.gameBoard;
  },
};
```
node:
```node
/wdi/projects/tic-tac-toe (editsTakeTwo)
$ node
> const game = require('./assets/scripts/index.js')
undefined
> game
{ game: 
   { gameBoard: [ '', '', '', '', '', '', '', '', '' ],
     player: [ 'x', 'o' ],
     yourMove: [Function: yourMove] },
  winnerIs: [Function: winnerIs] }
> game.yourMove();
TypeError: game.yourMove is not a function
    at repl:1:6
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> ~/wdi/projects/tic-tac-toe (editsTakeTwo)
```

**Comment by BenGitsCode** [comment]
❤️ thank you for your proper formatting there. When you have the three backticks, you can set the language just after (js, sass, css, node, ruby etc) to get some mostly accurate syntax highlighting as well, so I just added those in for you, you can see what it looks like by opening up the editor on that comment 👍

**Comment by bernardlee** [comment]
Your first attempt:
```node
> yourMove
{ yourMove: [Function: yourMove],
  winnerIs: [Function: winnerIs] }
> yourMove();
TypeError: yourMove is not a function
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```
You entered `yourMove` and it returned an object literal with two properties, `yourMove` and `winnerIs`, both of which are functions with the same names.  When you called `yourMove()` on the next line, you're trying to invoke that object literal as if it were a function, which is why you're getting a type error.  The correct invocation is `yourMove.yourMove()`.

The second attempt is similar except you have a nested object so the call would be `game.game.yourMove()`.

**Comment by laurpaik-zz** [comment]
Thank you!!!

**Comment by MicFin** [comment]
@laurpaik is this issue ready to be closed?

**Comment by laurpaik-zz** [comment]
yup!

**Comment by jrhorn424** [comment]
`yourMove.yourMove()` and `game.game.yourMove()` are "code smells" in the sense that they're cumbersome to type, repetitive, and should be a trigger to rename (or pass something different in) so that you don't have to be repetitive (for example, passing in a value, which could be an inner objects, instead of the entire outer object).

**Comment by bernardlee** [comment]
There are cleaner ways to export and import functions and objects, but maybe that question should be opened as an issue.  If so, then I can answer there.

**Comment by laurpaik-zz** [comment]
Yea I'm just trying to get everything to work before condensing it. Thanks, I'll post that issue now.
