### ISSUE TITLE
Grunt Nag

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#414]
Do files have to be in specific files to be processed by grunt nag? 
My Main.js file with the engine is in the root directory.

When I runt it it says:

Running "jshint:all" (jshint) task
>> 9 files lint free.
Running "jsonlint:all" (jsonlint) task
>> 6 files lint free.
Running "jscs:status" (jscs) task
>> 9 files without code style errors.

I expected a whole lot of lint which is why I don't think it is being checked.

**Comment by BenGitsCode** [comment]
Are you getting linter errors in Atom for that file?

**Comment by doremaxime** [comment]
yes. much lint.

**Comment by doremaxime** [comment]
All good, i think i figured it out.

**Comment by jrhorn424** [comment]
@doremaxime Your original assumption was correct. Store things in `assets/scripts` and you should be fine. :smile:
