### ISSUE TITLE
Move Handlers to its own file breaks them

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/game-project#415]
Hey Team!  I had my handlers in my index.js, and grunt nag was throwing an error because my function that runs the game (testLogic) and the handlers both reference each other.  I tried to migrate it out and now the clicks are not registering on the page.  Here's what I think the relevant code is: 

index.js:
```
const handlers = require('./handlers.js');

...

const testLogic = function (event) {
  event.preventDefault();
  gameLogic.turnOrder(parseInt(event.target.id));
  console.log(gameLogic.board);
  gameLogic.triggerEndGame(gameLogic.board);
  createBoard();
  handlers.addGameHandlers();
};

...

module.exports = { testLogic,
};

```

handlers.js:
```
const index = require('./index');

const addGameHandlers = () => {
  $('#0').on('click', index.testLogic);
...

module.exports = { addGameHandlers,
};```

**Comment by BenGitsCode** [comment]
@dsweetser It sounds like you have a circular dependency issue. I'll take a closer look at this when I get home, but [this](https://github.com/ga-wdi-boston/game-project/issues?utf8=%E2%9C%93&q=is%3Aissue%20circular%20dependency%20) may be a good starting place.

**Comment by dsweetser** [comment]
My code currently has 9 different click handlers, I'm going to try refactoring all of those into 1 function that I can pass to a single click handler to do what I need it to.

**Comment by samordonez** [comment]
I'm not sure what your DOM looks like but if all 9 tiles are children of the same element you can bind the click handler to the parent. The event will trigger when any of the 9 are clicked, and you can tell which one was clicked via `event.target` which has an 'id' attribute.

**Comment by samordonez** [comment]
something like this (your callback may be different depending on your JavaScript)

```javascript
const initGame = function () {
  $('#gameBoard').on('click', game.makeMove);
};
```

the '#gameboard' element is a div with nine children each with an id from 0 to 8.

**Comment by dsweetser** [comment]
That is absolutely brilliant!!!... but unfortunately doesn't seem to be solving my circular chicken and egg issue...

**Comment by samordonez** [comment]
That one I am not sure about, but hopefully having less click handlers makes is easier to debug!

**Comment by dsweetser** [comment]
TO FUTURE DEVELOPERS:

Circular dependency errors are hard to think your way out of.  I was able to solve mine by looking at what small functions my large functions were referencing and moving the larger functions back into the module that most of those functions came from.
