### ISSUE TITLE
grunt server issue

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/game-project#417]
I could not make sense of the error my grunt server was giving me, but it went away when I closed and reopened it.

**Comment by BenGitsCode** [comment]
@alexkarasik Please add the solution that closed the issue.

**Comment by BenGitsCode** [comment]
Clarification; you edited your issue to remove all the helpful information. Please don't edit issues, make new comments instead so that the thread tells a complete story of the problem.

**Comment by alexkarasik** [comment]
Sorry, I will not do that again. I can't recall what the error said now, but the text was yellow and I just could not make sense of it.

**Comment by BenGitsCode** [comment]
The original issue was:
>This prints out in my terminal:
Running "webpack-dev-server:start" (webpack-dev-server) task
70% 3/3 build modulesFatal error: listen EADDRINUSE 127.0.0.1:7165

>Me and my squad tried changing the dependencies and I am worried that something got messed up doing that. I google and found nothing I could make sense of.

That error means the port was already in use, and it sounds like you solved it by closing the server that was serving, and then serving a new one.
