### ISSUE TITLE
DRYing out/ separating functions from object literals

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/game-project#418]
Hi all, I have a semi-working engine, but all my functions are packed inside an object. I'm trying to dry it out so that my code isn't all inside the one object and is a little more condensed, but they don't work properly when I take them out of the object. The layout I have right now is sort of like this:
```node
let game = {
  gameBoard: [
    '', '', '',
    '', '', '',
    '', '', '',
  ],
  player: 'x',
  setNextPlayer: function () {...},
  yourMove: function () {...},
  winnerIs: function () {...},
};
```
Can someone help me? / if it's easier to explain in person I'd always appreciate a 1 on 1.

**Comment by laurpaik-zz** [comment]
I'm currently playing around with this in a different branch, will let y'all know if I have updates, but as of now the question still stands!

**Comment by laurpaik-zz** [comment]
I think I fixed it! I took everything outside of the object (except I made a player object for the symbol and the setNextPlayer function)  and created a function 
``` node 
const fullBoard = function (element) {
  return element === '';
};

const playGame = function () {
  for (let i = 0; i < gameBoard.length; i++) {
    yourMove(player.symbol);
    if (gameBoard.every(fullBoard) === false) {
      winnerIs('x', 'o');
      }
    }
    reset();
    return gameBoard;
  };
```
and now node gave me
```node
$ node
> const playGame = require('./assets/scripts/example.js')
undefined
> playGame.playGame();
x
o
x
o
x
o
x
o
x
[ '', '', '', '', '', '', '', '', '' ]
```

**Comment by laurpaik-zz** [comment]
If someone can confirm with me on the dryness vs smelliness of what I did I can close this!

**Comment by bernardlee** [comment]
What does your `module.exports = ...` line look like?

**Comment by laurpaik-zz** [comment]
Oh, thanks for pointing that out, it does look kind of smelly...
```node

module.exports = {
  gameBoard,
  player,
  yourMove,
  threeInARow,
  winRow,
  winColumn,
  winDiag,
  winnerIs,
  reset,
  fullBoard,
  playGame,
};

```

**Comment by bernardlee** [comment]
`module.exports` is (by convention, I think) an object and it is what gets imported and set as a variable when you use `require()`.

```javascript
// some-module.js

const someArray = ['some', 'array'];
const someNumber = 100;
const someString = 'some string.';

function someFunction(someParameter) {
  return someParameter;
}

module.exports = {
  someArray,    // This notation is shorthand for something: something
  someFunction,
  someString,
  renamedThing: someNumber
};
```

```javascript
// my-file.js

// This will import whatever module.exports is equal to, inside of
// some-module.js, and set it to the constant, "someModule".
const someModule = require('./some-module');

// someModule is now equal to:
// {
//   someArray: ['some', 'array'],
//   someFunction: [Function: someFunction],
//   someString: 'some string',
//   renamedThing: 100
// }

someModule.someArray;       // ['some', 'array']
someModule.someFunction();  // Calls this function.
someModule.someString;      // 'some string'
someModule.someNumber;      // undefined
someModule.renamedThing;    // 5
```

You can use something called destructuring (linked at the end of this comment) if you don't want to prepend every exported item with an identifier and only import the parts that you want.

```javascript
// my-file.js

// This will only import parts of the exported module that you want.
const { someFunction, someString, renamedThing } = require('./some-module');

someFunction(); // Calls this function.
someString;     // 'some string'
renamedThing;   // 5
someArray;      // Throws an error since we didn't import this and the
                // identifier doesn't exist.
```

You can also rename things that get imported.

```javascript
// my-file.js
const { someFunction: myRenamedFunction } = require('./some-module');

someFunction();       // Throws an error since this identifier doesn't exist.
myRenamedFunction();  // Calls someFunction() from the imported file.
```

`module.exports` doesn't have to be an object and you can set it to something else.
```javascript
// another-module.js
const exportedArray = ['another', 'array'];

module.exports = exportedArray;
```
```javascript
// my-file.js

const something = require('./another-module');

something;  // ['another', 'array']
```

Here's a link to the MDN article on destructuring.  You can do more a lot more than what was written in this comment, such as getting nested properties from objects.

[Destructuring Assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

**Comment by MicFin** [comment]
@laurpaik is this issue ready to be closed?

**Comment by laurpaik-zz** [comment]
I think so! If I have any more question I'll open a new one. Thank you so much!
