### ISSUE TITLE
1 on 1

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/game-project#420]
Whenever someone is I was hoping to have sometime to help with function structuring. I am having trouble breaking down the game structure into function statements.

**Comment by BenGitsCode** [comment]
Could you be more specific? What have you tried?

**Comment by novakw267** [comment]
I have what I think is a good setup for a toggle turn, and for setting up the board and winning conditions. I am trying to construct a set of functions to test placements and assignments in node and see if the winning conditions are accurate.

**Comment by MicFin** [comment]
@novakw267  Can you post your code examples of:

1.  a good setup for a toggle turn
2.  setting up the board
3.  winning conditions

If it makes sense to just share an entire JS file that might be helpful too

**Comment by novakw267** [comment]
andrew just helped with a print function to test the map, I am going to attempt to write try and write a win conditions function based around 
```
// const winConditions = [
// [0, 1, 2], [3, 4, 5], [6, 7, 8], //rows
// [0, 3, 6], [1, 4, 7], [2, 5, 8], //columns
// [0, 4, 8], [2, 4, 6] //diagonal
// ]; 
```
But I am not sure that is the best way to document the win conditions.

**Comment by MicFin** [comment]
It looks like you are heading in the right direction.

**Comment by novakw267** [comment]
Thanks mike.
