### ISSUE TITLE
Not Rendering scss file

### ISSUE THREAD

**Issue by skylarkJ** [ga-wdi-boston/game-project#421]
I committed my work in scss and html and a new content for config. js - the stuff rendered in the browser. Then I created game.js and linked it properly and since then scss hasn't been rendering.

**Comment by BenGitsCode** [comment]
What's the error you're seeing?

**Comment by skylarkJ** [comment]
No   f4769f9bdb7466be65088239c12046d1.eot  20.1 kB               
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB               
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB               
  89889688147bd7575d6327160d64e760.svg   109 kB               
448c34a56d699c29117adc64c43affeb.woff2    18 kB               
                              specs.js  1.36 kB       1       specs
                             vendor.js   595 kB       2       vendor
                    application.js.map   237 kB       0       application
                          specs.js.map  1.93 kB       1       specs
                         vendor.js.map   721 kB       2       vendor
webpack: bundle is now VALID.

**Comment by skylarkJ** [comment]
No error.

**Comment by skylarkJ** [comment]
It could be something with .js anyway.

**Comment by BenGitsCode** [comment]
Can you show me the code? Let's start with the HEAD section of your `HTML` and your `.scss` file. 

Make sure you put them in between sets of three backticks, or use the `<>` button in the comment editor.

**Comment by skylarkJ** [comment]
In general .js the function is defined but never used but in my .js the name of the function is included in module.exports for node.js. - Also, my .js doesn't have any content yet. Can this cause the issue?

**Comment by skylarkJ** [comment]
I just included a name of my js file - gameFile.js into this function bellow in index.js but the scss isn't still rendering. But the error of not defined went away.

$(() => {
  authEvents.addHandlers();
  gameFile.addHandlers();
});

**Comment by skylarkJ** [comment]
Well in gameFile.js - there is:
```
'use strict';


module.exports = {
  gameFile,
};
```
Which is throwing still the error gameFile undefined.

**Comment by BenGitsCode** [comment]
Open up the editor on the above comment, see how made it so that it's inside the backticks? Always format your code/errors like that please.

**Comment by skylarkJ** [comment]
`'use strict';

module.exports = {
gameFile,
};`

**Comment by BenGitsCode** [comment]
The issue is that your `.scss` stylings aren't rendering in the browser right? Can I see your `.scss` file and the HEAD of your HTML, as I asked above.

**Comment by bernardlee** [comment]
If `gameFile.js` only contains:
```javascript
'use strict';

module.exports = {
  gameFile,
};
```
then it's trying to export something that doesn't exist.

**Comment by skylarkJ** [comment]
`$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';

$background-color: #fff;
$font-color: #dfdfdf;
$white: #fff;
$grey: #808080;
$button-form-width: 150px;
$color-lime: #cddc39;
$color-green: #00e676;
$color-hover: #00c853;

body {
  color: $font-color;
}

#style-nav {
  border: $white;
}

.style-main-header {
  color: $color-lime;
  text-align: center;
  }

#center-tiles{
margin: 0 auto;
max-width: 300px;
}

.box {
  border: 5px solid $color-lime;
}

div .col-xs-4 {
  background-color: $color-lime;
  border: 5px solid $color-lime;
  color: $color-lime;
  height: 100px;
  margin: 2px;
  width: 100px;
}

div .col-xs-4:hover {
  background-color: #d4e157;
}

.button-form {
  width: $button-form-width;
}


  #button-password{
    margin-top: 10px;
    background: $color-green;
    border-color: $white;
  }

  #button-signup-nav {
    margin-top: 8px;
    background: $color-green;
    border-color: $white;
  }

  #button-signin-nav {
    margin-top: 8px;
    background: $color-green;
    border-color: $white;
  }

  #button-signout-nav {
    margin-top: 8px;
    background: $color-green;
    border-color: $white;
  }

  #button-password:hover{
    background: $color-hover;
    border-color: $white;
  }

  #button-signup-nav:hover {
    background: $color-hover;
    border-color: $white;
  }

  #button-signin-nav:hover {
    background: $color-hover;
    border-color: $white;
  }

  #button-signout-nav:hover {
    background: $color-hover;
    border-color: $white;
  }

  #style-signup {
    border: 1px solid $color-green;
    font-weight: 500;
  }

  #style-signin {
    border: 1px solid $color-green;
    font-weight: 500;
  }

  #style-changepassword {
    border: 1px solid $color-green;
    font-weight: 500;
  }

  #style-signout {
    border: 1px solid $color-green;
    font-weight: 500;
  }

  #style-signup:hover {
    background-color: $color-green;
    font-weight: 500;
  }

  #style-signin:hover {
    background-color: $color-green;
    font-weight: 500;
  }

  #style-changepassword:hover {
    background-color: $color-green;
    font-weight: 500;
  }

  #style-signout:hover {
    background-color: $color-green;
    font-weight: 500;
  }

a {
  color: $white;
}

form {
  border-color: $white;
}

label {
  color: grey;
  margin: 10px 0;
}
`

**Comment by skylarkJ** [comment]
`  <head>
      <title>Tic Tac Toe Game</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">

      
      <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

      
      <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
    </head>`

**Comment by skylarkJ** [comment]
I don't expect to render an empty js but scss yes.

**Comment by skylarkJ** [comment]
So commenting stuff out in gameFile.js fixed the issue.

**Comment by skylarkJ** [comment]
Thank you.
