### ISSUE TITLE
Multiple Board Reset Executed with One Click (Button)

### ISSUE THREAD

**Issue by spwisner** [ga-wdi-boston/game-project#423]
I am currently trying to create a reset button for the game.  The reset code is in jQuery, but one line of this function requires a different javascript function to be executed.  For the reset button, I am attempting to clear the array that holds clicks, clear messages, reset playerX as starting the game, and the x and o values that display on the page.  When the button is clicked, the anticipated goal is achieved.  **But, rather than seeing the console log nested in the reset function print "reset completed" once, it appears twice, which makes me believe the code is being run multiple times.**  

It is important to note:
1. All jQuery functions are nested under a document.ready command while the javascript functions are not
2. Only the jquery code runs multiple times and when the nested javascript function runs with a console log, it only prints once.

My guess is that my primary code (different function) for jQuery, which is also an on.click method, is interfering.  I think this for two reasons:

1. The button does not print my console.log message unless the game has started (i.e. one box was already clicked)
2. My primary code, which is a different function, also uses an on.click method in jquery

Here is the code for the reset function (and related code):

**index.html file**
```html
      <div class="game-play">
        <div class="player-turn">Player 1, it's your turn</div>
        <div class="player-message"></div>
        <div class = "game-board-container">
            <div class="0cell game-box"></div>
            <div class="1cell game-box"></div>
            <div class="2cell game-box"></div>

            <div class="3cell game-box"></div>
            <div class="4cell game-box"></div>
            <div class="5cell game-box"></div>

            <div class="6cell game-box"></div>
            <div class="7cell game-box"></div>
            <div class="8cell game-box"></div>
        </div>
        <div class="reset-game-container">
            <button id="reset-game" onclick="clearBoard()">Reset Board</button>
        </div>
      </div>
```
**board.js file**
```javascript
/// Javascript function located above the document.ready jQuery code:

const clearBoard = function() {
  gameBoard = ["", "", "", "", "", "", "", "", ""];
  currPlayer = playerX;
  tempSymbol = "";
  currentPlayTurn = "";
  messageText();
};

//document.ready (all jQuery code)
$(() => {

//Primary Code (NOT THE DISCUSSED PROBLEM)
$(".game-board-container div").on( "click", function() {
...
...
...
});

//Reset Code (THE SOURCE OF THE PROBLEM)
    $("#reset-game").on( "click", function() {
      console.log('reset completed');
      clearBoard();
      $(".game-box").text('');
    });

});
```

As I was typing this, I thought it could be a problem with how I'm selecting the general "div" category for the primary code in html.  I thought this could affect the reset-game button id which is nested under a "game-board-container div".  But, div#reset-game is not a child element of the first jQuery function, so I don't think this is the problem.

Your help is much appreciated and I apologize if there is too much detail.

**Comment by samordonez** [comment]
What does `clearBoard()` do? I assume it clears the board, but could I see the function?

**Comment by bernardlee** [comment]
In `index.html` you have `<button id="reset-game" onclick="clearBoard()">Reset Board</button>` (the `onclick`attribute sets this button to call `clearBoard()`) and in `board.js` you have `$("#reset-game").on("click", ...);` also calling `clearBoard()`.  This is why `clearBoard()` gets called twice.

No need to apologize.  There is no such thing as too much detail when it comes to debugging.

**Comment by spwisner** [comment]
Awesome.  Thanks so much Bernard.

**Comment by BenGitsCode** [comment]
Did you mean to reopen this issue @spw5235 ?

**Comment by spwisner** [comment]
Hi Bernard, 

I thought I could resolve the problem in two ways:

**Scenario 1**: remove the "onclick(clearBoard()" in the HTML while keeping the clearboard() function in jQuery 

or

**Scenario 2**: keep the "onclick(clearBoard()" in the HTML while removing the clearboard() function in jQuery.

Neither resolved the problem.  I think your described solution will not work because the console.log is only in the jQuery and is not part of the javaScript nested function.  To see if the same thing would happen, I included a different console.log for the nested javaScript function.  For Scenario 1, when the the onclick(clearBoard) function in the HTML is removed, both the nest JS and the jQuery console logs print out in multiples of two.  For Scenario 2, when the jQuery portion is removed, the nested JS function prints once, but the jQuery console log continues to print multiple times.  To me, this indicates that it's a problem with the jQuery (not nested js function).

Finally, doing further testing, I noticed that in BOTH **scenario 1** and **scenario 2**, the number of console.logs that appear depends on how many boxes have been clicked (in multiples of two).  For instance, when I only click one box before resetting, it prints twice.  When I click two different boxes before resetting, it prints 4 times - and so on...

Am I misinterpreting the fix?  Thanks so much.

Steve

**Comment by bernardlee** [comment]
Paste the entirety of `index.html`, `board.js` and any other relevant files here.  I will edit the post(s) afterward.

**Comment by spwisner** [comment]
Sorry.  I assumed you didn't want me to paste all of my work for all to see.  Just did so below.

(Edit from Bernard: Trimmed out stuff.)
```javascript
$(".game-board-container div").on( "click", function() {
  	let divClass = $( this ).attr("class");
    let divClassNum = parseInt(divClass);
    console.log(divClassNum);
    if (isCellEmpty( divClassNum ) === true) {
      $(".player-message").text("");
      symbolValue(currPlayer, divClassNum);
      $( this ).text( tempSymbol );
      if (gameOver(gameBoard) === true) {

        $(".player-turn").text("");
        $(".player-message").text("Game Over");
      } else {
        changePlayer();
        currentPlayTurn = messageText(currPlayer);
        $(".player-turn").text(currentPlayTurn);
      }
    } else {
      $(".player-message").text("Error: This box has already been selected.  Please select a different box to continue the game");
    }

    console.log(gameBoard);

    $("#reset-game").on( "click", function() {
      console.log('reset completed');
      clearBoard();
      $(".game-box").text('');
    });
  });
});
```

**Comment by bernardlee** [comment]
I can edit some of it.

**Comment by bernardlee** [comment]
All right, I didn't notice this at first since I assumed it was the formatting but now that I've reread the code and what you said, I can see that you have a nested click handler inside of another click handler.  That is where your problem is.

What's happening is that each time you click on anything that matches the `.game-board-container div` selector (your cells), it executes the block, `$("reset-game")...` and adds a click handler to the reset button that runs `clearBoard()`.

Click handlers don't get overwritten.  Each time that a cell gets clicked on, it adds another identical `click` event listener to the reset button.  This is why clicking multiple cells causes the reset button to execute `clearBoard()` multiple times.

**Comment by spwisner** [comment]
Perfect.  Thanks for your help and I appreciate your patience.

**Comment by jrhorn424** [comment]
Very minor thing: please prefer `event.target` to `this`. Example:

```diff
-      $( this ).text( tempSymbol );
+      $(event.target).text(tempSymbol);
```
