### ISSUE TITLE
Which status code should sign-out give back?

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/game-project#425]
I was testing my sign-up, sign-in, sign-out, and change-password actions to see if I was getting the correct status code responses.  For the sign-out action, I am unsure which status code I should be getting as a response.  In the game-project-api documentation, the User Actions summary table shows that the status code should be '201 created':

```
DELETE	`/sign-out/:id`	empty	201 Created	empty
```

However, later on in the documentation under the **signout** section, it reads:

```
signout

The signout actions is a DELETE specifying the id of the user to sign out.

If the request is successful the response will have an HTTP status of 204 No Content.

If the request is unsuccessful, the response will have a status of 401 Unauthorized.
```

Should I be getting a status code of 201 or 204 for a successful sign-out?

**Comment by bernardlee** [comment]
If I'm reading the source code for the API correctly, then a successful `DELETE` request to `/sign-out/:id` should return a status code of `204`.

**Comment by jwaskow** [comment]
When I sign-in with an existing account, I get a code of `200`, which I think is correct.  When I sign out of that account, I get a `200` followed by a `204`.  Attempting to sign out again after I have signed out pauses the debugger and gives the error `Uncaught TypeError: Cannot read property 'id' of undefined`.  Is this working correctly?

**Comment by jrhorn424** [comment]
> Is this working correctly?

I'm not sure why you get a `200` followed by a `204`.

However, the error on a second sign-out attempt is expected.

Were you attempting to test the following by signing out twice?
>If the request is unsuccessful, the response will have a status of 401 Unauthorized.

**Comment by jwaskow** [comment]
I'm also unsure why I'm getting a `200` followed by a `204`.  I'm testing for these codes in the network tab of developer tools in chrome.  Is this the correct place to look for status codes?

> If the request is unsuccessful, the response will have a status of 401 Unauthorized.

This is what I was trying to test, yes. I'm not getting any status code response, just the error I mentioned previously.

**Comment by jrhorn424** [comment]
> Is this the correct place to look for status codes?

Yes.

> This is what I was trying to test, yes. I'm not getting any status code response, just the error I mentioned previously.

That's because there is no **request** yet. The code breaks before you make a call to the API. If you want to test an unsuccessful response, try sending the wrong token when attempting to sign out.

**Comment by jwaskow** [comment]
I see, thanks.  Ill close this now
