### ISSUE TITLE
Breaking a loop

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/game-project#428]
I'm trying to tell my function to end after it finds a winner. I looked up `break`, but I think I'm using it wrong. Could someone help me?
```node
const playGame = function () {
  for (let i = 0; i < gameBoard.length; i++) {
    yourMove(player.symbol);
    if (winnerIs()===true) {
      break;
    }
  }
};
```

**Comment by jwaskow** [comment]
You might be looking for `return`.  I used `return` to exit my gameplay function if there is a winner before the code that places a new value in the array.  The first time the code runs into `return` it will exit the function without doing any of the code following `return`.

**Comment by laurpaik-zz** [comment]
I replaced `break` with `return` and it gave me the same result:
```node
$ node 
> const playGame = require('./assets/scripts/example.js')
undefined
> playGame.playGame();
x - -
- - -
- - -
x o -
- - -
- - -
x o x
- - -
- - -
x o x
o - -
- - -
x o x
o x -
- - -
x o x
o x o
- - -
x o x
o x o
x - -
Congratulations!x is the winner!
o - -
- - -
- - -
o x -
- - -
- - -
undefined
```
Is there something wrong with the location I have the `return`?

**Comment by jwaskow** [comment]
You should have the code check for a winner before it places a new 'x' of 'o' on the board.  That way, it reads return if there is a winner, and exits the function before it is able to make another play.

**Comment by BenGitsCode** [comment]
Were you able to resolve this @laurpaik ?

**Comment by laurpaik-zz** [comment]
Yup! Sorry, I keep forgetting to close these. Thanks, Jackson!
