### ISSUE TITLE
How do we use interpolation in jQuery

### ISSUE THREAD

**Issue by newayliu1** [ga-wdi-boston/game-project#429]
I am trying to empty all the cells text by using for loop. The variable, i, represent the name of each cells' id. Please see the code below. 
```javascript
const emptyBoard = function () {
  for (let i=0; i<9; i++) {
    $("##{i}").text('');
  }
};
```
I had tried different way to wrote it, but none of them are correct. HELP!!!

**Comment by bernardlee** [comment]
String interpolation in JavaScript uses grave accents (`) instead of single- or double-quotation marks.  An example is:
```javascript
const myString = 'Hello';

console.log(`myString's value is: ${myString}.`);
```

**Comment by jwaskow** [comment]
in this section: `$("##{i}").text('');`, you have two id selectors (`#`).  If the id for cells is just a number, such as `0` and `1`, you want to use just one id selector, like so: `$("#{i}").text('');`.  

Unless the id for your cells is `#0` and `#1`, in which case your code is correct.

**Comment by newayliu1** [comment]
jQuery said, 
```
Sizzle.error = function( msg ) {
	throw new Error( "Syntax error, unrecognized expression: " + msg );
};
```

**Comment by BenGitsCode** [comment]
Is the original function the one that throws this error? ☝️

**Comment by bernardlee** [comment]
I'm assuming that from your code, you are trying to select elements with `id` values of 0, 1, 2, ..., 7, 8, 9.  The selectors for those are `'#0'`, `'#1'`, `'#2'`, etc.  Refer to my first comment on how to use string interpolation and you can make some small changes in the argument to `$` to make it work.

**Comment by BenGitsCode** [comment]
Also worth mentioning that you shouldn't use numbers for HTML IDs 😉

**Comment by jwaskow** [comment]
@BenGitsCode Why shouldn't we use numbers for an HTML id? I know that in HTML 4 they have to begin with a letter, but doesn't HTML 5 allow them to be just numbers?

source: https://www.w3.org/TR/html5/dom.html#the-id-attribute

**Comment by newayliu1** [comment]
I tried $("#'${i}'"), $("#${i}") and $('#${i}'), none of them are working.

**Comment by jwaskow** [comment]
Have you tried `$("#{i}")`?

**Comment by bernardlee** [comment]
String interpolation only works if the string is wrapped with grave accents (`) not single-quotation marks (') or double-quotation marks (").

**Comment by newayliu1** [comment]
Yes. The correct way is 
```js
(<backtick>#${i}<backtick>).text('');
``` 
(edited by @jrhorn424 for clarity)
(edited further by @bengitscode for more clarity)

**Comment by jrhorn424** [comment]
> Why shouldn't we use numbers for an HTML id?

Because it isn't semantic at all. @jwaskow

If you're using the `id` of an element to store an index number you want to use later, you should use `data-` attributes instead. For example, `<div data-index=0>` is superior to `< div id=0>`.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by jrhorn424** [comment]
@jwaskow

**Comment by jwaskow** [comment]
If my HTML for my div is this: `<div class="col-xs-4" id='box0' data-index=0></div>`, how would I select this in jQuery?  Would it be: `$('#box0.data-index')`?

Or would the click handler be `$('#box0').on('click', function);`, and when I want to change the text for this div I use `$('#box0.data-index').text('X');`?

@jrhorn424

**Comment by bernardlee** [comment]
`id`s are unique so you can use `#box0` as a selector.  `#box0.data-index` would select elements that have an `id` of `box0` and a `class` of `data-index`.  If you want to get data from `data-*` attributes, then jQuery has a method specifically for this.  [jQuery.data()](https://api.jquery.com/data/).

**Comment by jrhorn424** [comment]
@jwaskow Check the linked documentation I sent, specifically the section on "CSS: selecting data-* attributes".
