### ISSUE TITLE
Cant create game state after each move

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/game-project#43]
I can't find the index of the last move on the board so it is preventing me from putting that value in the ajax PATCH request to send data after each move.

**Comment by RealWeeks** [comment]
Please go into more detail. Is board an array?

**Comment by jdamiron** [comment]
board is an array.

board = [ , , , , , , , , , ]

I need a function that registers when I click a certain box on my game board, it adds it into that respective slot on the board function. Then I'll be allowed to take the index of that number. That is my current understanding.

**Comment by jdamiron** [comment]
each space contains a string.

**Comment by RealWeeks** [comment]
@jdamiron Do you still need assistance with this, if so please comment and someone will get to you, if not please close.

**Comment by jdamiron** [comment]
I do not know how to code this function given the variables I used.

**Comment by jdamiron** [comment]
@J-Weeks

**Comment by jdamiron** [comment]
@MattB-GA-Boston still unresolved, need further help

**Comment by RealWeeks** [comment]
@jdamiron what do you define as a "last move" and when are you attempting to make the patch request?

When you click a game box on the board what do you have happening?

**Comment by jdamiron** [comment]
@J-Weeks @MattB-GA-Boston @jrhorn424 @gaand I am successfully creating a game on sign in. But this error is appearing.

```Uncaught ReferenceError: ajax.createGames is not defined(anonymous function) @ gamelogic.js:128jQuery.event.dispatch @ jquery.js:4732elemData.handle @ jquery.js:4544
index.js:49 Object {user: Object}
index.js:131 Successfully created game

``````
I am successfully creating the game but it still says the function is undefined. On the other hand when saveGames is called, which is my patch request to update game state, I get the same error:

```Uncaught TypeError: ajax.saveGames is not a function```

BUT, this code does not run. I am not sure why, both seem to be defined.
``````

**Comment by jrhorn424** [comment]
I believe the problem was circular reference. If you've resolved this issue, please close. If you have other issues, please continue opening them and notifying us.
