### ISSUE TITLE
Displaying a winner everytime 

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/game-project#431]
I got the display winner function to work, however it is displaying after each turn is taken instead of waiting for three in a row. 

```
const threeInARow = function (player, cellOne, cellTwo, cellThree) {
    return (cellOne === player) && (cellTwo === player) && (cellThree === player);
};

const winRow = function (player) {
  return threeInARow(player, board[0]), (board[1]), (board[2]) ||
         threeInARow(player, board[3]), (board[4]), (board[5]) ||
         threeInARow(player, board[6]), (board[7]), (board[8]);
};

const winColum = function (player) {
  return  threeInARow(player, board[0]), (board[3]), (board[6]) ||
          threeInARow(player, board[1]), (board[4]), (board[7]) ||
          threeInARow(player, board[2]), (board[5]), (board[8]);
};

const winDiag = function (player) {
  return   threeInARow(player, board[0]), (board[4]), (board[8]) ||
           threeInARow(player, board[2]), (board[4]), (board[6]);
};

const winnerIs = function (player) {
  return winRow(player.symbol) || winColum(player.symbol) || winDiag(player.symbol);
};

const getWinner = function () {
  if (winnerIs (player1)) {
    return ('Winner is X');
  }
  else if (winnerIs(player2)) {
    return ('Winner is O');
  }
  else { return -1;}
};



const printBoard = function(board) {
  for (let i = 0; i < board.length; i+=3) {
    console.log(board[i] + " " + board[i+1] + " " + board[i+ 2]);
  }
};

const turn = function (player, move, board) {
  board[move]=player.symbol;
  if (getWinner(board) !== -1) {
    console.log(getWinner());
  }
};
```
I had it displaying when console.log get winner individually with the turns. However not with this function.

**Comment by jrhorn424** [comment]
```
  if (getWinner(board) !== -1) {
```

You're passing something in, but are you using it?

```
  if (winnerIs (player1)) {
```

Is player1 defined?

Also, is that valid syntax? you've got a typo there.

**Comment by jrhorn424** [comment]
When is the last time you `nag`ed yourself?

**Comment by novakw267** [comment]
Running grunt nag now they're style errors but nothing else, currently fixing those. And player is defined 
```
const player = {
    symbol: 'X',
};
``` 

I have also changed those all player1 to player, I also fixed the space between winnerIs(player) still running into the same problem. 

I have tried defining player 1 and player 2 as variables to their corresponding x, and o as well as changing the players to 1 and 2 throughout the code and that broke it worse. so I went back to defining player as noted above.

**Comment by novakw267** [comment]
So I nuked and paved, in order to try and fix the problem and I think I fixed that. However now I am running into an issue of not being able to test in node because I can not utilize my 'yourMove' function.  [https://github.com/novakw267/tic-tac-toe/blob/nuke-pave/assets/scripts/game.js](url)

**Comment by bernardlee** [comment]
What are you typing into node and what is the output?

**Comment by novakw267** [comment]
> const yourMove = require('./assets/scripts/game.js') 
> undefined
> yourMove.yourMove(0)
undefined

So in theory it is supposed to apply an X to that place in the array. 

After I declare yourMove I receive 
>yourMove
{ board: [ '-', '-', '-', '-', '-', '-', '-', '-', '-' ],
  player1: 'X',
  player2: 'O',
  threeInARow: [Function: threeInARow],
  winRows: [Function: winRows],
  winColumn: [Function: winColumn],
  winDiag: [Function: winDiag],
  getWinner: [Function: getWinner],
  winnerIs: [Function: winnerIs],
  currentPlayer: 'x',
  togglePlayer: [Function: togglePlayer],
  yourMove: [Function: yourMove] }

so node is seeing the output from module exports

**Comment by bernardlee** [comment]
Where is the error that you're getting?

**Comment by novakw267** [comment]
I am not getting an error, it just remains undefined. Theoretically it should be assigning a piece to the game board, instead it returns undefined still.

**Comment by samordonez** [comment]
You are exporting all of the things from the game file and whe you test it in node you're delaring
`const yourMove = require(path/to/game/file);`

What this effectively means is that you're declaring a new object whose attributes and methods are all the things you're exporting from game.js, so `yourMove` isn't a function, and when you try to invoke it as such, node doesn't know what to do.

Basically node is seeing something like this: 
```javascript
yourMove = {
  export1,
  export2,
  export3(),
  export4(),
  //etc
}
```

**Comment by bernardlee** [comment]
It's displaying `undefined` because that's what those expressions evaluate to.  `const yourMove = require('./assets/scripts/game.js')` doesn't evaluate to anything, so it displays `undefined`.  `yourMove.yourMove(0)` displays `undefined` because, as I've seen in your source code, that function doesn't return anything.  Also, your declaration of `yourMove()` has no parameters.

**Comment by novakw267** [comment]
So still getting an undefined after editing and updating the code, ran grunt nag, had no errors, not even style errors [https://github.com/novakw267/tic-tac-toe/blob/nuke-pave/assets/scripts/game.js](url) I am not sure how to make it assign a piece to the board.

**Comment by bernardlee** [comment]
Are you talking about `yourMove()`?

**Comment by novakw267** [comment]
Yes I am

**Comment by bernardlee** [comment]
As I've mentioned before, `yourMove()` is written in such a way that it doesn't return anything, which is why you're getting `undefined` when you call it.

**Comment by samordonez** [comment]
I was trying to help in person earlier and the issue we were running into was that `yourMove()` wasn't updating the board array even after we added in code that should have. I don't have that the code currently looks like but checking the board after running `yourMove()` with an index passed to it still showed an array of empty strings.

**Comment by bernardlee** [comment]
I can take a look at it if the repository gets updated.

**Comment by novakw267** [comment]
doing so right now
sorry lauren and I were white boarding.

**Comment by novakw267** [comment]
Updated!

**Comment by bernardlee** [comment]
`yourMove()` is still declared with no parameters so passing arguments into it won't have any effects.

**Comment by MicFin** [comment]
@novakw267 did this work? Please update us on how the issue is going or close it if it is solved with a comment of the solution

**Comment by novakw267** [comment]
Sorry I got caught up in writing, I got that to work thanks a lot.
