### ISSUE TITLE
1-on-1

### ISSUE THREAD

**Issue by cshea93** [ga-wdi-boston/game-project#432]
Requesting a 1-on-1 for some direction on where to go next in my project. I have my board and I am able to play X on each box, however I've been stuck here for a bit. Feeling pretty overwhelmed in trying to understand how to structure my functions in regards to the project as a whole. Any suggestions would be useful.

**Comment by jrhorn424** [comment]
Have you picked up a marker? Have you reviewed the project checklist provided in this repo? Have you referenced the milestones list I made yesterday?

I'll grant your request, but first I'd like for you to post a to-do list. Just get everything out of your head. We can prioritize and order it later.

**Comment by cshea93** [comment]
Have referenced the milestones list and am still focused on the game engine. 

To do list:
1) create function that between x and 0 turns when click event is used
2) have these events recorded in the empty board array. 
3) function to check state of board for each turn. See what boxs are available/unavailable, if there is a winner
4) reset board function
5)api
5) record data from click handlers usage to dom
6) authorization

**Comment by cshea93** [comment]
testing in between/throughout each of those..

**Comment by jrhorn424** [comment]
@cpstrillvt93 Let's meet briefly before I leave. I'd like to make sure you're on the right track.
