### ISSUE TITLE
Deployment Issue 

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/game-project#434]
After adding and committing my branch I have checkout to my master and merge it with 'feature' branch.  When I tried deploying the master I have faced with ".ssh/id_rsa" asking for a certain type of password. I have tried the usual password that I have used so far but it is not working. 

order of the code was 
git status
grunt nag (only styling errors)
git add 
git status
git commit 
git checkout master
git merge feature 
grunt deploy

**Comment by BenGitsCode** [comment]
Can you show me the full message you get asking for a password? I'm guessing it's your github password but I can't be sure without seeing the output that you're seeing.

**Comment by wilsonkaya** [comment]
Enter passphrase for key '/Users/Wilson/.ssh/id_rsa''

**Comment by wilsonkaya** [comment]
d

**Comment by jrhorn424** [comment]
Did you choose a passphrase when you created that key?

**Comment by jrhorn424** [comment]
You should also re-run `ssh-add` when you figure out the passphrase.

**Comment by wilsonkaya** [comment]
It aborted the process and pushed me into "gh-pages" now I can't go to either my master or feature brach.  This is the return

```
Please make sure you have the correct access rights
and the repository exists.
Warning: Command failed: touch .nojekyll && git add --force .nojekyll index.html favicon.ico public && git commit -m "deploy task" && git push origin gh-pages --force && git clean -x -d --force --exclude=node_modules && git checkout master
Received disconnect from 192.30.253.112 port 22:11: Bye Bye
Connection to github.com closed by remote host.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 Use --force to continue.

```

**Comment by jrhorn424** [comment]
As I said before:

> Did you choose a passphrase when you created that key?

Do `ssh git@github.com` and try typing your passphrase. Your passphrase could be blank, but it isn't advisable to set it up this way. If you were successful in entering your passphrase, this is what you should see (with your username of course):

```
PTY allocation request failed on channel 1
Hi jrhorn424! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```

After you figure out your passphrase, do `ssh-add`.

Please add the output of `git remote -v` in a response.

After you've done all these steps, I'll answer the question of how to get out of `gh-pages`.

**Comment by wilsonkaya** [comment]
```
$ git remote -v
origin	git@github.com:wilsonkaya/tic-tac-toe.git (fetch)
origin	git@github.com:wilsonkaya/tic-tac-toe.git (push)
```

**Comment by MicFin** [comment]
@wilsonkaya what do you get when you run `ssh -T git@github.com` in the terminal ?

**Comment by wilsonkaya** [comment]
Hi wilsonkaya! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by jrhorn424** [comment]
Paste what you see when you try to `git checkout whatever-branch-you-are-trying-to-reach`.

**Comment by wilsonkaya** [comment]
```
 git checkout master
error: The following untracked working tree files would be overwritten by checkout:
	assets/auth/api.js
	assets/auth/events.js
	assets/auth/ui.js
	assets/scripts/config.js
	assets/scripts/events.js
	assets/scripts/example.js
	assets/scripts/gamelogic.js
	assets/scripts/index.js
	assets/scripts/store.js
	assets/scripts/templates/helpers/.keep
	assets/styles/index.scss
	grunt/aliases.json
	grunt/jasmine.json
	grunt/jscs.json
	grunt/jshint.json
	grunt/jsonlint.json
	grunt/paths.json
	grunt/shell.js
	grunt/webpack-dev-server.js
	grunt/webpack.js
	lib/add-nested-value.js
	lib/get-form-fields.js
	lib/parse-nested-query.js
	lib/set-api-origin.js
	spec/_all.js
	spec/example.spec.js
Please move or remove them before you switch branches.
Aborting
~/wdi/projects/tic-tac-toe (gh-pages)

```

**Comment by jrhorn424** [comment]
Follow the steps from #406

**Comment by wilsonkaya** [comment]
I did it. It comes to a point that I can't delete,

```
On branch gh-pages
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	assets/
	grunt/
	lib/
	node_modules/
	spec/

nothing added to commit but untracked files present (use "git add" to track)
~/wdi/projects/tic-tac-toe (gh-pages)
```

**Comment by jrhorn424** [comment]
I see. Try `git clean -di` if you need to get rid of directories as well as files. If you do delete directories, you will need to run `npm install` again.

**Comment by wilsonkaya** [comment]
Thank you very much. Everything worked perfectly.
