### ISSUE TITLE
Getting ID from html to js

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#435]
I am having trouble registering a winner.
I have a checkWinner() function, which fetches values from row() function, which gets it's value from data(), which in turn gets data from html.

I believe my issue lies within the data() and what it is fetching to put in row() but I don't understand.
I expect the value of the IDs of the rows in order for it to check for a winner.

game engine:
```
function data() {
  // need to be able to get the number whatever it is, not all of them...
  document.getElementById(0,1,2,3,4,5,6,7,8);
}

function row(a, b, c) {
  let result = false;
  if ((data(a) === document.turn) && (data(b) === document.turn) & (data(c) === document.turn)) {
    result = true;
  }

  return result;
}

function checkWinner() {
  let result = false;
  if(row(0, 1, 2) ||
     row(3, 4, 5) ||
     row(6, 7, 8) ||
     row(0, 3, 6) ||
     row(1, 4, 7) ||
     row(2, 5, 8) ||
     row(0, 4, 8) ||
     row(2, 4, 6)) {
       result = true;
     }

     return result;
}

function switchTurn() {
  if (checkWinner(document.turn)) {
    alert(document.turn + ' Wins!');
    document.winner = document.turn;
  } else if(document.turn === 'X') {
    document.turn = 'O';
  } else {
    document.turn = 'X';
  }
}

function noRepeat(circle) {
  if (document.winner !== null) {
    return  alert(document.turn + ' Wins!');
  } else if (circle.innerText === '') {
    circle.innerText = document.turn;
    switchTurn();
  } else {
    alert('already taken');
  }
}
```

html:
```
        <div class="gameboard">
            <div class="circle" onClick="noRepeat(this)" id="0">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="1">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="2">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="3">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="4">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="5">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="6">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="7">
            </div>
            <div class="circle" onClick="noRepeat(this)" id="8">
            </div>
         </div>
```

**Comment by BenGitsCode** [comment]
Take a look at this https://github.com/ga-wdi-boston/game-project/issues/429#issuecomment-275446909

**Comment by jrhorn424** [comment]
```
  document.getElementById(0,1,2,3,4,5,6,7,8);
```

Where did you find that? It isn't jQuery. You should use jQuery. If you're curious as to why it's not working anyway, reference the `getElementById` method signature and check what argument(s) it takes, and their types.

```
document.turn
```

Why are you doing this? Do you know what it does?

These patterns remind me of a very old solution to this from when I worked at the GA DC campus.


```
  if (checkWinner(document.turn)) {
```

How many arguments are you passing? How many parameters are defined?


```
            <div class="circle" onClick="noRepeat(this)" id="0">
```

Why are you using the `onClick` attribute?

```
function noRepeat(circle) {
```

Why is the argument called circle?

**Comment by doremaxime** [comment]
Bernard told me not to use jquery in the file (https://github.com/ga-wdi-boston/game-project/issues/419) so i saw in my memory game i had used the 'document.' technique, thought i'd give it a try and thought onClick in my html wasn't jquery. My original code had a lot of jquery so i started from scratch. i looked at a bunch of video and this is for now the best i can come up with.
I call it circle because my 3x3 is made of circles. Also, in https://github.com/ga-wdi-boston/game-project/issues/429#issuecomment-275446909 I saw that we are not to use numbers as IDs so I changed them to TL, TC, TR, ML, etc...

**Comment by jrhorn424** [comment]
@doremaxime Thanks for the info! The reason you shouldn't use jQuery in your engine file is because you shouldn't be accessing the DOM at all in your engine file. That means `document` is out. I'm not sure I've made this clear previously, but if you're going to test your code in node, it can't reference the DOM since there's no DOM in the command line.

If you want to use jQuery and the DOM to store your data instead of a board array, that's fine. But then you can't test it in node. The only way to test it at that point is in the browser.

The point about not using numeric ids is a good one, but I'm not sure you need ids at all for your tiles.

**Comment by doremaxime** [comment]
should i restart my game engine a 3rd time? i spent all of today writing the version with the document. because the jquery version wasn't accepted. Which leads to another question: where and when do i use jquery then because my index.js has to be plain javascript.

**Comment by jrhorn424** [comment]
> should i restart my game engine a 3rd time?

I'm not sure.

> because the jquery version wasn't accepted.

I understand the frustration there. It wasn't that the jQuery version was unacceptable per se, it was that you were having trouble debugging it (and we were too). Using jQuery for the logic makes the code more complex than it has to be, which adds to the time and effort required to debug it. Sometimes, the right answer is to delete that code and try again.

> where and when do i use jquery then because my index.js has to be plain javascript

It isn't about what's in `assets/scripts/index.js`. It's about the engine. If that's where the engine is stored, then yes, it should be JS without the DOM. I think a better place to store the engine is `assets/scripts/game/engine.js`.

Use jQuery to interact with the browser. Your `ui` code will utilize jQuery to manipulate the DOM. Those click handlers will also likely use code from your `api` and from your `engine`. But that's not the same thing as the `engine` using the DOM.

A different way of putting it is that you can use your engine inside your jQuery, but you can't use jQuery inside your engine (where "can't" really means "shouldn't").

**Comment by MicFin** [comment]
@doremaxime did this work? Please update use on how the issue is going or close it with your solution as a commentif it is solved

**Comment by doremaxime** [comment]
I have restarted my gameEngine and doing it differently, therefore i do not have a solution or working towards a solution to that problem. don't know if i am allow to close this issue with that answer...

**Comment by MicFin** [comment]
Thanks @doremaxime.  Make a final comment and do your best to verbalize what you are going to do differently then you may close the issue.

**Comment by doremaxime** [comment]
in my new version i am not using jquery at all nor 'document.'.
it is plain javascript and therefore unrelated to the initial issue.
