### ISSUE TITLE
Clarification of documentation regarding update api

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/game-project#436]
I'm reading through the documentation to try to understand what each action is supposed to do.  I thought that the `update` function is supposed to run after every move, so the game board on the server gets updated every turn.  This would imply that we tie the `update` function to the function that makes a move, so it would update automatically.  However, the documentation has this written in the **update a game's states** section:

```
<form>
  <input name="game[cell][index]" type="text" value="0">
  <input name="game[cell][value]" type="text" value="x">
  <input name="game[over]" type="text" value="false">
</form>
```

Doesn't a form mean that the user must input something?  If update is supposed to happen automatically, why would we need the user input from a form?

**Comment by jrhorn424** [comment]
> Doesn't a form mean that the user must input something? If update is supposed to happen automatically, why would we need the user input from a form?

Great question!

It's an example to show you what sort of data is required, if I recall correctly.

The update should happen automatically on click. Thanks for reading thoroughly!
