### ISSUE TITLE
js creating a method that will allow a player to switch turns

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/game-project#439]
I created a constructor function to represent my game, I listed its properties and defined the winning combinations.

```
const Game = function (board) {
  this.board = board;
  this.currentPlayer = 'x';
  this.currentGameMoves = 0;
  this.wins = [
        [0,1,2],[3,4,5],[6,7,8], // Row
        [0,3,6],[1,4,7],[2,5,8], // col
        [0,4,8],[2,4,6]]; // diag

};
```

I now want to prototype the methods to play the game, One of those would be changeTurns and i'm having a difficult time creating the function. I've used MDN and the prototyes repo to assist and I'm still unable to come up with a working function. 
 
Please see code below. 

P.S - May I also request a quick code/structure review?

```
//establish a turn counter

/*Game states/statuses
  not started
  inProgress
  winner=X O
  gameTied
*/


//establishes moves.
Game.prototype.setMove = function (i){
  this.board[i] = this.currentPlayer;
};

// make a method on the Game object that changes the player
Game.prototype.changePlayer = function (){
  this.currentPlayer =
// this function should change the player after a move has been made by the opposite player

};
//
//establish player wining or losing

//clear the board
//function that resets the board. Can this be turned into a method
const resetGameBoard = function() {
  for (let i = 0; board.length; i++) {
    board[i] = "";
    $('.box').text(''); //box for html boxes
  }
};


//full board function
isFull;: function() {
  for(let i = 0; i < 9; i++) {
    if (this.board[i] === this.EMPTY) {
      return false;
    }
  }
  return true;
},
```

**Comment by jrhorn424** [comment]
> One of those would be changeTurns and i'm having a difficult time creating the function.

Can you explain to me what the function should do in English?

**Comment by jrhorn424** [comment]
> P.S - May I also request a quick code/structure review?

Yes, in a separate issue. I'm happy to tell you that you look like you're on the right track! I'd like for `reset` and `isFull` to be part of the prototype as well. I think that might help. Also, how are you storing the board? should it be part of the Game object?

**Comment by jrhorn424** [comment]
>  I've used MDN and the prototyes repo to assist and I'm still unable to come up with a working function.

AFAICT you're using prototypes as intended. The problem you're running into is how to express what you want the changePlayer function to do. It doesn't have anything to do with (mis)understanding prototypes, I think.

**Comment by bernardlee** [comment]
Translate this into code: If the current player is "x", then change the current player to "o".  Otherwise, change the current player to "x".

**Comment by AshlenPrice** [comment]
The changeTurns function would check the board if the current player has made a move and then  if that's true then it would change turns.

- I will work on creating those prototypes.

Thank you for the feedback. I have reviewed it and ended up with the code below. Created the conditions under which the computer would allow a player to change turns and not override the other players move through a series of if and if else statements. Tested it in node and it worked. 

Thank you!
```
//establishes who moves.

Game.prototype.setMove = function (i){

//is a condition that means is the game space is empty and it allows the rest of the function to run.
  
  if (this.board[i]=== ''){
  this.board[i] = this.currentPlayer; 

// this function should change the player after a move has been made by the opposite player

  if (this.currentPlayer === 'x'){
      this.currentPlayer = 'o';
  } else if (this.currentPlayer === 'o'){
      this.currentPlayer = 'x';
  }
  }
};
```
