### ISSUE TITLE
Can't sign out

### ISSUE THREAD

**Issue by kylekatz** [ga-wdi-boston/game-project#44]
No Access Control Origin header?
`DELETE http://tic-tac-toe.wdibos.com/sign-out 
kylekatz.github.io/:1 XMLHttpRequest cannot load http://tic-tac-toe.wdibos.com/sign-out. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://kylekatz.github.io' is therefore not allowed access. The response had HTTP status code 404.`

**Comment by RealWeeks** [comment]
Can you paste in you're sign out Ajax request?

**Comment by kylekatz** [comment]
```
$('#sign-out').on('submit', function(e) {
    e.preventDefault();
    var formData = new FormData(e.target); // grab FormData
    $.ajax({
      //url: 'http://httpbin.org/post',
      url: myApp.baseUrl + '/sign-out',
      method: 'DELETE',
      contentType: false,
      processData: false,
      data: formData,
    }).done(function(data) {
      myApp.user = data.user;
      console.log(data);
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
  });
```

**Comment by gaand** [comment]
From the api docs, the path is `/sign-out/:id`.  So you have to include the user's id at the end.

**Comment by RealWeeks** [comment]
@kylekatz did this correct the issue?

**Comment by kylekatz** [comment]
Well, I suppose it corrected one issue, but it still doesn't work. Now it looks like this:

``` js
$('#sign-out').on('submit', function(e) {
    e.preventDefault();
    var formData = new FormData(e.target); // grab FormData
    $.ajax({
      //url: 'http://httpbin.org/post',
      url: myApp.baseUrl + '/sign-out/:117',
      method: 'DELETE',
      contentType: false,
      processData: false,
      data: formData,
    }).done(function(data) {
      myApp.user = data.user;
      console.log(data);
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
  });
```

**Comment by kylekatz** [comment]
Do I have to put the token in somewhere?

**Comment by kylekatz** [comment]
I still can't get this to work...anyone?

**Comment by gaand** [comment]
Yes, you have to pass the token header as we did in the api-token-auth lesson.

Also, please put the triple-backticks on separate lines above and below your code snippets.

**Comment by kylekatz** [comment]
Oh. Above. Gotcha. Thanks.

**Comment by RealWeeks** [comment]
@kylekatz Do you still need assistance with this?  If not please close, if so please respond and someone will gladly answer.
