### ISSUE TITLE
Confusion writing API for game action - GET	/games	games#index

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/game-project#442]
- Working on: I am writing the API to execute the first game action (see below) 

> Request	Response
> Verb	URI	body	Status	body
> GET	`/games[?over=]`	n/a	200, OK	games found

- Resources used: For this, I am looking at the following lesson on 'GET' 
https://github.com/ga-wdi-boston/jquery-ajax-get/blob/solution/assets/scripts/books/events.js 

-Problems encountered

1. To build a function in the events file, I need to refer to an id to get the game.
2. In order to use the id, shouldn't I create a game first POST and obtain id, then create GET and refer to the id of the game created. 
3. I see the id requested in books is accessed using jquery, which means, there is an element in the HTML with that name; so, is my HTML to have the mentioned one? (I think no, but please correct me if I am wrong).

-My code

**api_game.js**
```javascript
//get game
const game = function () {
  return $.ajax( {
    url:config.apiOrigin + '/games[?over=]',
    method: 'GET',
  });
};
```

**events_game.js**
```javascript
const onGetGame = function (event) {
  event.preventDefault();
  //let gameId = $()....
};
```
Thank you!

**Comment by bernardlee** [comment]
The `GET` action for the `/games` route doesn't require an `id` if you're requesting an index of all games.

**Comment by MicFin** [comment]
@yenpraja610 did this work? Please update us on how the issue is going or close it with your solution as a comment if it is solved

**Comment by s0phi4** [comment]
Got it :) Jackson explained in more detailed and it helped 
here is solution
api file:
```javascript
const game = function () {
  return $.ajax( {
    url:config.apiOrigin + '/games',
    method: 'GET',
  });
};
```

events file:

```javascript
const onGetGame = function (event) {
  event.preventDefault();
  api_game.game()
  .then(ui.success)
  .catch(ui.failure);
};
```

Thank you!!!

**Comment by jrhorn424** [comment]
These two names are misleading:

```js
// api.js
const game = function () { /* ... */ }
//...
// events.js
const onGetGame = function (event) {{ /* ... */ }
```

I would call the first one `index`, since you're getting a list of all the games. Then, for the handler, I'd name it `onGetGames` not `onGetGame`, since you will be retrieving multiple games and not just a single game.
