### ISSUE TITLE
Trouble with putting X actually on the board. 

### ISSUE THREAD

**Issue by cshea93** [ga-wdi-boston/game-project#444]
Having a difficult time getting X to appear on the board this time around. Have tried a variety of different jquery methods. Not sure if its my click handler or the way I am attempting to use my 'tiles' class. 

Here is the involved logic..

```javascript
// global variables
let board = ['', '', '', '', '', '', '', '', ''];
let player = 'x';

//switch between x and o function
let player_turn = function () {
  if(player === 'x') {
    player = 'o';
  }
  else {
    player = 'x';
  }
  console.log(player + '' + 'Your turn!');
};

//play x or o depending on player_turn;
const play_move = function(tiles){
  $(tiles).text(player);
  console.log('nice move');
};

//create game board that puts value in correct game board/tile index
// one of the two below?

let setGameArray = function (tiles) {
  let index = $(tiles).data('.board');
  board[index] = player;
  console.log(board);
};
```

and my handler for this event..

```javascript
const addHandlers = () => {
  $('.tiles').on('click', onTileClick);
    if ($('.tiles').text() === '') {
      $( ".tiles" ).text(player);
    }
    else {
      alert('error');
    }
};
```

**Comment by cshea93** [comment]
![image](https://cloud.githubusercontent.com/assets/16327726/22374562/a9675bf2-e474-11e6-872d-4df4785754a9.png)

**Comment by cshea93** [comment]
![image](https://cloud.githubusercontent.com/assets/16327726/22374587/c589202c-e474-11e6-8250-5f9dc43de46c.png)

(edited by @bengitscode *No screenshots of code please*)

**Comment by bernardlee** [comment]
Is your repository up to date so that I can look at all of your code?

**Comment by cshea93** [comment]
updating now

**Comment by cshea93** [comment]
updated..

this is what I get when I click my board. 
![image](https://cloud.githubusercontent.com/assets/16327726/22376308/73857c60-e47b-11e6-9e77-bcecbfe28159.png)

**Comment by bernard-ga** [comment]
When you click a tile, `onTileClick()` gets called and then that function calls `play_move()` with `event.target` as its argument.  In `onTileClick()`, `event` is a jQuery `Event` object and `event.target` is an `object` representing a DOM node.  `play_move()` accepts this object as its argument and then selects every element with a `tile` class and sets its text to `player`, which is the object representing the DOM node that got clicked.  This is why every tile is displaying `[object HTMLDivElement]`.

**Comment by bernardlee** [comment]
When you click a tile, `onTileClick()` gets called and then that function calls `play_move()` with `event.target` as its argument.  In `onTileClick()`, `event` is a jQuery `Event` object and `event.target` is an `object` representing a DOM node.  `play_move()` accepts this object as its argument and then selects every element with a `tile` class and sets its text to `player`, which is the object representing the DOM node that got clicked.  This is why every tile is displaying `[object HTMLDivElement]`.

**Comment by cshea93** [comment]
still not getting anywhere with this..how can I move forward in the project without making this function work?

**Comment by bernardlee** [comment]
Ideally, your game logic should be separate from your user interface.  Try writing Tic-Tac-Toe that only involves plain JavaScript (no jQuery or user interface manipulation).  i.e., only use an array to represent the game state and functions to represent the game logic.  Once that's done, you can use jQuery to call those game logic functions and update the user interface based on their inputs and outputs.

**Comment by cshea93** [comment]
my code essentially the same as it was last earlier....on the Feature branch

**Comment by MicFin** [comment]
@cpstrillvt93 are you able to move forward?  Please do not stay stuck.

**Comment by cshea93** [comment]
Thanks, guys. Struggling to separate the logic and the board events conceptually…I believe I was (attempting to) write a function that for both aspects, when in reality I was writing the two functions that dealt with the interface. Fatih and Jackson were a big  help in providing some context to what I am trying to do and what I was doing that wouldn’t work.  

Moving forward..

**Comment by raq929** [comment]
If this issue has been resolved, please post the code that resolved it and close. If not, please update with what the current issue is.

**Comment by cshea93** [comment]
It wasn't a code error, so much as it was a failed attempt at creating logic that would putgame pieces on to the board. Bernard's explanation helped me to back-track to a point in which I could move forward.
