### ISSUE TITLE
trouble checking the condition of winner

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#445]
I am testing my engine in node, specifically the checkWinner and checkEachIndex functions.
In node i have made it so that the is a winning condition for 'x' in my gameBoard. Therefor I expect my checkWinner function to say that 'x' is the winning condition but it is returning undefined.
I believe my issue lies in the for loop of checkWinner but can't get it.

node:
```
~/wdi/projects/tic-tac-toe (feature)
$ node
> const a = require('./assets/scripts/gameEngine.js');
undefined
> a.setToken(0,'x');
undefined
> a.setToken(1,'x');
undefined
> a.setToken(2,'x');
undefined
> a.checkWinner();
undefined
> a.checkWinner
[Function: checkWinner]
> 
```

gameEngine:
```
// this function is not the problem at hand but is later relevant to checkWinner
function checkEachIndex() {
  // check all gameBoard indexes are not empty.
  if ((gameBoard[0], gameBoard[1], gameBoard[2], gameBoard[3], gameBoard[4],
      gameBoard[5], gameBoard[6], gameBoard[7], gameBoard[8]) !== '') {
      return true;
      }
}

// if there are 3 of the same token in a row, then that token wins.
function checkWinner() {

  // winning combinations
  let win = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];

  // if one of these indexes is composed of the same token, then that token wins.
  for (let i = 0; i <= win.length; i++) {
    if (win[i] === ['x', 'x', 'x']) {
      winner = 'x';
      return (winner + ' wins!');
    } else if (win[i] === ['o', 'o', 'o']) {
      winner = 'o';
      return (winner + ' wins!');
    } else if (checkEachIndex() === true) {
      return ("it's a tie");
    }
  }
}

**Comment by doremaxime** [comment]
Furthermore, I truly think it is something wrong with the for loop as the tie condition (with checkEachIndex) works.

**Comment by bernardlee** [comment]
In `checkEachIndex()`, you have to check each index in `gameBoard` in your `if` statement's condition.  i.e., `if (gameBoard[0] === '' && gameBoard[1] === '' && ...) { ... }`.  You can use an array iteration method to make this less tedious.

`checkWinner()` doesn't work correctly because it's trying to compare two arrays in the `if` statements using a strict equality operator and arrays are reference types.  e.g., `win[0] === ['x', 'x', 'x']` is being interpreted as `[0, 1, 2] === ['x', 'x', 'x']`.

**Comment by MicFin** [comment]
The `win` array has 8 elements inside of it.  Your `for loop` is going from 0 up to and including 8 which means it eventually tries to loop through a 9th element **(array indexes start at 0 so an array with 8 elements inside of it should only require looping from 0 to 7)**.
```
for (let i = 0; i <= win.length; i++) {
```

Additionally, instead of having multiple returns in your function at each point in the if statement.  You could just change the value of the variable in the if statement and return that variable.
```
if (win[i] === ['x', 'x', 'x']) {
      winner = 'x';
} else if (win[i] === ['o', 'o', 'o']) {
      winner = 'o';
} else if (checkEachIndex() === true) {
      winner = "Tie, nobody";
}
return (winner + ' wins!');
```

**Comment by doremaxime** [comment]
Thank you both, i believe you both found problems! 
Bernard, i tried to use the every method but ended up not working so i though i'd do it basic for now.
as for your 2nd paragraph: [0, 1, 2] === ['x', 'x', 'x']   that's what i want it to do, to check that each index is the same value. Or am I not getting this?

I will change the for loop from 8 to 7.

**Comment by bernardlee** [comment]
Do you have the code from when you used `every()`?  As for array comparisons, you would have to compare every element in every index of both arrays.

**Comment by bernardlee** [comment]
```node
> const a = [1, 2, 3];
undefined
> const b = [1, 2, 3];
undefined
> a === b;
false
```

**Comment by doremaxime** [comment]
I see, I had not thought about the fact that the variables win and gameBoard were not the same! the function was doing only what it was told! haha

**Comment by doremaxime** [comment]
The way I have thought about going is assigning the indexes of the gameBoard to the possible win combinations by doing so:

```
  // winning combinations (old way)
  let win = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];

  // new way:
  let win1 = gameBoard[0, 1, 2];
  let win2 = gameBoard[3, 4, 5];
  //etc...
```
However, the lint is telling me that the syntax of win1 & win 2 is not right: it expected ']' but instead saw ','. 
Can I not select multiple indexes of an array? i

Also, from you second to last comment: I do not have the code from every(). should have just commented it out :(

**Comment by bernardlee** [comment]
`gameBoard[0, 1, 2]` is invalid syntax because you can only reference one array index and not multiple ones within brackets.  Your old way of storing the winning indices is fine, but you would have to use a nested iterator or loop to check the entire board; an outer one for going through the `win` array itself and an inner one to go through the indices within the nested arrays.

**Comment by doremaxime** [comment]
I got it to work i believe.

My function:
```
// if there are 3 of the same token in a row, then that token wins.
function checkWinner() {

  // if one of these indexes is composed of the same token, then that token wins.
  for (let i = 0; i <= 7; i++) {
    if (win[i] === (gameBoard[0] && gameBoard[1] && gameBoard[2]) ||
                   (gameBoard[3] && gameBoard[4] && gameBoard[5]) ||
                   (gameBoard[6] && gameBoard[7] && gameBoard[8]) ||
                   (gameBoard[0] && gameBoard[3] && gameBoard[6]) ||
                   (gameBoard[1] && gameBoard[4] && gameBoard[7]) ||
                   (gameBoard[2] && gameBoard[5] && gameBoard[8]) ||
                   (gameBoard[0] && gameBoard[4] && gameBoard[8]) ||
                   (gameBoard[2] && gameBoard[4] && gameBoard[6])) {
                    console.log('you win!');
                    restart();
    } else if (checkEachIndex() === true) {
      return ("it's a tie");
    }
  }
}
```

node:
```
> const a = require('./assets/scripts/gameEngine.js');
undefined
> a.setToken(3,'x')
undefined
> a.setToken(4,'x')
undefined
> a.setToken(5,'x')
you win!
undefined
> 
```

**Comment by bernardlee** [comment]
Good job.  You can also try to reduce some tedium while testing by writing some functions specifically for it.  e.g,
```javascript
// Set the entire first row's elements to the specified string.
function setFirstRow(playerToken) {
  setToken(0, playerToken);
  setToken(1, playerToken);
  setToken(2, playerToken);

  // Or: [0, 1, 2].forEach(number => setToken(number, playerToken));
}
```
