### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by newayliu1** [ga-wdi-boston/game-project#447]
After I connect the authentication file to my buttons and tried to sign up. 500 Internal server error pups up. 
 
![screen shot 2017-01-27 at 11 07 38 am](https://cloud.githubusercontent.com/assets/19287350/22377682/dc3cec5c-e480-11e6-80ec-fb0f63b0541b.png)

I have no idea what is wrong with my code.

**Comment by BenGitsCode** [comment]
Please post copied and pasted text instead of screenshots. 

You have more ideas than you realize. Your server is responding with `500 (Internal Server Error)`

Where do you think you could look for more information on that server errror?

**Comment by newayliu1** [comment]
I did check my API server. It says 
You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from validate_secret_key_config! at /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:530)

**Comment by BenGitsCode** [comment]
Are you trying to deploy the `game-project-api` server? I would recommend against that if so. 

If not, I'd like to see your `assets/scripts/config.js`

What URL are you pointing at?

**Comment by newayliu1** [comment]
I am running the project API server in my computer.

**Comment by newayliu1** [comment]
'use strict';

const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com',
  },
};

module.exports = config;

This is what I have in config.js.

**Comment by BenGitsCode** [comment]
I think you're confusing front and back end servers here. This file should connect to your API server.  You shouldn't be running or deploying an API server yourself. You're running a client server.

https://github.com/ga-wdi-boston/game-project/issues/400 Reference this issue and see if that helps clear it up.

**Comment by BenGitsCode** [comment]
Also check the  `016/code` channel in slack.

**Comment by newayliu1** [comment]
I just realize the project api we are using is a internet server. I think I get it.

**Comment by BenGitsCode** [comment]
Remember this drawing from last week?
![server/client](https://i.gyazo.com/6e2bad203cc43202556ef4481ada6e3a.png)

For this project we need to send requests to an existing API but we won't be working on that API itself, just using it.

**Comment by newayliu1** [comment]
I run two servers, client and game api, before. I thought the game api server is local one.

**Comment by BenGitsCode** [comment]
@newayliu1 Are you sure this issue was resolved? Please post your solution if so.
