### ISSUE TITLE
html / bootstrap problem

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/game-project#448]
I was under the assumption that in bootstrap the divs had a float left auto set;
i checked the bootstrap website and it looks like it should work, and there are no linters.
my code is:
```
 <div class="row">
           <div class="clearfix col-xs-4 box">box0</div>
           <div class="col-xs-4 box">box1</div>
           <div class="col-xs-4 box">box2</div>
         </div>
```
I was trying out a clearfix but nothing changed.

**Comment by BenGitsCode** [comment]
I can see linter errors in that already. What is the output of `grunt test`

**Comment by BenGitsCode** [comment]
What are you trying to do?

**Comment by MicFin** [comment]
Use your web browser inspector to see what CSS properties are being applied by each class.

Let me know:
1.  What CSS the `row` class is applying to your parent `div`
2.  What CSS the `col-xs-4` class is applying to the child `div`s
3.  What CSS the `box` class is applying to the child `div`s
4.  What CSS the `clearfix` class is applying to the first child `div`

**Comment by Soboscott** [comment]
sorry,
It was not a problem with my html, it was a problem with getting the right file on the right server.
when I was making changes nothing was happening.  but Andrew helped me out.
