### ISSUE TITLE
Click handler does not seem to be working

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/game-project#450]
I gave my id's number values in the form of strings and converted them to actual numbers, but now when I click on the boxes, nothing appears. my divs have classes of cell and box and id's of numbers as strings like so:
`  <div class="cell box" id="0" ></div>`

Here is my code:

```js
let boxes = $('.box');
  boxes.on('click', function(event) {
    if ($(event.target).text() === '') {
      $(event.target).text(currentPlayer);
 
    }
    let conversion = parseInt(event.target.id);
    turns(conversion);
    console.log(board);
  });
let boxes = $('.box');
  boxes.on('click', function(event) {
    if ($(event.target).text() === '') {
      $(event.target).text(currentPlayer);
 
    }
    let conversion = parseInt(event.target.id);
    turns(conversion);
    console.log(board);
  });
```

**Comment by BenGitsCode** [comment]
Please format code/error snippets in code blocks.

**Comment by bernardlee** [comment]
Can you update your repository so that I can everything that you current have?

**Comment by alexkarasik** [comment]
I just updated it. Sorry for the delay.

**Comment by bernardlee** [comment]
[`assets/scripts/index.js`](https://github.com/alexkarasik/TicTacToe/blob/myttc/assets/scripts/index.js) line [`19`](https://github.com/alexkarasik/TicTacToe/blob/myttc/assets/scripts/index.js#L19)

**Comment by alexkarasik** [comment]
That was it! Thank you so much!

**Comment by MicFin** [comment]
@alexkarasik please close if this issue is resolved
