### ISSUE TITLE
Low Priority - why doesn't ${var} work like I expect?

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/game-project#452]
Hey Team!

[low priority, issue is resolved but I don't understand why]

I've tried googling it to no avail, and while I came with a solution I'd like to know more about why what I did didn't work... even though I got distracted by other problems since and forgot to file the issue...

I'm trying to patch an update to the server.  my code looks like this:

```js
let gameId = 21369

const updateBoard = function (data) {
  return $.ajax({
    url: "${config.apiOrigin}/games/${gameId}",
    method: 'PATCH',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};
```

if the url line reads: `url: "${config.apiOrigin}/games/21369"`,
then the patch will go through correctly.

I wound up storing the data in the assets/store.js object, specifically under store.gameId key, so the final URL is `url: "${config.apiOrigin}/games/${store.gameId}"`, and this works, but I don't understand why!

**Comment by MicFin** [comment]
Review https://www.sitepoint.com/use-jquerys-ajax-function/
Particularly `url: A string containing the URL to which the request is sent`

**Comment by dsweetser** [comment]
OOOOOOOH. so it wasn't be converted to a string!!!!! thank you!

**Comment by jrhorn424** [comment]
:smile: Backticks are not quotes.
