### ISSUE TITLE
I can't get the grid to display with bootstrap

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/game-project#453]
This is my code set up in my html file to create the grid in theory, 

```</head>
    <body class="container-fluid">
      <h1> Tic Tac Toe!!!</h1>
      <div class="container-fluid">
      <div class="row">
        <div class="col-xs-4">XXX</div>
        <div class="col-xs-4">OOO</div>
        <div class="col-xs-4">XXX</div>
      </div>
      <div class="row">
        <div class="col-xs-4">X</div>
        <div class="col-xs-4">O</div>
        <div class="col-xs-4">X</div>
      </div>
      <div class="row">
        <div class="col-xs-4">X</div>
        <div class="col-xs-4">O</div>
        <div class="col-xs-4">X</div>
      </div>
    </div>
    </body>
```
which I styled following the guide on http://getbootstrap.com/css/?#grid-options

and it isn't displaying.

**Comment by jrhorn424** [comment]
Check your server log. If it isn't displaying, it's likely due to a syntax error in your JS. Please run `grunt nag`.

**Comment by novakw267** [comment]
I only had style errors, and I am working on fixing those now which were mostly in the game.js file. I do have an error in the inspect when I try to load the front end server saying that with 

`
require('./assets/scripts/index.js');
`
it says uncaught error.cannot find module, which only contains this. I assume I am missing something to connect these pieces. 

```
'use strict';

// user require with a reference to bundle the file and use it in this file
// var example = require('./example');

// load manifests
// scripts
require('./assets/scripts/index.js');

// styles
require('./assets/styles/index.scss');
```

  I am not sure if that's helpful I am trying to find any indication on google what maybe missing from this file or at all.

**Comment by novakw267** [comment]
I figured it out. Thanks.
