### ISSUE TITLE
requirement clarification

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/game-project#454]
When the requirements say you should 'visually display the results of retrieving game statistics' does this mean only completed games or should we include games that are in progress? 

If in progress games are required, does that include letting a player pick up an incomplete game by inputing a game ID (e.g. given by pushing a button that would show IDs for incomplete games)?

Use AJAX for interacting with a provided API. Specifically, your app must:

Visually display the results of retrieving game statistics, such as total games won by a user. (READ)
Create new games on the server. (CREATE)
Update a game by storing new moves. (UPDATE)

**Comment by jrhorn424** [comment]
> does this mean only completed games or should we include games that are in progress

That is your choice. You have enough data to display either, or both. Just be sure to clearly communicate to your user what you are showing them.

> If in progress games are required, does that include letting a player pick up an incomplete game by inputing a game ID (e.g. given by pushing a button that would show IDs for incomplete games)?

No, not required to pick up incomplete games. But if you do, you'll be the first developer to do so in my experience, and that would be really cool.

**Comment by cob0910** [comment]
Great, thanks for clarifying!
