### ISSUE TITLE
[JavaScript] Issue with getting my sign in buttons from auth

### ISSUE THREAD

**Issue by SquirtleSquad1988** [ga-wdi-boston/game-project#457]
Having trouble getting my sign in, sign up, and buttons to work in general on my page. I copied and pasted the code from the jquery-ajax-patch auth folder but I don't think the addHandlers function is being properly exported from my events.js file in the auth folder (located in my assets folder). When I click on any of the buttons that are using code from other files other than index.js(where my functional code is stored) the page refreshes (I have event.preventDefault in the appropriate places) Here are some snippets of code from a few of my files. For the purposes of this issue I will only focus on the sign up button since that was the thing I was trying to get working. From looking at other peoples code I know my code works I think the addHandlers export is not being exported properly:

events.js in my auth folder:
```js
const api = require('./api');
const ui = require('./ui');
const store = require('../store');

const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signUp(data)
    .then(ui.success)
    .catch(ui.failure);
};

const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp);
  $('#sign-in').on('submit', onSignIn);
  $('#change-password').on('submit', onChangePassword);
  $('#sign-out').on('submit', onSignOut);
};

module.exports = {
  addHandlers,
};
```

api.js
```js
const config = require('../config');
const store = require('../store');

const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data,
  });
};

module.exports = {
  signUp,
  signIn,
  passwordChange,
  signOut,
};
```

config.js in my scripts directory:
```js
const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com',
    development: 'http://tic-tac-toe.wdibos.com',
  },
};

module.exports = config;
```
Where is the addHandlers variable being imported?

Thanks and let me know if you have any question or require any clarifications

-Alex

**Comment by bernardlee** [comment]
Is your current repository up to date?  If so, then I'll clone it and take a look.

**Comment by BenGitsCode** [comment]
It would be imported wherever you require the file it was defined in. That I can see, it isn't being required in any of these files. 

>From looking at other peoples code I know my code works

You only know if your code works by testing your code, and seeing it work.

**Comment by SquirtleSquad1988** [comment]
I just pushed my code. It is in my working directory.

**Comment by bernardlee** [comment]
Here is the cause of your issue: [`assets/scripts/index.js`](https://github.com/SquirtleSquad1988/tic-tac-toe/blob/working/assets/scripts/index.js) line [`132`](https://github.com/SquirtleSquad1988/tic-tac-toe/blob/working/assets/scripts/index.js#L132).

**Comment by SquirtleSquad1988** [comment]
I deleted the line but the problem still persists.

**Comment by bernardlee** [comment]
`.ready()` takes a callback function as an argument.

**Comment by SquirtleSquad1988** [comment]
I reinstated the deleted line and formatted it correctly so that the event, 'click', was removed leaving only the function remaining
