### ISSUE TITLE
Complete project?

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/game-project#459]
Hey team!

I think I've got a project that meets requirements, can I get someone to look it over for me?

Thanks!
Dan

**Comment by BenGitsCode** [comment]
Happy to take a look at it. It's fully updated on github, and deployed?

**Comment by dsweetser** [comment]
Not yet deployed, I'm working on one more function that's above and beyond scope.  The most recent branch is api.

**Comment by BenGitsCode** [comment]
>Not yet deployed, I'm working on one more function that's above and beyond scope.

I'd recommend deploying your project at requirements first, then working on "above and beyond scope" features on a separate branch.

**Comment by MicFin** [comment]
@dsweetser once deployed let us know!

**Comment by dsweetser** [comment]
@MicFin a version of it is deployed without the last bit I was working on (getting a fetched game to display on the board).
