### ISSUE TITLE
Need help checking for bugs

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/game-project#462]
My project currently meets requirements, with the exception of potential bugs and any console logs that might be hiding out in parts of the code. I would like some help testing for bugs.

There are a couple things I am aware of, namely that the modals don't close when you've submitted the forms (the inputs also don't clear) and the user experience is terrible.

Here's the deployed version:
https://sofistication.github.io/tic-tac-toe/

**Comment by MicFin** [comment]
Sign Up: 
I clicked on Sign Up and a pop form was triggered.  When I filled out the pop up form and hit submit, nothing happened (it did console.log a new user object).  I closed the pop up manually and then clicked New Game and nothing happened.  

Sign In:  
I clicked on Sign in and a pop form was triggered.  When I filled out the pop up form and hit submit nothing happened (it did console.log the user object I had created).   I closed the pop up manually and then clicked New Game and nothing happened.

New Game:  
When I click New Game, nothing happens.  The error in the console was
```
Uncaught TypeError: Cannot read property 'token' of undefined 
at Object.create 
at Object.onCreateGame
```
and pointed to the following line in your code
```
	    headers: {
	      Authorization: 'Token token=' + store.user.token
	    }
	  });
```

**Comment by samordonez** [comment]
Sign Up doesn't currently sign you in automatically, so that is expected. I'm not sure why it wasn't letting you start a new game after signing in though. I'll look into it, thanks.

Edit: New Game is working fine after I sign in, could you show me the bug in person if you have the time?

**Comment by samordonez** [comment]
I've updated my deployed version with what is hopefully a fix for those bugs. The new game issue will still be there unless I accidentally fixed it.

**Comment by raq929** [comment]
Please post the code that fixed the bugs and close the issue!

**Comment by samordonez** [comment]
The New Game bug was solved by just hiding the button from users before they logged in.

I added a number of lines like this:
`$('#signInModal').modal('hide');`
to my success functions in order to hide the modals once users had logged in/signed up etc.
