### ISSUE TITLE
click handler

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#463]
I am having issues with the click handler. the lint in my html says that addHandlers is not defined.
both files are connected though.. I would like it to connect in order for me to check if clicking a circle would change it to whatever the token is at that time.

```javascript
const ticTacToe = require('./gameEngine');

// i need a to be able to click on an id within the class gameboard, which inserts the token and disables the click.
const addHandlers = (user, count) => {
  $('.gameboard').find('div').on('click',function () {
    $(this).text(user);
    count++;
  });
};

module.exports = {
  addHandlers,
};
```

js:
```javascript
const index = require('./index');

// inserts token into array.
const setToken = function (a, b) {

  // a = the index, b = the token we insert.
  if (gameBoard[a] === '') {
    gameBoard[a] = b;
    addHandlers(user, count);
    counter();
    switchTurn();
  } else {
    console.log('already taken');
  }

  // check for a winner/tie.
  checkWinner();

};

module.exports = {
  setToken,
};
```

**Comment by bernardlee** [comment]
Am I correct in assuming that the first file is `assets/scripts/index.js`?  If so, then the next file, assuming that `const index = require('./index');` is successful, will set `index` to `{ addHandlers: [Function: addHandlers] }`.

**Comment by doremaxime** [comment]
yes it is ```assets/scripts/index.js```. but addHandler is a function that is being called, so i don't see what the issue is. user and count are being recognized on both files but not addHandlers.

**Comment by bernardlee** [comment]
From what I'm seeing here, you're importing `assets/scripts/index.js` as `index`, but it's imported as an object with `addHandlers` as a property on the imported object.  Because of this, you can't call `addHandlers()` because it doesn't exist.  If you'd like, update your repository so that I can see if I'm misinterpreting the problem.

**Comment by doremaxime** [comment]
i've pushed it.

**Comment by bernardlee** [comment]
I tested your issue for a little bit and it turns out that it's a circular dependency issue.  Basically, `assets/scripts/index.js` `require`s `assets/scripts/gameEngine.js`, but `assets/scripts/gameEngine.js` `require`s `assets/scripts/index.js`.  One way that you can fix this is to move `addHandlers()` to another file, set its `module.exports`, and `require` it in the files that need it.

**Comment by doremaxime** [comment]
I did that but still no luck. i will put the jquery in the engine as this is preventing me from advancing for now. i'll meet up with people tomorrow so i'll see how they do it.

**Comment by doremaxime** [comment]
i've had everything in the file but i've been failing at the getting a token to show up on the board for the past couple hours..
I've tried it a few different ways but none worked and feel quite lost.
```
$(document).ready(function() {
  const addHandlers = () => {
    $('.gameboard').click(function () {
      $(this).closest('.circle').append(user);
      setToken();
    });
  };
});
```
and 
```
const addHandlers = () => {
  $('#TL').on('click', setToken);
  $('#TC').on('click', setToken);
  $('#TR').on('click', setToken);
  $('#ML').on('click', setToken);
  $('#MC').on('click', setToken);
  $('#MR').on('click', setToken);
  $('#BL').on('click', setToken);
  $('#BC').on('click', setToken);
  $('#BR').on('click', setToken);
};
```
and
```
document.addEventListener("click", function(){
    document.getElementsByClassNames("circle").innerHTML = user;
});
```
do you have a recommendation as to which to further pursue if any?

**Comment by doremaxime** [comment]
i have also tried:
```
$('.gameboard').on('click', function () {
  console.log('hi');
});

$(document).ready(function() {
  $('.gameboard').on('click', function () {
    console.log('hi');
  });
});

$(document).ready(function() {
  $('.gameboard').on('click', '.circle', function () {
    console.log('hi');
  });
});

$(document).ready(function() {
  $('.gameboard').click(function () {
    console.log('hi');
  });
});
```

**Comment by doremaxime** [comment]
update: 
the browser is recognizing a click. here is my code now:
index.js:
```
const gameEngine = require('./gameEngine');

$(() => {
  setAPIOrigin(location, config);
});

// use require with a reference to bundle the file and use it in this file
// const example = require('./example');

// use require without a reference to ensure a file is bundled
const authEvents = require('./auth/events.js');

// On Document ready
$(() => {
  $('#user-destroy').on('submit', authEvents.onDeleteUser);
  $('#edit-user').on('submit', authEvents.onPatchUser);
  $('#add-user').on('submit', authEvents.onPostUser);
  $('#TL').on('click', gameEngine.setToken);
  $('#TC').on('click', gameEngine.setToken);
  $('#TR').on('click', gameEngine.setToken);
  $('#ML').on('click', gameEngine.setToken);
  $('#MC').on('click', gameEngine.setToken);
  $('#MR').on('click', gameEngine.setToken);
  $('#BL').on('click', gameEngine.setToken);
  $('#BC').on('click', gameEngine.setToken);
  $('#BR').on('click', gameEngine.setToken);
});
```

gameEngine.js
```
// inserts token into array.
const setToken = function () {
  if (count % 2 === 0) {
    this.innerHTML = 'x';
    checkWinner();
    switchTurn();
    count++;
  } else if ((count % 2 !== 0) && this.innerHTML === '') {
    this.innerHTML = 'o';
    checkWinner();
    switchTurn();
    count++;
  } else {
    console.log('already taken');
  }

  checkWinner();
};

  $('.circle').on('click', function () {
    $(this).closest('.circle').append(user);
  });
```
it doesn't work exactly how I want it to yet but at least the click is being recognized.
I believe the answer was that I didn't have the lines with the IDs in the index.js and and the last 3 lines in the gameEngine.js
Please let me know if this issue can be closed.

**Comment by bernardlee** [comment]
If you think that the original issue has been resolved, then feel free to close this.  From my end, it seems that you've solved your issue of getting click handlers to work.  Feel free to open up other issues regarding other problems though.
