### ISSUE TITLE
AJAX files copy/paste

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#464]
I seem to remember that there are certain files that we are suppose to copy and paste from AJAX repos and leave them as they are, are the ones below some of them? 
```
~/wdi/training/jquery-ajax-patch/scripts/books (training)
$ ls
book-delete.sh	book-index.sh	book-patch.sh	book-show.sh
```
If not, should we still copy these to use as a template? If that's the case I assume we just change all the 'book' with 'user' and 'books' with 'users' as the concept is the same as the class topics: instead of GETing POSTing, etc.. books, we are just creating, fetching, etc.. users. please let me know if i am over thinking this?

**Comment by bernardlee** [comment]
No, those are not required.  Those are just shell scripts with `curl` commands in them that make it easier to test things out without having to tediously type them out each time.  However, you are free to modify them to test out the API if you want.

**Comment by doremaxime** [comment]
ok, i'll keep looking or for the files. thanks for the tip

**Comment by moshiko1988** [comment]
~/wdi/training/jquery-ajax-patch/assets/scripts/books (training)
$ ls
api.js		events.js	ui.js

**Comment by doremaxime** [comment]
thanks! i thought there were more than that but now i am reassured!
