### ISSUE TITLE
404 not found...

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/game-project#466]
I wrote function which modifies an object that is equal to Api format and as you would see I am consoling the object to make it sure that it is in right format. When the click event ocures, it consoles an object in right format. However, In network, it returns two response with the id number of the game. First one is 200 ok and second one 404 not found. I am sure that my function is not called two times. According to information described in API file I should be getting  JSON file." If the request is successful, the response will have an HTTP Status of 200 OK, and the body will be JSON containing the modified game, e.g.:" I can't figure out why response of the server is broken. Below I have shared my function, event, console and error message. 

<== Function  ==>
``` 
let singleUpdate = {
   "game": {
     "cell": {
       "index": 0,
       "value": "x"
     },
     "over": false
   }
 };

let sendMove = function (number){
  singleUpdate['game']['cell']['value'] = currentPlayer;
  singleUpdate['game']['cell']['index'] = parseInt(number.id);
  singleUpdate['game']['over'] = resettingGame;
// console.log(singleUpdate)

};

``` 
<==Object returned by Console ==>
```javascript
Objectgame: Objectcell: Objectindex: 1value: "o"__proto__: Objectover: false__proto__: Object__proto__: Object
2017-01-27 20:05:59.131 
```

<== Click Handler ==>
 ```$("#game-board").on("click", onUpDateGame); ```

<== Event==>
Event,
``` 
const onUpDateGame = function(event){
    event.preventDefault();
    const passmove = game.singleUpdate;
    // console.log(passmove);
    api.updateUserGame(passmove)
    .then(ui.onSuccess)
    .catch(ui.onError);
};

```
<== Error ==>
PATCH http://tic-tac-toe.wdibos.com/games/1621 404 (Not Found)

**Comment by bernardlee** [comment]
Can you push a recent branch onto your repository?

**Comment by wilsonkaya** [comment]
Thank you. I have just found the solution. There were two bugs: First of all I was not storing the necessary informations when I was creating a new game. The second one  I was not using the game id but id of the player. I have corrected these two issues now everything is fine.
