### ISSUE TITLE
Cleaning up?

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/game-project#47]
After ignoring vendor.js and *bundle.js and running grunt rebuild in preparation for loading my page on git hub pages, I noticed a number of mysterious files appeared in my project directory, in addition to spec.js and vendor.bundle.js files. Can I safely delete these? 

https://www.dropbox.com/s/pc4lhtc84b7akuj/Screenshot%202016-02-06%2019.48.43.jpeg?dl=0

**Comment by RealWeeks** [comment]
@rchezrutt88 No.  Also no need to concern yourself with these if everything is working properly.  Does this answer your question?  If so please close, if not please comment further and we would be glad to help.
