### ISSUE TITLE
Patch 

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/game-project#472]
How should update behave when we click the same place twice ? When I click a certain square it sends a patch the server for the first time and when I click the second time it send another one. However, this does not either break my engine or the result. Is it expectable ?

The first response:
XHR finished loading: PATCH 200
```
game: {id: 22606, cells: ["x", "", "", "", "", "", "", "", ""], over: false,…}}
```
The second response:
XHR finished loading: PATCH 200 
```
{game: {id: 22606, cells: ["x", "", "", "", "", "", "", "", ""], over: false,…}
```

**Comment by bernardlee** [comment]
This is expected.

**Comment by wilsonkaya** [comment]
Thank you

**Comment by bernardlee** [comment]
The client that you're writing should prevent duplicate requests being sent.
