### ISSUE TITLE
problems with engine and the loading of the page

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#473]
I add the indexes to the individual click functions in the index.js as such:
```
  $('#TL').on('click', gameEngine.setToken(0));
  $('#TC').on('click', gameEngine.setToken(1));
  $('#TR').on('click', gameEngine.setToken(2));
  $('#ML').on('click', gameEngine.setToken(3));
  $('#MC').on('click', gameEngine.setToken(4));
  $('#MR').on('click', gameEngine.setToken(5));
  $('#BL').on('click', gameEngine.setToken(6));
  $('#BC').on('click', gameEngine.setToken(7));
  $('#BR').on('click', gameEngine.setToken(8));
```
these will be used in as arguments for setToken's parameters. 
For example, if #BR is clicked on, ```setToken``` will have an 'x' or 'o' placed at the 8th index of the gameBoard array.
But by having $().on('click',..... it only makes it so that WHEN you click, that function will called upon right? 
I ask because as the page is being loaded, the browser goes through the checkWinner function and is logging 'it's a tie'. 
I expect the page to load, for the user to click, which adds an x to the board and array making a tie not possible, and then it checks for a winner or tie. but now it is checking for a winner/tie before anything happens:

gameEngine.js:
```
const setToken = function (index) {
  if (gameBoard[index] === '') {
    gameBoard[index] = user;
    if (user === 'x') {
      user = 'o';
    } else if (user === 'o') {
      user = 'x';
    } else {
      console.log('already taken');
    }
  }

  checkWinner();
};
```
I make sure that checkWinner is after the setting of the Token.

**Comment by doremaxime** [comment]
Furthermore,
By setting my ```let user = '';``` variable empty will result the browser to log 'already taken' 9 times.
By only declaring it, it will log 'already taken' 9 times and then log a ```tie```.
By setting my ```let user = 'x';``` variable to ```x``` the browser will log ```x won``` and vice versa with setting it to ```o```. 
Therefore, checkWinner is indeed being run before anything happening.

**Comment by laurpaik-zz** [comment]
Did you set an event target?

**Comment by doremaxime** [comment]
I didn't! didn't know about that, let me look into it!

**Comment by doremaxime** [comment]
Thanks Lauren, I confirm that that's what was missing.
