### ISSUE TITLE
need help with GET index to appear on the screen

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/game-project#475]
Hi,
I have a function that displays the results of the search onto the screen, but it only works for the individual item search, not the full index. I'm copying both for a comparison, but 
```node
const onIndexSuccess = function (data) {
  if (data.games) {
    console.log(data.games);
    for (let i = 0; i < data.games.length; i++) {
      $('#search-result').text(data.game[i].cells);
    }
  }
};

const onGetSuccess = function (data) {
  if (data.game) {
    console.log(data.game);
    $('#search-result').text(data.game.cells);
  }
};
```

I also tried 
```node
const onIndexSuccess = function (data) {
  if (data.games) {
    console.log(data.games);
    for (let i = 0; i < data.games.length; i++) {
      $('#search-result').text(data.games);
    }
  }
};
``` 
which gave me a list of 58 `[object Object]`s. Can someone point me in the right direction?

**Comment by laurpaik-zz** [comment]
also when I try
`$('#search-result').text(data.games.cells);` it doesn't put any text on the screen, though it still prints out in console.

**Comment by bernardlee** [comment]
Your `for` loop body tries to access the `game` property on `data`, which doesn't exist.  Now assume that it's written correctly and accesses the correct property.  What do you think each iteration of the loop is going to do?

**Comment by laurpaik-zz** [comment]
I was trying to make it show each array combination in my history, but I've just been informed we only need to show how many times the user has played? Is this true?

**Comment by bernardlee** [comment]
That isn't relevant to this issue, but the answer is here: [Game Project Requirements](https://github.com/ga-wdi-boston/game-project/blob/master/requirements.md).

**Comment by laurpaik-zz** [comment]
Thank you! Andrew just showed me how I can get the old id information of a game... need to switch to `data.games[i].cells` if I want to use my `for` loop... it only gives me the most recent game, but that was closer to what I expected!
