### ISSUE TITLE
files not working with eachother

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/game-project#478]
having trouble linking the index.js, bootstrap and my scss.
I've tried reverting back to the original,
but something went very wrong,
that's the best way I know how to articulate the problem.

**Comment by raq929** [comment]
Come by and see us during workshop time if this is still an issue. If not, please update with what happened, and close. Thanks!

**Comment by Soboscott** [comment]
I will  seek you out in the morning.
thank you
