### ISSUE TITLE
API for forms is not working

### ISSUE THREAD

**Issue by skylarkJ** [ga-wdi-boston/game-project#479]
I had a sign-up, sign in, sign out, change password working one day including the gameUpdate function - in the browser -wins above the board. The next day I moved to a jQuery messages without touching API for forms at all.

When I tried to test the whole experience again - I tried to log in with the same user from a day ago while opened console to check for errors and I wasn't getting any response at all - empty white space - no action in the console. 

So I tried to create a new user and was getting an error that the token is not defined and pointing to the function gameUpdate with the property authorization. 

Now I tried again and not getting any action in the console. [https://skylarkj.github.io/tic-tac-toe/](https://skylarkj.github.io/tic-tac-toe/)

This is my api.js

```javascript
'use strict';

const config = require('../config');
const store = require('../store');

const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data,
  });
};

const signIn = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-in',
    method: 'POST',
    data,
  });
};

const changePassword = function (data) {
  return $.ajax({
    url: `${config.apiOrigin}/change-password/${store.user.id}`,
    method: 'PATCH',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};

const signOut = function () {
  return $.ajax({
    url: `${config.apiOrigin}/sign-out/${store.user.id}`,
    method: 'DELETE',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};

const gameStat = function () {
  return $.ajax({
    url: config.apiOrigin + '/games?over=true', // will get only games that are already finished
    method: 'GET',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};

const gameCreate = function () {
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};

const gameUpdate = function (id, data) {
  return $.ajax({
    url: config.apiOrigin + '/games/' + id,
    method: 'PATCH',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};

const ajaxDefaults = {
  url: 'http://localhost:3000',
};

const myRequest = (data, success, fail) => {
  $.ajax(Object.assign({ method: 'POST', data }, ajaxDefaults))
  .done(success)
  .fail(fail);
};

module.exports = {
  signUp,
  signIn,
  changePassword,
  signOut,
  myRequest,
  gameStat,
  gameCreate,
  gameUpdate
};
```

**Comment by raq929** [comment]
What happens when you try to sign in? I would try going through a similar process that @doremaxime is going through in #481. Put console.logs in each step, and see where the failure point is.

**Comment by skylarkJ** [comment]
I used console.log but no data were throwing in in the console.

**Comment by doremaxime** [comment]
As you know I had a similar problem (not exactly the same) and it was fixed by restarting the server and it worked. The reason restarting the server makes a difference is because it is not like the front end web dev like html and css, those you can see differences when refreshing the browser. However, with the back end refreshing the server will allow you to see the changes you are making. If you knew that before and tried it, sorry for the waste of time ;)

**Comment by skylarkJ** [comment]
I am getting this error in the console. `Local
Exception
:
TypeError: Cannot read property 'token' of undefined at Object.gameUpdate (http://localhost:7165/public/application.js:357:50) at HTMLDivElement.<anonymous> (http://localhost:7165/public/application.js:574:10) at HTMLDivElement.dispatch (http://localhost:7165/public/vendor.js:13098:28) at HTMLDivElement.elemData.handle (http://localhost:7165/public/vendor.js:12906:29)
data
:
Object
id
:
""
this
:
Object
Closure
Closure (87)
Window
Global`

**Comment by MicFin** [comment]
The error
```js
application.js:340 Uncaught TypeError: Cannot read property 'token' of undefined
```
Is because your `gameCreate` and `gameUpdate` functions uses a `store.user.token` which doesnt work if no user signed in because `store.user` is undefined.

```js
const gameCreate = function () {
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`, // errors when store.user is undefined
    },
  });
};

const gameUpdate = function (id, data) {
  return $.ajax({
    url: config.apiOrigin + '/games/' + id,
    method: 'PATCH',
    headers: {
      Authorization: `Token token=${store.user.token}`, // errors when store.user is undefined
    },
    data,
  });
};
```
The issue seems to be that your `sign up` and `sign in` form events are not triggering the API call.
To trouble shoot this issue...please add  `console.log` at these points and see if you can figure out where the issue may be.

Notice I am starting at where the javascript code kicks off at document ready and then I add a `console.log` within the functions that get triggered to find out where a bug might be.

**index.js**
```js
// On document ready
$(() => {
  console.log("made it to index.js") // make sure our JS reaches this point
  console.log(authEvents); // see what the authEvents object is
  authEvents.addHandlers();
  gameFile.boardPaint();
  // handlersJQ.addHandlers();
});
```

**events.js**
```js
const onSignUp = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);
  console.log("made it to events.js") // make sure our JS reaches this point
  console.log(data); // see what the data is
  console.log(api); // see what the api object is
  api.signUp(data)
    .then(ui.success)
    .catch(ui.failure);
};
```

**api.js**
```js
const signUp = function (data) {
   console.log("made it to api.js") // make sure our JS reaches this point
   console.log(data); // see what the data passed in is
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data,
  });
};
```

**ui.js**
```js
const success = (data) => {
  // handle success
  console.log("made it to ui.js") // make sure our JS reaches this point
  console.log(data); // what is this data?  should you save it somewhere?  like to your store.user?
};
```

**Comment by jrhorn424** [comment]
@MicFin's suggestion is the best next step in getting this solved.

**Comment by skylarkJ** [comment]
I have tried the console.log testing before but wasn't getting any action in the console. The bug was a bootstrap issue using on all forms <input> class data-dismiss="modal". When I used it I didn't realize that it can influence id for a handler. I used it to give a user experience the form fields that when he/she submits the data, all fields will clear up.

**Comment by MicFin** [comment]
@skylarkJ  Can you post the HTML that was broken and then the HTML that fixed it?  If that was the fix then after you post it, you can close the issue.

**Comment by skylarkJ** [comment]
For the demonstration, I am only including a block of the code for the sign-up form, but the bug appeared in all forms. 

index.html - before 
Comment: Line with <input> included the bootstrap class data-dismiss="modal" - marked bold. To give APIs the data, this class needed to be deleted. The issue with information in the fields after the submit action - I am going to solve with jQuery.
`
    
        <div class="modal fade" id="modalSignUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                
              </div>
              <div class="modal-body">
                 <form id="sign-up">
                   <fieldset>
                     <legend>Sign Up</legend>
                     <label>
                       Email
                       <input type="text" class="form-control" name="credentials[email]">
                     </label><br>
                     <label>
                       Password
                       <input type="password" class="form-control" name="credentials[password]">
                     </label><br>
                     <label>
                       Password Confirmation
                       <input type="password" class="form-control" name="credentials[password_confirmation]">
                     </label>

                     <input id="style-signup" type="submit" **data-dismiss="modal"** class="form-control button-form" name="submit" value="Sign Up">
                   </fieldset>
                 </form>
               </div> 
             </div> 
           </div> 
         </div> 
`
