### ISSUE TITLE
Bundle.js and vender.bundle.js errors when hosting

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/game-project#48]
My web app works locally but when it is hosted on github I get bundle.js and vender.bundle.js errors. I looked at both files and the line number on which the error occurred and both of them are on empty lines.

http://ajordon.github.io/tic-tac-toe/

**Comment by RealWeeks** [comment]
@ajordon Seems to work now. Is this still an issue?  If not please close, if so please comment further and we'd be glad to work with you to debug.
