### ISSUE TITLE
my deployment issue

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/game-project#480]
When I tried to deploy last night I made a mistake that caused my issue today. I think what happened was that I forgot to push or did not push properly after merging. Somehow when I opened my project in atom, my files were empty. My engine was gone and my auth files were gone. I copied and pasted them in a backup folder just in case this situation would happen, so I still have my content. I copied and pasted them back in, but I am not sure if I should make a new repo now. I want to start the deployment process from scratch if possible because I can no longer make sense of what the log is saying.
I want to really make sure that I never ever make this mistake again and will make sure to commit much more frequently. Learned some lessons the hard way these past 24 hours.

**Comment by raq929** [comment]
Can you do `git branch -a` to see all the branches?
It's likely that your work is not lost, it's simply on a different branch.

**Comment by alexkarasik** [comment]
This is what I see when I do that:
  gh-pages
  master
  myttc
* submission
  remotes/origin/gh-pages
  remotes/origin/master
  remotes/origin/myttc

I put all my old work in a new branch called submission, which I am currently on.

**Comment by raq929** [comment]
Cool. If you check out to the other branches, can you see the files that were gone?

**Comment by alexkarasik** [comment]
In some with some rougher drafts and sloppier code, but I know what I want to push is now in submission.

**Comment by alexkarasik** [comment]
When I do git status, this is what comes up: 
You are currently rebasing branch 'master' on '394cb60'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working tree clean

**Comment by alexkarasik** [comment]
should I do that git command that it says? 
git rebase --continue

**Comment by raq929** [comment]
Hmmm... I think your safest option is `git rebase --abort`. Unless you know how and why you got into the rebase. 

Also, please note that github IS your backup for your files. You need to use it as such. Copying and pasting your code in from another place will not be acceptable for future projects.  We need to see a clear commit history going back to the beginning of the project, which you don't have if you copied everything in in one commit.

**Comment by raq929** [comment]
Let's take a look at this sometime tomorrow and try to figure out what's going on.

**Comment by raq929** [comment]
The reason your files were empty in the first place may have been because you were in the middle of a rebase. `git status` is your best friend in that circumstance.

**Comment by jrhorn424** [comment]
@alexkarasik Is this closeable? What was your resolution?

**Comment by alexkarasik** [comment]
The resolution was to get out of rebase. Apologies for not closing.
