### ISSUE TITLE
trouble hiding the modal after signing in.

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#481]
I am having trouble hiding the modal after signing in.
here is my html code for the module:
```
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Users Logins
        </button>

        <!-- Modal -->
        <!-- Start of API Token Auth -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"></h4>
              </div>
              <div class="modal-body">

```
I have tried many different combinations (below in the ui) to hide the modal once someone signs in but I can't seem to get it.
```
const success = (data) => {
  console.log(data);
  $('#myModalLabel').modal('hide'); //trying to get the modal to hide.
  $('.myModalLabel').modal('hide'); //trying to get the modal to hide.
  $('.modal-dialog').modal('hide'); //trying to get the modal to hide.
  $('.modal-content').modal('hide'); //trying to get the modal to hide.
  $('#myModal').modal('hide'); //trying to get the modal to hide.
  $('.modal').modal('hide'); //trying to get the modal to hide.
  $('#modal').modal('hide'); //trying to get the modal to hide.
  $('.modal-fade').modal('hide'); //trying to get the modal to hide.
  $('.fade').modal('hide'); //trying to get the modal to hide.
  $('.btn-lg').modal('hide'); //trying to get the modal to hide.
};
```

the events correctly point to the ui:
```
const onSignIn = function (event) {
  event.preventDefault();
  console.log('HIDING THE MODAL');

  let data = getFormFields(event.target);

  api.signIn(data)
  .then((response) => {
    store.user = response.user;
    console.log('HIDING THE MODAL 2');
    return store.user;
  })
    .then(ui.success)
    .catch(ui.failure);
};
```

**Comment by raq929** [comment]
OK, looks like you've got a lot going on here. Have you tried these one at a time instead of all at once?

Are you sure that this success function is running? (Put a `console.log('HIDING THE MODAL')` or some such in there to double-check.

**Comment by doremaxime** [comment]
hmm... the data (email, id, and token) were appearing in the console.
I believed it was connected as that was being console logged it but i just put in another console log and that doesn't show up. none of my console logs for the sign in api, events, nor ui show up but i the POST for signing in works... which is in the functions... weird. leaves me even more confused. 
As for the JQuery, I have tried doing one by one but i put them all so that you could see what I have tried. I have pushed my repo if you want to take a look, unless you already know what I am doing wrong.

**Comment by raq929** [comment]
Please follow my instructions and put a different console.log in. Your other success methods probably also log the data, so you can't rely on that to be sure that this one is running.

**Comment by raq929** [comment]
Sorry, I see that you did put in a second console.log. If it's not showing up, it's because this code is not running. Which is good news! Because it means you don't have a problem hiding the modal. 
So, what function calls this one? It looks like it's `onSignUp`, and you're calling ui.success... are you sure that's what you want?

**Comment by doremaxime** [comment]
yes, I had put console.log('HIDING THE MODAL'), and console.log('HIDING THE MODAL 2') in events, console.log('HIDING THE MODAL api') in the api, and console.log('HIDING THE MODAL ui') in the ui.

**Comment by raq929** [comment]
Awesome! Which ones do you see when you sign up?

**Comment by raq929** [comment]
(I recommend commenting out the hiding the modal code in the meantime.)

**Comment by doremaxime** [comment]
none of the console logs are showing. . I did check and it was indeed the events signIn that i commented, the signUp was an extra one.
I have commented the hides out.

**Comment by raq929** [comment]
Neat. That's useful information. Since _none_ of them are showing up, I suspect you don't have a click handler set on the button.

**Comment by doremaxime** [comment]
I have ran grunt nag and nothings comes up either. 
I have checked the module exports and requires seem to be connected as the POST is working and I am signing in.

**Comment by doremaxime** [comment]
Let me check on that button handler! I haven't thought of that since I successfully log in when I click it.

**Comment by raq929** [comment]
Can you post the code for the rest of the modal, and the code where you set the click handler?

**Comment by doremaxime** [comment]
html modal:
```
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Users Logins
        </button>

        <!-- Modal -->
        <!-- Start of API Token Auth -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"></h4>
              </div>
              <div class="modal-body">

                <form class="modal-button" id="sign-up">
                  <fieldset>
                    <legend class="modal-titles">Sign up!</legend>
                    <label class="modal-info">
                      Email: <br><input type="email" name="credentials[email]"><br>
                      Password: <br><input type="password" name="credentials[password]"><br>
                      Confirm Password: <br><input type="password" name="credentials[password_confirmation]">
                    </label><br>
                    <input type="submit" name="submit" value="Sign up!">
                  </fieldset>
                </form>

                <br>
                <br>

                <form class="modal-button" id="sign-in">
                  <fieldset>
                  <legend class="modal-titles">Sign in!</legend>
                  <label class="modal-info">
                    Email: <br><input type="email" name="credentials[email]"><br>
                    Password: <br><input type="password" name="credentials[password]"><br>
                  </label><br>
                  <input type="submit" name="submit" value="Sign in!">
                </fieldset>
              </form>

              <br>
              <br>

              <form class="modal-button" id="change-password">
                <fieldset>
                  <legend class="modal-titles">Change Password!</legend>
                  <label class="modal-info">
                    Current Password: <br><input type="password" name="passwords[old]"><br>
                    New Password: <br><input type="password" name="passwords[new]"><br>
                  </label><br>
                  <input type="submit" name="submit" value="Change Password!"><br>
                </fieldset>
              </form>

              <br>
              <br>

                <form class="modal-button" id="sign-out">
                  <fieldset>
                    <legend class="modal-titles">Sign Out!</legend>
                    <input type="submit" name="submit" value="Sign Out!">
                  </fieldset>
                </form>
              </div>
            </div>
          </div>
        </div>
```

**Comment by raq929** [comment]
Cool. What about the click handler?

**Comment by doremaxime** [comment]
events:
```
const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp);
  $('#sign-in').on('submit', onSignIn);
  $('#change-password').on('submit', onChangePassword);
  $('#sign-out').on('submit', onSignOut);
};
```
I am confused about that because I make a user, enter the log in info, click the log in button, and in the browser console I get the data(email, id and token). Therefore in my mind I understand that the button works because when I click it, it does what it should.

**Comment by doremaxime** [comment]
This is a screen shot right after I click sign in:
![screen shot 2017-01-31 at 10 23 01 pm](https://cloud.githubusercontent.com/assets/24608045/22494235/e6370810-e803-11e6-81d5-0dc21b74b126.png)
You can see on the console the data the server sends back.

**Comment by doremaxime** [comment]
Do you see my error after seeing the click handler?

**Comment by doremaxime** [comment]
Solution has been found.
There was an issue with the server.
Restarted client server.
Click handlers work!
