### ISSUE TITLE
API create game issue

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#484]
I am having an issue creating a game with the API.
The issue is that when the API sends data back (last line of code in comment) after clicking the button restart, which sets of the event, it is coming back as 'undefined'. 
I would expect it to come back with a game ID which in turn will be used for updating the game.
I have put a few console.logs and the flow seems correct. I have ran grunt nag. Checked the require/exports. restarted the servers. Tried adding 'id' to the parameter and end of the url of the api. Still no luck.

events:
```
const onCreateGame = function (event) {
  console.log('events onCreateGame checkpoint');
  event.preventDefault();
  api.create()
    .then((response) => {
      store.game = response.game;
    })
    .then(ui.createSuccess)
    .catch(ui.failure);
};
```

api:
```
const create = function (data) {
  console.log('api create checkpoint');
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};
```

ui:
```
const createSuccess = (data) => {
  console.log('ui onCreateGame checkpoint');
  console.log(data);
};
```

Any tips?

**Comment by gaand** [comment]
```diff
     .then((response) => {
       store.game = response.game;
+      return response;
     })
```

OR

```diff
-    .then((response) => {
-      store.game = response.game;
-    })
+    .then((response) =>
+      store.game = response.game
+    )
```

**Comment by doremaxime** [comment]
Thank you Antony!
I have tried both and please correct me if I am wrong but I should be getting a game ID back from the server right? So that the PATCH knows what to link the game data to?

As you can see, when signing in, I get an: ID, email, and token. 
![screen shot 2017-02-05 at 3 00 41 pm](https://cloud.githubusercontent.com/assets/24608045/22629486/fe294bf4-ebb4-11e6-9029-6ab532abdd82.png)
However, when I click to mark a token, ```store.game``` in ```store.game.id``` is said to be undefined. 

![screen shot 2017-02-05 at 3 30 22 pm](https://cloud.githubusercontent.com/assets/24608045/22629655/133d4ca4-ebb8-11e6-8fbb-754f21e382b1.png)

I followed the trail which leads to the file store.js
store.js:
```
const store = {
};

module.exports = {
  store,
};
```
As with the exercises we did in class with books, and current wdi16 developers' code, the const of this file is empty. I believe this to be normal which leads me to ask if  the ```game``` in ```store.game``` is a keyword for our project?

**Comment by gaand** [comment]
I suggest starting with `console.log(response)` before you try to store the game.

**Comment by doremaxime** [comment]
That is what I am trying to do, to get the create part right first as it leads to other things which cannot be done without it.
This is why I wondered: should I be getting a game ID back from the server when a user logs in so as to start/create a game? 
when I ```console.log(response)``` i just get undefined. Which is why I was looking for some help.

**Comment by MicFin** [comment]
You are chaining 2 `.then()`.  You want to chain 2 `.then()` and pass the response from the 1st to the 2nd then you need to have a `return` value that will get passed from the 1st to the 2nd.  You are not setting `return` value so the `response` is not getting passed to the 2nd `.then()` or its `ui.createSuccess` method but instead `undefined` is because in JS our functions with no explicit `return` value will `return` undefined.
```js
api.create()
    .then((response) => {
      store.game = response.game;
      // no return value here so .then(ui.createSuccess) does not get the response
      // by default it returns `undefined`
    }) 
    .then(ui.createSuccess) // ui.createSuccess is expecting the response as its data param but gets `undefined`
    .catch(ui.failure);
```
Please try the following and share what is logged in the console for `data`.
```js
api.create()
    .then((response) => {
      store.game = response.game;
      return response;
    }) 
    .then(ui.createSuccess) 
    .catch(ui.failure);
```

**Comment by doremaxime** [comment]
Thanks Antony, 
I had tried that before.
I just restarted my computer and it's worked!
Thank you for your help!
