### ISSUE TITLE
Click Handlers After a Win

### ISSUE THREAD

**Issue by ladypinetree** [ga-wdi-boston/game-project#486]
I'm having issues getting my reset button to turn clicking back on after a win. (There's no off click for a draw so the issue doesn't occur unless the reset is after a win.)

If a player wins clicking is disabled, but when the reset button is pressed clicking does not turn back on. I have tried adding it to the function that is called by the reset button, to the click handler for the reset button, and to the function that sets the player's turn. Nothing would work. 

This is how I turned it off:
```
      if (isWinner(gameBoard) === true) {
        $('.player-turn').text('');
        $('.message-player').text('You Win');
        $('.game-box').off('click');
```
I've tried adding it to the current player's turn 
```
  currentPlayTurn = messageText(currentPlayer);
  $('.player-turn').text(currentPlayTurn);
  $('.message-player').text('');
  $('.game-box').text('');
  $('.game-box').on('click');
};
```
To the reset function: 
```
const clearBoard = function () {
  gameBoard = ['', '', '', '', '', '', '', '', ''];
  currentPlayer = playerX;
  playSymbol = '';
  currentPlayTurn = '';
 $('.game-box').on('click');
```
And to the button itself:
```
$('#reset-button').on('click', function () {
  console.log('reset completed');
  clearBoard();
 $('.game-box').on('click');
});
```

I think this is an issue with bubbling but I can't figure out how to stop it.

Thanks,
Maura

**Comment by raq929** [comment]
This is related to #382

Basically, when you turn off the click handlers, they are GONE. They aren't still attached to the DOM element, so you can't just turn them back on. You have to set them again, the same way you set them initially.

**Comment by bernardlee** [comment]
`$('.game-box').on('click');` won't do anything.  `.on()` needs a callback function passed in to act as handler.

**Comment by raq929** [comment]
What's your status? If this is resolved, please post the code that resolved it with an explanation and close the issue. If it's still an issue, please update us on where you're at.

**Comment by ladypinetree** [comment]
This was resolved by changing the reset button to a start game button that sets the on.click and runs the game over function to set the off.click on a win or draw

```
function clearBoard(event) {
  // gameBoard[i] = '';
  let gameEvent = event;
  playerX = 1;
  playerO = 2;
  gameBoard = ['', '', '', '', '', '', '', '', ''];
  currentPlayer = '';
  playSymbol = 'x';
  currentPlayTurn = '';
  over = false;

  console.log(gameEvent);
  $('.game-board-container div').on('click', function () {
    const messageText = function (currentPlayer) {
      return 'It\'s your turn, Player ' + currentPlayer;
    };

    let divClass = $(this).attr('class');
    let divClassNum = parseInt(divClass);
    console.log(divClassNum);
    if (isSpaceEmpty(divClassNum) === true) {

      $('.message-player').text('');
      symbolValue(currentPlayer, divClassNum);
      $(this).text(playSymbol);
      if (gameOver(gameBoard) === true) {
        $('.player-turn').text('');
        $('.message-player').text('Game Over');
        over = true;
      } else {
```
The gameOver function is:
```
const gameOver = function (arr) {
  let isBF = isBoardFilled(arr);
  let isW = isWinner(arr);
  if (isBF || isW) {
    $('.game-box').off('click');
    return true;
  }
};
```
