### ISSUE TITLE
Create Game Post Accumulating with Each Sign-In

### ISSUE THREAD

**Issue by cshea93** [ga-wdi-boston/game-project#487]
With each sign in, the total games played(post) is going up by 1.

For example: I create an account, sign-in to that new account, and then play one game. My "Show Games" button displays "You have played 1 game". I then sign-out, then sign back in, play one more game. When I click my "Show Games" button this time, instead of displaying "You have played 2 games", its displays "You have played 3 games". I repeat the process again and it displays "You have played 6 games", and then again 10, and then again 15, and so on. 

I am looking for repeated handlers and while I have narrowed it down to my "reset/create game" button that is causing the problem, however I am unsure where/how to move this handler without breaking my game. 

Since it seemingly involves several files, mainly my UI, Events, and Game-logic files, I have posted my repo for the game below. 

https://github.com/cpstrillvt93/tic-tac-toe

**Comment by cshea93** [comment]
** Updated code is in the Feat branch

https://github.com/cpstrillvt93/tic-tac-toe/tree/feat

**Comment by cshea93** [comment]
I had a similar issue with the patches accumulating with each sign-in, however was able to work those out only to create this post issue.

**Comment by MicFin** [comment]
What's the count going up by?  Is it always just 1 ahead of the actual?

**Comment by cshea93** [comment]
After one sign in, it goes up by 1 for each game played. After a second sign in, it goes up by 2 for each game played, and so on.

**Comment by bernardlee** [comment]
Everytime `onSignInSuccess()` gets called, `$('#start').on('click', game.resetBoard);` gets executed and adds another `click` event listener to `#start`.

**Comment by cshea93** [comment]
Solved. Every time I signed in, a click handler was being added to my start game button. Issue solved by moving my handler out of onSignInSuccess() into my event handlers in event.js
