### ISSUE TITLE
Undefined show object

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/game-project#488]
I am having trouble getting the count for the games display. It just says your account has played an undefined, or depending on the placement I can get it to say zero games. Basically the object is undefined. 

This is my show and index functions
```
const index = function () {
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'GET',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};

const show = function () {
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.game.id,
    method: 'GET',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};
```

This is the call of the show function. 
```
const onGetGames = function (data) {
  event.preventDefault();
  // let data = getFormFields(event.target);

      api.index(store.game.id)
      .then(ui.onSuccess)
      .catch(ui.onError);
  // if (store.game.id.length ){
  console.log('Data result is: ' + JSON.stringify(data));

  console.log(data + ' at events.js onGetGames');
    api.show(store.game.id)
      .then(ui.onSuccess)
      .catch(ui.onError);
      $('#winMessage').text(data.email + ' has played ' + store.game.id.length + ' games!');

};
``` 
I am not sure what other code would be needed to discern this.

**Comment by bernardlee** [comment]
`store.game.id` is a number.

**Comment by novakw267** [comment]
Okay, I can't seem to figure out what the array that represents the games being stored is called. When I hit the games played button and it sends back an array of objects in the console that are all the games I have played at the moment that totals to 166. At least it seems like that is the count of games.

**Comment by bernardlee** [comment]
Check the index section here: https://github.com/ga-wdi-boston/game-project-api.

**Comment by raq929** [comment]
Anything you want to do with data coming back from the api needs to be done in a `then` after the API call, or in your onSuccess function.

**Comment by novakw267** [comment]
Okay that fixed that issue. I think I have a couple of others but for now issue closed. Thank you.
