### ISSUE TITLE
Lost on creating new game on server

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/game-project#489]
I'm trying to create the game on the server I have my reset board function in my engine, and the click- handler for that in a file called game clicks.

Reset Board function 
``` js
Game.prototype.resetGameBoard = function() {
  this.board = ['', '', '', '', '', '', '', '', ''];
$('.box').empty();
this.gameOver = false;
this.currentPlayer = 'X';
}; 
```

game clicks
``` js
'use strict';
console.log('game-clicks running');

const engine = require('./engine');
const api = require('../auth/api');
const store = require('../store');
const ui = require('./ui');
const gameEvents = require('./events');
// auth events

const game = new engine.Game();

// const addGameHandlers = () => {

$('.box').on('click', function(){
  let move = $(this).attr('id'); // c3
  let boardIndex = game.gameSpaces.indexOf(move); //3
  let currentMove = game.currentPlayer;
  let isValid = game.setMove(boardIndex);
  if (isValid === true) {
    $(this).text(currentMove);
  }
});

$('#new-battle').on('click', function (){
console.log("stuff");
game.resetGameBoard();
$('#message-box').text(' ');
});
```
These are the functions that reset the game and start the game, but it doesn't connect to the server. I know I'm missing something but just unsure of what else to try. I have changed the files, requiring all the appropriate files at the top of each file.   I even tried to refactor the functions and move the clicks for the game into the engine file but all get are errors. 
Maybe someone can spot what I may be missing. Check out my repo, game-events branch if you need to see more of the code, but here are the snippets
reset /new game refactoring in the engine file looks like this, the console gives me an error when it triggers saying it's not a function. I made sure I commented out the functions I wasn't using and added a console log to the button to made sure it was working. 

```js

Game.prototype.resetGameBoard = function() {
  this.board = ['', '', '', '', '', '', '', '', ''];
$('.box').empty();
this.gameOver = false;
this.currentPlayer = 'X';
};


const newGame = new Game();

$('#new-battle').on('click', function () {
this.resetGameBoard();
$('#message-box').text(' ');
});

```
API related scripts

Create - api.js 
``` js
const create = function (data) {
  console.log(data);
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};


module.exports = {
  getIndex,
  create,
  show,
  update,
  updateGameStatus,
};
```
game/events.js
```
//when clicking new game, this should run resetGameBoard function
const onCreate = function (event) {
  console.log('creating game');
  event.preventDefault();

    gameApi.create(data)
    .then((response) => {
      store.game = response.game;
    })
    .then(gameUi.createSuccess)
    .catch(gameUi.failure);
};
```
game/ui.js
```js

const createSuccess = () => {
  $('#promt').text('New Game Successfully Created');
};


module.exports = {
  failure,
  success,
  createSuccess,
  onPatchSuccess,
};
```

**Comment by raq929** [comment]
OK, so what happens when you click New Game? Do you see the console log? 
You'll probably want to save data from the API response to that, in a similar way that you did with login data.

What does it say isn't a function? Remember you can get a lot of help from error messages. You're using `this` in the global scope in your first snippet you posted, so that's probably not what you want. Also, you have a function on the prototype of a constructor function you haven't defined. You probably want `engine.Game.protoype.ResetGame =`.
I think you likely want to call resetGame on an instance of Game, not on `this`.

**Comment by bernardlee** [comment]
Your game-events branch was updated 15 hours ago.  Is this what we're looking at?

**Comment by raq929** [comment]
Take it one thing at a time. Get rid of your error, then work on making the API call.

**Comment by AshlenPrice** [comment]
@bernardlee Sorry just pushed updated version

**Comment by bernardlee** [comment]
There are no event handlers being attached to your "New Battle" button.  You have a function, `addAjaxHandlers()`, attaching one to it in `assets/scripts/game/events.js`, but it isn't being called anywhere.  Also, the buttons are impossible to be see because your footer is covering them up when the screen width is less than 1055px.

**Comment by AshlenPrice** [comment]
@raq929  when I click new game with this below active. It runs the reset function and clears the board. 
```js
$('#new-battle').on('click', function (){
console.log("stuff");
game.resetGameBoard();
$('#message-box').text(' ');
});
```
this was the error
![image](https://cloud.githubusercontent.com/assets/24688275/22856276/2dd88aee-f05c-11e6-822e-87227fa0a796.png)

to make that error I was using this 
![image](https://cloud.githubusercontent.com/assets/24688275/22856289/556710ee-f05c-11e6-9620-66a99e466a46.png)

To your last point, I didn't think I needed to do ``` engine.Game.protoype.ResetGame =.```  if I require the file that the constructor is on.

**Comment by AshlenPrice** [comment]
@bernardlee  aren't I calling it in the create function in my ``` game/api.js ``` file?

**Comment by bernardlee** [comment]
No.  Your `create()` function in `assets/scripts/game/api.js` performs an Ajax call.

**Comment by raq929** [comment]
You're defining it in your `game/api` file. You have to call it elsewhere.

You have to remove or change the `this.resetGameBoard()`. `this` is the window in that context, not the game.

**Comment by raq929** [comment]
Right now we are trying to solve multiple problems at once and it's confusing. Let's do one thing at a time and focus on clicking new game without an error before moving on to the API call.

**Comment by raq929** [comment]
How's it going?

**Comment by jrhorn424** [comment]
Was this addressed? Was there a satisfactory resolution? What was learned? Are there other issues? Is this closeable?
