### ISSUE TITLE
Cross-Origin Request Blocked?

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/game-project#49]
I'm trying to finish the API interface for my tic-tac-toe project. I keep getting a 400 bad request with this error to the console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ttt.wdibos.com/users. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

This is my function for creating a new user on the server:

```
let baseUrl = "http://ttt.wdibos.com";
let contentType = "application/json";

let createUser = function(data) {
  let credentials = {credentials: $.extend({}, data)};
  console.log(credentials);
  $.ajax({
      type: "POST",
      url: baseUrl + "/users",
      contentType: contentType,
      processData: false,
      data: credentials,
    }).done(function(data) {
      console.log(data);
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
}
```

...where data = {credentials: {email: "something", password: "something", password_confirmation: "something"}}.

What's going on here?

**Comment by GA-MEB** [comment]
You're hitting the wrong URL.
It's `'http://tic-tac-toe.wdibos.com'`

**Comment by rchezrutt88** [comment]
Doesn’t seem to matter? Still bouncing. 

https://www.dropbox.com/s/y4eeiitwzydjslf/Screenshot%202016-02-09%2011.21.26.jpeg?dl=0

**Comment by GA-MEB** [comment]
If you direct your request to a mirror like this one, what do you see as the output?
`https://httpbin.org/post`

**Comment by rchezrutt88** [comment]
That works. Echoes back:

https://www.dropbox.com/s/f50znj16yrgy9b1/Screenshot%202016-02-09%2011.44.28.jpeg?dl=0

**Comment by rchezrutt88** [comment]
I have a hunch the problem is with the contentType property. In my case I’ve given it the value “application/json”. I unthinkingly copied it from one of the demos. 

However, in the docs it sez:

```
Note: For cross-domain requests, setting the content type to anything other than application/x-www-form-urlencoded, multipart/form-data, or text/plain will trigger the browser to send a preflight OPTIONS request to the server.
```

I don’t know what a preflight OPTIONS request is but it sounds BAD and WEIRD.

**Comment by rchezrutt88** [comment]
Still getting these fabulously unhelpful "Cross-Origin Request Blocked" errors. I am confident now that I am assigning the correctly formatted information to data:
![screenshot 2016-02-09 16 20 54](https://cloud.githubusercontent.com/assets/2382361/12930940/2cadfe7c-cf49-11e5-8899-0f40dd0b7fa7.jpeg)
Really stumped.

**Comment by jrhorn424** [comment]
`"Cross-Origin Request Blocked"` is generally a useless error. When you control the API, it will be a sign to you to check your server log. Since you don't own this API and we haven't seen major server-side issues, I suspect this is an error in your request.

For example, not using the correct names in your form inputs for FormData will give you this error, even though the real problem is that you're sending something unexpected to the backend. It all bubbles up through the browser console as `"Cross-Origin Request Blocked"`.

**Comment by rchezrutt88** [comment]
Got it. Hope that doesn't mean that there won't be a good way to design our own APIs to throw more helpful error messages for bad input?

**Comment by jrhorn424** [comment]
The problem is that's how the _browser_ handles error messages. Its not secure to leak details of how your server is failing in production. In a development environment it will be clearer what the causes are.
