### ISSUE TITLE
Terminal: Enter passphrase for key '/Users/MD/.ssh/id_rsa':

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#490]
I am trying to do a git push but a passphrase is being required.

Terminal:
```Enter passphrase for key '/Users/MD/.ssh/id_rsa': ``` (it then has a key symbol)

I have tried adding my github password and SSH but neither work. My duck seems to be deaf...
I know that the key means nothing will show but that it is still being inputed.

I had to restart my computer for updates and I believe ending the terminal session is what triggered it from asking for such.

What do I enter in?

**Comment by bernardlee** [comment]
This isn't a game project issue, but I can try to help.  It'll be easier over Slack, so send me a message there.
