### ISSUE TITLE
game board not showing

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/game-project#493]
my game board is not showing up when you click the play button
I guess I am hiding the board as soon as it loads, I added the jquery $('#wrapper').show();
but it is still not working and it is making app run super slow.

**Comment by bernardlee** [comment]
Search your code for the function that calls `  $('#wrapper').show();`.

**Comment by Soboscott** [comment]
i see that my const createGameSucess in ui.js

**Comment by bernardlee** [comment]
Is it called anywhere?

**Comment by Soboscott** [comment]
I added it to 
const signInSuccess = () => {
  // $('#sign-in1').dropdown('toggle');

  // $('#sign-up').val('');
  $('#sign-in');
  $('#sign-up-btb').hide();
  $('.signinhide').hide();
  $('#getGame').show();
  // $('#change-password').show();
  $('#sign-out').show();
  $('#reset').show();
  $('h2').show();
  $('.changebtn').show();
  $('#wrapper').show();
};
and it is now called by:
const onSignIn = function (event) {
    event.preventDefault();

  let data = getFormFields(event.target);

  api.signIn(data)
    .then((response) => {
      store.user = response.user;
      return store.user;
    })
    .then(ui.signInSuccess);

    // .then(ui.success)
  // .catch(ui.failure);

};

**Comment by Soboscott** [comment]
what shows now is a compressed game board

**Comment by Soboscott** [comment]
I don't think it is a css issue, but I also don't know how it could be a html one either

**Comment by bernardlee** [comment]
The goal was to get the board to display, correct?

**Comment by Soboscott** [comment]
a new issue !
