### ISSUE TITLE
Request for Wireframe Review

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/game-project#498]
I haven't ever created a wireframe and just wanted a pair of eyes on it before I submit with project on Monday.

Here is the link to both two images.

http://imgur.com/sE8y9Su

http://imgur.com/zFI76Dd

Thank you!
 @lisamsmith100

**Comment by payne-chris-r** [comment]
Those look great! I might add some sort of visual for how users sign in/sign out/etc though?

**Comment by payne-chris-r** [comment]
Hey @lisamsmith100 ,
Can you update this issue and close it if it's resolved?

**Comment by lisamsmith100** [comment]
Thank you for response; closing this issue.
