### ISSUE TITLE
Rails Server - 500 error when connecting, unable to reinstall

### ISSUE THREAD

**Issue by buffalo0707** [ga-wdi-boston/game-project#499]
Was getting a 500 "Internal Server Error" when trying to connect to game-project-api Ruby Server via browser or curl script. After shutting down server and trying to restart, I'd get an error indicating that something is already running on port 4741.

Rebooted, same behavior.

Removed entire game-project-api folder via terminal. Attempted to reinstall server using instructions in library-api-guide repo. Error when trying to run 'bundle exec rake db:migrate' command:

could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Tried running library-api-guide api by running 'bundle exec rails server' from within wdi/tmp/library-api-guide to see if that server is working. Server spins up OK, but I receive a 500 error when trying to access via browser:

"status": 500,
"error": "Internal Server Error",
"exception": "#<PG::ConnectionBad: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/tmp/.s.PGSQL.5432\"?\n>",

Rebooted - did not resolve. 

Both servers were working yesterday

**Comment by BenGitsCode** [comment]
What is the output of typing 

`brew services list`

In your terminal?

**Comment by buffalo0707** [comment]
```sh
$ brew services list
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (7/7), done.
Unpacking objects: 100% (10/10), done.
remote: Total 10 (delta 0), reused 5 (delta 0), pack-reused 0
Tapped 0 formulae (37 files, 50.9KB)
Name       Status  User          Plist
postgresql started alanhenderson /Users/alanhenderson/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
```

**Comment by jonifallon** [comment]
```sh
$ bundle exec rails server
=> Booting Puma
=> Rails 4.2.7.1 application starting in development on http://localhost:4741
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[61116] Puma starting in cluster mode...
[61116] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
[61116] * Min threads: 8, max threads: 32
[61116] * Environment: development
[61116] * Process workers: 4
[61116] * Preloading application
[61116] * Listening on tcp://localhost:4741
Exiting
/Users/joni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `initialize': Address already in use - bind(2) for "::1" port 4741 (Errno::EADDRINUSE)
	from /Users/joni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `new'
	from /Users/joni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `add_tcp_listener'
```

I'm having the same issue.

**Comment by BenGitsCode** [comment]
Quit terminal completely, re-navigate to the api directory and try running again, what's your error there?


That very first error sounds like you already had a server running on that port. The others may be separate.

**Comment by buffalo0707** [comment]
No error when launching library-api-guide server from terminal. Appears to start OK
```sh
~/wdi/tmp/library-api-guide (jquery-ajax)
$ bundle exec rails server
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:4741
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.1-p112), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:4741
Use Ctrl-C to stop

```

Still getting 500 error when trying to access http://localhost:4741/ via chrome. Still unable to complete game-project-api install due to error noted earlier when running bundle exec rake db:migrate

```sh
could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by BenGitsCode** [comment]
@jonifallon  Review this line of your error carefully. 

```/Users/joni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `initialize': Address already in use - bind(2) for "::1" port 4741 (Errno::EADDRINUSE)```

If you're still unsure, start googling it ( I think that list bit in parentheses will bring you much google joy ) If you still can't get it working then please open an individual issue.

**Comment by BenGitsCode** [comment]
I think I see the issue. What server are you trying to run and why?

**Comment by buffalo0707** [comment]
I want to run game-project-api to begin working on my project, but I cannot because I cannot complete the installation due to the reasons mentioned above. Again, i am trying to reinstall it after removing it to troubleshoot the origin 500 error I was receiving. 

I am now trying to run library-guide-api as a troubleshooting step to see if I can at least get ANY server running, but it is not working either due to a 500 error.

**Comment by jonifallon** [comment]
I rebooted my mac and now I am all set.

**Comment by BenGitsCode** [comment]
I see. You do not need to run the game-project-api. It's already deployed for you. 

You don't need to serve the api, just connect your tic tac toe client to our deployed api.

If you do not already have a working game engine, I think that's a better starting place.

**Comment by buffalo0707** [comment]
Thanks Ben. I was able to complete the reinstall of the game-project-api thanks to this article:

http://stackoverflow.com/questions/12472988/postgresql-error-could-not-connect-to-server-no-such-file-or-directory

Looks like I'm in business now. I am curious what you mean by connecting my client to your deployed API, but I won't worry about that right now :)

All set for now - thanks again.

**Comment by BenGitsCode** [comment]
Good job! You can close this issue if it's resolved. Could you please just briefly summarize the steps you took from that SO? For those reading this in the future.

**Comment by buffalo0707** [comment]
Solution: 
1. In terminal, navigated to /usr/local/var/postgres/
2. ran following command:
```sh
rm postmaster.pid
```
3. Attempted API install from where previously failing - installed successfully, able to launch server
