### ISSUE TITLE
[Bootstrap] - Bootstrap not installing properly

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/game-project#5]
Error from grunt serve:
ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
Module parse failed: /Users/jamesfriedman/wdi/projects/tic-tac-toe/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4172-4253 6:4276-4357

Issue: tried installing Bootstrap in project repository following instructions on https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass, however when running grunt serve to test in browser, several copies of the above error are thrown each referencing a different file in node_modules/bootstrap-sass/assets/fonts/.

Have tried installing different loaders as suggested by posts on stackoverflow, but receive same errors. App was working correctly prior to Bootstrap installation, but now is unable to style the page.

**Comment by RealWeeks** [comment]
did you run npm install --save-dev bootstrap-sass?  Can you send me the line from the package.json that has it?

**Comment by jpfriedman18** [comment]
Followed all applicable instructions in the Bootstrap lesson repo, i.e:
- ran npm install --save-dev bootstrap-sass
- added vendor: ['jquery', 'bootstrap-sass'] to grunt/webpack.js
- Registered the font path and include the bootstrap-sass module in style manifest

In package.json, we can see: "bootstrap-sass": "^3.3.6"

**Comment by RealWeeks** [comment]
lastly can you paste in what you have in your style manifest?  Also did you remove normalized from the package.json and index.js?

**Comment by jpfriedman18** [comment]
normalized.css was not present in the existing package.json and index.js files.

at the top of the style manifest was:
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';

**Comment by RealWeeks** [comment]
looking into it now, will be with you shortly

**Comment by RealWeeks** [comment]
Issue closed: solution clone template repo, copy necessary code in.

**Comment by jrhorn424** [comment]
The problem is that the loaders for fonts and other static assets were added to `js-template`. The reason I added them there instead of the bootstrap talk is because whether or not you use bootstrap, it's a good idea to have loaders defined for fonts and svgs.

The solution:
-   [ ] From the project repository, add `js-template` as a remote
-   [ ] Fetch the new remote
-   [ ] Check out the latest versions of grunt configuration and package.json, for example `git checkout js-template/master -- grunt package.json`
-   [ ] `npm install`
-   [ ] `grunt serve` to test
-   [ ] Commit these new files (and only these new files) with a meaningful message

**Comment by edesilets** [comment]
I have the exact same issue. What is the 

> "From the project repo?"

I am getting from cohort mates that the repo you are referring to is ....
 https://github.com/ga-wdi-boston/js-template

So the first command would be....
`git remote add origin https://github.com/ga-wdi-boston/js-template.git`

Second command.....
`git checkout --track -b origin/js-template`

Then follow the rest of the instructions from ....
- Check out the latest versions of grunt configuration and package.json, for example git checkout js-template/master -- grunt package.json

**Comment by jrhorn424** [comment]
No, when I say "project repo" I mean your local repository that has your tic-tac-toe project in it.

So the first step would be `git remote add js-template https://github.com/ga-wdi-boston/js-template.git` and the second command would be `git fetch js-template`. Then, follow as indicated in my previous check list.

**Comment by edesilets** [comment]
Conduct these steps

```
git remote -v
git remote add origin https://github.com/ga-wdi-boston/js-template.git
git fetch origin
git checkout origin/master -- grunt package.json
npm install
```

@ajordon 
2-3-2016 11:54AM

**Comment by jrhorn424** [comment]
Do **not** call the new remote origin. Origin is reserved for your github copy of your project.

**Comment by jrhorn424** [comment]
These are the _corrected_ steps.

``` diff
git remote -v
- git remote add origin https://github.com/ga-wdi-boston/js-template.git
+ git remote add js-template https://github.com/ga-wdi-boston/js-template.git
- git fetch origin
+ git fetch js-template
- git checkout origin/master -- grunt package.json
+ git checkout js-template/master -- grunt package.json
npm install
```
