### ISSUE TITLE
returning user data from AJAX .done to global variable

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/game-project#50]
I'm writing my AJAX requests in a separate file from my main function. When I call an AJAX request from main--sign-in(), for instance--I'd like to store the returned user object in a global variable in my main function. 

My natural instinct here is to pass by reference this userData variable to the sign-in function (or whichever), and then assign to it the returned value within the .done block of the sign-in function. Can I do this in JS? I've tried but the userData variable remains undefined after a successful sign-in. 

Essentially: Can I pass by reference in JS? Would it be reasonable to do so in this case? Would a better workaround be to store userData within the AJAX file and then write a getter function, one which I could export to the main file?

**Comment by jrhorn424** [comment]
**Real** globals are hard to do with webpack, but here's a possible solution.
1.  Create a file called `app.js`. Export an object literal. Maybe it has data in it, maybe it's empty for now.
2.  In your ajax requests file, `let app = require('./app')`.
3. When `done` fires, store the data you want, something like `app.token = data.user.token`.
4. Whenever you need to reference `app.token`, you'll need to grab a reference to it with `let app = require('./app')` if the require isn't already in the file.

@gaand might have more insight here. I haven't used a pattern like this with webpack, but I think it will work.

**Comment by gaand** [comment]
Part of the problem may be that your test of userData may be happening before the sign in completes.

**Comment by rchezrutt88** [comment]
This occurred to me. I tied console.log(userData) to a “print info” button so I could give .done time to fire before peeking at the userData variable.

**Comment by gaand** [comment]
Please paste the ajax/done code.

**Comment by rchezrutt88** [comment]
http://stackoverflow.com/questions/13104494/does-javascript-pass-by-reference

"Specifically, when you pass an object (or array) you are (invisibly) passing a reference to that object, and it is possible to modify the contents of that object, but if you attempt to overwrite the reference it will not affect the copy of the reference held by the caller - i.e. the reference itself is passed by value”

So perhaps if I pass the function a reference to an object literal rather than an unassigned variable?

**Comment by rchezrutt88** [comment]
```
let signIn = function(formData, userData //a reference to a variable in main) {

  //TODO handle cases where user already signed in

  if(userData) {
    throw 'user already signed in';
  }

  $.ajax({
      type: "POST",
      url: baseUrl + '/sign-in',
      contentType: false,
      processData: false,
      data: formData,
    }).done(function(responseData) {
      console.log(responseData);

      userData = responseData.user;
      let userEmail = responseData.user.email;

      //display user email in navbar
      $(".navbar-right").append("<li><p class='navbar-text'>Signed in as " + userEmail+ "</p></li>");

      //hide modal
      $("#signinModal").modal("hide");

    }).fail(function(jQXHR) {
      console.log(jQXHR);
    });
};
```

**Comment by jrhorn424** [comment]
As long as you are requiring the target object in the current file, you will have a reference to the data stored there. Probably more like `let app = require('./app.js')` then later `singIn(myForm, app.userData)` should work. Are you getting any errors?
