### ISSUE TITLE
Is there any way to clear my database?

### ISSUE THREAD

**Issue by jim-moody** [ga-wdi-boston/game-project#500]
I'm up to 147 games in my database and it physically pains me to have all that bad data just sitting there.

**Comment by jordanallain** [comment]
how are the games stored?

**Comment by jim-moody** [comment]
I am creating games by using the POST method of /games and updating them by using the PATCH method of /games/:id

**Comment by jordanallain** [comment]
what data is stored about each game?

**Comment by BenGitsCode** [comment]
What have you tried? For instance http://bit.ly/2o35Yna

**Comment by jim-moody** [comment]
This is what my game object looks like:
```js
{
  "id":175,
  "cells":  ["","","","","","","","",""],
  "over":false,
  "player_x":  {
      "id":1,
       "email":"test@test.com"
      },
  "player_o":null
}
```

I tried running a DELETE method on the /games:id path but that didn't work.  I was afraid to try anything else as I didn't want to mess up my database configuration.

**Comment by jordanallain** [comment]
do you mean you don't want to edit your ajax request? there are other ways to communicate with APIs

**Comment by jim-moody** [comment]
In order to delete my entire database I would need to do `bundle exec rake db:drop`

And then to recreate the database, follow steps 7-10 in the https://github.com/ga-wdi-boston/library-api-guide

h/t Chris
