### ISSUE TITLE
Error when signing-in on deployed site 

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/game-project#501]
I built out the sign-up, sign-in, sign-out, and change password features. I tested these on my local server and it worked. I ran grunt deploy and then opened my site through GitHub Pages. 

When I tried to sign-up on the site using a new email and password, I received an error in the console. I have attached a screenshot of the "mixed content" error.

<img width="712" alt="screen shot 2017-04-05 at 11 33 52 am" src="https://cloud.githubusercontent.com/assets/20606223/24713660/4b5c13bc-19f4-11e7-8262-11be8fd6ea95.png">

**Comment by jordanallain** [comment]
anything in that error message stand out to you?

**Comment by naributler** [comment]
Hmm well the URL protocols do not match - GitHub Pages is using https, the local host is using http. I tried modifying my local host protocol to take https, but received another error: 
<img width="1163" alt="screen shot 2017-04-05 at 11 50 54 am" src="https://cloud.githubusercontent.com/assets/20606223/24714342/37c370a0-19f6-11e7-8b24-45dd7afd8dfd.png">

**Comment by jordanallain** [comment]
Where are you sending the POST request?

**Comment by BenGitsCode** [comment]
any updates @narichasavanorkejoyce ?

**Comment by naributler** [comment]
Haven't been able to make much progress here - I'm trying to send the POST request to the localhost, but the request should probably be going to GitHub pages?

**Comment by BenGitsCode** [comment]
Do you? 

What are you trying to send a POST to and why?

**Comment by naributler** [comment]
I'm referencing issue #273. I changed my production API to https://aqueous-atoll-85096.herokuapp.com/ and re-deployed. However, I'm still getting the same error.

**Comment by jordanallain** [comment]
what does the error say? same exact thing word for word?

**Comment by naributler** [comment]
Yes, I'm still getting this error: 
Mixed Content: The page at 'https://narichasavanorkejoyce.github.io/tic-tac-toe/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:4741/sign-in/'. This request has been blocked; the content must be served over HTTPS.

**Comment by naributler** [comment]
My configuration file looks like this: 
```javascript
'use strict'

const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com/'
  }
}

module.exports = config
```

**Comment by jordanallain** [comment]
can you post the code that is requiring this file and using `config`

**Comment by BenGitsCode** [comment]
Look closer. 

The error didn't change **at all** but you changed the endpoint you were making a request to...so shouldn't it be different, if it's using endpoint in the above snippet?

**Comment by BenGitsCode** [comment]
Have you committed, pushed and redeployed your client?

**Comment by naributler** [comment]
I believe I have committed, push, redeployed...could I show you in person?

**Comment by jrhorn424** [comment]
The **development** URL is different than what it is currently showing. Are you in production, or development?

**Comment by naributler** [comment]
I'm still confused about how config.js should be set up. Is the following inaccurate? 

```javascript
'use strict'

const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com/'
  }
}

module.exports = config
```

**Comment by BenGitsCode** [comment]
I'll come over to look now

**Comment by naributler** [comment]
Issue resolved! Thank you @BenGitsCode! Here's my summary of the solution: 

Per issue #273, the production URL needed to be changed to https://aqueous-atoll-85096.herokuapp.com/. The development URL remains http://localhost:4741. The configuration file contains the following code: 

```javascript
'use strict'

const config = {
  apiOrigins: {
    // production: 'https://ga-wdi-boston.herokuapp.com'
    development: 'http://localhost:4741',
    production: 'https://aqueous-atoll-85096.herokuapp.com/'
  }
}

module.exports = config
```

Then, we required config.js in api.js: 
```javascript 
const config = require('../config')
```

Next, the URL in each AJAX request needs to change. For example, the sign-up POST request looks like this: 
```javascript
const signUp = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/sign-up/',
    method: 'POST',
    data
  })
}
```
Key point: In order to find the correct URL, we needed to use config.apiOrigin. NOT config.apiOrigins.

**Comment by BenGitsCode** [comment]
Awesome closing comment! Good work.
