### ISSUE TITLE
How to initialize a game

### ISSUE THREAD

**Issue by vanduong28** [ga-wdi-boston/game-project#502]
I'm struggling with how to initialize a game. I want to set the following:

const gameBoard = new Array(9)
let currentPlayer = playerX
let moveCount = 0

I'm unsure where to make these declarations (within a function or global?) and continue to receive "not defined" linter errors when I try to define them. Any help would be greatly appreciated!

**Comment by BenGitsCode** [comment]
What have you tried so far? What are the linter errors you're getting?

**Comment by vanduong28** [comment]
I tried the following: 

const newGame = function () {
  const gameBoard = new Array(9)
  let moveCount = 0
  let currentPlayer = playerX
  console.log(gameBoard)
  console.log(moveCount)
  console.log(currentPlayer)
}

and the linter needs me to define playerX but that's where I struggle with how to do so :/

**Comment by BenGitsCode** [comment]
pro tip: put your code in back ticks to prettily format it like [this](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

How did you define others, for example, `currentPlayer`❓

**Comment by vanduong28** [comment]
I declared it as empty: currentPlayer = ' '

Oops, sorry about the back ticks. Thought that was only for Slack formatting :p

**Comment by BenGitsCode** [comment]
that line `let currentPlayer = playerX` is throwing the error `player x is undefined` yes?

Why didn't it throw undefined on `newGame` ,`gameBoard`,`moveCount`,`currentPlayer`?

What was different?

**Comment by danman01** [comment]
Any updates on this @vanduong28?

**Comment by vanduong28** [comment]
I've tried defining it outside the method but still encountering linter errors. I didn't receive errors for newGame because I performed a module.exports and if I console.log for gameBoard,moveCount,currentPlayer I don't have the linter errors.

```js

const playerX = 'X'
const playerO = 'O'
let currentPlayer = null
let moveCount = 0

const newGame = function (event) {
  const gameBoard = new Array(9)
  let moveCount = 0
  let currentPlayer = playerX
}

```

**Comment by payne-chris-r** [comment]
There's a large difference between this:
```js
const newGame = function () {
  ...
  let currentPlayer = playerX
}
```
and this:
```js
const playerX = 'X'
...

const newGame = function (event) {
  ...
  let currentPlayer = playerX
}
```

**Comment by payne-chris-r** [comment]
In the first code snippet posted above, what does javascript think `playerX` is? In the second, what does it think `playerX` is?

**Comment by vanduong28** [comment]
In the first is playerX an object and in the second playerX is a string?

**Comment by payne-chris-r** [comment]
Close! In the first the javascript parser is looking for a variable called `playerX` which is never defined. So, your linter is probably saying `playerX` is not defined. 

In the second it's looking for a variable called `playerX` which IS defined (on line 1), and has the value `'X'`.

**Comment by vanduong28** [comment]
I'm closing this issue because as I continue to add different methods I'm discovering I should be defining variables in either other methods or globally. I may have more questions but will open a new issue for any future errors. Thanks!
