### ISSUE TITLE
API Change PW Path name wrong

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/game-project#504]
In the API guid the change password method is listed as being: "changepw" for the URL path.

When I used that I got the error below:

ActionController::RoutingError (No route matches [PATCH] "/changepw/7"):
actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

By changing the path to "change-password" I got it to work.

**Comment by BenGitsCode** [comment]
`/change-password/:id` is the URI pattern and	`users#changepw`is the associated controller and action.

**Comment by jordanallain** [comment]
@sjruby Can this be closed?
