### ISSUE TITLE
Need help setting up some things on game-project-api

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/game-project#505]
Reviewing the material from https://github.com/jonifallon/game-project-api, I have completed the authentication piece (signin, signup, change pw, signout).  I am confused, however, with how to proceed with setting up the rest of it.  If someone could help me understand where to place code for things like "The show action..." I would appreciate it.  I'm sure I can get through it if someone can help me with the first one.

**Comment by payne-chris-r** [comment]
A `show` is kind of like "go get one thing", right? Do you remember how we did that for books?

**Comment by BenGitsCode** [comment]
☝️

**Comment by jonifallon** [comment]
I'm slowly getting the pieces in place.  I don't know if they actually "work" (since I don't have the logic built yet), but they're not blowing up my site!

**Comment by BenGitsCode** [comment]
Try getting the logic working first!

**Comment by jonifallon** [comment]
All my auth functions were working fine until now.  Since the last time I checked it, I’ve been adding the game code from this request, and periodically checking the signing, sign-up, etc. functions along the way. They’ve worked fine until now.

Now when I try to sign in, change password, or add a new user, I get

http://localhost:4741/sign-up 400 (Bad Request) or 401 (unauthorized).

I’ve restarted both servers.   As far as I know, I haven’t  changed any of the code associated with those auth functions.  Can you please help?

```sh
Started POST "/sign-in" for ::1 at 2017-04-05 16:20:30 -0400
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by UsersController#signin as */*
  Parameters: {"credentials"=>{"email"=>"doug", "password"=>"[FILTERED]"}, "submit"=>"Sign in!"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "doug"]]
  SQL (6.5ms)  UPDATE "users" SET "token" = '0341717213057b40dab56d2643af6cfb', "updated_at" = '2017-04-05 20:20:30.918487' WHERE "users"."id" = $1  [["id", 2]]
Completed 401 Unauthorized in 98ms (ActiveRecord: 9.7ms)


Started POST "/sign-up" for ::1 at 2017-04-05 16:22:41 -0400
Processing by UsersController#signup as */*
  Parameters: {"credentials"=>{"email"=>"tina", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "submit"=>"Sign up!"}
   (0.1ms)  BEGIN
  User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'tina' LIMIT 1
   (0.2ms)  ROLLBACK
  User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'tina' LIMIT 1
Completed 400 Bad Request in 80ms (ActiveRecord: 0.9ms)
```

**Comment by jonifallon** [comment]
Please ignore.  i'm not longer receiving the issue.  User error on my part.  I will update this when I have completed adding all the code mentioned above.

**Comment by payne-chris-r** [comment]
@jonifallon is this issue resolved?

**Comment by jonifallon** [comment]
I have not finished but I'll close this for now and will reopen if needed.
