### ISSUE TITLE
Don't understand how store works

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/game-project#506]
I am using the api-token-auth code that i did in class as a reference for setting up my create account, login, log out, and change password components of my project. 

store is an empty object that holds data such as user.id, user.token, etc. I don't know or understand where in the code we actually push this data to store.

**Comment by payne-chris-r** [comment]
How do you get or set data into an object? For example, if the object was 
```js
const someObj = {}
```
How would I put something in there? Get it out? What if it were from another file?

**Comment by payne-chris-r** [comment]
@awoodrum87 any updates?

**Comment by payne-chris-r** [comment]
@awoodrum87 ☝️

**Comment by awoodrum87** [comment]
its all good

**Comment by payne-chris-r** [comment]
Please close with a solution/explanation!

**Comment by awoodrum87** [comment]
Closing: store is the least of my issues.

**Comment by payne-chris-r** [comment]
Can you ask us more questions about it?
