### ISSUE TITLE
Winning Combinations

### ISSUE THREAD

**Issue by brianedmunds** [ga-wdi-boston/game-project#507]
I have successfully created a game board in my index.html
```<div class="game-board">
        <div id="0" class ="square zero"></div>
        <div id="1" class ="square one"></div>
        <div id="2" class ="square two"></div>
        <div id="3" class ="square three"></div>
        <div id="4" class ="square four"></div>
        <div id="5" class ="square five"></div>
        <div id="6" class ="square six"></div>
        <div id="7" class ="square seven"></div>
        <div id="8" class ="square eight"></div>
      </div>```

Using JS, I am able to alternate between "X" and "O" when the user selects a cell:
```$('.square').on('click', function () {
  $(this).html(currentPlayer = currentPlayer === player1 ? player2 : player1)
  $(this).unbind('click')
})
```
I've identified each of the possible winning combinations and put them in an array:

```const winningCombinations = [
  [0, 1, 2],
  [0, 3, 6],
  [0, 4, 8],
  [1, 4, 7],
  [2, 4, 6],
  [2, 5, 8],
  [6, 7, 8],
  [3, 4, 5]
  ]```

However, I am now stuck on how to check the player selections made on the board against the possible winning combinations to determine who won.  Not sure where to go from here.  Any guidance would be appreciated.

**Comment by payne-chris-r** [comment]
Reformatting for you (and me):

I have successfully created a game board in my index.html
```html
<div class="game-board">
        <div id="0" class ="square zero"></div>
        <div id="1" class ="square one"></div>
        <div id="2" class ="square two"></div>
        <div id="3" class ="square three"></div>
        <div id="4" class ="square four"></div>
        <div id="5" class ="square five"></div>
        <div id="6" class ="square six"></div>
        <div id="7" class ="square seven"></div>
        <div id="8" class ="square eight"></div>
      </div>
```

Using JS, I am able to alternate between "X" and "O" when the user selects a cell:
```js
$('.square').on('click', function () {
  $(this).html(currentPlayer = currentPlayer === player1 ? player2 : player1)
  $(this).unbind('click')
})
```
I've identified each of the possible winning combinations and put them in an array:

```js
const winningCombinations = [
  [0, 1, 2],
  [0, 3, 6],
  [0, 4, 8],
  [1, 4, 7],
  [2, 4, 6],
  [2, 5, 8],
  [6, 7, 8],
  [3, 4, 5]
  ]
```

However, I am now stuck on how to check the player selections made on the board against the possible winning combinations to determine who won.  Not sure where to go from here.  Any guidance would be appreciated.

**Comment by BenGitsCode** [comment]
What have you tried so far?

**Comment by brianedmunds** [comment]
I tried a few different approaches that I've found via google.  Hard to explain them here as I didn't quite understand them - I copied and pasted portions of code, renamed some pieces to match my existing code, but they didn't work.

**Comment by danman01** [comment]
Think back to [boggle](https://github.com/ga-wdi-boston/js-boggle-challenge): can you find some similarities between the boggle tray and coords and what you're trying to achieve at this stage with this project?

**Comment by brianedmunds** [comment]
Thanks Dan.  I'll revisit boggle and see what I can take away from that.

**Comment by payne-chris-r** [comment]
You'll need to iterate *a lot*.

**Comment by payne-chris-r** [comment]
@brianedmunds please update

**Comment by brianedmunds** [comment]
Thanks for the advice.  I think that I am now on the path to solving this.  Closing this issue.
