### ISSUE TITLE
Want to confirm approach to GITHUB

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/game-project#508]
I think I've been using GIT wrong, I've been spinning of new branches locally and then merging into master.  But I've only pushed master to GITHUB.  Here's a break down of my branching:

  changePW - merged with master but not on GIT HUB
  signIn  - merged with master but not on GIT HUB
  signOut - Branch/feature I am currently working on
  signUp  - merged with master but not on GIT HUB
  wireFrame  - merged with master and on git HUB

does it matter that I kept all those features/branches local or will the history of the merging be clear in master?

**Comment by BenGitsCode** [comment]
For clarification, you're asking what will show on github? What do you mean by does it matter?

**Comment by BenGitsCode** [comment]
This is your current git history of your [project](https://github.com/sjruby/tic-tac-toe-client/network) on your github remote.

**Comment by sjruby** [comment]
Okay yeah that answers my question, the way I'm doing all the splits locally and then merging to master makes it appear that I'm working only in the master branch on GITHUB.  I'm not going to mess with any of the history but will change that work flow go forward.

**Comment by BenGitsCode** [comment]
That's a great insight!

You can close this issue if you'd like, but it'd be a lot cooler if you updated it with your refined workflow first, to better aid future developers with that question. Suggestion, not required.
