### ISSUE TITLE
Trouble with module.exports...

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/game-project#51]
I have a main file with my document ready function and an ajax-interface file with my ajax requests. I am trying to import a resetBoard function to my ajax-interface file so that I wrap board resets in the ajax .done blocks.
I've set it up like this: 

```
main.js
let resetBoard = function () {}
...
module.exports = {resetBoard,};
```

```
ajax-interface.js
let main = require('/main');
let userAction = function() {
$.ajax({//ajax body}).done(function(){main.resetBoard())}
```

However, I keep getting this error:

18:02:20.731 TypeError: main.resetBoard is not a function
signIn/<() bundle.js:833
[17]/</jQuery.Callbacks/fire() vendor.bundle.js:3301
[17]/</jQuery.Callbacks/self.fireWith() vendor.bundle.js:3431
done() vendor.bundle.js:8873
[17]/</</<.send/callback/<() vendor.bundle.js:9239
1 bundle.js:833:6

resetBoard() performs as it ought to when called inside main.js.

**Comment by jrhorn424** [comment]
I'd have to see your code. It looks like this is a minimum example, but I need to see everything for clarity.

Also, the following is an antipattern:

``` js
$.ajax({//ajax body}).done(function(){main.resetBoard())}
```

Instead, prefer this:

``` js
$.ajax({//ajax body}).done(main.resetBoard)
```

Have you tried getting all your functionality working in one file? Things are complected here since you may be running into more than one problem.

**Comment by rchezrutt88** [comment]
Right, I see that there’s no need for that anonymous function.

Haven’t tried refactoring the code into one file yet. At this point it feels like it would require some serious surgery. 

I’m puzzled now because I thought I had a handle on the export/require pattern but now I’m not so sure. 

Let me know if you’d be willing to take a quick peek at my code.

**Comment by rchezrutt88** [comment]
Likely a circular dependence issue.
