### ISSUE TITLE
Issue importing functions

### ISSUE THREAD

**Issue by rrdaniels85** [ga-wdi-boston/game-project#510]
Hello!

I am currently running into issues when I try to import functions from my index.js file into my events.js file. The events.js file is able to import functions from other documents but just not from index.js. As part of my testing, I created a dummy function to see if any function can be passed from index.js to events.js.

In index.js, I created this function and then exported it: 
```
 const testing = function () {
   console.log('it is connected now')
 }
 
 module.exports = {
   testing
 }
 ```
Then, at the top of my events file, I required the index.js file this way: 
```
const getFormFields = require(`../../lib/get-form-fields`)

const api = require('./api')
const ui = require('./ui')
const index = require('../scripts/index')
```
I call the function further down in events.js within clickSquare (a function defined within events.js):
```
const clickSquare = function (event) {
  event.preventDefault()
  console.log('yep, you clicked that square')
  $(this).addClass('selected')
  $(this).html("<img src='assets/styles/images/jedi-yoda.jpg'>")
  $(this).text('X')
  let squareId = $(this).attr('id')
  console.log(squareId)
  index.testing()
}
```
I use this with the click handler at the bottom of events.js: 
```
const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp)
  $('#sign-in').on('submit', onSignIn)
  $('#sign-out').on('submit', onSignOut)
  $('#change-password').on('submit', onChangePassword)
  $('.square').on('click', clickSquare)
}
```
The clickSquare function works through the line with console.log(squareId). It then throws an error when it gets to index.testing(). The error says that index.testing() is not a function. 

At first I thought it was just a path issue when I require the index.js file but I have tried different variations and had a few people look at it with me so I don't think that's the issue at this point. I also tried labeling the index.js file something else (ex. const game) in case index was a reserved word but that did not make a difference. I am basically at at stand still at this point as I've been trying to debug this for close to an hour.

**Comment by jordanallain** [comment]
Do you have a reason for storing the function in the `index.js` file?

**Comment by rrdaniels85** [comment]
I actually just fixed it!

**Comment by rrdaniels85** [comment]
By moving it into another file

**Comment by jordanallain** [comment]
Close issue please!
