### ISSUE TITLE
Git - steps to merge with master

### ISSUE THREAD

**Issue by deeforte** [ga-wdi-boston/game-project#512]
Hello.   I'd like some guidance on best practices to keep an accurate github record of versioning, merging with master without wiping out local copies.

I created a branch called 'feature' to work on basic game board functionality.  I did a commit of that this morning and then a 'git push origin feature".   I have not yet merged with master because I am unsure of the steps.

This afternoon I created another branch 'authorize' to work on the signup/in/out/pswd chg functionality.  I have committed that but not yet pushed it.   

Should I merge the first branch 'feature' (or any other completed (branch) with 'master' before pushing another branch 'authorize'?   or does that not matter?   Should we wait until near the end of project to merge with master?

I've done some research on the merge commands.  Is this correct?
git checkout master
git merge feature
git merge authorize
git push origin master

Thank you very much for your help.   No rush on this (I think).

Dee Dee

**Comment by danman01** [comment]
That flow looks good to me:
```
git checkout master
git merge feature
git merge authorize
git push origin master
```
As for when to merge, I would say, merge when you are happy with the work in the branch and you are comfortable having it in your mainline, master branch. Master should be deployable, meaning you aren't afraid if that code makes it to the live site. Many real-world codebases are updated multiple times a day. So, don't wait until theres a ton of code to merge into master, or you will want to keep pushing back the new code release, and it'll keep growing. Merge in small increments (single branches) and test them out.

You will get a feel for when to merge as you get more practice using git. Don't be afraid to experiment with different strategies and approaches with branching and merging.

**Comment by BenGitsCode** [comment]
☝️ Great advice.  Git is much more forgiving with mistakes than most seem to think it is. 

Don't be afraid of breaking things because that makes you afraid to try things. 

If you break something, it's nothing we haven't fixed before—and if it is we'll be super excited about it!

**Comment by deeforte** [comment]
Thank you!  Very helpful!
