### ISSUE TITLE
x's and o's on game board

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/game-project#513]
I cannot get X's or O's to appear on my gameboard. 
I have reviewed: 
The jquery/dom training: https://github.com/awoodrum87/jquery-dom
.val jquery documentation http://api.jquery.com/val/
.text jquery documentation http://api.jquery.com/text/

**Comment by awoodrum87** [comment]
i'm also unsure where it should go. there are lots of .js files

**Comment by jordanallain** [comment]
what have you tried so far? can i see some code?

**Comment by awoodrum87** [comment]
`const onClickBoard = function () {
  event.preventDefault()
  console.log('works')
}`

`$('#indexZero').on('click', () => { onClickBoard() })`

This displays 'works' in the console when I click on the game tiles. ( all 9 of them, i only included one ajax call)

**Comment by jordanallain** [comment]
Progress!

**Comment by jscohen** [comment]
Hi Angela,

The .text method assigns a text value to the HTML element selected.  So if you had an element with an id of #indexzero, you could assign a value to it using .text like so:

$('#indexzero').text('some text')

If you do this, the text will appear in that element in the DOM.  You could put the above in your function and change the text to 'X'

**Comment by awoodrum87** [comment]
update: kill me.

**Comment by benjimelito** [comment]
That doesn't sound like a positive update (to put it mildly)...I'm guessing that Jon's code didn't help you? Are you still having the same issue?

**Comment by awoodrum87** [comment]
actually johns suggestion allows me to display an X (for example) on either a single game square (by using the id) or on every game square by using the class. 

`const onClickBoard = function () {
  event.preventDefault()
  console.log('works')
  // all 9 squares log 'works'
  $('#indexZero').text('X')
  // the square assigned to indexZero displays and X
}`

click handlers:

`const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp)
  $('#sign-in').on('submit', onSignIn)
  $('#sign-out').on('submit', onSignOut)
  $('#change-password').on('submit', onChangePassword)
  $('#indexZero').on('click', onClickBoard)
  $('#indexOne').on('click', onClickBoard)
  $('#indexTwo').on('click', onClickBoard)
  $('#indexThree').on('click', onClickBoard)
  $('#indexFour').on('click', onClickBoard)
  $('#indexFive').on('click', onClickBoard)
  $('#indexSix').on('click', onClickBoard)
  $('#indexSeven').on('click', onClickBoard)
  $('#indexEight').on('click', onClickBoard)
}`

**Comment by benjimelito** [comment]
Cool 👍  So sounds like this issue is resolved then. If you're having another issue, feel free to close this one and open another.

**Comment by awoodrum87** [comment]
lol not quite. I can't get either get one square to display x or all of them. I can't get anything in between and I don't know how to tie displaying an X or O to my game logic.

**Comment by awoodrum87** [comment]
wooooohoooo
Ben is the best! $('#indexZero').text(symbol)

**Comment by awoodrum87** [comment]
Follow up: Ben helped me determine that using 'this' would force the click handler to display a string x or o on just 'this click. See code below. 

Rather than
`$('#indexZero').text('X')`
where only the square with indexZero id returns X when clicked, I used this.
`$(this).text('X')`
