### ISSUE TITLE
Having trouble finding game ID to update game state

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/game-project#514]
Right now I'm testing trying to run the update game logic, will always update the game array with X for now.  The game  store variable I'm using to try and find the URL is not working.  The error that returns is 404 not found which I think means I must not be assigning the URL correctly.  

```js
const tttClick = function (clickedId) {
  const squareChanged = {
    game: {
      cell: {
        index: clickedId,
        value: 'x'
      },
      over: false
    }
  }

  const data = JSON.stringify(squareChanged)
  console.log(data)

  return $.ajax({
    method: 'PATCH',
    url: app.host + '/games/:' + gameStore.gameStore.id,
    headers: {
      Authorization: 'Token token=' + store.store.token
    },
    data: data
  })
}
```

**Comment by danman01** [comment]
Could you post your entire error message? It'll likely include a few more clues.

I do see this:
```
url: app.host + '/games/:' + gameStore.gameStore.id,
```
So, while we have `:ID` in routes, that actually is how route documentation refers to a placeholder for whatever ID you supply, and the `:` should not be included in your actual url.

**Comment by sjruby** [comment]
Full error below:

Started PATCH "/games/:33" for ::1 at 2017-04-05 19:30:12 -0400
Processing by GamesController#update as */*
  Parameters: {"{\"game\":{\"cell\":{\"index\":\"1\",\"value\":\"x\"},\"over\":false}}"=>nil, "id"=>":33"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "308a627e216052f6c542a5b80a1302a7"]]
  Game Load (0.3ms)  SELECT  "games".* FROM "games" WHERE "games"."id" = $1 LIMIT 1  [["id", 0]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.07ms)
Completed 404 Not Found in 3ms (Views: 0.5ms | ActiveRecord: 0.5ms)

**Comment by jordanallain** [comment]
Did you see the comment from @danman01  ?

> So, while we have `:ID` in routes, that actually is how route documentation refers to a placeholder for whatever ID you supply, and the `:` should not be included in your actual url.
