### ISSUE TITLE
Failing to get unbind to stop a click

### ISSUE THREAD

**Issue by donpowers** [ga-wdi-boston/game-project#515]
Using this syntax

console.log('ID: ' + this.id)
$(this.id).unbind('click.myEvents')

It is failing to stop the click. Ideas?

I was using element.addEventListener('click', flipMark) ...spoke with Chris and mentioned jquery off
I updated the code to use 'on' and I can't get that to work either.

$('elementID').on('click', flipMark)

**Comment by jordanallain** [comment]
what are you passing `unbind` as an argument?

**Comment by danman01** [comment]
You will want to call `off` on the same element which you called `on` (basically allowing the event to fire only once per element). jQuery also has [this `one` method](http://api.jquery.com/one/) which looks interesting.

I would try getting `on` working first, testing with `console.log` and then move to `off` or trying `one`

So, start small and use `console.log` pretty heavily to make sure you are doing what you think you are doing.

**Comment by donpowers** [comment]
Here is the single line of code...not much to it.  I'm using the 'id'...could I be using the wrong way in passing the id? I tried several different ways in passing the id in the $() but nothing seems to work.
If I use   element.addEventListener('click', flipMark) it works as expected

  const elementID = gameCellIDs[i] + '-img'
    console.log('elementID: ' + elementID)
    $('#elementID').one('click', flipMark)

**Comment by jordanallain** [comment]
If that is the EXACT line of code then carefully look at the last line.

**Comment by donpowers** [comment]
Are you referring to the 'one'?  I tried that as well...To attach an event that runs only once and then removes itself, see .one()

**Comment by jordanallain** [comment]
Ah okay sorry, I thought you were still using `.on`

Which of these methods do you plan on trying to use? Also would help if you supplied us with more code and formatted it. You can surround a block of code with three back-ticks before and after it, and `js` after the opening back-ticks.

\```js
  Will format your code to look like js!
\```

**Comment by donpowers** [comment]
This is all the code, nothing else.  I only need to click a single time, one() is the better choice, now that I'm aware of it. 
```js
const elementID = gameCellIDs[i] + '-img'
console.log('elementID: ' + elementID)
$('#elementID').one('click', flipMark)
```

**Comment by jordanallain** [comment]
If that is all the code then what is `gameCellIDs[i]`?

**Comment by payne-chris-r** [comment]
What is `$('#elementID')`? what is `elementID`? What is `#elementID`? Are they all the same thing to the interpreter?

**Comment by donpowers** [comment]
Can I get someone to stop by and review this issue with me?

**Comment by payne-chris-r** [comment]
Please answer the questions we've asked. I don't think the code you've written is doing what you're intending it to do.

**Comment by donpowers** [comment]
const gameCellIDs = [
  'cell-0',
  'cell-1',
  'cell-2',
  'cell-3',
  'cell-4',
  'cell-5',
  'cell-6',
  'cell-7',
  'cell-8'
]
```js
const setUpGameBoard = function () {
  console.log('setUpGameBoard')
  for (let i = 0; i < gameCellIDs.length; i++) {
    const elementID = gameCellIDs[i] + '-img'
    console.log('elementID: ' + elementID)
    $('#elementID').one('click', flipMark)
    //const element = document.getElementById(elementID)
    element.addEventListener('click', flipMark)
  }
}
```
elementID is the ID I assigned to the img tag.  I'm trying to register for events on the img tag.  It works with addEventLinstener but not 'on' or 'one' jquery calls. 

I try several ways to pass the ID to jquery, using # and without and still not getting my callback.

**Comment by tvcrawley** [comment]
If `addEventListener` works, what's the difference between `element.addEventListener('click', flipMark)` and `$('#elementID').one('click', flipMark)` as far as targeting is concerned?

**Comment by tvcrawley** [comment]
Can you share here how the problem was solved? @donpowers

**Comment by donpowers** [comment]
It appears passing a string object(I built the ID ) into the $() was the issue. jQuery does some things to figure out what you're passing it.  Look at this: http://stackoverflow.com/questions/14142303/passing-a-string-to

When I hard coded the string it works as expected.
  $('#cell-0-img').one('click', flipMark)
