### ISSUE TITLE
Where to declare and store the game object

### ISSUE THREAD

**Issue by jkjellan** [ga-wdi-boston/game-project#516]
I know I need to build out a game object that looks like this:

```
{
  "game": {
    "id": 1,
    "cells": ["o","x","o","x","o","x","o","x","o"],
    "over": true,
    "player_x": {
      "id": 1,
      "email": "and@and.com"
    },
    "player_o": {
      "id": 3,
      "email": "dna@dna.com"
    }
  }
}
```
And I know the first step is a POST request to api-url/games, which returns the basic framework for the game object.

But I'm not sure where I should declare and store this object. My game logic need access to it, but so do my API calls. My plan as of now is to build the game object in the same file where I make AJAX requests to the game API, and then require that api.js file in my gameLogic.js file.  I'm just not very confident in this approach.

**Comment by jkjellan** [comment]
I'm actually thinking now that I should build the game object in the ui.js file where I receive back the ajax response, not in api.js where I made the request.  And then require ui.js in my gameLogic.js file.

**Comment by jordanallain** [comment]
What do you mean by 'build the game object'? 

Have you seen the response of a POST request to that url using curl or in the README?

**Comment by jkjellan** [comment]
Yes, I know know the AJAX requests hand back an object. I guess I'm just not sure how to pass that object to my game logic functions to test for a win, etc.

**Comment by jordanallain** [comment]
Have you tried anything or do you have any thoughts?

**Comment by jkjellan** [comment]
Just having trouble wrapping my head around it.  Going to try calling my game-logic functions from the ui.js file, passing in the ajax response (i.e. the game object) as an argument.

**Comment by jordanallain** [comment]
edit: also that sounds like a good thing to try

Refer back to the books and library api that we went over if you need a reference.

https://github.com/ga-wdi-boston/jquery-ajax-post/tree/master/assets/scripts/books

I think that could help you trace the steps out.

**Comment by jkjellan** [comment]
Thanks I'll take a look.

**Comment by payne-chris-r** [comment]
New phone. Who dis? (AKA please add a github photo)

**Comment by rlarsonil71** [comment]
Jim Kjellan

**Comment by payne-chris-r** [comment]
I know who it is @rlarsonil71 ! :stuck_out_tongue_winking_eye:

**Comment by payne-chris-r** [comment]
@jkjellan you probably want to store the game you get back in your `store` object. Just like we have `store.user`, why not have `store.game`?

**Comment by jkjellan** [comment]
I'm worried that I didn't organize my logic functions properly.  I had a working game, but when I tried to refactor to call the logic functions from index.js, I'm just getting a mess.  I don't even know what question to ask right now.  I think I just need to talk through the basic structure of my game with someone.

**Comment by tvcrawley** [comment]
Since there have been a lot of changes made, make sure the correct files are required and the correct functions/objects/etc are exported. If you're still mixed up afterwards, start with one file and go through it line by line making sure it is appropriately linked to what you want and do this for each file you refactored.

**Comment by jkjellan** [comment]
Ok I'm feeling better about the game logic now.  I created one entry point function to all of my game logic (handleClick), which calls all my other logic functions (checkWin, and renderBoard), and I'm only exporting handleClick to index.js . Now things are much less screwy, and I'm moving on to the AJAX game requests.

**Comment by BenGitsCode** [comment]
@jkjellan please close this issue if you're satisifed with the resolution.

**Comment by jkjellan** [comment]
I'm good for now. I'm sure I'll have more questions!
