### ISSUE TITLE
index.js and index.scss appear 'missing' but are there

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/game-project#517]
Issue:  I made duplicates of both of these files because I was doing some testing with some drastic changes, and didn't want to complicate the code I alredy had.  I created backup copies of each and named them indexBackup.js and indexBackup.html.  I then proceeded to make changes on the originals, index.js and index.html.  When I was finished, I no longer wanted the testing I had done so I deleted index.js and index.html, and then restored by renaming indexBackup.js and indexBackup.html to their original names, index.js and index.html.  The files are back intact, but I'm receiving issues when trying to view on http://localhost:7165/ .  I'm assuming it thinks the files were permanently deleted.  What can I do to resolve?

<img width="952" alt="screen shot 2017-04-05 at 11 30 52 pm" src="https://cloud.githubusercontent.com/assets/26150525/24736856/9f1d3210-1a58-11e7-9186-a00585b8a747.png">

**Comment by jonifallon** [comment]
Update:  it's the assets/styles/index.scss and the index.js file that are missing, not index.html.

**Comment by jordanallain** [comment]
Are the files in the correct location?

Have you compared them to the files of the same name in the browser-template to see if you maybe forget to add something back in that needs to be there?

**Comment by jonifallon** [comment]
The browser-template code appeared to be the same, but I repasted it in those files and now it works!  thanks, Jordan!

**Comment by jonifallon** [comment]
It's doing it again.

**Comment by benjimelito** [comment]
Hold on Joni, I'm coming over to take a look

**Comment by jonifallon** [comment]
Haven't had the issue for 20 minutes or so, and Ben helped me understand what the error actually means (not that the file isn't there, but there's code issues).  Whatever bad code it saw is no longer there, so hopefully this is resolved.
