### ISSUE TITLE
Struggling to pass GameStore Object Array

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/game-project#519]
I have a function called "turn switcher" that is supposed to check whose turn it is that's not working.  I think it's because I'm not passing the game.cells array as I expected.  Been messing around with just getting my gameStore object to print in the log when I click on a cell but can't get it to work.

The code below is what I have as my .then success function for when the tttClick API function runs.  I know that the .tttClick API pass is being successful b/c the back end is returning the code of 200
Not sure why I can't get the log to print the game store cells.

```js
const clickSuccess = function (data) {
  gameStore.gameStore = data.game
  console.log(gameStore.game.cells)
}
```

**Comment by benjimelito** [comment]
Are you getting anything in the console to log, or is nothing showing up at all? Also, would you mind attaching the code you have for the entire `tttClick` function?

**Comment by sjruby** [comment]
Here's the tttClick function, console log isn't returning anything:

```js

const tttClick = function (clickedId) {
  const clickedCell = clickedId * 1

  return $.ajax({
    method: 'PATCH',
    url: app.host + '/games/' + gameStore.gameStore.id,
    headers: {
      Authorization: 'Token token=' + store.store.token
    },
    data: {
      'game': {
        'cell': {
          'index': clickedCell,
          'value': 'x'
        },
        'over': false
      }
    }
  })
}
```

**Comment by sjruby** [comment]
I'm getting stuck b/c the .then success function for my newGame api call is working and looks almost the same: 
``` js
const newGameSuccess = function (data) {
  gameStore.gameStore = data.game
  $gameStatus.text(store.store.email + ' created game number ' + gameStore.gameStore.id)
  console.log(data.game.cells)
  console.log(gameStore.gameStore.cells)
}
```

**Comment by benjimelito** [comment]
Gotcha. First I would make sure 100% that your ` tttClick` function is working correctly by attaching a `.catch` function after the `.then` to see if there could be some sort of error. I also might try putting a console.log statement before your `clickSuccess` function fires in the `.then` to see if you are getting to that point.

**Comment by benjimelito** [comment]
Make sure to close this out when you get a chance ✌️

**Comment by sjruby** [comment]
thanks!
