### ISSUE TITLE
Need to discuss logic and order in which I should do things

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/game-project#521]
I have given up on the logic I was trying to write and am instead looking to 'reuse' some code I found online.  I've wasted too much time trying to figure it out.  The code I found, which for the most part makes sense to me, uses an automated computer.  I've tried to take that auto functionality out, but it isn't working and I'm wondering how much time I should spend trying to take it out.

I also need help understanding what order I should do things.  I'm really frustrated, tired, and just need some guidance.  If someone could spend some time with me helping me to get back on track, I would appreciate it.

**Comment by BenGitsCode** [comment]
I suggest getting up and taking a brisk walk, grab some water tea/coffee and give yourself a quick break.

After that I'd like you to try pseudo coding out what you need your game logic to do for you. If you could just talk to the computer and tell it the code needs to _do_ what would you say to it?

I think that's a great place to start and will help you back on track! Post it here and we can go over it together.

**Comment by payne-chris-r** [comment]
How's the pseudocoding go @jonifallon? Do you have a good set of "next steps"?

**Comment by jonifallon** [comment]
A couple of my coworkers helped me get back on the right path.  I understand the directive to 'take a walk' to clear my head, but given the deadline, that's not the help I was looking for.  I will be more explicit about the fact that I need to speak with someone verbally the next time I open an issue.
