### ISSUE TITLE
Can't add second player via AJAX

### ISSUE THREAD

**Issue by jscohen** [ga-wdi-boston/game-project#522]
I am trying to use the PATCH function to add player o to my games.  I have the following CURL script that works: 

```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/games/$ID"
curl "${API}${URL_PATH}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
```

Basically the flow is: Player 1 signs in, Player 1 starts a new game, Player 2 Signs in, Player 2 joins the game.

However, my AJAX call is giving me a 400 error:

```
const joinGame = () => {
  return $.ajax({
    url: config.apiOrigin + '/games/' + games.game.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + players.player.token
    }
  })
}
```

I was also trying before to have two players signed in at once and stored in a global players object, but couldn't get that to work either.

**Comment by BenGitsCode** [comment]
Please post the actual error.

**Comment by jscohen** [comment]
﻿```
vendor.js:17471 XHR failed loading: PATCH "http://localhost:4741/games/89".
```

In this case, the patch is not happening and player o is not populated.

**Comment by jscohen** [comment]
So rookie mistake - I forgot to add event.preventDefault() on my call function that hits the api:

```
const p2joinGame = function () {
  event.preventDefault()
  console.log('Join Game Started')
  if (games.game.game === undefined) {
    $('.pl').text('You need to start a game first!')
    return false
  }
  api.joinGame().then(ui.joinGameSuccess)
  .catch(ui.joinGameFailure)
}
```

Now that I call the AJAX function below it works but player o is still not being populated.

```
const joinGame = () => {
  return $.ajax({
    url: config.apiOrigin + '/games/' + games.game.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + players.player.token
    }
  })
}
```

What I expect: for the games.game.game object's player o field to be populated by the user with the players.player.token provided in the join game function

What I'm getting: games.game.game object's player o field is null

**Comment by jordanallain** [comment]
have you compared your `joinGame` AJAX call to the AJAX call that creates a new game?

**Comment by payne-chris-r** [comment]
Hey Jon,
I love that you're tackling this. I just want to make sure you feel comfortable that you've met requirements and have no user facing bugs before you try to go for a stretch goal!

**Comment by jscohen** [comment]
Hey Chris,

I haven't met all the requirements yet, so I decided to hold off on this for now.

Thanks,

 - Jon

**Comment by benjimelito** [comment]
Sounds good Jon, please close this issue when you get a chance!

**Comment by payne-chris-r** [comment]
Also, add a picture on github profile!!
