### ISSUE TITLE
having issues firing off an action in event.js when selecting a dropdown item

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/game-project#524]
```HTML
        <ul class="nav navbar-nav navbar-right">
          <!-- <li><a href="#">Link</a></li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Game Actions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#" data-target="#createGame">Create Game</a></li>
              <li><a href="#">********</a></li>
              <li><a href="#">********</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">********</a></li>
            </ul>
          </li>
        </ul>
```

```event.js
const addHandlers = () => {
  $('#createGame').on('select', onCreateGame)
```

I click on the "Create Game" and nothing seems to fire

**Comment by BenGitsCode** [comment]
wat?

**Comment by BenGitsCode** [comment]
Please review [this](https://github.com/ga-wdi-boston/project-issue-tracker-guide#how-to-use-the-issue-tracker)

**Comment by BenGitsCode** [comment]
and [this](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by octater** [comment]
the code is between ''' and '''

**Comment by octater** [comment]
my bad.  wrong tick marks

**Comment by jordanallain** [comment]
What are you targeting with `$('#createGame')`

**Comment by octater** [comment]
#createGame is targeted to the dropdown item "create game".  when the user selects this value from the dropdown, I want to fire some code

**Comment by jordanallain** [comment]
the way you have set `#createGame` on that anchor tag doesn't look like the way we have previously done it. Have you checked out the jQuery lessons we did to see how we set an ID and use jQuery to select it?

**Comment by octater** [comment]
Thanks Jordan.  I am now able to get the action started from the dropdown
