### ISSUE TITLE
GitHub Pages Error on Deploy

### ISSUE THREAD

**Issue by danielleletarte** [ga-wdi-boston/game-project#525]
I'm getting the Project Not Found creature when I run grunt deploy after pushing my Master branch. 

![image](https://cloud.githubusercontent.com/assets/25553014/24766180/5a72a9a4-1ac8-11e7-8dea-ebc691dc23db.png)

I am using the following domain name: danielleletarte.github.io/tic-tac-toe-client

**Comment by jordanallain** [comment]
did you go through the steps in the gh-pages-deployment-guide?

**Comment by BenGitsCode** [comment]
Please ensure you have followed the steps in the guide completely.

If you have and still have the issue, I will take a look at it.

**Comment by danielleletarte** [comment]
Yes, I followed the directions with no luck. Still getting the "Project Not Found" error.

**Comment by BenGitsCode** [comment]
Let's take a look. Where are you?

**Comment by BenGitsCode** [comment]
Can you please close your issue, with a summation of the resolution?

**Comment by danielleletarte** [comment]
My GitHub pages was publishing to my personal website rather than the default github.io location. This was a setting in my GitHub account left over from when it was used exclusively for personal projects. Fixed now, thanks Ben!
