### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by brianedmunds** [ga-wdi-boston/game-project#526]
In the console, whenever I enter the name of one of my declared variables, I get the following message: "VM2704:1 Uncaught ReferenceError: winningCombinations is not defined"

This is what the winningCombinations variable looks like in my js file:

```
const winningCombinations = [
  // Horizontal
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],

  // Vertical
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8],

  // Diagonal
  [0, 4, 8],
  [2, 4, 6]
]
```
I would expect for the array to be returned in the console, but the error displays instead.  Haven't been able to identify a cause for this.  Same thing is happening for other variables as well. 
 Thoughts?

**Comment by benjimelito** [comment]
Is it possible you're not exporting the file where this code lives? Would you mind posting in the entire file where this code lives, and also the file where you're using it?

**Comment by payne-chris-r** [comment]
Are you trying to interact with your script as it runs? You probably want a debugger in there if you do. Otherwise, just use a console.log to see inside your variable.

**Comment by brianedmunds** [comment]
I can console.log it successfully, and I see the expected values in the console when I do that.  It's when I try to enter the variable name into the console itself that I get error.  

Ben - here is the entire file:

```
'use strict'

const setAPIOrigin = require('../../lib/set-api-origin')
const config = require('./config')

$(() => {
  setAPIOrigin(location, config)
})

// use require with a reference to bundle the file and use it in this file
// const example = require('./example')

// use require without a reference to ensure a file is bundled
require('./example')

const authEvents = require('./auth/events.js')

// On document ready
$(() => {
  authEvents.addHandlers()
})

const winningCombinations = [
  // Horizontal
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],

  // Vertical
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8],

  // Diagonal
  [0, 4, 8],
  [2, 4, 6]
]

const chosenSquares = {
  'x': [],
  'o': []
}

let currentPlayerToken = 'x'

$('.board').on('click', '.square', function (event) {
  const square = $(event.currentTarget)
  $(this).text(currentPlayerToken)

  const indexOfSquare = $('.square').index(square)
  const currentPlayerSquares = chosenSquares[currentPlayerToken]
  currentPlayerSquares.push(indexOfSquare)
  console.log(winningCombinations)

    // Check for win
    //
    // For each winning combination
  $.each(winningCombinations, function (index, combination) {
      // Stary by assuming that the player has all of the squares
    let hasAllSquares = true

      // For each of squares in the combination
    $.each(combination, function (index, square) {
        // If the player's chosen squares does not contain the current square
      if ($.inArray(square, currentPlayerSquares) === -1) {
        hasAllSquares = false
      }
    })

      // Display the winner
    if (hasAllSquares) {
      alert(currentPlayerToken + ' wins!')
    }
  })

  if (currentPlayerToken === 'x') {
    currentPlayerToken = 'o'
  } else {
    currentPlayerToken = 'x'
  }
  $(this).unbind('click')
})
```

**Comment by jordanallain** [comment]
so to clarify, when you enter `console.log(winningCombinations)` it logs the array to the console, but when you enter `winningCombinations` to the console it says it is undefined?

**Comment by BenGitsCode** [comment]
👉 https://github.com/ga-wdi-boston/game-project/issues/526#issuecomment-292251661

**Comment by brianedmunds** [comment]
Jordan - yes, that is correct

**Comment by jordanallain** [comment]
Any updates @brianedmunds ?

**Comment by brianedmunds** [comment]
I am all set now.  Ben sent a couple of minutes chatting with me and cleared things up.  Thanks all.
