### ISSUE TITLE
.then problems

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/game-project#527]
I have a step in a function that calls the API to update the game over to true based on some
predicate logic. 

```js 
  if (arraysToCheck.some(xWins)) {
    result = 'x Wins'
    api.endGame()
      .then(console.log('I prove the end game API function ran!'), ui.endGameSuccess)
      .catch(ui.endGameFailure)
  }
```
I know the endGame() is working b/c the consle log happens.  ui is defined as:

```js
const ui = require('../gameEventsUI')
```

Inside of that gamesEventsUi file there is the function I think should run but is not:

```js
const endGameSuccess = function (response) {
  console.log('I would prove that end game success ran thing ran')
}
```

**Comment by benjimelito** [comment]
So I would look at the docs for `.then` online and make sure that you are following the correct structure for passing functions in. I think your functions are working properly, but not firing when you want them to.

**Comment by payne-chris-r** [comment]
👆what Ben said. What does `.then()` expect as an argument?

**Comment by sjruby** [comment]
I looked at the documentation and am still confused, I got rid of the console log to b/c it looks like the endGameSuccess funciton was being passed to the "failedCallBack".  But it's still not working, looking at it against an example of .then that works I don't know what the error is.

working .then from newGame function:
```js
  api.newGame()
    .then(ui.newGameSuccess)
    .catch(ui.newGameFailure)
```

Failing .then:
```js
 api.endGame()
    .then(ui.endGameSuccess)
    .catch(ui.endGameFailure)
```

**Comment by jordanallain** [comment]
have you put console.log statements in both ui.endGameSuccess and ui.endGameFailure to see if it makes it into either of those?

**Comment by sjruby** [comment]
Yeah both statements are just trying to spit out a console log to let me know it ran, that's how I know it's not triggering, b/c the console log isn't working.  I can see the right status code message on my back end server, so I know it worked, and if I swap ui.endGameSuccess for a simple console log it works.

**Comment by jordanallain** [comment]
have you exported and required all the appropriate functions?

**Comment by sjruby** [comment]
yes b/c when I change the code the function runs and creates a different error but trys to call the right function.  
 
```js
api.newGame()
    .then(ui.newGameSuccess())
    .catch(ui.newGameFailure)
}
```

**Comment by jordanallain** [comment]
wanna meet me in the kitchen and we can dig through it?

**Comment by jordanallain** [comment]
Sam is going to follow his file flow to make sure he doesn't have a dependency loop.

**Comment by sjruby** [comment]
That was it, thanks Jordan!

**Comment by jordanallain** [comment]
@sjruby if you're all set maybe give a bit of advice and close the issue, thanks!
