### ISSUE TITLE
Reset API Database

### ISSUE THREAD

**Issue by buffalo0707** [ga-wdi-boston/game-project#528]
My game-project-api database is full of bogus game data as a result of some bugs in my client code. I'd like to reset the DB to get this data out.

I found this article with a [possible solution](http://stackoverflow.com/questions/4003978/reset-the-database-purge-all-then-seed-a-database):

Per the SO article, I can reset the DB with the following two commands:

```sh
rake db:reset
rake db:drop db:create db:migrate db:seed
```

Can you advise if this is a good idea or the right command before I attempt to run it? I don't want to hose my DB...

**Comment by jordanallain** [comment]
>  I don't want to hose my DB...

what do you mean by hose?

**Comment by payne-chris-r** [comment]
I think you're on the right track. Never used db:reset. I walked Steve through the steps as well in a closed issue somewhere.

**Comment by buffalo0707** [comment]
By hose, I mean break it.

I tried running db:reset but got this error:
```sh
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 11.3.0. Prepending `bundle exec` to your command may solve this.
```
I did what it said and ran:
```sh
bundle exec db:reset
```
and it worked!

Thanks folks.
