### ISSUE TITLE
Are bootstrap modals allowed?

### ISSUE THREAD

**Issue by khan-ngo** [ga-wdi-boston/game-project#529]
I understand alerts are not allowed. Are bootstrap modals allowed?

**Comment by jordanallain** [comment]
Absolutely!

**Comment by Jcornmanhomonoff** [comment]
@kqngo Please close this issue, thanks 🙃

**Comment by tvcrawley** [comment]
@kqngo If you have received a satisfactory answer, please **close** this issue

**Comment by khan-ngo** [comment]
thanks for your inputs :-)
