### ISSUE TITLE
How do I see my data at localhost:4741/users

### ISSUE THREAD

**Issue by khan-ngo** [ga-wdi-boston/game-project#530]
Using game project API:
==========================
http://localhost:4741/users
outputsHTTP Token: Access denied.

Tried to access via curl, but I'm not encouraged by the result:
==========================
$ curl --include --request GET http://localhost:4741/users
HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 6a7242cb-061f-40d0-81b1-65fae7843bb0
X-Runtime: 0.002086
Vary: Origin
Transfer-Encoding: chunked

HTTP Token: Access denied.

**Comment by Jcornmanhomonoff** [comment]
Are you sure you're using the correct Token?

**Comment by BenGitsCode** [comment]
Errors _are_ encouraging, they tell us what isn't working.

`HTTP/1.1 401 Unauthorized` you're making an unauthorized request.

Just as Jessica said, are you sure you have the right token? Please post the command you used to run that curl request.

**Comment by payne-chris-r** [comment]
I think Ben is looking for you to paste the entire curl req below.

**Comment by BenGitsCode** [comment]
That I am.

you posted the curl request you executed but not _how_ you typed the command to run said script. 

I wanna see that.

**Comment by payne-chris-r** [comment]
@kqngo why are you trying to access `localhost:4741/users`?

**Comment by tvcrawley** [comment]
@kqngo If you are still having trouble seeing data at `localhost:4741/users`, please **answer all** the above questions so that we may better help you.

**Comment by khan-ngo** [comment]
I was looking for quick access, but am able to access this data via curl by passing the required Token. I'm all set, thank you.
