### ISSUE TITLE
Setting img to clickable on new game

### ISSUE THREAD

**Issue by deeforte** [ga-wdi-boston/game-project#531]
Hello. Need assistance with clearing clicks on the squares that were used on the previous game.

As squares are clicked I am moving an X or O image to the square and making that square unclickable with a $(this).unbind('click') statement. When I clear the board for a new game I'm able to move a blank img to the square, but not able to clear the click attribute so that that square can be used in the new game. Able to click on other squares in new game but not those used in first game.

Have tried..
document.getElementsByTagName('img')[i].onclick = true
document.getElementsByClassName('.square').onclick = true

Any advice?

Thank you!

Dee Dee

**Comment by jordanallain** [comment]
so you are using `unbind` to turn off the event listener?

**Comment by deeforte** [comment]
Yes.  I had tried .off('click') but had the same issue.   Should I use something other than unbind to take used squares out of play?

**Comment by jordanallain** [comment]
you will just need to do something to activate those event listeners again when someone wants to start a new game

**Comment by jordanallain** [comment]
Any updates @deeforte ?

**Comment by deeforte** [comment]
I spent a couple hours researching and could not find the answer.  Instead of using unbind / bind I changed code to send an alert & return if a square has already been clicked on.   I'll close issue.

Thank you!!!
