### ISSUE TITLE
Unable to checkout another branch

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/game-project#532]
I deployed and closed Chrome page displaying my site.

Wasnt able to checkout another branch.

git checkout newfeature is aborted every time I try.

What I'm seeing now:

Aborting
~/wdi/projects/tic-tac-toe-client (gh-pages)
$ 

I didn't make any substantive changes before I realized I'm on gh-pages branch.

Can we force checkout with loss of those changes?

Thanks.

**Comment by jordanallain** [comment]
i'm not sure what you're problem is. are you trying to create a new branch or checkout to an existing one?

**Comment by lisamsmith100** [comment]
checkout an already-existing branch called newfeature.

**Comment by lisamsmith100** [comment]
Also, I'm unable to use command 'grunt serve' on that branch.  Need some help troubleshooting this issue as I cannot make any additional changes on the gh-pages branch.  Would love some help.  Thank you!

**Comment by jordanallain** [comment]
ok, coming over

**Comment by lisamsmith100** [comment]
Thank you, Jordan!
We added/committed changes (side eff. from grunt deploy).
After we made the changes, we were able to move to master branch, confirm that files were present in Atom, and then 'checkout newfeature' branch.

If, when using 'grunt deploy' there is an error, I will open another issue (with warning that we may need to delete 'gh-pages' branch.  Closing this issue.

**Comment by lisamsmith100** [comment]
Thank you!
