### ISSUE TITLE
GitHub: Creating a new branch off of master doesn't have my most recent changes

### ISSUE THREAD

**Issue by aeabbott** [ga-wdi-boston/game-project#534]
I think I was creating my new branches off of other branches instead of creating the branches off of master which caused my problem, so now it seems my master branch is out of sync. I don't know how to fix it.

**Comment by jordanallain** [comment]
does your newest branch have all the changes you want?

**Comment by aeabbott** [comment]
The latest branch I was working on has all my changes from all my previous branches.

**Comment by jordanallain** [comment]
Okay so you can merge that branch into master and it will have all the changes.

Typically the workflow is you make a branch off of master, when you are finished with that code you merge it into master, then you branch off of master again to work on the next bit.

**Comment by BenGitsCode** [comment]
(please change your github profile picture to picture of yourself)

**Comment by jordanallain** [comment]
@aeabbott And close the issue if that fixed it !

**Comment by aeabbott** [comment]
I learned that my local master branch can be off from github's master branch to resolve I went to my master branch from my terminal and did a git pull origin master and now my local branch is up to date. Thanks for the help!

**Comment by jordanallain** [comment]
Specifically, she had pushed her feature branch and merged to master via a pull request on github.com but hadn't merged locally. So her github master branch was ahead of her local master branch.
