### ISSUE TITLE
Getting Modals to Connect w

### ISSUE THREAD

**Issue by rrdaniels85** [ga-wdi-boston/game-project#535]
I am currently struggling with getting my modal buttons to connect appropriately with my event handlers and other functions for sign-in. Before adding modals, I was successfully able to get sign in, sign up, sign out, and change password to function correctly.

The first modal that I have tackled is sign-in. The button shows up, and when I click on it, it brings up the modal with the email address and password field. However, when I click sign in, nothing happens and the page simply refreshes. I think somehow I am not listening to the correct element with my event hander but cannot figure out what the issue is. Here is the code for my modal and for my event listener: 
```
<!-- Modal button -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#sign-in-form">
        Sign In/Sign Up
      </button>

      <!-- Modal -->
      <form class="modal fade" id="sign-in-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Continue Your Jedi Training!</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="sign-in">
              <fieldset>
              <legend>Continue Your Training - Sign in!</legend>
              <input name="credentials[email]" type="text" id="sign-in-email" placeholder="Email">
              <input name="credentials[password]" type="password" id="sign-in-password" placeholder="Password">
              <input type="submit" name="submit" value="Sign in!">
            </fieldset>
            </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
```
Event handler
```
  $('#sign-in').on('submit', onSignIn)
```
function for onSignIn
```
const onSignIn = function (event) {
  event.preventDefault()
  console.log('sign in ran')
  const data = getFormFields(this)
  api.signIn(data)
    .then(ui.signInSuccess)
    .catch(ui.signInFailure)
}
```

**Comment by benjimelito** [comment]
This sounds somewhat similar to an issue Ron had, have you checked out https://github.com/ga-wdi-boston/game-project/issues/518?

**Comment by BenGitsCode** [comment]
What have you tried so far? I see the `console.log` in `onSignIn`  ( 👍 ) but have you tried using a debugger from the start of that chain?

Have you tried carefully reviewing the bootstrap code in your html?

**Comment by rrdaniels85** [comment]
No - ill check it out

**Comment by rrdaniels85** [comment]
Looked at Ron's issue and it appeared his was more tied to the fact that his modal was nested in a nav bar which mine is not.

**Comment by rrdaniels85** [comment]
After manipulating it a little, i'm getting a linter error that the form field shouldn't be nested

**Comment by rrdaniels85** [comment]
<img width="959" alt="error" src="https://cloud.githubusercontent.com/assets/26202864/24774189/04aa8dd4-1ae6-11e7-8496-94e463b68986.png">

**Comment by rrdaniels85** [comment]
says <form> shouldn't be nested

**Comment by payne-chris-r** [comment]
Yeah, I think the problem is if you have a nested form, it doesn't know which is being submitted on click of the 'submit' button? I think you need to un-nest your forms.

**Comment by BenGitsCode** [comment]
❓ Are you unsure of how to address the error? I'm just confused by the last comment.

**Comment by rrdaniels85** [comment]
OK - i worked it out with some awesome classmates and we figured out it was a nesting issue and they worked with me to fix it. thanks!

**Comment by payne-chris-r** [comment]
Booyah! Nicely done.

**Comment by BenGitsCode** [comment]
Teamwork ftw! please close the issue @rrdaniels85

**Comment by rrdaniels85** [comment]
thanks guys!
