### ISSUE TITLE
Create a game

### ISSUE THREAD

**Issue by MattKwonDo** [ga-wdi-boston/game-project#536]
Not sure how to go about creating a game. 

In index.html I have this button, which doesn't do anything yet:
``` html
        <h2>Play a new game</h2>
        <form class='games' id='game-create'>
          <div class="form-group">
          </div>
          <button type="submit" class="btn btn-default">New game!</button>
        </form>
```

In index.js I have this submit handler function for the button:
``` js
const authEvents = require('./auth/events.js')
$(() => {
  authEvents.addHandlers()

  $('#game-create').on('submit', authEvents.onCreategame)
  $('#games-search').on('submit', authEvents.onGetgames)
  $('#game-search').on('submit', authEvents.onGetgame)
  // $('#game-delete').on('submit', authEvents.onDeletegame)
  $('#game-update').on('submit', authEvents.onUpdategame)
})
```

In my events.js file I have this function that is run when the button is clicked:
``` js
const gameApi = require('./gameApi.js')
const gameUi = require('./gameUi.js')

const onCreateGame = function (event) { // deleted event
  event.preventDefault()
  const data = getFormFields(event.target)
  const game = data.game

  if (game.id.length !== 0) {
    gameApi.create(data)
    .then(gameUi.onNoContentSuccess)
    .catch(gameUi.onError)
  } else {
    console.log('this ran!')
  }
}

module.exports = {
  addHandlers,
  valueCalc,
  onCreateGame,
  onGetGames,
  onGetGame,
  onDeleteGame,
  onUpdateGame
}
```

In my gameApi.js file I have this function (temporarily just have dummy data):
``` js
const create = function (data) {
  return $.ajax({
    url: app.host + '/games/',
    method: 'POST',
    // data: data
    data: {
      'game': {
        'id': 3,
        'cells': ['x','o','x','o','x','o','x','o','x'],
        'over': true,
        'player_x': {
          'id': 1,
          'email': 'and@and.com'
        },
        'player_o': null
      }
    }
  })
}
```

**Comment by benjimelito** [comment]
What signs are you getting that the game is not being successfully created?

**Comment by MattKwonDo** [comment]
nothing shows up in terminal that indicates a request was sent to the server

**Comment by benjimelito** [comment]
I would probably start by throwing in some `console.logs` at each step to see where the chain is getting broken. This will help you determine if the issue is with attaching your click handler, or your API call, or your `onCreateGame` function...etc.

**Comment by MattKwonDo** [comment]
Thanks, good idea, pretty brain dead at this point haha 
So when I did that I found that I had a casing issue, after resolving that I found that the "create" function is breaking.

**Comment by MattKwonDo** [comment]
Not really sure where to go from here

**Comment by jordanallain** [comment]
what do you mean your function is breaking? is your code reaching that function?

**Comment by MattKwonDo** [comment]
sorry that wasn't clear, but nothing seems to happen after the console log.

**Comment by jordanallain** [comment]
looks like you are checking the length of a number `game.id.length !== 0`

that might be an issue

**Comment by MattKwonDo** [comment]
I think it's getting past there, based on where I inserted my console logs and the output. I think my issue is more conceptually I'm not sure what I need to pass. I'm going to keep working on this tonight. Thanks guys!

**Comment by jordanallain** [comment]
Any updates @MattKwonDo ? #516 may be a good reference

**Comment by MattKwonDo** [comment]
I'm working through documentation to get a better understanding of what's going on atm

**Comment by MattKwonDo** [comment]
got it to work, made a number of updates:

In index.html I updated the button to be cleaner and removed extra stuff:
``` html
    <button type="button" class="btn btn-primary btn-lg" id='game-create-new' >New Game!</button>
```

In my events.js file I deleted a few lines that had consts I didn't need and also the if statement:
``` js
const onCreateGame = function (event) {
  event.preventDefault()
  console.log('1 ran!')
  gameApi.create()
    .then(gameUi.onNoContentSuccess)
    .catch(gameUi.onError)
  console.log('3 ran!')
}
```

In my gameApi.js file I deleted the data, changed the url, and added the authorization token):
``` js
const create = function () {
  console.log('2 ran!')
  return $.ajax({
    url: config.apiOrigin + '/games/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
