### ISSUE TITLE
Exit a game after win + Back End High Level

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/game-project#537]
I have a function that determines the winner successfully yet it still allows the user to keep clicking the game board. For now I just have it showing the winner in console.log. I have a return statement after a winner is found in the function but that doesn't prevent me from calling the function again. I didn't bother pasting code here as my function is 130 lines. Might be easier to show in person.

My second request is to discuss the back end components to tee me up for tomorrow. I don't have any code written here but don't follow the requirements on what is needed here.

**Comment by benjimelito** [comment]
No worries, I would probably file a second issue for your second request however. As for your first request, how are you determining a winner? In the case that a winner is determined, could you add in some more code to disable click handlers on your game board?

**Comment by glasneed** [comment]
OK, I will try the disable of a click handler. Wasn't aware there even was such a thing. All I've seen so far is the onclick functionality. Thanks. I'll open a second issue about the back end after I look through it tonight.

**Comment by glasneed** [comment]
I was able to disable the click handler so I'll close this ticket.
