### ISSUE TITLE
Need help if possible.  having an issue where X is not going first

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/game-project#539]
Hello All,

Here is my problem, I got the winning combo and it seems to be working but my first click seems to be off every time.  I'm a little confused since I think I got the right functions for it.  if current player is X  base on the currentTurn function it should go X.  

const player1 = 'X'
const player2 = 'O'
// let board = new Array(9)
let currentPlayer = 'X'
const tileObject = {[player1]: [], [player2]: []}

// currentTurn function that works out who goes first
const currentTurn = function () {
  console.log(currentPlayer)
  currentPlayer = currentPlayer === player1 ? player2 : player1
  return currentPlayer
}

// start function that goes of the click event
const start = function () {
  $(this).html(currentTurn)
  $(this).unbind('click')
}`

**Comment by Ryaong792** [comment]
forgot the add Console log does show X being inputted but still shows '0'.

events.js:108 update cell this:  <div class=​"square sq1" id=​"box-0">​O​</div>​
2017-04-07 07:24:23.268 events.js:110 this element id = box-0
2017-04-07 07:24:23.268 events.js:114 X [0]0: 0length: 1__proto__: Array(0) 0
2017-04-07 07:24:23.271 events.js:11 X

**Comment by jordanallain** [comment]
@Ryaong792  update !

**Comment by Ryaong792** [comment]
updating and closing.   Rachel was able to help me out where I was missing the issue.  
main problem with my console log:

const currentTurn = function () {
  console.log(currentPlayer)
  currentPlayer = (currentPlayer === player1) ? player2 : player1
  console.log(currentPlayer)
  return currentPlayer

first I had it before the action so it did not show the right logs.
2nd was that

const start = function () {
  $(this).html(currentPlayer)
  currentTurn()
  $(this).unbind('click')

that setting to current player first then going to the turn function.  ALL night I was not able to get this done but having someone from cohort to help.   Thanks anyways!!! :).
