### ISSUE TITLE
Request guidance on objects

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/game-project#540]
I'd like some guidance on the project, particularly making sure my objects are correct and logic makes sense, making sure I'm on the right track.

I've got authentication done, curl request for create game, deploy complete but want another set of eyes on it.  I want to make sure I have things set up well.
Would someone have 5-10 minutes to sit with me today to offer pointers?
Thank you.

**Comment by payne-chris-r** [comment]
Are you stuck on something, or just looking for reassurance?

**Comment by lisamsmith100** [comment]
I'm not able to make the on('click', function) work and wondering why.  Also before I go down a rabbit hole with game logic and objects, want to make sure I'm on right path.  I think I am, but with time constraints, I want to make sure before I spend too much time on any one part.
So, confirmation that my objects are set up would be awesome and
confirmation that my game logic is set up correctly.
Thank you!

**Comment by lisamsmith100** [comment]
I'm not stuck per se but not sure why my on('click', function) is not working.

**Comment by tvcrawley** [comment]
Can you paste the code that is related to this function?

**Comment by danman01** [comment]
For your game logic issue, please open a separate issue, and outline what you have so far. What's the user flow, what's the game flow, and point out at which step you are unsure. Many times simply writing out what's going on, step by step, will alert you if something is off in regards to logic.

**Comment by lisamsmith100** [comment]
Thank you . Will open separate issue for game logic.

in my html:
<td class=‘boardpiece’><div class=‘boardpiece’ id=‘3’>&nbsp;</div></td>

in game/events.js:
const addHandlers = () => {

  $('#createGame').on('click', onCreateGame),
  $('#boardpiece').on('click', onPlayerIs),
  $('#clearGame').on('click', onClearGame)
}

**Comment by payne-chris-r** [comment]
Reformat please! using ```js!

**Comment by lisamsmith100** [comment]
in my html:
```
        <td class=‘boardpiece’><div class=‘boardpiece’ id=‘0’>&nbsp;</div></td>
```
in game/events.js:
```
const addHandlers = () => {

$('#createGame').on('click', onCreateGame),
$('#boardpiece').on('click', onPlayerIs),
$('#clearGame').on('click', onClearGame)
}
```

**Comment by lisamsmith100** [comment]
I'm still working on game logic as well so maybe not open another issue.  will keep trying.

**Comment by lisamsmith100** [comment]
I'm not sure how to get it fired from my click to test it.

**Comment by tvcrawley** [comment]
`'boardpiece'` is a class of both `<td>` and `<div>`, how are classes accessed in jQuery?

**Comment by lisamsmith100** [comment]
I'll try the $('.boardpiece')on('click', onPlayerIs).  Thank you!

**Comment by lisamsmith100** [comment]
or I was thinking of trying $('#0).on('click', onPlayerIs) as well.  or $('#1).on('click'.onPlayerIs). Thanks.

**Comment by tvcrawley** [comment]
@lisamsmith100 **Please close** if your issue has been resolved.

**Comment by lisamsmith100** [comment]
Certainly will do when I can.  I'm still not getting it but will keep trying.

**Comment by lisamsmith100** [comment]
Hi Toni,
Should I close this issue if not resolved yet?  I think I need to shift my focus and come back to it?  I don't want to keep you hanging.
Thanks.

**Comment by tvcrawley** [comment]
Have you been able to get your `on()` click event to work?

**Comment by lisamsmith100** [comment]
Hi Toni, 
I'm trying a different button to try to troubleshoot.  Trying to do new game.
in html,
```
        <ul class="nav navbar-nav navbar-right">
                <li class="Games">
                    <a href="#" class="dropdown-games" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Games <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#" id="createGame">New Game</a></li>
                        <li><a href="#" id="clear-game">Clear Game</a></li>
                        <li><a href="#" id="total-games">Total Games</a></li>
                        <li><a href="#" id="number-wins">Number of Wins</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
```
Then in events.js, there's this code:

```js
'use strict'

const getFormFields = require(`../../../lib/get-form-fields`)

const api = require('./api')
const ui = require('./ui')

const onCreateGame = function (event) {
//  const data = getFormFields(this)
  event.preventDefault()
  console.log('i clicked new game')
  api.createGame(data)
    .then(ui.createGameSuccess)
    .catch(ui.createGameFailure)
}
//and at bottom:
const addHandlers = () => {

  $('#createGame').on('click', onCreateGame),
  $('.boardpiece').on('click', onPlayerIs),
  $('#clearGame').on('click', onClearGame)
}

module.exports = {
  addHandlers,
  onCreateGame,
  onPlayerIs,
  onClearGame
}

then, in api.js:
'use strict'

const config = require('../config')
const store = require('../store')
const logi = require('/logic')

const createGame = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    data
    // data: data is same as just plain data
  })
}
```

QUESTION:  do I need to remove data here?  my `create.sh` looks like this:

```
#!/bin/bash
#ID=26 TOKEN=BAhJIiVmYjNjMzM3MTcwMjc2ODIyNTMxZWFiMDQ3NDFlNmQ2OAY6BkVG--797ff868af4f1d602ec25c7cfb6124ad76d6e39f sh scripts/create.sh

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/games"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Authorization: Token token=$TOKEN" \
```
Thanks for your guidance.

**Comment by danman01** [comment]
Is the ☝️ code working? Does this pertain to the original problem of this issue?

is `console.log('i clicked new game')` outputting?

are you exporting in your api.js appropriately so you can require??

**Comment by lisamsmith100** [comment]
Thanks.  Still a click() issue.  No, not outputting.  Will continue sleuthing and trying.

**Comment by danman01** [comment]
```
const addHandlers = () => {

  $('#createGame').on('click', onCreateGame),
  $('.boardpiece').on('click', onPlayerIs),
  $('#clearGame').on('click', onClearGame)
}
```
is a function. Are you calling it anywhere? And, if so, are you ensuring `document.ready`?

**Comment by lisamsmith100** [comment]
I'm opening a new issue for that now.  Thanks.

I haven't been able to get the on('click'...) handler to work yet.

I'm trying to follow the event and object data but not finding where the issue is.

I don't see where the addHandlers function is being used.  Is it in a file given with browser template?

Thank you.

**Comment by lisamsmith100** [comment]
My newGame button/click is working but my game board is not.  I'm still working on that part.

**Comment by benjimelito** [comment]
Try looking in your `index.js` file. Sounds like you've been able to attach at least one click handler if the newGame button works, are you getting anything to log in the console when clicking on the game board?

**Comment by lisamsmith100** [comment]
The new game console.log is working but the game board clicking is not.  There seems to be an issue with 
```js
const createGameFailure = (error) => {
  console.error(error)
}
```
but I'm not sure why.

  It's being exported:
```js
module.exports = {
  createGameSuccess,
  createGameFailure,
  showGameSuccess,
  showGameFailure,
  updateGameSuccess,
  updateGameFailure,
  clearGameSuccess,
  clearGameFailure
}
```
I am continuing to try!

**Comment by benjimelito** [comment]
Let me come check it out

**Comment by jordanallain** [comment]
status @lisamsmith100 ?

**Comment by lisamsmith100** [comment]
stillno luck.  keep trying and troubleshooting.

**Comment by lisamsmith100** [comment]
```js
$('.boardpiece').on('click', onPlayerIs),

```
in my addHandlers function hasn't produced any activity upon clicking.  Still not finding what is wrong.  Do you have any suggestions?

**Comment by lisamsmith100** [comment]
I got the new game button to work but the boardpieces are still not working.  I'm continuing to work through.

**Comment by jordanallain** [comment]
What are you working on now?

**Comment by payne-chris-r** [comment]
If you've resolved this issue, please post your solution, and open a new issue if you have one! Thanks @lisamsmith100

**Comment by lisamsmith100** [comment]
I haven't resolved the button clicking but I'll close this and post another issue if/when I have one.
