### ISSUE TITLE
Assistance on next steps after creating a new game on server

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/game-project#541]
What I've completed is:

1. The whole sign in/out process.
2. The actual game play for win/loss/draw.
3. Created a game via AJAX that gave back a Completed 200.

What I'd like to tackle  next is storing the actual moves in that game object that was created.  After that I'd like to tackle showing the game stats results.

However, I'd like to request a 1-1 to review my project to date and discuss next steps.

**Comment by payne-chris-r** [comment]
This is a great issue, @conorjennings. Thanks for letting us know. I'll come find you in a bit.

**Comment by payne-chris-r** [comment]
Met with @conorjennings. He's in a good place. Conor, can you update this issue with where you're at and what your next steps are when you get a chance?

**Comment by glasneed** [comment]
My next steps are to work on hooking up my tic tac toe game board to the game that was successfully created on the rails server. I also need to ensure that the game board stores the successful onClick actions in an array. Once I have that set up I then need to ensure that every time I click on the game board that the action is then updated on the game array that I successfully created.

**Comment by BenGitsCode** [comment]
That seems like a great resolution to the OP. Please close this issue.
