### ISSUE TITLE
requirements question

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/game-project#543]
in regards to game score.  I only have it pop up to say who won the game.
I think we need to have an area to keep the current amount of games played etc.

Do we need to pull total amount from the server for player or the current session?
for example if Joe = player-x played 5 games will show all 5 games or will it need that if Joe logs in as player x it will need to pull Joe full count.  

Also would it be possible to have someone look at my game and give me feedback on it at its state 
before the weekend.

**Comment by danman01** [comment]
Requirements for score that I am seeing in `requirements.md`:
- Visually display which side won if a player gets three in a row or show a draw/"cat’s game" if neither wins.

- Use AJAX for interacting with a provided API. Specifically, your app must:

  - Visually display the results of retrieving game statistics, such as total games won by a user. (READ)

If you have any particular questions about your code, make sure to put those questions in an issue, as opposed to asking for a general review of the project. Go through the requirements and check off what is done and what is pending, and what you're stuck on / have questions about.

**Comment by Ryaong792** [comment]
thank you.
