### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by donpowers** [ga-wdi-boston/game-project#544]
After performing a grunt deploy I'm seeing the error below.  Not sure how to fix the issue. 
I do have a branch that I'm unsure if it has been merged. I still coming up to speed on git.  Suggestions?

Warning: Command failed: git push origin master
To github.com:donpowers/Tic-Tac-Toe-Client.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:donpowers/Tic-Tac-Toe-Client.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 Use --force to continue.

**Comment by donpowers** [comment]
I did review the error message and it is still not clear to me what I need to do next.  I did create several branches that I merged today.  If I tried to merge in the order in which I created them, but I may of gotten one out of order.  Could the changes from this branch been merged with one of the other pushed, pulled and merged changes?

**Comment by donpowers** [comment]
Perform a git pull on the master.  Seems to of done the trick.

**Comment by samguergen** [comment]
I suggest you create a new branch (git checkout -b branch-name) then add, commit and push to this branch name. This will save your work as backup.
Once you do this, try performing a git pull origin master, then a git push origin master to see if this fixes the issue.
If it doesn't, merge the remote branch-name with remote master on Github, or go to git checkout master, then git merge branch-name.
