### ISSUE TITLE
After deploying, getting errors in console trying to access API

### ISSUE THREAD

**Issue by jim-moody** [ga-wdi-boston/game-project#545]
This is the error I am getting in the console:

`
XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jim-moody.github.io' is therefore not allowed access.
`

Everything works fine locally.

**Comment by BenGitsCode** [comment]
Where did you get the URL  https://ga-wdi-boston.herokuapp.com/sign-up from?

**Comment by jim-moody** [comment]
That's just the way it was when I copied browser template
Here is an example of one of my api calls:

```js
const config = require('../config')

const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```

**Comment by BenGitsCode** [comment]
Two things:

Search through ` lm-01-forum` from yesterday (around 5:20) and I think you'll find some relevant information shared by a fellow developer. 

Also, please very carefully review the head of HTML and consider opening an additional issue if you find a problem there.

**Comment by jim-moody** [comment]
Ah I missed that - thanks Ben!   And for anyone else - it's actually in the `lm-01-projects` channel

For anyone else's reference, Nari pasted the correct code for config.js in Slack which I have included below.  The production URL in in the config file needed to be updated.

```diff
'use strict'

const config = {
  apiOrigins: {
-    production: 'https://ga-wdi-boston.herokuapp.com'
+   production: 'https://aqueous-atoll-85096.herokuapp.com/'
  }
}

module.exports = config
```

[edited 2017-04-07 by @bengitscode : diff syntax for clarity]
