### ISSUE TITLE
Need help with game logic

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/game-project#546]
I'm spinning my wheels on the game logic. 
I'm really really close, I feel like I have all the pieces, but just can't get them together. 
I have considered:
- using .some() to iterate through the squares played and compare it to the winning combination arrays. 
-storing X and O indexes in their respective arrays and trying to iterate through those
- finding the indexes on the game board that have X or O and comparing them. 
My code is below doesn't work and I fully understand why. What I am ultimately trying to do is say hey if the indexes 0, 1, and 2 on my game board equal X then X wins. 

```
const squaresPlayed = []
// log the square that was clicked
$('.gameBoard').on('click', '.boardPiece', function (event) {
  // registers the current click
  const currentClick = $(event.currentTarget)
  // gets the index of the square that was just clicked
  const indexOfSquare = $('.boardPiece').index(currentClick)
  // gets the X or O
  const stringInHTML = $(currentClick).html()
  // if logic that considers whether the current click was X or O and pushes
  // index of the square to the appropriate array
  if (stringInHTML === 'X') {
    squaresPlayed.push('X')
  } else {
    squaresPlayed.push('O')
  }
  console.log(squaresPlayed)
  console.log('X or O in the DOM?:', stringInHTML)
  console.log(winner())
})

const winner = function () {
  if (squaresPlayed[0] === 'X' && squaresPlayed[1] === 'X' && squaresPlayed[2] === 'X') {
    return 'X wins'
  } else if (squaresPlayed[3] === 'X' && squaresPlayed[4] === 'X' && squaresPlayed[5] === 'X') {
    return 'X wins'
  } else if (squaresPlayed[6] === 'X' && squaresPlayed[7] === 'X' && squaresPlayed[8] === 'X') {
    return 'X wins'
  } else {
  } return 'Try O'
}
```

**Comment by samguergen** [comment]
A missing piece: inside your const stringInHtml() function, try checking whether the player is a X or O player, then replacing the .html() inside the currentClick element with the X or O, then apply the rest of your logic.

**Comment by tvcrawley** [comment]
When you say "considered" does that mean you've tried these options already or are you running them by us to see what approach would be best?

**Comment by awoodrum87** [comment]
@tvlangley it means i tried them but was unable to make it work.

**Comment by awoodrum87** [comment]
@samguergen 
apologies for not including this earlier. In my events.js I have the the X and O player 
```
let playerSymbol = 'X'

const onClickBoard = function () {
  event.preventDefault()
  console.log('works')
  // ^ all 9 squares log 'works'
  if ($(this).text() === ' ') {
    $(this).text(playerSymbol)
    if (playerSymbol === 'X') {
      playerSymbol = 'O'
    } else {
      playerSymbol = 'X'
    }
  }
```

**Comment by samguergen** [comment]
What is your specific issue? "Game logic" is a bit too broad of an issue. We can only help you if we are able to pinpoint the problem somewhat. If you can't pinpoint at all, and generally are lost about how to go about doing things, then we can schedule a 1:1

**Comment by awoodrum87** [comment]
ah. I cannot get my game logic to return a winner. specifically, I cannot calculate (if that is the right word) when I have 3 in a row. 
I can click on my board and log an X or O. I just cannot connect the pieces in my code to determine when I've got three in a row.

**Comment by samguergen** [comment]
Is your squaresPlayed array able to records Xs and Os clicked, and store them at their appropriate location in the array? For example, if square 8 was clicked, then stores the X at array[7]?

**Comment by awoodrum87** [comment]
I AM A GOLDEN GOD. 
I figured it out. I use an ajax call to compare the values in the squares, NOT an array as the array just stores the  X or O in the order it was clicked. See below. 

```
const winner = function () {
  const boxZero = $('#box-0').html()
  const boxOne = $('#box-1').html()
  const boxTwo = $('#box-2').html()
  const boxThree = $('#box-3').html()
  const boxFour = $('#box-4').html()
  const boxFive = $('#box-5').html()
  const boxSix = $('#box-6').html()
  const boxSeven = $('#box-7').html()
  const boxEight = $('#box-8').html()

  if (boxZero !== '' && boxZero === boxOne && boxZero === boxTwo) {
    return 'winner'
  }
```

**Comment by awoodrum87** [comment]
I am closing this issue. Thank you!

**Comment by awoodrum87** [comment]
I guess I should have tested more than one winning condition. The following returns a winner on every single click. 
```
const winner = function () {
  const boxZero = $('#box-0').html()
  const boxOne = $('#box-1').html()
  const boxTwo = $('#box-2').html()
  const boxThree = $('#box-3').html()
  const boxFour = $('#box-4').html()
  const boxFive = $('#box-5').html()
  const boxSix = $('#box-6').html()
  const boxSeven = $('#box-7').html()
  const boxEight = $('#box-8').html()
// logic to determine horizontal winners
  if (boxZero !== '' && boxZero === boxOne && boxZero === boxTwo) {
    return 'winner'
  } else if (boxThree !== '' && boxThree === boxFour && boxThree === boxFive) {
    return 'winner'
  } else if (boxSix !== '' && boxSix === boxSeven && boxSix === boxEight) {
    return 'winner'
  } else {
    return 'no winner'
  }
}
```
ps. take your time. I am going to get lunch and go for a walk and clear my mind. I'll be back around 12:30

**Comment by awoodrum87** [comment]
Sam, I did not see your comment:
"Is your squaresPlayed array able to records Xs and Os clicked, and store them at their appropriate location in the array? For example, if square 8 was clicked, then stores the X at array[7]?"

The answer is yes.

**Comment by samguergen** [comment]
I suggest you try the most basic condition, and console.log wherever possible. Try first testing with only one winning condition (if boxes 0-2 are the same) - test  win/fail for that condition, and gradually add from there.

**Comment by awoodrum87** [comment]
So I have console logged at each point and individually I get the expected results. The below code and screen shot returns 'Row 2 Winner' when my expected result is 'try again'
```
const winner = function () {
  const boxZero = $('#box-0').html()
  const boxOne = $('#box-1').html()
  const boxTwo = $('#box-2').html()
  const boxThree = $('#box-3').html()
  const boxFour = $('#box-4').html()
  const boxFive = $('#box-5').html()
  // const boxSix = $('#box-6').html()
  // const boxSeven = $('#box-7').html()
  // const boxEight = $('#box-8').html()
// logic to determine horizontal winners
  if (boxZero !== '' && (boxZero === boxOne) && (boxZero === boxTwo)) {
    return 'row 1 is true'
  } else if (boxThree !== '' && (boxThree === boxFour) && (boxThree === boxFive)) {
    return 'row 2 is true'
  } else {
    'try again'
  }
}
```
<img width="328" alt="screen shot 2017-04-07 at 1 40 12 pm" src="https://cloud.githubusercontent.com/assets/25780850/24812444/19d4387e-1b98-11e7-9b85-15b49572114e.png">

HOWEVER, when row 2 is an actual winner I do actually get 'Row 2 winner'

<img width="316" alt="screen shot 2017-04-07 at 1 44 24 pm" src="https://cloud.githubusercontent.com/assets/25780850/24812510/5fe1dfba-1b98-11e7-9f8b-7cc540131b7a.png">

**Comment by awoodrum87** [comment]
follow up: I have written the logic for all 8 winning conditions. Here's what I get:
If I have a winner (3 in a row) the expected result prints in the log. I get the wrong message for all clicks up until a winner though. IE when I clock on square 4 (and only on square 4) I get 'row 2 is a winner'.

**Comment by BenGitsCode** [comment]
Have you used a debugger to walk through the code ?

**Comment by awoodrum87** [comment]
I'm working through it now. Will report back.

**Comment by awoodrum87** [comment]
I have used debugger but i don't really know how to interpret what happens. it just stops the code from running

**Comment by awoodrum87** [comment]
I changed direction a little as I started thinking about the back end stuff. I am getting an error that says determineWinner is not a function.
```
const determineWinner = function (playerSymbol, gameBoard) {
// lots of code
}
module.exports = {
  determineWinner
}
```
and here is where I call it and where the error occurs
```
let playerSymbol = 'X'

const onClickBoard = function () {
  event.preventDefault()
  console.log('works')
  // ^ all 9 squares log 'works'
  if ($(this).text() === ' ') {
    const id = $(this).attr('id')
    gameBoard[id] = playerSymbol
    $(this).text(playerSymbol)
    if (playerSymbol === 'X') {
      playerSymbol = 'O'
    } else {
      playerSymbol = 'X'
    }
    index.determineWinner(gameBoard, playerSymbol)
```

**Comment by awoodrum87** [comment]
I've moved the two chunks of code into one file because that is why I am getting the determineWinner is not a function error. but that logic does not work either. 

```
const determineWinner = function (gameBoard, playerSymbol) {
// logic to determine winners
  if (
     (gameBoard[0] === playerSymbol && gameBoard[1] === playerSymbol && gameBoard[2] === playerSymbol) ||
     (gameBoard[3] === playerSymbol && gameBoard[4] === playerSymbol && gameBoard[5] === playerSymbol) ||
     (gameBoard[6] === playerSymbol && gameBoard[7] === playerSymbol && gameBoard[8] === playerSymbol) ||
     (gameBoard[6] === playerSymbol && gameBoard[3] === playerSymbol && gameBoard[0] === playerSymbol) ||
     (gameBoard[7] === playerSymbol && gameBoard[4] === playerSymbol && gameBoard[1] === playerSymbol) ||
     (gameBoard[8] === playerSymbol && gameBoard[5] === playerSymbol && gameBoard[2] === playerSymbol) ||
     (gameBoard[6] === playerSymbol && gameBoard[4] === playerSymbol && gameBoard[2] === playerSymbol) ||
     (gameBoard[8] === playerSymbol && gameBoard[4] === playerSymbol && gameBoard[0] === playerSymbol)) {
    return 'we have a winner'
  }
}
const onClickBoard = function () {
  event.preventDefault()
  console.log('works')
  // ^ all 9 squares log 'works'
  if ($(this).text() === ' ') {
    const id = $(this).attr('id')
    gameBoard[id] = playerSymbol
    $(this).text(playerSymbol)
    if (playerSymbol === 'X') {
      playerSymbol = 'O'
    } else {
      playerSymbol = 'X'
    }
  }
  determineWinner(gameBoard, playerSymbol)
}
```

**Comment by awoodrum87** [comment]
Thanks for the help Ben. 
Note: the order in the onClickBoard Function was off. I needed to call the determineWinners function before the player symbol changes. 
The correct code is:

```
const onClickBoard = function () {
  event.preventDefault()
  if ($(this).text() === ' ') {
    const id = $(this).attr('id')
    gameBoard[id] = playerSymbol
    determineWinner(gameBoard, playerSymbol)
    $(this).text(playerSymbol)
    if (playerSymbol === 'X') {
      playerSymbol = 'O'
    } else {
      playerSymbol = 'X'
    }
  }
}
```
