### ISSUE TITLE
Trouble getting the images to load

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/game-project#548]
Right now my x/o/blank squares are all images.  It works when I serve the page to the local host but when I deploy the site to gitpages I get a 404 not found error.  

I double checked I have the images uploaded to the assets folder of my git repository , but I'm wondering if the problem is that I just can't use a "file path" to find an image once I've pushed the site to git hub pages.

**Comment by jordanallain** [comment]
You can use the file path, what does yours look like? 

Can you paste in the exact error you are getting?

**Comment by sjruby** [comment]
This is the error: sjruby.github.io/:142 GET https://sjruby.github.io/assets/images/blank-square.png 404 (Not Found)

The src it's looking for is: 
src="/assets/images/blank-square.png"

**Comment by tvcrawley** [comment]
What have you tried to fix the error? The identified problem has something to do with the `src`. Are there any examples in the wild similar to this?

**Comment by sjruby** [comment]
I've tried uploading to imgur to get it to a URL I've googled the error with no luck. Will keep messing around with the imgur link.

**Comment by tvcrawley** [comment]
What link are you using from imgur?

**Comment by sjruby** [comment]
Got it to work

**Comment by jordanallain** [comment]
@sjruby Explanation?

**Comment by sjruby** [comment]
I figured out how to link it to the imgur image and just use that, still not sure why the relative link didn't work but oh well!
