### ISSUE TITLE
Request guidance on using a dropdown with modals

### ISSUE THREAD

**Issue by cpm5041** [ga-wdi-boston/game-project#549]
I've created a dropdown navbar using bootstrap that I would like to use to link my credential functionality. I've reviewed the bootstrap documentation and could not figure out how to link my current credential functionality to be used inside the drop down as a modal. I would like some guidance as we didnt review in great detail.

```    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Sign Up</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Sign In</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Sign Out</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Change Password</a></li>
          </ul>
        </li>
      </ul>```

**Comment by danman01** [comment]
I would start here: Google --> use dropdown in modal bootstrap

**Comment by cpm5041** [comment]
Thanks

**Comment by benjimelito** [comment]
Make any progress on this?

**Comment by Jcornmanhomonoff** [comment]
@cpm5041 Did you solve this issue yet? If so, please comment on how you solved and close! If not, please comment with a follow-up question so we can help! 🙃

**Comment by cpm5041** [comment]
I put this on the back burner while I focused on main functionality but still have not made any progress. I could use some help getting pointed in the right direction. I would like to know how to link a modal to a div I created for the credential functionality. If anyone has time before EOD it would be greatly appreciated.

**Comment by cpm5041** [comment]
I am going to put this aside until I have requirements finished but Ben was able to give me a starting point.
