### ISSUE TITLE
CURL Patch not working

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/game-project#550]
I have created a game with a valid ID (in this case the ID is 9. But when I try to run this curl script below, it fails to run". I checked closed logs and couldn't find anything to help and am wasting too much time on CURL here.

```
curl --include --request PATCH "http://localhost:4741/games/9" \
  --header "Content-Type: application/json" \
  --data '{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}'```

The error I get back is: 
```
HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Cache-Control: no-cache
Content-Type: text/html; charset=utf-8
X-Request-Id: 92e09aa3-316d-401e-9991-d3ce2c64efa3
X-Runtime: 0.006758
Vary: Origin
Transfer-Encoding: chunked

```

**Comment by jordanallain** [comment]
You're unauthorized from PATCHing, go back to the jQuery PATCH lesson we did with books and see how your curl request from that one differs from your current one.

**Comment by glasneed** [comment]
Yes I did that before I posted as I wanted to get a copy of the solution code. But it is empty and I didn't have the code myself as I can rarely keep up with code alongs.

https://github.com/ga-wdi-boston/jquery-ajax-patch/tree/solution/scripts/books

**Comment by jordanallain** [comment]
Here is an example of a PATCH from the books lesson, ignoring the URL string do you see any differences with your curl?

```sh
curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request PATCH \
  --header "Authorization: Token token=${TOKEN}" \
  --header "Content-Type: application/json" \
  --data '{
    "example": {
      "text": "'"${TEXT}"'"
    }
  }'
```

**Comment by glasneed** [comment]
Yes that worked. If you could please attach that to the empty script in the solution branch above for patch, that would be helpful. 
Thank you

**Comment by jordanallain** [comment]
Please mention what you were missing!

**Comment by glasneed** [comment]
I didn't have the 
 --header "Authorization: Token token=${TOKEN}" \
 in my code as I had no example to work against and compare. This missing line fixed the curl.
