### ISSUE TITLE
Game Logic - Request Pointer

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/game-project#551]
Hi,
I have been trying to test the game logic in Node.
Here's what I have so far.

 const makeMove = function(isPlayer) { //function accepts isPlayer (X or O as arg
  if(isPlayer === "X") {  //if isPlayer passed is an X (goes first)
    boardpiece = "X"
    console.log(boardpiece) //this will be a text('boardpiece') to browser
    isPlayer = "O" //switch isPlayer to be "O"
//    $('#0').on('click', text(isPlayer)  wanting this to work
  } else {
    isPlayer = "O"
    boardpiece = "O"
    console.log(boardpiece)
    isPlayer("X")
  }
    return boardpiece
}

Would love any pointers to what I'm doing incorrectly and a hint to how to fix.
Thank you.

**Comment by benjimelito** [comment]
Hey Lisa. What is not working about your code that you want to work? Also, please format your code by surrounding it in backticks ``!

**Comment by lisamsmith100** [comment]
Thanks.  I thought I heard that the backticks for html only--I understand now.  Tony Leo just explained that they need the js or html.

I'm wanting it to return an X and O and it was only returning an X.  I'll keep trying.

```js

const makeMove = function(isPlayer) { //function accepts isPlayer (X or O as arg
  if(isPlayer === "X") {  //if isPlayer passed is an X (goes first)
    boardpiece = "X"
    console.log(boardpiece)
    isPlayer = "O"
//    $('#0').on('click', text(isPlayer)
  } else {
    isPlayer = "O"
    boardpiece = "O"
    console.log(boardpiece)
    isPlayer("X")
  }
    return boardpiece
}
```

**Comment by benjimelito** [comment]
Cool 👍 . So when you console.log `boardpiece`, does it look the way you expect it to? Also, I'm curious about what the `isPlayer` function does on the last line of your `else` block?

**Comment by lisamsmith100** [comment]
I re-wrote it and am getting the return value I expect.
