### ISSUE TITLE
Game history does not consistently update 

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/game-project#552]
I'm finding that my game history does not update consistently. 

Here's my UI: 
<img width="726" alt="screen shot 2017-04-07 at 12 20 26 pm" src="https://cloud.githubusercontent.com/assets/20606223/24809150/a32d6ed0-1b8c-11e7-9705-13ea5aa6d5ef.png">

In order to play a game, I first sign-up/sign-in a user. Then, I click "Start!" to begin a game. After playing a game, I click "Game Statistics!" to see the game history. 

Here's a screenshot of my game history after playing the first game: 
<img width="655" alt="screen shot 2017-04-07 at 12 14 54 pm" src="https://cloud.githubusercontent.com/assets/20606223/24809232/e252a04e-1b8c-11e7-8adb-0f26a9ce0d6e.png">

The array in my game history matches the game board. 

Here's a screenshot of my game history after playing the **second** game: 
<img width="651" alt="screen shot 2017-04-07 at 12 15 49 pm" src="https://cloud.githubusercontent.com/assets/20606223/24809275/ff6a5af0-1b8c-11e7-93a0-59f6b73a1681.png">

Everything is still fine. The game history array matches my board. 

Now, here's what happens after the **third** game: 
<img width="646" alt="screen shot 2017-04-07 at 12 17 02 pm" src="https://cloud.githubusercontent.com/assets/20606223/24809324/22570004-1b8d-11e7-9ab6-b9ccb3178125.png">

Now, the history does not match. Instead, the third object in the game history holds the results of my second game. I'm confused about why the history stops updating after the second game. 

I'm suspecting there is a problem with my GET request. Here is my code: 
```javascript
const onGetIndex = function (event) {
  event.preventDefault()
  // const data = getFormFields(event.target)
  gameApi.indexGame()
    .done(gameUi.successIndex)
    .fail(gameUi.fail)
}
```

```javascript
const indexGame = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

```javascript
const successIndex = (data) => {
  // console.log('successIndex worked!')
  store.game = data.game
  // console.log(store)
  console.log(data)
}
const failure = (error) => {
  console.error(error)
}
```
Any help would be much appreciated. Thank you!

**Comment by benjimelito** [comment]
Is it possible that you're sending more than one `POST` request when sending games to the database? I would maybe try using `curl` requests to verify that there aren't duplicate game objects in the database.

**Comment by naributler** [comment]
I believe I am only sending one `POST` request. That `POST` request is only sent when I hit the 'Start!' button. I checked the games object, but I did not see any duplicate game ids for that user. 

Now, I'm wondering if there is an issue with my `PATCH` request. Perhaps I need to push a new game into the games array in the `PATCH`? Here's my code: 

```javascript
const onSubmitMove = function (event) {
  event.preventDefault()
  console.log('onSubmitMove worked!')
  const data = getFormFields(this)
  console.log(this)
  console.log(event.target)
  gameApi.submitMove(data)
    .done(gameUi.successMove)
    .fail(gameUi.fail)
}

const submitMove = function (data) {
  console.log(data)
  console.log(store)
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const successMove = (data) => {
  console.log('successMove worked!')
  console.log(data)
  store.game = data.game
}
```

**Comment by benjimelito** [comment]
I don't necessarily think you need to do it inside the patch, but would you mind posting the code where you are pushing your game objects?

**Comment by naributler** [comment]
Sure, so that would be the `GET` request? Here's the code: 

```javascript
const onGetIndex = function (event) {
  event.preventDefault()
  // const data = getFormFields(event.target)
  gameApi.indexGame()
    .done(gameUi.successIndex)
    .fail(gameUi.fail)
}
const indexGame = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
const successIndex = (data) => {
  // console.log('successIndex worked!')
  store.game = data.game
  // console.log(store)
  console.log(data)
}
const failure = (error) => {
  console.error(error)
}
```

If it's helpful, here are all of my AJAX requests for the game objects: 

```javascript
'use strict'

const gameApi = require('./game-api')
const gameUi = require('./game-ui')
const getFormFields = require('../../../lib/get-form-fields.js')

const onNewGame = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  gameApi.newGame(data)
    .done(gameUi.successNewGame)
    .fail(gameUi.fail)
}

const onSubmitMove = function (event) {
  event.preventDefault()
  console.log('onSubmitMove worked!')
  const data = getFormFields(this)
  console.log(this)
  console.log(event.target)
  gameApi.submitMove(data)
    .done(gameUi.successMove)
    .fail(gameUi.fail)
}

const onGetIndex = function (event) {
  event.preventDefault()
  // const data = getFormFields(event.target)
  gameApi.indexGame()
    .done(gameUi.successIndex)
    .fail(gameUi.fail)
}

const gameEventHandlers = () => {
  $('.new-game').on('submit', onNewGame)
  $('#game-info').on('submit', onSubmitMove)
  $('#game-statistics').on('submit', onGetIndex)
}

module.exports = {
  gameEventHandlers
}
```

```javascript
'use strict'

const config = require('../config')
const store = require('../store')

const newGame = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

const submitMove = function (data) {
  console.log(data)
  console.log(store)
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const indexGame = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

module.exports = {
  newGame,
  submitMove,
  indexGame
}
```

```javascript
'use strict'
const store = require('../store.js')

const successIndex = (data) => {
  console.log('successIndex worked!')
  store.game = data.game
  // console.log(store)
  console.log(data)
}

const successNewGame = (data) => {
  console.log('successNewGame worked!')
  store.game = data.game
  console.log(store)
}

const successMove = (data) => {
  console.log('successMove worked!')
  console.log(data)
  store.game = data.game
}

const failure = (error) => {
  console.error(error)
}

module.exports = {
  failure,
  successIndex,
  successNewGame,
  successMove
}
```

**Comment by benjimelito** [comment]
Ah okay I see, so you're setting the game object in `store` to the current game that you're in. Is there a reason why you are doing this after each successful move?

**Comment by naributler** [comment]
Ah, you're right! store.game = data.game was not necessary. In addition, I did not have a feature to prevent the user from clicking (and sending a patch request) a cell after someone won the game. Once I added that feature and removed store.game = data.game, the game history was accurate.  (also, thank you @laurpaik for helping me debug this!!!)
