### ISSUE TITLE
updating the game over to true is not working when the game has a winner or cat finish

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/game-project#553]
here is what I am seeing in the console log files

```log file
here is my current move data from within updateMove:  Object {game: Object}game: Objectcell: Objectindex: 2value: "X"__proto__: Objectover: true__proto__: Object__proto__: Object
2017-04-07 13:20:50.092 jquery.js:9566 XHR finished loading: PATCH "http://localhost:4741/games/58".
send @ jquery.js:9566
ajax @ jquery.js:9173
updateMove @ api.js:34
onUpdateGame @ events.js:47
buildCurrentMove @ gameplay.js:683
onBox3 @ gameplay.js:191
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
2017-04-07 13:20:50.092 ui.js:65 here is the game after an update move was issued 
```

The updateMove object has the last move and over is true, but after the update, the over is still false from the server

```JS
const updateMove = function (inData) {
  console.log('here is my current move inData from within updateMove: ', inData)

  const data = {
    'game': {
      'cell': {
        'index': inData.game.cell.index,
        'value': inData.game.cell.value
      },
      'over': inData.game.over
    }
  }
  console.log('here is my current move data from within updateMove: ', data)

  return $.ajax({
    url: app.host + '/games/' + game.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + player1.user.token
    },
    data
  })
}
```

**Comment by jordanallain** [comment]
have you logged all the data you are using there to make sure it is what you think it is?

what are you passing to `updateMove` as an argument when it is invoked?

what is `game` in the line `game.game.id`?

what is `player1`?

**Comment by octater** [comment]
Here is the updateMove
```js
  console.log('made it to update game, data is: ', currentMove)

  api.updateMove(currentMove)
  .done(ui.updateMoveSuccess)
  .fail(ui.updateMoveFailure)
```
the console log shows the following:
Object {game: Object}game: Objectcell: Objectindex: 2value: "X"__proto__: Objectover: true__proto__: Object__proto__: Object
2017-04-07 13:55:09.297 

this look correct

**Comment by jordanallain** [comment]
the way you pasted it in makes it very hard to tell what is the object and what its properties are.

is `over: true` a property on the game object? or the cell object?

**Comment by octater** [comment]
game and player1 are just holding the values for each.  the moves are getting updated, just not the "over" value
```
game is:
Object {playerup: 2, clicks: 5, gameOver: 1, isReady: "Y", game: Object}
clicks:5
game:Object
  cells:Array(9)
  id:60
  over:false
  player_o:null
  player_x:Object
    email:"fred@gmail.com"
    id:4
    __proto__:Object
    __proto__:Object
  gameOver:1
  isReady:"Y"
  playerup:2
  __proto__:Object
```

**Comment by octater** [comment]
it goes
game: Object
  cell: Object
  over: true

looks to be property of the game object

**Comment by jordanallain** [comment]
@octater any status updates terry?

**Comment by payne-chris-r** [comment]
@octater I've just updated your comment from 8 hours ago. Did I get the formatting right? Next time if you can format that so it's a little easier to read it will be helpful!

**Comment by octater** [comment]
this was working all along, just my console logging was bad.  Sorry everyone for the issue
