### ISSUE TITLE
Alert Loop

### ISSUE THREAD

**Issue by brianedmunds** [ga-wdi-boston/game-project#555]
For now, my code has an alert displaying whenever the game ends in a draw.  However, when I close the alert, it reopens.  This happens 8 times and the finally stops.  Any thoughts on why that could be the case? 

```
    $.each(winningCombinations, function (index, combination) {
      // This variable is declared, and is used in determining whether or not
      // the user has all of the squares necessary to satisfy a winning combination
      let hasAllSquares = true
      $.each(combination, function (index, square) {
        // console.log(square)
          // -1 is returned if a match is not found
        if ($.inArray(square, currentPlayerSquares) === -1) {
          // In which case, hasAllSwquares is set to false
          hasAllSquares = false
        }
      })
      if ((hasAllSquares === false) && (chosenSquares[currentPlayerToken].length === 5)) {
        alert('Draw Game')
      }
      // If the current player has all of the squares for a winning combination
      // then this alert is displayed.  (Alert is just a placeholder for now
     // and will be replaced later)
        // Display the winner
      if (hasAllSquares) {
        alert(currentPlayerToken + ' wins!')
      }
    })
    // This changes the player token to the other player
    if (currentPlayerToken === 'x') {
      currentPlayerToken = 'o'
    } else {
      currentPlayerToken = 'x'
    }
  }
})
```
Some solutions that I found online to make sure that the alert only displays once involve using session storage, or setting a cookie and then checking that cookie, but those solutions sound overly complex.  I suspect that there is a simper solution, but not sure what it is.  Any thoughts?

**Comment by jordanallain** [comment]
looks like you are calling a method called `each` multiple times, do you know what that method does?

**Comment by brianedmunds** [comment]
I'm using that to iterate over each of the squares inside of each combination to see if there is a match to the winning combinations.  Now that you mention that, the total number of winning combinations is 8, and the alert displays 8 times.  Is my code as written causing the alert to display during each iteration?

**Comment by jordanallain** [comment]
that is what i was thinking.

**Comment by brianedmunds** [comment]
Looks like that's what it is.  Not sure how to solve it, though.  Whenever I take that logic out of the function, my game blows up on me.  Any suggestions?

**Comment by jordanallain** [comment]
There's a lot going on in that function, its pretty tough to juggle whats happening. I would suggest trying to make the function simpler and only check for one possible win scenario. If you have one function that can do that, you can have another function to check a different winning scenario. If they all work, you can make another function that simply calls those functions to see if any return a winner.

**Comment by brianedmunds** [comment]
I've tried to break the function out into separate, smaller functions.  However, I haven't been able to do that successfully, and I've been spinning my wheels on it.  Could you or one of the other instructors help me to break out one of the functions to get me started, and then I could use that as a guide for the functions?

**Comment by jordanallain** [comment]
hey brian wanna come sit in the back row with me?

**Comment by payne-chris-r** [comment]
@brianedmunds any update?

**Comment by Ryaong792** [comment]
```
((hasAllSquares === false) && (chosenSquares[currentPlayerToken].length === 5)) {
        alert('Draw Game)
return false
```

**Comment by brianedmunds** [comment]
This is all set.  Closing this out.
