### ISSUE TITLE
Can't see site after deploying

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/game-project#556]
Chris helped me grunt deploy a couple of hours ago - which as far as I can tell - was successful.

```sh
To github.com:jonifallon/tic-tic-toe.git
 * [new branch]      gh-pages -> gh-pages
Removing .DS_Store
Removing .editorconfig
Removing .eslintrc.json
Removing .gitignore
Removing .jscsrc
Removing .jshintignore
Removing .jshintrc
Removing .remarkrc
Removing .scss-lint.yml
Removing CONTRIBUTING.md
Removing Gruntfile.js
Removing LICENSE
Removing README.md
Removing STYLE.md
Removing assets/
Removing forms.md
Removing grunt/
Removing index.js
Removing indexBackup.html
```
I'm checking http://jonifallon.github.io/tic-tac-toe/ but it gives me a 404 error.  Let me know what else you need from me.

**Comment by jordanallain** [comment]
Joni please run `git status` from your local master branch and show us the message.

**Comment by jonifallon** [comment]
```sh
$ git  status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   assets/scripts/auth/api.js
	modified:   assets/scripts/auth/events.js
	modified:   assets/scripts/auth/ui.js
	modified:   assets/scripts/game.js
	modified:   assets/styles/styles.scss
	modified:   index.html

no changes added to commit (use "git add" and/or "git commit -a")
~/wdi/tictactoe/tic-tac-toe (master)
$ 
```

**Comment by BenGitsCode** [comment]
Are you still having this issue on your deployed site?

**Comment by jonifallon** [comment]
Yes.  http://jonifallon.github.io/tic-tac-toe/ is giving me a 404 error.

**Comment by jonifallon** [comment]
Ben helped me resolved.

**Comment by BenGitsCode** [comment]
Joni just :
- added and committed her current modified files on her feature branch.
- Merged it to master and resolved some small conflicts
- ran grunt deploy and it worked. 

We didn't fully diagnose the original cause yet, but progress is progress and as far as the OP issue title, this has been resolved. We can at least see a website now.
