### ISSUE TITLE
Need Halp w/ Game Logic

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/game-project#558]
Hello -- I've been thrashing for quite a while now and feel stuck with creating the game logic. 

So far, I've been able to put together a decent board that accepts X's and O's and alternates between players. My challenge right now is coming up with the ability to determine a winner. I've started by creating a list of winning combinations but I am not sure how to create a function to match them to the game board. I've tried looking through boggle challenges and past notes to see if I can push through this hurdle but realize that I'm running out of time and thrashing for way too long so I'm looking for some guidance on how to complete this piece.

I've created a new folder within my assets/scripts/ folder containing the following code below for my game logic so far:

```js
'use strict'

const player1 = 'X'
const player2 = 'O'
let currentPlayer = 'O'

// This alternates player turns.
const currentTurn = function () {
  console.log("It's " + currentPlayer + "'s turn now.")
  currentPlayer = currentPlayer === player1 ? player2 : player1
  return currentPlayer
}

// Prevents overwriting.
const start = function () {
  $(this).html(currentTurn)
  $(this).unbind()
}

// Creates the cell IDs.
const gameCellIds = [
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8'
]

// This creates the game object for logging the user
const gameObject = {
  'game': {
    'id': 1,
    'cells': ['null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'],
    'over': false,
    'player_x': {
      'id': 1,
      'email': 'and@and.com'
    },
    'player_o': null
  }
}

// This adds an event listener every time a box is clicked, run the updateCell function.
const setUpGameBoard = function () {
  console.log('setUpGameBoard ran!')
  for (let i = 0; i < gameCellIds.length; i++) {
    const elementId = gameCellIds[i]
    const element = document.getElementById(elementId)
    element.addEventListener('click', updateCell)
  }
}

// This logs an id into the gameObject array.
const updateCell = function () {
  console.log(currentPlayer)
  const id = this.id
  console.log('ID of clicked box = ' + id)
  const index = id.split('-')
  // const index = index1[1]
  gameObject.game.cells[index] = currentPlayer
  console.log('gameObject', gameObject)
}

const clickHandler = () =>
  $('.box').on('click', start)

// Function for button to reset the game board.
const clearBoard = function () {
  console.log('Clearboard ran!')
}

const resetHandler = () =>
  $('#reset-board').on('click', clearBoard)

  // This lists out all the possible winning combinations.
  const winCombos = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 5],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6]
  ]

module.exports = {
  clickHandler,
  setUpGameBoard,
  updateCell,
  clearBoard,
  resetHandler
}
```

**Comment by jordanallain** [comment]
to check for the winning combination you're going to need to iterate through all those arrays. maybe try to break this down into a smaller problem. see if you can just check one row and determine if theres a win in that row. once you've done that it should be easier to apply similar logic to the other areas of the board.

**Comment by andyjzhong** [comment]
Thanks Jordan -- I will try checking for a win one row at a time and let you know as soon as I have something worth reviewing.

**Comment by andyjzhong** [comment]
Aight cool -- it def helped to break it down step by step. Below is my logic

My thinking is that I wanted a function that checked for 1 winner and worked backwards from there. 
1. The game can only be won by 2 parties, either Player X or Player O. If neither, it's a Draw.
2. What does it mean to "win" a game? To have any of the following scenarios: A) Matching Row, B) Matching Column, or C) Matching Diagonal.
3. How do each of these scenarios get fulfilled? If I only focus on X winning the top row, I'd want to check if the cell values in box0, box1, and box2 are all X's. I'll need to grab the data from the gameObject somehow, but I'm not quite there yet.

Can you please tell me if I'm on the right track and whether you can help provide some assistance on helping me obtain the values I've stored in my gameObject above? Thank YOU!!

Below is the code I wrote for this logic so far:

```js
// This lists out all the possible winning combinations.
const winCombos = [
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],
  [0, 3, 6],
  [1, 4, 5],
  [2, 5, 8],
  [0, 4, 8],
  [2, 4, 6]
]

const threeInARow = function () {

}

// To see if X has won any of the rows.
const xWinsRow = function () {
  return allThreeX(cellValue(‘a’), cellValue(‘b’), cellValue(‘c’))
}

// Requirements for X to win.
const xWins = function () {
  return xWinsRow() || xWinsColumns() || xWinsDiagonal()
}

// Requirements for O to win.
const oWins = function () {}

// Function to check if either X or O is a winner.
const checkWinner = function () {
  console.log('checkWinner ran!')
  if (xWins()) {
    return 'X'
  }
  if (oWins()) {
    return 'O'
  }
  return null
}
```

**Comment by andyjzhong** [comment]
Thanks so much for your help, Jordan! I was able to get some direction for building out a way to determine a winner on my game board. I plan to apply the logic for the code we came up with together for winning a single row to the other winning scenarios and will open up a new issue when necessary.

```js
const gameBoard = new Array(9)

// To see if X has won any of the rows.
const xWinsRow = function () {
// This checks each of the rows to see if 3 cells in a row are filled with X's.
  if ((gameBoard[0] === 'X' && gameBoard[1] === 'X' && gameBoard[2] === 'X') ||
  (gameBoard[3] === 'X' && gameBoard[4] === 'X' && gameBoard[5] === 'X') ||
  (gameBoard[6] === 'X' && gameBoard[7] === 'X' && gameBoard[8] === 'X')) {
    console.log('True')
  }
}
```

**Comment by payne-chris-r** [comment]
Realizing you're thrashing is the hardest part. Admitting you've been thrashing is a great way to diagnose why, how, and what led you there. My most used thought process to try and 'de-thrash' myself is "What is the smallest most immediate problem at hand?" Go fix that. It seems like you're in a better spot now though. Thanks for opening this issue. Let us know if you get stuck on the next piece!

**Comment by jordanallain** [comment]
@andyjzhong any updates on your progress Andy?

**Comment by andyjzhong** [comment]
Thanks for checking in, Jordan! I managed to get my game logic to work and I'm now able to determine whether X or O wins. I spent some time yesterday adding a Draw feature and also worked on how to display to the viewer what the outcome is. I'm now stuck on a couple different things:

1. Adding the ability to reset the board, essentially clearing out the board so that the user can play again.
2. Perhaps the bigger issue at hand is making sure my forms for signing up, etc. are set up in the API.
3. I still don't have the ability to log games, but I feel like this will come once my API is set up.

Still feels like there's a lot to be done, but since tomorrow is the presentation, I wanted to make sure that I at least had something to deliver and we can work through each of the missing pieces of the requirements after Monday.

Taking it one step at a time, I would like to aim to at least get the reset/clear board function working by tomorrow though. I'll add in my code in a post right after this one.

**Comment by jordanallain** [comment]
Awesome thanks for the feedback Andy. Why don't you close this issue and open a new issue with just one problem that you are trying to tackle.

**Comment by andyjzhong** [comment]
Below is the code for a button that I'm looking to build a reset board functionality for.

``` html
        <form id="clearBoard">
          <input type="submit" name="submit" value="Clear Board!">
        </form>
```

```js
// Function for button to reset the game board.
const clearBoard = function () {
  console.log('clearBoard ran!')
}
```

```js
const clearBoard = function (event) {
  console.log('Clear Board ran!')
  event.preventDefault()
  game.clearBoard()
}
```

It looks like the button itself is working. When I click on the button, it logs 'clearBoard ran!' in the console. I think I just need some direction on how to clear the array so that I can play again.

As I think about my current problem at hand, I'm essentially trying to remove any logged X's or O's in my gameBoard array I've previously created. I've tried various things like setting the gameBoard to an empty array (i.e. gameBoard = []) and doing a replace-text-with ' ' (while this one clears the board, it does NOT allow the user to play again). 

Below is my JS for the array and how I'm creating my game board and allowing for X's and O's to be placed. Any guidance would be greatly appreciated.

```js
// This adds an event listener every time a box is clicked, run the updateCell function.
const setUpGameBoard = function () {
  for (let i = 0; i < gameCellIds.length; i++) {
    const elementId = gameCellIds[i]
    const element = document.getElementById(elementId)
    element.addEventListener('click', updateCell)
  }
}

// This logs an X or O into the gameBoard array.
const updateCell = function () {
  console.log(gameBoard)
  const id = this.id
  // const index = index1[1]
  gameBoard[id] = currentPlayer
  checkWinner()
  checkDraw()
  turnCounter()
  if (xWins() === true || oWins() === true) {
    return
  }
}
```

**Comment by andyjzhong** [comment]
Oops -- Did not see your comment from 4 minutes ago -- let me know if you'd like me to repaste this into a new one.

**Comment by Ryaong792** [comment]
Andy hit me up in slack I think I might be able to help.

**Comment by jordanallain** [comment]
yes please close this issue, open a new one if you still need help with the most recent problem. thanks!

**Comment by andyjzhong** [comment]
Thanks, Jordan. We couldn't figure it out so I'll close this issue here and log a new one.
