### ISSUE TITLE
Require statement not recognizing script

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/game-project#559]
My code cannot locate this script.

When I run the same approach in Terminal, it correctly locates it.

```
Last login: Thu Apr  6 09:10:19 on ttys002
~/wdi/projects/tic-tac-toe-client/assets/scripts/game-logic$ ls -ltr ../game-ajax/gameEvents.js 
-rw-r--r--  1 conor  staff  3494 Apr  7 15:31 ../game-ajax/gameEvents.js
~/wdi/projects/tic-tac-toe-client/assets/scripts/game-logic$ 

```

The error is "Parsing Error - Unexpected Token"
<img width="200" alt="screen shot 2017-04-07 at 3 44 53 pm" src="https://cloud.githubusercontent.com/assets/26227953/24817124/43965c30-1ba9-11e7-86bc-0fa7e10ce394.png">

**Comment by glasneed** [comment]
const game-events = require('../game-ajax/gameEvents')


is what I used

**Comment by glasneed** [comment]
Another hour wasted! I just changed to camelCase and it resolved the issue. Total stab in the dark and it worked.

const gameEvents = require('../game-ajax/gameEvents')

**Comment by glasneed** [comment]
Re opening as it errors when i load the page. 

"reference error: require not defined" is what shows up in chrome console

**Comment by jordanallain** [comment]
can you post the `gameEvents.js` file and the file that is requiring it?

**Comment by glasneed** [comment]
I don't follow? I didn't do anything to gameEvents.js. I am just trying to call a function in gameEvents.js from within  game-logic.js

That is why I used that require statement at the top of game-logic.js  to try to point to gameEvents.js. 

What am I missing ?

**Comment by glasneed** [comment]
Not sure what is going on. In searching Google, it says I can't use a require statement? Yet I've successfully used require statements in other sections of my code.

Node.JS is a server-side technology, not a browser technology. Thus, Node-specific calls, like require(), do not work in the browser.
http://stackoverflow.com/questions/31931614/require-is-not-defined-node-js

**Comment by jscohen** [comment]
So I'm not sure if this is the same thing, but require statements in my UI code did not get recognized unless they were in the function being called.  I think it's a scope issue.  This made me crazy too!

**Comment by payne-chris-r** [comment]
@conorjennings I think this has been resolved. Can you post the resolution?

**Comment by glasneed** [comment]
Jon - Appreciate your feedback yesterday. 

In the end, the rule was that I had broken a MAJOR rule by adding in a script tag in my index.html file and missed the RTFP two lines above that said "Do not add `script` tags unless you know what you are doing"
Clearly I didn't know what I was doing.
