### ISSUE TITLE
Error connecting to server

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#56]
getting error with console testing. Having issues with server

**Comment by RealWeeks** [comment]
Please be more descriptive. What's the error, how do you know it's a server issue?

**Comment by Jcornmanhomonoff** [comment]
<img width="502" alt="screen shot 2016-04-04 at 4 50 57 pm" src="https://cloud.githubusercontent.com/assets/17557070/14262833/810db504-fa85-11e5-8fc1-150ef00dbc07.png">

**Comment by RealWeeks** [comment]
look at what server you're trying to connect to

**Comment by Jcornmanhomonoff** [comment]
I have tried 2 different things already

**Comment by RDegnen** [comment]
what did you try?

**Comment by gaand** [comment]
`localhost` refers to your machine.  Is the game API running on your machine?

**Comment by RealWeeks** [comment]
@Jcornmanhomonoff was this issue resolved?

**Comment by Jcornmanhomonoff** [comment]
i have tried running grunt serve on ~/wdi/training/api-token-auth (training) and ~/wdi/training/api-token-auth/lib (training). I suppose I'm uncertain as to where I'm supposed to be running grunt serve and rails server.

**Comment by laurenfazah** [comment]
@Jcornmanhomonoff - @gaand is questioning towards the game API that is specifically set up for this project. Remember, the game API url was sent out in the projects Slack channel.

**Comment by gaand** [comment]
You have two parts, client (what you're building based on the js-template repository) and API (what the client interacts with using AJAX).  While you're developing the game, you run the client on your machine using `grunt serve` in the repository you created to hold the code.  You don't run `rails server` on your machine at all.  You point your client AJAX requests at the API hosted at http://tic-tac-toe.wdibos.com

**Comment by RealWeeks** [comment]
Attempting to test out previous project and confusion about connecting to hosted server and local server.  Explained the difference and advised Jessica follow the tic-tac-toe api documentation and use the link @gaand  posted above and in the project channel.

**Comment by Jcornmanhomonoff** [comment]
Changed link to proper API in code and ran grunt serve and rails server in proper repos.
