### ISSUE TITLE
Update Board

### ISSUE THREAD

**Issue by gastevend** [ga-wdi-boston/game-project#560]
I have:
       1. created the board 
       2. created the winning logic
       3. created all the logic to sign in 
       4. created the logic to start a new game and post it to the server

What is happening now is that I am kind of at a blocking point for myself... I cant really wrap my head around how i need to find the index of what spot was clicked and format it so that i can send that to the back and update the board. 
          I have tried to create the API call but im having trouble finding the index to pass into. I dont have my HTML set up as a table so im hoping i dont have to redo this. I think im just kind of helpless at this point. 

Is there anyway i could sit down with someone just to make sure im not going crazy?

**Comment by benjimelito** [comment]
I would think about ways you can give each square some unique identifier in the HTML. How are you determining winning logic at the moment?

**Comment by gastevend** [comment]
I have an id on every div in the html so 

```html
<div class='game-board'>
        <div id='0'>
        </div>
        <div id='1'>
        </div>
        <div id='2'>
        </div>
        <div id='3' class='beg-row'>
        </div>
        <div id='4'>
        </div>
        <div id='5'>
        </div>
        <div id='6' class='beg-row'>
        </div>
        <div id='7'>
        </div>
        <div id='8'>
        </div>
      </div>
```
the way that I determine winnig logic is by just seeing if any of the winning paths have 'XXX' or 'OOO'

```js
if (($('#0').html() + $('#1').html() + $('#2').html() === playerX) || ($('#0').html() + $('#1').html() + $('#2').html() === playerO)) {
      if (turn === 'O') {
        turn = 'X'
      } else {
        turn = 'O'
      }
      console.log(turn + ' wins')
      $('div').off('click')
      gameOn = false
```

**Comment by gastevend** [comment]
I just had a chat with Ben my issue was that i wasnt passing in any parameters to my api function. I needed to figure out how to grab the id from my html for what ever was clicked on as well as what the value was and then be able to pass those in as parameters into my api patch call function
