### ISSUE TITLE
Requirements clarification: console.logs

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/game-project#565]
I have removed all of my console.log() functions from my code that I used when testing and debugging my code. I do, however, have some intentional console.log() functions. These are not at all important to the functionality of my code, It was just a habit from practicing these in class. Should the following be removed to be in compliance with the requirements?

```
const signInSuccess = (data) => {
  console.log('Sign in Success. Data is: ', data)
  store.user = data.user
}

const signInFailure = (error) => {
  console.log('Sign in error. Error is: ', error)
```

**Comment by jordanallain** [comment]
Get em out! You can hit `command+shift+f`  in atom if you have your whole project open and it will search every file instead of just the current file.

**Comment by payne-chris-r** [comment]
I often say it depends @awoodrum87. Are you done building out that feature? The chances are, yes. And if you're done with the feature you should be ok with removing them. If you have plans to go back and improve on it, and you think they would be helpful, it's ok to leave them. It is certainly best practice to remove all of them prior to pushing your code to production though!

**Comment by awoodrum87** [comment]
OK great, thank you. I will remove them when I'm sure I won't be modifying that feature anymore.
