### ISSUE TITLE
Error calling a function inside a different JS file

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/game-project#567]
Hi -
I get the following error that is preventing me from continuing work today as I can't get a function call to be invoked. Chrome gives this error:

**gameEvents.js:14 Uncaught TypeError: gameLogic.gameStart is not a function**

My gameEvents.js file begins as follows:

``` 
const getFormFields = require(`../../../lib/get-form-fields`)
const gameApi = require('./gameApi')
const gameUi = require('./gameUi')
const gameLogic = require('./gameLogic')

const onCreateGame = function (event) {
  console.log('>>>>>>>>>>>>>>>>>> onCreateGame where event is ', event)
  event.preventDefault()
  gameApi.createNewGame()
    .then(gameUi.onCreateGameSuccess)
    .catch(gameUi.onCreateGameError)
  gameLogic.gameStart()
} 
```

As you can see I have the necessary require statements in place to call gameLogic.gameStart()

And in gameLogic.js, there is that one main function in there called gameStart() as follows (with the body of it removed as it this issue just has to do with actually invoking it rather than the logic inside it).

```
 'use strict'
const getFormFields = require(`../../../lib/get-form-fields`)

const gameStart = function () {
  // Global Variables:
  let playerTurn = 0
  let numberOfClicks = 0
.
.
.
  playGame()
}

module.exports = gameStart 
```

Any help or insight appreciated as I'm baffled why it is not been recognised.

**Comment by payne-chris-r** [comment]
I think this has to do with the circular dependency we talked about. You can't require `gameEvents` from `gameLogic` and `gameLogic` from `gameEvents`. You need to try to refactor this so that it uses the tree diagram we talked about.

**Comment by glasneed** [comment]
Thanks Chris. I will close this annoying issue, aren't they all!. I just resolved it an hour ago by sticking all the game code in gameEvents.js and got rid of gameLogic.js. This way I didn't get bogged down (and Irish expression!) with circular dependency issues. Code is working now and I'm moving ahead..like a snail.
