### ISSUE TITLE
Differences between deployed and local environment

### ISSUE THREAD

**Issue by jkjellan** [ga-wdi-boston/game-project#568]
Deployed Game:  https://jkjellan.github.io/tic-tac-toe-client/

I've had no issues on my local rails environment, but I'm running into weird issues in the deployed environment.  There appears to be a disconnect where once in awhile my PATCH requests to update the game are not registering on the web server.  The image at the link below is a good example.  The game I circled shows on the server as unfinished, but the actual game was completed. I think the issue might be that my game logic operates on a mirror local array, not the array handed back by the AJAX response, so my guess is that the web server is not always registering my PATCH requests. And I say that because, again, this appears to only be a problem in the deployed environment.

A potential fix is to have my game logic operate on the array handed back to me by the webserver via ajax, and that way if the PATCH request isn't registering I would know it, but that's a pretty large change for this late in the game.  I talked to a couple different consultants during the week who said it wasn't a requirement for my game logic to operate on the AJAX response, but I'm worried that this will be considered a bug.  Want to get your thoughts.  Thanks.

<img width="785" alt="screen shot 2017-04-08 at 10 11 27 pm" src="https://cloud.githubusercontent.com/assets/15950933/24834085/49baa2e6-1ca9-11e7-8fe8-afeb9e389bff.png">

Jim

**Comment by jkjellan** [comment]
I'm having difficulty replicating the issue now.  16 games in a row now that are all registering properly on the web server.  Not sure what to think, or even if this is a problem.  Thoughts? Is it possible that my issue was caused by trying to play the game before it was fully deployed?

**Comment by jkjellan** [comment]
I just want to make sure this won't be considered a bug

**Comment by payne-chris-r** [comment]
The order of operations should be click, see if valid move, if valid move make the request, if request is successful, continue. Your local game and the one stored on the server should always be identical. If they're not, you need to figure out why there are inconsistencies being created.

**Comment by payne-chris-r** [comment]
So no. You're not required to use the object that's handed back from the server, but why wouldn't you? Doing otherwise and having "two sources of truth" is a good way to over complicate things.

**Comment by jkjellan** [comment]
I definitely agree that using the handed back object is best practice, and if I were to build this again, I would definitely do that.  I'll see how easy it is to make that change now, but everything appears to be working, so might not have to.  I'm confused as to why I had an issue when testing just after deployment, but all my subsequent testing has worked.
