### ISSUE TITLE
Reset Button -- Clearing out an Array?

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/game-project#569]
Below is the code for a button that I'm looking to build a reset board functionality for.

```html
<form id="clearBoard">
  <input type="submit" name="submit" value="Clear Board!">
</form>
```

```js
// Function for button to reset the game board.
const clearBoard = function () {
  console.log('clearBoard ran!')
  // Need a function to go and clear out an array
  // This currently just replaces all the text in the box. Does not allow user to re-click.
  $('.box').text('')
}
```

It looks like the button itself is working. When I click on the button, it logs 'clearBoard ran!' in the console. I think I just need some direction on how to clear the array so that I can play again.

As I think about my current problem at hand, I'm essentially trying to remove any logged X's or O's in my gameBoard array I've previously created. I've tried various things like setting the gameBoard to an empty array (i.e. gameBoard = []) and doing a replace-text-with ' ' (while this one clears the board, it does NOT allow the user to play again).

Below is my JS for the array and how I'm creating my game board and allowing for X's and O's to be placed. I know I need to pass it a function to clear out my gameBoard array Any guidance would be greatly appreciated.

```js
// This adds an event listener every time a box is clicked, run the updateCell function.
const setUpGameBoard = function () {
  for (let i = 0; i < gameCellIds.length; i++) {
    const elementId = gameCellIds[i]
    const element = document.getElementById(elementId)
    element.addEventListener('click', updateCell)
  }
}

// This logs an X or O into the gameBoard array.
const updateCell = function () {
  console.log(gameBoard)
  const id = this.id
  // const index = index1[1]
  gameBoard[id] = currentPlayer
  checkWinner()
  checkDraw()
  turnCounter()
  if (xWins() === true || oWins() === true) {
    return
  }
}

// Array to check win status. Build array during game.
let gameBoard = new Array(9)
```

**Comment by payne-chris-r** [comment]
Is the problem clearing the board/array or starting another game?

**Comment by payne-chris-r** [comment]
The solution you said you've tried seems like the perfect way to clear the board. Once board is clear you should be able to allow a new game to start the same way you did the first time

**Comment by danman01** [comment]
@andyjzhong can this issue be closed?

**Comment by andyjzhong** [comment]
Yes -- Thank you guys, I'll reopen an issue when I run into something else.
