### ISSUE TITLE
project doesn't work as expected in prod environment

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/game-project#571]
I have repeatedly deployed and not had issues. I deployed a few mins ago and the sign up, sign in etc are throwing HTTP 400 errors. gahhhh.
I have referenced #545, #501 , #554 and I cannot figure out what is wrong. My code is below. PORQUE?!?!?!
my code in API:
```
const config = require('../config')
const store = require('../store')

const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up/',
    method: 'POST',
    data
  })
}
```
my code in config:
```
'use strict'

const config = {
  apiOrigins: {
    // development: 'http://localhost:4741',
    production: 'https://aqueous-atoll-85096.herokuapp.com/'
  }
}

module.exports = config
```

**Comment by awoodrum87** [comment]
clarification. sometimes it works. sometimes it doesn't. 
perhaps it's a server issue? I dunno.

**Comment by payne-chris-r** [comment]
What's the full error? And what URL are you trying it on?

**Comment by awoodrum87** [comment]
Here is a screenshot of the error. 
The URL to my deployed game is: https://awoodrum87.github.io/tic-tac-toe-client/index.html
<img width="560" alt="screen shot 2017-04-10 at 6 37 28 am" src="https://cloud.githubusercontent.com/assets/25780850/24858029/6dcd15aa-1db8-11e7-87d2-8b5dfa086e24.png">

**Comment by awoodrum87** [comment]
I made that comment ^. went right back to the game and my http requests worked. :) a very curious situation..
<img width="538" alt="screen shot 2017-04-10 at 6 40 51 am" src="https://cloud.githubusercontent.com/assets/25780850/24858124/efd54efa-1db8-11e7-85d3-87b1af46cc9c.png">

**Comment by danman01** [comment]
This may happen when you try and create a username that's already in the database. Try a different email address.

**Comment by awoodrum87** [comment]
Thanks @payne-chris-r and @danman01. Must have just been a quirk. Very likely that I used a name/password that was already taken. Closing this issue.
