### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/game-project#573]
I'd like to deploy and then complete my pull request with my url but unable to deploy due to grunt not being installed locally.
here is what I'm seeing in the terminal:

```
$ git status
On branch master
nothing to commit, working tree clean
~/wdi/projects/tic-tac-toe-client (master)
$ grunt deploy
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
~/wdi/projects/tic-tac-toe-client (master)
$ git status
On branch master
nothing to commit, working tree clean
~/wdi/projects/tic-tac-toe-client (master)
$ grunt deploy
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
```

Do I complete bundle install?  I should be at GA by 8:30 if someone needs to look at what I have.
Would love a suggestion or advisement on next steps to get my page deployed as I'd like to inspect it in prod.  

Thank you!

**Comment by payne-chris-r** [comment]
`npm install`

**Comment by payne-chris-r** [comment]
Why are you opening a pull request though?

**Comment by lisamsmith100** [comment]
Ah.  Thanks.  I hoped it would work with install.  I misread and am second-guessing myself now and think I was double-checking the scope study.  Thanks for the response.  Deployment was successful.
Thank you again.
