### ISSUE TITLE
I would like a Git re-do

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/game-project#574]
I have had too many issues with Git since I first deployed the wrong way.  I would like a re-do if possible, since I'm still receiving a lot of conflicts which makes it difficult for me to continue (it's extra work and too confusing/risky).  Is it possible to take the code I have and duplicate/start from scratch with a fresh deploy?

https://jonifallon.github.io/tic-tic-toe/

**Comment by payne-chris-r** [comment]
You typically don't want to do that. You actually want to untangle your mess and get your history back on track. Let's chat on this.

**Comment by payne-chris-r** [comment]
@jonifallon was this resolved?

**Comment by jonifallon** [comment]
Yes, I haven't run into the issue with conflicts for several days.  Closing.
