### ISSUE TITLE
grunt deploy - forms work in grunt serve but not in grunt deploy

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/game-project#575]
All my forms work when I run them in grunt serve, but not when I do grunt deploy.   My error message says: 
```
XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://maggicorp.github.io' is therefore not allowed access. The response had HTTP status code 400.
```
I am concerned this has something to do with my config file, which currently looks like this. 
```js
'use strict'
const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com',
    development: 'http://localhost:4741/'
  }
}
module.exports = config
```

Catherine listed hers as her github account url and it is return a similar error message.

**Comment by jordanallain** [comment]
try replacing
`'https://ga-wdi-boston.herokuapp.com'`
with the correct url

**Comment by Maggicorp** [comment]
Thanks Jordan.  That worked for me, but not for some other people I was working with last night.

**Comment by d00medman** [comment]
So I was having basically the same problem as Maggie, and applied this snippet of code to my configurations. While it worked in removing the no-access-control error, it did not resolve the underlying problem, as I am now being thrown a 400 error and being given this:

`POST https://aqueous-atoll-85096.herokuapp.com//sign-up 400 (Bad Request)`
`vendor.js:9676 XHR finished loading: POST "https://aqueous-atoll-85096.herokuapp.com//sign-up".`
`Object {readyState: 4, responseText: "", status: 400, statusText: "Bad Request"}`

for perspective, the code works perfectly when run 

Why would the same solution applied to to functionally identically c

**Comment by BenGitsCode** [comment]
@d00medman that sounds like a separate issue, please open one if you need assistance. 

@Maggicorp Can you close this issue with a resolution comment?

**Comment by mangoceylon** [comment]
Jordan's fix worked for me FYI.
