### ISSUE TITLE
grunt deploy - forms work in grunt serve but not in grunt deploy part 2

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/game-project#576]
Linking to this issue: https://github.com/ga-wdi-boston/game-project/issues/575

So I was having basically the same problem as Maggie, and applied this snippet of code to my configurations. While it worked in removing the no-access-control error, it did not resolve the underlying problem, as I am now being thrown a 400 error and being given this:

``
POST https://aqueous-atoll-85096.herokuapp.com//sign-up 400 (Bad Request)
vendor.js:9676 XHR finished loading: POST "https://aqueous-atoll-85096.herokuapp.com//sign-up".
Object {readyState: 4, responseText: "", status: 400, statusText: "Bad Request"}
``

for perspective, the code works perfectly when run by maggie and nikki, but when it was applied to myself, catherine and david, it failed. 

Why would the same solution applied to to functionally identical code?

**Comment by benjimelito** [comment]
Take a look at the documentation for that error, it should provide some insight as to what is going on with your request. (Hint, I would look at what data you are providing for your POST)

**Comment by MicFin** [comment]
@d00medman did you get a CURL request to work?  Please share the CURL request for you `POST`

**Comment by d00medman** [comment]
I tried a lot of solutions, including deleting an extra '/' in the url.

Here is my curl request. 

`curl --request POST http://localhost:4741/sign-up \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "an@example.email",
      "password": "an example password",
      "password_confirmation": "an example password"
    }
  }'
`

I honestly think I may need a one on one to help with this problem. I am worried that I may do some serious damage with my constant redeployment.

This is also all to say nothing of the fact that my local grunt server oscillates between working and throwing the following error seemingly at random

`webpackJsonp([0],[
/* 0 */
/***/ function(module, exports, __webpack_require__) 
	__webpack_require__(1);
	(function webpackMissingModule() { throw new Error("Cannot find module \"./index.js\""); }());
/***/ }
]);
//# sourceMappingURL=application.js.map`

**Comment by MicFin** [comment]
Meet me in the kitchen

**Comment by d00medman** [comment]
```js
'use strict'

const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com',
    development: 'http://localhost:4741'
  }
}

module.exports = config
```

So the issue appears to have been an extraneous '/' in the config of my code which caused it to throw a bad portal error.
