### ISSUE TITLE
game-project-api: 500 server not found error when run in local:7165

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/game-project#577]
Hello,
I am getting a 500 server not found error running my game-project-api.  I looked at the issues already open related to this question, and tried them out (checking out, restarting, ect) but none resolved my issues.  When I sign in I get 500 server not found, and when I look at the game project api it says - block in spawn thread and -block in run.  All the sign in and sign out working work fine when I run them from my github hosted site.  The start of the error message in the api server says 
```
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by danman01** [comment]
@Maggicorp That is a postgresql error. Is your postgres server running and is the socket at that location `/tmp/.s.PGSQL.5432`

**Comment by Maggicorp** [comment]
Thanks Danny.  I can't tell if it is running at that location.  Before I tried to sign in the message said 
```
$ bundle exec rails server
=> Booting Puma
=> Rails 4.2.7.1 application starting in development on http://localhost:4741
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[876] Puma starting in cluster mode...
[876] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
[876] * Min threads: 8, max threads: 32
[876] * Environment: development
[876] * Process workers: 4
[876] * Preloading application
[876] * Listening on tcp://localhost:4741
[876] Use Ctrl-C to stop
[876] - Worker 1 (pid: 891) booted, phase: 0
[876] - Worker 0 (pid: 890) booted, phase: 0
[876] - Worker 2 (pid: 892) booted, phase: 0
[876] - Worker 3 (pid: 893) booted, phase: 0
```
Which is what it said before when it was running fine.  I tried to look in the tmp folder at the socket but there was nothing in that folder and I am not really sure what I am looking for.  I also did some googling of postgres and sockets, but still am unable to get the server to run properly.

**Comment by MicFin** [comment]
Try rebooting your PG server using:
`brew services stop postgresql`
 `brew services start postgresql`

**Comment by MicFin** [comment]
@Maggicorp Status update?

**Comment by Maggicorp** [comment]
I did that, but it is still giving the same response and error message.

**Comment by MicFin** [comment]
Let's take a look at the error message together.

**Comment by Maggicorp** [comment]
Postgres needed to be reinstalled.  Issue resolved.

**Comment by Maggicorp** [comment]
Issues has returned. Hey, I am having the same problem again with my rails server that I had yesterday.  It was working fine before lunch, I excited the terminal but didn't turn off the computer, and now it is giving the same error message it gave me yesterday.  Same 500 error.  Yesterday to fix it we reinstalled postgres, but now I am having the same problem.

**Comment by BenGitsCode** [comment]
What is the full error you get when serving?

**Comment by Maggicorp** [comment]
In the terminal it says
```
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by Maggicorp** [comment]
In the browser it says 
```
jquery.js:9566 POST http://localhost:4741/sign-in 500 (Internal Server Error)

```

**Comment by Maggicorp** [comment]
I changes my development URL to http://tic-tac-toe.wdibos.com so I can work on my game, but I still could use help so that in the future I can run a rails server

**Comment by jrhorn424** [comment]
Development URL should indeed be what you've noted here. Production can still point to heroku.

Can we work through this Friday afternoon together, since it is no longer blocking your progress?

Feel free to leave this open until it is resolved.

**Comment by MicFin** [comment]
Has this been resolved?

**Comment by Maggicorp** [comment]
This has not been resolved.  I still need help getting my computer to run rails server api.  However, it has been fixed in that I can work on my game.  Jeff, or anyone, if you can help me with this tomorrow that would be great.

**Comment by MicFin** [comment]
Ice boxed for looking at later with @jrhorn424
