### ISSUE TITLE
development vs production in APIOrigin

### ISSUE THREAD

**Issue by prankmode** [ga-wdi-boston/game-project#578]
I have production and development set as different servers in my config.js file.  Is there something else I need to do to make it use the development string?  When I set the url in my ajax query to
config.apiOrigins it does not pick up the development version of the url.  I can make it work by specifying config.apiOrigins.development but......maybe not so good?

**Comment by MicFin** [comment]
Please share the entire `config.js` file

**Comment by prankmode** [comment]
```
'use strict'

const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com',
    development: 'http://localhost:4741'
  }
}

module.exports = config
```

**Comment by MicFin** [comment]
Have you tried restarting your client server?

**Comment by prankmode** [comment]
Yes, I did.

**Comment by MicFin** [comment]
Ok let's take a look together

**Comment by prankmode** [comment]
the problem is that I was using the plural of config.apiOriginSSSSSSSS instead of singular.

WRONG:
```
const signOut = () => {
  return $.ajax({
    url: config.apiOrigins + '/sign-out/' + store.user.id,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
CORRECT:
```
const signOut = () => {
  return $.ajax({
    url: config.apiOrigin + '/sign-out/' + store.user.id,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

party on.
