### ISSUE TITLE
Git Bash Terminal - Issue Installing NPM Install Dependencies

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/game-project#579]
I am having an issue running npm install from the terminal in the master directory and repository for my file kellyej-tictac-toe game.

**Comment by Jcornmanhomonoff** [comment]
can you past the error you're getting please?

**Comment by kellye2010** [comment]
Hi Jessica,
Below is the screen I see after running the nmp install for dependencies:

![npminstallissue](https://cloud.githubusercontent.com/assets/4691419/24918508/ab5d3eb2-1eae-11e7-8ac5-57be22bbf084.png)

**Comment by kellye2010** [comment]
In the screenshot above, I am not highlighting the text. It appears highlighted once I run npm install, but no other signs of npm install successfully running appear.

**Comment by kellye2010** [comment]
Below is what the issue looks like while running:

![image](https://cloud.githubusercontent.com/assets/4691419/24919362/675eebc2-1eb1-11e7-8c25-323cbc904eb5.png)

And below is the terminal ui after:
![image](https://cloud.githubusercontent.com/assets/4691419/24919414/92dd8a4c-1eb1-11e7-96f3-2e0d2c38327a.png)

**Comment by Jcornmanhomonoff** [comment]
Are you able to run your front end server?

**Comment by kellye2010** [comment]
Yes, I am able to run my grunt server on port 7165.

**Comment by BenGitsCode** [comment]
What is the issue you're having? What you're describing sounds like a successful npm installation.

When npm installs successfully there is no success message.

**Comment by kellye2010** [comment]
I wasn't expecting a literal success message, but I thought it usually listed what was installed.
This issue can be closed. Thank you.

**Comment by Jcornmanhomonoff** [comment]
@kellye2010 Would you mind closing it if you have no further questions please? 🙃

**Comment by kellye2010** [comment]
Training
