### ISSUE TITLE
Unable to PATCH game state using curl

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/game-project#58]
I keep getting 400: BAD REQUEST errors, and I'm not sure why. All of the other API requests work fine. Here's my curl script, which I've been passing the game ID and the logged-in user TOKEN:

``` sh
curl --include --request PATCH http://tic-tac-toe.wdibos.com/games/$ID \
  --include \
  --request PATCH \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data "{
     \"game\": {
      \"cell\": {
        \"index\": 0,
        \"value\": \"x\";
      },
      \"over\": false;
    }
  }"
```

Any help pointing me in the right direction would be appreciated!

**Comment by gaand** [comment]
Is your JSON valid?  You can check with jsonlint.

**Comment by jrhorn424** [comment]
I believe you have a syntax error.

```diff
-        \"value\": \"x\";
+        \"value\": \"x\"
```

**Comment by soynog** [comment]
Got it! Semicolons are just so reflexive now; 

_shakes fist at javascript_

Thank you!!
