### ISSUE TITLE
I think I need to rename my project repo

### ISSUE THREAD

**Issue by bcem2004** [ga-wdi-boston/game-project#580]
I accidentaly saved the file name with a space on the end and it is causing confusion in the terminal.

Thanks!

**Comment by MicFin** [comment]
By file name do you mean the project folder name?  
You changed it from `browser-template` to `something with space`?

If so, then git will perfectly fine with you renaming the folder to what you would prefer.

> *Repository Directory*
> 
> Rename the directory containing the repository, as used by git clone master child:
> 
> Open a command prompt (or file manager window).
> Change to the directory that contains the repository directory (i.e., do not go into the repository directory itself).
> Rename the directory (e.g., using mv from the command line or the F2 hotkey from a GUI).
> Git does not reference this directory name.

https://stackoverflow.com/questions/2041993/how-to-rename-a-git-repository

**Comment by bcem2004** [comment]
Thank worked - Thank you!!!
