### ISSUE TITLE
How to receive input from the console

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/game-project#581]
So I am currently implementing my game engine strictly in javascript. In order to do this, I need to take input from the console in order to log where the current player wants to place their mark. The most straightforward method of doing this I have found is the window.prompt method. This, however, comes with a problem in that this method only works in a browser, which requires me to input my entire code into the js console. Are there methods to receive input from the user directly into the console? I vaguely remember us doing this in an early lesson. If my memory serves me correctly, what lesson would I be best served looking at?

**Comment by benjimelito** [comment]
Although it is certainly possible to create a game that is playable in the console, I would probably recommend simply pasting your game logic in a repl and then running the functions with different inputs to test it. What is the logic you've created thus far?

**Comment by d00medman** [comment]
I have created the board, the move function, the move function's accompanying legality check and just completed the victory checks, but have yet to test them. How do I pass the game through a repl?

**Comment by danman01** [comment]
Have you done this? Google -> javascript user input from console / node.js accept user input from console

**Comment by danman01** [comment]
However, I would urge you to not spend too much time on that approach. It seems at first to make the development process simpler (cutting out the web application portion), but it might turn into something more complicated, as you're having to accept input and run it through your logic via the console, and then do it again via the web.

**Comment by MicFin** [comment]
I agree with @danman01.  You should not need to take input from the user.  Just build a game engine that can add an `x` to your board (array) when you tell it to with a function.  You're overthinking it.

**Comment by d00medman** [comment]
Alright, I've decided to simply move on
