### ISSUE TITLE
Receiving error when trying to check sign-up button

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#582]
index.html:12 GET file:///Users/scott/wdi/projects/tic_tac_toe/public/vendor.js net::ERR_FILE_NOT_FOUND
index.html:13 GET file:///Users/scott/wdi/projects/tic_tac_toe/public/application.js net::ERR_FILE_NOT_FOUND

**Comment by benjimelito** [comment]
I would make sure that the listed path is correct first. Also, could you paste the code that triggers this error?

**Comment by ghost** [comment]
The error pops up directly when the page loads.
`js
<script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
  <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>`

**Comment by Jcornmanhomonoff** [comment]
Does your front end server start okay?

**Comment by ghost** [comment]
Yes grunt server is running

**Comment by MicFin** [comment]
Are you viewing it from `localhost`?  Your message says `file:///Users/scott/wdi/projects/tic_tac_toe/public/vendor.js` which makes me think you are not viewing it from `localhost`.

**Comment by danman01** [comment]
Did this work at some point, then stop working?

**Comment by ghost** [comment]
Thank you Mike, forgot the easiest solution.
