### ISSUE TITLE
Curl Request discrepancy between server response and console log

### ISSUE THREAD

**Issue by bcem2004** [ga-wdi-boston/game-project#583]
Hello,
When I run a "sign-in" Curl request in the server I receive the following:

"$ curl "http://localhost:4741/sign-up" \
>   --include \
>   --request POST \
>   --header "Content-Type: application/json" \
>   --data '{
>     "credentials": {
>       "email": "annn@example.email",
>       "password": "an example password",
>       "password_confirmation": "an example password"
>     }
>   }'
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"4345a0bb6155c15eaf70deaf69d2e94f"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: a74e4fac-9469-4381-adca-7c15df909c50
X-Runtime: 0.464631
Vary: Origin
Transfer-Encoding: chunked"
However, I am not receiving a "success" message in the console. Has a user been created?
Thank you!

**Comment by Jcornmanhomonoff** [comment]
It looks like you are running sign-up and not sign-in as you had mentioned. You are getting a `201 Created` response. Is that not what you're looking for? 200's are success responses.

**Comment by Jcornmanhomonoff** [comment]
If you are confused about what the terminal is giving you back as a response, I might try googling it. ie: http://lmgtfy.com/?q=What+does+201+response+mean

**Comment by bcem2004** [comment]
Further issues to de-bug. Thank you !
