### ISSUE TITLE
Can't console.log click event

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/game-project#584]
I've assigned an id to each box and am trying to console log a click event but nothing occurs.  

// index.html
``` 
<div class="board">

    <div class="row1">
      <div class="box" data-id= "0">X</div>
      <div class="box" data-id= "1">X</div>
      <div class="box" data-id= "2">X</div>
    </div>

    <div class="row2">
      <div class="box" data-id= "3">X</div>
      <div class="box" data-id= "4">X</div>
      <div class="box" data-id= "5">X</div>
    </div>

    <div class="row3">
      <div class="box" data-id= "6">X</div>
      <div class="box" data-id= "7">X</div>
      <div class="box" data-id= "8">X</div>
    </div>
  </div>
```

// events.js
```
const clickedBox = function () {
  console.log('clicked')
}

$('0').on('click', clickedBox)
$('1').on('click', clickedBox)
$('2').on('click', clickedBox)
$('3').on('click', clickedBox)
$('4').on('click', clickedBox)
$('5').on('click', clickedBox)
$('6').on('click', clickedBox)
$('7').on('click', clickedBox)
$('8').on('click', clickedBox)
```

**Comment by benjimelito** [comment]
Have you tried attaching the click handler to something other than the `data-id` to see if you are selecting it properly in jQuery?

**Comment by Jcornmanhomonoff** [comment]
To begin with, double check your syntax. What are the numbers that you're targeting? Classes? IDs?

**Comment by danman01** [comment]
`$('myId').on('click', clickedBox)` is not the proper way to target a _data attribute_. Also, assigning an `id` to an element is not done with `data-id= "myid"`. That being said, you _can_ use data attributes to attach click handlers to elements, and that's a common practice. If you're unsure about data attributes and how to use them, be sure to look it up.

**Comment by eliottenos** [comment]
is the id not assigned properly in index.html?  

tried this with with no joy...

```
$('#0').click(function () {
  console.log('click event called')
})
```
and..
```
$('#0').click(function () {
  alert('click event called')
})

**Comment by MicFin** [comment]
```js
$("#0") 
```
Does not correctly select
```html
<div class="box" data-id="0">X</div>
```
What does it select?  How would you select an element by it's `data-id`?

**Comment by eliottenos** [comment]
taking a step back, this doesnt console log `<h1>`
can't see where my function isnt correct...
```
$('h1').click(function () {
  console.log('You clicked a paragraph!')
})
```

**Comment by eliottenos** [comment]
not sure why that went so big ^^^

**Comment by MicFin** [comment]
Please use the preferred `.on()` method instead of `.click()` although both do work.

```js
$('h1').on('click', function () {
  console.log('You clicked a paragraph!')
})
```
Do you have an `<h1>` element that is on the screen for a user to click and trigger that event?

**Comment by eliottenos** [comment]
Thanks, no just the id which is causing the issue. Should I structure the HTML differently so as not to assign an id to each box?

**Comment by eliottenos** [comment]
The h1 was just an example

**Comment by jordanallain** [comment]
you don't currently have an id assigned to any of the divs, but that is okay. you should change the way you are trying to select it with jQuery.

**Comment by MicFin** [comment]
Let's break down the goals of what you're trying to accomplish.
1.  Use jQuery to select an element(s) in the DOM
2.  Add a click event to the selected element(s)
3.  `console.log()` when the click event is triggered

**1.  Use jQuery to select an element in the DOM**
Let's focus on just step 1.  The HTML element you want to select is...

```html
<div class="box" data-id= "0">X</div>
```

That element is type `div` and has a `class="box"` and a `data-id="0"`.  It does NOT have an ID attribute which would have been `id="something"`.  

So to select that element we need to use either it's element type `div` or it's class `.box` or it's `data-id=0`.  
If we want to make this click event for ALL of the `div`s then we would use the `div` selector.  
If we want to make this click event for ALL of the `.box`s then we would use the `.box` selector.
If we want to make this click event for just this element with `data-id="0"` we would use the `[data-id="0"]` selector.

For you program, you should be able to write the click event so it attaches to ALL of the `.box`s. 

How would you use jQuery to select all of the elements that have the `.box` class?

**Comment by eliottenos** [comment]
```
$('.box').click(function () {
  console.log('You clicked a paragraph!')
})
```

**Comment by tvcrawley** [comment]
With the above code, does the console.log appear when you click on a `.box`?

**Comment by eliottenos** [comment]
nope, code seems to be correct from what i can see...

**Comment by tvcrawley** [comment]
Can you change to using `.on` like in the example below:

```js
$('h1').on('click', function () {
  console.log('You clicked a paragraph!')
})
```

**Comment by eliottenos** [comment]
still no good...

```
$('.box').on('click', function () {
  console.log('You clicked a paragraph!')
})
```

**Comment by eliottenos** [comment]
Problem solved!

Needed to export clickEvent and require in index.js
