### ISSUE TITLE
Module is not defined in Chrome, Safari

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/game-project#585]
Linter Output: Linter is not showing any errors in the .js file where Chrome is saying the error is originating.

Issue Description: _[Chrome error message](http://imgur.com/zrRyMzL)
My code is working, but I get this error message in Chrome and Safari when I begin interacting with my game board.  It doesn't cause anything to break, but I'm not sure if it is something that will hurt me down the line._

[ what you were doing when the problem showed up ]
_I had just imported my code from a different .txt editor (Brackets) that I was using last night to get some of my game logic started.  After I imported the code, I fixed all the Linter errors, and tested it in the browser, and the error showed up._

[ error message (as text), if one exists ]

_Error message in Safari: "Error: Cannot find module 'undefined'."_

_Error message in Chrome: "Uncaught ReferenceError: module is not defined"_

[ the code that caused the error (as a fenced code block) or ]

The error is showing at the bottom, over `module.exports` but here is all my javascript just in case:

```
'use strict'

function startGame () {
  document.turn = 'X'
  changeAlert(document.turn + ' always gets to start.  sorry bruh')
}

function changeAlert (txt) {
  document.getElementById('alert').textContent = txt
}

function nextMove (square) {
  if (square.textContent === '') {
    square.textContent = document.turn
    changeTurn()
  } else {
    changeAlert('pick another square, dummy!')
  }
}

function changeTurn () {
  if (document.turn === 'X') {
    document.turn = 'O'
  } else {
    document.turn = 'X'
  }
  changeAlert('it\'s ' + document.turn + '\'s turn now')
}

module.exports = {
  startGame,
  changeAlert,
  nextMove,
  changeTurn
}
```

[ the code that isn't working as expected ]
_The code is working, but this error is weirding me out_

[ things you've tried to fix the problem ]
_I tried commenting out the module.exports, but got Linter errors.  I tried moving the `<scripts>` tag from the bottom of my index.html into the head, and nothing has removed the error._
[ the last point at which code worked ]
_The code still works :)_

**Comment by danman01** [comment]
Are you running this code from your frontend grunt server? The browser does not support node.js and needs extra libraries to run javascript that uses node features, like `requires` and `module`.

**Comment by rowlandhill** [comment]
Yep!  I'm running it in my [grunt server](http://localhost:7165/).  I was not getting these errors while I was setting up my authentication using `requires` and `module`

**Comment by MicFin** [comment]
@rowlandhill Please share the URL that you are on in the browser and copy and paste the error from the browser console, don't do a screen shot.

**Comment by rowlandhill** [comment]
[URL](http://localhost:7165/)

[ error message (as text), if one exists ]

Error message in Safari: "Error: Cannot find module 'undefined'."

Error message in Chrome: "Uncaught ReferenceError: module is not defined"

**Comment by MicFin** [comment]
Status update?

**Comment by rowlandhill** [comment]
I meant to update this!  I spoke with Jordan and Erica and they guided me to the realization that I'm not exporting anything in my gamelogic.js file and it's not being required anywhere else.  I need to export them to index.js, require gamelogic.js in index.js and then put all the functions in the document.ready function and call them that way.  I don't know if I'm wording it correctly, but I need to mirror what we did for events.js

**Comment by rowlandhill** [comment]
So I think it's safe to close this out, unless what I wrote above doesn't make any sense and I still don't understand the problem I have hahaha

**Comment by MicFin** [comment]
Yes, sounds like you solved that particular issue, please close.

**Comment by rowlandhill** [comment]
Thanks!
