### ISSUE TITLE
Pass argument to a function from an event handler

### ISSUE THREAD

**Issue by joebelmonte** [ga-wdi-boston/game-project#586]
Hi, is there a way to pass an argument (other than 'event') to a function that is called from an event handler?

This is my code (which is not working):

```js
const addHandlers = () => {
  $('.zero').on('click', gamePlay(0))
}
```
.zero is the upper left square.   I would like to create 1 gamePlay function that adds Xs and Os to the game board but I need to pass an argument to that function that tells it which square to modify.

**Comment by MicFin** [comment]
Have you considered adding a `data-board-position` to the element so you can create a callback that uses `event` or `this` to get the `data-board-position` value

```js
const gamePlay = function(event) {
   // use jquery to get the data-board-position attribute value of the object clicked
}
```

I think that is a better solution.  If you must pass an argument to a click event then please read more about how to do so at the `.on()` answer to this StackOverflow question
http://stackoverflow.com/a/16708040/2842709

**Comment by joebelmonte** [comment]
Thanks for the quick response and the suggestion! For the time being I have implemented a different, less elegant approach but it is at least functional. Once I complete all of the other requirements, I will circle back to this and see what I can do, time permitting of course. 

Closing the ticket for now.
