### ISSUE TITLE
Cancel button submitting form

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/game-project#587]
I am having a strange issue where clicking the cancel button (#change-password-cancel-btn) on a form (#change-password) triggers the form submission event. When either button is clicked, it triggers the "onChangePassword" event handler.

I've used this pattern for the sign up and sign in forms and the cancel links on those fire two separate events.

This code sets the html of the content div
```
const viewState = '<div class="form-box">' +
    '<form id="change-password">' +
      '<fieldset>' +
        '<legend>change password</legend>' +
        '<div class="form-group">' +
          '<input type="password" class="form-control" name=passwords[old] id="change-password-old" placeholder="old password">' +
        '</div>' +
        '<div class="form-group">' +
          '<input type="password" class="form-control" name=passwords[new] id="change-password-new" placeholder="new password">' +
        '</div>' +
        '<button type="submit" class="btn btn-default pull-right">submit</button>' +
        '<button class="btn btn-link pull-right" id="change-password-cancel-btn">cancel</button>' +
      '</fieldset>' +
    '</form>' +
  '</div>'

  $('.content-state').html(viewState)
```
These are the event handlers for the form:

```
$('body').on('submit', '#change-password', onChangePassword)
$('body').on('click', '#change-password-cancel-btn', game.backToGame)
```
Here is the AJAX call for change password:
```
const changePassword = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/change-password/' + store.user.id,
    method: 'PATCH',
    headers: {
      'Authorization': 'Token token=' + store.user.token
    },
    data
  })
}
```
And the two functions to handle success & failure:
```
const changePasswordSuccess = (response) => {
  console.log('changePasswordSuccess:', response)
  game.message('password changed')
  game.backtoGame()
}

const changePasswordFailure = (error) => {
  console.error('changePasswordFailure:', error)
  game.message('password change failed')
}
```

**Comment by MicFin** [comment]
1.  Dangerous to add click events to the `body` element.  I would start by re-evaluating what you are adding a click event to, choose a parent closer than the `body`.
2.  Remember event bubbling.  If a button is clicked, it will bubble up to the form unless you stop it.  Potentially the cancel button should be outside of the form so it doesn't bubble up to it.

**Comment by pjliddy** [comment]
adding type="button" to the cancel link resolved the submission issue.
