### ISSUE TITLE
Error when running my "Sign Out" button in the browser

### ISSUE THREAD

**Issue by noobiwankenoobi** [ga-wdi-boston/game-project#588]
Getting error: TypeError: cannot read property "id" of undefined.

It's coming from this part of my code in my api.js file (in bold):
```js
const signOut = () => {
  console.log('inside signIn. data is:')
  return $.ajax({
    url: config.apiOrigin + '/sign-out' + **store.user.id,**
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

I believe I either need to alter that "store.user.id" bit or delete it altogether.

**Comment by benjimelito** [comment]
I would verify if `store.user.id` is defined by console.logging it somewhere in your code, and also checking to make sure you're exporting it properly. As an aside, I also see an issue with that url...

**Comment by noobiwankenoobi** [comment]
I think the url is what I was trying to point out actually. I tried to bold it. Is that showing up?

**Comment by benjimelito** [comment]
No, that definitely shows up. I was merely pointing out that you need a '/' between `sign-out` and `store.user.id`.

**Comment by noobiwankenoobi** [comment]
Perfect, thank you Ben. It's still not working but I will keep working on it.

**Comment by benjimelito** [comment]
Would you mind posting in your code for your `store` file? It might also be helpful to paste in your code that creates data in the `store` file.

**Comment by noobiwankenoobi** [comment]
From store.js file:
```js
'use strict'

const store = {
}

module.exports = store
```
---------------------
from ui.js file:
```js
const signInSuccess = (data) => {
  console.log('Sign in successful!', data)
  store.user = data.user
}

const signOutSuccess = () => {
  console.log('Succesfully Signed Out')
  store.user = null
}
```
-------------------
from events.js file:
```js
const onSignOut = function (event) {
  event.preventDefault()
  console.log('sign out is running')

  api.signOut()
    .then(ui.signOutSuccess)
    .catch(ui.signOutFailure)
}
```

**Comment by noobiwankenoobi** [comment]
yeah it says store.user is undefined. Is that because on signOut the user is getting deleted?
If that's the case, I don't know what to put there instead.

**Comment by benjimelito** [comment]
I would try to approach this in incremental steps: First check to see that `data.user.id` exists in your `signInSuccess` function. Then check to see that `store.user.id` exists, then check to see that `store.user.id` is recognized in your `api.js` file. If you still can't find the place where it's breaking we can go over it tomorrow.

**Comment by MicFin** [comment]
Status update?

**Comment by noobiwankenoobi** [comment]
Still having the problem. To the point where I straight up checked the solutions branch of the lesson we did and can't see the difference. I'm probably just tilted. Will take any help given. I moved on to other stuff in the meantime

**Comment by MicFin** [comment]
ok come out to kitchen we can take a look

**Comment by noobiwankenoobi** [comment]
SOLUTION:

page refresh was losing the store.user value
didn't know refresh button reset everything
assumed it was automatically storing in cache
thnx 4 help.
