### ISSUE TITLE
[ Javascript ] - Can I use another Javascript library

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/game-project#589]
Am I allowed to use another javascript library in this project?
I would use one to handle routing. To switch between sign in, sign up and game screens.
I'm considering React or Mustache/[Moostaka.](http://moostaka.mrvautin.com/gettingstarted)

I would only do this if I have bonus time after I meet all requirements.

**Comment by danman01** [comment]
You can achieve the same idea of switching between views (sign up, sign in, game screen) with javascript and / or jquery to show / hide certain elements of the page. If you did want to explore other libraries after you've met all requirements, feel free.

**Comment by benjimelito** [comment]
I'm personally a big fan of React, but there's definitely a lot that takes getting used to when using it. If you've met all requirements and have any questions about it feel free to open some issues.

**Comment by arlofeirman** [comment]
thanks!

**Comment by aprilsourz** [comment]
Thank you
