### ISSUE TITLE
JQuery - Issue Alternating after Click Handler

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/game-project#59]
Hi, I created my playMove function to alternate between turns, but after testing it and searching through google -- I can't find my epiphany that will make it work. I was hoping that I could change my 'player'  variable each time there is a click.

``` js
const playerMove = function() {
  let player = 'x';
  let turn = 0;

  if(player === 'x') {
  $('.tile').on('click', function(event) {
    event.preventDefault();
     $(this).text('X').css('font-size', '30px').css('text-align', 'center');
     player = 'o';
     turn++;
  });
}
  else if(player === 'o') {
  $('.tile').on('click', function(event) {
    event.preventDefault();
    $(this).text('O').css('font-size', '30px').css('text-align', 'center');
    player = 'x';
    turn++;
  });
}

};
```

**Comment by RDegnen** [comment]
Have you tried putting a debugger in to see whats happening at each step of your handler?

**Comment by laurenfazah** [comment]
Where/when are you calling the `playerMove()` function? Make note of the variables you're initializing at the beginning of the function block.

**Comment by RealWeeks** [comment]
@rdelvallej32 has this issue be resolved?  Any further questions? Please ask.

**Comment by rdelvallej32** [comment]
I'm trying to use/read the debugger

**Comment by RDegnen** [comment]
Is it returning what you expect?

**Comment by rdelvallej32** [comment]
I'm unsure, it's just posting X after the debugger

**Comment by laurenfazah** [comment]
I met with Roberto to try to clear up some convoluted code. He's going to run with that and hopefully reach a solution soon.

**Comment by rdelvallej32** [comment]
Thank you! I cleaned up the code and now it is alternating between X and O!
