### ISSUE TITLE
Updates made to HTML page do not stick to local server

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/game-project#590]
I am currently building the tic-tac-toe board in my html. When I apply the local file path to my browser, I am able to see the changes I have made. However, when I attempt to view these changes on my localhost, I see nothing and am thrown the error 

`
Resource interpreted as Stylesheet but transferred with MIME type text/x-scss: "http://localhost:7165/assets/styles/index.scss".
`

How can I resolve this error so I can use my local host to assess my HTML/CSS code?

**Comment by MicFin** [comment]
These are 2 different questions.  Let's start with just HTML.

1.  What HTML file have you made changes to?  What were those changes?  How did they appear (if at all) on the page when you viewed it from `localhost`?  What URL did you view it from?
2.  Are you on the correct branch?  Make sure your working directory and the branch your server is running from are the same.   
3.  Handle CSS after you solve this HTML issue and open a new issue for the CSS.

**Comment by d00medman** [comment]
2. my grunt server is on the same branch as my working directory.

1. the file I have been using has been index.html. As it stands, most changes actually render with no problem (for example, the addition of a reset button or the creation of some new headlines). However, this code (the build of the board) has proven to be doggedly problematic

`          <div class="game-board">

            <div class="container">

            <div class="row">

              <div class="inner" data-id ="0">

                <button class="cell" data-id="0" id="0" type="button"></button>

              </div>

              <div class="inner" data-id ="1">

                <button class="cell" data-id="1" id="1" type="button"></button>

              </div>

              <div class="inner" data-id ="2">

                <button class="cell" data-id="2" id="2" type="button"></button>

              </div>

            </div>

            <div class="row">

              <div class="inner" data-id ="3">

                <button class="cell" data-id="3" id="3" type="button"></button>

              </div>

              <div class="inner" data-id ="4">

                <button class="cell" data-id="4" id="4" type="button"></button>

              </div>

              <div class="inner" data-id ="5">

                <button class="cell" data-id="5" id="5" type="button"></button>

              </div>

            </div>

            <div class="row">

              <div class="inner" data-id ="6">

                <button class="cell" data-id="6" id="6" type="button"></button>

              </div>

              <div class="inner" data-id ="7">

                <button class="cell" data-id="7" id="7" type="button"></button>

              </div>

              <div class="inner" data-id ="8">

                <button class="cell" data-id="8" id="8" type="button"></button>

              </div>

            </div>

          </div>
`

It does not appear at all when on my local host, while appearing when I call with the filepath (though it's behavior can be described as finicky at best. 

It is worth noting that, in the head I attached the following line of code:
`<link href="./assets/styles/index.scss" rel="stylesheet" type="text/css">`

There was no link to my stylesheet when I began to build the board, which caused the inner items to stack on each other rather than form rows of three. When I attached the stylesheet link, I found it worked successfully when loading the filepath, but throws this error when I spin up my grunt server. It is also worth noting that, even when I remove the stylesheet and spin up my grunt server at this point, there is no change in output.

I am almost certain that this is where my error is, however, this was the only way I was able to render a tic tac toe board without using a table, so I am very hesitant to scrap what I have.

**Comment by d00medman** [comment]
An update on this issue: I ended up removing the link in the head, but I also noted that my linter starts screaming whenever I type in the .scss folder. Is it possible that the dependencies necessary for scss to properly link have not been installed?

**Comment by jordanallain** [comment]
you added `<link href="./assets/styles/index.scss" rel="stylesheet" type="text/css">` to the head of the index.html?

**Comment by d00medman** [comment]
Yes. I copied that link from the fundamentals and updated the href with the
path of my index.scss. When I open the browser with the path of my HTML
page, it works exactly as intended (it did not do so before I put that line
in the head). However, it did not work on my localhost and threw the above
error.

Also, I'm replying by email because this comment was not visible in the
issue queue for whatever reason.

I'm pretty much stonewalled here. I cannot really finish my HTML build
until I can properly render the board, and this is the primary obstacle to
me completing this objective.

**Comment by Jcornmanhomonoff** [comment]
1. You should not need to link to the index.scss stylesheet in your HTML. 
2. Please answer Mike's 1st question about how the HTML is appearing: `How did they appear (if at all) on the page when you viewed it from localhost? What URL did you view it from?`

**Comment by d00medman** [comment]
Here is how the HTML appears when rendered on my localhost:7165 
http://imgur.com/a/ETqT4

for perspective, here is what it looks like when drawn in the browser with the file path:
http://imgur.com/a/4x9ur

and here is what it looks like when it is rendered in the browser with the file path when the head has the stylesheet link, which is what I am working towards:
http://imgur.com/a/vrNRL

**Comment by BenGitsCode** [comment]
Alex come find me in the kitchen and I'll take a look.

**Comment by d00medman** [comment]
Issue was that something in my CSS overwrote the HTML and prevented its rendering.

**Comment by payne-chris-r** [comment]
@d00medman please post what that "something" was so people like you that run into this issue know how to avoid this in the future!

**Comment by d00medman** [comment]
Honestly, I have no idea what that something was. I was told to open a separate issue to resolve it, but ended up moving in a different direction in my implementation in order to bypass the issue entirely. 

While I am not sure what it was, my guess is that whatever this process indicates

`Resource interpreted as Stylesheet but transferred with MIME type text/x-scss: "http://localhost:7165/assets/styles/index.scss".`

is at the core of the issue.

**Comment by jrhorn424** [comment]
Do browsers know how to interpret SASS? Is `scss` the same file extension as `css`?

**Comment by d00medman** [comment]
I don't think so; isn't SASS a scripting language which turns .scss files into .css files which can be rendered by the browser?

**Comment by jrhorn424** [comment]
Correct. So when you use `link`, you're asking the browser to go get a resource from a server somewhere (could be the same one your HTML came from) and "inline" that resource. The browser will complain when it is asked to interpret something it doesn't know how to.

What do you infer about our template and how you should include SASS in a project?

**Comment by d00medman** [comment]
That the template is designed to handle all of these things on its own and the linkages are pre-built?

**Comment by jrhorn424** [comment]
That's right, so how where would you put your own SASS? Where would you put someone else's SASS?

**Comment by d00medman** [comment]
Both in separate files with export statements pointing to index.scss?

**Comment by MicFin** [comment]
Do we use export statements in SASS?

**Comment by d00medman** [comment]
hmm this may have been where I erred. I tried to place my CSS in a separate holder, but the same issue of my HTML being overwritten emerged. Entirely possible I was mistakenly using export instead of import.

**Comment by MicFin** [comment]
Status?  Can this be closed?

**Comment by d00medman** [comment]
Yeah. I opted to go a different route in the creation of my board.

**Comment by MicFin** [comment]
Did that work?  If so, please explain how you solved it and close.
