### ISSUE TITLE
Trouble starting game

### ISSUE THREAD

**Issue by mangoceylon** [ga-wdi-boston/game-project#591]
Using a jquery click and function to start game:

The click event is using the containing div for the gameboard:
`const gameHandlers = () => {
  $('game-board').on('click', fillCell)`

The function fillCell is trying to add the string 'X' or 'O' to the individual ID for the clicked cell using "this":
const fillCell = () => {
  for (let i = 0; i < gameBoard.length; i++) {
    if (i === 1) {
      document.this.innerHTML = 'X'
    } else {
      if (i % 2 === 0) {
        document.this.innerHTML = 'O'
      }
    }
  }
}`

gameBoard is an empty array

**Comment by jordanallain** [comment]
first lets reformat your code. to open a code block type

\```js
Three back ticks to open the block, then the name of the language, js for javascript
\```
Three more back ticks to end the code block

```js
const fillCell = () => {
  for (let i = 0; i < gameBoard.length; i++) {
    if (i === 1) {
      document.this.innerHTML = 'X'
    } else {
      if (i % 2 === 0) {
        document.this.innerHTML = 'O'
      }
    }
  }
}
```

second, have you put a console.log statement in the click event to see if you are capturing the click on the correct element?

**Comment by mangoceylon** [comment]
Thanks. This helped conceptually with what I'm going to do. Closing.
