### ISSUE TITLE
Change Password id returning as undefined in console

### ISSUE THREAD

**Issue by Pouk91** [ga-wdi-boston/game-project#592]
Hi, I'm having issues with creating my api change password function. I keep receiving the error message below. Mentioned also is the code I've used below the error message.

api.js:25 data is  Object {passwords: Object, submit: "Change password!"}
2017-04-11 19:05:18.750 api.js:27 Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.changePassword (api.js:27)
    at HTMLFormElement.onChangePassword (events.js:27)
    at HTMLFormElement.dispatch (jquery.js:5206)
    at HTMLFormElement.elemData.handle (jquery.js:5014)

```js
event.js

const onChangePassword = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  api.changePassword(data)
    .then(ui.changePasswordSuccess)
    .catch(ui.changePasswordFailure)
}
```

```js
api.js
const changePassword = (data) => {
  console.log('data is ', data)
  return $.ajax({
    url: config.apiOrigin + '/change-password/' + store.user.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```
```js
ui.js
const changePasswordSuccess = (response) => {
  console.log(response)
}

const changePasswordFailure = (error) => {
  console.error(error)
}
```
```sh
change-password.sh
#!/bin/bash

curl --include --request PATCH http://localhost:4741/change-password/$ID \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "passwords": {
      "old": "d",
      "new": "super sekrit"
    }
  }'

```html
index.html
  <form id="change-password">
    <fieldset>
      <legend>Change password</legend>
      <input type="password" name="passwords[old]" value="old password">
      <input type="password" name="passwords[new]" value="new password">
      <input type="submit" name="submit" value="Change password!">
    </fieldset>
  </form>
```

**Comment by jordanallain** [comment]
did the curl request work?

have you tried console.logging `store.user.id` to see what its value is?

**Comment by Pouk91** [comment]
I did and it was returning as undefined and sorry was going to close this before someone commented. The issue resolved it self not sure what was the cause but everything works now. Thanks for replying though!
