### ISSUE TITLE
Currently working on game engine, stuck on "add to board" stage

### ISSUE THREAD

**Issue by TronB** [ga-wdi-boston/game-project#595]
To add a bit more detail, I skipped the authentication step provided in the game project schedule and moved to the game engine. I created a 3x3 grid using tables and gave a data id to each square to represent the different parts of the game board like so:
```
<table class="game-board" align="center">
    <tr class="row-one">
        <td data-id="one"></td>
        <td data-id="two"></td>
        <td data-id="three"></td>
    </tr>
    <tr class="row-two">
        <td data-id="four"></td>
        <td data-id="five"></td>
        <td data-id="six"></td>
    </tr>
    <tr class="row-three">
        <td data-id="seven"></td>
        <td data-id="eight"></td>
        <td data-id="nine"></td>
    </tr>
</table>
```
I thought of doing a click method to start off, but can't get it to work. I'm not sure if it's due to the syntax or because I don't have my JS file set up properly(I inserted this code to a new JS file because I couldn't locate the JS files listed in the html file)

```
const onClickCell = function (evt) {
  const sqNum = evt.target.data(id)
  if (typeof sqNum !== 'string') {
    const player1 = 'X'
    return player1}
  else {
    return false
  }
}

$('.game-board').on('click', onClickCell)
```

**Comment by samguergen** [comment]
Have you tried commenting the JS file, and instead, replacing it with a basic console.log() ?
If the logging works, you know that the JS file is correctly linked. You can also run your local server and check to see if you are receiving any 404 or 'file not found' error in your JS console.

**Comment by TronB** [comment]
Hi Sam, I did. I believe the JS file i created is properly linked. I'm getting an error saying that '$' is not defined. Do I have to setup Jquery whenever I create a new JS file?

**Comment by MicFin** [comment]
Join me in the kitchen at 10:30 and I will take a look with you.
