### ISSUE TITLE
Game Engine Steps

### ISSUE THREAD

**Issue by bcem2004** [ga-wdi-boston/game-project#597]
Hello,
I am having difficulty formulating a plan for the game engine. I was hoping you could provide some questions/things to think about just to get me heading in the right direction. Here are my notes so far:
1. an x needs to exist
2. an O needs to exist
3. I need to make an array. I don't know if this should simply 1-9 or if every item should be a square combo i.,e (1,2), (3,3) etc.
4. I believe Boolean will need to be used at some point, for example, if x=true than you can't put an o in that box
5. Before step 4, an X will need to placed, and I am stuck there, as well.

I am sorry; I know this is not an actual question and I don't have examples of code to share. I don't know if this is "allowed", but if I am able to get certain prompts (similar to how Fundamentals was set up), I am fairly certain I would be able to construct the functions. 

Please let me know if there is anything else I can provide.

Thank you.

**Comment by jordanallain** [comment]
do you have a board rendered in your html?

**Comment by bcem2004** [comment]
yes
'html'
<br>
  <div class="board">
    <div class="row">
      <div class="col-xs-4 box">X</div>
      <div class="col-xs-4 box">O</div>
      <div class="col-xs-4 box">X</div>
    </div>
    <div class="row">
        <div class="col-xs-4 box">O</div>
        <div class="col-xs-4 box">X</div>
        <div class="col-xs-4 box">O</div>
    </div>
    <div class="row">
        <div class="col-xs-4 box">X</div>
        <div class="col-xs-4 box">O</div>
        <div class="col-xs-4 box">X</div>
    </div>
  </div>

**Comment by bcem2004** [comment]
sorrry

**Comment by bcem2004** [comment]
`html`
<br>
  <div class="board">
    <div class="row">
      <div class="col-xs-4 box">X</div>
      <div class="col-xs-4 box">O</div>
      <div class="col-xs-4 box">X</div>
    </div>
    <div class="row">
        <div class="col-xs-4 box">O</div>
        <div class="col-xs-4 box">X</div>
        <div class="col-xs-4 box">O</div>
    </div>
    <div class="row">
        <div class="col-xs-4 box">X</div>
        <div class="col-xs-4 box">O</div>
        <div class="col-xs-4 box">X</div>
    </div>
  </div>

**Comment by bcem2004** [comment]
sorry, i'm trying to send this in markdown format and obviously failing. sorry

**Comment by BenGitsCode** [comment]
Those are all great of how to build the engine, I think you just need help organizing them and that's okay.

Have you tried turning any of that into pseudo code?

That's also okay, what are you trying to format it as?

**Comment by BenGitsCode** [comment]
This is a great reference https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by bcem2004** [comment]
Hi, I was trying to send the code for my board in html. I used the "insert code" brackets, but it isn't going through

**Comment by bcem2004** [comment]
The notes I wrote above were my pseudo code, but that is as far as I was able to get. I have been referencing the js from fundamentals to job my brain. My issue with js is that I can follow along in class, but am still having trouble producing it myself.

**Comment by bcem2004** [comment]
Should I just continue with pseudo code?

**Comment by jordanallain** [comment]
sure if that would help. i think having a rendered board in html will help with setting up click handlers and having a spot where the X's and O's will go. that might be a good first step if you don't have anything in HTML yet. what type of HTML elements would be good to represent the board?

**Comment by bcem2004** [comment]
Thank you for your responses, but I am nowhere near the point of click handlers, etc. I literally haven't started any javascript. I know we are not supposed to ask, but if anyone is able to sit down with me to point me in the right direction, I would greatly appreciate it. I literally do not know where to start.

**Comment by jordanallain** [comment]
i'm telling you where to start. first get some HTML rendered to your page that resembles a tic-tac-toe board. do you need assistance with that?

**Comment by bcem2004** [comment]
yes please

**Comment by jordanallain** [comment]
Emily's gameboard in HTML

<img width="358" alt="screen shot 2017-04-12 at 10 29 16 am" src="https://cloud.githubusercontent.com/assets/18097107/24962798/e9df231e-1f6a-11e7-983d-6616dbc4215e.png">

**Comment by jordanallain** [comment]
so you have a board in HTML, have you applied any CSS to it so that it visibly appears like a tic-tac-toe board?

**Comment by bcem2004** [comment]
![screen shot 2017-04-12 at 10 32 13 am](https://cloud.githubusercontent.com/assets/26386601/24962973/615c8940-1f6b-11e7-9c9f-a2f8bc2600b3.png)

**Comment by bcem2004** [comment]
Full Disclosure - got help from  a classmate last night

**Comment by jordanallain** [comment]
sweet so we have a board, but we don't want it to be pre-populated with X's or O's. what is the smallest problem we can solve next (other than removing the X's and O's) ? i would say setting up an event listener on these cells that simply console.log's a message so we know the event listeners are set up properly.

what do you think?

**Comment by bcem2004** [comment]
I will try to do the event listeners. Thank you.
