### ISSUE TITLE
Difficulty with GameApi curl request for Updating Game

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/game-project#598]
I'm trying to run the curl request to update the game api.  Here is my update-game.sh doc data.  I currently am using a game ID from the create game function which I have working, and the TOKEN is the TOKEN from the user who signed in when the game was created.  I looked at the issue cue, but all those answers and questions were about the step after the curl request worked.  Any suggestions?
```
#!/bin/bash

curl --include --request PATCH http://localhost:4741/games/$GameID \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data '{}'
# data output from curl doesn't have a trailing newline
echo
```

Here is what I put in the terminal
```
TOKEN=BAhJIiUxMWEwMDkzMDk1YjVhOGVhZWI4MTk1MDczNzhjNjA3NAY6BkVG--ebaf8b610314cd60db524d0a65b546766860fb42 GameID=33 sh scripts/update-game.sh 
```

**Comment by BenGitsCode** [comment]
Where are you trying to make a curl request to, and why?

**Comment by Jcornmanhomonoff** [comment]
What's the response you're getting from that CURL request?

**Comment by Maggicorp** [comment]
The response is a 400 Bad Request.  I am trying to access a game I have already started, I think, but I am a little fuzzy about the game api overall. 

```
HTTP/1.1 400 Bad Request
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache
Content-Type: application/json
X-Request-Id: 7798354e-4951-4cce-b04c-179225963578
X-Runtime: 0.117419
Vary: Origin
Transfer-Encoding: chunked
```

**Comment by jordanallain** [comment]
have you looked at the API documentation for what it is expecting for a PATCH request?

**Comment by Maggicorp** [comment]
Yes, I am looking at it right now. I think partly my confusion is about what I should be passing. It seems like just the object ID number is not sufficient and I need to pass this.  What I am trying to do is the step -- Update Game (curl then web app).  Am I passing a move to an existing game? 
```
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
``` 
In the data section.

**Comment by prankmode** [comment]
Hey Maggie - Yes, you need to update an existing game.  And the update is the new move.  It kinda freaked me out - I thought we could just send the whole array but no - just the item that is updated.

**Comment by Maggicorp** [comment]
Cool, I

**Comment by Maggicorp** [comment]
Cool, thanks everyone I got the curl request to work.  I just had to input the data for making one move.
