### ISSUE TITLE
My browser is returning 'ReferenceError: $ is not defined' when I try to run on Grunt Serve

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/game-project#599]
When I'm trying to run my code on my grunt server, I'm getting an issue saying that $ is not defined. 
My browser is not reading the JQuery functions I'm trying to use.

This is my html head:
```<html>
    <head>
      <title>Example</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Do not add `link` tags unless you know what you are doing -->
      <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

      <!-- Do not add `script` tags unless you know what you are doing -->
      <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="assets/scripts/gameLogic.js"></script>
    </head>
```

And this is the variable I'm trying to declare with JQuery (it is on gameLogic.js):
```
'use strict'

// Where my code starts
// const elementId = document.getElementsByClassName('col-xs-4')

const elementId = $('.col-xs-4')
```

**Comment by samguergen** [comment]
In your JS file, you should add a script tag linking your jQuery third-party.
This should be a relative path to your jQuery file. You can also use the following CDN: 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

**Comment by MicFin** [comment]
On a personal project that would be an excellent way to link jQuery.  In our project, it is already loaded through your `index.js`.  Your `gameLogic.js` file must be loaded (required) into the `index.js` to work properly.

**Comment by jbeltrami** [comment]
Thank you!
