### ISSUE TITLE
Correct path to require() files?

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/game-project#600]
I am working with two files in my scripts directory: game.js and views.js. 

When I call a function in views.js from the game.js file, I get the following error:
```
views.message is not a function
```

In the new game.js file:
```
'use strict'
const views = require('./views.js')

const initGame = function () {
  views.message('player X\'s turn')
}
```
I can call files in the game.js file when the following is in view.js, so I'm stumped on why I'm getting the error. I suspect it's something other than the require file path.
```
const game = require('./game.js')
```

**Comment by jordanallain** [comment]
you have `game.js` requiring `views.js` and `views.js` requiring `game.js` ?

if that is the case you have a dependency loop going on there where the files are requiring each other, this will never work.

**Comment by pjliddy** [comment]
yeah. I was just looking at that.

**Comment by jordanallain** [comment]
you can create another file that only exports things needed by other files and doesn't require anything.

**Comment by pjliddy** [comment]
cool. thanks
