### ISSUE TITLE
Passing click event into variable, and arrays into functions

### ISSUE THREAD

**Issue by mangoceylon** [ga-wdi-boston/game-project#601]
I'm trying to create a variable to store the currently clicked on item, using language something like this:

`let clickID = $('data-id').on('click')`

I'm trying to test around the action with code like this:
`$('#button').on('click', function () {
  const clicky = $(this)
  console.log(clicky.data('id'))
})`

But not getting any interaction with the dom.

I'm also passing arrays into functions and I'm getting an error that these arrays are never being used, example:

`let playerY = ['', '', '', '', '', '', '', '', '']`

`let checkForWinner = function (playerX, playerY, winner)`

**Comment by jordanallain** [comment]
okay one thing at a time. you are targeting the ID button is that what you are trying to do? if you console.log('Hello') does it log 'Hello' to the console when you click on the element you are setting the listener on?

**Comment by MicFin** [comment]
I agree.  You have 3 steps you're trying to accomplish but you didnt successfully complete step 1 and moved to step 3.

1.  Use jQuery to select an element(s) in the DOM
2.  Use jQuery to add a click handler to the selected element(s)
3.  Use jQuery to get the `data-id` attribute from the clicked element

Please start at step 1.  Currently `$('data-id')` is likely not selecting the element you want.

**Comment by mangoceylon** [comment]
Thanks, I slowed down and logged a bunch and figured the jQuery issue out.

I'm now at the point where I'm assigning values but they are not getting used. Some of them seem pretty obvious (I probably need to return a result to use the variable/function) but other ones make it seem like I'm not getting something with global vs local scope, such as the array example above.

**Comment by MicFin** [comment]
Please close this issue with a solution of hte correct click event and open a new issue with code examples of your current issue.
