### ISSUE TITLE
Added ids to html and columns disappeared in css

### ISSUE THREAD

**Issue by bcem2004** [ga-wdi-boston/game-project#602]
Hello,

I added ids to my html in an attempt to start the engine logic and the columns disappeared. I am going to try to move on the logic, but am just wondering if there were any ideas on how to adjust the css.

Thank you.

![screen shot 2017-04-12 at 11 12 11 am](https://cloud.githubusercontent.com/assets/26386601/24965163/45e297e4-1f71-11e7-87d3-49ebe2960895.png)

**Comment by bcem2004** [comment]
previous grid
![screen shot 2017-04-12 at 10 32 13 am](https://cloud.githubusercontent.com/assets/26386601/24965188/54fcf224-1f71-11e7-945a-36e509082ff7.png)

**Comment by bcem2004** [comment]
current grid
![screen shot 2017-04-12 at 11 15 58 am](https://cloud.githubusercontent.com/assets/26386601/24965214/6edbe470-1f71-11e7-81fa-74c7bb1d5548.png)

**Comment by Jcornmanhomonoff** [comment]
What does your css look like?

**Comment by MicFin** [comment]
Your HTML looks great, share the CSS like @Jcornmanhomonoff suggested

**Comment by Jcornmanhomonoff** [comment]
@bcem2004 can you post your solution on this and close please?! 🙃

**Comment by bcem2004** [comment]
Worked with Jessica to resolve. Thank you.
