### ISSUE TITLE
Update Game questions - trying to access game ID

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/game-project#603]
Hello,
I am trying to figure out the best way to save and update my gameID number so I can access it to use the for the update game request.  I have some general question about how this id works and what I am passing.  I would love some one-on-one help with it if possible.  If not, I can continue to elaborate on specific questions.

**Comment by MicFin** [comment]
I would use the same strategy you used with saving your `user` object when you got that back from the API with a token.  Do you recall what that was?

**Comment by Maggicorp** [comment]
I did.  I tried to save it is store.games = response.games 
and then tried to call it with store.games.id

**Comment by Maggicorp** [comment]
The error I get is that it cannot read the id property of undefined at Object.updateGame.

**Comment by Maggicorp** [comment]
So it seems like I am either not saving it or not calling it correctly.  I am looking over the documentation to try and find out where that end of the problem is.

**Comment by Maggicorp** [comment]
Using my console log it looks like it isn't saving it to store.  Shouldn't this be saving the games object to store.js?  When I console.log response it is the right thing. 

```
const store = require('../store.js')

const newGameSuccess = (response) => {
  console.log(response)
  $('.instruction-box').text('You did it! Now you can play!')
  store.games = response.games
}

```

**Comment by jordanallain** [comment]
what did `response` look like when it logged it.

**Comment by Maggicorp** [comment]
response logs to the correct object, but when I console.log store the response game object isn't there

**Comment by MicFin** [comment]
Please show what `response.games` logs in the console and also `response`.

**Comment by Maggicorp** [comment]
Hey, found the problem.  It turns out that I was working off of the wrong createGameSuccess function.   
Thanks!
