### ISSUE TITLE
General help with events/eventhandlers/data-ids

### ISSUE THREAD

**Issue by noobiwankenoobi** [ga-wdi-boston/game-project#606]
Need a nudge/

Help understanding:
-exactly what event.target does in getFormFields(event.target)
-data-id's
-"on right track" check

Realize this is general, but was told to let it rip

**Comment by BenGitsCode** [comment]
How have you tried using those so far? What's your current understanding of those now?

**Comment by jordanallain** [comment]
do you have a function that uses `event` in it? if so, try logging event.target to the console to get a better idea of what it represents.

**Comment by noobiwankenoobi** [comment]
I have something that looks like this, mostly borrowed/altered from the auth section:

```
const onUpdateGameBoard = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.updateGameBoard(data)
    .then(ui.updateGameBoardSuccess)
    .catch(ui.updateGameBoardFailure)
}

const gameEventHandlers = () => {
  $('#game-cell').on('click', onUpdateGameBoard)
}

module.exports = {
  gameEventHandlers
}
```

**Comment by BenGitsCode** [comment]
Please format your code like this https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by noobiwankenoobi** [comment]
edited it^^

**Comment by noobiwankenoobi** [comment]
I will continue to use google, the game-api documentation, and my friends for this.
I'll figure it out. Thanks.

**Comment by noobiwankenoobi** [comment]
feelsbadman
