### ISSUE TITLE
Trouble writting JQuery

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/game-project#607]
I'm trying to create the game logic, but don't know how to do it with JQuery.
I'm not being able to make my Javascript code interact with the HTML on the browser.
I can think of the pseudo-code and even achieve my goals on console, just can't make a code so far.

**Comment by MicFin** [comment]
What file are you writing the code in?
What code are you writing?  What jQuery did you try?
How is it not working?  What is the error?

**Comment by jbeltrami** [comment]
I'm writing in a file that I created and exporting (and requiring) it to index.js.
I'm trying to modify the text that I have on a DIV element with an ID (as shown below). I tried to get the ID using JQuery, but it does not translate to something that I can work on. When I console log it, I get a function and an object that has a key with the array I want to access, but I can't run anything else after.

The error:
gameLogic.js:7 this is elementId: [object Object]
2017-04-12 13:29:50.868 gameLogic.js:11 
this is changeMessage: [object Object]
2017-04-12 13:29:50.868 index.js:26 

The code (index.jx):
```js
'use strict'

const setAPIOrigin = require('../../lib/set-api-origin')
const config = require('./config')

$(() => {
  setAPIOrigin(location, config)
})

const authEvents = require('./auth/events.js')

$(() => {
  authEvents.addHandlers()
})

// use require with a reference to bundle the file and use it in this file
// const example = require('./example')

// use require without a reference to ensure a file is bundled
require('./example')

// code starts here

const gameLogic = require('./gameLogic.js')

console.log(gameLogic)

// gameLogic.elementId[2].innerHTML = 'O'

module.export = authEvents
```

the code on gameLogic.js:
```js
'use strict'

// Where my code starts
// const elementId = document.getElementsByClassName('col-xs-4')

const elementId = $('.col-xs-4')
console.log('this is elementId: ' + elementId)

const changeMessage = $('#message')
changeMessage.innerHTML = 'Truco'
console.log('this is changeMessage: ' + changeMessage)

// const startGame = function () {
//   document.turn = 'X'
//   changeMessage(document.turn + ' always gets to start.  sorry bruh')
// }

// startGame()

module.exports = {
  elementId,
  changeMessage
  // startGame
}
```

**Comment by MicFin** [comment]
Show me da code :)

**Comment by jbeltrami** [comment]
I'm sorry, I submitted it by mistake. It's already updated  on the first post.

**Comment by MicFin** [comment]
You start with
```js
const gameLogic = require('./gameLogic.js')
```
now the `gameLogic` variable is an object
```js
{
  elementId: elementId,
  changeMessage: changeMessage
}
```
And you can do
```js
gameLogic.elementId // should be an array of elements from when you did $('.col-xs-4')
gameLogic.elementId[0] // should be the first element from when you did $('.col-xs-4')
gameLogic.changeMessage // should be the element from when you did $('#message')
```
Is that what you expected?

**Comment by MicFin** [comment]
Also,
```js
const changeMessage = $('#message')
```
Now `changeMessage` is a jQuery object of the HTML element with an ID of message.
It is not a javascript object so you do not want to do `changeMessage.innerHTML = 'Truco'`

**Comment by jbeltrami** [comment]
I'm sorry, but I still don't get it. 
I tried to set changeMessage as a function:
```
const changeMessage = (txt) => {
  $('#message').val(txt)
}
```

tried to run this:
```
// code starts here

const gameLogic = require('./gameLogic.js')

console.log(gameLogic)
gameLogic.changeMessage('Text goes here')
console.log('This is my changeMessage: ' + gameLogic.changeMessage)

// gameLogic.elementId[2].innerHTML = 'O'
```
And nothing happened on my page.

this is my HTML file, with the div ID message:
```
  <div id="message">TEST</div>

      <div id="container">
        <div class="row">
          <div class="col-xs-4" data-id="0"></div>
          <div class="col-xs-4" data-id="1"></div>
          <div class="col-xs-4" data-id="2"></div>
        </div>

        <div class="row">
          <div class="col-xs-4" data-id="3"></div>
          <div class="col-xs-4" data-id="4"></div>
          <div class="col-xs-4" data-id="5"></div>
        </div>

        <div class="row">
          <div class="col-xs-4" data-id="6"></div>
          <div class="col-xs-4" data-id="7"></div>
          <div class="col-xs-4" data-id="8"></div>
        </div>
      </div>

```

**Comment by MicFin** [comment]
Come to the kitchen, we can look together.

**Comment by jbeltrami** [comment]
Thank you.

I was using the wrong method on JQuery. The correct way to write it would be:

```
const changeMessage = (txt) => {
  let element = $('#message')[0]
  $(element).text(txt)
}
```
