### ISSUE TITLE
Checkpoint Touchbase

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/game-project#609]
Current step: I am currently building the game logic in pseudo code  in a game.js file. 
Goal: Receive feedback on structural set up so far.

**Comment by MicFin** [comment]
Please share the game logic psuedocode here 👍

**Comment by BenGitsCode** [comment]
Any updates here?

**Comment by kellye2010** [comment]
Hi Mike/Ben, thinking through more on my own.
Should I go ahead and close this?

**Comment by BenGitsCode** [comment]
If you'd like. I wanted to see your pseudo code to make sure you were on a good path. If you feel like you're working through it well on your own, and you're answering your own questions to satisfaction, it's okay to close this issue. (just don't hesitate to open another!)

**Comment by Jcornmanhomonoff** [comment]
@kellye2010 post any code that you have questions on for your game logic if you would like more specific help 🙃

**Comment by benjimelito** [comment]
Let me know if you are having any issues with following the structure of the `auth` file

**Comment by kellye2010** [comment]
Hi Ben,
Below is what I have so far for my clickSquare event. I set the function to console.log "Hello, World", but I do not see this message when clicking a button in the UI. I am not able to get my events to attach to my board or receive a message in the console. Is there anything you see below that I should take a closer look at? Or is there a different area in my project files I need to 'require' to do this?

```js
'use strict'
const clickSquare = function (event) {
  console.log('Hello, World!')
  event.preventDefault()
  alert('Hello, World!')
}
const addHandlers = () => {
  $('.game-board').on('click', clickSquare)
}

module.exports = {
  addHandlers
}
`
Please help :(

**Comment by MicFin** [comment]
In your `index.js` you should require that file and save it as a variable so you can call `yourVariable.addHandlers()`

**Comment by kellye2010** [comment]
Ive required my game.js logic file into my index.js file. In the console when I run `clickSquare.addHandlers();`
I receive the error message below
```
VM6544:1 Uncaught ReferenceError: clickSquare is not defined
    at <anonymous>:1:1
```

**Comment by kellye2010** [comment]
Update:
Ive required my events.js logic file into my index.js file. In the console when I run clickSquare.addHandlers();
I receive the error message below

VM6544:1 Uncaught ReferenceError: clickSquare is not defined
    at <anonymous>:1:1

**Comment by MicFin** [comment]
Please share your `index.js` and the `events.js`

**Comment by kellye2010** [comment]
Please see below:

events.js
```js
'use strict'

// const getFormFields = require(`../../../lib/get-form-fields`)
//
// const api = require('./api')
// const ui = require('./ui')
// const game = require('./game')

const clickSquare = function (event) {
  console.log('Hello, World!')
  event.preventDefault()
  alert('Hello, World!')
  // api.clickSquare()
  //   .then(ui.validSquare)
  //   .catch(ui.invalidSquare)
}

const addHandlers = () => {
  $('.square').on('click', clickSquare)
}
//
module.exports = {
  clickSquare,
  addHandlers
}

```




index.js
```js
'use strict'

// user require with a reference to bundle the file and use it in this file
// var example = require('./example');

// load manifests
// scripts
require('./assets/scripts/index.js')

// styles
require('./assets/styles/index.scss')

// logic
require('./assets/scripts/game/events.js')
```

**Comment by MicFin** [comment]
Please share the `/assets/scripts/index.js` file.  We want to `require` your `events.js` in the  `/assets/scripts/index.js` no in the high level `index.js`

**Comment by MicFin** [comment]
In your `events.js` you do not need to export both `clickSquare` and `addHandlers`
```js
module.exports = {
  clickSquare,
  addHandlers
}
```
This is because `addHandlers` already has `clickSquare` as a callback to the click event.  So you can just export 
```js
module.exports = {
  addHandlers
}
```

**Comment by kellye2010** [comment]
I tried both. 
BUT
I was using the project index.js file, not the assets/scripts/index.js file. I will try this now.

**Comment by kellye2010** [comment]
THIS works!

**Comment by MicFin** [comment]
Victory!!

We can close this issue now and when you run into something else, just open a new one.

**Comment by kellye2010** [comment]
Will do, thanks!
