### ISSUE TITLE
I'm trying to show an item for a short duration. Whose visibility is set to hidden

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#61]
I've tried to use both show() and css() with a timer. Show doesnt work at all. I can get css to change the attribute, but I can't figure out how to set it back with a timer. Below is the code I have tried:

`$('h3').show('8s');`

`$('h3').css('visibility', 'visible');
      setTimeout($('h3').css('visibility', 'visible'), 10);
    }
`

``$('h3').css('visibility', 'visible');
      h3.setTimeout($('h3').css('visibility', 'visible'), 10);
    }
`

**Comment by laurenfazah** [comment]
Check the jQuery docs on `show` to see what CSS it is actually manipulating vs what you are using. They may seem similar, but there are differences.

Also, look into what format you can send time with `show` as a setter.
