### ISSUE TITLE
[Requirements Questions] - Single Page Application

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/game-project#610]
In the requirements it says my app must be a single page application.

Can I present the UI/Design however I want as long as the page does not refresh and I fulfill all other listed requirements?

Do I need to present the user with distinct screens/views? Can I just hide and show elements?

**Comment by MicFin** [comment]
You can hide and show if you would prefer.  But at no point should the page refresh.

**Comment by aprilsourz** [comment]
Thank you,

I'm going to hide and show for now. I'm more comfortable with that. If I have time tomorrow I will experiment with routing for different views.
