### ISSUE TITLE
.toggle?

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/game-project#611]
Can I use use toggle to alternate between 'X' and 'O'

current click event is:
```
const clickEvent = function () {
  $('.box').on('click', function () {
    $('<p>X</p>').appendTo(this)
  })
}
```
Can I incorporate this somehow:
```
$( "td" ).toggle(
  function() {
    $( this ).addClass( "selected" );
  }, function() {
    $( this ).removeClass( "selected" );
  }
);
```

**Comment by benjimelito** [comment]
So `toggle` is good for adding and removing classes like in the example, but I feel like it would not be the best option for toggling between `x` and `o`. This is due to the fact that it requires clicking on the same element twice in order to change which function is executed.

**Comment by eliottenos** [comment]
ok thanks,
ive hit a dead end moving on from the first click event, moving to alternating and incorporating an array for the boxes

**Comment by benjimelito** [comment]
I would think about some sort of conditional statement that checks to see whose turn it is, and depending on this either adds an `x` or an `o`. Theres a few ways you could determine which player's turn it is, but if you're still stuck I could come by and point you in the right direction.

**Comment by eliottenos** [comment]
yep, guidance would be appreciated!

**Comment by benjimelito** [comment]
Sure, one sec

**Comment by eliottenos** [comment]
added an if or else statement to alternate between 'X' and 'O'

**Comment by eliottenos** [comment]
```
let turn = 'X'

const clickEvent = function () {
  $('.box').on('click', function () {
    if (turn === 'X') {
      $('<p>X</p>').appendTo(this)
      turn = 'O'
    } else {
      $('<p>O</p>').appendTo(this)
      turn = 'X'
    }
  })
}
```
