### ISSUE TITLE
How do I store the ID of the current game?

### ISSUE THREAD

**Issue by joebelmonte** [ga-wdi-boston/game-project#612]
Hi, I am able to post a new game but I want to store the ID of the game that is created in new variable.  I need to do this so that I can patch to the appropriate game at the conclusion of game play.  Here is the code I have for the post:

```js
const postGame = () => {
  console.log('inside postGame')
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
This seems to be working correctly, but again I can't seem to figure out how to access the ID of the game that is created...

**Comment by benjimelito** [comment]
I would think about storing the game data somewhere AFTER it has been created. Creating a game should return the game's data, including the ID. If you store this data somewhere, you will be able to access it in order to determine the ID that you need.

**Comment by joebelmonte** [comment]
Sorry Ben, I hear what you are saying but I think that's actually what my question is.  I know that it returns data that includes the ID - I can't figure out where that goes or how to store it...

**Comment by benjimelito** [comment]
Ok cool, let me come over and check out what you have right now

**Comment by joebelmonte** [comment]
For reference, this worked: 

```js
const startGame = function () {
  api.postGame()
    .then(ui.postGameSuccess)
    .catch(ui.postGameFailure)
}
```

Plus:

```js
const postGameSuccess = (data) => {
  store.game = data.game
}
```

Thanks for the help!!
