### ISSUE TITLE
Game API Patch request - which is bonus?

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/game-project#613]
@MicFin 

Hi Mike, this is a question related to what we talked about earlier today. 

In the game api documentation, it mentions two types of patch requests, where one is for join a game as player 'o', and the other is to update a game's state. It's not clear to me which of these is a requirement or bonus (or are they both requirements)?

from the documentation, does "update game" refer to both (1) joining as player 'o' and (2) track/update a game's state?

```
Game API

 Review query-ajax-post
 Create Game (curl then web app)
 Update Game (curl then web app)
 Get Games (curl then web app)
 Get a Game (curl then web app)
```

Thank you in advance

**Comment by jordanallain** [comment]
the bonus is to have another player be able to join. updating the games state is required.

**Comment by nriser** [comment]
@jordanallain 

Great, thank you for your response!!!
