### ISSUE TITLE
Arrays for winning conditions not firing

### ISSUE THREAD

**Issue by mangoceylon** [ga-wdi-boston/game-project#615]
I'm using for each to discover if one of my player's arrays have met the winning condition:

`const playerXWins = function () {
  $.each(winner, function (index, value) {
    if (playerX.includes(value[0]) &&
    playerX.includes(value[1]) &&
    playerX.includes(value[2])) {
      return true
    } else {
      return false
    }
  })
}`

The idea is that the array returns true when the condition is met, and false if it hasn't been yet.

I'm calling the function like so:

`if (playerXWins()) {
      console.log('Player X wins')
      return
    }`

I'm trying to include more console logs to help check logic throughout, but not getting much returned.

**Comment by benjimelito** [comment]
Am I correct in assuming that `playerX` is an array? If so, I would look at how to use the `.includes` method, which I think might be a potential source of this bug.

**Comment by mangoceylon** [comment]
Yes, it is an array. I'll look into `.includes` more.

**Comment by mangoceylon** [comment]
Pretty stuck here @benjimelito
