### ISSUE TITLE
Gameboard issue with win condition logic

### ISSUE THREAD

**Issue by TronB** [ga-wdi-boston/game-project#616]
I'm currently in the process of writing the logic for the win conditions. I was thinking of writing if statements that checks each row and column by first comparing the string values in the top row. If they all match it'll give an alert message. 

When the page first loads it gives the alert message(which I'm assuming is because the browser is reading all array values being the same since there is nothing in it). But when I click to fill the top row with matching x/o values, the alert doesn't pop up. I'm not quite sure where to go from here.
```js
const gameBoard = []
let turnCount = 1
$(document).ready(function () {

  const onClickCell = function (evt) {
    // saves the position on the board that was clicked
    const positionOnBoard = $(evt.target).data('id') // 1 or 2, etc

    // assigns an x or o based on the turn and only if cell isn't occupied with a string value
    if (turnCount % 2 === 1 && typeof gameBoard[positionOnBoard] !== 'string'){
      gameBoard[positionOnBoard] = 'x'
      turnCount++
    }
    else if (turnCount % 2 === 0 && typeof gameBoard[positionOnBoard] !== 'string') {
      gameBoard[positionOnBoard] = 'o'
      turnCount++
    }

    // add x or o to the position on the board
    $(evt.target).text(gameBoard[positionOnBoard])
    //debugger
  }
//doesn't work properly
  const winningCombo = function(){
    if (gameBoard[0] === gameBoard[1] && gameBoard[1] === gameBoard[2])
    {
      alert('Mr. PM steal yo gurl')
    }
  }
winningCombo()

  $('.game-board td').on('click', onClickCell)
})
```

**Comment by benjimelito** [comment]
Are you checking to make sure that `gameBoard` is being filled up with the characters you expect? I would also recommend using `console.log` statements rather than alerts, just so you can see the order of things and have the results saved.

**Comment by MicFin** [comment]
Does `winningCombo()` get called when you expect?  Look closely at your indentation.  

All of this below, is NOT inside of the `onClickCell` function so it only runs one time when the page loads and not when someone clicks.
```js
const winningCombo = function(){
    if (gameBoard[0] === gameBoard[1] && gameBoard[1] === gameBoard[2]) {
      alert('Mr. PM steal yo gurl')
    }
}
winningCombo()
```

**Comment by jordanallain** [comment]
any updates on this @TronB

**Comment by TronB** [comment]
I tried playing around with this to see if I could get the win conditions to respond properly so far I have

```
$(document).ready(function () {
  const gameBoard = []
  let turnCount = 1
  const onClickCell = function (evt) {
    // saves the position on the board that was clicked
    const positionOnBoard = $(evt.target).data('id') // 1 or 2, etc

    // assigns an x or o based on the turn and only if cell isn't occupied
    if (turnCount % 2 === 1 && typeof gameBoard[positionOnBoard] !== 'string') {
      gameBoard[positionOnBoard] = 'x'
      console.log(gameBoard)
      turnCount++
    }
    else if (turnCount % 2 === 0 && typeof gameBoard[positionOnBoard] !== 'string') {
      gameBoard[positionOnBoard] = 'o'
      console.log(gameBoard)
      turnCount++

    }
    winCondition()
    // add x or o to the position on the board
    $(evt.target).text(gameBoard[positionOnBoard])
  }

  function winCondition () {
    if (gameBoard[0] === gameBoard[1] && gameBoard[1] === gameBoard[2]) {
      console.log('top row')
    }
//this line here breaks the logic
    else if (gameBoard[3] === gameBoard[4] && gameBoard[4] === gameBoard[5]) {
      console.log('mid row')
    }
}

  // win combination logic
  $('.game-board td').on('click', onClickCell)
})
```

I tried to console log the win conditions to see if it would act as expected. The first if statement alone works fine, but then when adding the second statement it will console log regardless of where I click

Deleting the else if statement doesn't seem to fix the problem either, it will still console log.

**Comment by jordanallain** [comment]
Looks like you have a LOT going on inside that document.ready function. I would try to remove some of those function declarations and put them in the global scope.

**Comment by TronB** [comment]
thanks for the followup
