### ISSUE TITLE
Can't get click event to work JQuery

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/game-project#618]
Trying to figure out how to trigger my click event. Read the documentation and still can't figure out why it is not working.

this is what I have so far:
```js
'use strict'

// Where my code starts
// const elementId = document.getElementsByClassName('col-xs-4')
let turn = 'X'

const boardObj = $('.col-xs-4')

const changeMessage = (txt) => {
  const element = $('#message')[0]
  $(element).text(txt)
}

const startGame = () => {
  changeMessage(turn + ' is the first player')
}
// code works until this line

// click event that takes an element of boardObj and reassings its value to
// whatever the variable turn is at the moment.
// This function needs to call nextMove, passing in the index at the end.

const changeBoard = () => {
  $('boardObj[0]').text(turn)
}

$('boardObj[0]').on('click', changeBoard)
// console.log($(boardObj[0]).text(turn))
```

My browser load without a problem, but it does not do anything.
When I try to console.log it, the function will work and the value gets reassigned.

**Comment by benjimelito** [comment]
I would look at the way you're accessing the element that you want to click on. Would you mind also pasting in the HTML that you used to create your game board?

**Comment by jbeltrami** [comment]
I'm sorry, I'm not sure that I understand what you're saying.
If I console.log my `boardObj[0]` it is going to log the div I'm trying to access. And if I uncomment the console.log that I hid, it is even going to change the element in the board.

Here is my HTML:
```
<div id="container">
        <div class="row">
          <div class="col-xs-4" data-id="0"></div>
          <div class="col-xs-4" data-id="1"></div>
          <div class="col-xs-4" data-id="2"></div>
        </div>

        <div class="row">
          <div class="col-xs-4" data-id="3"></div>
          <div class="col-xs-4" data-id="4"></div>
          <div class="col-xs-4" data-id="5"></div>
        </div>

        <div class="row">
          <div class="col-xs-4" data-id="6"></div>
          <div class="col-xs-4" data-id="7"></div>
          <div class="col-xs-4" data-id="8"></div>
        </div>
      </div>
```

**Comment by MicFin** [comment]
You are trying to accomplish too many steps at once.

1.  Use jQuery to select an element(s) in the DOM
2.  Use jQuery to add a click event to the selected element(s)
3.  Call the `changeBoard` function when the click event is triggered

Focus on step 1 first.  Are you selecting an element(s) from the DOM?  `console.log()` you jQuery selector.
```js
$('boardObj[0]')
```

**Comment by jbeltrami** [comment]
I'm really sorry, but I still don't get it.

this is what I got so far:

1. Use jQuery to select an element(s) in the DOM - used console.log on my object and this is what I got back: `<div class="col-xs-4" data-id="0"></div>` (I think this is what I'm trying to work on)

2. Use jQuery to add a click event to the selected element(s) - wrote this chunk 
```
$('boardObj[0]').on('click', function () {
  alert('success')
})
```
And nothing happens. I don't get any kind of error/message to guide me. I've checked the documentation and it seems to be right, but there is no "click". If instead of the function, I write:
```
$('boardObj[0]').on('click', console.log('success'))
```
It is going to console.log right away, without the clicking.

I think I'm focusing on the wrong thing, but I don't know exactly what to focus on.

**Comment by jbeltrami** [comment]
Was trying to make Javascript and JQuery to interact out of order.
Created the button using `this` and that assumes in which square of the board I'm clicking automatically.

Final click event code looks like this:
```

$('.col-xs-4').on('click', function () {
  $(this).text(turn)
  changeTurn()
})
```
