### ISSUE TITLE
Display question - get game and get games

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/game-project#619]
Hi,
I can do the get game and get games function, but currently it just prints them in a box after having turned them into a string. Is that okay presentation? 
Thanks,

**Comment by benjimelito** [comment]
Do you mean for retrieving previously played games? If so...screenshot?

**Comment by jordanallain** [comment]
update @Maggicorp ?

**Comment by Maggicorp** [comment]
Hey, I had some conversations and am currently printing the data is a more readable format. Thanks.  Basically my question was just how should I format it and what should I display.  What I decided to do is show game id and if the game was completed in the get games section, and the outcome (who won, was it a tie?) in the get one game section.
