### ISSUE TITLE
Difference between GET index and GET show

### ISSUE THREAD

**Issue by noobiwankenoobi** [ga-wdi-boston/game-project#620]
What is the difference between:

GET	/games/:id	games#show

GET	/games	games#index

I took this directly from the documentation, and don't quite get the difference.

**Comment by benjimelito** [comment]
In short, making a GET request to `games` with an `:id` parameter will return you a single game, whereas making a GET request to `games` without an `:id` parameter will return you ALL the games in the database for a user

**Comment by MicFin** [comment]
`The index action is a GET that retrieves all the games associated with a user. `
https://github.com/ga-wdi-boston/game-project-api#index

`The show action is a GET specifying the id of the game to retrieve`
https://github.com/ga-wdi-boston/game-project-api#show

**Comment by noobiwankenoobi** [comment]
thanks, I looked at both of those in the documentation and I guess I read them wrong.
