### ISSUE TITLE
Unable to patch game. 

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/game-project#624]
I'm trying to patch the game to allow player "o" to join. So far I keep getting 400 bad request returns. 
The first thing I'm doing is creating a game. After creating the game using

```
const createGameSuccess = (data) => {
  $('#playarea').toggle()
  store.game = data.game
  console.log(store.game)
  console.log(store.game.id)
}

```
I get

```
Object {id: 30, cells: Array(9), over: false, player_x: Object, player_o: null}
30
```
in my log.  This makes me think I'm using the right id and url reference to patch the game.
The code I'm using for the actual patch is

events.js
```
const onJoinIn = function (event) {
  event.preventDefault()
  api.joinIn(event)
    .then(ui.joinInSuccess)
    .catch(ui.joinInFailure)
}
```
api.js
```
const joinIn = () => {
  console.log('join in')
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {}
  })
}
```
ui.js
```
const joinInSuccess = () => {
  console.log('A new challenger approaches')
}

const joinInFailure = () => {
  console.log('Not on my court!')
}
```
When I click the button for player two to join I get a 400 error and
My console log returns "not on my court" which is my on failure message.

**Comment by MicFin** [comment]
I just want to verify, have you met all of the requirements before trying to have a `playerO` join?

**Comment by Anddrew914** [comment]
No, when working on it I thought it was part of the main requirements.
