### ISSUE TITLE
What is the purpose of the game API?

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/game-project#626]
I know this question may seem a little broad in scope, but I am not sure why we need to hook up the game API. We have learned how to interact with it, and I understand its value in authentication, by why does it need to interface with the game engine? Discounting further practice with a concept which will grow more and more central in the next couple of units, if we are not pursuing the bonus (where it seems essential), what practical benefit does the API provide to the project?

**Comment by MicFin** [comment]
2 quick practical advantages
1.  It gives you an access point to a database where you can save users and their emails, passwords, etc.
2.  It gives you an access point to a database where you can save games, the status of games, the user who played a game, etc.

**Comment by d00medman** [comment]
Cool, so would it be reasonable to say that the four methods we are creating are going to provide these practical advantages?

**Comment by MicFin** [comment]
Yes 
## API end-points

| Verb   | URI Pattern            | Controller#Action |
|--------|------------------------|-------------------|
| POST   | `/sign-up`             | `users#signup`    |
| POST   | `/sign-in`             | `users#signin`    |
| DELETE | `/sign-out/:id`        | `users#signout`   |
| PATCH  | `/change-password/:id` | `users#changepw`  |
| GET    | `/games`               | `games#index`     |
| POST   | `/games`               | `games#create`    |
| GET    | `/games/:id`           | `games#show`      |
| PATCH  | `/games/:id`           | `games#update`    |
| GET    | `/games/:id/watch`     | `games#watch`     |

https://github.com/ga-wdi-boston/game-project-api#api-end-points
