### ISSUE TITLE
Access-Control-Allow-Origin 400 error on github.io pages

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/game-project#627]
I used grunt deploy to push my latest build to GitHub pages but was receiving an error when trying to use the API to create a new user.

The code works locally. The console logs are below with the access control message.

```js
Failed to load resource: the server responded with a status of 400 (Bad Request)

pjliddy.github.io/:1 
XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-up. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://pjliddy.github.io' is therefore not allowed access. 
The response had HTTP status code 400.

application.js:677 signUpFailure():
Object {readyState: 0, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
signUpFailure @ application.js:677
mightThrow @ vendor.js:3693
process @ vendor.js:3761
```

**Comment by MicFin** [comment]
Can you also include the entire AJAX call?  Does your CURL script for this action work when made to the API?  If so (or not) include that and the response too.

**Comment by pjliddy** [comment]
This is all the code I could identify that touches the ajax call:

This is the contents of config.js:
```
'use strict'

const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com',
    development: 'http://localhost:4741'
  }
}

module.exports = config
```
This is the eventHandler that submits the form:
```
const onSignUp = function (event) {
  console.log('onSignUp')

  const data = getFormFields(this)
  event.preventDefault()

  console.log(data.credentials)

  if (data.credentials.email.length === 0) {
    views.message('email required')
  } else if (data.credentials.password.length === 0) {
    views.message('password required')
  } else if (!data.credentials.password_confirmation.length === 0) {
    views.message('password confirmation required')
  } else if (data.credentials.password !== data.credentials.password_confirmation) {
    views.message('passwords must match')
  } else {
    api.signUp(data)
      .then(ui.signUpSuccess)
      .catch(ui.signUpFailure)
  }
}
```
This is the jQuery ajax call being made:
```
const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```
This is the data object that gets passed into the POST to the local instance of the API:
```
{
  email: "user9@mail.com", 
  password: "pass", 
  password_confirmation: "pass"
}
```
Here's the object returned by the local instance of the API:
```
user: Object
  email: "user9@mail.com"
  id: 7
```
Here's a curl script run from my desktop that reaches the API and gets a response:
```
#!/bin/bash

curl --include --request POST https://ga-wdi-boston.herokuapp.com/sign-up \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "user@gmail.com",
      "password": "pass",
      "password_confirmation": "pass"
    }
  }'
```
This is the response returned to my terminal:
```
HTTP/1.1 201 Created
Server: Cowboy
Date: Thu, 13 Apr 2017 00:54:15 GMT
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Etag: W/"1207951599646bd916d322415f1be043"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 8eb3e7ca-fd5e-415c-88aa-622985383847
X-Runtime: 0.179389
Vary: Origin
Transfer-Encoding: chunked
Via: 1.1 vegur

{"user":{"id":106,"email":"user@gmail.com"}}
```

**Comment by MicFin** [comment]
What is `data` when you `console.log(data)` and send it to the API?

Is it what the API expects?
```
{
  "credentials": {
    "email": "an@example.email",
    "password": "an example password",
    "password_confirmation": "an example password"
  }
}
```
https://github.com/ga-wdi-boston/game-project-api/blob/master/README.md#signup

**Comment by pjliddy** [comment]
Here's what the object that gets sent with the POST looks like when it gets output to the console. It doesn't print in JavaScript format, but the structure looks right. It's created using the getFormFIelds() function. The local version is returning the proper user object with email and id.
```
Object {credentials: Object}
  credentials: Object
    email: "user8@mail.com"
    password: "pass"
    password_confirmation: "pass"
    __proto__: Object
  __proto__: Object
```

**Comment by akgoode** [comment]
Hi PJ I'm not a consultant but I noticed this issue.  I think you should try using a different URL for your production API.  My tic-tac-toe game and most other people's I've looked at use `    production: 'https://aqueous-atoll-85096.herokuapp.com',` as their production URL.  Worth a shot.

**Comment by MicFin** [comment]
@pjliddy come to the kitchen, let's take a look at this together.

**Comment by pjliddy** [comment]
Solution: quotes were missing from around the name attribute value in the html for the credentials form:
```
name="credentials[email]"
```

**Comment by pjliddy** [comment]
Needed to change url to https://aqueous-atoll-85096.herokuapp.com as well
