### ISSUE TITLE
Game Creation Error

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#63]
I'm unsure from the documentation if a user ID is required to create a game. I want to initialize a new game right when the page loads. So far I am using:

``` javascript
'use strict'


const createGame = (success,failure) =>{
  $.ajax({
    method: "POST",
    url: 'http://tic-tac-toe.wdibos.com/' + 'games',
  })
  .done(success)
  .fail(failure);
}



module.exports = {
  createGame,
}
```

I am unsure if I need a header to create a game.
And for some reason the code tags are not working in the issues =/

**Comment by louarnos** [comment]
nevermind. I need a user to create a game

**Comment by RealWeeks** [comment]
@louarnos If you managed to resolve this please close.
