### ISSUE TITLE
Quick clarification on scope

### ISSUE THREAD

**Issue by joebelmonte** [ga-wdi-boston/game-project#631]
Hi, I have a quick clarification question on scope.  I'm wondering which of the following is true:

1. A user should be able to play ONLY when they are logged in.
2. A user should be able to play whether they are logged in or not.
3. A user should be able to play when they are logged in.  It's optional whether they should also be able to play when they are not logged in.

Thanks,

Joe

**Comment by jordanallain** [comment]
1. 👍

**Comment by joebelmonte** [comment]
Thanks.
