### ISSUE TITLE
Game update patch replacing data instead of updating it. 

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/game-project#632]
Whenever I send my game update data to the rails server it replaces the data instead of patching it. I thought that patch was designed to update data, so I'm not sure what needs to be.

```
    'game': {
        'cell': {
          'index': idnumber,  my idnumber is the index of the board I clicked on, it's the same variable that is successfully used to compare win conditions.  
          'value': currentplayer alternates each turn between x and o.
        },
        'over': over
      }
    }
```

I'm expecting to receive an updated board each turn, but instead it just replaces the array with the new value 

```
Object {game: Object}
game
:
Object
cell
:
Object
index
:
4
value
:
"o"
__proto__
:
Object
over
:
false
__proto__
:
Object
__proto__
:
Object
```

Like so. That's the console log of the object, it just turned index into 4 instead of updating the array.

**Comment by jordanallain** [comment]
have you double checked the API README to see what a successful PATCH request will send back as a response.

**Comment by Anddrew914** [comment]
Yeah it's telling me that if I send a single number (the array  number)  and the player (x or o) then I'll get back an updated array with x or o placed in the according index location. Instead I"m getting the index value I sent, as a number, and x or o coming right back .

**Comment by jordanallain** [comment]
Can you post the function that makes the AJAX request?

**Comment by benjimelito** [comment]
Sounds like maybe this is resolved?

**Comment by Anddrew914** [comment]
Yeah I took a different route so now I'm stuck elsewhere! I'll post another issue if necessary

**Comment by benjimelito** [comment]
Yup, please close this on out and post an issue that describes what you're working on now
