### ISSUE TITLE
click event

### ISSUE THREAD

**Issue by JLisaW** [ga-wdi-boston/game-project#634]
I'm having a hard time figuring out the next step for the click event.  I've added the handlers but I think i'm missing a step somewhere.  This is what I have so far, I'm not sure if it's correct

```
const onClickSquare = function (event) {
  event.preventDefault()
  gameApi.click()
  .then(ui.onClickSquareSuccess)
  .catch(ui.onClickSquareFailure)
```

```
const addHandlers = () => {
  $('#square 0').on('click', onClickSquare)
  $('#square 1').on('click', onClickSquare)
  $('#square 2').on('click', onClickSquare)
  $('#square 3').on('click', onClickSquare)
  $('#square 4').on('click', onClickSquare)
  $('#square 5').on('click', onClickSquare)
  $('#square 6').on('click', onClickSquare)
  $('#square 7').on('click', onClickSquare)
  $('#square 8').on('click', onClickSquare)
}
```

**Comment by jordanallain** [comment]
what are you doing with that `addHandlers` function? is it somewhere else in your code?

**Comment by JLisaW** [comment]
I have this in the index.js

```
$(() => {
  authEvents.addHandlers()
  gameEngineEvents.addHandlers()
})
```

**Comment by jordanallain** [comment]
okay cool. so lets simplify it a bit to see if the click handlers are working. in your onClickSquare function, if you put a console.log as the first line, see if that gets printed to the console when you click on one of the squares.

**Comment by JLisaW** [comment]
it doesn't print to the console and i'm not sure what to do next.  i've tried to name each square and it doesn't work either

**Comment by Jcornmanhomonoff** [comment]
If it's not logging anything then it's not hitting that function. Are you calling the function anywhere?

**Comment by Jcornmanhomonoff** [comment]
@JLisaW status?
