### ISSUE TITLE
Production environment does not load properly

### ISSUE THREAD

**Issue by sstone72389** [ga-wdi-boston/game-project#636]
I cannot get my production environment to function properly. I am getting the follow error in the attached screenshot. 

I am using this code in my config file:

```
'use strict'

const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com',
    development: 'http://localhost:4741'
  }
}

module.exports = config
```

![screen shot 2017-04-13 at 9 51 57 am](https://cloud.githubusercontent.com/assets/25782275/25007585/00c54954-202f-11e7-9aee-e46c3347516b.png)

**Comment by jordanallain** [comment]
Did you read the error? Does that URL look correct?

**Comment by sstone72389** [comment]
It looks correct to me.

**Comment by MicFin** [comment]
Sounds like `gameLogic.js` is not being properly required in `index.js`

**Comment by BenGitsCode** [comment]
Please don't use screenshots. That error message can't be copied or easily read.

**Comment by jordanallain** [comment]
`https://sstone723 sstone72389.github.io/:1589.github.io/spencer-tic-tac-toe/assets/scripts/gameLogic.js` doesn't look correct to me

**Comment by sstone72389** [comment]
hmmmm I used an actual script tag rather than the requires....  I know thats not optimal but it isss linked properly. It works perfectly in my local environment... What is wrong with the link?

**Comment by MicFin** [comment]
I will come show you.

**Comment by sstone72389** [comment]
By wrapping my gameLogic.js code in a function called startGame and exported start game to index.js.

at the bottom of gameLogic.js:
```
module.exports = {
  startGame
}
```

at the top of index.js I required gameLogic:

```
const game = require('./gameLogic')
```

adding this to the document.ready function, also (within index.js as well)
```
game.startGame()
```
