### ISSUE TITLE
Patch not working properly

### ISSUE THREAD

**Issue by mangoceylon** [ga-wdi-boston/game-project#638]
When I use an ID with tons of history, the first patch request (first move) is completely filled out:

`"game":{"id":13,"cells":["x","o","x","o","x","o","x","x","x"],"over":false,"player_x":{"id":13,"email":"dh"},"player_o":null}}`

When I use a new player I get a 404.

A curl to request the history of the long account returns a list of games with no moves stored.

My patch code is within my core game engine javascript function:

`const update = {cell: {index: clickID, value: currentPlayer}}`

and after the function loops it is called like this:

`gameDelta({game: update})`

I also pass info about the game being over or not after each player moves, like so:

`update.over = true`

`update.over = false`

**Comment by benjimelito** [comment]
Would you mind posting the code for `gameDelta`? Also, what is the `url` that is giving you a 404 error?

**Comment by mangoceylon** [comment]
URL is: http://localhost:4741/games/43

Game Delta:

```
const gameDelta = function (data) {
  console.log(data)
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/games/' + store.user.id,
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: data
  })
}
```

**Comment by MicFin** [comment]
One issue might be that you are passing the `user` ID instead of the `game` ID as the end of your URL

**Comment by mangoceylon** [comment]
I was thinking that right after I pasted it in

**Comment by mangoceylon** [comment]
Yup, fixed.
