### ISSUE TITLE
+1 Increment function only executes once

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#64]
``` javascript
turns = 1;

const turnCount = function(){
  return turns++;
};

turnCount();
```

I have this in Repl.it and even though I'm hitting the Run button multiple times, it only returns "1" rather than continuing on to 2, then 3, etc.  There are no linter errors in Atom and I can't discern what I'm doing wrong from examples on the internet.

**Comment by susandaiute** [comment]
Oops! That's "Let turns=1".

**Comment by laurenfazah** [comment]
@susandaiute what is your objective here? Is it to increase `turns` value? If so, be aware of what Repl.it is _returning_ to you...

**Comment by susandaiute** [comment]
Yep, I want to increase the value of `turns`.  If that's a hint about "return" I'm definitely not getting it haha

**Comment by laurenfazah** [comment]
If your goal is to increase `turns`, it isn't necessary to return it. Repl.it is displaying to you the return of the **postfix** increment of `turns++`. It could be that the context of the REPL environment is distracting you from your objective (which you aren't far from).

**Comment by susandaiute** [comment]
So just ax `return`?

Which would leave it as:

`let turns = 1;

const turnCount = function(){
  turns++;
};

turnCount();`

**Comment by RDegnen** [comment]
REPL might not be the best place to test that

**Comment by laurenfazah** [comment]
It looks like that should give you what you want - test out by console logging `turns` to verify! And remember in Repl.it, every time you hit "run", it's running that script from the top...aka all variables are reset.

**Comment by susandaiute** [comment]
It works! Thanks Lauren!
