### ISSUE TITLE
How to resolve a 401 error

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/game-project#640]
I am currently implementing the create method of the game API. Upon testing, I received a 401 error from my rails server at 4741. This means that I do not have proper authorization to access the server. 

How am I to go about securing authorization, thus resolving this error?

**Comment by d00medman** [comment]
the result of my attempted AJAX call:

`POST http://localhost:4741/games/ 401 (Unauthorized)
send @ jquery.js:9566
ajax @ jquery.js:9173
create @ api.js:7
makeMove @ playGame.js:157
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
`

`
2017-04-13 11:47:07.758 jquery.js:9566 XHR finished loading: POST "http://localhost:4741/games/".`

My AJAX call:

`api.create(parseData())
    .then(ui.createSuccess)
    .then(ui.createFailure)`

The create method:

`const create = (data) => {

  return $.ajax({

    url: config.apiOrigin + '/games/',

    method: 'POST',

    data

  })

}`

the parseData method:

`const parseData = function () {

  const game = {

    id: games++,

    cells: board,

    over: isGameOver(),

    player_x: {

      id: games++,

      email: store.user.id

    },

    player_o: {

      id: games++,

      email: store.user.id

    }

  }

  return game

}`

**Comment by benjimelito** [comment]
Looks to me like you are missing the authorization portion of your POST call, let me know if you are having issues adding this in.

**Comment by jordanallain** [comment]
look back to our jquery ajax lesson on the books API, you should see how we fixed this issue.

**Comment by d00medman** [comment]
This worked. For clarification do I need to place an authorization header in any AJAX call used after I login?

Also, while my code works on both the rails server and manifests properly, my error catch method is firing for whatever reason. I do have it set to console.error, and it returns undefined (meaning it could not find an error). 

In my auth API events, I had prevent default on. Do you think my current error is a result of the absence of this call?

**Comment by jordanallain** [comment]
You need to place an authorization header in any AJAX call that requires it. The API documentation should help with this, but if you send a request that says Unauthorized, that is also a good indication.
