### ISSUE TITLE
Don't know where to start my create game API

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/game-project#642]
Don't understand what the instructions mean.
Tried to google what a POST with an empty body means, but didn't find anything to clarify.

**Comment by BenGitsCode** [comment]
Which instructions do you need help clarifying?

**Comment by jbeltrami** [comment]
I don't know which part of the POST is the body.

**Comment by BenGitsCode** [comment]
What did you google when searching for that?

**Comment by jbeltrami** [comment]
Multiple things:
"what is a post with an empty body curl"
"what is a curl body"
"what is url body"
"post request with empty body"

**Comment by jbeltrami** [comment]
Working on this.
Time box: 12:50

**Comment by jbeltrami** [comment]
Yeah, still stuck on this. Getting 401 Unauthorized, even after signin in.

**Comment by jbeltrami** [comment]
Nevermid! just figured it out! I had to pass in the token of my User.
Thanks for the help!
