### ISSUE TITLE
Get All Games 401 Unauthorized error

### ISSUE THREAD

**Issue by xiangcatherine** [ga-wdi-boston/game-project#643]
I have been getting a 401 Unauthorized error when running the curl request in my terminal.

I have the following code in my get-all-games.sh file 
```
#!/bin/bash

curl --include --request GET http://tic-tac-toe.wdibos.com/games \
  --header "Authorization: Token token=$TOKEN" \

echo
```

I typed the following in my terminal:

`
$ TOKEN=BAhJIiUwM2FmYjkxNGI0YzQyZTFmMGFiZDU0OWE3YTU2ZTdmYwY6BkVG--e26ac50630eb47b786c3aefb08afd0208ca9ee75 sh scripts/get-all-games.sh
`

I also signed in before getting the token, so I'm pretty sure I have the right token. Any thoughts?

**Comment by MicFin** [comment]
Please use `https://aqueous-atoll-85096.herokuapp.com` for your production API URL and not `http://tic-tac-toe.wdibos.com`

**Comment by xiangcatherine** [comment]
Changed code to this: 

```
#!/bin/bash

curl --include --request GET https://aqueous-atoll-85096.herokuapp.com/games \
  --header "Authorization: Token token=$TOKEN" \

echo
```

Still getting the same 401 Unauthorized error.

**Comment by xiangcatherine** [comment]
Changing the URL to my local host solved the problem!

```
#!/bin/bash

curl --include --request GET http://localhost:4741/games \
  --header "Authorization: Token token=$TOKEN" \
  --data ''

echo

```

Thank you!
