### ISSUE TITLE
Cannot find module 'assets/scripts/auth/api.js'

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/game-project#644]
I'm trying to require my API and UI folders into my JS engine so I can update the game at each click and I'm getting this above error. I've tried several different file paths.

**Comment by benjimelito** [comment]
If the path is correct, this is most likely due to the fact that there is an error in that file. Do you have any linter errors there?

**Comment by Anddrew914** [comment]
No, no linter errors, and it was all working right before I added that require to the engine file.

**Comment by Anddrew914** [comment]
A one on one would be great, because I've tried 3 or 4 different paths to solving this one problem and every time I run into some thing or another. I think having clarity on the nature of require/export, and on the API in general would go a long way to letting me trouble shoot these issues more effectively.

**Comment by MicFin** [comment]
Come to kitchen we can look together

**Comment by MicFin** [comment]
Please close this and describe the solution

**Comment by Anddrew914** [comment]
Oh sorry! 
I did indeed type the file path incorrectly. I forgot that the ./ is important because it let's the computer know to start from the current location
