### ISSUE TITLE
Trying to reset input values after sign out

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/game-project#646]
My game is holding onto all the input values in the sign in field and I can't figure out how to use them.  I tried using the JQuery selector for the form and using the function .text(' ') to add empty text, but that had no effect. Then I tried   
```
$('.clear-input').reset()
```
but that threw an error message and said that the above code is not a function.  I also looked at old issues but couldn't find any questions along this line.

**Comment by MicFin** [comment]
You are close.

Two strategies
1.  Reset each input individually https://stackoverflow.com/questions/6364289/clear-form-fields-with-jquery
2.  Reset the entire form https://stackoverflow.com/questions/6653556/jquery-javascript-function-to-clear-all-the-fields-of-a-form

I prefer option 2.

**Comment by Maggicorp** [comment]
Got it.  Using the trigger('reset') function worked.
