### ISSUE TITLE
[requirements] - Game api

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/game-project#647]
Just want to double check. The game api features are all required except for watch and join a game as player 'o'?

**Comment by MicFin** [comment]
Yes, but if you want to be more specific please do

**Comment by aprilsourz** [comment]
Here's my understanding of the requirements.

Each new game gets stored on the server, on every move the the current game gets updated. When the game ends by win or draw its stop getting updated and is marked as completed. The next game the user plays will create new game on the server

I have to have a button that when clicked will display all the games the user has played and the result of each game. As well as the total number of wins and losses for X and O and total number of draws. 

I also need to have a button with an input that will get one game by entering the ID number and display its outcome.

**Comment by aprilsourz** [comment]
Do i have to display the Incompleted games?

**Comment by MicFin** [comment]
1.  I have to have a button that when clicked will display all the games the user has played and the result of each game. As well as the total number of wins and losses for X and O and total number of draws.
> Yes, but you could simplify and just have a message that says "You have played 5 games"
2.  I also need to have a button with an input that will get one game by entering the ID number and display its outcome.
> Yes, and it doesnt have to display anything more than "You won/lost/did not finish game 5"
3. Do i have to display the Incompleted games?
>Not necessarily, they can just be part of the "You played 5 games"

**Comment by tvcrawley** [comment]
For game stats, **from the game project requirements section**:
```
Visually display which side won if a player gets three in a row or show a draw/"cat’s game" if neither wins.

Visually display the results of retrieving game statistics, such as total games won by a user. (READ)

```

For these requirements, we are looking for you to meet them. The way in which you do so is up to you as long as it's achieved.

**Comment by aprilsourz** [comment]
Thank you. This clears that up for me.
