### ISSUE TITLE
game result

### ISSUE THREAD

**Issue by prankmode** [ga-wdi-boston/game-project#654]
Am I correct in that the database does not store if the user wins/loses the game?  It just stores whether the game is over?  seriously?

**Comment by benjimelito** [comment]
This is correct, although to meet the requirements you simply need to display some sort of statistic about the game. That being said, the array of moves is stored so you should be able to run your 'determine winner' logic on the returned array.

**Comment by prankmode** [comment]
ugh.  well, it's not as bad as css.
