### ISSUE TITLE
Can't access a single element using GET request

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/game-project#655]
I'm trying to run the 'show' function, but I keep getting a 404 (Not found) back.
I'm looking on my functions and this is what I get.

The request:
```curl --include --request GET http://localhost:4741/games/${ID}
  --header "Content-Type: application/json" \
  --data '{
  "game": {
    "id": 1,
    "cells": ["o","x","o","x","o","x","o","x","o"],
    "over": true,
    "player_x": {
      "id": 1,
      "email": "and@and.com"
    },
    "player_o": {
      "id": 3,
      "email": "dna@dna.com"
    }
  }
}'
```
The function that passes the Id to Ajax/Ui
```const onGetGame = function (event) {
  event.preventDefault()
  const id = getFormFields(event.target)
  api.getGame(id)
    .then(ui.getGameSuccess)
    .catch(ui.getGameFailure)
}
```
The AJAX function:
```const getGame = (id) => {
  return $.ajax({
    url: config.apiOrigin + '/games/' + id,
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
The Ui handler (for the moment):
```
const getGameSuccess = (data) => {
  console.log(data)
}

const getGameFailure = (error) => {
  console.log(error)
}
```

**Comment by benjimelito** [comment]
What does the url look like when you are getting your error? Also, where are you getting the `id` that you are passing to `api.getGame()`

**Comment by jbeltrami** [comment]
I'm not sure on which url I should be looking at, but this is what I have on my browser `http://localhost:7165/?submit=Access+Single+Game&game%5Bid%5D=0`.
I'm getting the id with 'getFormsField', I think.

**Comment by benjimelito** [comment]
Ah ok, sorry I missed that above. Let me come take a look

**Comment by jbeltrami** [comment]
Thank you for the help.
It was an issue on my API Request syntax.
This is what it looks like now:
```
const onGetGame = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.getGame(data.game.id)
    .then(ui.getGameSuccess)
    .catch(ui.getGameFailure)
}
```

It is working.

**Comment by MicFin** [comment]
Is this working?  Please close if it is or share the error if it is not
