### ISSUE TITLE
'over' query parameter for game api GET requests: requirement?

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/game-project#657]
Regarding the subject above, it says in the game api documentation that "The optional `over` query parameter restricts the response to games with a matching `over` property." I'm wondering if that means that it is a requirement or not for this project to have a feature that displays completed and not completed games. I'm wondering because I'm trying to prioritize things to do, since we don't have much time left. Thank you in advance!

https://github.com/ga-wdi-boston/game-project-api#index

**Comment by BenGitsCode** [comment]
`Visually display the results of retrieving game statistics, such as total games won by a user. (READ)`

is the requirement. 

Completed/uncompleted games are definitely _options_ but which statistics you share with the user is up to you.

**Comment by BenGitsCode** [comment]
Does that make sense?

**Comment by nriser** [comment]
Yes, that makes sense. Thank you for your response!
