### ISSUE TITLE
token for user 1 undefined.

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#66]
I am getting an error when I try to send a POST to create a new game, saying that my token for the signed in user is undefined. This is even after I have signed in a new user and returned the object where I am storing the user token and see that it is there as I would expect. I dont have linter errors. I could past the code but its many modules linked together.

**Comment by laurenfazah** [comment]
Can you put in a debugger and console.log your POST request to see how the token is being passed?

**Comment by louarnos** [comment]
I'm not sure how to do that with how my code currently set up.

**Comment by RDegnen** [comment]
Can you post your ajax request code in here

**Comment by louarnos** [comment]
``` javascript
'use strict'

const user1 = require('../auth/user1.js')

const createGame = (success,failure) =>{
  $.ajax({
    method: "POST",
    url: 'http://tic-tac-toe.wdibos.com/' + 'games',
    headers: {
      Authorization: 'Token token=' + user1.user.token
    },
  })
  .done(success)
  .fail(failure);
}



module.exports = {
  createGame,
}
```

**Comment by louarnos** [comment]
the back-ticks don't seem to be formatting the code

**Comment by RealWeeks** [comment]
@louarnos you need 3 and a line break after/before

**Comment by RealWeeks** [comment]
What is in the user1.user object? can you put a debugger or console log in and show us?

**Comment by louarnos** [comment]
user1 is a file I am using to store my user data once player 1 logs in. I'm unsure where you want the debugger. I am console logging  user1 after i log in to be sure that it is storing the user object and it is returning what I expect.

**Comment by RealWeeks** [comment]
Try creating a new user, the sign them in. Does the same thing happen for other users?

**Comment by louarnos** [comment]
ive signed with a bunch of users

**Comment by RealWeeks** [comment]
paste in your error so i can see it please. I want to see the wording

**Comment by louarnos** [comment]
```
createGame.js:10 Uncaught TypeError: Cannot read property 'token' of undefinedcreateGame @ createGame.js:10addHandlers @ events.js:15(anonymous function) @ index.js:15fire @ jquery.js:3187self.fireWith @ jquery.js:3317jQuery.extend.ready @ jquery.js:3536
```

**Comment by louarnos** [comment]
```
createGame.js:10 Uncaught TypeError: Cannot read property 'token' of undefinedcreateGame 
@ createGame.js:10addHandlers 
@ events.js:15(anonymous function) 
@ index.js:15fire 
@ jquery.js:3187self.fireWith 
@ jquery.js:3317jQuery.extend.ready
 @ jquery.js:3536
```

**Comment by RDegnen** [comment]
Did you properly export the user from wherever its coming from? its saying cannot read property 'token' of undefined because it can't find the user

**Comment by louarnos** [comment]
I believe so, yes. It doesnt give me an issue before this saying it doesnt know what user1 is. If i change the path at all it says that the file doesnt exist. It seems to see the file fine.

**Comment by louarnos** [comment]
no linter errors

**Comment by louarnos** [comment]
Well linter was out of date. I also wasn't calling the right class/id from my html for a j-query call. Didn't have a prevent default on my button.

**Comment by RealWeeks** [comment]
@louarnos Please close if you have a chance
