### ISSUE TITLE
Don't know how to request PATCH and update my existing games

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/game-project#663]
Trying to write my patch request, to update games.
Wrote all the functions on api.js, events.js and ui.js. I'm still getting a 404 Not Found, once I try to run those requests.
I tried to console.log the data I'm getting with `getFormsField`, but it is returning an empty object.
I think I need to tie the game I create with that, but I'm not sure on how to do it.
this is the code I have:

events.js:
```
const onUpdateGame = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log(data)
  api.updateGame(data)
    .then(ui.updateGameSuccess)
    .catch(ui.updateGameFailure)
}
```
api.js:
```
const updateGame = (id) => {
  return $.ajax({
    url: config.apiOrigin + '/games/' + id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
ui.js:
```
const updateGameSuccess = (data) => {
  console.log(data)
}

const updateGameFailure = (error) => {
  console.log(error)
}
```
curl request:
```
#!bin/bash
curl http://localhost:4741/games/${ID} \
--include \
--request PATCH \
--header "Authorization: Token token=$TOKEN" \
--data '{
  "game": {
    "id": 1,
    "cells": ["","","","","","","","",""],
    "over":false,
    "player_x": {
      "id": 1,
      "email": "and@and.com"
      },
    "player_o": {
      "id": 3,
      "email":
      "dna@dna.com"
    }
  }
}'
```

**Comment by jordanallain** [comment]
do you need to input data in a form to update the game? what data are you trying to capture from a form?

**Comment by jbeltrami** [comment]
I'm not sure. I think I don't. This is the PATCH for new games.
I actually don't have a form. should I have one?

**Comment by jordanallain** [comment]
You can't PATCH a new game because a PATCH is modifying an existing resource. You POST to create a new game, then you want to PATCH that game on every move.

**Comment by jordanallain** [comment]
The PATCH should contain the new state of the game board and the last move should change over to true. Not anything you really need a form for.

**Comment by MicFin** [comment]
`POST` is for new (EX: when you create a new game)
`PATCH` is for updating (EX: when you add a position to the board)
`GET` is for viewing (EX: when you want to see all games played)

**Comment by MicFin** [comment]
**events.js**
```js
const onUpdateGame = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log(data)
  api.updateGame(data) // here you pass in a data object to updateGame()
    .then(ui.updateGameSuccess)
    .catch(ui.updateGameFailure)
}
```

 
**api.js**
```js
const updateGame = (id) => { // BUT here you call it ID instead data
  // console.log(id) what is it?
  return $.ajax({
    url: config.apiOrigin + '/games/' + id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
Also AJAX patch request does not have the `data` object that the API expects. 
https://github.com/ga-wdi-boston/game-project-api#update-a-games-states

You should be sending a data object with the AJAX call
https://github.com/ga-wdi-boston/jquery-ajax-post/blob/master/assets/scripts/books/api.js#L23
