### ISSUE TITLE
Making a grid without images. 

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/game-project#664]
I had to delete my grid that uses pictures since I can't get them to load on the website. I'm having trouble making one without those images because they acted as spacers. If I could get help before everyone leaves that'd me awesome!

**Comment by BenGitsCode** [comment]
Andrew, have you tried using those same images uploaded to something like Imgur instead of local assets?

**Comment by BenGitsCode** [comment]
Try that (and be sure to have the file extension included in the `src` attribute) and let me know if that works.

**Comment by Anddrew914** [comment]
Didn't work, but I did switch to buttons and I think that'll do it.
