### ISSUE TITLE
jquery difference between deploy and local

### ISSUE THREAD

**Issue by prankmode** [ga-wdi-boston/game-project#665]
Hi -  My DOM seems to be acting differently on github pages and locally.

In my html file, I have:

```html
  <div id="your-stats">
            <p id="num-games-played">you played X games</p>
            <p id="num-games-won">you won X of them</p>
  </div>
```

in the console, when running with a LOCAL server, if i query those  ids, i get
```js
$('#num-games-played') 
[p#num-games-played]
0: p#num-games-played
length: 1
__proto__: Object(0)
```
you see (i hope) that it thinks it's an array.

this same query, when running against the REMOTE server, does not return an array:

```
$('#num-games-played') 
<p id=​"num-games-played">​you played X games​</p>​
```

what the heckity heck heck.   

needless to say, resetting that text to something else is not working.

**Comment by MicFin** [comment]
It appears like you are using the correct jQuery selector.
```js
$('#num-games-played')
```
Did you try `$('#num-games-played').text("")` or `$('#num-games-played').html("")` and it did not work?

**Comment by prankmode** [comment]
yes.  actually, in my code i set .innerText - and it works in my local because I am using the array [0] to set it.  but because of that it is failing on the deployed version.

**Comment by prankmode** [comment]
So I don't really want to close this - because the problem is not root caused or solved.  I used a work around - I used document.getElementById to retrieve what I needed and that worked the same on both versions.  Let me know if want me to close this.
