### ISSUE TITLE
Rails Server already in use?

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/game-project#667]
I'd like to get some work done on my site today, but when I cannot seem to get my rails server back up and running.  I was in my game-project-api directory, I typed `bundle exec rails server` into my terminal, but I get an error message that tells me it's "exiting" and won't start.  I quit out of all Terminal windows, restarted twice, but still won't work.  Is the server down?  Here's part of the error message:

`Exiting
/Users/rowlandhill/.rvm/gems/ruby-2.3.1/gems/puma-3.6.0/lib/puma/binder.rb:266:in `initialize': Address already in use - bind(2) for "::1" port 4741 (Errno::EADDRINUSE)`

I dragged the screenshot in below, but in case that doesn't work, here's [a link to a screenshot of the entire error message](http://imgur.com/XjfNZuJ)

<img width="1185" alt="screen shot 2017-04-15 at 9 38 08 am" src="https://cloud.githubusercontent.com/assets/20341219/25064085/fbd721cc-21c0-11e7-941c-c62601e6161f.png">

**Comment by BenGitsCode** [comment]
Always copy the the text of the error messages over use of screenshots.

What do you think that means? Have you searched for it in the issue queue?

**Comment by rowlandhill** [comment]
Ah, sorry about that :) I'll paste all the code next time!

Well, I think it means the server is still running.  I think I've been hitting Ctrl-Z to exit instead of Ctrl-C.  Does that make a difference?

I should have checked the queue for previous answers!  Looks like I just needed to reboot my computer since the server was not shut down at all, so it was still running.

What do I need to do to make sure I shut it down completely?  Do I need to close out of Terminal and reboot my computer?  

Thank you so much for the quick response, Ben!!

**Comment by BenGitsCode** [comment]
Mostly likely you had a server running in another terminal window that was minimized or a tab you didn't notice. 

The address it's referring to is the port number.

**Comment by prankmode** [comment]
Rowland - - did you reboot your terminal?  If not, you can try to just kill the server process.  That might work.  I can tell you how to do that if you haven't rebooted already....

**Comment by rowlandhill** [comment]
Thanks, Ben and Erica!  I completely quit out of Terminal three times, but it still wouldn't let me connect, so I quit Terminal again, rebooted my laptop and was able to get online :)
