### ISSUE TITLE
Passing in Data w/ Patch

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/game-project#669]
Greetings -- I'm currently stuck on figuring out how to pass in data to the game objects. More specifically, I've managed to successfully create a game in the Game API but I can't figure out how to get it so that when a user places an X on the game board, it logs the X into the current game id.

I've tried reviewing open/closed issue logs and also the Game Project API documentation and understand that I have to pass in data using PATCH with something like this: 
```js
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
```

Below is my code for updating a game:

events.js
```js
const onUpdateGame = function (event) {
  event.preventDefault()
  console.log('AZ: onUpdateGame from events.js ran!')
  const data = getFormFields(event.target)
  console.log(data)
  api.updateGame(data)
    .then(ui.updateGameSuccess)
    .catch(ui.updateGameFailure)
}
```

api.js
```js
// Creates the Ajax function to PATCHES data into a game id
const updateGame = (id) => {
  console.log('AZ: updateGame from api.js ran!')
  console.log(id)
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: data
  })
}
```

ui.js
```js
const updateGameSuccess = (id) => {
  console.log('AZ: updateGameSuccess from ui.js ran!')
  console.log(id)
  store.games = id.games
}

const updateGameFailure = (error) => {
  console.error(error)
}
```

Please let me know if you require any additional detail. Any guidance is greatly appreciated!

**Comment by prankmode** [comment]
andy - in onUpdateGame, you call api.updateGame with "data" - that data is what is returned from getFormFields.  but then api.updateGame looks like it wants an id.  that seems like a mismatch?
you need to make "data" that is passed to the ajax call look like that PATCH stuff from the documentation.  have you gotten a curl request to work on it?

**Comment by andyjzhong** [comment]
Hi -- thanks for the feedback! It looks like I'll have to change the "data" in api.updateGame to reflect an :id rather than data which I will try later today. 

I think what I'm struggling on is how to make the curl request which I'll need to review documentation and past trainings for. I've been stuck on this part for a while now, as I can't seem to get over how the logged X's magically get pulled into exactly where they need to be in the game object I created in the API. I know it has something to do with the ajax command and passing in an id in order for the game object to recognize that data I want to pass it -- just can't seem to get past this hurdle.

**Comment by payne-chris-r** [comment]
Can you post the curl request you've tried?

**Comment by andyjzhong** [comment]
Thanks for the catch, @prankmode. I was able to fix that error you mentioned above, but I also realized that the more immediate issue at hand was that I didn't have the ability to pass in data to the API because my onUpdateGame function didn't know what form fields to retrieve from. After working with a classmate I was able to diagnose and get my update game working now.

Using the example from the Game Project API, I was able to create a form for logging the game id, game markers, and game status. 

```html
    <!-- Update Game Form-->
    <form id="game_info">
      <input id="index_form" name="game[cell][index]" type="text" value="0">
      <input id="move_marker_form" name="game[cell][value]" type="text" value="x">
      <input id="game_over_form" name="game[over]" type="text" value="false">
    </form>
```
Using jQuery, I was able to link the input id's to my game logic, which essentially helps populate the form so that the click handlers know which values to get every time the game board is clicked. 

```js
const currentTurn = function () {
  currentPlayer = currentPlayer === player1 ? player2 : player1
  $('#move_marker_form').val(currentPlayer)
  $('#index_form').val(+$(this).attr('id'))
  return currentPlayer
}
```
```js
const checkWinner = function () {
  console.log('Check Winner Ran!')
  if (xWins() === true) {
    $('.banner-id').text('Player X Wins!')
    $('#game_over_form').val('true')
    return 'X'
  }
  if (oWins() === true) {
    $('.banner-id').text('Player O Wins!')
    $('#game_over_form').val('true')
    return 'O'
  }
}
```
I found that once I figured out how to tell onUpdateGame to retrieve the data in my newly created form, the update game functionality worked for me.

Thank you to all who helped!
