### ISSUE TITLE
Ajax calls failing

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/game-project#67]
Linter is clean

I've been trying to get sign-up and login calls. Sign-up calls will console.log but not refresh the page like (I think) they did before. No errors are being thrown in the browser. I placed the debugger in different places and it didn't raise anything either. I've tried using curl to test the login on usernames were successfully signed-up and get 401 errors.

**Comment by RealWeeks** [comment]
So @philschoof to clarify your sign in and sign up ajax functions aren't working and you tried to put debuggers in your code and those debuggers didn't trigger?

Were you able to successfully sign up/sign in using curl or did you get 401?

**Comment by philschoof** [comment]
Correct 
I was able to successfully sign up through the browser, but as far as I can tell that is no longer the case - and I haven't been able to sign in using the browser or curl.

**Comment by RDegnen** [comment]
If the debugger isn't firing than check if your properly calling the functions you put it in

**Comment by RealWeeks** [comment]
What has changed in your code since it worked?

**Comment by RealWeeks** [comment]
What are your errors, please paste them in as well

**Comment by philschoof** [comment]
Editing the sign-in call. I'm now having some issues with my architecture that might be the root of the problem.

**Comment by RealWeeks** [comment]
@philschoof is this still an open issue or have you moved on to another one, if this is the case please close, otherwise we'd be happy to answer followups.

**Comment by philschoof** [comment]
Sorry - I'll follow up if need be. Thanks guys.
