### ISSUE TITLE
[Requirements] - error messages.

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/game-project#670]
Do I have to display a unique error message on the page for sign up failure due to the username already being taken vs the password and confirmation not matching?

Do I have to display a unique error message on the page for sign in failure due to the username already being taken vs the username and password not matching?

All I'm getting back from the API for sign in, sign up and change password failures is a status code. I tried consoling logging the error object and couldn't any unique data telling me how the request failed.

Here is my code for handling authorization errors. I check to see if  I am getting the expected status code for failure then display a message on the page, otherwise display 'Unknown Error'. Will this meet requirements?
```js
const displayErrorMessage = (errorText) => {
  $('#display-error').text('')
  $('#display-error').show()
  $('#display-error').text(errorText || 'Unknown error')
  $('#display-error').delay(3000).fadeOut()
}

const signUpFailure = (error) => {
  if (error.status === 400) {
    displayErrorMessage('There was problem signing up, please try again!')
  } else {
    displayErrorMessage()
  }
}

const signInFailure = (error) => {
  if (error.status === 401) {
    displayErrorMessage('Invalid username or password.')
  } else {
    displayErrorMessage()
  }
}

const changePasswordFailure = (error) => {
  if (error.status === 400) {
    displayErrorMessage('Invalid password.')
  } else {
    displayErrorMessage()
  }
}
```

**Comment by MicFin** [comment]
Yes, just a single message that the sign up, change password, or sign in failed is enough.  You are correct that the API does not return you any data about why it failed.

Sign Up 
>If the request is unsuccessful, the response will have an HTTP Status of 400 Bad Request, and the response body will be empty.
https://github.com/ga-wdi-boston/game-project-api#signup

Sign In 
>If the request is unsuccessful, the response will have an HTTP Status of 401 Unauthorized, and the response body will be empty.
https://github.com/ga-wdi-boston/game-project-api#signin

Change PW
>If the request is unsuccessful the reponse will have an HTTP status of 400 Bad Request.
https://github.com/ga-wdi-boston/game-project-api#changepw

**Comment by aprilsourz** [comment]
Ok great. Thanks!
