### ISSUE TITLE
Need help with API 

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/game-project#671]

**Comment by jonifallon** [comment]
I have made a lot of progress this weekend on TTT game, but I don't know how to begin building user stats using api.  My signin, signout, password reset, and new game API stuff seems to be working fine.  I've looked at the issues that other folks have logged but there is nothing that helps me understand how to do it.  I am requesting that someone sit with me to help me understand how to do it.

**Comment by MicFin** [comment]
A first stat to get is usually # of games the user has played.

Have you reviewed the section of the API about index to get all the games?
https://github.com/ga-wdi-boston/game-project-api#index

You could also review how the GET collection talk got all the books
https://github.com/ga-wdi-boston/jquery-ajax-get-collection/commit/1e4d76265aa1d3666bc49275e00f6e3cad1c1dce

**Comment by jonifallon** [comment]
Thank you.  I have reviewed those files but I still need help understanding how to implement and display game stats.

**Comment by MicFin** [comment]
If we break down the example from the lesson https://github.com/ga-wdi-boston/jquery-ajax-get-collection/commit/1e4d76265aa1d3666bc49275e00f6e3cad1c1dce

1.  We create a click event https://github.com/ga-wdi-boston/jquery-ajax-get-collection/commit/1e4d76265aa1d3666bc49275e00f6e3cad1c1dce#diff-d5d8292a2131b881773db93e71c4e892R19
2.  Then a callback function for that click event https://github.com/ga-wdi-boston/jquery-ajax-get-collection/commit/1e4d76265aa1d3666bc49275e00f6e3cad1c1dce#diff-d5d8292a2131b881773db93e71c4e892R19
3.  Then an API call https://github.com/ga-wdi-boston/jquery-ajax-get-collection/commit/1e4d76265aa1d3666bc49275e00f6e3cad1c1dce#diff-d5d8292a2131b881773db93e71c4e892R19
4.  Then a callback for when the API call is successfull https://github.com/ga-wdi-boston/jquery-ajax-get-collection/commit/1e4d76265aa1d3666bc49275e00f6e3cad1c1dce#diff-d5d8292a2131b881773db93e71c4e892R19
5.  At that point you would have an array of the games a user has played and can count that array and display the number on the screen.

Do 1 step at a time.  Try to complete just Step 1.  Then 2.  Then 3.  Do not attempt all 5 at once.

**Comment by benjimelito** [comment]
Your goal for PATCH:

1. Inside `onUpdateGame`, get the index and value of the element that was clicked
2. Create an object that looks like this, with the `index` and `value` filled in:

```{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
```

data.game.cell.index = 
data.game.cell.value = 


3. Call `api.updateGame` with the above object as an argument.

**Comment by jonifallon** [comment]
Between the help from Ben and my squadmate Alan, I have successfully implemented the API.  Thank you.
