### ISSUE TITLE
1:1 Request - API Functionalty

### ISSUE THREAD

**Issue by cpm5041** [ga-wdi-boston/game-project#674]
I’ve been working on my game project throughout the week and have hit a thrashing point regarding some API functionality, specifically my “No network activity” finding. 
I would like a better understanding of what is required to resolve this issue.
I've tried working with other students and attempting to get API functionality working. I receive a "GET" error that points to my CSS file, but only on the deployed app and I'm at a loss for as to why. I am working to get update game/game over API functionality but can't seem to get it going/or receive console logs where anticipated. I would appreciate the opportunity to sit down with a consultant to point me in the right direction.

**Comment by payne-chris-r** [comment]
Please paste your `index.html` code here.

**Comment by cpm5041** [comment]
```html <!DOCTYPE html>
<html>
<head>
  <title>Chris's Tic Tac Toe Game</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="assets/styles/index.css">
  <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do|Permanent+Marker" rel="stylesheet">  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
  <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
  <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
</head>
  <body class="container-fluid" background='https://i.imgur.com/Kae8lUv.jpg'>
      <form id="sign-up" class="credentials sign-up">
        <fieldset>
          <legend>Sign up to play!</legend>
          <input type="text" name="credentials[email]" value="" placeholder="email">
          <input type="password" name="credentials[password]" value="" placeholder="password">
          <input type="password" name="credentials[password_confirmation]" value="" placeholder="password confirmation">
          <input class="credentials" type="submit" name="submit" value="Sign up!">
        </fieldset>
      </form>
      <form id="sign-in" class="credentials">
        <fieldset>
          <legend>Sign in!</legend>
          <input type="text" name="credentials[email]" value="" placeholder="email">
          <input type="password" name="credentials[password]" value="" placeholder="password">
          <input class="credentials" type="submit" name="submit" value="Sign in!">
        </fieldset>
      </form>
      <form id="sign-out" class="credentials signOut">
        <fieldset>
          <legend>Sign out!</legend>
          <input class="credentials" type="submit" name="submit" value="Sign out!">
        </fieldset>
      </form>
      <form id="change-password" class="credentials pw">
        <fieldset>
          <legend>Change Password</legend>
          <input type="password" name="passwords[old]" value="" placeholder="Old Password">
          <input type="password" name="passwords[new]" value="" placeholder="New Password">
          <input class="credentials" type="submit" name="submit" value="Change Password">
        </fieldset>
      </form>
<h2 class='userNotification'>&nbsp;</h2>
  <h1 class='welcome'>Sign in to play some Tic-Tac-Toe!</h1>
  <div style="text-align:center;"><button type='button' id='create' class='newGame'>New Game!</button></div>
  <br>
  <h5 class='games-played' id=#games-played>&nbsp;</h5>
<br>
  <div class='game-board'>
    <div class='boxOne box' id="box-0">&nbsp;</div>
    <div class='boxTwo box' id="box-1">&nbsp;</div>
    <div class='boxThree box' id="box-2">&nbsp;</div>
    <div class='boxFour box' id="box-3">&nbsp;</div>
    <div class='boxFive box' id="box-4">&nbsp;</div>
    <div class='boxSix box' id="box-5">&nbsp;</div>
    <div class='boxSeven box' id="box-6">&nbsp;</div>
    <div class='boxEight box' id="box-7">&nbsp;</div>
    <div class='boxNine box' id="box-8">&nbsp;</div>
  </div>
</body>

</html>
```

**Comment by payne-chris-r** [comment]
```diff
<head>
      <title>Example</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">

-      <!-- Do not add `link` tags unless you know what you are doing -->
      <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

-      <!-- Do not add `script` tags unless you know what you are doing -->
      <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script></head>
```

Not only did you do what the comments told you *NOT* to do, but you deleted them altogether...

**Comment by cpm5041** [comment]
Ah good catch! I had thought I had corrected this. This was from when I tried to start on the design before the template.  I will redeploy and provide an update. Thanks!

**Comment by cpm5041** [comment]
Excellent, the GET error no longer appears in the deployed environment. Would this now satisfy the  “No network activity”  requirement? Could you briefly describe what happened?

**Comment by payne-chris-r** [comment]
No. "No network activity" means you're not making any requests to the API to persist game data. The games you play can't only exists in your client. They must be making Ajax requests to update a game on the API.

**Comment by payne-chris-r** [comment]
As far as what happened:
Webpack builds up a few things for us in order to make deploying easier. What you did by adding link and/or script tags in your HTML is essentially "break the contract" set up by our webpack config. In order to do what you were trying to do you need to follow the convention/pattern we showed you in class.

**Comment by cpm5041** [comment]
Thank you for the clarification! I kept working through it and am now able to update the game on the API with each move. My next tasks are to communicate when a game is over to the API, and then get the Index of a users game. My plan is to add functionality in the check winner function to change game to "over" in the Ajax request. After that I need to figure out how many games a user has played by retrieving the amount of games/over associated with that user.
I've been working through it but would still appreciate a 1:1 to discuss my approach asap.

**Comment by payne-chris-r** [comment]
That all sounds great. It sounds like you're on the right track. Are you just looking for confirmation, a planning session, or are you stuck on the logic? I'll talk to someone about sitting down with you.

**Comment by cpm5041** [comment]
A little bit of all of the above. I feel like I'm so close so I want to try a few things then be able to sit down with someone. Thank you!

**Comment by jrhorn424** [comment]
Ben M will meet with you today at 4pm.

**Comment by cpm5041** [comment]
Thanks for the quick turnaround!

**Comment by cpm5041** [comment]
Thanks for the 1:1 Ben. I was able to get my API call working after our meeting by moving the call to a button click.
