### ISSUE TITLE
Create New Game Issue -- Cannot Play Multiple Games

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/game-project#678]
Hello -- I'm currently experiencing an issue with my create game function where I'm unable to play a second game after clicking my Create New Game button.

I've successfully been able to log in and create a new game. Patch game also works -- it's correctly logging the moves for X's and O's into the game object and the game is unplayable after a win/draw is met. The problem is after the game, when I hit Create New Game again, it cleared the board and created a new game object, BUT **I'm unable to click the cells to log the X's and O's into the newly created game.**

Below is my code for my Create Game functionality:

events.js:
```js
// Creates a new game.
const onCreateGame = function (event) {
  event.preventDefault()
  console.log('onCreateGame from events.js ran!')
  api.createGame()
    .then(ui.createGameSuccess)
    .catch(ui.createGameFailure)
}
```
api.js:
```js
// Creates the Ajax function to POST data for new game
const createGame = (data) => {
  console.log('createGame from api.js ran!')
  return $.ajax({
    url: config.apiOrigin + '/games/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
ui.js:
```js
const createGameSuccess = (data) => {
  console.log('createGameSuccess from ui.js ran!')
  $('.box').text('')
  $('#gameArea').show()
  $('.banner-id').text("Let's Play!")
  console.log(data)
  store.game = data.game
}
```
game logic:
```js
const player1 = 'X'
const player2 = 'O'
let currentPlayer = 'O'

// This alternates player turns.
const currentTurn = function () {
  currentPlayer = currentPlayer === player1 ? player2 : player1
  $('#move_marker_form').val(currentPlayer)
  $('#index_form').val(+$(this).attr('id'))
  return currentPlayer
}

// Prevents overwriting.
const start = function () {
  $(this).html(currentTurn)
  $(this).unbind()
}

// Retrieves the This adds an event listener every time a box is clicked, run the updateCell function.
const setUpGameBoard = function () {
  console.log('AZ: Initialized Gameboard')
  $('#signUpForm, #signInForm, #signOutForm, #changePasswordForm, #game_info, #createGame, #gameArea').show()
  $('#signOutForm, #changePasswordForm, #game_info, #createGame, #gameArea').hide()
  for (let i = 0; i < gameCellIds.length; i++) {
    const elementId = gameCellIds[i]
    const element = document.getElementById(elementId)
    element.addEventListener('click', updateCell)
  }
}

// This logs an X or O into the gameBoard array.
const updateCell = function () {
  console.log(gameBoard)
  const id = this.id
  // const index = index1[1]
  gameBoard[id] = currentPlayer
  checkWinner()
  checkDraw()
  turnCounter()
  $('#game_info').submit()
  if (xWins() === true || oWins() === true) {
    $('.box').off()
    return
  }
}
```

If possible, I'd really like to meet with someone to discuss since the resubmission deadline is this weekend. Thank you!

Thanks!
Andy

**Comment by benjimelito** [comment]
I'm guessing this might have something to do with that `start` function that's defined above where the unbinding takes place. Are you calling that anywhere?

**Comment by andyjzhong** [comment]
Thanks for the quick response, Ben. I've tried passing in the start function into my createGameSuccess previously but I don't recall it working for me. Let me try it once more tonight when I get home to see if I can replicate that issue.

**Comment by andyjzhong** [comment]
Ben -- I just got home and tried passing in the start function into my createGameSuccess function in my UI file. I figured that if a game was successfully created, it would run the start function to start the game. However, when I do this I get an error in the console upon clicking the Create New Game button that says: **authGame.start() is not a function** (I disagree). I believe I've 'required' the file correctly shown below with my updated code.

```js
const authGame = require('../game-logic/game.js')

const createGameSuccess = (data) => {
  console.log('createGameSuccess from ui.js ran!')
  $('.box').text('')
  $('#gameArea').show()
  $('.banner-id').text("Let's Play!")
  console.log(data)
  store.game = data.game
  authGame.start() // Adding the function from my game.js file here.
}
```
I'm also not quite sure if the unbind() piece of code within the start function is causing this to error. Kind of reaching for straws at this point.

I'm also noticing something quite interesting in my back-end terminal whenever I click my Create Game button and I'm not sure if this is contributing to the issue. It's essentially trying to run some SQL to SELECT something a bajillion times shown in the below pic. It does end in a Completed 200 message which you can't see at the bottom of the pic but it jumped out to me as strange.

[http://imgur.com/RNkaoRz](url)

Any additional help would be greatly appreciated!

**Comment by andyjzhong** [comment]
<img width="1310" alt="screen shot 2017-04-20 at 10 13 30 pm" src="https://cloud.githubusercontent.com/assets/26101294/25260288/3b137c76-2619-11e7-9c52-7f9eb0593a54.png">

Uploading screen shot since the above link doesn't work.

**Comment by andyjzhong** [comment]
Quick update: One of my classmates found the issue with my start game function and it's now currently working! I will post my solution as soon as I have a chance today.

**Comment by payne-chris-r** [comment]
Good to hear. Post solution and close please!

**Comment by andyjzhong** [comment]
Below is the code that worked for me:

```js
const createGameSuccess = (data) => {
  $('.box').text('')
  $('#gameArea').show()
  $('.banner-id').text("Let's Play!")
  store.game = data.game
  $('#move_marker_form').val(authGame.currentPlayer)
  $('#index_form').val(+$(this).attr('id'))
  $('#game_over_form').val('false')
  authGame.gameBoard = {}
  authGame.currentPlayer = 'X'
}
```
