### ISSUE TITLE
Error Message: Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/game-project#681]
Hello --

I'm wondering if someone can help me with a bug in my code which logs an Unexpected Identifier in the console. I believe this is the last step in my project that I need to fix in order to complete.

I'm confident that it's related to this function in my Create Game button since it only shows up when this button is clicked. Below is the code:

```js
// Creates a new game.
const onCreateGame = function (event) {
  event.preventDefault()
  game.clearBoard()
  api.createGame()
    .then(ui.createGameSuccess)
    .catch(ui.createGameFailure)
  setTimeout(api.getGames()
    .then(ui.getGamesSuccess)
    .catch(ui.getGamesFailure), 2000)
}
```

Please let me know if you require any additional info!

**Comment by jordanallain** [comment]
need more data! do you know which line it is mad at? throw a debugger in the function and test all the variables you are trying to work with to see what they are.

**Comment by andyjzhong** [comment]
Yes! Thanks for the quick response, Jordan. I'm 99.9% sure it has something to do with the setTimeout function. I'll try throwing in a debugger during one of our breaks.

**Comment by andyjzhong** [comment]
<img width="1279" alt="screen shot 2017-04-21 at 12 58 38 pm" src="https://cloud.githubusercontent.com/assets/26101294/25288203/63d279a4-2692-11e7-8d32-de975f736b13.png">

**Comment by jordanallain** [comment]
try moving the debugger to the first line of the function. when you are paused in the debugger did you try testing all of your variables to make sure they are what you think they are? also you shouldn't need to use the setTimeout method, I would try to move the call to getGames to its own event listener to simplify it.

**Comment by andyjzhong** [comment]
Thanks Jordan!!! I took your advice and just called the getGames in its own event listener! This removed the error completely.
