### ISSUE TITLE
deployed site not showing all content

### ISSUE THREAD

**Issue by JLisaW** [ga-wdi-boston/game-project#682]
I followed all the steps for deploying my game but for some reason the board itself doesn't show up.  It works on my local server and it says my master branch and the branch I was working on is up to date.  I tried deploying a couple times and it only shows what I deployed the first time.  I'm not sure what other information I should provide.      

https://jlisaw.github.io/tic-tac-toe-project/
https://github.com/JLisaW/tic-tac-toe-project

**Comment by payne-chris-r** [comment]
The deploy step removes all past attempts every time you try it, so it will only ever look like you've done it once.

**Comment by payne-chris-r** [comment]
What's the error?

**Comment by payne-chris-r** [comment]
Does your console show anything?

**Comment by payne-chris-r** [comment]
What is it supposed to look like?

**Comment by JLisaW** [comment]
My console is giving me a 404 error
![image](https://cloud.githubusercontent.com/assets/26361086/25307148/047eb43a-276a-11e7-9d70-b4939da8df0b.png)

**Comment by JLisaW** [comment]
it's supposed to look like this 
![image](https://cloud.githubusercontent.com/assets/26361086/25307154/178b998a-276a-11e7-943c-0902bdb4713a.png)

**Comment by MicFin** [comment]
The [browser-template html file](https://github.com/ga-wdi-boston/browser-template/blob/master/index.html) loads all of the css and js files for us through: 
```html
  <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
  <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
```
You should not link to any css or js files in the head of the html document like you did [here](https://github.com/JLisaW/tic-tac-toe-project/blob/master/index.html#L10).
```html
<link rel="stylesheet" href="assets/styles/style.css">
```

Using `browser-template` our styling can be done in [index.scss](https://github.com/JLisaW/tic-tac-toe-project/blob/master/assets/styles/index.scss) where you can import other `.scss` files into if you want.  Additionally, our javascript can be done in [index.js](https://github.com/JLisaW/tic-tac-toe-project/blob/master/assets/scripts/index.js) where we require other `.js` files into if we want.

You should move your css from [style.css](https://github.com/JLisaW/tic-tac-toe-project/blob/master/assets/styles/style.css) to [index.scss](https://github.com/JLisaW/tic-tac-toe-project/blob/master/assets/styles/index.scss) which is the main file you should use for styling and remove the link in `index.html`.

**Comment by JLisaW** [comment]
ah I see, now I can see the board thanks!
