### ISSUE TITLE
Onclick function undefined

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#69]
I have this in my HTML:

`<button><div class="col-md-4" id="1" onclick="boxClicked(1)"><p>Box 1</p></div></button>`

which is a single cell/box in the Tic Tac Toe game,

and this for JS in a file called "gamePlay.js":

``` javascript
const boxClicked = function(boxId) {
  if(getPlayer()==="playerO") {
    document.getElementById(boxId).innerHTML="O";
    turnCount();
    console.log("Go Player X");
 } else {
    document.getElementById(boxId).innerHTML="X";
    turnCount();
    console.log("Go Player O");
  }
};
```

Basically, I want the boxClicked function to change the HTML in this first cell using .innerHTML to either "O" or X".  When I click on the box in localhost, I get the error that "boxClicked" is undefined.  I required gamePlay.js into index.js, but I'm wondering if maybe the HTML file isn't properly accessing the gamePlay.js file.

Thanks!!

**Comment by RealWeeks** [comment]
I think you're going about this in the wrong way @susandaiute .  Please read this: http://stackoverflow.com/questions/12627443/jquery-click-vs-onclick

You may want to reconsider your approach.

**Comment by RealWeeks** [comment]
replace `.click()` with `.on('click'...`

**Comment by RealWeeks** [comment]
We also know jQuery so this: `document.getElementById(boxId).innerHTML="O";` can turn into this: `$(selector).method('o')`

**Comment by susandaiute** [comment]
I'll try it today, thanks Jason!

**Comment by susandaiute** [comment]
IT'S WORKING AND IT IS BEAUTIFULLLLLLLLLL!
THANKS JASON
