### ISSUE TITLE
CURL - POST Request - Error: 443: Connection refused

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#692]
Issue Description:

I'm testing out API requests using curl. I'm attempting to make a POST for sign-up, using the curl command included before and receive the following error:

curl: (7) Failed to connect to ttt.wdibos.com port 443: Connection refused

I borrowed the format for this request from the solutions branch of the API token auth repo. This user has not been created previously. I currently have my client server running on localhost 7165.

curl "https://ttt.wdibos.com/sign-up" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
    "email": "matthewgray88@gmail.com",
    "password": "secret",
    "password_confirmation": "secret"}
  }'

**Comment by benjimelito** [comment]
Try making the request to "http://tic-tac-toe.wdibos.com" instead, the url we initially gave you was incorrect 🔨
