### ISSUE TITLE
HTML - Unable to view updates on github public project URL

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#693]
I'm able to see changes to my html on my localhost, but not on the public facing github URL, by which I mean:

https://artpylon.github.io/tic-tac-toe-mrg/

I think I've gone through the steps to update the code on GH:I've added a signin/signup form in my html, merged to master, ran git push origin master, ran grunt deploy. I have grunt server running in the project repository.

**Comment by jordanallain** [comment]
sometimes the updates can take a bit to kick in.

**Comment by Jcornmanhomonoff** [comment]
@artpylon I believe it just took a few minutes to load. Can you close this issue if it's fixed please?

**Comment by artpylon** [comment]
Resolved. Ran grunt deploy a couple more times, waited. Then, the changes showed up.
