### ISSUE TITLE
gh pages deploy issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#694]
Hello,
I have followed the instructions as slacked out but I get the following error message when running grunt deploy:

nothing added to commit but untracked files present (use "git add" to track)
Warning: Command failed: test -z "$(git status --porcelain)"  || (git status && false)
 Use --force to continue.

I have tried to commit changes but the same message comes up

**Comment by jordanallain** [comment]
what is the output from running `git status`?

**Comment by ghost** [comment]
(use "git add <file>..." to include in what will be committed)

	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	STYLE.md
	assets/
	favicon.ico
	forms.md
	grunt/
	index.html
	index.js
	lib/
	package.json
	spec/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by scottyscripts** [comment]
Did you make an initial commit before pushing??

**Comment by ghost** [comment]
Did make a commit, still got same message

**Comment by MicFin** [comment]
`git status` must have a clean working directory.  If you still see files in staging then you need to `git add`, `git commit` and `git push` them before trying to `grunt deploy`

**Comment by ghost** [comment]
Ok, will try that and report back

**Comment by ghost** [comment]
OK, it deployed successfully. Thank you very much.

**Comment by Jcornmanhomonoff** [comment]
@rothenbg will you please close the issue if this has been solved? Thanks 🙃

**Comment by BenGitsCode** [comment]
Please close this issue with your resolution, was it adding and committing the above files?
