### ISSUE TITLE
Grunt Deploy problems

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/game-project#695]
grunt deploy isn't working

output from git status and grunt deploy:

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
~/wdi/projects/tic-tac-toe (master)
$ grunt deploy
Warning: Task "deploy" not found. Use --force to continue.

Aborted due to warnings.

Execution Time (2017-05-16 11:01:19 UTC-4)
loading tasks  995ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 996ms

~/wdi/projects/tic-tac-toe (master)
$ 

I tried grunt deploy -- force and it didn't work.

This is the url I'm using to view my tic-tac-toe game on github.io
https://marcynash.github.io/tic-tac-toe

**Comment by MicFin** [comment]
Did you do `npm install`?

**Comment by MarcyNash** [comment]
Yes! The git status above was after committing the node_modules folder. 

Running npm install, I got many, many lines of output like these --

 create mode 100644 node_modules/yauzl/README.md
 create mode 100644 node_modules/yauzl/index.js
 create mode 100644 node_modules/yauzl/package.json

**Comment by MicFin** [comment]
What does `ls` show from `/wdi/projects/tic-tac-toe (master)`?

**Comment by MarcyNash** [comment]
I looked at a training folder where I ran "grunt serve". There is "grunt" that I can exec in the top level folder. 

No "grunt' in in my tic-tac-toe folder --

~/wdi/projects/tic-tac-toe (master)
$ ls
CONTRIBUTING.md	README.md	favicon.ico	index.html	node_modules
Gruntfile.js	STYLE.md	forms.md	index.js	package.json
~/wdi/projects/tic-tac-toe (master)
$

**Comment by MicFin** [comment]
That does not look like a downloaded version of browser-template to me.  Did you download from browser-template?
https://git.generalassemb.ly/ga-wdi-boston/browser-template

**Comment by MarcyNash** [comment]
I forked form https://github.com/ga-wdi-boston/browser-template but it looks like my unzip didn't get the folders. Will google unzip and redo my tic-tac-toe repro!  Thanks

**Comment by Jcornmanhomonoff** [comment]
@MarcyNash the directions say to download. Not to fork. I suggest restarting that part of the project.

**Comment by benjimelito** [comment]
Let me know if you are having issues with the non-forked version of the `browser-template`

**Comment by BenGitsCode** [comment]
I'm late to this issue, but never just try `--force`. It's a destructive command.

**Comment by MarcyNash** [comment]
Downloaded non-forked browser-template and now things work!
