### ISSUE TITLE
Linter in Atom covering screen

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#696]
My linter, in addition to displaying errors in the pane, pops up a huge red window whenever I try to move the cursor. It's really distracting.  

![linter-hell](https://cloud.githubusercontent.com/assets/809042/26113671/2e3c5d82-3a29-11e7-9266-8627e6940bc6.jpg)

[ things you've tried to fix the problem ]

I googled this issue to no avail.

**Comment by benjimelito** [comment]
Have you run `npm-install` in this repo yet?

**Comment by lisawilliams** [comment]
Hi, Ben: Yes, I just checked, I did run npm-install in this repo.

**Comment by Jcornmanhomonoff** [comment]
Do you have `jshint` installed as a package?

**Comment by scottyscripts** [comment]
Make sure the file ends with `.js` if it's a JavaScript file

**Comment by lisawilliams** [comment]
Scott: it does end in .js

**Comment by lisawilliams** [comment]
Jessica: ls -a shows: 

 .jshintignore		.jshintrc

**Comment by lisawilliams** [comment]
Fix = just fix errors
