### ISSUE TITLE
grunt deploy not working followed the instruction now i dont know where to push  how will this read my repository be  

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/game-project#697]
~/wdi/newproject/project1 (master)
$ grunt deploy
Running "shell:git-is-clean" (shell) task

Running "shell:git-checkout-master" (shell) task
Already on 'master'

Running "webpack:build" (webpack) task
Version: webpack 1.15.0     
                                 Asset     Size  Chunks             Chunk Names
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
                        application.js   172 kB       0  [emitted]  application
                              specs.js  1.18 kB       1  [emitted]  specs
                             vendor.js   352 kB       2  [emitted]  vendor
   [0] ./index.js 248 bytes {0} [built]
   [0] ./spec/_all.js 198 bytes {1} [built]
   [0] multi vendor 40 bytes {2} [built]
   [1] ./assets/scripts/index.js 361 bytes {0} [built]
       cjs require ./assets/scripts/index.js [0] ./index.js 9:0-36
   [2] ./~/jquery/dist/jquery.js 268 kB {2} [built]
       single entry jquery [0] multi vendor
       cjs require $ [1] ./assets/scripts/index.js 1:0-17
       cjs require jQuery [19] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 1:0-17
   [3] ./lib/set-api-origin.js 1.11 kB {0} [built]
       cjs require ../../lib/set-api-origin [1] ./assets/scripts/index.js 3:19-54
   [4] ./lib/parse-nested-query.js 403 bytes {0} [built]
       cjs require ./parse-nested-query [3] ./lib/set-api-origin.js 3:23-54
   [5] ./lib/add-nested-value.js 745 bytes {0} [built]
       cjs require ./add-nested-value [4] ./lib/parse-nested-query.js 3:21-50
   [6] ./assets/scripts/config.js 132 bytes {0} [built]
       cjs require ./config [1] ./assets/scripts/index.js 4:13-32
   [7] ./assets/scripts/example.js 37 bytes {0} {1} [built]
       cjs require ./example [1] ./assets/scripts/index.js 14:0-20
       cjs require ../assets/scripts/example [18] ./spec/example.spec.js 3:14-50
   [8] ./assets/styles/index.scss 1.03 kB {0} [built]
       cjs require ./assets/styles/index.scss [0] ./index.js 12:0-37
   [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 158 kB {0} [built]
       cjs require !!../../node_modules/css-loader/index.js!../../node_modules/sass-loader/index.js!./index.scss [8] ./assets/styles/index.scss 4:14-118
  [10] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       cjs require ../../node_modules/css-loader/lib/css-base.js [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 1:27-83
  [11] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4172-4253
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4276-4357
  [12] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 84 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4409-4492
  [13] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff 83 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4525-4607
  [14] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4639-4720
  [15] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4756-4837
  [16] ./~/style-loader/addStyles.js 6.91 kB {0} [built]
       cjs require !../../node_modules/style-loader/addStyles.js [8] ./assets/styles/index.scss 7:13-69
  [17] ./spec spec\.js$ 182 bytes {1} [built]
       require.context ./ [0] ./spec/_all.js 6:10-50
  [18] ./spec/example.spec.js 173 bytes {1} [optional] [built]
       context element ./example.spec.js [17] ./spec spec\.js$
  [19] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 69.7 kB {2} [built]
       single entry bootstrap-sass [0] multi vendor

Running "shell:git-push-master" (shell) task
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: Command failed: git push origin master
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 Use --force to continue.

Aborted due to warnings.

Execution Time (2017-05-16 11:23:07 UTC-4)
loading tasks    1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 27%
webpack:build  2.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 71%
Total 3.8s

**Comment by scottyscripts** [comment]
did you add your repository on Github as your origin?

**Comment by isharma-sharma** [comment]
no how we will do that

**Comment by MicFin** [comment]
Follow these instructions.
https://help.github.com/articles/adding-a-remote/
You will end up doing something similar to:
```
git remote add origin https://github.com/user/repo.git
```

**Comment by Jcornmanhomonoff** [comment]
@isharma-sharma status update? How are you doing with this? All set?

**Comment by isharma-sharma** [comment]
no trying
i get the error while setting the repository
```error
$ git remote set-url
error: Unknown subcommand: git://github.com/set-url/project1.git
```

**Comment by MicFin** [comment]
You are not following the steps correctly.  
https://help.github.com/articles/adding-a-remote/

```
git remote add origin https://github.com/user/repo.git
```
The URL `https://github.com/user/repo.git` should be replaced with YOUR github repository link that you get when you click the green button to clone.

You should then be able to run `git remote -v` and see that the correct URL is set as the remote.

**Comment by isharma-sharma** [comment]
deleted my old repository and created the new one by git remote -v
