### ISSUE TITLE
JS - Globally Changing Values of Literals

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/game-project#7]
Linter Output:

grunt nag didn't return anything on point.

Issue Description:

I declare a global string variable, and try to change its value inside of a function. Using console logs I found that the value changed within the function, but the global value of the function did not change. Is it just not possible to change the global value of a literal? Do I have to convert it to any array first?

I declared the variable as a var, declared the function as a var, commented out pretty much every possible problem line, and nothing has worked. Any help would be appreciated!

**Comment by gaand** [comment]
Please provide the global variable declaration and an example of a function that changes it.

**Comment by MFBrewster** [comment]
``` js
let board = [];
let player = 'o';
let game = 0;

let newGame = function(player, game, board) {
  clearBoard(board);
  player = 'x';
  // if (game % 2 === 0) { player = 'x'; }
  // else { player = 'o'; }
  game++;
  return;
};

let clearBoard = function(board) {
  for (let i = 0; i < 9; i++) {
    board[i] = '';
  }
  return;
};
```

after running the function, `console.log(player)` returns 'o'

**Comment by gaand** [comment]
The formal parameter `player` shadows the global variable `player`.  So, your assignment changes something function local.

**Comment by MFBrewster** [comment]
``` js
let newGame = function(localPlayer, game, board) {
  clearBoard(board);
  localPlayer = 'x';
  // if (game % 2 === 0) { player = 'x'; }
  // else { player = 'o'; }
  game++;
  return;
};

newGame(player, game, board);
console.log(player);
```

still returns 'o', unfortunately

**Comment by gaand** [comment]
You're still assigning to the formal parameter.

You can't change the global variable by assigning the local one.  Maybe this will help make it clearer:

``` js
let globalPlayer = 'o';

let newGame = function(player) {
  let localPlayer = player;
  localPlayer = 'x';
  return;
};

newGame(player);
```

So the change you make stays in the function.

**Comment by MFBrewster** [comment]
``` js
let newGame = function(player, game, board) {
  clearBoard(board);
  let p = player, g = game;
  p = 'x';
  // if (game % 2 === 0) { player = 'x'; }
  // else { player = 'o'; }
  g++;
  return;
};

console.log(player, game, board);
newGame(player, game, board);
console.log(player, game, board);
```

console logs: 
o 0 []
o 0 [ '', '', '', '', '', '', '', '', '' ]

In other words, it appears I cannot change the value of global strings or numbers within the function, but I can change the value of an array (demonstrated by the "clearBoard" function creating the array of empty strings).

**Comment by gaand** [comment]
Yes.  The array is a reference type so the different variables point to the same object.

A solution would be to store the player, and the board, as a properties of an object stored globally

``` js
const gameState = { // or something
  player: 'o',
  board: [],
};
```

**Comment by RealWeeks** [comment]
@MFBrewster is this resolved?  If so please close.

**Comment by MFBrewster** [comment]
Yes that worked, I stored all of the literals I want to change inside of a global object, and called the whole object into the function. Thank you!
