### ISSUE TITLE
Git merge issue

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/game-project#70]
I have successfully merged a few of my working branches to master, but I'm having some issue getting this to work tonight.

I'm not sure if I'm making a dumb error, or missing something from it just being late.

I'll post my terminal history below, including more than enough lines to see my problem.

I have been working on branch "gamejs" and have made progress that I would like to merge onto my master branch before proceeding. Please advise.
'''
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
~/wdi/project/tic-tac-toe (master)$ git checkout gamejs
Switched to branch 'gamejs'
~/wdi/project/tic-tac-toe (gamejs)$ git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
~/wdi/project/tic-tac-toe (master)$ git merge gamejs
Already up-to-date.
~/wdi/project/tic-tac-toe (master)$ git checkout gamejs
Switched to branch 'gamejs'
~/wdi/project/tic-tac-toe (gamejs)$ git push origin gamejs
To git@github.com:Benjamski/tic-tac-toe.git
 ! [rejected]        gamejs -> gamejs (non-fast-forward)
error: failed to push some refs to 'git@github.com:Benjamski/tic-tac-toe.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/project/tic-tac-toe (gamejs)$ git add .
~/wdi/project/tic-tac-toe (gamejs)$ git git commit
git: 'git' is not a git command. See 'git --help'.

Did you mean this?
    init
~/wdi/project/tic-tac-toe (gamejs)$ git commit
On branch gamejs
nothing to commit, working directory clean
~/wdi/project/tic-tac-toe (gamejs)$ git push origin gamejs
To git@github.com:Benjamski/tic-tac-toe.git
 ! [rejected]        gamejs -> gamejs (non-fast-forward)
error: failed to push some refs to 'git@github.com:Benjamski/tic-tac-toe.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/project/tic-tac-toe (gamejs)$ git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
~/wdi/project/tic-tac-toe (master)$ git merge gamejs
Already up-to-date.
~/wdi/project/tic-tac-toe (master)$ git push origin master
Counting objects: 31, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (31/31), done.
Writing objects: 100% (31/31), 3.80 KiB | 0 bytes/s, done.
Total 31 (delta 18), reused 0 (delta 0)
To git@github.com:Benjamski/tic-tac-toe.git
   47edb36..f23f211  master -> master
~/wdi/project/tic-tac-toe (master)$ git merge gamejs
Already up-to-date.
~/wdi/project/tic-tac-toe (master)$ git checkout gamejs
Switched to branch 'gamejs'
~/wdi/project/tic-tac-toe (gamejs)$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
~/wdi/project/tic-tac-toe (master)$ git merge gamejs
Already up-to-date.
~/wdi/project/tic-tac-toe (master)$ 
'''

**Comment by gaand** [comment]
The message indicates `gamejs` on the remote has commits that you don't have locally.  So rejecting the push is correct behavior.

You can compare `git log` locally with the commit log on github to see what's different.

**Comment by BenGitsCode** [comment]
I understand that my game js remote on github and my local gamejs repo files do not match up in their commits, but I'm completely unclear as to why. I thought I had only  made new branches, deleted them when coding was unsuccessful, and merged them into master when they were successful. Currently, master is very behind in my progress, and the gamejs branch is the most up-to-date status of my project. 

I have tried pulling gamejs to my local repo, using reset hard to the specific commit that is most updated and several combinations of pushing and pulling master and gamejs branches and every attempt seems to go the wrong place. I think I am missing a pull somewhere, but I'd like to better understand how I'm fixing my branch order before just thrashing to an answer.

Is there a danger/poor practice in setting my gamejs branch as my new default branch?

or making a "better-master" branch and merging "gamejs" to it and then setting that as my new master branch? I want to continue on working on my project, but not until I  can move forward with minimum damage to my branch and commit history.
