### ISSUE TITLE
JS: Event handler for signup form refreshes the page without console-logging data

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#700]
Hi! 
I have a working curl script for sign-up, and a HTML/Bootstrap signup form. I am having trouble writing the event handler. 

Here is the entirety of my auth/scripts/events.js file right now: 

```js
'use strict'
const getFormFields = require('../../../lib/get-form-fields.js')

const onSignUp = function (event) {
  event.preventDefault()
  let data = getFormFields(event.target)
  console.log(data)
//  api.signUp(data)
//  .done(ui.success)
//  .fail(ui.fail)
}

module.exports = {
  onSignUp
}
```
When I fill out the form and press submit, the page refreshes and I get the following output in the console: 

``` 
VM1080:1 XHR finished loading: GET "http://localhost:7165/sockjs-node/info?t=1494952622874".
(anonymous)	@	VM1080:1
AbstractXHRObject._start	@	abstract-xhr.js:132
(anonymous)	@	abstract-xhr.js:21
```

**Comment by Jcornmanhomonoff** [comment]
It sounds like it's not getting to your `onSignUp` function. Is it console logging data?

**Comment by lisawilliams** [comment]
No, it's not console logging anything. The stuff above is the only thing that is in the console.

**Comment by Jcornmanhomonoff** [comment]
Where are you calling the function?

**Comment by lisawilliams** [comment]
Not sure where to do that? Keep looking at auth-token-api, but don't get it.

**Comment by lisawilliams** [comment]
In the list I have it says, "Add event to index. js." Here's what index.js looks like: 

``` 'use strict'

// user require with a reference to bundle the file and use it in this file
// var example = require('./example');

// load manifests
// scripts
require('./assets/scripts/index.js')
require('./assets/scripts/auth/events.js')

// styles
require('./assets/styles/index.scss')
```

It does point to events.js and has the correct path to events.js.

**Comment by Jcornmanhomonoff** [comment]
So it sounds like you're on the right track. You need to call the function in order to use it. You've already made your event handler but you haven't used it anywhere. `index.js` is where I would do this.

**Comment by lisawilliams** [comment]
```js
require('./assets/scripts/auth/events.js')
``` 
does not do that? There has to be a function in index.js in addition to requiring events.js?

**Comment by lisawilliams** [comment]
shoot. 
```
require('./assets/scripts/auth/events.js')

```

**Comment by Jcornmanhomonoff** [comment]
Require just gives you access to that file. You need to call the function. Think about the books demo. When we wanted to get a book we clicked on a button which had an ID and on the submit of it we did something.

**Comment by Jcornmanhomonoff** [comment]
@lisawilliams status update?

**Comment by lisawilliams** [comment]
The form needed name="credentials[password_confirmation]" instead of id="credentials[password_confirmation]"
