### ISSUE TITLE
Ajax - Attempting to change password, id undefined

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#701]
I've added a form to change user's password, includes only new password and old password fields. 

I've successfully curled the change password command. 

When I test the ajax call, the console shows an error that it cannot find id of undefined. 

I think what's happening is that the ID and token for a logged in user are not being accessed correctly or are not be stored at all. So, I tried added code to the sign in function to store the id and token in the store file, but I don't think that's working properly. With the added code, sign in returns undefined to the console.

Code:
Sign in ajax call, this is where I am attempting to store the id and token in the store file, which is required in this file. When sign in is submitted, this returns undefined to the console, before adding the ".then"... code to signIn, this code worked.

```js
const signIn = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-in',
    method: 'POST',
    data
  })
  .then((response) => {
    store.userToken = response.user.token
    store.id = response.user.id
  })
}
```
When a change password form is submitted, onChangePassword is called:

```js
const onChangePassword = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.changePassword(data) // passing credentials to the ajax call
    .then(ui.changePasswordSuccess) // using a Promise to ensure order of execution
    .catch(ui.changePasswordFailure)
```
onChangePassword calls changePassword:

```js
const changePassword = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/change-password/' + data.user.id,
    method: 'PATCH',
    data
  })
}
```
Console shows this error:
<img width="732" alt="screen shot 2017-05-16 at 12 54 31 pm" src="https://cloud.githubusercontent.com/assets/26583372/26118169/e2c8c8e6-3a36-11e7-8141-520bd85508ea.png">

**Comment by benjimelito** [comment]
If you `console.log` store, what does it show?

**Comment by artpylon** [comment]
Where should I insert the console.log? I would guess it need to come after the .then in the signIn function, but when I put it there I have a linter error that the code is unreachable.
