### ISSUE TITLE
Page refreshing

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#703]
Hello, I am trying to get the sign-up function to work but it keeps refreshing the page instead

code:
'''js
const onSignUp = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  event.preventDefault()
'''
As shown, I have written preventdefault () and it still refreshes looked on stackOverflow but didn't find the answers that helpful.

**Comment by scottyscripts** [comment]
What happens if you put a `console.log` inside that function

**Comment by scottyscripts** [comment]
where is this being invoked?

**Comment by ghost** [comment]
with a console.log it still refreshes
'''js
const onSignUp = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log()
  event.preventDefault()
'''

**Comment by scottyscripts** [comment]
Can you console.log a random string and see if it outputs to your console.

**Comment by scottyscripts** [comment]
like `console.log('in onSignup function')`

**Comment by ghost** [comment]
it still doesn't output 
```js
const onSignUp = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log('boo')
  event.preventDefault()
```

**Comment by benjimelito** [comment]
Backticks! (Not single quotes)

**Comment by ghost** [comment]
So I invoked addHandlers in the index.js file and it worked.  Thank you and sorry for the single quotes.
