### ISSUE TITLE
"XHR finished loading" error

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/game-project#704]
Hey so every time I try to POST new signup info I get this error in my console:
```XHR finished loading: GET "http://localhost:7165/sockjs-node/info?t=14949592```
My curl request for this worked (got a 201 Created return) but when I move it over to the browser I keep getting the XHR error. I've tried to figure out what the error code is telling me but all the resources online are just forums about enabling/disabling XML log requests. Can someone help me figure out what this error code is saying?
Here are some more screenshots:
![screenshot from 2017-05-16 14-24-07](https://cloud.githubusercontent.com/assets/27901872/26122322/1334e4e8-3a45-11e7-8b79-11b1a311e5d8.png)
![screenshot from 2017-05-16 14-23-35](https://cloud.githubusercontent.com/assets/27901872/26122329/168ab82a-3a45-11e7-84d3-fee3505566ff.png)

**Comment by slammyde7113** [comment]
restarted my grunt server webpack and now I'm getting more descriptive errors. I think I'm having trouble calling the signUp function but I dont know what I'm missing in my code. Here's a screenshot of my new errors:
![screenshot from 2017-05-16 14-52-10](https://cloud.githubusercontent.com/assets/27901872/26123021/7cb4ed26-3a47-11e7-9e17-7e0ce444222b.png)

**Comment by scottyscripts** [comment]
take a look at the url you are POSTing to. Can you post what you have in `config.js`

**Comment by scottyscripts** [comment]
are you requiring config.js ?

**Comment by slammyde7113** [comment]
all set. Made these changes and it worked:
url: config.apiOrigins.development + '/sign-up/'

**Comment by slammyde7113** [comment]
```
'use strict'

const config = {
  apiOrigins: {
    development: 'http://tic-tac-toe.wdibos.com',
    production: 'https://aqueous-atoll-85096.herokuapp.com'
  }
}

module.exports = config
```

```
const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigins.development + '/sign-up/',
    method: 'POST',
    data
  })
}
```

**Comment by BenGitsCode** [comment]
Please do not use screenshots. We want errors and code easily read, and copy/pastable. 

Great job on the code fences (pro tip: add  `js` after the opening three backticks to get some javascript syntax highlighting.)

Good job on the fix!
