### ISSUE TITLE
Sign up resulting in a page refresh and no console.log

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/game-project#705]
Sign up form: 
```html
  <form id="sign-up">
              <fieldset>
                <legend>Sign up!</legend>
                <input type="text" name="credentials[email]" value="" placeholder="email">
                <input type="password" name="credentials[password]" value="" placeholder="password">
                <input type="password" name="credentials[password_confirmation]" value="" placeholder="password confirmation">
                <input type="submit" name="submit" value="Sign up!">
              </fieldset>
            </form>
```
api.js
```js
const config = require('./config')
const store = require('./store')

const signUp = function (data) {
  return $.ajax({
    url: config.ApiOrigin + '/sign-up/',
    method: 'POST',
    data
  })
  .then((response) => {
    store.userToken = response.user.token
    console.log(store)
  })
}
module.exports = {
  signUp
}
```
events.js
```js
const api = require('./api')
const ui = require('./ui')
const getFormFields = require('../../../lib/get-form-fields.js')

const onSignUp = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.signUp(data)
    .then(ui.signUpSuccess)
    .catch(ui.signUpFailure)
}

const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp)
}

module.exports = {
  addHandlers
}
```
ui.js
```js
const signUpSuccess = (data) => {
  console.log(data)
}

const signUpFailure = (error) => {
  console.error(error)
}

module.export = {
  signUpSuccess,
  signUpFailure
}
```
I made my own auth folder with the api.js, events.js, and ui.js files.  Maybe the requires are off?  I've tried different file paths, but it hasn't netted me any gains.

I'm not getting any console messages, so maybe it's the way the button is set up?

**Comment by benjimelito** [comment]
I think this is something that Scott just covered, are you invoking the `addHandlers` function anywhere?

**Comment by scottyscripts** [comment]
you need to invoke that addHandlers function in index.js

**Comment by RoryEnright** [comment]
does it need it's own line or can it be done like this?

```js
const addHandlers = require('./scripts/auth/events')

$(() => {
  setAPIOrigin(location, config)
  addHandlers()
})
```

**Comment by scottyscripts** [comment]
that looks good to me! Try it out and let me know! Is the path for the require correct?

**Comment by RoryEnright** [comment]
Think I've found the correct path, but it's giving me an error.

jQuery.Deferred exception: addHandlers is not a function TypeError: addHandlers is not a function
    at HTMLDocument.<anonymous> (http://localhost:7165/public/application.js:41:4)
    at mightThrow (http://localhost:7165/public/vendor.js:11497:30)
    at process (http://localhost:7165/public/vendor.js:11565:13) undefined

**Comment by jordanallain** [comment]
you named the variable that requires the file addHandlers, and it should have a property addHandlers that is a function. a bit confusing perhaps.

**Comment by RoryEnright** [comment]
const authEvents = require('./auth/events.js')

$(() => {
  authEvents.addHandlers()
})
