### ISSUE TITLE
Git Problems

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/game-project#706]
I added, committed and pushed the changes from development to master. I then issued a pull request to put commits in the development branch in the master. I forgot to pull the changes locally.

I cannot checkout the development branch or the master branch.

**Comment by benjimelito** [comment]
When you say you are unable to checkout the development or master branch, what branch are you currently on? What command are you running to try to checkout either of these branches?

**Comment by MarcyNash** [comment]
I'm in not in any branch --

$ git checkout development
assets/scripts/change-password-json.sh: needs merge
assets/scripts/sign-in-json.sh: needs merge
assets/scripts/sign-out-json.sh: needs merge
error: you need to resolve your current index first
~/wdi/projects/tic-tac-toe 
$ ls
CONTRIBUTING.md	STYLE.md	grunt		node_modules
Gruntfile.js	assets		index.html	package.json
LICENSE		favicon.ico	index.js	public
README.md	forms.md	lib		spec
~/wdi/projects/tic-tac-toe 
$

**Comment by MarcyNash** [comment]
git reset HEAD on all three files above and development branch and master branch are now fixed.
