### ISSUE TITLE
i tried a lot but not able to reslove this i m not getting my signUp work

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/game-project#707]
/Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js doesn't exist
  /Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.webpack.js doesn't exist
  /Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.web.js doesn't exist
  /Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.js doesn't exist
  /Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.json doesn't exist
resolve directory
  /Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js doesn't exist (directory default file)
  /Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js/package.json doesn't exist (directory description file)
[/Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js]
[/Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.webpack.js]
[/Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.web.js]
[/Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.js]
[/Users/shantanusharma/wdi/newproject/project1/assets/scripts/auth/events.js.json]
 @ ./assets/scripts/index.js 5:17-44

**Comment by benjimelito** [comment]
Under what conditions are you receiving this error? Would you mind posting some of your code for signup?

**Comment by isharma-sharma** [comment]
```js
const signUp = function(data) {
  console.log('data is', data)
  return $.ajax({
    url: config.apiOrigin + '/sign-up/',
    method: 'POST',
    data

  })
}
module.exports = {
  signUp} 
```
```js
const authEvents = require('./auth/events.js')
$(() => {
  authEvents.addHandlers()
})
```

**Comment by isharma-sharma** [comment]
my index.js file was on the wrong folder it need to be in scripts
