### ISSUE TITLE
When submitting a form, debugger pauses and references mystery file onload.wff

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#708]
When submitting my signup form, the debugger pauses and gives the following error: 

onloadwff.js:75 Uncaught TypeError: e.getBoundingClientRect is not a function
    at Object.s [as isClickable] (onloadwff.js:75)
    at n (onloadwff.js:75)
    at r (onloadwff.js:75)
    at onloadwff.js:75

**Comment by lisawilliams** [comment]
(The signup form still works and logs the credentials object to the console.

**Comment by BenGitsCode** [comment]
I don't understand the question.  Browser? JS?

Can you share the code?

**Comment by lisawilliams** [comment]
The error is coming from a file called onloadwff.js. I don't remember adding this file, and I can't find it...I don't know what part of my code to send to you.

**Comment by lisawilliams** [comment]
(Edited question for better findability)
