### ISSUE TITLE
Weird error but still works?

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/game-project#709]
I got my changePassword feature to work but I get all these messages from the console telling me something is wrong. Here's a screenshot:
![screenshot from 2017-05-16 15-42-59](https://cloud.githubusercontent.com/assets/27901872/26125061/bfcbd3ca-3a4e-11e7-84f4-424eae92fb3b.png)
The error messages starting with "jQuery" (three yellow one) occur when I change the password but it still works. The three messages (events.js:24, jquery.js:9566, jquery.js:9566, and ui.js:15) occur when I try to login using the old password. The last messages occur when I login using the new password.
Is something happening behind the scenes that could affect my overall output? I can't understand the jquery files Jeff said not to look in them so I'm a little confused.

**Comment by scottyscripts** [comment]
Cannot read property user of undefined. So somewhere you are trying to access a user property on an undefined object. Can you post your code?

**Comment by slammyde7113** [comment]
api
```
const changePassword = function (data) {
  console.log(data)
  return $.ajax({
    headers: {
      'Authorization': 'Token token=' + store.userToken
    },
    url: config.apiOrigin + '/change-password/' + store.id,
    method: 'PATCH',
    data
  })
  .then((response) => {
    store.userToken = response.user.token
    return store.userToken
  })
  .then(console.log)
}
```

```
const onChangePassword = function (event) {
  // prefer event.target over this
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log(data)
  // initiates an HTTP request that was defined in the api module as singUp
  api.changePassword(data) // passing the credentials to the ajax call
    .then(ui.changePasswordSuccess) // using the Promise tot ensure order execution
    // .then() afterwards takes the results of the previous .then()
    .catch(ui.changePasswordFailure)
}
```

```
const changePasswordSuccess = (data) => {
  console.log(data)
}

const changePasswordFailure = (error) => {
  console.log(error)
}
```

**Comment by slammyde7113** [comment]
1.) api
2.) events
3.) ui
**

**Comment by scottyscripts** [comment]
console.log(response) in the `.then` function after you make your request. What are you getting

**Comment by slammyde7113** [comment]
in the ajax return?

**Comment by scottyscripts** [comment]
in the .then function after returning ajax

**Comment by slammyde7113** [comment]
```
const changePassword = function (data) {
  console.log(store.userToken)
  return $.ajax({
    headers: {
      'Authorization': 'Token token=' + store.userToken
    },
    url: config.apiOrigins.development + '/change-password/' + store.id,
    method: 'PATCH',
    data
  })
  .then((response) => {
    console.log(response)
    console.log(store.userToken)
    store.userToken = response.user.userToken
    return store.userToken
  })
  .then(console.log)
}
```

**Comment by slammyde7113** [comment]
response is undefined apparently

**Comment by slammyde7113** [comment]
![screenshot from 2017-05-16 16-08-09](https://cloud.githubusercontent.com/assets/27901872/26125968/e2c72106-3a51-11e7-97a4-4353929c2c08.png)

**Comment by scottyscripts** [comment]
What will response.user be if response is undefined? sounds error worthy. Take a look at where you are trying to save the token.

**Comment by slammyde7113** [comment]
what exactly does 'response" do? Does it take the info returned from the previous function as its argument?

**Comment by slammyde7113** [comment]
PATCH method doesn't return anything so 'response' was undefined
