### ISSUE TITLE
Game Users

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#71]
I would like to change color of the box instead of place an x or o. I'm having trouble figuring out how to swap between players while using colors instead of text. Here is my code thus far.

``` css

'use strict';

let turnClick = 0;

let players = [box.css('background', 'red'), box.css('background', 'blue']


//counts clicks
$('.available').on('click', function(){
  let currentCell = $(this);
    return turnClick++;
});

//changes block to red on click
$('.available').on('click', function(){
  let currentCell = $(this);
  currentCell.removeClass('available');
  currentCell.css('background', 'red');
});

```

**Comment by gaand** [comment]
Question:  Have you tried running this code?

Suggestion: use the `addClass` method rather than the `css` method.  Create classes named, e.g. `player-x` and `player-o` with backgrounds `blue` and `red`.

**Comment by Jcornmanhomonoff** [comment]
I have successfully run the code without the let players variable. My count clicks works as does changing the block color on clicks. I'll replace the css with addClass.

If I make the classes in index.js, do I declare the backgrounds in my scss file?

**Comment by RDegnen** [comment]
The classes you would add with addClass would be css classes

**Comment by Jcornmanhomonoff** [comment]
So for example:

``` css
$('.available').on('click', function(){
  let currentCell = $(this);
  currentCell.removeClass('available');
  currentCell.addClass('player-x', 'background', 'red');
});
```

**Comment by Jcornmanhomonoff** [comment]
I suppose I'm confused as to where I'm declaring the class. ie: would it be in my html?

**Comment by RDegnen** [comment]
would would declare the class in your scss file because it is a css class that you want to apply with addClass. e.g.

```
.classToAdd {
  background: red;
}
```

**Comment by Jcornmanhomonoff** [comment]
Added classes in scss file with background color.
