### ISSUE TITLE
grunt deploy not working

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/game-project#710]
Ran grunt deploy. It looked like it worked --

$ grunt deploy
Running "shell:git-is-clean" (shell) task

Running "shell:git-checkout-master" (shell) task
Already on 'master'
Your branch is up-to-date with 'origin/master'.

Running "webpack:build" (webpack) task
Version: webpack 1.15.0     
                                 Asset     Size  Chunks             Chunk Names
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
                        application.js   173 kB       0  [emitted]  application
                              specs.js  1.18 kB       1  [emitted]  specs
                             vendor.js   352 kB       2  [emitted]  vendor
   [0] ./index.js 248 bytes {0} [built]
   [0] ./spec/_all.js 198 bytes {1} [built]
   [0] multi vendor 40 bytes {2} [built]
   [1] ./assets/scripts/index.js 361 bytes {0} [built]
       cjs require ./assets/scripts/index.js [0] ./index.js 9:0-36
   [2] ./~/jquery/dist/jquery.js 268 kB {2} [built]
       single entry jquery [0] multi vendor
       cjs require $ [1] ./assets/scripts/index.js 1:0-17
       cjs require jQuery [19] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 1:0-17
   [3] ./lib/set-api-origin.js 1.11 kB {0} [built]
       cjs require ../../lib/set-api-origin [1] ./assets/scripts/index.js 3:19-54
   [4] ./lib/parse-nested-query.js 403 bytes {0} [built]
       cjs require ./parse-nested-query [3] ./lib/set-api-origin.js 3:23-54
   [5] ./lib/add-nested-value.js 745 bytes {0} [built]
       cjs require ./add-nested-value [4] ./lib/parse-nested-query.js 3:21-50
   [6] ./assets/scripts/config.js 188 bytes {0} [built]
       cjs require ./config [1] ./assets/scripts/index.js 4:13-32
   [7] ./assets/scripts/example.js 37 bytes {0} {1} [built]
       cjs require ./example [1] ./assets/scripts/index.js 14:0-20
       cjs require ../assets/scripts/example [18] ./spec/example.spec.js 3:14-50
   [8] ./assets/styles/index.scss 1.03 kB {0} [built]
       cjs require ./assets/styles/index.scss [0] ./index.js 12:0-37
   [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 158 kB {0} [built]
       cjs require !!../../node_modules/css-loader/index.js!../../node_modules/sass-loader/index.js!./index.scss [8] ./assets/styles/index.scss 4:14-118
  [10] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       cjs require ../../node_modules/css-loader/lib/css-base.js [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 1:27-83
  [11] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4172-4253
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4276-4357
  [12] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 84 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4409-4492
  [13] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff 83 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4525-4607
  [14] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4639-4720
  [15] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4756-4837
  [16] ./~/style-loader/addStyles.js 6.91 kB {0} [built]
       cjs require !../../node_modules/style-loader/addStyles.js [8] ./assets/styles/index.scss 7:13-69
  [17] ./spec spec\.js$ 182 bytes {1} [built]
       require.context ./ [0] ./spec/_all.js 6:10-50
  [18] ./spec/example.spec.js 173 bytes {1} [optional] [built]
       context element ./example.spec.js [17] ./spec spec\.js$
  [19] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 69.7 kB {2} [built]
       single entry bootstrap-sass [0] multi vendor

Running "shell:git-push-master" (shell) task
Everything up-to-date

Running "shell:deploy-prepare" (shell) task
Deleted branch gh-pages (was 1cecbdf).
Switched to a new branch 'gh-pages'
rm '.editorconfig'
rm '.eslintrc.json'
rm '.gitignore'
rm '.jscsrc'
rm '.jshintignore'
rm '.jshintrc'
rm '.remarkrc'
rm '.scss-lint.yml'
rm 'CONTRIBUTING.md'
rm 'Gruntfile.js'
rm 'LICENSE'
rm 'README.md'
rm 'STYLE.md'
rm 'assets/scripts/.eslintrc.json'
rm 'assets/scripts/change-password-json.sh'
rm 'assets/scripts/config.js'
rm 'assets/scripts/example.js'
rm 'assets/scripts/index.js'
rm 'assets/scripts/sign-in-json.sh'
rm 'assets/scripts/sign-out-json.sh'
rm 'assets/scripts/sign-up-json.sh'
rm 'assets/scripts/store.js'
rm 'assets/scripts/templates/helpers/.keep'
rm 'assets/styles/index.scss'
rm 'favicon.ico'
rm 'forms.md'
rm 'grunt/aliases.json'
rm 'grunt/eslint.json'
rm 'grunt/jasmine.json'
rm 'grunt/jsonlint.json'
rm 'grunt/paths.json'
rm 'grunt/shell.js'
rm 'grunt/webpack-dev-server.js'
rm 'grunt/webpack.js'
rm 'index.html'
rm 'index.js'
rm 'lib/add-nested-value.js'
rm 'lib/get-form-fields.js'
rm 'lib/parse-nested-query.js'
rm 'lib/set-api-origin.js'
rm 'package.json'
rm 'spec/.eslintrc.json'
rm 'spec/_all.js'
rm 'spec/example.spec.js'

Running "webpack:build" (webpack) task
Version: webpack 1.15.0     
                                 Asset     Size  Chunks             Chunk Names
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
                        application.js   173 kB       0  [emitted]  application
                              specs.js  1.18 kB       1  [emitted]  specs
                             vendor.js   352 kB       2  [emitted]  vendor
   [0] ./index.js 248 bytes {0} [built]
   [0] ./spec/_all.js 198 bytes {1} [built]
   [0] multi vendor 40 bytes {2} [built]
   [1] ./assets/scripts/index.js 361 bytes {0} [built]
       cjs require ./assets/scripts/index.js [0] ./index.js 9:0-36
   [2] ./~/jquery/dist/jquery.js 268 kB {2} [built]
       single entry jquery [0] multi vendor
       cjs require $ [1] ./assets/scripts/index.js 1:0-17
       cjs require jQuery [19] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 1:0-17
   [3] ./lib/set-api-origin.js 1.11 kB {0} [built]
       cjs require ../../lib/set-api-origin [1] ./assets/scripts/index.js 3:19-54
   [4] ./lib/parse-nested-query.js 403 bytes {0} [built]
       cjs require ./parse-nested-query [3] ./lib/set-api-origin.js 3:23-54
   [5] ./lib/add-nested-value.js 745 bytes {0} [built]
       cjs require ./add-nested-value [4] ./lib/parse-nested-query.js 3:21-50
   [6] ./assets/scripts/config.js 188 bytes {0} [built]
       cjs require ./config [1] ./assets/scripts/index.js 4:13-32
   [7] ./assets/scripts/example.js 37 bytes {0} {1} [built]
       cjs require ./example [1] ./assets/scripts/index.js 14:0-20
       cjs require ../assets/scripts/example [18] ./spec/example.spec.js 3:14-50
   [8] ./assets/styles/index.scss 1.03 kB {0} [built]
       cjs require ./assets/styles/index.scss [0] ./index.js 12:0-37
   [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 158 kB {0} [built]
       cjs require !!../../node_modules/css-loader/index.js!../../node_modules/sass-loader/index.js!./index.scss [8] ./assets/styles/index.scss 4:14-118
  [10] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       cjs require ../../node_modules/css-loader/lib/css-base.js [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 1:27-83
  [11] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4172-4253
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4276-4357
  [12] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 84 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4409-4492
  [13] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff 83 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4525-4607
  [14] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4639-4720
  [15] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg [9] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4756-4837
  [16] ./~/style-loader/addStyles.js 6.91 kB {0} [built]
       cjs require !../../node_modules/style-loader/addStyles.js [8] ./assets/styles/index.scss 7:13-69
  [17] ./spec spec\.js$ 182 bytes {1} [built]
       require.context ./ [0] ./spec/_all.js 6:10-50
  [18] ./spec/example.spec.js 173 bytes {1} [optional] [built]
       context element ./example.spec.js [17] ./spec spec\.js$
  [19] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 69.7 kB {2} [built]
       single entry bootstrap-sass [0] multi vendor

Running "shell:deploy-publish" (shell) task
.nojekyll Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 504,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 2999635,
  size: 0,
  blocks: 0,
  atime: 2017-05-16T19:41:30.000Z,
  mtime: 2017-05-16T19:41:30.000Z,
  ctime: 2017-05-16T19:41:30.000Z,
  birthtime: 2017-05-16T19:41:30.000Z }
[gh-pages (root-commit) 328fcdc] deploy task
 11 files changed, 13667 insertions(+)
 create mode 100644 .nojekyll
 create mode 100644 favicon.ico
 create mode 100644 index.html
 create mode 100644 public/448c34a56d699c29117adc64c43affeb.woff2
 create mode 100644 public/89889688147bd7575d6327160d64e760.svg
 create mode 100644 public/application.js
 create mode 100644 public/e18bbf611f2a2e43afc071aa2f4e1512.ttf
 create mode 100644 public/f4769f9bdb7466be65088239c12046d1.eot
 create mode 100644 public/fa2772327f55d8198301fdb8bcfc8158.woff
 create mode 100644 public/specs.js
 create mode 100644 public/vendor.js
To https://github.com/MarcyNash/Tic-Tac-Toe.git
 + 1cecbdf...328fcdc gh-pages -> gh-pages (forced update)
Removing .editorconfig
Removing .eslintrc.json
Removing .gitignore
Removing .jscsrc
Removing .jshintignore
Removing .jshintrc
Removing .remarkrc
Removing .scss-lint.yml
Removing CONTRIBUTING.md
Removing Gruntfile.js
Removing LICENSE
Removing README.md
Removing STYLE.md
Removing assets/
Removing forms.md
Removing grunt/
Removing index.js
Removing lib/
Removing package.json
Removing spec/
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

Done.

Execution Time (2017-05-16 15:41:23 UTC-4)
loading tasks           2.1s  ▇▇▇▇▇▇▇▇▇ 22%
webpack:build           3.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 34%
shell:git-push-master  367ms  ▇▇ 4%
webpack:build           1.2s  ▇▇▇▇▇▇ 13%
shell:deploy-publish    2.4s  ▇▇▇▇▇▇▇▇▇▇▇ 26%
Total 9.4s

~/wdi/projects/tic-tac-toe (master)
$ 
The url I'm using is https://marcynash.github.io/tic-tac-toe

The result is a 404 - file not found

**Comment by jordanallain** [comment]
https://marcynash.github.io/Tic-Tac-Toe/ works for me!

**Comment by BenGitsCode** [comment]
@MarcyNash Look closely at your url and Jordans.

You posted: `https://marcynash.github.io/tic-tac-toe`

he posted: `https://marcynash.github.io/Tic-Tac-Toe/`

**Comment by MarcyNash** [comment]
https://marcynash.github.io/Tic-Tac-Toe/ works! The T's in Tic-Tac-Toe must be capitalized.
