### ISSUE TITLE
Sign up, after submitting a sign up, 404 not found

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/game-project#711]
Error
jquery.js:9566 POST http://localhost:7165/[object%20Object]/sign-up/ 404 (Not Found)
send	@	jquery.js:9566
ajax	@	jquery.js:9173
signUp	@	api.js:7
onSignUp	@	events.js:10
dispatch	@	jquery.js:5206
elemData.handle	@	jquery.js:5014

It's saying the page config.apiOrigins + 'sign-up' can't be found?

```js
const config = require('../config')
// const store = require('../store')

const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigins + '/sign-up/',
    method: 'POST',
    data
  })
}
```

**Comment by scottyscripts** [comment]
can I see your index.js file

**Comment by Jcornmanhomonoff** [comment]
@RoryEnright status update?
