### ISSUE TITLE
Curl request to log out user returns 401 Unauthorized

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#713]
I am trying to write a curl request to log out a user, but my curl script returns 401 Unauthorized. 

I created a new user and signed in using curl, both successfully. 

When I sign in the user, I get the following response: 

HTTP/1.1 200 OK

And it returns the following object with token: 
```
{"user":{"id":77,"email":"lisa@lisa.com","token":"BAhJIiU4MjhlNWVkMDExNTJhNzBmYzk1ZjE5MmY2NGZlNDQ2ZAY6BkVG--a5c8d746c6db94c6b0976f8a0ac75ffee028b3bc"}}
```

However, when I make the following curl request, I get a 401 denied error. Here's the curl request: 

```
curl "http://tic-tac-toe.wdibos.com/sign-out/:77" \
  --include \
  --request DELETE

```

Here's the output at the terminal: 

```
HTTP/1.1 401 Unauthorized
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 16 May 2017 20:57:33 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Cache-Control: no-cache
X-Request-Id: cfbbaf6b-af64-46c8-a6b2-a6dea832c303
X-Runtime: 0.009050
Vary: Origin

HTTP Token: Access denied.
```

**Comment by lisawilliams** [comment]
I've read the API docs, which show the format as: 

```
`/sign-out/:id`

```
But it doesn't have it written out...so I'm not sure I have it in the right format.

**Comment by Jcornmanhomonoff** [comment]
It looks like you're getting an access denied error which typically means you ned to pass through some kind of token.

**Comment by lisawilliams** [comment]
OK, so I wrote a new curl request, but this also returns 401 Access Denied: 

```
curl "http://tic-tac-toe.wdibos.com/sign-out" \
  --include \
  --request DELETE \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "id": 77,
      "email": "lisa@lisa.com",
      "password": "333"
      "token":"BAhJIiU4MjhlNWVkMDExNTJhNzBmYzk1ZjE5MmY2NGZlNDQ2ZAY6BkVG--a5c8d746c6db94c6b0976f8a0ac75ffee028b3bc"
    }
  }'
```

**Comment by BenGitsCode** [comment]
I think you have a syntax error there. 

Review one of the curl requests from template, or another repo and pay close attention to the `\` and the trailing `,`'s

**Comment by lisawilliams** [comment]
Hi, Ben -- 
I did see that I was missing a trailing comma after "password": "333" and I fixed that. Interestingly, it no longer gives a 401 Access Denied response. Sadly, it gives us a 404 instead *chuckle* Here's the curl request, followed by the response: 

```
url "http://tic-tac-toe.wdibos.com/sign-out" \
  --include \
  --request DELETE \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "id": 77,
      "email": "lisa@lisa.com",
      "password": "333",
      "token":"BAhJIiViZjE4NjcxNWIyYmUxMTBhNWU4YjE3NDMxZmRmMWQzNQY6BkVG--4f1386d9aaf28c219f9675cc671bf0a204430fdb"
    }
  }'
```
And here's the response in the terminal: 

```
HTTP/1.1 404 Not Found
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 17 May 2017 00:29:02 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 1564
Connection: keep-alive
X-Request-Id: d2fc4235-b3af-4562-a76d-f842e49f8c63
X-Runtime: 0.009001
Vary: Origin

<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

```
It actually goes on to return the HTML and CSS of the entire 404 page, but I figured we didn't need that here.

**Comment by lisawilliams** [comment]
Okay, this approach, taken from the master branch of the [game-project-api repo ](https://git.generalassemb.ly/ga-wdi-boston/game-project-api/blob/master/scripts/sign-out.sh )also does not work. There is no response, the terminal just hangs: 

```
curl --include --request DELETE "http://tic-tac-toe.wdibos.com/sign-out/77" \
  --header "Authorization: Token token="BAhJIiViZjE4NjcxNWIyYmUxMTBhNWU4YjE3NDMxZmRmMWQzNQY6BkVG--4f1386d9aaf28c219f9675cc671bf0a204430fdb"

```

**Comment by lisawilliams** [comment]
Okay. Have been bashing at it for over an hour unsuccessfully.  Did find [this issue](https://github.com/ga-wdi-boston/full-stack-project/issues/619) which looked promising but doesn't actually help because it doesn't really talk about the shell scripts. Was hoping to make some progress this evening but made none (well, on this -- I added more forms and started setting up the /game file structure and reading ahead in the API reference).

**Comment by jordanallain** [comment]
> curl --include --request DELETE "http://tic-tac-toe.wdibos.com/sign-out/77" \
  --header "Authorization: Token token="BAhJIiViZjE4NjcxNWIyYmUxMTBhNWU4YjE3NDMxZmRmMWQzNQY6BkVG--4f1386d9aaf28c219f9675cc671bf0a204430fdb"

Looks like you have an extra `"` in that one

**Comment by scottyscripts** [comment]
@lisawilliams can you post your most recent curl script

**Comment by lisawilliams** [comment]
Jessica helped with a solution. Mainly syntax errors (misplaced double quote; URL needs ID at the end). 
Working version of sign out curl script: 

```
curl "http://tic-tac-toe.wdibos.com/sign-out/77" \
  --include \
  --request DELETE \
 --header "Authorization: Token token=BAhJIiVjNmMyNTViYTlmNGJjYzUyMDY3ZDk1ZGNiNzJkMWZjNwY6BkVG--837ad42237719ed8f0826a17a6ef30bfaa10d3e3"
```

It's also important to sign in the user and get a fresh token.   C[ode in my repo, with comments on what it returns, here](https://github.com/lisawilliams/tic-tac-toe/blob/development/assets/scripts/curl-scripts/sign-out.sh).
