### ISSUE TITLE
Ajax - Unable to make update game call - 400 bad request

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#717]
Attempting to make an update game call after a user has selected the first tile in a newly created game, 400 bad request returned. I am able to curl the request successfully. 

I am console logging the store object that I'm using to build the json object for the request, and the data looks correct. 

```js
const updateGame = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data: '{"game": {"cell": {"index": store.game.cell.index, "value": "store.game.cell.value"}, "over": store.game.over}}'
  })
  .then((response) => {
    console.log('This is the response after update game: ', response)
    store.game = response.game
    store.player_o = response.player_o
    console.log('This is the store after update game: ', store)
  })
}
```

**Comment by artpylon** [comment]
Fixed one issue I noticed in the above code, quotes around store.game.cell.value, but still getting 400 bad request on retest of the code

**Comment by artpylon** [comment]
Notice that my index value in the store object is in quotes... Seems like an issue, but I can't see where those are being included in my code
<img width="686" alt="screen shot 2017-05-17 at 10 45 47 am" src="https://cloud.githubusercontent.com/assets/26583372/26160042/2380d1f0-3aee-11e7-8832-0cd5fdd88684.png">

**Comment by benjimelito** [comment]
I wouldn't focus on the store value being in quotes, I don't believe that's your problem. One thing I would point out though is that entire value you are assigning to your `data` key is in quotes

**Comment by scottyscripts** [comment]
```
{"game": 
  {"cell":  {
      "index": store.game.cell.index, 
      "value": "store.game.cell.value"
       }, 
      "over": store.game.over
    }
}
```
What you are currently sending.
do you want the cell to have a property of over?
Does this match the data structure of your working curl request?

**Comment by artpylon** [comment]
Resolved. Thanks.

**Comment by benjimelito** [comment]
Cool, please make sure to update this issue to note what it was that solved your issue before closing 👍

**Comment by artpylon** [comment]
Resolution involved both changes mentioned above by Ben and Scott. Entire data object was in quotes, and my brackets included over within the cell object. fixed both
