### ISSUE TITLE
JS - isGameOver function returning opposite boolean from expected result

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#718]
I created this function to tell if any of the conditions for the game to be over had been met. It's returning the opposite boolean than expected, i.e. it's returning isGameOver === true after the first move.
```js
const isGameOver = function () {
  if (store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[3] + store.game.cells[4] + store.game.cells[5] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[6] + store.game.cells[7] + store.game.cells[8] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[0] + store.game.cells[3] + store.game.cells[6] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[1] + store.game.cells[4] + store.game.cells[7] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[2] + store.game.cells[5] + store.game.cells[8] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[0] + store.game.cells[4] + store.game.cells[8] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[2] + store.game.cells[4] + store.game.cells[6] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.moves > 8) {
    store.over = true
    return true
  } else return false
}
```

**Comment by artpylon** [comment]
Found a few issues with the original code, updated above.

**Comment by benjimelito** [comment]
Can you try `console.log`ing your `store.game.cells` before getting to this point to see what it looks like?

**Comment by artpylon** [comment]
Yes, store.game.cells looks correct prior to update game call. 
<img width="646" alt="screen shot 2017-05-17 at 11 05 03 am" src="https://cloud.githubusercontent.com/assets/26583372/26161068/dd775cbc-3af0-11e7-83a8-ad467e5e20c7.png">

**Comment by scottyscripts** [comment]
take a look at the last else statement, is that syntax correct?

**Comment by artpylon** [comment]
Added brackets and retested, isGameOver still returns true after first move:

```js
const isGameOver = function () {
  if (store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[3] + store.game.cells[4] + store.game.cells[5] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[6] + store.game.cells[7] + store.game.cells[8] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[0] + store.game.cells[3] + store.game.cells[6] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[1] + store.game.cells[4] + store.game.cells[7] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[2] + store.game.cells[5] + store.game.cells[8] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[0] + store.game.cells[4] + store.game.cells[8] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.game.cells[2] + store.game.cells[4] + store.game.cells[6] === 'xxx' || 'ooo') {
    store.over = true
    return true
  } else if (store.moves > 8) {
    store.over = true
    return true
  } else { return false }
}
```

**Comment by scottyscripts** [comment]
this syntax in your if statement isn't checking what you think it's checking. You are actually checking if `store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'xxx'` OR `if 'ooo'`  which will always return true.

**Comment by artpylon** [comment]
@sdavidson140 my game array is empty strings by default, so only pieces that have been played will show x's or o's, so I think that part works?

Jess and I discovered that I was actually creating a dupe over attribute, i needed to specify store. game.over, instead of store.over

**Comment by scottyscripts** [comment]
@artpylon That may be a separate issue. I was trying to make the point that in JavaScript you can't check if an expression equals one or two values the way you were doing it. Take a look at this. http://stackoverflow.com/questions/9121395/javascript-the-prettiest-way-to-compare-one-value-against-multiple-values
Your if statements as is are checking if `store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'xxx'`. It is NOT checking if `store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'ooo'` It is instead checking if 'ooo' is true. Since it's a string, it will always be true. Let me know if you have questions about this.

**Comment by scottyscripts** [comment]
if you wanted to check both you could check each expression individually like 
``` if ((store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'xxx') || (store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'ooo'))
```
