### ISSUE TITLE
how will i Get the game i wrote the following code in api 

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/game-project#719]
````
const getGamesForUser = function () {
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.userId,
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}
the response on the console is.
```

tic-tac-toe.wdibos.com/change-password/102:1 PATCH http://tic-tac-toe.wdibos.com/change-password/102 400 (Bad Request)
ui.js:30 Object {readyState: 4, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}

**Comment by Jcornmanhomonoff** [comment]
It looks like the response you're getting is an invalid change password attempt. Are you asking about change password or getting a game?

**Comment by isharma-sharma** [comment]
getting the game  change password is working

**Comment by BenGitsCode** [comment]
It looks like the console response is from a change password PATCH but the code you have is a GET for games. 

Have you tested your GET games in curl requests?

**Comment by isharma-sharma** [comment]
yep i tried 
```~/wdi/newproject/project1 (startinggame)
$ curl "http://tic-tac-toe.wdibos.com/games/102"
HTTP Token: Access denied.
~/wdi/newproject/project1 (startinggame)
$ --include \
> --request GET \
> --header "Authorization: Token token=BAhJIiU1OWVhOGVkNzA5OWRkMDVmNzA1ZjdhNmUzZmEyNzM2ZAY6BkVG--b9b8cf7d8f27a35ab3b7f1a43c91fc311fb8d012" \
> 
-bash: --include: command not found
~/w

**Comment by Jcornmanhomonoff** [comment]
@isharma-sharma can you paste in _only_ your curl request please? _Not_ the response.

**Comment by isharma-sharma** [comment]
curl "http://tic-tac-toe.wdibos.com/games/102"
--include \
--request GET \
--header "Authorization: Token token=BAhJIiU1OWVhOGVkNzA5OWRkMDVmNzA1ZjdhNmUzZmEyNzM2ZAY6BkVG--b9b8cf7d8f27a35ab3b7f1a43c91fc311fb8d012" \

**Comment by Jcornmanhomonoff** [comment]
You're missing `\` at the end of your include & GET lines. Let's start with that. Once you add those syntax changes, throw it in the console and paste both your new script as well as your response.

**Something to keep in mind:** Your token changes every time you log in.
Make sure that you're: 
   **A**) logged in
   **B**) using the most recent token

**Comment by isharma-sharma** [comment]
i tried the curl with the recent token


```-bash: --include: command not found

**Comment by Jcornmanhomonoff** [comment]
Please paste both your new script as well as your response

**Comment by isharma-sharma** [comment]
```
const getGamesForUser = function () {
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.userId,
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}
```

response:
```Object {userToken: "BAhJIiU0MGI4ODI2ZDU4NGE5MWI4ZjA0NTBkMmVmYzVmZTVjMgY6BkVG--2389546435f841361f379bacea1ca196422e8cbf", userId: 102}
ui.js:11 undefined
jquery.js:9566 PATCH http://tic-tac-toe.wdibos.com/change-password/102 400 (Bad Request)
send @ jquery.js:9566
ajax @ jquery.js:9173
changePassword @ api.js:31
onGetGamesForUser @ event.js:35
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
ui.js:30 Object {readyState: 4, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}

**Comment by Jcornmanhomonoff** [comment]
What you just posted is not a curl request. Please paste in the new curl request with the edits we were talking about above ☝️

**Comment by isharma-sharma** [comment]
here it is 
````
curl "http://tic-tac-toe.wdibos.com/games/102"
--include \
--request GET \
--header "Authorization: Token token=BAhJIiViYmM1MmFhZDdiZWM5ZjBmMWYwNDgwYTM5NGE4NDY2ZgY6BkVG--6c0c02da37743734b235501826e6ce586d55b4af" \


i

**Comment by Jcornmanhomonoff** [comment]
So when you run that code, what's the response you're getting in the terminal?

**Comment by isharma-sharma** [comment]
I m stuck in this for more than two hours  

every time i try with the new token it gives be 
``
-bash: --include: command not found
