### ISSUE TITLE
Sign Out Error

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/game-project#72]
Hi, I am trying to have my ajax request sign out the user, but I am getting an error message that the property id of user is undefined. I used the debugger and it is pointing at the "app.user.id" part of the url. I'm stumped because I have an app-data.js similar to the exercise that we did last friday to store the id and token of a user. I'm signed in as a user and i can see it in my console. My html is also referencing the correct id for sign-out.

`````` html
<form id="sign-out">
          <button type="submit" class="btn btn-default">Sign Out</button>
          </form>

```js

const app = require('../app-data');

///this is my api file
const signOut = (success, failure) => {
  //if(!app.user) bad;
  debugger;
  $.ajax({
    method: "DELETE",
    url: app.api + '/sign-out/' + app.user.id,
    headers: {
      Authorization: 'Token token='+ app.user.token,
    },
  })
  .done(success)
  .fail(failure);
};

///this is my ui.js file
const app = require('../app-data');

const signInSuccess = (data) => {
  app.user = data.user;
  console.log(data);
};

///This is in my app-data file
const app = {
  api: 'http://tic-tac-toe.wdibos.com',
};
``````

**Comment by laurenfazah** [comment]
@rdelvallej32 what is it saying the value of `app.user.id` is when paused by the debugger?

**Comment by rdelvallej32** [comment]
It's saying property id of user is undefined

**Comment by RDegnen** [comment]
Can you open up the user object in the debugger and see if it has an id property on it?

**Comment by RealWeeks** [comment]
Also what directory is your app-data in? this: `const app = require('../app-data');` is different from this `const app = require('./app-data');`

**Comment by rdelvallej32** [comment]
The app-data is saved outside of the directory, that my api-file lives in. When i check the id property for the object it says undefined.

**Comment by RDegnen** [comment]
Does the user object itself exist?

**Comment by rdelvallej32** [comment]
No it doesn't, but it does when I sign in
