### ISSUE TITLE
Jquery - Event is undefined when attempting to show X/O on gameboard UI

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#721]
When a user selects a tile I am successfully calling the API to update the game, .then I want to call a UI function to update the gameboard to show the user's piece. I am attempting to pass the event to then UI function so it knows which tile to update. 

onSelectTile Function 
```js
const onSelectTile = function (event) {
  console.log('this is the tile event data id', this.dataset.id)
  event.preventDefault()
  const data = getFormFields(event.target)
  store.game.cell = {}
  store.game.cell.index = this.dataset.id
  console.log(store.game.cell.index)
  turn()
  isGameOver()
  store.moves++
  console.log('this is store before update game call ', store)
  console.log('this is event before update game call ', event)
  displayGameResult(data, event)
  // api.updateGame(data)
  //   .then(ui.selectTileSuccess)
  //   .catch(ui.selectTileFailure)
  store.xTurn = !store.xTurn
  console.log('player x turn ', store.xTurn)
  console.log('moves ', store.moves)
}
```
displayGameResult (calls the API, then calls the UI function)
```js
const displayGameResult = function (data, event) {
  if (store.game.over === false) {
    api.updateGame(data, event)
      .then(ui.selectTileSuccess)
      .catch(ui.selectTileFailure)
  } else {
    api.updateGame(data, event)
      .then(ui.endGameSuccess)
      .catch(ui.endGameFailure)
  }
}
```

UI function:

```js
const selectTileSuccess = (event) => {
  console.log('about to place tile, event.target is ', event.target)
  $(event.target).text(store.game.value)
}
```

**Comment by benjimelito** [comment]
What does `api.updateGame` return?

**Comment by MicFin** [comment]
Also, I do not think you want to pass the event around that much.  You should probably only interact with the `event` object in the `onSelectTile` function and should be passing a property of the event object that you want (maybe it's `event.target`) to the next function `api.updateGame`.

**Comment by artpylon** [comment]
Thanks, I've changed it so that my ui function reads off of the game object in store. It's finding this info correctly. I'll open a separate issue for a subsequent bug.
