### ISSUE TITLE
JS/API: Where is user token data being stored upon signup? How do we get the token back?

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#722]
So, I have a function, signOut, in my API.js that is intended to pass data from the user object to the API to log out the user.  Here it is: 

```
const signOut = () => {
  return $.ajax({
    url: app.host + '/sign-out/' + store.user.id,
// ^^^ fails here when store returns undefined  ^^^
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

I have an event handler in events.js,  signIn, that runs and returns the following object: 

```

Object {credentials: Object, submit: "Sign in"}
credentials:
Object
email: "lisa@placeblogger.com"
password: "333"
token:"BAhJIiU0ZDliNzc0MmE4NmE0N2NhZWJjNTY1ZGExZTFjNDEwZQY6BkVG--6843863146c04fd90c9f39de052063f2efb97262"

```
Console.log says 'sign out ran' when I click sign out, but the debugger stops and gives the following error: 

```
"Cannot read property 'id' of undefined"
```
in response to 'url: app.host + '/sign-out/' + store.user.id,'

I made a commit to store and share the current state of my auth scripts (event.js, api.js, and ui.js) which you can see [here](https://github.com/lisawilliams/tic-tac-toe/tree/development/assets/scripts/auth). 

Stuff I did to try to solve this already: 
* Delete store from signOut (leaving .user.id and .user.token)
* Refer to API docs
* Refer to auth-token-api repo
* Looked at the [following issue](https://github.com/ga-wdi-boston/game-project/issues/588) which appeared similar and made sure I ran onSignIn every time my page refreshed and before running onSignOut.

**Comment by Jcornmanhomonoff** [comment]
What is `user` in this case? How might we find that out?

**Comment by BenGitsCode** [comment]
If it fails when store returns undefined, go back a step—when should `user` be defined? Where is the break between you setting the value of `user` and trying to access that value?

**Comment by lisawilliams** [comment]
I tried to console log store.user.id in the event handler, but it just doesn't recognize "store." I was looking at [this issue](https://github.com/ga-wdi-boston/game-project/issues/686) (wish they had closed it with the solution!)

**Comment by lisawilliams** [comment]
Well, the object has to get into store.js somehow, yes?

**Comment by scottyscripts** [comment]
Are you defining a variable named store in that file using `require`?
Yes, the object gets into the store object only when you put it there. 
At any point are you assigning the store object a user property?
If not, you need to do that, so you can access information about the user at a later point.
 When would be a good point to store information about the user?

**Comment by lisawilliams** [comment]
@Jcornmanhomonoff @BenGitsCode @sdavidson140  excellent suggestions. Both api.js and ui.js now require store.js like so: 

```
const store = require('./../store')

```

But there also has to be some way for the user object to get in there. So, in events.js, the onSignIn function now reads like this: 

```
const onSignIn = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log(data)
  api.postSignIn(data)
    .then(ui.onSignInSuccess)
    .catch(ui.onSignInFailure)
}

```
But wait, that doesn't seem to store anything, does it?  But it does call two other functions from ui.js, and one of those stores the user object like so: 

```
const onSignInSuccess = (response) => {
  console.log('yayyyyy we did it')
  console.log(response)
  store.user = response.user
  console.log('store.user console log data is ' + store.user)
}
```
So now the user object is in store.js.  But how does our sign out function use it? In a very similar way to the way onSignIn stores the data: 

```
const onSignOut = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log(data)
  api.signOut(onSignIn.data)
  .then(ui.signOutSuccess)
  .catch(ui.signOutFailure)
}
```
and there's a corresponding function in ui.js, signOutSuccess, which reads like this; 

```
const signOutSuccess = () => {
  console.log('signOut success ran. and nothing was returned')
  store.user = null
}
```
So, it reaches the user object in store.js and makes it null. 

Not only does this work, I think I actually understood it. Please don't tell Jeff that I used the U word. ;)
