### ISSUE TITLE
jquery - unable to inject X or O into the tile div

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#723]
```js
const selectTileSuccess = () => {
  console.log('store index is ', store.game.cell.index)
  console.log('store value is ', store.game.cell.value)
  $('.tile').children().eq(store.game.cell.index).html('<p>store.game.cell.value</p>')
}
```

I'm attempting to add an X or O to the board, but finding the child div (the tile on the gameboard) of the container div, by the index that I have stored in the store object. 

My console.logs in the above function show that the index and value return as expected before the jquery line. 

I've tried both .html('<p>store.game.cell.value</p>') and .text, neither shows the piece in the tile.

<img width="924" alt="screen shot 2017-05-17 at 12 44 28 pm" src="https://cloud.githubusercontent.com/assets/26583372/26165709/ecfe506a-3afe-11e7-9e29-a1f2b85c6dd3.png">

**Comment by Jcornmanhomonoff** [comment]
@artpylon Can you past in the exact code you've tried please?

**Comment by artpylon** [comment]
This is the .text method I tried:

**Comment by artpylon** [comment]
```js
const selectTileSuccess = () => {
  console.log('store index is ', store.game.cell.index)
  console.log('store value is ', store.game.cell.value)
  $('.tile').children().eq(store.game.cell.index).html('<p>store.game.cell.value</p>')
  $('.tile').children().eq(store.game.cell.index).text(store.game.cell.value)
}
```
I put the alternate method i tried under the other

**Comment by sdavidson140** [comment]
You can verify that you are using the correct jQuery selector you want by taking a look in the console. What happens when you enter `$('.tile').children().eq(store.game.cell.index)` in the console? Is it selecting what you think it is?

**Comment by scottyscripts** [comment]
What happens if you log your selector to the console inside of that function? Is it selecting what you expect it to?

**Comment by artpylon** [comment]
@sdavidson140 it looks like it's possibly interpreting the index as length instead of index... which conflicts with my reading of the .eq() guide: https://api.jquery.com/eq/

```js
const selectTileSuccess = () => {
  console.log('store index is ', store.game.cell.index)
  console.log('store value is ', store.game.cell.value)
  console.log($('.tile').children().eq(store.game.cell.index))
  $('.tile').children().eq(store.game.cell.index).html('<p>store.game.cell.value</p>')
  $('.tile').children().eq(store.game.cell.index).text(store.game.cell.value)
}
```
<img width="732" alt="screen shot 2017-05-17 at 1 38 57 pm" src="https://cloud.githubusercontent.com/assets/26583372/26167913/4491e0ec-3b06-11e7-9642-779210addca0.png">

**Comment by sdavidson140** [comment]
is the index an integer or a string?

**Comment by artpylon** [comment]
OK, got it! Moved the jquery to the onSelectTile function, used this instead of the .eq() method.

```js
const onSelectTile = function (event) {
  console.log('this is the tile event data id', this.dataset.id)
  event.preventDefault()
  const data = getFormFields(event.target)
  store.game.cell = {}
  store.game.cell.index = this.dataset.id
  console.log(store.game.cell.index)
  turn()
  isGameOver()
  store.moves++
  $(this).text(store.game.cell.value)
  displayGameResult(data)
  // api.updateGame(data)
  //   .then(ui.selectTileSuccess)
  //   .catch(ui.selectTileFailure)
  store.xTurn = !store.xTurn
  console.log('player x turn ', store.xTurn)
  console.log('moves ', store.moves)
}
```
