### ISSUE TITLE
git question

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/game-project#724]
I want to revert to a previous version (back to last night's commit) of the index.html file. Looked at previous issues and googled to figure out what to do and I'm confused.

What I want is to see the difference between the file as it is now in my development branch and what it looked like in the commit from last night. Don't know if I pushed last night's commit to master.

**Comment by jordanallain** [comment]
if you push the branch up to github there are some really easy ways to check out the files from different commits. have you pushed the branch you were working on to github?

**Comment by MarcyNash** [comment]
I found the diff information on github and I can use that!
