### ISSUE TITLE
js - isGameOver function not reading game.cells array as expected

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#726]
This might require an in person walkthrough. I think this might be an issue with the order of my functions and have added console logging to test that out, but can't see the issue. 

So, I have a function that evaluates whether the game is over by checking the contents of the store.game.cells object. It looks at the 9 possible scenarios where the game should end, i.e. there are 3 x's or o's in the verticals, horizontals, diagonals, or the board is full. That function looks like this:

```js
const isGameOver = function () {
  if (store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'xxx' || store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.game.cells[3] + store.game.cells[4] + store.game.cells[5] === 'xxx' || store.game.cells[3] + store.game.cells[4] + store.game.cells[5] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.game.cells[6] + store.game.cells[7] + store.game.cells[8] === 'xxx' || store.game.cells[6] + store.game.cells[7] + store.game.cells[8] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.game.cells[0] + store.game.cells[3] + store.game.cells[6] === 'xxx' || store.game.cells[0] + store.game.cells[3] + store.game.cells[6] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.game.cells[1] + store.game.cells[4] + store.game.cells[7] === 'xxx' || store.game.cells[1] + store.game.cells[4] + store.game.cells[7] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.game.cells[2] + store.game.cells[5] + store.game.cells[8] === 'xxx' || store.game.cells[2] + store.game.cells[5] + store.game.cells[8] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.game.cells[0] + store.game.cells[4] + store.game.cells[8] === 'xxx' || store.game.cells[0] + store.game.cells[4] + store.game.cells[8] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.game.cells[2] + store.game.cells[4] + store.game.cells[6] === 'xxx' || store.game.cells[2] + store.game.cells[4] + store.game.cells[6] === 'ooo') {
    store.game.over = true
    return true
  } else if (store.moves > 8) {
    store.game.over = true
    return true
  } else { store.game.over = false }
}
```
When testing this, I am logging on of the possible win scenarios then placing x's in each of those spots. See the win array console log below.

<img width="1249" alt="screen shot 2017-05-17 at 2 34 13 pm" src="https://cloud.githubusercontent.com/assets/26583372/26170231/ad51d256-3b0e-11e7-88d7-d6b050b0a011.png">

**Comment by artpylon** [comment]
When the win scenario is met, the isGameOver function fails to flip the store.game.over boolean to true.
<img width="1257" alt="screen shot 2017-05-17 at 2 41 25 pm" src="https://cloud.githubusercontent.com/assets/26583372/26170296/f22d74e8-3b0e-11e7-8478-93842eef8c4a.png">

**Comment by artpylon** [comment]
I've also tried logging the result of invoking the isGameOver function, this returns undefined. 

From testing, the isGameOver function never flips the store.game.over boolean, so I don't think it's order of operations.

**Comment by Jcornmanhomonoff** [comment]
When are you calling `isGameOver`?

**Comment by artpylon** [comment]
I'm calling it immediately after calling the update game api: 

```js
const onSelectTile = function (event) {
  console.log('this is the tile event data id', this.dataset.id)
  event.preventDefault()
  const data = getFormFields(event.target)
  store.game.cell = {}
  store.game.cell.index = this.dataset.id
  console.log(store.game.cell.index)
  turn()
  store.moves++
  $(this).text(store.game.cell.value)
  $(this).off()
  // displayGameResult(data)
  api.updateGame(data)
    .then(ui.selectTileSuccess)
    .catch(ui.selectTileFailure)
  isGameOver()
  store.xTurn = !store.xTurn
  console.log('player x turn ', store.xTurn)
  console.log('moves ', store.moves)
  console.log('this is the store after select tile ', store)
  console.log('win array ', store.game.cells[0] + store.game.cells[1] + store.game.cells[2])
  console.log('result of isgameover function ', isGameOver())
}
```

**Comment by tvcrawley** [comment]
If you comment out the logic of `isGameOver` and enter a console.log. Is that displayed in the console?

**Comment by artpylon** [comment]
@tvlangley Yes, added a console log inside the isGameOver function and that appear during a test.

**Comment by tvcrawley** [comment]
Ok, so we know the function is being called. How about changing the console.log to include one of the conditionals you're testing for (e.g. `store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'xxx' || store.game.cells[0] + store.game.cells[1] + store.game.cells[2] === 'ooo'`) and see if that renders a boolean.

**Comment by artpylon** [comment]
hmmm... so that also worked:
<img width="1240" alt="screen shot 2017-05-17 at 3 21 29 pm" src="https://cloud.githubusercontent.com/assets/26583372/26171906/909748f2-3b14-11e7-82bd-52ab54ee0fbe.png">

**Comment by tvcrawley** [comment]
Good, next let's run the entirety of the first if statement in and console.log `store.game.over` before the return
