### ISSUE TITLE
update game  is not working . curl is returning 400 bad request

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/game-project#727]
````
curl "http://tic-tac-toe.wdibos.com/games" \
--include \
--request PATCH \
--header "Content-Type: application/json" \
--header "Authorization: Token token=BAhJIiUwNjQ2Y2RhMTA5ZGM4OWZkMjBkNTVlZDMxMTg3YjE4NAY6BkVG--a702276c99763f454d5d8746a6fba07e30fa4d23" \
--data '{
  "games": {
    "id": "602",
    "cell": ["","","","","","","","",""],
    "over": false,
    "player_x":  {
     "id": 102 ,
     "email": a@gmail
   },
  "player_o": {
    "id": 134,
    email:"b@gmail"
  }
  }
}'

**Comment by Jcornmanhomonoff** [comment]
@isharma-sharma double check your syntax. For example: in one place you have quotes around email and in another you don't

**Comment by isharma-sharma** [comment]
same 400 errors
after placing quotes

**Comment by Jcornmanhomonoff** [comment]
Can you post your new code please?

**Comment by isharma-sharma** [comment]
curl "http://tic-tac-toe.wdibos.com/games/672" \
--include \
--request PATCH \
--header "Content-Type: application/json" \
--header "Authorization: Token token=BAhJIiUwNjQ2Y2RhMTA5ZGM4OWZkMjBkNTVlZDMxMTg3YjE4NAY6BkVG--a702276c99763f454d5d8746a6fba07e30fa4d23" \
--data '{
  "games": {
    "id": "602",
    "cell": ["","","","","","","","",""],
    "over": false,
    "player_x":  {
     "id": "102" ,
     "email": "a@gmail"
   },
  "player_o": {
    "id": "134",
    email:"b@gmail"
  }
  }
}'

**Comment by Jcornmanhomonoff** [comment]
@isharma-sharma double check your syntax. For example: in one place you have quotes around email and in another you don't

**Comment by isharma-sharma** [comment]
i am finding quotes in right places

**Comment by Jcornmanhomonoff** [comment]
please compare `player_x` object to your `player_o` object

**Comment by Jcornmanhomonoff** [comment]
Use this as a guide:
```js
{
  "game": {
    "id": 1,
    "cells": ["","","","","","","","",""],
    "over":false,
    "player_x": {
      "id": 1,
      "email": "and@and.com"
      },
    "player_o": {
      "id": 3,
      "email": "dna@dna.com"
    }
  }
}
```

**please note that this is not exact to what you will have**

**Comment by danman01** [comment]
@isharma-sharma how's this issue going? If you have resolved it, can you report back and close the issue?

**Comment by isharma-sharma** [comment]
yes done with this
