### ISSUE TITLE
get game show game is not working things are working when i do by curl request but not working on console

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/game-project#728]
api code for get game for user
````
const getGamesForUser = function () {
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}


code for show game for user
````

const showGame = function () {
  console.log(store.gameId)
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.gameId,
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}

**Comment by isharma-sharma** [comment]
i think my button is not working as their is no response when i press it

**Comment by isharma-sharma** [comment]
it is working now in class,  i think there is some issue with server because i didn't even touch the code and how its working now

**Comment by jordanallain** [comment]
is the ajax call succeeding now?

**Comment by isharma-sharma** [comment]
on my url i m seeing below address

`http://localhost:7165/?submit=loading.......`

**Comment by MicFin** [comment]
Can you please share the `index.html`, `scripts/index.js` and `scripts/auth/events.js` (or whatever file the click event is being defined)?
