### ISSUE TITLE
i m not getting how to do update game not even an idea how to do that

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/game-project#729]
i wrote the curl request which was working  but dont now how to do in ajax

**Comment by scottyscripts** [comment]
What specifically about the ajax are you unsure about? Are you unsure of what data to send? Do you have an event that will fire the update game action?

**Comment by isharma-sharma** [comment]
i have but i m not sure it is correct not getting how to connect update with cell click 

```const onUdateGame = function (index, value, over) {
    event.preventDefault()
  api.updateGame(index, value, over)
    .then(ui.updateGamesuccess)
    .catch(ui.updateGamefailure)
 }

**Comment by scottyscripts** [comment]
So it sounds like you want to listen for a click event, and pass the above function as a callback. Is there a place where you are already registering these event listeners?

**Comment by isharma-sharma** [comment]
I m not getting how to add the click event to the update

**Comment by scottyscripts** [comment]
@isharma-sharma How's it going with the update?

**Comment by isharma-sharma** [comment]
still on it not completed  got confused in game joined   and game update

**Comment by isharma-sharma** [comment]
not getting index fixed   on the game board

**Comment by benjimelito** [comment]
How are you trying to pass in the index? Did you try changing your HTML `id`s to `data-id`s?

**Comment by isharma-sharma** [comment]
i have changed my html id to data-id
but how to use i have no idea i was trying to store the cell value by response and it didn't work

**Comment by isharma-sharma** [comment]
by doing things my player change  is not working
