### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#73]
Doesn't appear that my CSS styling are working. I'm doing something wrong. I just don't know what it is. I've tried several iterations and finally realized it's not rendering onto my html file. I have it under style.css.

**Comment by RealWeeks** [comment]
Why aren't you coding in your styles.scss file? It's already linked up for you.  Try moving your styles in there.

**Comment by ghost** [comment]
I'm creating that file?

**Comment by laurenfazah** [comment]
It should already be there for you in /assets/styles/.

**Comment by ghost** [comment]
It is not in mine.

**Comment by ghost** [comment]
I have index.scss

**Comment by laurenfazah** [comment]
That's the one - import everything into there then close if that fixes it, or feel free to follow up if it doesn't.

**Comment by ghost** [comment]
lol...I'll work it there now. Although I felt like I tried that before. I'll give it another go.

**Comment by ghost** [comment]
@laurenfazah not getting the CSS to work in index.scss

**Comment by laurenfazah** [comment]
Was it working before?

**Comment by RealWeeks** [comment]
Also do you have linter errors?

**Comment by ghost** [comment]
I was working on the CSS last night and quit that to do the javascript. So I quickly checked it just out of curiosity and it's not working. I don't have any linter errors.

**Comment by RDegnen** [comment]
are there any errors in your console?

**Comment by ghost** [comment]
I have errors in console that don't have to do with css.

**Comment by laurenfazah** [comment]
@bryansarnold call me over when your linter errors are clear and I'll help diagnose in person.
