### ISSUE TITLE
Ajax - Unable to update api with over: true

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#731]
After I've determined that a game is over I flip the over boolean in my local store object to true. Then, I call the update game API again. I can see in my logging that locally the over value for the ended game is true. 

However, when I call the index api to get all games for a user, all over flags are false. 

```js
const gameOver = function () {
  if (store.game.over === true) {
    $('#zero').off('click', events.onSelectTile)
    $('#one').off('click', events.onSelectTile)
    $('#two').off('click', events.onSelectTile)
    $('#three').off('click', events.onSelectTile)
    $('#four').off('click', events.onSelectTile)
    $('#five').off('click', events.onSelectTile)
    $('#six').off('click', events.onSelectTile)
    $('#seven').off('click', events.onSelectTile)
    $('#eight').off('click', events.onSelectTile)
    gameOverUI()
    api.endGame()
      .then(ui.endGameSuccess)
      .catch(ui.endGameFailure)
  }
}
```

ajax call to update the game:
```js
const endGame = function () {
  console.log('endGame api store is ', store)
  return $.ajax({
    url: config.apiOrigin + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data: {"game": {"cell": {"index": store.game.cell.index, "value": store.game.cell.value}}, "over": store.game.over}
  })
  // .then((response) => {
  //   store.game.cells = response.game.cells
  // })
}
```

**Comment by benjimelito** [comment]
So just to be clear : The `endGame` function is firing successfully, `store.game.over` contains the correct value, and the PATCH request is going through successfully?

**Comment by artpylon** [comment]
Yes

**Comment by benjimelito** [comment]
Are you calling the index using a `curl` script, or from within the app?

**Comment by artpylon** [comment]
Screenshots below show:
1. store.game.over = true, just before the endgame update call is made(game 1013):
<img width="603" alt="screen shot 2017-05-18 at 10 04 45 am" src="https://cloud.githubusercontent.com/assets/26583372/26206094/d30cad60-3bb1-11e7-898f-118453317951.png">

2. games array after call is made, shows game 1013 over as false
<img width="746" alt="screen shot 2017-05-18 at 10 05 07 am" src="https://cloud.githubusercontent.com/assets/26583372/26206120/ea263aca-3bb1-11e7-8422-614a4a0217bc.png">

**Comment by artpylon** [comment]
converted store.game.over values to 1's and 0's, this seems to have resolved the issue
