### ISSUE TITLE
Getting a DELETE request when I want a GET request

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#732]
The code executes a DELETE request when I want it to execute a GET request.
Curl Request:

```
curl --include --request GET http://tic-tac-toe.wdibos.com/index/
```
Error message:
```
tic-tac-toe.wdibos.com/sign-out/159:1 DELETE http://tic-tac-toe.wdibos.com/sign-out/159 401 (Unauthorized)
```

**Comment by scottyscripts** [comment]
Take another look at the API endpoints for the game https://github.com/ga-wdi-boston/game-project-api

**Comment by scottyscripts** [comment]
Is `/index` a valid path?

**Comment by ghost** [comment]
edited curl request to 
```
curl --include --request GET http://tic-tac-toe.wdibos.com/games/{?=over}
```
Still get the same message

**Comment by ghost** [comment]
Fixed error due to copying and pasting the api.signout
