### ISSUE TITLE
404 error on show game GET request

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#735]
When I run create game I get an error that reads:
```
GET http://tic-tac-toe.wdibos.com/games/:idundefined 404 (Not Found)
```
my cur request does work i think(I get an unauthorized error when not signed in) but here it is anyway:
```
curl "http://tic-tac-toe.wdibos.com/games:id" \
--include \
--request GET \
--header "Content-Type: application/json" \
--header "Authorization: Token token=${TOKEN}" \
```

**Comment by scottyscripts** [comment]
Take a look at the path `http://tic-tac-toe.wdibos.com/games/:idundefined` do you see anything that shouldn't be there at the end? Is something not defined?

**Comment by ghost** [comment]
Solved the undefined mystery, it was code in my api file, but I still get the 404 error
```
GET http://tic-tac-toe.wdibos.com/games/:id 404 (Not Found)
```

**Comment by jordanallain** [comment]
the `:id` is how we specify in a route that an id will be passed in. when making the actual request there should be an id number instead of the `:id`

**Comment by ghost** [comment]
Thank you, I changed the url to the url below and it worked
```
"http://tic-tac-toe.wdibos.com/games/${ID}"
```
