### ISSUE TITLE
getFormFields is not returning what I expect in onUpdateGame

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/game-project#736]
I have set up each game cell as a form --

<form id="cell0">
          <div data-indexID="0" class="col-xs-4 col-md-4 box cell-height ttt-cell">
            <input name="game[cell][index]" type="text" value="0" hidden="true">
            <input name="game[cell][value]" type="text" class="cell-height" value="">
            <input name="game[over]" type="text" value="0" hidden="true">
          </div>
        </form>

I set an event in  onDocumentReady --

  $('#cell0').on('click', onUpdateGame)

const onUpdateGame = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  console.log('onUpdateGame  ')
  // console.log('Got to onUpdateGame')
  // console.log(data)
  api.update(data)
  .then(ui.onUpdateGameSuccess)
  .catch(ui.onUpdateGameFailure)
}

The data object returned form getFormFields is not what I expect.

**Comment by scottyscripts** [comment]
can you send code showing what one of these forms looks like please

**Comment by MarcyNash** [comment]
Sorry, I thought I did.

<form id="cell0">
          <div data-indexID="0" class="col-xs-4 col-md-4 box cell-height ttt-cell">
            <input name="game[cell][index]" type="text" value="0" hidden="true">
            <input name="game[cell][value]" type="text" class="cell-height" value="">
            <input name="game[over]" type="text" value="0" hidden="true">
          </div>
        </form>

**Comment by MarcyNash** [comment]
<form id="cell0">
          <div data-indexID="0" class="col-xs-4 col-md-4 box cell-height ttt-cell">
            <input name="game[cell][index]" type="text" value="0" hidden="true">
            <input name="game[cell][value]" type="text" class="cell-height" value="">
            <input name="game[over]" type="text" value="0" hidden="true">
          </div>
        </form>

**Comment by MarcyNash** [comment]
``` html
  <form id="cell0">
          <div data-indexID="0" class="col-xs-4 col-md-4 box cell-height ttt-cell">
            <input name="game[cell][index]" type="text" value="0" hidden="true">
            <input name="game[cell][value]" type="text" class="cell-height" value="">
            <input name="game[over]" type="text" value="0" hidden="true">
          </div>
        </form>
```

**Comment by scottyscripts** [comment]
What does `event.target` log to the console before you invoke `getFormFields`?

**Comment by scottyscripts** [comment]
getFormFields needs to take the `form` as an argument.

**Comment by MarcyNash** [comment]
Great. I'll try it.

**Comment by MarcyNash** [comment]
That did it. event.currentTarget has the form. Thanks
