### ISSUE TITLE
JS/jQuery/AJAX: I have a new game object from the API, but I'm not sure how to get started displaying it on the board. 

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#737]
I have a "New Game" button which successfully returns the following objects from the API: 

``` 
Object {game: Object}
game: Object
cells:
Array(9)
0:""
1: ""
2: ""
3: ""
4: ""
5: ""
6: ""
7: ""
8: ""
length: 9
id: 1229
over: false
player_o: null
player_x: Object
email: "lisa@placeblogger.com"
id: 60
```
I'm not sure how to get started linking this to the HTML in a way that affects the divs I use to make up my game board.  

To resolve this, I've spent a lot of time in the issue queue. I felt like [this issue](https://github.com/ga-wdi-boston/game-project/issues/584) got close to what I was trying to do, but I had difficulty understanding what was being presented as a solution (or even if the solution actually solved the problem).

**Comment by lisawilliams** [comment]
Also browsing the [following issue from Matt](https://github.com/ga-wdi-boston/game-project/issues/723). Closer, but I'm still not quite getting it.

**Comment by benjimelito** [comment]
This is a good start. I would start out by thinking what the action is that you want a user to be able to perform, and what the result on your game board will be. I don't think you necessarily need to display any of the "new game" data to the user.

**Comment by benjimelito** [comment]
For example : "I want a user to be able to click on a tile, and have an "x" display in that tile". Try working on solving that problem, without worrying about what the game object looks like in the database.

**Comment by lisawilliams** [comment]
Okay, I have new and interesting error messages! 😃

I have the following HTML defining the game board: 

```
 <div class="top">
<div class="col-md-4 box text-center gamecell" id="zero"><span class ='cellZero'>T</span></div>
<div class="col-md-4 box text-center gamecell" id ="one"><span class ='cellOne'>I</span></div>
<div class="col-md-4 box text-center gamecell" id ="two"><span class ='cellTwo'>C</span></div>
 </div>

 <div class="middle">
<div class="col-md-4 box text-center gamecell" id="three"><span class ='cellThree'>T</span></div>
<div class="col-md-4 box text-center gamecell" id="four"><span class ='cellFour'>A</span></div>
 <div class="col-md-4 box text-center gamecell" id="five"><span class ='cellFive'>C</span></div></div>

<div class="bottom">

<div class="col-md-4 box text-center gamecell" id="six"><span class ='cellSix'>T</span></div>
<div class="col-md-4 box text-center gamecell" id="seven"><span class ='cellSeven'>O</span></div>
<div class="col-md-4 box text-center gamecell" id="eight"><span class ='cellEight'>E</span></div>

</div>
```
I have the following event handler in events.js, with #zero at the bottom: 

```
const addHandlers = () => {
  $('#sign-up-form').on('submit', onSignUp)
  $('#sign-in-form').on('submit', onSignIn)
  $('#sign-out').on('submit', onSignOut)
  $('#change-password').on('submit', onChangePassword)
  $('#create-game').on('submit', onCreateGame)
  $('#zero').on('click', onClickCellZero)
}
```
The event handler is handing the on('click') to onClickCellZero:

```
const onClickCellZero = function (event) {
  $('#zero').on('click', '.cellZero').text('it worked')
}
```
onClickCellZero is in module exports. 

When I load my app, sign in, create a new game board (all of which work) and click on Cell Zero, it hangs in the debugger with the following errors in jquery.js: 

![jquery-error](https://cloud.githubusercontent.com/assets/809042/26222101/c07a0c08-3be6-11e7-8df0-2c2d3ef015d3.jpg)

**Comment by lisawilliams** [comment]
I also [pushed my development branch](https://github.com/lisawilliams/tic-tac-toe/tree/development) at this point if you wish to browse.  (oh wow, just noticed Github does this automatically if you link to the issue's URL in your commit message. Nifty!)

**Comment by lisawilliams** [comment]
Things I have done to resolve this issue: 

- Read [the documentation for jQuery's text() function](http://api.jquery.com/text/#text2)
- Checked out [an example on jsFiddle](http://jsfiddle.net/cornelas/PZnSb/7/?utm_source=website&utm_medium=embed&utm_campaign=PZnSb)

**Comment by lisawilliams** [comment]
@benjimelito Psst!

**Comment by benjimelito** [comment]
One thing I'm noticing off the bat is that you don't need to attach the click handler twice. When you are writing this `$('#zero').on('click', onClickCellZero)` in your `addHandlers` function, it is already being attached. The second `$('#zero').on('click'...` is redundant.

**Comment by benjimelito** [comment]
Inside that function, you could simply set `.cellZero` to the text that you desire.

**Comment by lisawilliams** [comment]
Ben, your suggestion worked. I changed the code to: 

``` const onClickCellZero = function (event) {
  $('.cellZero').html('it worked')
}
```
Lo and behold! 

![it-worked](https://cloud.githubusercontent.com/assets/809042/26222964/05ef5e48-3bea-11e7-9d3c-34cf42150119.jpg)

**Comment by lisawilliams** [comment]
(For any future readers of this issue, it's necessary to refresh, sign in, and get a new game board before this will work. If you are not logged in, it will not work, and if your page refreshes you are probably not logged in)
