### ISSUE TITLE
Why does this refresh my page?

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/game-project#738]
I have a "clear" button for my game board that is suppose to clear my board to start a new round but every time I click it it refreshes the page. I can't pin down why this is happening because the function is extremely simple. Here a link to my code.
```
const boardCleared = function () {
  $('#box1').text('')
  $('#box2').text('')
  $('#box3').text('')
  $('#box4').text('')
  $('#box5').text('')
  $('#box6').text('')
  $('#box7').text('')
  $('#box8').text('')
  $('#box9').text('')
}
```
Does the page refresh because I'm manipulating the DOM?

**Comment by scottyscripts** [comment]
How is this function invoked?? Can you paste that code?

**Comment by slammyde7113** [comment]
forgot the event.preventDefault()!
