### ISSUE TITLE
PATCH Request 404 error

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#739]
Sorry for another 404 error, but for the second to last patch request I get a 404 error.  Here is my curl:
```
curl "http://tic-tac-toe.wdibos.com/games/${ID}" \
--include \
--request PATCH \
--header "Content-Type: application/json" \
--header "Authorization: Token token=${TOKEN}"
-data "{
  \"emails\": {
    \"email\": \"${EMAIL}\",
```
Again sorry for the repetition I tried looking at my previous ones and making adjustments but they did not work.

**Comment by Jcornmanhomonoff** [comment]
What are you trying to do a PATCH request on?

**Comment by ghost** [comment]
I am trying to do an PATCH update to join as player_o if that helps

**Comment by Jcornmanhomonoff** [comment]
Have you already created a game?

**Comment by ghost** [comment]
I already did that api

**Comment by Jcornmanhomonoff** [comment]
I would check [here](https://git.generalassemb.ly/ga-wdi-boston/game-project-api) to see what information you have to pass through for a successfull PATCH request. It won't be far off from your create.

**Comment by ghost** [comment]
Ok I will look, do you want me to close this issue now or later?

**Comment by ghost** [comment]
Issue is null, out of scope for assignment
