### ISSUE TITLE
Looking for a way to convert some type of identifier of a div to a number

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#74]
i.e. if an id was set to string '00', how i could convert that to a two zeros for use with operators. 

was hoping someone could point me in the right direction.

**Comment by laurenfazah** [comment]
@louarnos can you provide more clarity on what you're trying to accomplish?

**Comment by louarnos** [comment]
I want to associate  a number with each div for my gameboard so I can call it later. For example

012
345
678

represents my divs in html, they would have an identifier that is stored as a digit. Like id = 0 id = 1 etc.
I think i can use a parse function to convert a string to a digit though.

**Comment by laurenfazah** [comment]
Ah. Check out the HTML attribute `data` and the corresponding jQuery selector.

**Comment by louarnos** [comment]
Ok, thank you.
