### ISSUE TITLE
readme file - linter error

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/game-project#741]
Should I be concerned about this? It showed up after I finished typing up my readme file. Doesn't seem to affect gameplay.

<img width="1020" alt="screen shot 2017-05-18 at 4 00 28 pm" src="https://cloud.githubusercontent.com/assets/26583372/26221053/24a2f590-3be3-11e7-88fb-97e4747315b6.png">

**Comment by scottyscripts** [comment]
This won't effect your actual application. We use an npm package to help clean up READMEs https://www.npmjs.com/package/remark-lint. You could npm install to get rid of the error if you wanted

**Comment by scottyscripts** [comment]
https://github.com/wooorm/remark-lint

**Comment by Jcornmanhomonoff** [comment]
`npm install --global remark-cli remark-lint remark-html`

**Comment by artpylon** [comment]
nice. thanks!
