### ISSUE TITLE
Having Issues with CSS and dynamically changing the size of Font/Divs (Using Bootstrap)

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/game-project#742]
I rushed through the CSS aspect of my project, so my code is far from organized. I created classes without much rhyme or reason, just to get on with progressing through the project. 

My project looks fine on a browser as long as the width stays above about 720px, but as soon as the browser shrinks, things start to blow up. 

I used bootstrap rows/columns to create the general layout of the game board, and set a static height for each row. The width adjusts properly since the rows use the default bootstrap classes, but the heights remain the same. I thought about using media queries to change the static height, depending on the width of the view-port, but after the window shrinks past the xs breakpoint for bootstrap, the width starts to fluctuate fluidly. I want to somehow set up the height of each div to a percentage so that the height fluctuates in proportion to how the width fluctuates. 

My game-board is setup as three rows of three divs within a container div that is also a row. The 9 divs have borders that create the actually # shape, and those divs have a <p> tag in them that I change the content of to display an X or and o. The problem I seem to have is setting the height of the div as a percentage of its container seems to collapse the div, since the <p> tags are empty until the space is turned into an X or O, and the div has no content in the meantime.

Some similar issues are occurring with the buttons that have a static size. The Buttons on the left side of the board have a static width, and cut off when the div shrinks. The font sizes within the buttons are giving me problems too as the text spills off of the buttons when they shrink/cut-off. I would like to set the font-size of the button text dynamically to the size of the button itself, but can't seem to find a solution.

I can try to work out a solution using media queries, but in terms of div sizing and font sizes, I would like to make them dynamic, and save the media queries for dictating when buttons should stack instead of display in a row. 

I can paste some of my css, but its very scattered, and I'm not sure what needs to be pasted.

Here is a link to my project currently: https://constaac.github.io/Tic_Tac_Toe/

**Comment by Jcornmanhomonoff** [comment]
Please post your HTML & CSS files.

**Comment by constaac** [comment]
Paste the code or send a zip of the files? Code's long...
