### ISSUE TITLE
Trouble getting board to click

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#743]
I can't get the game board to click, don't know where to start

**Comment by scottyscripts** [comment]
Are you listening for a click event anywhere on your board?

**Comment by benjimelito** [comment]
Remember our lessons on jQuery, specifically registering click handlers - https://git.generalassemb.ly/ga-wdi-boston/jquery-dom

**Comment by ghost** [comment]
Sorry for the vagueness, I have click handlers example below just struggling with what callback functions to write
```
$('.cell0').on('click', onClick)
```

**Comment by scottyscripts** [comment]
so when you click on element with class of `cell0` the onClick function should be invoked. Is that happening?

**Comment by ghost** [comment]
the trouble is that I don't know what to write for the onClick function

**Comment by ghost** [comment]
Started on path, will open up different issues as needed
