### ISSUE TITLE
type:error cannot set property 'id'

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#744]
Been tinkering and now can't sign-in.  Get this error, it references api.js which the relevant code is:
```  
const signIn = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-in/',
    method: 'POST',
    data
  })
  .then((response) => {
    store.userToken = response.user.token
    store.user.id = response.user.id
    return store.userToken
  })
  .then(console.log)
```
Don't know what is wrong, was working before

**Comment by ghost** [comment]
oops, error is 
```
TypeError: Cannot set property 'id' of undefined
```

**Comment by ghost** [comment]
Update: Issue is store.user.id is undefined like so
```
const store = {
  user: {
    id: '',
    token: ''},
  gameBoard: ['', '', '', '', '', '', '', '', '']
}
how do I fix the issue?

**Comment by benjimelito** [comment]
Have you tried `console.log`-ing the response object? If so, what does it look like?

**Comment by ghost** [comment]
Isn't the response object just a parameter to pass through?

**Comment by ghost** [comment]
It's definitely something with the store.user.id, tried rewriting line by line and error message only comes up after inputting "store.user.id"

**Comment by ghost** [comment]
Figured it out, had an extra line of code that was messing it up
