### ISSUE TITLE
jQuery problen

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/game-project#745]
I am trying to set the value in of a game board cell. the html is  --

``` html
<form id="cell0">
          <div data-indexID="0" class="col-xs-4 col-md-4 box cell-height ttt-cell">
            <input name="game[cell][index]" type="text" value="0" hidden="true">
            <input name="game[cell][value]" type="text" class="cell-height" value="qawerty">
            <input name="game[over]" type="text" value="0" hidden="true">
          </div>
        </form>
```
Since each cell is a form, I am trying to use name="game[cell][index]".  I've played around with $('#cell0) in the console. I've tried --

$('#cell0.name="game[cell][index]"')
jquery.js:1580 Uncaught Error: Syntax error, unrecognized expression: #cell0.name="game[cell][index]"
    at Function.Sizzle.error (jquery.js:1580)
    at Sizzle.tokenize (jquery.js:2232)
    at Sizzle.select (jquery.js:2659)
    at Function.Sizzle [as find] (jquery.js:884)
    at jQuery.fn.init.find (jquery.js:2922)
    at jQuery.fn.init (jquery.js:3032)
    at jQuery (jquery.js:98)
    at <anonymous>:1:1

$('#cell0').attr('name="game[cell][index]"')
undefined

I'm out of ideas and google results.

**Comment by benjimelito** [comment]
Are you sure that's the correct syntax for `.attr`?

**Comment by MarcyNash** [comment]
I'm not sure. Will check when I get home.

**Comment by MarcyNash** [comment]
I did have incorrect syntax for attr. In reading the function more closely, this function changes the attribute's value, not the element's value. Will check the jQuery docs for the function I need. Thanks!

**Comment by MarcyNash** [comment]
I was able to get jQuery to update the tic tac toe board with this --

$('input').get(3 * data.game.cell.index + 1).value = data.game.cell.value

It's doesn't look as scalable or clean and hope to learn a better way.

**Comment by BenGitsCode** [comment]
@MarcyNash there is always a better way. The first solution is never the best solution--but it *is* a solution. If the need to make things better is really nagging at you, open an issue on your repo to refactor this code later. Scalable and clean is a job for future Marcy (but that's awesome that you recognize that!) focus on your project deliverables.👍

**Comment by BenGitsCode** [comment]
Also please close this issue, as your solution as resolved it.

**Comment by MarcyNash** [comment]
$('input').get(3 * data.game.cell.index + 1).value = data.game.cell.value       //works
