### ISSUE TITLE
I did a stupid thing with my code

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#746]
So for reasons I can't really explain I accidentally grunt deployed my website and my code is messed up now.
The errors i get on the console are
```
Uncaught Error: Cannot find module "./index.js"
    at webpackMissingModule (application.js:6)
    at Object.<anonymous> (application.js:6)
    at __webpack_require__ (bootstrap dbb65f0…:52)
    at webpackJsonpCallback (bootstrap dbb65f0…:23)
    at application.js:1
```
and 
```
client?6bcf:75 ./index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/geoffreyrothenberg/wdi/projects/rothenbg.github.io/index.js'
    at Error (native)
 @ multi application
```
how screwed am I?

**Comment by jordanallain** [comment]
don't freak out, it'll be fine. did you push before deploying?

**Comment by ghost** [comment]
Yes I did

**Comment by jordanallain** [comment]
what is the repo you are working in? you can click through the commits and look at what you changed in each one.

**Comment by ghost** [comment]
Not currently in front of computer, obviously need a break before I do more damage. Is it possible to pick this up tomorrow?

**Comment by jordanallain** [comment]
yes but not before presentations.

**Comment by ghost** [comment]
Currently working in rothenbg.github.io repo. Made a separate repo afterwards that wasn't deployed

**Comment by jordanallain** [comment]
okay, if you need a break thats okay. 

https://github.com/rothenbg/rothenbg.github.io/commits/master

those are your commits. the green check means it deployed to github pages. you can click on the 7 digit alpha numeric code on the right of each commit to see what was changed in each one.

**Comment by jordanallain** [comment]
the `< >` button will take you to the entire repo at the time of that commit if you want to browse around at any given point in time.

**Comment by ghost** [comment]
Ok

**Comment by jordanallain** [comment]
is there something you did that broke something? or are you just worried that you deployed before you were ready? or is it something else?

**Comment by ghost** [comment]
All I did was deploy and then my code broke, giving the errors that were in the original post

**Comment by jordanallain** [comment]
when are you getting those errors? in the terminal or in the chrome console?

**Comment by ghost** [comment]
Both

**Comment by jordanallain** [comment]
did you name the repo your githubname.github.io?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
The code just fixed itself, have no clue what happened.

**Comment by ghost** [comment]
I'll close this this issue if that's ok, thank you very much for bearing with me.
