### ISSUE TITLE
'grunt deploy' deploys only index.html

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/game-project#748]
Background:
- My website https://ericlscace.github.io/tic-tac-toe was initially deployed correctly with a simple landing page that showed only the name of the game. We'll call this "v0".
- After creating the master for the May 19 presentation ("v1"), 'grunt deploy' ran successfully without errors. However, the URL still showed the initial v0.
- Last night (May 19/01:30 ET), in reviewing the settings on the repo, it showed that the source was from GH-Pages. I changed source to "master". The v1 version of the site appeared.
- This morning (May 19/07:45 ET) neither v0 nor v1 appear. What appears is just the empty DOM structure of v1 index.html plus some CSS styling applied to <body>. No javascript runs.
- Re-running 'grunt deploy' does not repair.
- The repo settings "source" is still "master".

GH Pages repo from GA-WDI does not shed light. The GH Pages reference link is similarly unhelpful.

Suggestions?

**Comment by EricLScace** [comment]
Tried using Handlebars, but getting an error when executing js related to the Handlebars.template function call. I could use a second pair of eyes on this.

**Comment by danman01** [comment]
Could you post the error as well as the files where you are using the handlebars templates? Were you able to work through the handlebars talk README ok? Also let's close this issue out and open a new one related to handlebars. Thanks.

**Comment by EricLScace** [comment]
See #754 for follow-up.
