### ISSUE TITLE
On.click returning undefined.

### ISSUE THREAD

**Issue by natdjerf** [ga-wdi-boston/game-project#75]
I'm having trouble returning the value of the cell in the console in jQuery. I've tried event.target and :target but nothing seems to return the div class ID. It's also possible I'm approaching this in the wrong way. My intention is to check to see if the board space is filled (currently with just an 'x', but will be a variable), if it is isn't, to populate 'x'. I _think_ a conversation would be really helpful if someone is up to it. 

``` html
<div class="board">
          <div class="top">
            <div class="top-right">
```

``` js
'use strict';

$('.board > div > div').on("click", function() {
  let move = $(this).id;
  if ( $( this ).text() !== 'x') {
    $( this ).text('x');
    console.log(move);
  }
  else {
    console.log('not available');
  }
});

```

**Comment by RDegnen** [comment]
What does it say is the value of `$(this)` in the console

**Comment by RealWeeks** [comment]
To add onto what Ross said if you're doing something like this:

``` html
<div class="parent">
          <div class="child">
            <div class="baby-child">
```

to drill down to the 'baby-child' class you could do something like this:

``` javascript
$('.parent .baby-child')
```

But please share what the value of $(this) is

**Comment by natdjerf** [comment]
Just added console.log($(this)) and it is returning [div.top-left, context: div.top-left]. 

So hmm! Maybe it's just my if/else that isn't properly set up.. 
Looks like it's working with : if ( $ (this).text() !== 'x') {

``` js
$('.board > div > div').on("click", function() {
  if ( $ (this).val() !== 'x') {
    $( this ).text('x');
console.log($(this));
  }
  else {
    console.log('not available');
  }
});
```

returns:
[<div class=​"top-right">​
            Top Right
            ​</div>​, <div class=​"top-center">​
            Top Center
            ​</div>​, <div class=​"top-left">​
            Top Left
            ​</div>​, <div class=​"middle-right">​
            Middle Right
            ​</div>​, <div class=​"middle-center">​
            Middle Center
            ​</div>​, <div class=​"middle-left">​
            Middle Left
            ​</div>​, <div class=​"bottom-right">​
            Bottom Right
            ​</div>​, <div class=​"bottom-center">​
            Bottom Center
            ​</div>​, <div class=​"bottom-left">​
            Bottom Left
            ​</div>​]

**Comment by RDegnen** [comment]
That seems to be returning your entire array of divs, you might want to be more specific with your selectors

**Comment by RealWeeks** [comment]
@natdjerf re: what @RDegnen said, please reference my earlier comment

**Comment by natdjerf** [comment]
Sorry, on the click it returns the specific cell! (the [div.top-left, context: div.top-left] was the value of $this. 

I _think_ I should be all set from here with the below returning the cell ID. Is board > div > div bad practice? I was using $('.board > div > div') so I could only pick up clicks on the board element.  

``` js
// To identify player as 'x' or 'o' :
$('.board').on('click', function () {
    moveCounter++;
  if (moveCounter % 2 === 0) {
    player = 'o';
  }
  else {
    player = 'x';
  }
});

// To populate the board with move :
$('.board > div > div').on("click", function() {
  if ( $ (this).text() !== player) {
    $( this ).text(player);
    console.log($(this));
  }
  else {
    console.log('not available');
  }
});
```

**Comment by RealWeeks** [comment]
Yes, it's not semantic from looking at your code when you do $('.board > div > div') it's better to be as close to semantic as possible.  If you have a solution though, please feel free to close the issue.

**Comment by gaand** [comment]
You might want to investigate `event.target`.

**Comment by natdjerf** [comment]
When I set it up this way:

``` js
$('.board > div > div').on("click", function() {
  let location = $( event.target );
  if ( $ (this).text() !== '') {
    $( this ).text(player);
    console.log($(this));
    console.log($(event.target));
    console.log(location + 'was played by player ' + player);
  }
  else {
    console.log('not available');
  }
});
```

both this & event target return the specific cell name, but location (when set to either one) still just returns [object Object]. What am I doing wrong?

**Comment by natdjerf** [comment]
My main goal is to get the location of what was clicked to push it into an array, but it's possible I am just going about it in the wrong way.  Any advice/thoughts would be helpful

**Comment by gaand** [comment]
You have to specify a formal parameter to your handler in order to access the event object.  A good name would be `event`.

**Comment by natdjerf** [comment]
It still returns Object object

``` js
$('.board > div > div').on("click", function(event) {
  let location = $( event.target );
  if ( $ (this).text() !== '') {
    $( this ).text(player);
    console.log($(this));
    console.log($(event.target));
 **   console.log(location + 'was played by player ' + player);**
  }
  else {
    console.log('not available');
  }
});
```

**Comment by gaand** [comment]
What is the location?  It's a jQuery dom element.  What happens when you try to add a string to a jQuery dom element?  Apparently it returns `"[Object object]"`.

What do you want to get from that dom element?  Its class?  Something else?  If you want an `index` from it, I suggest you look at HTML5 data attributes and the jQuery data method.

**Comment by RDegnen** [comment]
@natdjerf was this ever resolved?

**Comment by natdjerf** [comment]
AH, yes. I changed gear for a few.

``` js
 let location = $(event.target).attr('id');
```

**Comment by gaand** [comment]
Please use a `data-index` (or similar) as an sttribute and 

``` js
let location = $(event.target).data('index');
```

for this purpose.

The `id` attribute should only be used to uniquely identify a dom element.

**Comment by gaand** [comment]
@natdjerf Is this issue resolved?  If so, please close.  If not, please ask a followup question.
