### ISSUE TITLE
Does the following meet the requirements for addressing API calls to production API?

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#752]
Hi! 

I received the following feedback on my project: 

``` 
Using incorrect API URL for production

```

The API calls I was making during my demo on Friday used the following function: 

``` 
const postSignIn = function (data) {
  return $.ajax({
    url: app.host + '/sign-in',
    method: 'POST',
    data
  })
}
``` 
app.js reads as follows: 

```
module.exports = {
  host: 'http://tic-tac-toe.wdibos.com'
}
```
API calls using this configuration do work.  

After reading [the following issue from Matt](https://github.com/ga-wdi-boston/game-project/issues/698), I realized that I did have a file called config.js, which reads as follows: 

``` 
'use strict'

const config = {
  apiOrigins: {
    development: 'http://tic-tac-toe.wdibos.com',
    production: 'https://aqueous-atoll-85096.herokuapp.com'
  }
}

module.exports = config
```
However, modifying a function in api.js as follows results in the error described below the code: 

``` 
const post = function (data) {
  return $.ajax({
    url: config.apiOrigins + '/sign-up',
    method: 'POST',
    data
  })
}
```
The error message returned in the console reads: 

``` 
Failed to load resource: the server responded with a status of 404 (Not Found)

``` 

I modified the code as follows. This successfully  returns a user object with an ID upon sign up, and a user object with a token upon sign in. 

```
// Auth API calls

const post = function (data) {
  return $.ajax({
    url: config.apiOrigins.production + '/sign-up',
    method: 'POST',
    data
  })
}

const postSignIn = function (data) {
  return $.ajax({
    url: config.apiOrigins.production + '/sign-in',
    method: 'POST',
    data
  })
}
```
My question: does this code meet requirements if it does not switch between development and production? I am essentially hard-coding in the reference to the production API into functions in api.js. 

Thank you for reading!

**Comment by danman01** [comment]
Hi Lisa,

It looks like you've found a way to get the `config.apiOrigins` object to return the value you need. Alternatively / to get more functionality out of the browser template, check out this issue: https://github.com/ga-wdi-boston/game-project/issues/578 - there's a way to write your server reference in such a way that prod or dev environments will "just work" due to browser template handling that logic for you.
