### ISSUE TITLE
Game API: Able to update game object, but getting 400 Bad Request error when passing it to API

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#753]
Hi! 

I have the following event handlers to create a new game array, and to respond to a user clicking on a cell:  

``` 
const onCreateGame = function (event) {
  event.preventDefault()
  console.log('hello!')
  const data = getFormFields(event.target)
  console.log(data)
  console.log('onCreateGame ran')
  api.createGame()
    .then(ui.createGameSuccess)
    .catch(ui.createGameFailure)
}

const onClickCellZero = function (event) {
  $('.cellZero').html('X')
  api.updateGame()
    .then(ui.UpdateGameSuccess)
    .catch(ui.UpdateGameFailure)
}

```
The problem is, I'm not sure how to write the function to call the API to update the board. 

This is what I have now: 

``` 
// update game
const updateGame = (data) => {
  return $.ajax({
    url: config.apiOrigins.production + '/games/',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

I'm not sure how to get information from user input into the API call and get back an updated game board array.

**Comment by lisawilliams** [comment]
(I'm continuing to work on this! I will leave updates here as I go).

**Comment by lisawilliams** [comment]
Making progress at least in the sense that I am getting new and different error messages! 😃  I've updated the functions I've written making the API requests, and  I now get the following console error: 

``` 
PATCH https://aqueous-atoll-85096.herokuapp.com/games/5612 400 (Bad Request)
```
Which tells me that my request is reaching the API but not formed properly. Here is the code that's making the request when a user clicks one of the cells on the board: 

```

const createGame = (data) => {
  return $.ajax({
    url: config.apiOrigins.production + '/games/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
  .then((response) => {
    console.log('createGame returns ', response)
    store.gameID = response.game.id
  })
}

// update game
const updateGame = (data) => {
  return $.ajax({
    url: config.apiOrigins.production + '/games/' + store.gameID,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

**Comment by lisawilliams** [comment]
I admit I actually cackled with glee in a way that would have made the voiceover actress for the witch in Snow White proud when I got this to work.  My aim here was to change the value of one cell in the "cells" array in the game object in store.js.  

My createGame function returns a valid game object with an array of cells from the API, complete with a game ID: 

![creategamereturns](https://cloud.githubusercontent.com/assets/809042/26280318/dfa6e68a-3d9b-11e7-9d22-5c48e7b98683.jpg)

Then, I added the following code to events.js (after a long time fiddling around, trying to get the code to actually put something into the array of cells in the object): 

```
const onClickCellZero = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  $('.cellZero').html('X')
  store.game.cells[0] = 'x'
  console.log(store.game)
  console.log(data)
  // api.updateGame(data)
  //   .then(ui.updateGameSuccess)
  //   .catch(ui.updateGameFailure)
}
```
And when I click on Cell Zero, it returns the following in the console: 


![onclickcellzeroreturns](https://cloud.githubusercontent.com/assets/809042/26280327/71abaf52-3d9c-11e7-97f1-c8028f1ece3d.jpg)

Woo! That feels good. I realize this doesn't update it on the backend, but that's next.

**Comment by lisawilliams** [comment]
Okay, so, when passing this through to the API, I'm not getting a happy result.  Here's the code in events.js that is passing off store.game  to updateGame in api.js. 

``` 
const onClickCellZero = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  $('.cellZero').html('X')
  store.game.cells[0] = 'x'
  console.log(store.game)
  console.log('this is ', data)
  api.updateGame(store.game)
    .then(ui.updateGameSuccess)
    .catch(ui.updateGameFailure)
}
```
Here's the updateGame function.  It should be passing store.game to the API along with the user token, no? And yet I get a 400: Bad Request response in the console (PATCH https://aqueous-atoll-85096.herokuapp.com/games/5636 400 (Bad Request)) 

```
const updateGame = (data) => {
  return $.ajax({
    url: config.apiOrigins.production + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

Thoughts? Halp? 

I have been reading through the API docs and the issue queue to get this far (the issue queue has been very helpful!) 

I have referenced a commit to this issue with the current state of my code, if you would like to browse around. I appreciate it!

**Comment by benjimelito** [comment]
So the 400 error is basically telling you that you haven't formatted your data in the exact way that the API requires. I would make sure that the data you are passing looks exactly like the following example: https://git.generalassemb.ly/ga-wdi-boston/game-project-api#create.

When you are console.logging `store.game` above, does it look different from the example?

**Comment by lisawilliams** [comment]
Thank you, Ben -- I'll check!  I also think I should probably join player_o before I get around to patching the game state. Back to the Curl Request Mines I go :)

**Comment by benjimelito** [comment]
The "join player o" feature is additional! I would make sure you have a
fully functioning CRUD app before you start working on that.

**Comment by lisawilliams** [comment]
Oh, okay.  I thought I needed player_o just so I could have a place in store.js to stow moves that weren't "x".  That makes things simpler!

**Comment by lisawilliams** [comment]
Got this working! Thanks to @benjimelito  and a couple WDI cohort members (particularly Sam who suggested an approach to setting player X as the first player!)
