### ISSUE TITLE
Handlebars.templates not recognized in js

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/game-project#754]
Get js reference error in templatesComplied.js:

> (function () {
> var template = Handlebars.template,
> templates = Handlebars.templates = Handlebars.templates || {};

generates on execution in Chrome:

> ReferenceError: Handlebars.template not defined.

Problem with assets/scripts/index.js?

**Comment by EricLScace** [comment]
compiledTemplates.js contains

(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['gameGrid'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\n<div class=\"row\">\n  <div id=\"0\" class=\"game-grid col-xs-2 col-xs-offset-3\"></div>\n  <div id=\"1\" class=\"game-grid col-xs-2 game-grid-column\"></div>\n  <div id=\"2\" class=\"game-grid col-xs-2\"></div>\n</div>\n\n<div class=\"row\">\n  <div id=\"3\" class=\"game-grid col-xs-2 col-xs-offset-3 game-grid-row\"></div>\n  <div id=\"4\" class=\"game-grid col-xs-2 game-grid-center\"></div>\n  <div id=\"5\" class=\"game-grid col-xs-2 game-grid-row\"></div>\n</div>\n\n<div class=\"row\">\n  <div id=\"6\" class=\"game-grid col-xs-2 col-xs-offset-3\"></div>\n  <div id=\"7\" class=\"game-grid col-xs-2 game-grid-column\"></div>\n  <div id=\"8\" class=\"game-grid col-xs-2\"></div>\n</div>\n";
},"useData":true});
templates['player'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\n<div class=\"row\">\n\n  <div class=\"player-name col-xs-offset-3 col-xs-5\">\n  </div>\n\n  <div class=\"player-actions col-xs-3\">\n  </div>\n</div>\n";
},"useData":true});
templates['signInRegister'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\n<div class=\"player1 col-xs-offset-1 col-xs-3\">\n  <form id=\"sign-in\">\n    <fieldset>\n      <p>Log in:</p>\n\n      <input type=\"text\"\n      name=\"credentials[email]\" placeholder=\"player name\">\n      <br>\n\n      <input type=\"password\"\n      name=\"credentials[password]\" placeholder=\"password\">\n      <br>\n\n      <input type=\"submit\" name=\"submit\" value=\"Log in\">\n    </fieldset>\n  </form>\n</div>\n\n\n<div class='player1 col-xs-3'>\n  <form id=\"sign-up\">\n    <fieldset>\n      <p>…or register:<p>\n\n      <input type='text'\n      name='credentials[email]' placeholder='player name'>\n\n      <input type='password'\n      name='credentials[password]' placeholder='password'>\n\n      <input type='password'\n      name='credentials[password_confirmation]' placeholder='confirm password'>\n\n      <input type=\"submit\" name=\"submit\" value=\"Register\">\n    </fieldset>\n  </form>\n</div>\n";
},"useData":true});
})();

**Comment by danman01** [comment]
Were you able to set up your project with all the requirements for handlebars and verify you have a working handlebars installation? Does your `package.json` look like the one in the [handlebars talk](https://git.generalassemb.ly/ga-wdi-boston/handlebars/blob/master/package.json) and are you requiring your templates when you use them in your js like [here](https://git.generalassemb.ly/ga-wdi-boston/handlebars/blob/master/assets/scripts/books/ui.js)?

**Comment by EricLScace** [comment]
I am following the steps here: https://www.sitepoint.com/a-beginners-guide-to-handlebars/

> npm install handlebars -g
for a global installation of handlebars was successful. -g was probably overkill as I see handlebars.min.js is in many folders beyond this project.

All the template files are stored in assets/templates/

The template files were recompiled with:
> handlebars ./assets/templates -f templatesCompiled.js

The templatesCompiled.js file exists.

Index.html includes these references
>    <script src="./node_modules/handlebars/dist/handlebars.min.js"></script>
>    <script src="./node_modules/handlebars/dist/cjs/handlebars.runtime.js"></script>
>    <script src="./assets/scripts/templatesCompiled.js"></script>
just before the closing tag </head>

My templates are in separate .handlebars files.

Each template file is straight HTML — no escapes, handlebars variables, or other handlebars syntax.

The templates compiled successfully.

An example of a code snippet that refers to a template is here:
>// Load player's log-in/registration forms into UI
  // Wait for the load to complete before continuing (synchronous, but
  // needed to be sure form is ready to fire event).
  const signInRegisterTemplateScript = Handlebars.templates.signInRegister()
  $('#player').html(signInRegisterTemplateScript, function () {
    authEvents.addHandlers()
  })

Linter complains that Handlebars is undefined.
The local service compiles successfully, but the landing page throws an exception:
<img width="1203" alt="screen shot 2017-05-22 at 14 56 48" src="https://cloud.githubusercontent.com/assets/6785602/26324060/40cba964-3eff-11e7-9eb3-b64be39353a3.png">

I feel there is a small step I am missing... but also I am losing a lot of time on this.

**Comment by EricLScace** [comment]
I really would like to get this sorted out before leaving for home tonight.

**Comment by EricLScace** [comment]
And package.json has the same two lines of references to handlebars as the prototypical example [there](https://git.generalassemb.ly/ga-wdi-boston/handlebars/blob/master/assets/scripts/books/ui.js).

**Comment by danman01** [comment]
Hmm I would follow the implementation in our [handlebars talk](https://git.generalassemb.ly/ga-wdi-boston/handlebars), as we have it integrated with the browser-template which will load things appropriately. You will need the files in package.json, installed with `npm install`, and used appropriately in your script.

How are you doing on the requirements thus far to resubmit?

Specifically, getting the github README updated and getting the client deployed and working? 

Implementing a new technology does take time. Before you go too far on this, make sure you have your requirements met as a new technology can take time, especially since we have not gone over this one yet.

**Comment by EricLScace** [comment]
Templates are integral to the design approach. I can do an ugly work-around but it's really bad practice.

I am working on the other remaining items for resubmission in parallel.

**Comment by EricLScace** [comment]
The template issue is preventing a working client from being deployed.

**Comment by danman01** [comment]
@EricLScace let's find some time after outcomes to sit down and work on it.

**Comment by EricLScace** [comment]
Outcomes is in workshop mode now. I've stripped the codebase back to not using compile handlebars — it's now the uncompiled version that adheres to the code example in the handlebars module.

The template called by index.js on landing loads into the DOM and is rendered. However, an event fired on a form in the loaded template leads to a page refresh.

**Comment by danman01** [comment]
Ok, sounds like you're making good progress. The javascript event handlers are run when the page loads. When new elements are placed on the page, those event handlers may not be registered on the new elements. If your event handlers are not being run, ensure that the code to attach the event handlers is not running too soon, before the element is present on the page.

**Comment by EricLScace** [comment]
Thanks again. Fixed with uncompiled templates — and as these templates are short and relatively simple, that should be sufficient for minimum requirements compliance. Closing the issue.
