### ISSUE TITLE
400 bad request when clicking a second time (PATCH request)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#756]
So I get the following error message when I click a second space (patch request goes through when clicking a first space)
```
PATCH http://tic-tac-toe.wdibos.com/games/225 400 (Bad Request) tic-tac-toe.wdibos.com/games/225:1 PATCH
```
API code is 
```
const updateGame = function (data) {
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/games/' + store.userId,
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}
```
Curl request is 
```
curl "http://tic-tac-toe.wdibos.com/games/id=${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
```

**Comment by danman01** [comment]
Are you sending any updated data to the server?

More: 
https://github.com/ga-wdi-boston/library-api-guide#user-content-patch-change-passwordid

**Comment by ghost** [comment]
I'm sorry i'm really confused as to what I'm doing with the grid space. I'll close this until I have it sorted out. Issue is not ripe.
