### ISSUE TITLE
Need 1-on-1 help (general planning)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#757]
Hi,
Would anyone be able to meet after class for a little bit and help me plan out what exactly I need to do to complete the project. Sorry if this isn't the right forum for this request.

**Comment by danman01** [comment]
Hi, looking back to the email, there's many that you need to complete. 

Do you have user stories, and do those user stories correlate to the [requirements](https://github.com/ga-wdi-boston/game-project/blob/master/requirements.md)? If so, you can start by going down each user story and accomplishing the task, one by one, until you have a functioning project that meets requirements. 

What have you completed thus far, and what do you think are the next items you should do? We can likely find a time to ensure you're on track, if not today, then tomorrow during workshop.

**Comment by ghost** [comment]
I know I have a lot to do, but its mostly just finding a launch point for the game board that I'm stuck on.  I have completed my curl requests (sign-in, etc.). I have the empty-string array for the game board and I have the board in the html doc.  Its a matter of being able to click on the cell and change to an x or an o while logging it into the game array thats bugging me.

**Comment by danman01** [comment]
Ok, so you need to click on a cell (a DOM element with an ID or class) and trigger some javascript code. That javascript code needs to either add an X or O to the cell (append text to the html element).

Do you have click handlers that are run when something is clicked?

**Comment by ghost** [comment]
yes I have clickhandlers

**Comment by ghost** [comment]
e.g.
```
('.cell0').on('click', onUpdateGame)
```

**Comment by danman01** [comment]
Do those result in the Js running that you want / expect? Can you console log within `onUpdateGame`, and from there, do you then have logic to add text into the clicked cell?

**Comment by ghost** [comment]
Hi,closing this issue because I talked to Ben for a bit. Thanks for your help
