### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#758]
Had this issue yesterday, but time wasn't right to bring it up.  I get a 400 bad request error when I click on a second square.  It works the first time but after that all I get are errors.  I tried passing a different object through as data but it didn't help.  Below is the events code I am using:
```
const onUpdateGame = function (event) {
  event.preventDefault()
  console.log(event.target)
  const data = getGames[1]

  api.updateGame(data)
  .then(gameUi.updateSuccess)
  .catch(ui.fail)
}
```

**Comment by benjimelito** [comment]
So the reason the first request works ok is because you're passing an empty object, which is what the API expects the first time around. In order to actually make a `PATCH` request, you will need to pass an object that looks like the following example: https://github.com/ga-wdi-boston/game-project-api#update

**Comment by benjimelito** [comment]
That being said, it might also help to institute the logic for which type of symbol you are updating the board with before getting the `PATCH` request working. Feel free to open another issue if you're having problems with that.

**Comment by ghost** [comment]
I am passing this as an object though:
```
'id': 2,
    'cells': ['', '', '', '', '', '', '', '', ''],
    'over': false,
    'player_x': {
      'id': 3,
      'email': ''
    },
    'player_o': {
      'id': 1,
      'email': ''
    }
  }
```
Do i need to pass both objects?

**Comment by benjimelito** [comment]
I thought that when we console.logged the object last night it was empty? A "Bad Request" error means there is some issue with the data that is being passed along. Try console.logging `data` right before calling `api.updateGame` and see what you get.

**Comment by ghost** [comment]
I changed it last night when I was working on the project to the array object in games.js. Right now it is the object that you linked to.

**Comment by ghost** [comment]
still having the problem

**Comment by ghost** [comment]
Nevermind, problem solved, functions were calling wrong data
