### ISSUE TITLE
Exported function works in one .js file but throws a TypeError, not a function, in another.

### ISSUE THREAD

**Issue by cuprous** [ga-wdi-boston/game-project#76]
When exporting a function from create-handlers.js, it is callable in index.js, after including a require statement, on document load. However, calling the same function from another file that has the necessary require statement leads to a TypeError, not a function.

I simplified the imported function by changing the contents to a console.log message, and this error is still happening.

If you need more information, please let me know.

**Comment by RealWeeks** [comment]
Can you paste in your require/exports? I'm thinking this may be a module.exports = someFunction vs a module.exports = {someFunction}

**Comment by cuprous** [comment]
create-handlers.js function and exports:

``` js
const initBoard = () => {
  console.log('test message works?');
};

module.exports = {
  pageLoadHandlers,
  initBoard,
};
```

index.js import:

``` js
const handlers = require('./create-handlers');
```

ui.js import:

``` js
const handlers = require('./create-handlers');
```

In both files they're called as 

``` js
handlers.initBoard();
```

**Comment by gaand** [comment]
Is `ui.js` in the same directory as `index.js`?

**Comment by cuprous** [comment]
Yes, all three files are in the same directory.

**Comment by gaand** [comment]
This is probably a problem with order of execution.

**Comment by gaand** [comment]
Circular dependency in requires.

**Comment by RealWeeks** [comment]
@cuprous Can you write your solution (once you have on) then kindly close the issue,

**Comment by cuprous** [comment]
Error unresolved. I removed the require ui.js from create-handlers.js.

Is it possible there is another circular reference? Here's the current file and include structure.
- apiCalls: 1. app-data, 2. ui
- create-handlers: 1. apiCalls, 2. get-form-fields
- index: 1. create-handlers
- ui: 1. app-data, 2. create-handlers

Is the following an issue? ui -> create-handlers -> apiCalls -> ui?

**Comment by RealWeeks** [comment]
Sounds circular, Antony has already assigned, @gaand any further insight from looking at this code?

**Comment by gaand** [comment]
I think you need to restructure things so that the map of requires is less ring like and more tree like.

**Comment by cuprous** [comment]
Solution: wrote down all files and their requires and removed all circular references.
