### ISSUE TITLE
win condition help

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#762]
So I am trying to check for the win condition and in to start I am just trying to get the computer to recognize the text in the cell.  My code is 
```
const checkForWin = (data) => {
  if ($('#cell8') === 'X') {
    console.log('yay')
  }
```
I know this code is wrong I just don't know how I should go about it.  If its easier to talk in person then I am in the Newbury room until 6.  Thanks

**Comment by benjimelito** [comment]
I think rather than checking the text in the cells in the DOM, it would be much easier to check the values that you have stored in your `cells` array. See the following for reference of what a single game object should look like: https://github.com/ga-wdi-boston/game-project-api#index

**Comment by benjimelito** [comment]
If you are registering moves properly, this object should be available to you in `store.game`

**Comment by ghost** [comment]
How exactly do you store the values in the array, is there a method that can link the value to the array?

**Comment by ghost** [comment]
Figured out how to store values in the array, will close this issue for now
