### ISSUE TITLE
404 not found on other accounts

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#763]
Weird Problem but my game works fine with a specific sign-in but I get the above error when trying it with other sign-ups.  Curl request is 
```
curl "http://tic-tac-toe.wdibos.com/games/id=${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \

```
api:
```
const updateGame = function (data) {
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/games/' + store.userId,
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data: data
  })
}
```

**Comment by jordanallain** [comment]
im a little confused, those looks like PATCH requests to update a game not a sign-in or sign-up function

**Comment by ghost** [comment]
They are PATCH Requests, they do not work if I sign into an account other a specific one that I ahve been working in

**Comment by jordanallain** [comment]
they shouldn't work unless they are PATCH requests to a game that was created by the current signed in user.

**Comment by ghost** [comment]
I don't really understand that answer, I can create and sign into another account I then press the game board and I get the error.  ON the account that works I sign-in and the game-board works.  I

**Comment by danman01** [comment]
What error do you get when you sign in with the non-working account? As Jordan mentioned, user ids are tied to game ids, and PATCH requests should work if coming from the user id that created the game. 

Use console logs to investigate the values of the user id and game id, and see if it's what you expect. 

Refer to the [game project api documentation](https://github.com/ga-wdi-boston/game-project-api) if you need the endpoint to look up a specific game to get more information.

**Comment by ghost** [comment]
I get this error
```
PATCH http://tic-tac-toe.wdibos.com/games/251 404 (Not Found)
jquery.js:9566 XHR finished loading: PATCH "http://tic-tac-toe.wdibos.com/games/251".
send @ jquery.js:9566
ajax @ jquery.js:9173
updateGame @ api.js:76
onUpdateGame @ events.js:70
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
```

**Comment by danman01** [comment]
Does that game return a 200 when you issue a `GET` request to `/games/251`?

**Comment by ghost** [comment]
GET requests work

**Comment by danman01** [comment]
So it seems to be an authentication error? If you create a new game with a curl request, then issue a PATCH to that game with a curl request, does that work? What I'm getting at is...at what point in your application does the create-update process have a bug?

**Comment by ghost** [comment]
Don't think its an authentication error, the patch request (updating the board) is the only feature not working.

**Comment by MicFin** [comment]
Make sure that your `store.userToken` is being reset properly upon sign out and then sign in.  
Where does that get set and reset? 

You use it for authorization when making a PATCH request.
```js
const updateGame = function (data) {
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/games/' + store.userId,
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data: data
  })
}
```

Also, here ` url: config.apiOrigin + '/games/' + store.userId,` it looks like you are passing the `store.userId` where you should be passing the ID of the game (likely in your `data` object).  Or maybe that's just not named correctly.

**Comment by ghost** [comment]
Curious why it only works on one account then, if I'm passing the wrong ID

**Comment by MicFin** [comment]
The ID you are passing must happen to also be the ID of a game that user owns.  Either way, I would not try to figure out why the incorrect thing happens to work, I would focus on correcting it so you get the expected behavior.

**Comment by ghost** [comment]
what does 'data' supposed to reference? Tried ```data.id``` and ```data.games.id``` and got ```tic-tac-toe.wdibos.com/games/undefined:1 PATCH http://tic-tac-toe.wdibos.com/games/undefined 404 (Not Found)``` message

**Comment by ghost** [comment]
update: tinkered around with the cur request and have
```curl "http://tic-tac-toe.wdibos.com/games/${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
  "game": {
    "id": 1,
    "cells": ["","","","","","","","",""],
    "over": false,
    "player_x": {
      "id": 1,
      "email": "and@and.com"
      },
    "player_o": {
      "id": 3,
      "email":
      "dna@dna.com"
    }
  }
}'
```
tried ```... + data.game.id``` and get this 404 error: ```tic-tac-toe.wdibos.com/games/1:1 PATCH http://tic-tac-toe.wdibos.com/games/1 ```  guidance on what to do next?

**Comment by ghost** [comment]
so removed data: data from api function and got one account to work, and another to return a bad request error. Progress!

**Comment by MicFin** [comment]
What is `data` and `store`?  Use `console.log()` as shown below.
```js
const updateGame = function (data) {
  console.log('update data is ', data) // log data here to see what it is
  console.log('update store is ', store) // log store here to see what it is
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/games/' + store.userId,
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data: data
  })
}
```

**Comment by ghost** [comment]
data is ``` Object {game: Object}```
store is ```Object {store: Object, userId: 251, userToken: "BAhJIiVlMDFlOGI4OTFhYTUwMTU3MmNlNDliOGNkMzUwOGE0YQY6BkVG--d920a8c094085294facd778289d82a6e80ed8b38"}```

**Comment by ghost** [comment]
fwiw my api function now looks like:
```
  console.log('update data is ', data)
  console.log('update store is ', store)
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/games/' + data.game.id,
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}
```

**Comment by ghost** [comment]
Honestly don't know where to go from here

**Comment by ghost** [comment]
Anybody?

**Comment by jordanallain** [comment]
What output did you get from that last curl script? Were you signed in as the user that created the game you were PATCHing?

**Comment by ghost** [comment]
What do you mean about the curl script?

**Comment by ghost** [comment]
Sorry, I think I understand now.  I got a 404 error

**Comment by payne-chris-r** [comment]
Are you doing a request to `games/userId`?

**Comment by ghost** [comment]
No, the Id of the game

**Comment by MicFin** [comment]
It looks like you lost the `data: data` part of your AJAX call which is where you want to pass the updated game information to the API. 
What error do you get with the following?
```js
const updateGame = function (data) {
  // print data.game.id is it the ID you expect?
  console.log('update data.game.id is ', data.game.id) 
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + '/games/' + data.game.id,
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    // set the data property to be your newly updated data object
    data: data
  })
}
```
