### ISSUE TITLE
prevent double click

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#764]
I have tried various methods to prevent the value and text from changing after a cell is clicked once and then again. My code is:
```
const updateSuccess = (event) => {
  if (event.detail === 1) {
    if (playerXTurn === true) {
      $('#cell0').val('X')
      $('#cell0').text('X')
    } else if (playerXTurn === false) {
      $('#cell0').val('O')
      $('#cell0').text('O')
    }
  }
  getGames.game.cells[0] = $('#cell0').val()
  playerXTurn = !playerXTurn
}
```
it ignores the first if statement and changes anyway

**Comment by MicFin** [comment]
What is `event.detail` if you console.log it each time?

**Comment by ghost** [comment]
I get undefined, was expecting a number i guess

**Comment by ghost** [comment]
For perspective of my dilemma, I can either get the cells to change X => O but not prevent a double-click or I can move the ``` event.detail``` and prevent the double-click but not change X => O

**Comment by ghost** [comment]
Issue resolved, changed event.detail to a conditional statement based on whether the cell in the array is equal to the value in the cell.  Thank you for your time.
