### ISSUE TITLE
Retrieve game 404

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#765]
Separate from my other 404 error.  Get a 404 error when trying to retrieve a game.
```
curl "http://tic-tac-toe.wdibos.com/games/id=${ID}" \
--include \
--request GET \
--header "Content-Type: application/json" \
--header "Authorization: Token token=${TOKEN}" \
```
api:
```
const showGame = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/games/' + getGames.game.id,
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}
```
error message is 
```
GET http://tic-tac-toe.wdibos.com/games/1 404 (Not Found)  tic-tac-toe.wdibos.com/games/1:1 
```

**Comment by MicFin** [comment]
The URL on this curl request URL does not look correct.  
What does it end up looking like once you pass in the ID?
What does the API expect?
```
curl "http://tic-tac-toe.wdibos.com/games/id=${ID}" \
```

**Comment by ghost** [comment]
URL is the one I used on similar curl requests (per the game project api document), what is looks incorrect?

**Comment by MicFin** [comment]
The API documentation got a GET request SHOW action URL endpoint, 
Is `/games/:id`
Not `/games/id=:id`
https://git.generalassemb.ly/ga-wdi-boston/game-project-api#game-actions

**Comment by MicFin** [comment]
Also, use console.log to see what the value of `getGames.game.id` is, is it what you expect?

**Comment by ghost** [comment]
so removed ```data: data``` from api function and got one account to work, and another to return a bad request error. Progress!

**Comment by ghost** [comment]
Ignore above comment for another issue, resolved issue added data: data to api call
