### ISSUE TITLE
Game board will not reset after calling New Game function 

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/game-project#767]
Hi, 
I have a curious bug. I'm able to play a game successfully, and indicate win/lose/draw to a user, and collect their stats.  

When they finish a game, I hide the gameboard div so that they can't keep playing after a game is over. 

However, when they hit the New Game button after finishing a game, the gameboard unhides -- but the UI still has the moves they made in the previous game. It has these *even though the array of game cells has an array of blank cells.*  

I'm really perplexed by this bug.  

My flow looks like this: 

```index.html``` has a button with a form id of create-game: ```<form id="create-game">```

```events.js``` has an event handler for that button that looks like this: 

```
const onCreateGame = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.createGame()
    .then(ui.createGameSuccess)
    .catch(ui.createGameFailure)
}
```
That is then passed to ```api.js```, which has a function that pulls a new game from the API: 

```
const onCreateGame = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.createGame()
    .then(ui.createGameSuccess)
    .catch(ui.createGameFailure)
}
```

Then, that's passed to a function in ui.js that's *supposed* to unhide the board, and give us a new grid reading "Tic/Tac/Toe": 

```
const createGameSuccess = (response) => {
  console.log('yayyyyy we did it')
  console.log(response)
  console.log(store.game.cells)
  if (store.game.cells[0] === '') {
    $('#cellZero').text('T')
    $('#cellOne').text('I')
    $('#cellTwo').text('C')
    $('#cellThree').text('T')
    $('#cellFour').text('A')
    $('#cellFive').text('C')
    $('#cellSix').text('T')
    $('#cellSeven').text('O')
    $('#cellEight').text('E')
    $('#gameboard').show()
  }
  $('#usermessage').text('You have a new game. Good luck.')
}
```

Unfortunately, what you actually see is the  moves you made in the previous game, despite the fact that we do have a new, empty game array. In fact, the board is playable -- you can play a new game on it and it will work.  But why doesn't it refresh the ui portion of the board?  Thoughts welcome!  

I have included a commit to reflect these issues for ease of browsing.

**Comment by lisawilliams** [comment]
Here is a deployed version of my game: 
https://lisawilliams.github.io/tic-tac-toe/

**Comment by benjimelito** [comment]
Just a thought, but I would think that it has something to do with that `if` statement that triggers resetting the game squares. Try messing around with that and see if you can get some different results. For instance, I might simply try `if (store.game.cells[0])` rather than `if (store.game.cells[0] === '')`

**Comment by EricLScace** [comment]
I'm a little confused by the code in these areas:
- Index.js: Makes a local function call api.createGame(). Why is there a .then and .catch here?
- Where is the code for .createGame() in api?
- I don't understand how the codeblock in event.js is used.
- Put a breakpoint at the start of createGameSuccess. I suspect you'll find that store.game.cells[0] has the value from the old game... and therefore the if () will test false and the cells will not be initialized as you intended.
