### ISSUE TITLE
Not being able to deploy

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#769]
Once I type in grunt deploy it gives me two fatal messages saying that 'origin' does not appear to be a git repository and that it could not read from remote repository.

**Comment by tvcrawley** [comment]
What is your output when you type `git remote -v`?

**Comment by ghost** [comment]
It doesn't do anything and comes back with a blank line.

**Comment by tvcrawley** [comment]
Was the directory ever made into a git repository? (aka`git init`)

**Comment by ghost** [comment]
Yes, I even wrote it twice to double check and it reinitialized the existing Git repo

**Comment by tvcrawley** [comment]
Was the origin (in this case the link to github) added? (aka `git remote add origin <--github-link-->`)

**Comment by tvcrawley** [comment]
@MarioJr92 update?

**Comment by ghost** [comment]
No it wasn't, I'm trying to do that now and it's failing
