### ISSUE TITLE
Git merge branch issues

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/game-project#77]
I was working of a branch called project and adding/committing there, then switching to master and merging.  It doesn't seem to be registering in my repository though and when I tried to resolve the issue by pulling it seems to have reverted some of my changes.  How can I clear my repository back to normal and start working from that point?

**Comment by laurenfazah** [comment]
I saw his terminal output - going to work through it in person.

**Comment by MichaelB167** [comment]
Lauren and Jason helped me fix the issue, I deleted the original project branch and master seems to be up to date.
