### ISSUE TITLE
Can't access function from a required file

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#770]
Linter Output:

No issues caught by linter

Issue Description:

I wrote a function called onClick in a file called events.js and put it in the export module. Then I required events.js in index.js so I could use that function on an event listener. In the event listener, I have the function written as events.onClick(). However, when I try testing that in my browser, the debugger says that events.onClick is not a function.

error from debugger:
jquery.js:3860 jQuery.Deferred exception: events.onClick is not a function TypeError: events.onClick is not a function
    at HTMLDocument.<anonymous> (http://localhost:7165/public/application.js:46:36)
    at mightThrow (http://localhost:7165/public/vendor.js:11500:30)
    at process (http://localhost:7165/public/vendor.js:11568:13)

[ the code that caused the error (as a fenced code block) or ]

```javascript
const setAPIOrigin = require('../../lib/set-api-origin')
const config = require('./config')
const events = require('./events')

$(() => {
  setAPIOrigin(location, config)
})

// use require with a reference to bundle the file and use it in this file
// const example = require('./example')
$(() => {
  $('.space0').on('click', events.onClick(0))
})
```
To fix the problem, I've tried renaming the variable attached to the function, I've tried running a console.log test in the linked function, I've tried running the code in node to see if it would recognize the function that way, and I've tried running the function outside of the event listener, but no matter what I do, I get "Type error: events.onClick is not a function".

I haven't had a point where this has worked yet, so the last time I've been able to run the page without errors is before I added the event listeners to index.js.

**Comment by Jcornmanhomonoff** [comment]
Can you paste your code from your events file please?

**Comment by bradleyden** [comment]
Here it is, for now I'm just trying to get the console log to work. Thanks!

```javascript
// const engine = require('./engine')

const onClick = function (space) {
  console.log('test')
  // if (engine.isPlayerOne) {
  //   engine.placeX(space)
  // } else {
  //   engine.placeO(space)
  // }
}

module.export = {
  onClick
}
```

**Comment by Jcornmanhomonoff** [comment]
Compare how you're exporting functions with how we had done it in previous lessons.

**Comment by bradleyden** [comment]
Okay I figured it out, it needs to be module.exports, not module.export.

I even compared it to the example.js before posting and still didn't catch it somehow. Thank you!
