### ISSUE TITLE
Issue with Change Password 

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/game-project#771]
```js
const changePwd = function (data) {
  console.log(data)
  console.log(store)
  return $.ajax({
    method: 'PATCH',
    url: app.host + '/change-password/' + store.user.id,
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

It gives me 400 Bad Request. This means that my request is not formatted property. I couldn't find the mistake. I tried logging data and store. Both Values work. I compared the syntax with api-token lesson and its the same syntax. I am not sure why this didn't work.

error: 

aqueous-atoll-85096.herokuapp.com/change-password/1160:1 PATCH https://aqueous-atoll-85096.herokuapp.com/change-password/1160 400 (Bad Request)

**Comment by Jcornmanhomonoff** [comment]
What are you getting back as `data`?

**Comment by kailinc** [comment]
<img width="292" alt="screen shot 2017-06-27 at 3 29 24 pm" src="https://user-images.githubusercontent.com/25471305/27606225-76089758-5b4d-11e7-8675-425d9292924b.png">

the first one is data 
the second one is store

**Comment by kailinc** [comment]
I GOT IT!! OMG! Silly. In the html, I put the wrong order for form for old and new password.
