### ISSUE TITLE
Page triggers function in event listener automatically without click

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#772]
Linter Output:

No issues caught by linter

Issue Description:

My link to the events.js function is working now, but I'm experiencing a problem with how the event listener is behaving. I have a very simple function to simply log 'test' being exported from events.js. But when I load the page, the function in the event listener is triggered before I click on the specified div, so 'test' is logged immediately.

Weirdly, when I move the function from events.js and put it directly into the event listener, it behaves like it should- it only logs 'test' when the correct div is clicked on. The problem only occurs when I link to an exported function.

No errors.

Doesn't work:
```javascript
const setAPIOrigin = require('../../lib/set-api-origin')
const config = require('./config')
const events = require('./events')

$(() => {
  setAPIOrigin(location, config)
})

// use require with a reference to bundle the file and use it in this file
// const example = require('./example')
$(() => {
  $('.space0').on('click', events.onClick(0))
})
```
events.js:
```javascript
// const engine = require('./engine')

const onClick = function (space) {
  console.log('test')
  // if (engine.isPlayerOne) {
  //   engine.placeX(space)
  // } else {
  //   engine.placeO(space)
  // }
}

module.exports = {
  onClick
}
```

Works:
```javascript
const setAPIOrigin = require('../../lib/set-api-origin')
const config = require('./config')
const events = require('./events')

$(() => {
  setAPIOrigin(location, config)
})

// use require with a reference to bundle the file and use it in this file
// const example = require('./example')
$(() => {
  $('.space0').on('click', function () {
      console.log('test')
})
```
To fix the problem, I tried putting the linked function directly into the event listener, which made it behave like I want it to, but that is not an ideal situation for the structure of the code. I also tried removing the arguments/parameters from the events.js function to make it as simple as possible but got the same result. I couldn't find any information online about the .on('click') method being triggered without a click.

The code isn't causing any errors, but it's not behaving like I expect, so my most recent "working" version was before adding the interactivity through event listeners to begin with.

Thanks!

**Comment by jordanallain** [comment]
What is the difference between your functions in the working and non working examples.

`not working`
```js
events.onClick(0)
```

`working`
```js
function () { console.log('test') }
```

**Comment by jordanallain** [comment]
hint: invocation vs definition

**Comment by bradleyden** [comment]
I'm still not sure what the difference is, aren't both of those functions being invoked, it's just that the one in the working example is anonymous and the non-working one was defined elsewhere?

**Comment by jordanallain** [comment]
how do we invoke a function?

**Comment by bradleyden** [comment]
Oh right, so we don't want to invoke the callback function. I took the parentheses off the function and it works the same.

But how would I be able to pass an argument into that callback, if I want several event listeners to use the same callback? Or do I need to make a new callback for each event listener?

**Comment by jordanallain** [comment]
sounds like you fixed the problem! wanna close this issue and open a new one!

**Comment by bradleyden** [comment]
Okay, thanks!
