### ISSUE TITLE
i am creating local variables and i need to make them global

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/game-project#773]
I am trying to get a variable that I created in a function to update globally.

I tried assigning it in the global scope but the function does not seem to update the value there.

**Comment by jordanallain** [comment]
how are you creating the variable?

**Comment by 3point14guy** [comment]
Yeah, so I messed up the wording there a little bit.

I created the variable at the top of my file as undefined and then the variable gets changed in the function I use.

**Comment by 3point14guy** [comment]
When the variable is changed by the function, it doesn't update globally

**Comment by jordanallain** [comment]
can you post some relevant code?

also, remember back to the api token auth lesson where you used `store` to hold data about the user temporarily?

**Comment by 3point14guy** [comment]
let currentMarker = 'x'
let lastMarkerPlayed
let oppositeMarker

if (currentMarker === 'x') {
  oppositeMarker = 'o'
}
 
// these select the x or o button
$('.x-button').on('click', function () {
  currentMarker = 'x'
  console.log(currentMarker)
})
$('.o-button').on('click', function () {
  currentMarker = 'o'
  console.log(currentMarker)
})

// these select squares 1-9 and then do a task
// first it checks if the currentMarker (either the x game piece or the o game
// piece) has been played; if no, enter the game piece in the square
$('.square-one').on('click', function () {
  if (currentMarker !== lastMarkerPlayed) {
    $('.square-one').text(currentMarker)
    lastMarkerPlayed = currentMarker
  } else {
    $('.square-one').text(oppositeMarker)
  }
})
// when I get to this one, only o will be played
$('.square-two').on('click', function () {
  if (currentMarker !== lastMarkerPlayed) {
    $('.square-two').text(currentMarker)
    lastMarkerPlayed = currentMarker
  } else {
    $('.square-two').text(oppositeMarker)
  }
})

**Comment by jordanallain** [comment]
going to re post your code with back ticks


```js
let currentMarker = 'x'
let lastMarkerPlayed
let oppositeMarker

if (currentMarker === 'x') {
  oppositeMarker = 'o'
}

// these select the x or o button
$('.x-button').on('click', function () {
  currentMarker = 'x'
  console.log(currentMarker)
})

$('.o-button').on('click', function () {
  currentMarker = 'o'
  console.log(currentMarker)
})

// these select squares 1-9 and then do a task
// first it checks if the currentMarker (either the x game piece or the o game
// piece) has been played; if no, enter the game piece in the square
$('.square-one').on('click', function () {
  if (currentMarker !== lastMarkerPlayed) {
    $('.square-one').text(currentMarker)
    lastMarkerPlayed = currentMarker
  } else {
    $('.square-one').text(oppositeMarker)
  }
})

// when I get to this one, only o will be played
$('.square-two').on('click', function () {
  if (currentMarker !== lastMarkerPlayed) {
    $('.square-two').text(currentMarker)
    lastMarkerPlayed = currentMarker
  } else {
    $('.square-two').text(oppositeMarker)
  }
})
```

**Comment by jordanallain** [comment]
did you check out the `api-token-auth` lesson that we did in class? we did a similar thing where we had to store the user data locally.

**Comment by 3point14guy** [comment]
looking now

**Comment by jordanallain** [comment]
remember after signing in we had to store the users token so that we could use it in future requests.

**Comment by 3point14guy** [comment]
so if I constructed my variables like this const store = {
}
that would solve the issue

**Comment by jordanallain** [comment]
you already have a store file in your file structure...if you make that file accessible to other files, then you could store variables in there

**Comment by payne-chris-r** [comment]
Jordan is right. You typically want to avoid global variables at all costs!

**Comment by 3point14guy** [comment]
Ok, code is not working how I expected with global variables in place, so I am going to try coding it a different way.
