### ISSUE TITLE
Clarification on Game Requirements

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/game-project#774]
I was looking at the API for the Tic Tac Toe. For the Boards part, it looks like the actions are set up for people playing against each other on different devices. On Monday, Scott told us to set it up so that people are playing on the same device. I'm just kinda confused. We are making Tic Tac Toe for people to play on the same device right?

**Comment by jordanallain** [comment]
yes, it's a bonus to allow users on multiple devices to play against each other.

**Comment by kailinc** [comment]
How do people do that?? Ok thanks!
