### ISSUE TITLE
How do I create an object in Javascript?

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#777]
I've reach an new low. I'm trying to create a create an object for a turn counter in my js. I have been using: 
`let turnCounter = {
  counter: 0 
}
`
The error message I get back is "Uncaught ReferenceError: turnCounter is not defined
    at <anonymous>:1:1". 

My hope is that by using an object I can put turnCounter.counter++ in a function and be able to keep track of the turns.

**Comment by jordanallain** [comment]
Why make it an object if it's only holding one numerical value?

**Comment by CoreyFedde** [comment]
So I can affect the global object within functions. I've been thinking that if in this scenario:
` let var = 0
function() {
var++
}
`
Var would still equal 0. But with an object it would change values. Am I wrong?

**Comment by jordanallain** [comment]
As long as you use `let` you're good to go

**Comment by jordanallain** [comment]
The thing with var++ is that it will return the value of var and then increment it afterwards, so it may appear to not change it but it does.

**Comment by CoreyFedde** [comment]
`let turnCounter = 0`
Still getting the same error on developer tools "VM14680:1 Uncaught ReferenceError: turnCounter is not defined
    at <anonymous>:1:1"

**Comment by CoreyFedde** [comment]
Luke just summed it up for me. You can't access variables within JS files through the developer tools, but they are still working in your code. Adding console logs can help you keep track of what they are internally.
