### ISSUE TITLE
I somehow broke my local server

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/game-project#778]
I tried to change the address where I was sending requests to (in my scripts and in my API config), and now my localhost won't load.

I tried looking through the closed answers but didn't find anything similar.

Error on dev tools is Syntax Error: Unexpected token in JSON at position 1.

Also in console is says [WDS] Disconnected!

**Comment by jordanallain** [comment]
Can you post the code you changed?

**Comment by jbculbertson** [comment]
I changed the first line of each of my .sh files to look like this:

curl "https://aqueous-atoll-85096.herokuapp.com/$ID"

I also changed the config file to look like this:

'use strict'

const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com/'
  }
}

module.exports = config

**Comment by jordanallain** [comment]
Did you shut down your server and start it back up and it wouldn't start?

**Comment by jbculbertson** [comment]
I don;t think so?

I changed these links from the ge-library one we used the other day.  It was working file (for login and signup), until I changed

**Comment by jordanallain** [comment]
Try to restart it and post any errors you get

**Comment by jbculbertson** [comment]
grunt serve starts up fine.  Page is 'paused on excepton: Syntax error: unexpected token in JSON at position 1

**Comment by jordanallain** [comment]
Does the chrome console show you anything useful? Sometimes it will show you the line that it's erroring on which isn't always helpful but may be.

**Comment by jbculbertson** [comment]
it seems to be pointing to a file called json3.js

**Comment by payne-chris-r** [comment]
Let's take a look first thing this morning

**Comment by jbculbertson** [comment]
resolved by adding a dev server to my config file
