### ISSUE TITLE
SCSS linter errors

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/game-project#779]
I am having the same linter errors that other people were having recently.  I hadn't yet opened my SCSS file to see these, or I would hae reported earlier.

Basically my linter is constantly shouting at me "error running scss-lint

**Comment by cpearce31** [comment]
https://github.com/ga-wdi-boston/game-project/issues/768

**Comment by BenGitsCode** [comment]
Were you able to solve @jbculbertson ?

**Comment by jbculbertson** [comment]
I had to turn off the linter last night. I'll be in soon if someone could
help me troubleshoot - i think it was the same issue others were having

**Comment by BenGitsCode** [comment]
👍 We can take a look at both when you're in.

**Comment by cmcqueen1987** [comment]
I am having the same issue as well. I was going to write up an issues right now, but looks like Jeff beat me to the punch!

**Comment by cmcqueen1987** [comment]
^ I actually just resolved my own issue by following Caleb's post above. It was having trouble at first because I didnt restart Atom. ALL GOOD!

**Comment by jbculbertson** [comment]
fixed
