### ISSUE TITLE
general issues

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#78]
My html/css/javascript is working and project looks good and works -  no linter errors.

I need some general help talking through the back-end integration

Thanks, Arif

**Comment by RDegnen** [comment]
can you be more specific?

**Comment by pvdri** [comment]
I'm having an issue approaching the login - just stuck

**Comment by RealWeeks** [comment]
You have to be more specific, what are you stuck on?  What are you error messages? What have you written when it comes to login thus far?

**Comment by pvdri** [comment]
I don't know what I'm supposed to do... with ajax and the login...

**Comment by RealWeeks** [comment]
What have you tried?

**Comment by pvdri** [comment]
I need help understanding a concept... not specific code

**Comment by gaand** [comment]
Have you referred to the `api-token-auth` training I led on Friday?

**Comment by pvdri** [comment]
yes, i have referred to it

**Comment by gaand** [comment]
Then you should have more specific questions.

**Comment by pvdri** [comment]
I'm confused about which login to use and create, I'm confused with how the ajax works with it, and what should be saved and displayed on our tic tac toe game

**Comment by gaand** [comment]
Focus on one issue at a time.

I'm not sure what you mean by "which login to use".  Could you clarify?  The API doc specifies what's required to sign-in.  The api-token-auth talk on Friday covered using the part of the API from JavaScript and from a shell script.

**Comment by pvdri** [comment]
I know... I didn't understand it... perhaps I'm just slow

**Comment by pvdri** [comment]
Regarding the login :  I'm not sure how to create it and submit it / what is the relationship of the form to the API...

**Comment by laurenfazah** [comment]
@pvdri you should be able to refer to the AJAX examples we ran in class. You'd send data to the game API endpoints in the same fashion for every action(verb) you need to make.

**Comment by RDegnen** [comment]
The form is what collects the data that you want to send to the API

**Comment by pvdri** [comment]
so the input form on HTML collects the data, that data is then submitted to an external server using ajax, and then...

**Comment by pvdri** [comment]
when i re log in

**Comment by pvdri** [comment]
form submits the data again

**Comment by pvdri** [comment]
and I should be logged in?

**Comment by RDegnen** [comment]
When your successfully logged in the server should respond with a user object

**Comment by pvdri** [comment]
this an incredibly inefficient way to respond to conceptual questions.... this format works well with specific questions...

**Comment by pvdri** [comment]
If I want to confuse myself, there are plenty of online resources to do it - I'm here because there is a failing in my understanding

**Comment by pvdri** [comment]
??

**Comment by laurenfazah** [comment]
Arif, understanding starts with specific questions. Our lesson time was to go over the concepts as a whole. Revisit those lessons and try to work through this process, step by step. It should be in this step by step process that specific questions pop up. Asking us like this in a very unprofessional manner to explain these general concepts during project week is not acceptable. This is what 1:1 time up through now was meant for. 

If you are confusing yourself, I suggest you step back and take notes while thinking through each step of this process, then revisit those notes and try to piece them together with code. Again, step by step. If you are attempting something and that is throwing you issues, we can help you diagnose that specific thing you are attempting. But until you attempt something, we cannot step in to assist. That would be cheating you of your understanding.
