### ISSUE TITLE
Jquery .on event handler listening for click on game board grid

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/game-project#780]
Trying to create a jquery function for my game board using .on

Linter Output:
nothing

Issue Description:
I can't figure out how to get a console log to display 'working' to let me know if I'm clicking a square on my game board

code:
[

const clickSuccess = function () {
  event.preventDefault()
  console.log('click success!')
}

// display console log when clicking designated coordinate of 3x3 grid..
```js
const addHandlers = () => {
  $(document).on('click', clickSuccess)
  $('#A2').on('click', clickSuccess)
  $('#B1').on('click', clickSuccess)
}

module.export = {
  addHandlers
}
]
```

this is what I'm targeting: 
```html
      <div class="rowA">
        <div id='A1' class="col-xs-6 col-xs-6 box"> a1
        </div>
        <div id='A2' class="col-xs-6 col-xs-6 box"> a2</div>
      </div>
```
[ I tried setting $(document).on to see if anywhere on the document would trigger the handler but no luck ]

**Comment by jordanallain** [comment]
do you have a document ready function anywhere?

**Comment by ryanwk** [comment]
no, I'm not sure what that is.
I tried pasting this into the console: 
```js
$(document).ready(function () {
  $('body').on('click', '#B1', function () {
    event.preventDefault()
    console.log('click success!')
  })
})
```
that works in the console but not in atom

**Comment by ryanwk** [comment]
I think my 'eventListener.js' file isn't connected to my index.js. Should it be?

**Comment by jordanallain** [comment]
refer back to the jquery lessons where we got books with a button/form. we had to attach our addHandlers function to the DOM when the page was fully loaded.

**Comment by tvcrawley** [comment]
@ryanwk Update?

**Comment by ryanwk** [comment]
stumped

**Comment by ryanwk** [comment]
I had my event listeners held in a file called 'eventListeners'.js 
I was having trouble linking that file with Index.js
So we required my eventListeners.js file in index.js 
```js
const eventListeners = require('./eventListeners')
```
then export my functions in eventListeners.js 
```js
module.exports = {
  addHandlers
}
```
I was missing an S from module.export!!! should have been 'module.exports', thank you!
