### ISSUE TITLE
error: POST http://localhost:4741/sign-up net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/game-project#781]
getting the error above when trying to do sign-up.  

curl request works, so it is somewhere in my code.  

attempted to change /localhost:4741/ to https://ga-library-api.herokuapp.com/sign-up as developer tools indicates that is where the problem is.  this did not work.  unsure of where to go from here.

**Comment by 3point14guy** [comment]
changed config.js to
```js
'use strict'

const config = {
  apiOrigins: {
    development: 'http://tic-tac-toe.wdibos.com',
    production: 'http://tic-tac-toe.wdibos.com'
  }
}

module.exports = config
```
making progress I think.  now get 400 bad request

**Comment by jordanallain** [comment]
the production url should be a different though.

**Comment by 3point14guy** [comment]
const config = {
  apiOrigins: {
    development: 'http://tic-tac-toe.wdibos.com',
    production: 'https://aqueous-atoll-85096.herokuapp.com'
  }
}
still 400 bad request

**Comment by 3point14guy** [comment]
so Jeff says this is the same issue he was having and Ben fixed it for him but Jeff is not entirely sure how to explain it to me

**Comment by 3point14guy** [comment]
fixed: missing "/" from production URL
production: 'https://aqueous-atoll-85096.herokuapp.com/'
