### ISSUE TITLE
Ongoing issue - jquery.js:9566 POST http://localhost:4741/sign-up net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/game-project#783]
Spoke with Ben this morning, we couldn't figure out why my connection is refusing.  

Ben instructed me to re-download the browser template, and copy over code from curl files and js files.  

Did that, and I'm gettng the same error in console when I try to signup

POST http://localhost:4741/sign-up net::ERR_CONNECTION_REFUSED
send @ jquery.js:9566
ajax @ jquery.js:9173
signUp @ api.js:7
onSignUp @ events.js:10
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
09:17:53.096 jquery.js:9566 XHR failed loading: POST "http://localhost:4741/sign-up".
send @ jquery.js:9566
ajax @ jquery.js:9173
signUp @ api.js:7
onSignUp @ events.js:10
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014

**Comment by Jcornmanhomonoff** [comment]
What does your config file look like?

**Comment by jbculbertson** [comment]
'use strict'

const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com/'
  }
}

module.exports = config

**Comment by jbculbertson** [comment]
now I am looking at my api file, and I'm pointing to apiOrigin.  Not apiOrigins

**Comment by BenGitsCode** [comment]
With it changed to `apiOrigin` what messaging are you getting in the console on sign-up?

**Comment by jbculbertson** [comment]
POST http://localhost:7165/[object%20Object]/sign-up 404 (Not Found)

**Comment by jbculbertson** [comment]
Ben fixed by adding a development server to my config file

**Comment by jbculbertson** [comment]
Hey Ben - Do I need to point my curl requests to the dev server instead of the production one.

When I attempt to create an account through local host site, I get the error below:
POST http://tic-tac-toe.wdibos.com/sign-up 400 (Bad Request),

and when I try it via the command line, I get this crazy error:

SWORD='c' sh scripts/sign-up-json.sh
HTTP/1.1 404 Not Found
Server: Cowboy
Date: Wed, 28 Jun 2017 16:49:06 GMT
Connection: keep-alive
Content-Type: text/html; charset=utf-8
X-Request-Id: 8977de30-eb9a-4239-8411-4e43adcf4912
X-Runtime: 0.003171
Vary: Origin
Content-Length: 1564
Via: 1.1 vegur

<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  
  <div class="dialog">
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
┌─[jeffculbertson@Jeffs-MacBook-Air-2] - [~/wdi/projects/new-project] - [Wed Jun 28, 12:49]

**Comment by jbculbertson** [comment]
thank you Scott, a million times.  Scott clarified this issue and more.

This issue was because in the middle of changing my urls around in curl request scripts, I ended up removing the trailing /sign-up, /sign-in, etc.  Fixed that, and then went through tokens for about 30 minutes, which helped a ton!
