### ISSUE TITLE
Don't know how to check for column wins

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/game-project#784]
Hello! 
I currently have the following long-winded logic to check for wins in each row of the board:

```
$('#game-board').on('click', function (event) {
  console.log(event, event.target)
  if (piecesInPlay.length % 2 === 0 && piecesInPlay.length < 9) {
    $(event.target).html('x')
    event.preventDefault()
    if ($('#row-one').children().text() === 'xxx') {
      console.log('win')
    } else if ($('#row-one').children().text() === 'ooo') {
      console.log('winwin')
    } else if ($('#row-two').children().text() === 'xxx') {
      console.log('win')
    } else if ($('#row-two').children().text() === 'ooo') {
      console.log('winwin')
    } else if ($('#row-three').children().text() === 'xxx') {
      console.log('win')
    } else if ($('#row-three').children().text() === 'ooo') {
      console.log('winwin')
    }
  } else if (piecesInPlay.length % 2 !== 0 && piecesInPlay.length < 9) {
    $(event.target).html('o')
    event.preventDefault()
    if ($('#row-one').children().text() === 'xxx') {
      console.log('win')
    } else if ($('#row-one').children().text() === 'ooo') {
      console.log('winwin')
    } else if ($('#row-two').children().text() === 'xxx') {
      console.log('win')
    } else if ($('#row-two').children().text() === 'ooo') {
      console.log('winwin')
    } else if ($('#row-three').children().text() === 'xxx') {
      console.log('win')
    } else if ($('#row-three').children().text() === 'ooo') {
      console.log('winwin')
    }
  } else {
    console.log('draw')
  }
```

**What I can't figure out now is how to check for wins in each column (up and down) without writing even longer winded logic.** Any pointers? Thanks!

**Comment by jordanallain** [comment]
do you have any thoughts as to how you could maybe break this code down into something more DRY? maybe a function that can accept arguments?

**Comment by jingrid** [comment]
I have some idea, I tried changing each of the 
`if ($('#row-one').children().text() === 'xxx') `
to just
`if ($('.row').find('.col-xs-4 box').text() === 'xxx')`
but that didn't work.

**Comment by BenGitsCode** [comment]
What did it do differently?

**Comment by payne-chris-r** [comment]
You probably don't want to be doing logic based on what's in the DOM. You want the DOM to render what your logic/data model holds. There's a few reasons for this:
1. It separates your concerns -- js array and logic decides game information, your CSS/DOM/jquery handles the UI of that.
2. It's much easier to check through the values in an array than 9 sections of the DOM.
