### ISSUE TITLE
API Documentation Question Regarding User Object

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/game-project#786]
With the API set up, is it possible to get the user object by his or her id and then manipulate values? I was thinking to add  { "totalWins" : 10 }. Something Like that. This is for the purpose of getting the total wins of a player and updating totalwins after each game.

**Comment by jordanallain** [comment]
you shouldn't have to manipulate the user object at all, each game is stored with a user associated with it, so retrieving all the games will only return games associated with that user. does this answer your question at all?

**Comment by kailinc** [comment]
I was thinking about the getting total wins of the user. In getting all the games of the user, the documentation seems like it doesn't have an attribute to tell which player wins. It only says if the game is over or not.

**Comment by jordanallain** [comment]
knowing that a game is over, and having the array stored with that game, would it be possible to find out which player won?

**Comment by kailinc** [comment]
gotcha! use a function to check the array for wins
