### ISSUE TITLE
Can't access API from localhost

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#787]
I've set up a basic sign up form as a starting point based on the authorization lesson, and I'm getting an error when I try to make a new user:

XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:7165' is therefore not allowed access.

api.js signUp function:
```javascript
const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```
config.js:
```javascript
const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com'
  }
}

module.exports = config
```
API Origin:
```javascript
const setAPIOrigin = (location, config) => {
  // strip the leading `'?'`
  const search = parseNestedQuery(location.search.slice(1))

  if (search.environment === 'development' ||
      location.hostname === 'localhost' &&
      search.environment !== 'production') {
    if (!(config.apiOrigin = config.apiOrigins.development)) {
      // const port = +('GA'.split('').reduce((p, c) =>
      //   p + c.charCodeAt().toString(16), '')
      // )
      config.apiOrigin = `https://ga-wdi-boston.herokuapp.com`
    }
  } else {
    config.apiOrigin = config.apiOrigins.production
  }
}

module.exports = setAPIOrigin
```
What does this error mean? I tried looking it up but the MDN documentation seemed a little over my head.

Thanks!

**Comment by jordanallain** [comment]
the error is basically saying the api you are trying to hit is not accepting requests from you.

you don't have the correct api url in there.

**Comment by BenGitsCode** [comment]
Have you searched the issue queue for the correct url for the game project api?

**Comment by bradleyden** [comment]
Oh yeah, I got it. API url is https://ga-library-api.herokuapp.com. It's working now.

I thought the url in config.js was pointing to the api, but it's not. Thank you!
