### ISSUE TITLE
Structuring Issue

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/game-project#788]
I have made the AJAX request for creating a game. After creating a game, I plan to do something 
similiar to getFormFields. After creating the game, I want  JS to run a file that will handle the Game Operations. The Game Operations will have click listener on the boards, win checks, turns, tie checks, and ajax request for updating the board. How should I structure this? I'm afraid that structuring it wrong will cause some weird bug that will take a long time to fix. 

![image](https://user-images.githubusercontent.com/25471305/27644278-1372fad0-5bf1-11e7-91e4-9100457b482e.png)

**Comment by jordanallain** [comment]
i would model it after the user file structure. do you have a reason for a gameOperation file as well as a boardEvents file?

**Comment by kailinc** [comment]
I just wanted to make it neater. I was just over thinking my structuring. It seems like it works well, but I do appreciate it if anyone takes some time to look at the structuring of my files and give me some pointers. Cheers.
