### ISSUE TITLE
Page Continually Crashing

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#79]

**Comment by louarnos** [comment]
my page is currently crashing with no errors. At a certain point in my code, my page becomes unresponsive.

**Comment by louarnos** [comment]
also my linter errors dont seem to be showing up.

**Comment by RealWeeks** [comment]
At what point does your page crash? / Do you have any loops in your code, those are generally a good place to start.

**Comment by gaand** [comment]
Please run `grunt nag` and paste the output.

**Comment by RealWeeks** [comment]
For the linter problem, please open a separate issue so we can track and target that.

**Comment by louarnos** [comment]
```
'use strict'

const findWin =  require('./findWin.js');
const game = require('./game-data.js');
const move = require('./make-move.js');

const play = () => {
  debugger;
  while(game.moveCount < 9 ){
    debugger;
    $('.board').find('box').click(function(){
      debugger;
      event.preventDefault();
      let currentBox = $(this);
      debugger;
      if(true){
        move.makeMoveX(currentBox);
        // $('.00.p').val('x')
        // // update game state
        // game.game.cells[0] = 'x'
        // game.playerOnesTurn = (!game.playerOnesTurn);
        // game.moveCount +=1;
      }else if (false) {
        move.makeMoveO(currentBox);
        // $('.00.p').val('o')
        // //update game state
        // game.game.cells[0] = 'o'
        // game.playerOnesTurn = (!game.playerOnesTurn);
        // game.moveCount +=1;
      }
    });

  }
}

module.exports = {
  play,
};
```

Its making it inside the while loop, but won't make it to the 3rd debugger. So its failing on

```
 $('.board').find('box').click(function(){
```

**Comment by RealWeeks** [comment]
Check your if/else syntax

**Comment by RealWeeks** [comment]
you may have more bugs as well but that is a place to start.

**Comment by louarnos** [comment]
Ok, its not making to the if statement. It crashes before the 3rd debugger.

**Comment by louarnos** [comment]
the true/false statements in the conditional is just so I can test this portion of the code. They will be changed.

**Comment by gaand** [comment]
As I said abovet, please paste the output of running `grunt nag`.

**Comment by RealWeeks** [comment]
@louarnos are you still having issues?
