### ISSUE TITLE
Can't get console to log anything on sign-up submit button

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/game-project#790]
Hello

I'm adding an event handler for the sign-up button:
```
const addHandlers = () => {
  $('#sign-up').on('submit', console.log('working'))
}
module.exports = {
  addHandlers
}
```
but this doesn't log anything into my console when I click on the ('submit') button. 

Here is my html for the sign up form:
```
  <form id="sign-up">
    <fieldset>
      <legend>Sign up!</legend>
      <input type='text' placeholder='email' name='credentials[email]'>
      <input type='password' placeholder='password' name='credentials[password]'>
      <input type='password' placeholder='password again' name='credentials[password_confirmation]'>
      <input type="submit" name="submit" value="Sign up!">
    </fieldset>
  </form>
```

**Comment by Jcornmanhomonoff** [comment]
What does your button look like for the form?

**Comment by Jcornmanhomonoff** [comment]
Are you requiring addHandlers somewhere?

**Comment by jingrid** [comment]
My button:

When I set my console to 'Preserve Log' and then click the button, I get
the following msg

Navigated to http://localhost:7165/?credentials%5Bemail%5D=&
credentials%5Bpassword%5D=&credentials%5Bpassword_
confirmation%5D=&submit=Sign+up%21
​

**Comment by Jcornmanhomonoff** [comment]
Ignore the button comment (hence why it was deleted). Where are you requiring `addHandlers`?

**Comment by jingrid** [comment]
Hm I'm not sure where to require addHandlers

**Comment by jingrid** [comment]
Oh wait, I just added it to index.js and now it works
