### ISSUE TITLE
Issue testing my sign-up form

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/game-project#792]
Am getting the following error when trying to test my sign up form sheet
ReferenceError: setAPIOrigin is not defined

**Comment by cpearce31** [comment]
Can you provide the full error?

**Comment by Azinck94** [comment]
jquery.js:3860 jQuery.Deferred exception: setAPIOrigin is not defined ReferenceError: setAPIOrigin is not defined
    at HTMLDocument.<anonymous> (http://localhost:7165/public/application.js:32:4)
    at mightThrow (http://localhost:7165/public/vendor.js:11499:30)
    at process (http://localhost:7165/public/vendor.js:11567:13) undefined

**Comment by BenGitsCode** [comment]
can we see your `config.js` and `api.js` ❓

**Comment by Azinck94** [comment]
**CONFIG.JS**
`'use strict'
const config = require('./config')
const store = require('./store')

const signUp = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/sign-up/',
    method: 'POST',
    data
  })
}

const signIn = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/sign-in/',
    method: 'POST',
    data
  })
}
const changePassword = function (data) {
  // console.log('api data is: ', data)
  // console.log('api data is: ', store)
  return $.ajax({
    url: config.apiOrigin + '/change-password/' + store.user.id, // ':id',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
const signOut = function () {
  return $.ajax({
    url: config.apiOrigin + '/sign-out/' + store.user.id,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

module.exports = {
  signUp,
  signIn,
  changePassword,
  signOut
}`

**Comment by Azinck94** [comment]
**CONFIG.JS**
'use strict'

const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com'
  }
}

module.exports = config

**Comment by Jcornmanhomonoff** [comment]
Please format your code

**Comment by Azinck94** [comment]
```'use strict'
const config = require('./config')
const store = require('./store')

const signUp = function (data) {
console.log(data)
return $.ajax({
url: config.apiOrigin + '/sign-up/',
method: 'POST',
data
})
}

const signIn = function (data) {
console.log(data)
return $.ajax({
url: config.apiOrigin + '/sign-in/',
method: 'POST',
data
})
}
const changePassword = function (data) {
// console.log('api data is: ', data)
// console.log('api data is: ', store)
return $.ajax({
url: config.apiOrigin + '/change-password/' + store.user.id, // ':id',
method: 'PATCH',
headers: {
Authorization: 'Token token=' + store.user.token
},
data
})
}
const signOut = function () {
return $.ajax({
url: config.apiOrigin + '/sign-out/' + store.user.id,
method: 'DELETE',
headers: {
Authorization: 'Token token=' + store.user.token
}
})
}

module.exports = {
signUp,
signIn,
changePassword,
signOut
}```

**Comment by Azinck94** [comment]
CONFIG.JS
```'use strict'

const config = {
apiOrigins: {
production: 'https://ga-wdi-boston.herokuapp.com'
}
}

module.exports = config```
Sorry about that, thanks!

**Comment by Azinck94** [comment]
I am reading through this issue to see if there is any correlation, will keep you guys updated. Thanks!
https://github.com/ga-wdi-boston/full-stack-project/issues/619

**Comment by Azinck94** [comment]
Still can't figure it out, have been through all the auth files. Am still getting this Uncaught TypeError: setAPIOrigin is not a function
    at HTMLDocument.<anonymous> (index.js:7)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)
here is my set-api-origin.js
 ```
'use strict'

const parseNestedQuery = require('./parse-nested-query')

/*
  possibilites to handle and example URLs:

  client local, api local
    http://localhost:7165/
  client local, api remote
    http://localhost:7165/?environment=production
  client remote, api local
    https://ga-wdi-boston.github.io/browser-template/?environment=development
    This will require allowing "unsafe scripts" in Chrome
  client remote, api remote
    https://ga-wdi-boston.github.io/browser-template/
*/

const setAPIOrigin = (location, config) => {
  // strip the leading `'?'`
  const search = parseNestedQuery(location.search.slice(1))

  if (search.environment === 'development' ||
      location.hostname === 'localhost' &&
      search.environment !== 'production') {
    if (!(config.apiOrigin = config.apiOrigins.development)) {
      const port = +('GA'.split('').reduce((p, c) =>
        p + c.charCodeAt().toString(16), '')
      )
      config.apiOrigin = `http://localhost:${port}`
    }
  } else {
    config.apiOrigin = config.apiOrigins.production
  }
}

module.exports = {
  setAPIOrigin
}
```

**Comment by Azinck94** [comment]
Index.js 
```'use strict'

const setAPIOrigin = require('../../lib/set-api-origin')
const config = require('./config')

$(() => {
  setAPIOrigin(location, config)
})

require('./example')

let turnCounter = 0


// logic
$('#game-board').on('click', function (event) {
  if (turnCounter % 2 === 0) {
    const fill = $(event.target).text()
    if (fill === '') {
      $(event.target).text('x')
      $('#game-text').text('Player 2 Turn')
      turnCounter++
      console.log(turnCounter)
    }
  } else {
    const fill = $(event.target).text()
    if (fill === '') {
      $(event.target).text('o')
      $('#game-text').text('Player 1 Turn')
      turnCounter++
      console.log(turnCounter)
    }
  }
})


$('#new-game-button').on('click', function (event) {
  console.log('button clicked')
  $('#game-text').text('New game!')
  turnCounter = 0
  // Create an array to represent the game-board
  $('.game-cell').each(function () {
    $(this).text('')
  })
})

const authEvents = require('./events.js')


$(() => {
  authEvents.addHandlers()
})

module.exports = {
  authEvents
}

**Comment by Azinck94** [comment]
config.js
```'use strict'

const config = {
  apiOrigins: {
    production: 'https://aqueous-atoll-85096.herokuapp.com'
  }
}

module.exports = config
