### ISSUE TITLE
Submitting sign up form

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#794]
I have a function that should submit the data of the sign up form and prevent it from refreshing, but when clicked it is still refreshing and I can't tell if the submit is working.

Have tried adding console.logs and changing the event handler to "click" instead of submit to verify the button is working.

Code for function:
API.js
`const onSignUp = function (event) {
  event.preventDefault()
  console.log(getFormFields(event.target))
  const data = getFormFields(event.target)
  if (data !== 0) {
    signUp(data.id)
      .then('Success')
      .catch('Error')
  } else {
    console.log('Please provide an email id!')
  }
}`
Index.js
`$('#submitSignUp').on('submit', api.onSubmit)`
HTML
`<button id="submitSignUp" type="submit" class="btn btn-default">Submit</button>`

**Comment by jordanallain** [comment]
should you be listening for the submit of a button or a form?

**Comment by CoreyFedde** [comment]
THANK YOU. 

Switched the index.js command to focus on the form and it is now working. Although will not be able to verify fully until you can log in.
