### ISSUE TITLE
Clearing board

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/game-project#795]
I'm having trouble clearing my board.  I can successfully clear the board, but then I can only seem to play one additional play.  I feel like this is related to me turning off my event listener in my selectCell board, but I thought I overcame that by redeclaring my event handlers in my clearBoard function.  Both are below.  I'd love some advise on how I might get through this!

```
const onSelectCell = function () {
  $(this).text(whoseTurn)
  $(this).off()
  gameBoard[this.dataset.id] = whoseTurn()
  totalMoves += 1
  evaluateBoard(gameBoard)
  console.log(totalMoves)
}

const onClearBoard = function (event) {
  event.preventDefault
  $('#0').on('click', onSelectCell).text('')
  $('#1').on('click', onSelectCell).text('')
  $('#2').on('click', onSelectCell).text('')
  $('#3').on('click', onSelectCell).text('')
  $('#4').on('click', onSelectCell).text('')
  $('#5').on('click', onSelectCell).text('')
  $('#6').on('click', onSelectCell).text('')
  $('#7').on('click', onSelectCell).text('')
  $('#8').on('click', onSelectCell).text('')
}
```

**Comment by cpearce31** [comment]
Are you sure `$(this)` is referring to what you think it is? What do you get if you `console.log` it?

**Comment by jbculbertson** [comment]
I think that t-his is referring to the object that was clicked on to invoke the function.  It works the first time through, just not after reset.

When I CL it, I get <div class='col-xs-4 box' id='0' data-id='0'> </div> 

This works the first time, as I capture the data-id in it

**Comment by jbculbertson** [comment]
<div class="col-xs-4 box" id="2" data-id="2"></div>

**Comment by jbculbertson** [comment]
'''
div class="col-xs-4 box" id="2" data-id="2"
'''

**Comment by payne-chris-r** [comment]
When do you call onClearBoard?

**Comment by payne-chris-r** [comment]
Does the method chaining with `.text('')` work?! That's kind of cool.

**Comment by jbculbertson** [comment]
chatted this with Caleb for a bit.  The .text chaining does work!  But I'm still not able to reset my board the way I want.  onClearBoard is called automatically whenever a game is finished .  I used to have it be manually when a game was finished by clicking a button.  However, both leave me unable to then initiate a OnSelectCell function

**Comment by jbculbertson** [comment]
chatted with Chris for a bit (thanks Chris).

My mistake was that I was never explicitly clearing the gameBoard array upon completion of a game.  Once I did that, issue went away
