### ISSUE TITLE
trouble implementing my logic

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/game-project#797]
When someone clicks a space on my game board I want to place an X or an O in that space. 

This function works: 
```js
const xGoes = function () {
  $('#middle').on('click', function (event) {
    $(event.target).html('X', event.target)
  })
}
```
Now I've created some logic that will allow players to switch turns and place the appropriate X or O in a space upon clicking the board.

```js
let xTurn = true

const toggleTurn = function () {
  if (xTurn === true) {
    return xGoes()
  } else if (xTurn === false) {
    return oGoes()
  }
}

const xGoes = function () {
  $('#middle').on('click', function (event) {
    $(event.target).html('X', event.target)
    xTurn = false
  })
}

const oGoes = function () {
  $('#middle').on('click', function (event) {
    $(event.target).html('O', event.target)
    xTurn = true
  })
}

module.exports = {
  toggleTurn
}
```

xTurn is the default or starting turn and it's set to true.
toggleTurn invokes the xGoes / oGoes function depending on what the boolean value of Xturn is.
After a player clicks, then xTurn is changed to allow a players turn to change, and subsequently invoke the appropriate function that would place an X or O in a grid square on the game board.

I think the logic is sound but I'm not getting any results when implementing this. What am I doing incorrectly?

**Comment by jordanallain** [comment]
```js
const xGoes = function () {
  $('#middle').on('click', function (event) {
    $(event.target).html('X', event.target)
  })
}
```

Can you tell me what this function is doing?

**Comment by ryanwk** [comment]
When someone clicks my game board (the section with an ID="#middle")  
.on listens for a click then invokes a function (with an parameter 'event') .... 
I guess I don't understand the function

**Comment by jordanallain** [comment]
So this code:

```js
  $('#middle').on('click', function (event) {
    $(event.target).html('X', event.target)
  })
```

is targeting an HTML element with the ID of middle, and then saying, when someone clicks on this, run this function. Remember back to the jquery books lesson, we set those event listeners in a function called addHandlers, and then we invoked the addHandlers function when the document (page) was loaded. so it sets the event listener once, not every time the element is clicked.

if this doesn't help you understand let me know!

**Comment by ryanwk** [comment]
so I need to make it listen for every time a click occurs not just the first time?

**Comment by jordanallain** [comment]
you just want to be sure that the event listener is set when the page is done loading, not try to set it when they click on the cell. are you invoking the function that sets the event listener?

**Comment by ryanwk** [comment]
yes in my index.js file, where it is required, and it uses the short-hand to ensure the document is ready

**Comment by jordanallain** [comment]
cool i'll come sit with you and run through it together.

**Comment by ryanwk** [comment]
refactored my event listeners properly and used jquery .text to place text into a square on my game board
```js
const addHandlers = function () {
  $('.game-cell').on('click', placeX)
}

const placeX = function () {
  debugger
  $(this).text('X')
}
```
Thank you Jordan!!
