### ISSUE TITLE
Post error on sign in

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#798]
When using the sign in function I am getting back an error that says "POST http://tic-tac-toe.wdibos.com/sign-in/ 401 (Unauthorized)".

Code:
```
const onLogIn = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  // console.log(data)
  signIn(data)
    .then(console.log('Success'))
    .catch(console.log('Nope'))
}`

`const signIn = function (data) {
  return $.ajax({
    url: 'http://tic-tac-toe.wdibos.com' + '/sign-in/',
    method: 'POST',
    data
  })
}
```

**Comment by scottyscripts** [comment]
What do you see when you console.log `data` in your `onLogIn` function?

**Comment by CoreyFedde** [comment]
I don't get a console log for data at all. I think the error occurs before the console.log can happen.

**Comment by scottyscripts** [comment]
did you comment it out? I see `//` before it

**Comment by CoreyFedde** [comment]
*doh* The console.log provides an object that contains the right username and password.

**Comment by scottyscripts** [comment]
can you paste that object? It should look like something like this....
```
  "credentials": {
    "email": "an@example.email",
    "password": "an example password",
  }
```
lets make sure it's formatted correctly based on what the API is expecting. Make sure you are trying to sign in with a user you already created also!

**Comment by CoreyFedde** [comment]
Object {credentials: Object}
credentials:
Object email: "test3" 
password:"password"
__proto__:
Object constructor:
function Object() hasOwnProperty:
function hasOwnProperty()isPrototypeOf:
function isPrototypeOf() propertyIsEnumerable:
function propertyIsEnumerable()toLocaleString:
function toLocaleString()toString:
function toString()valueOf:
function valueOf()__defineGetter__:
function __defineGetter__()__defineSetter__:
function __defineSetter__()__lookupGetter__:
function __lookupGetter__()__lookupSetter__:
function __lookupSetter__()get __proto__:
function __proto__()set __proto__:
function __proto__()

**Comment by scottyscripts** [comment]
Are you positive that `YOU` are the one who created user named `test3`with a password as `password`. Why don't we try to create a new user and sign in with them to make sure this isn't an issue of not having the correct credentials

**Comment by CoreyFedde** [comment]
I used Test5189803 as the username and I'm getting the same error when I try to login.

**Comment by CoreyFedde** [comment]
Solution: sign-up was not working, so the console was throwing an error because the users were not created.
