### ISSUE TITLE
404 Not Found when creating game

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#799]
I'm trying to make a 'create game' button, but I get a 404 error in curl and AJAX when I try to run it.

curl:
```sh
curl "https://ga-library-api.herokuapp.com/games" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{}'
```
AJAX:
```js
const createGame = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    data
  })
}
```
Error message: POST https://ga-library-api.herokuapp.com/games 404 (Not Found)

My config.apiOrigin is working for all of the sign up/sign in features. Is the problem with my url?

**Comment by cpearce31** [comment]
Are you sure you're using the right API? (close was accidental, whoops!)

**Comment by bradleyden** [comment]
Okay, turns out I have no idea what the correct API url is and I've been working in the wrong one (since they both have end points at '/sign-up')

I'm going to dig up the correct url from a previous issue and post it here before closing.

**Comment by bradleyden** [comment]
correct API url is http://tic-tac-toe.wdibos.com
