### ISSUE TITLE
Adding player moves into an array

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/game-project#8]
I am using this function:

```
let player1Move = function () {
  $('.gameboard').children().on('click', function () {
  $(this).text('X');
};

to represent the first players move,

and this function:

let player1moves = []
function (player1moves) {
  $(.gameboard.box).push(player1move);
}
```

to store each move into an array in order to match an array in the winning conditions.

First issue is the player1move function breaks my game.
Second issue is a player will not reach a winning combination in the first 3 moves each game, meaning they could gather an array of 5 numbers total and that would never be equal to my winning combo arrays of only 3 numbers total.

Any suggestions on syntax or if i'm not thinking through the functions properly would be greatly appreciated!

**Comment by RealWeeks** [comment]
One issue at a time.  Paste in your error, and linter errors.

**Comment by jdamiron** [comment]
@J-Weeks no error is given

**Comment by RealWeeks** [comment]
what do you mean by "breaks my game"?

**Comment by jdamiron** [comment]
@J-Weeks all the CSS  is removed

**Comment by RealWeeks** [comment]
Open your chrome console and paste your error message. I'm positive there is one.

**Comment by gaand** [comment]
This appears to be missing quotes:

``` js
$(.gameboard.box).push(player1move);
```

**Comment by jdamiron** [comment]
```
./assets/scripts/gamelogic.js
Module build failed: SyntaxError: /home/jeremiah/wdi/projects/temp2/tictactoe/assets/scripts/gamelogic.js: Unexpected token (58:0)
  56 | //  }
  57 | // };
> 58 | 
     | ^

```

**Comment by jdamiron** [comment]
also

Uncaught Error: Cannot find module "./gamelogic"

**Comment by RealWeeks** [comment]
So is the first issue resolved? if so close this and open another.  If someone has the same issue we want them to be able to read through the issues for possible solutions.  Try to keep it one issue per thread.

**Comment by jdamiron** [comment]
no, this code:

let player1Move = function () {
  $('.gameboard').children().on('click', function () {
  $(this).text('X');
}

breaks the CSS on my game alone and throws the errors above.

**Comment by RealWeeks** [comment]
Solved: } / ) confusion.
