### ISSUE TITLE
Backend approach - will it break something?

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/game-project#80]
No errors - the code works as I intended. I just want to make sure my approach won't cause problems later on.

Since two users have to sign in, I'm having the sign-in success outcome assign the returned data to two different user variables. To sign out, I'm having the sign-out success outcome run two different AJAX calls  because the different user id's for the url and tokens are in different places. Is this an ok way to approach it?

**Comment by philschoof** [comment]
Here is my sign-out success 

``` js
const signOut = (success, failure) => {
  $.ajax({
    method: "DELETE",
    url: app.api + '/sign-out/' + app.user1.id,
    headers: {
      Authorization: 'Token token=' + app.user1.token
    },
  }).done(success)
  .fail(failure);

$.ajax({
  method: "DELETE",
  url: app.api + '/sign-out/' + app.user2.id,
  headers: {
    Authorization: 'Token token=' + app.user2.token
  },
}).done(success)
.fail(failure);
};
```

**Comment by gaand** [comment]
You probably want to have the auth calls as two different events.

So, users sign in and sign out individually.  

That's not required, but seems less prone to confusion.  Also, when signing a user out, you want to nullify the user attribute.  The code you pasted doesn't appear to be able to handle that correctly.

**Comment by philschoof** [comment]
I see - thanks!
