### ISSUE TITLE
don't know how to update game in api.js

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/game-project#800]
I'm trying to update the game when each move is played, but 
- not sure how to format the api patch request
- not sure how to get my js to ping the api with each new move

This is what I currently have for my patch request:
```
const updateGame = function () {
  return $.ajax({
    url: app.host + '/games', + ??,
    method: 'PATCH'
  })
}
```

**Comment by jordanallain** [comment]
have you referenced the api docs for a patch request?

**Comment by jordanallain** [comment]
https://github.com/ga-wdi-boston/game-project-api#update-a-games-states

**Comment by jingrid** [comment]
Yes, but I'm still unsure how to format the request.

**Comment by cpearce31** [comment]
I think your Ajax request needs a `data` field. If you do:
```
const updateGame = function () {
  return $.ajax({
    url: app.host + '/games', + ??,
    method: 'PATCH',
    data: {}
  })
}
```
do you at least get back the current game state? You can replace `??` with a hardcoded ID to test it out.

**Comment by scottyscripts** [comment]
What does the `data` object you are sending look like? It should look similar to this with your own values
```
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
```

**Comment by cpearce31** [comment]
Any progress here?

**Comment by jingrid** [comment]
hm I'm not sure what the data object I'm sending looks like. I don't know how to format the object with things like 'game', 'cell', etc.

**Comment by cpearce31** [comment]
Let's take a look at your code.

**Comment by Azinck94** [comment]
am running into same problem myself!

**Comment by scottyscripts** [comment]
@jingrid update?

**Comment by jingrid** [comment]
I keep getting this error:
```
Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.updateGame (api.js:70)
```
my api.js updateGame function is:
```
const updateGame = function (data) {
  return $.ajax({
    url: app.host + '/games' + store.game.id,
    method: 'PATCH',
    data
  })
}
```
and my ui.js updateGameSuccess function is:
```
const updateGameSuccess = (data) => {
  store.game = data.game.id
  console.log('merpp')
  console.log(data)
}
```

**Comment by cpearce31** [comment]
Can you console.log `store` inside `updateGame` and post what you get back?

**Comment by jordanallain** [comment]
do you want to take a look at this together @jingrid ?

**Comment by jingrid** [comment]
@cpearce31 this is what I get back:
Object {store: Object}

@jordanallain yes pls

**Comment by jingrid** [comment]
In api.js, I put 'data' as the param to pass into my function: 
```
const updateGame = function (data) {
  console.log('data is', data)
  return $.ajax({
    url: app.host + '/games/' + store.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```
Then in events.js file, I pass the 3 params that need to be passed for the `PATCH` request according to https://git.generalassemb.ly/ga-wdi-boston/game-project-api#update-a-games-states 
```
const onUpdateGame = function (letter, index, gameOver) {
  const data = {
    'game': {
      'cell': {
        'index': index,
        'value': letter
      },
      'over': gameOver
    }
  }
  api.updateGame(data)
    .then(ui.updateGameSuccess)
    .catch(ui.updateGameFailure)
}
```
and then I call `updateGame` within the logic of my game, in order to retrieve the values I need to pass into `letter`, `index`, and `gameOver`.
