### ISSUE TITLE
improved my logic with jquery .text but how still stuck on toggling between x and o?

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/game-project#802]
When someone clicks a space on my game board I want to place an X or an O in that space.
used jquery this and .text to listen for clicking on any cell within my game board and then used .text to place an x or o in the appropriate cell.

This function works:

```js
let xTurn = true

const addHandlers = function () {
  $('.game-cell').on('click', placeX)
}

// or const addHandlers = function () {
//  $('.game-cell').on('click', placeX)
//}

const placeX = function () {
  $(this).text('X')
  xTurn = false
}

const placeO = function () {
  $(this).text('O')
  xTurn = true
}
```

but when I try to toggle between x and o.. something goes wrong...

```js

const addHandlers = function () {
  $('.game-cell').on('click', toggleTurn)
}

const toggleTurn = function () {
  if (xTurn === true) {
    return placeX()
    debugger
  } else if (xTurn === false) {
    return placeO()
  }
}

module.exports = {
  addHandlers,
  toggleTurn
  // clickSuccess
}
```

**Comment by jordanallain** [comment]
are you sure you want to be `return`ing those placeO and placeX function calls?

**Comment by ryanwk** [comment]
I took out the return, still nothing ... 

```js
const toggleTurn = function () {
  if (xTurn === true) {
    placeX()
  } else if (xTurn === false) {
    placeO()
  }
}
```
I put debugger in various places and it debugs so I'm thinking it does get to the point in which toggleTurn is invoked but my if statement doesn't seem to do anything

**Comment by ryanwk** [comment]
ok I've tried this but still stuck:
```js
const addHandlers = function () {
  $('.game-cell').toggle(function () {
    placeX()
  } function () {
    placeO()
  }
})
```
I'm not sure if I understand how to format .toggle but supposedly it invokes a function on one click then another on an odd click

**Comment by cpearce31** [comment]
Double check the docs on `.toggle()`, it doesn't do what you're describing: http://api.jquery.com/toggle/. Instead think about whether you can store whose turn it is somewhere outside of your `toggleTurn` function.

**Comment by ryanwk** [comment]
I've got that. 
```js
const addHandlers = function () {
  $('.game-cell').on('click', toggleTurn)
}

const placeX = function () {
  $(this).text('X')
   xTurn = false
}
const placeO = function () {
  $(this).text('O')
   xTurn = true
}

let xTurn = true

const toggleTurn = function () {
  if (xTurn === true) {
    placeX()
  } else if (xTurn === false) {
    placeO()
  }
}

module.exports = {
  addHandlers,
  toggleTurn
}
```
let xTurn = true. by default it is x's turn. then whenever placeX or placeO is executed, it changes xTurn to either true or false, which should alternate between X and O. 

however, when I try my game nothing happens. I tried breaking down toggleTurn to see if it would  pass placeX through the addHandlers event listener to see if the default of xTurn = true works and still nothing.

**Comment by cpearce31** [comment]
I would try putting a console.log inside toggleTurn to make sure that it's firing when you click an element with the class .game-cell.

**Comment by ryanwk** [comment]
I was able to get it working, built new functions, and added more features. Thank you Caleb and Jordan!
