### ISSUE TITLE
Question about API post requests for creating games

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#805]
I noticed that when I send a request to create a new game, it inserts the game into a seemingly random index in my games array. Sometimes the most recent game will appear at index 1 or 2, sometimes it will appear at 15, etc. I'm able to check this by using console.table() on the game array and sorting them by game id, but when I do that the index values are in a jumbled order, and likewise when I sort by index value, the game ids are in a random order.

How does the API determine where in the array to place a newly created game? Is there a way to always add a new game to the end of the array so that both the array index and game id are in order of when the game was created?

Here's my post request:
```javascript
const createGame = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/games',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

**Comment by scottyscripts** [comment]
So are you saying that once you do a POST request to create a game, the next time you do a GET for games they are all in a seemingly random order?

**Comment by scottyscripts** [comment]
Isn't your order of created games reflected in your `id` of your `game`. So if you had an array of game objects, is there a way you could order them based on each object's id?

**Comment by bradleyden** [comment]
Thanks Scott! So I should make a function to make a new array sorted by the id value then?

Is the API supposed to create an out of order array by default? I remember the book exercise added newly created books to the end of the array, so is this one set up differently? I should be able to resort the values pretty easily using a function, but I want to make sure I'm not doing something wrong to make them get created out of order to begin with.

**Comment by scottyscripts** [comment]
That sounds like an awesome solution! Perhaps using `.map` or one of the other array iteration functions we were using! The API takes other factors into account when querying like looking for games that are over, so it's possible they won't be in the order you created them. This API is set up differently though. Nope, you're not doing anything wrong as long as your games are actually being created! Nice job noticing that the API was doing this. Sometimes we'll have to manipulate the data we receive from an API to get it ordered how we want, but you'll see really soon how you can determine how data gets queried and sent when you build your own API.

**Comment by bradleyden** [comment]
Awesome, thanks! I will probably use .map to do that so I can always know the most recent game is the last object in the array.

It was mainly frustrating because for a while last night I was getting successful API responses after updating a game, but then I'd check the most recent game in the array thinking that was the game I'd just created and it would not have been updated, so I thought it wasn't working. Knowing this will be helpful when I start trying to make it possible to switch between active games!
