### ISSUE TITLE
My project is hosted on git.generalassembly instead of kailinc.github

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/game-project#809]
My code for the basic requirements are working perfectly and is ready to be set to the WEB! There is an issue though. Since I saved the repo on git.generalassembly instead of kailinc.github.com. Is that a problem? Do I have to somehow move the repo to my personal git hub?

**Comment by cpearce31** [comment]
You should be able to just make a blank repository on Github, change the URL of your remote, and push. Check this out for changing remote URLs: https://help.github.com/articles/changing-a-remote-s-url/.

**Comment by kailinc** [comment]
Will my commits and branches still be there after i change the URL of remote?

**Comment by kailinc** [comment]
I'm really scared that I'll mess up and all my code will be gone. Can an adult spend 5-10mins with me on doing this?

**Comment by kailinc** [comment]
Caleb walked me through it. The process was exactly like the link provided.
