### ISSUE TITLE
Linter not working

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#81]
Seems to be up to date but no issues ever show up for JS. Theyre fine for css and html.

**Comment by gaand** [comment]
Have you tried quitting out of atom completely then restarting it from the command line?

**Comment by RealWeeks** [comment]
Removed all linters and reinstalled, checked preferences all are correct.  Closed and reopened atom from the command line.  Linter issues still not showing at the bottom, severely hindering production. 
@gaand @jrhorn424 @MattB-GA-Boston Any ideas/ suggestions?

**Comment by louarnos** [comment]
fixed.

**Comment by gaand** [comment]
Disabled linter-eslint. Installed linter-jshint, linter-jscs. Added missing `.*rc` files.
