### ISSUE TITLE
Stuck on update PATCH request

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#812]
Hi all,

Similar issue to Ingrid's (https://github.com/ga-wdi-boston/game-project/issues/800), but I'm having trouble formatting a correct PATCH request to update the game and getting back even a current game state.

Relevant code:
AJAX Request
```js
const gameUpdates = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/games/' + save.game.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {}
  })
}
```
Calling it
```js
const getGameUpdates = function () {
  event.preventDefault()
  console.log(save.game.id)
  gameUpdates()
    .then(function (data) {
      console.log('Success')
      save.game = data.game
    })
    .catch(function (data) {
      console.log('Nope')
    })
}
```
Implement on click
```js
$('#gameActionButton').on('click', gameActions.getGameUpdates)
```

My goal right now is to get the current game state. I was following Caleb's instructions from the previous issue request linked above. 

But after logging in, creating a new game, and storing the ID, I'm getting back an error that says "PATCH http://tic-tac-toe.wdibos.com/games/2960 400 (Bad Request)"

I've tried changing the URL, playing with the request, and double checked the steps leading up to the request and have gotten stuck. 

Any help would be appreciated!

**Comment by Jcornmanhomonoff** [comment]
Okay so let's start from your ajax PATCH request. Specifically the URL. If you look at the [game project api docs ](https://git.generalassemb.ly/ga-wdi-boston/game-project-api), what path does it expect there for a game update?

**Comment by CoreyFedde** [comment]
`/games/:id`

I see what you mean, I saw that typo for the url and fixed it on my end, but forgot to fix it in the issue request. My URL is:
url: config.apiOrigin + '/games/' + save.game.id,

With save.game = data.game

**Comment by sdavidson140** [comment]
what does the `data` object you are sending look like? It should look similar to this ```
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
``` via api documentation

**Comment by Jcornmanhomonoff** [comment]
So if you look at what you're passing through your request for data, it's an empty object but it's actually expecting changes to the game. Direct quote via the api docs:

**update a game's states**

This update action expects a PATCH with changes to to an existing game, e.g.:
```js
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
```

**Comment by CoreyFedde** [comment]
I think my problem is I am not sure how to create a function that turns the game-board into an object that resembles what you have above.

**Comment by scottyscripts** [comment]
You don't necessarily need a function to do this. We are just creating an object with the keys specified here. In order to create this object we need to know 3 things
1) what is the index of the cell that was just updated (if its the first box in the top left its index 0, if its the last box in the bottom right it would be index 8)
2) what was the value that was just put in the square
3) Is the game over or not. 
Once we know all of these things, we can create a javascript object that looks like above and pass that object as the value to our `data` parameter in our AJAX patch request

**Comment by CoreyFedde** [comment]
Fixed (mainly).
The main issue for me was figuring out how to create an object with the keys specified above and then to pass it through an AJAX function to update the server.

You can create that object within the function where you call your AJAX request and use variables to pass it into JSON format before passing it to the function to update the server. Below is a sample code that is a loose structure that works:

```js
const updateServer = function () {
let varOfIndex = **find the index of the box you are changing**
let valueOfBox = **Find the new value of the box post change**
let overFunction = **A function that will determine whether or not your game is over**

const data = {
    'game': {
      'cell': {
        'index': varOfIndex,
        'value': valueOfBox
      },
      'over': overFunction
    }
  }
// pass the new data object to your AJAX function
gameUpdates(**data**)
}
```
