### ISSUE TITLE
Quick clarification about player_o and watch

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#813]
I just want to clarify something. Should we only be adding player_o data to a game object if we're doing the bonus for online play? In other words, for local hot seat multiplayer, we should be leaving that as null since we can't have two people be logged in at the same time on the same device right?

Also, the watch feature is also limited to the bonus objectives, and we shouldn't worry about it for the MVP correct?

If either of these are expected for the MVP, I will have some questions, but if they just exist for the bonuses I will leave them alone for now. Thanks!

**Comment by scottyscripts** [comment]
Correct! For an mvp you will not to send that information about player_x and player_o. You just want to make sure you are sending information about your game.  The watch functionality is also a bonus. You are free to leave these alone for now!

**Comment by bradleyden** [comment]
Sweet thanks!
