### ISSUE TITLE
can click forever!

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/game-project#814]
I have having issues with being able to alternate between x and o, but still having the ability to cycle through them and click the same square forever! I think I need either an if statement, or by looking online, maybe return false? I am just not exactly sure where it should go!

**Comment by Jcornmanhomonoff** [comment]
Just to clarify, you **can** or **can't** alternate between x and o?

**Comment by jillrizley** [comment]
oh sorry...that made 0 sense. I CAN alternate, now I need to only be able to click once in each box.

**Comment by Jcornmanhomonoff** [comment]
So there are a few different ways you could go about this. One way might be to add something like a class to a box once the box is clicked & any boxes that have that class might have the click turned off.

**Comment by Jcornmanhomonoff** [comment]
These might be of use: 
https://github.com/ga-wdi-boston/game-project/issues/614
https://github.com/ga-wdi-boston/game-project/issues/625

**Comment by Jcornmanhomonoff** [comment]
You could also check to see if there is some kind of value in the box and not let someone click there if that's the case.

**Comment by jillrizley** [comment]
yeah that's what I'm trying to do, I'm having a hard time figuring out the coding for it. I looked at the examples and tried to recreate them to fit the code I already have, but it doesn't seem to be doing anything either

**Comment by jordanallain** [comment]
wanna talk through it together?

**Comment by jillrizley** [comment]
yes pleaseeeee!

**Comment by jillrizley** [comment]
solved by adding an if statement checking to see if there was anything in the box _before_ it has been clicked
