### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/game-project#816]
I am trying to run an index game action to retrieve all of the games associated with a user but am conceptually coming to a halt. I know it is a GET request and I have set up a games.sh file but am unsure of how to properly format the object I am sending in. I have also set up a gameTally function in api.js that looks like this 
```js
const gameTally = function (data) {
  return $.ajax({
    url: config.apiOrigin.development + '/games/' + data,
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {}
  })
}
```

**Comment by Jcornmanhomonoff** [comment]
Think about how we do a GET request. We don't have to pass through any data because we're just trying to receive data. Are you able to GET an individual game or is this your first GET request for this?

**Comment by scottyscripts** [comment]
The API documentation tell us that the path for `index` action for games is `/games`. Double check your URL. Also remember that our curl scripts (`games.sh`) are completely seperate from our AJAX. They are just two ways to hit our API. Curl scripts are used to reach our API from the command line, but AJAX is used to reach our API from the browser. The urls should be the same in these requests if you are hitting the same endpoint, but AJAX doesn't care at all about your `.sh` files

**Comment by Azinck94** [comment]
ok I think I'm following does this look like a step in the right direction? 
```
const gameTally = function () {
  return $.ajax({
    url: config.apiOrigin.development + '/games',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

**Comment by jordanallain** [comment]
looks worth trying out! did you see if it worked?

**Comment by Azinck94** [comment]
So guys, I am running with the following:
events.js 
```const getGameUpdates = function () {
  event.preventDefault()
  console.log(save.game.id)
  api.gameTally()
    .then(function (data) {
      console.log('Success')
      save.game = data.game
    })
    .catch(function (data) {
      console.log('Nope')
    })
}


api.js

const gameTally = function () {
  console.log('hey')
  return $.ajax({
    url: config.apiOrigin.development + `/games/',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}


index.js

$('#new-game-button').on('click', events.getGameUpdates)

**Comment by cpearce31** [comment]
`gameTally` is supposed to return all games, right? If so, you wouldn't want any reference to `id` in the url you're querying. Check out the url we `POST`ed to create a new game.

**Comment by Azinck94** [comment]
```const gameTally = function () {
  console.log('hey')
  return $.ajax({
    url: config.apiOrigin.development + '/games/',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

**Comment by cpearce31** [comment]
Does that work?

**Comment by Azinck94** [comment]
I am trying to run it with the following function but am not getting the console log in my api function for it:

```js
('#new-game-button').on('click', function (event) {
  event.preventDefault()
  const data = {}
  api.newGame(data)
    .then(ui.newGameSuccess)
    .catch(ui.failure)
  api.getGameUpdates(data)
  $('#game-text').text('New game!')
  turnCount = 0
  // Create an array to represent the game-board
  $('.game-cell').each(function () {
    $(this).text('')
  })
})

**Comment by Jcornmanhomonoff** [comment]
Where are you console logging something? In your ui file? It means that we aren't getting to that point if that's the case.

**Comment by Azinck94** [comment]
api
```const gameTally = function () {
  console.log('hey')
  return $.ajax({
    url: config.apiOrigin.development + '/games/',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

**Comment by Azinck94** [comment]
here is my solution!
events.js
```const getGameUpdates = function () {
  event.preventDefault()
  // console.log(store.game.id)
  api.gameTally()
    .then(function (data) {
      console.log(data)
      console.log('Success')
      store.game = data.game
    })
    .catch(function (data) {
      console.log('Nope')
    })
}
