### ISSUE TITLE
Keep users signed in?

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#817]
I would like to have it so that users stay signed in when the page is refreshed or when they leave the page and come back, and they are only signed out when they click "sign out".

Is this something that is within the scope of our abilities or is it a server-side thing that I can't do much about at this point?

**Comment by jordanallain** [comment]
Hey Brad, this sounds like something you should be trying to do only if you feel like you've met requirements already. If that is the case you probably want to look into local storage

**Comment by cpearce31** [comment]
Technically you could probably store the token as a cookie, as I don't think browser-template's auth logic expires tokens. This would be a little hacky though and probably a lot of work. Definitely a stretch goal. The basics of how cookies work in JS: https://www.w3schools.com/js/js_cookies.asp

**Comment by bradleyden** [comment]
Cool, definitely not there yet but I'm definitely interested in learning that stuff eventually. Thanks for the info!
