### ISSUE TITLE
Sign out is refreshing the page

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/game-project#818]
I have the event.preventDefault() line in my sign out function, but the page is refreshing anyway. That is the only event that is doing this. Here is my sign out function, with some working ones for comparison:

```javascript
const onSignIn = function (event) {
  const data = getFormFields(this)
  event.preventDefault()
  api.signIn(data)
    .then(ui.signInSuccess)
    .catch(ui.signInFailure)
}

const onChangePassword = function (event) {
  const data = getFormFields(this)
  event.preventDefault()
  api.changePassword(data)
    .then(ui.changePasswordSuccess)
    .catch(ui.changePasswordFailure)
}

const onSignOut = function (event) {
  const data = getFormFields(this)
  event.preventDefault()
  api.signOut(data)
    .then(ui.signOutSuccess)
    .catch(ui.signInFailure)
}
```
Not sure why this is the one thing on my page that is causing a refresh.

**Comment by jordanallain** [comment]
can you post the event listener for the sign out button?

**Comment by jordanallain** [comment]
and the HTML of the sign out button and whatever parent container it is in

**Comment by scottyscripts** [comment]
^^^ what he said. Also a good way to check if the function is actually being run is by putting a console.log('something') in your `onSignOut` function. If we don't see this logging to the console, then there is probably an issue with our event handler (maybe the id we are listening for doesn't match the id in our HTML)

**Comment by bradleyden** [comment]
I think I may have discovered the problem in my HTML. I will post the solution and close the issue if it works, otherwise I'll post an update. Thanks!

**Comment by bradleyden** [comment]
Okay I was able to fix it. I had it set up in a very convoluted way where the html was being modified using jquery .html() so I updated my code to have the 'signed in' interface and the 'signed out' interface in two different divs, then used .show() and .hide() to toggle between them, instead of just rewriting the entire html block using .html(). Now signing out does not refresh the page.
