### ISSUE TITLE
Deployment Website Issue

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/game-project#819]
I tested my code and there were no errors. Initially I had the repo in enterprise, so I had to change the repo url to an empty repo on github.com. That worked out fine. I followed the guide line for deployment instructions. I ran grunt deploy and everything was fine. I checked the website around 15mins later and I don't see the file I created. On github.com i went to the gh-pages branch and looked at the html file. The index.html file is 

```html
<!DOCTYPE html>
<html>
    <head>
      <title>Example</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Do not add `link` tags unless you know what you are doing -->
      <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

      <!-- Do not add `script` tags unless you know what you are doing -->
      <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
    </head>
    <body class="container-fluid">
      <h1>Example</h1>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
      ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.</p>
    </body>
</html>

I'm not sure which steps I missed.

**Comment by scottyscripts** [comment]
When you look at your source code on your master branch, do you see your HTML in `index.html` or this stuff?

**Comment by scottyscripts** [comment]
when you do a `grunt deploy` whatever is on your `master` branch will be what shows on your `gh-pages` branch. Is it possible your `master` branch isn't up to date?

**Comment by kailinc** [comment]
Yeah I also see this in master index.html. My master branch is the bare bones template provided at the beginning. I do have other branch 'MVP' which has all the files I made

**Comment by kailinc** [comment]
Seems like I have to put everything I have on my working branch 'MVP' to the master branch. Then I will have to deploy from master again. Is that right?

**Comment by scottyscripts** [comment]
This is correct! You could go about this by merging your other branch into master, then running grunt deploy again

**Comment by kailinc** [comment]
https://github.com/geodynamics/specfem3d/wiki/Merging-Development-Branches-into-Master

Thanks Scott! You are a G
