### ISSUE TITLE
I cant figure out how transfer my api requests to the webpage

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/game-project#820]
I have created the post, get, patch requests but I do not know how to make them appear on my page.

**Comment by cpearce31** [comment]
Let's take a look at your code and see if we can figure out a way to do it

**Comment by scottyscripts** [comment]
@Fcarrion001 How's this going?

**Comment by Fcarrion001** [comment]
fixed.  for update I needed to nest my game logic into the update function, then plug the variables into the object that the update calls for.  I also needed to add logic to the newGame function in order to have it reset the board and start from turn 1.
