### ISSUE TITLE
Trouble with global variable

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#821]
I have a variable that is gameStatus = 'false' set in one of my js files.

When there is a win match, gameStatus = 'true'.

When I require the js file in another file so "logic = require(....)" and use logic.gameStatus it comes up as false even if it console logging as true from the logic file.

I am not sure if I am declaring it wrong or have overlooked something.

For a solution, I have tried console logging, changing the function, moving its position, etc.

Relevant code:
```js
let gameStatus = 'false'
if (turnCounter > 3) {
    if (boxOne !== '' && boxTwo !== '' && boxThree !== '') {
      if (boxOne === boxTwo && boxTwo === boxThree) {
        if (boxOne === 'X') {
          $('#game-text').text('Player 1 wins')
          $('#game-board').off()
        } else {
          $('#game-text').text('Play 2 wins')
          $('#game-board').off()
        }
        gameStatus = 'true'
        console.log('this is the gameStatus from the win: ', gameStatus)
        console.log('this is the gameStatus from the win: ', gameStatus)
      }
    }
const turnLogic = function (event) {
  if (turnCounter % 2 === 0) {
    const value = $(event.target).text()
    if (value === '') {
      $(event.target).text('X')
      $('#game-text').text('Your move Player 2')
      console.log(turnCounter)
      checkWin()
      console.log('this is game status:', gameStatus)
      gameActions.getGameUpdates()
      turnCounter++
    }
  } else {
    const value = $(event.target).text()
    if (value === '') {
      $(event.target).text('O')
      $('#game-text').text('Your move Player 1')
      console.log(turnCounter)
      checkWin()
      console.log('this is game status:', gameStatus)
      gameActions.getGameUpdates()
      turnCounter++
    }
  }
}
```
From the other file:
```js
const logic = require('./logic.js')
const getGameUpdates = function () {
  event.preventDefault()
  console.log(save.game.id)
  console.log('this is the global from gameActions: ', logic.gameStatus)
  const currIndex = $('.game').index(event.target)
  const newValue = $(event.target).text()
  const gameStatus = logic.gameStatus
  const data = {
    'game': {
      'cell': {
        'index': currIndex,
        'value': newValue
      },
      'over': gameStatus
    }
  }
```

**Comment by benjimelito** [comment]
I believe you need to be accessing this in the way you use `store.js` in this project. For example, I would create an object called `gameStatus`, and then have a key value pair in there, like so: 
```const gameStatus = { over : false}```. I would then want to put this object in module.exports in order to use it in other files.

**Comment by CoreyFedde** [comment]
I get an error: "Cannot read property over of 'undefined'" and gets stuck on the line "const gameStatus = logic.gameStatus.over"

**Comment by CoreyFedde** [comment]
After diagnosing with Dr. Ben, the problem turned out to be caused by circular requiring. I was requiring gameActions in my logic file and requiring my logic file in my gameActions. This can cause issues.

Additionally, in order to export something to another file, it needs to be turned into an object, not just a variable.
