### ISSUE TITLE
README.md Wireframes

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/game-project#824]
I took pictures for my wireframes. How should I put the photos in? Should I make a folder in the repo with Wireframe as the title and have all the wireframes there?

**Comment by scottyscripts** [comment]
that is definitely a good way to go about it. You will want to have links in your README.md file that point to your wireframes as well!

**Comment by kailinc** [comment]
I drew my wireframes on a whiteboard. Can I upload those photos to Google Drive and link it? 
Also, for listing technologies used, is that just listing programming languages?
By the way, how do we make our README.md as nice as the ones you  guys make?

**Comment by scottyscripts** [comment]
As long as you have links to them in your README you're all good! Also, don't forget to also link to or include your user stories

**Comment by jordanallain** [comment]
[here's a link](https://guides.github.com/features/mastering-markdown/) explaining the markdown github accepts. also, when you are editing a markdown file in atom, you can do a markdown preview that will show you how it will render on the web. lemme know if you need help figuring that out.

**Comment by jordanallain** [comment]
if you're all set please close @kailinc !
