### ISSUE TITLE
is there a go-back function??

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/game-project#826]
I am trying to go back to a blank game board after displaying a gif for game won.

I have the gif replacing the game board to prevent any further play.

I am having difficulty researching a way to bring the game back without using browser history.

What should I start thinking about next?

**Comment by scottyscripts** [comment]
So when you are playing your game, you are populating squares with values. Perhaps there is a jQuery method we could use to empty all of those squares.

**Comment by 3point14guy** [comment]
Yes, that works.  I can empty all the squares.  It is only when I style the div that the squares are in with a gif, that I have a problem.

**Comment by 3point14guy** [comment]
instead of replacing the game board with the image, Scott helped to learn about show and hide.  I put the image in a new div and used the show and hide methods to alternate between the two divs as called for by the current state of the game. The game now has the functionality that I was looking for without a time machine.
