### ISSUE TITLE
Getting syntax error: unexpected token in console

### ISSUE THREAD

**Issue by cmcqueen1987** [ga-wdi-boston/game-project#827]
I have gone through my code and it seems to be written out correctly for the check for 3X and 30 logic, but I keep getting an error in my console for a ")". If somebody could take a quick look I would appreciate it!

**Comment by scottyscripts** [comment]
@cmcqueen1987 Is this issue resolved?

**Comment by cmcqueen1987** [comment]
Issue was due couple of different things. I had () in the wrong place as well as an additional || statement. Issue has been resolved.
