### ISSUE TITLE
API: Where to start

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/game-project#828]
This question was probably answered a few times already and all but I figure I would open an issue about not really knowing how to start on the api aspects. I'm looking through all my info to see what the website is that I'm uploading to. I probably missed the info somewhere.

**Comment by cpearce31** [comment]
The API address is `https://aqueous-atoll-85096.herokuapp.com/`, and the docs are here: https://git.generalassemb.ly/ga-wdi-boston/game-project-api

**Comment by mak1323** [comment]
Awesome thank you, saved me lots of time going through everything.
