### ISSUE TITLE
Styling disappears on GitHub Pages

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/game-project#83]
Any idea why all my styling disappeared when I tried to host my game on github.io? It still looks fine on my localhost.

Here's a link to the site on github:
http://soynog.github.io/tic-tac-toe/

Not what the relevant code to incude here would be, so here's a link to my repo:
https://github.com/soynog/tic-tac-toe

I think I may not have set it up properly... does anyone remember in which lesson we hosted something on GitHub pages, or could send me a step-by-step for how to get it up there?

Thanks!

**Comment by RDegnen** [comment]
It was in the html/css lesson, what were the steps you went through to host on gh-pages?

**Comment by soynog** [comment]
Found it, followed the steps at the end of the lesson, and it worked! Thanks Ross!
