### ISSUE TITLE
Pushing to github

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/game-project#831]
Hi - I'm asking here because I REALLY don't want to do this wrong.  Until now, I've been working on my local repo, but I want to make sure I know how to push this project up to my remote repo.  I've heard other people say taht I need to setup a remote repo first.  Any helps or tips appreciated!

**Comment by jordanallain** [comment]
yes you need to set up a new repo on github first.

**Comment by jordanallain** [comment]
do you need assistance with this?

**Comment by scottyscripts** [comment]
@jbculbertson How's this going?

**Comment by jbculbertson** [comment]
walked through process with Jordan.  all set, thanks!
