### ISSUE TITLE
font link

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/game-project#832]
I remember Antony telling us last week that we shouldn't add link tags to a previous file.  Before I add a font link, wanted to check to make sure its ok?

I plan to add this to my head.

<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">

**Comment by jordanallain** [comment]
better you use @import in your css if you can!

**Comment by jbculbertson** [comment]
thanks!
