### ISSUE TITLE
Trouble with finding an imported object's property

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#833]
Hi,

I'm importing an object from another file named gamesPlayed. When I console.log gameActions.gamesPlayed I get an object with a length property nested within it. But when I console.log gameActions.gamesPlayed.length, it comes back as undefined. 

Any thoughts on how to access it?

gameActions file
```js
let gamesPlayed = {}
const getStats = function (event) {
  stats()
  .then(function (data) {
    console.log('success')
    console.log(data.games.length)
    gamesPlayed.length = data.games.length
  })
  .catch(function (data) {
    console.log('Nope')
  })
}
```
logic file
```js
const getNewGame = function (event) {
  console.log('button clicked')
  $('#game-text').text('New game!')
  turnCounter = 0
  // Create an array to represent the game-board
  $('.game').each(function () {
    $(this).text('')
  })
  gameActions.getStats()
  let gameCount = gameActions.gamesPlayed.length
  console.log('this is gameActions.gamesPlayed ', gameActions.gamesPlayed)
  console.log('this is gameActions.gamesPlayed.length ', gameActions.gamesPlayed.length)
  $('#gamesDisplay').text(gameCount)
}
```
Results of the last two console logs:

" this is gameActions.gamesPlayed  
Object {}
length: 82
__proto__: Object

 " this is gameActions.gamesPlayed.length undefined"

**Comment by benjimelito** [comment]
One possible issue is that I believe `length` is a reserved property name, and may cause some weird behavior if you create your own property called `length`. Try calling your property something else - if you still get an issue, let me know and I'll come check it out.

**Comment by CoreyFedde** [comment]
Still showing up as undefined

**Comment by CoreyFedde** [comment]
There was an issue with an asynchronous function. By placing the line to display text as the value of the object.length in the initial function, it was fixed.
