### ISSUE TITLE
css file not working

### ISSUE THREAD

**Issue by rtuttle611** [ga-wdi-boston/game-project#834]
selected a body to maintain and nothing is happening. 

```scss 
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
@import 'color';
@import 'theme';
@import 'game-board';



.gameBoard {
  background-color: gray;
  width: 350px;
}

.spot {
  width: 100px;
  height: 100px;
  background-color: pink;
}

**Comment by cpearce31** [comment]
Can you clarify a little what you're trying to do, and also post your html?

**Comment by rtuttle611** [comment]
```html
<div class='gameBoard'>
    <h1 class='headline'>Welcome to Tic-Tac-Toe</h1>
    <ul>
      <li class='spot' id='spot1'>1</li>
      <li class='spot' id='spot2'>2</li>
      <li class='spot' id='spot3'>3</li>
      <li class='spot' id='spot4'>4</li>
      <li class='spot' id='spot5'>5</li>
      <li class='spot' id='spot6'>6</li>
      <li class='spot' id='spot7'>7</li>
      <li class='spot' id='spot8'>8</li>
      <li class='spot' id='spot9'>9</li>
    </ul>
  </div>

attempting to modify my board and it's not responding

**Comment by Jcornmanhomonoff** [comment]
Are you receiving any errors in your console?

**Comment by rtuttle611** [comment]
these 2 separate errors. (they were similar to my script line issues the other day that we resolved)


localhost/:10 GET http://localhost:7165/dependencies.js 
2017-06-29 15:20:25.883 localhost/:11 GET http://localhost:7165/bundle.js 404 (Not Found)

**Comment by cpearce31** [comment]
I'll take a look if you'd like

**Comment by rtuttle611** [comment]
it was in fact a syntax error in MY part when copying and pasting and moving lines. I had an error in my scripts. went onto original github project file and got correct script text, now works fine.
