### ISSUE TITLE
Difficulty with API/CURL

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/game-project#835]
So I'm having difficulty with my API and Curl, trying to connect with CURL first but failing.
```sh
#!/bin/bash

curl "https://aqueous-atoll-85096.herokuapp.com/" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials":{
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'",
      "password_confirmation": "'"${PASSWORD_CONFIRMATION}"'"
    }
  }'

echo
```
this is what I'm going with but comes back 404

**Comment by jordanallain** [comment]
are you trying to sign up?

**Comment by mak1323** [comment]
Trying to sign up, initiate, everything. Just trying to get the API confirmed to work so I can move unto AJAX, though to be honest I'm not entirely sure my AJAX is hooked up correctly if my curl isn't working.

**Comment by jordanallain** [comment]
you aren't providing the correct url for signing up.
```
Verb	URI Pattern	Controller#Action
POST	/sign-up	users#signup
```

**Comment by jordanallain** [comment]
which means the URL should be 

`curl "https://aqueous-atoll-85096.herokuapp.com/sign-up" \`

**Comment by mak1323** [comment]
Thank you, that made a bit more sense. I wasn't sure if I it automatically created that aspect.
