### ISSUE TITLE
AJAX requests work on development URL, but not production

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#836]
Just deployed my web app, which was working fully while using the development URL. Now that the config file is using the production URL, the AJAX requests don't work.

The errors that I am getting back are 400 bad requests. "
15:23:23.011 vendor.js:9678 POST https://ga-wdi-boston.herokuapp.com/sign-up 400 (Bad Request)
send @ vendor.js:9678
ajax @ vendor.js:9285
signUp @ application.js:584
onSignUp @ application.js:624
dispatch @ vendor.js:5318
elemData.handle @ vendor.js:5126"

Not sure where to start debugging this, especially now that the URL has changed.

**Comment by jordanallain** [comment]
that is not the correct production URL...

try replacing

https://ga-wdi-boston.herokuapp.com

with 

https://aqueous-atoll-85096.herokuapp.com

in your config file

**Comment by CoreyFedde** [comment]
Thank you. Push the change and then redeploy to fix?

**Comment by jordanallain** [comment]
diditwork.jpg?

**Comment by CoreyFedde** [comment]
Changing the URL worked!
