### ISSUE TITLE
can't change value of 'over' (in patch request) from false to true 

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/game-project#838]
I made a function to check if checkForWin returns true or false
```
const checkGameOver = function () {
  if (checkForWin === true) {
    return true
  } else {
    return false
  }
}
```
and then I call that function in the params of 
`onUpdateGame('x', $(this).data('id'), checkGameOver())`

where onUpdateGame is 
```
const onUpdateGame = function (letter, index, gameOver) {
  const data = {
    'game': {
      'cell': {
        'index': index,
        'value': letter
      },
      'over': gameOver
    }
  }
  api.updateGame(data)
    .then(ui.updateGameSuccess)
    .catch(ui.updateGameFailure)
}

```
but the value of 'over' stays false even when checkForWin returns true

**Comment by jordanallain** [comment]
do you want to be returning true || false in that function or setting the value of gameOver to true or false?

**Comment by jingrid** [comment]
set the value of gameOver to true or false. 

Thought I could achieve that with the function lol

**Comment by jordanallain** [comment]
you can if you change whats happening in the function

**Comment by jordanallain** [comment]
maybe something like:

```diff
const checkGameOver = function () {
  if (checkForWin === true) {
-    return true
+   gameOver = true
  } else {
-    return false
+   gameOver = false
  }
}
```

**Comment by jordanallain** [comment]
or you could set gameOver = checkGameOver() since currently it would return true or false.

**Comment by jingrid** [comment]
this works:
defined `let gameOver = false`

changed function to 
```
const checkGameOver = function () {
  if (checkForWin() === true) {
    gameOver = true
  } else {
  }
}
```
then keep the params as 
`onUpdateGame('x', $(this).data('id'), gameOver)`
