### ISSUE TITLE
Passing cell Id into function

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#84]
I'm trying to pass `boxId` (the id of the cell that was clicked) into the `boxClicked` function.  When I click a box the Id of the box is alerted and then another alert saying "undefined" pops up.  boxClicked then fails to run.  
There are no linter errors.

``` javascript
let boxId = $('.container').on('click', 'div', function (e) {
    e.preventDefault();
    ($(this).attr('id'));
});

const boxClicked = function() {
  if(getPlayer()==="playerO") {
    $('boxId').html('O');
    turns++;
    alert("Go Player X");
 } else if(getPlayer()==="playerX") {
    $('boxId').html('X');
    turns++;
    alert("Go Player O");
  } else {alert("Cell Unavailable");
 }
};

$(document).ready(function() { $('boxId').bind("click", boxClicked); });
```

Thank you!

**Comment by RDegnen** [comment]
is 

```
let boxId = $('.container').on('click', 'div', function (e) {
    e.preventDefault();
    ($(this).attr('id'));
});
```

properly catching an id? maybe put a debugger in there and see what $(this) is.
Also I dont think you need parenthesis around  `$(this).attr('id')`

**Comment by gaand** [comment]
The `on` method doesn't return what the handler passed to it returns.

Remember that the handler doesn't run until someone clicks the div.

**Comment by susandaiute** [comment]
I went the obvious route and added `return`.

``` javascript
let boxId = $('.container').on('click', 'div', function (e) {
    e.preventDefault();
    ($(this).attr('id'));
});
```

That's not working either.

**Comment by susandaiute** [comment]
oops!! it now looks like:

``` javascript
let boxId = $('.container').on('click', 'div', function (e) {
    e.preventDefault();
    return$(this).attr('id');
});
```

**Comment by laurenfazah** [comment]
Remember, `attr()` is a setter and getter in jQuery, so it doesn't need to be wrapped in a function to _get_ the value you're looking for.

**Comment by RealWeeks** [comment]
.on() doesn't return what you think it returns. You're on the wrong path here.

**Comment by susandaiute** [comment]
Result: Lauren is awesome. Code works!
