### ISSUE TITLE
deployed page not displaying

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/game-project#840]
my repo is https://git.generalassemb.ly/jingrid/Tic-Tac-Toe-project

but the deployed page http://jingrid.github.io/Tic-Tac-Toe-project

isn't loading. I deployed around 20 min ago.

**Comment by jordanallain** [comment]
Your project repo should be on github not github enterprise.

**Comment by jordanallain** [comment]
If you deployed to GHE the link will not be http://jingrid.github.io/Tic-Tac-Toe-project

**Comment by jordanallain** [comment]
https://git.generalassemb.ly/pages/jingrid/Tic-Tac-Toe-project/

**Comment by jingrid** [comment]
Ah i moved it from enterprise and now it works!
