### ISSUE TITLE
game works on local but not deployed site

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/game-project#842]
SO my game runs smoothly on localhost but when I try to run what I've deployed I get the following error:
```
Mixed Content: The page at 'https://azinck94.github.io/TicTacToe/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tic-tac-toe.wdibos.com/sign-in/'. This request has been blocked; the content must be served over HTTPS.
```
I have tried to run it as https but nothing has worked. I will be in tomorrow AM if anyone could help my get a handle on this would really appreciate!

**Comment by jordanallain** [comment]
Don't see anything there

**Comment by jordanallain** [comment]
Looks like you have the wrong URL there. Should be the aqueous atoll one others are using.

**Comment by jordanallain** [comment]
@Azinck94 is this still an issue?

**Comment by Azinck94** [comment]
changed config.js to
```
'use strict'

const config = {
  apiOrigin: {
    development: 'https://aqueous-atoll-85096.herokuapp.com',
    production: 'https://aqueous-atoll-85096.herokuapp.com'
  }
}

module.exports = config
