### ISSUE TITLE
cannot sign out, possible token issue 

### ISSUE THREAD

**Issue by rtuttle611** [ga-wdi-boston/game-project#845]
```js
const updateGame = (data) =>
$.ajax({
  url: config.apiOrigin + '/games/' + store.current_game_id,
  method: 'PATCH',
  headers: {
    Authorization: 'Token token=' + store.user.token
  },
  data
})```

**Comment by benjimelito** [comment]
I noticed this is the function for updating a game, not signing out. Could you post the code you have for signing out? Also, are you getting any sort of error upon trying to sign out?

**Comment by rtuttle611** [comment]
it was a syntax error with a comma, my apologies for the delayed closure of this issue
