### ISSUE TITLE
Game states

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/game-project#846]
I've been fixing everything else on my project, but I'm now stuck on how to start new game states and game state logic. I'm not sure where to connect it and how to connect it. All my other api is working great, but I'm confused on how to start with my code on this. 

I know I need 
```js
<form>
  <input name="game[cell][index]" type="text" value="0">
  <input name="game[cell][value]" type="text" value="x">
  <input name="game[over]" type="text" value="false">
</form>
{
  "game": {
    "cell": {
      "index": 0,
      "value": "x"
    },
    "over": false
  }
}
```
I think I need to make a form in my html, use that as my get form fields and use it to display, but I'm not entirely sure.

**Comment by mak1323** [comment]
So I've been working on this all week and weekend (as much as I could). This is the patch request I'm making
```js
  const data = {
    "game": {
      "cell": {
        "index": currentMoveForPatch,
        "value": value
      },
      "over": endResults(playerOne, playerTwo)
    }
  }
  api.updateGame(data)
}
```

which attaches to this
```js
const updateGame = function (data) {
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + 'games/' + ui.gameId(),
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
with the id being
```js
const createGame = function () {
  event.preventDefault
  api.createGameState()
    .then(ui.createGameSuccess)
    .catch(ui.createGameFailure)
  api.getStates()
    .then(ui.getStatesSuccess)
    .catch(ui.getStatesFailure)
  gameRecord(ui.games)
}
```
```js
let activeGame = false

const gameId = function () {
  console.log(activeGame.id)
  return activeGame.id
}
```
```js
const getStatesSuccess = (data) => {
  message("You're ready to play.")
  store.games = data
  games = store.games
  console.log(games)
}
```
I've stared at the code going in, it matches the required code. Combed over other open and closed issues. I was hoping the one on one on friday would have helped helped, but we missed it. I'm been at this for hours, no idea where to go.

**Comment by payne-chris-r** [comment]
What's the error you're getting?

**Comment by payne-chris-r** [comment]
Have you tried using a curl script to mimic your Ajax request?

**Comment by payne-chris-r** [comment]
What URL are you trying to make your request to?

**Comment by mak1323** [comment]
I was messing up in a dumb way. I got too close to the code and couldn't tale a step back. The problem was here
```js

const updateGame = function (data) {
  return $.ajax({
    method: 'PATCH',
    url: config.apiOrigin + 'games/' + ui.gameId(),
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: data
  })
}

```

I wasn't attaching the data.
