### ISSUE TITLE
Reset Button defaulting to browser refresh

### ISSUE THREAD

**Issue by MBKeeler** [ga-wdi-boston/game-project#849]
I have a bug that I only just now has been hindering my efforts to fix up my project code to meet requirements.  I would like to have another set of eyes on code and check my logic.

The issue is that once a game is won, the game board fades out and a Reset button appears.  The reset button and the associated <form> tag info is inserted using jquery.  The button appears just fine, but when clicked I am realizing that the whole page is reset.  In other words the browser is defaulting to resetting the page rather than calling my reset function.  Below is the event handler code, game reset function call to my gameLogic resetGame function (not provided in this issue) and the jquery I use to create the reset button.  

At I fixed a bug where I was using a class name rather than an id name.  But after fixing that the button still does not call my resetGame function.  However, I'm far past the 1/2 hr time box to work the issue. 

**From my events.js file**
```
// reset the game array and board
const resetGameBoard = function (event) {
  console.log('reset game called')
  event.preventDefault()
  gameLogic.resetGame()
  ui.resetBoard()
}

const addHandlers = function () {
  $('#sign-up').on('submit', onSignUp)
  $('#sign-in').on('submit', onSignIn)
  $('#sign-out').on('submit', onSignOut)
  $('#box_grid div').on('click', clickSector)
  $('#resetButton').on('submit', resetGame)
}
```

**From my UI.JS**
```
const displayWinnner = function (playerValue) {
//  console.log('displayWinnner was called')
  if (playerValue === 'o') {
    $('#message').html('The game is over.')
    $('#message2').html('<h4><span style="color:green">Player O</span> is the winner! </h4>')
    $('.box_grid').fadeOut(2500)
    $('#message2a').html('<form id="resetButton"><button type="submit" name="submit">Reset Game</button></form>').fadeIn(2000)
  } else {
    $('#message').html('The game is over.')
    $('#message2').html('<h4><span style="color:green">Player X</span> is the winner!</h4>')
    $('.box_grid').fadeOut(2500)
    $('#message2a').html('<form id="resetButton"><button type="submit" name="submit">Reset Game</button></form>').fadeIn(2000)
  }
}
```

**Comment by payne-chris-r** [comment]
You probably are adding the jquery click handler BEFORE the button is present in the DOM. If the jquery click handler runs 
`$('#resetButton').on('submit', resetGame)` 
BEFORE you show that button
`$('#message2a').html('<form id="resetButton"><button type="submit" name="submit">Reset Game</button></form>').fadeIn(2000)` 
then the handler wasn't actually applied successfully. You need to apply the handler AFTER the button is added to the DOM.
