### ISSUE TITLE
Changing Classes

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#86]
I'm having an issue with my classes. I am getting my x and o to alternate, however, when I click again on my o, it adds an x class to it and switches it to an x. Any help???

``` js

$('.available').on('click', function(){
  let currentCell = $(this);
  currentCell.removeClass('available');
  currentCell.addClass('player');
  if (player === 'player-x') {
    currentCell.addClass('player-x');
  }else {
    currentCell.addClass('player-o');
    }
  }
);

```

**Comment by RealWeeks** [comment]
This is because when you add a class you are doing exactly that solely adding a class. You may want to consider doing some "clean up" if you're adding things then want them gone later.

**Comment by laurenfazah** [comment]
Inspect the cells you click in your browser's inspector panel to see what classes are being added when...

**Comment by RealWeeks** [comment]
@Jcornmanhomonoff worry about what @laurenfazah said first. In doing that you'll probably solve this and other problems.

**Comment by Jcornmanhomonoff** [comment]
I did that and it adds the o class and then adds the x class on top of that afterwards. I suppose I'm still confused as to why it's adding another class to it.

**Comment by RDegnen** [comment]
Does it remove the class .available? or does that still exist?

**Comment by Jcornmanhomonoff** [comment]
Issue solved. Had to reference a class and then remove it and add another.
