### ISSUE TITLE
player icon undefined

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/game-project#88]
playerIcon is a variable set to the strings "xzibit" and "oprah" alternating between clicks.

That much is working, and places the correct string into the clicked cell.

``` js


// takes num of clicks % 2
function getPlayer(numOfClicks){
  if (numOfClicks % 2 === 0) {
  playerIcon = playerIcons[0];
} else {
 playerIcon = playerIcons[1];
}

}


$('td').on('click', function(){
  turnClick++;
  if (turnClick % 2 === 0) {
  playerIcon = playerIcons[0];
} else {
playerIcon = playerIcons[1];
}
  console.log(playerIcon);
  console.log(turnClick);
  let currentCell = $(this);
  currentCell.text(playerIcon);

  console.log(currentCell.id);
  //checks move validity
  currentCell.text(playerIcon);

});
```

my console is printing 
Xzibit playerIcon
1 (clickcount)
undefined (should be currentCell.text(playerIcon)

shouldn't the final console.log be printing the player icon currently assigned to that cell ?

**Comment by RealWeeks** [comment]
this console.log `console.log(currentCell.id);` ? What is $(this)?

**Comment by RDegnen** [comment]
Does currentCell have an id property?

**Comment by BenGitsCode** [comment]
My html looks like this, so that console.log(currentCell.id) should be referencing the id of the currentCell clicked, which in the case of clicking cell #C1 would be C1 right?

``` html
<div id="board" class="row">
        <table class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3">
          <tr class="box-row" >
            <td id="C1" class="start-cell" ></td>

            <td id="C2" class="start-cell" ></td>

            <td id="C3" class="start-cell" ></td>
          </tr>
          <tr class="box-row">
            <td id="C4" class="start-cell" ></td>

            <td id="C5" class="start-cell" ></td>

            <td id="C6" class="start-cell" ></td>
          </tr>
          <tr class="box-row">
            <td id="C7" class="start-cell" ></td>

            <td id="C8" class="start-cell" ></td>

            <td id="C9" class="start-cell" ></td>
          </tr>
        </table>
      </div>
```

**Comment by laurenfazah** [comment]
ID is an attribute of the `<td>` cell, so look into getting attributes in jQuery and that should get you exactly what you're looking for. Remember, using dot notation (`currentCell.id`) only works with JavaScript objects...

**Comment by BenGitsCode** [comment]
I changed my console log to

``` js
console.log(currentCell.attr('id'));
```

and now the console returns:

the current player
the num of clicks
the correct id of the table cell clicked
