### ISSUE TITLE
JS- Cant update the contents of the selected div

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/game-project#9]
``` js
$('#gameboard').on('click', function(event) {
  event.stopImmediatePropagation();
  let gameboardBox = $(event.target.id);
  alert(gameboardBox); //Testing purposes
  if (global.turn === true) {
    gameboardBox.text("X").css("background-color", "green");
    global.turn = false;
    console.log(gameboardBox.text());//Testing purposes
  } else {
    gameboardBox.text("O").css("background-color", "red");
    global.turn = true;
    console.log($(event.target.id).text());//Testing purposes
  }
});
```

I am trying to fill the event.target.id with an X or and O. My alert will display the entire object at the event.target.id. The "selector" function in JQuery will return the correct id name but I get errors on my intital .text(), stating the selector is not a function. Which it isnt.....

**Comment by jrhorn424** [comment]
I have some questions.

``` js
$('#gameboard').on('click', function(event) {
  event.stopImmediatePropagation();
```

Why `stopImmediatePropagation()` instead of `preventDefault()`?

``` js
  let gameboardBox = $(event.target.id);
```

This may be a poorly named variable. It seems to me that this is an ID, not a DOM node, correct? So it should be string type. When I read `gameBoardBox` I imagine a DOM node.

``` js
    gameboardBox.text("X").css("background-color", "green");
    global.turn = false;
    console.log(gameboardBox.text());//Testing purposes
  } else {
    gameboardBox.text("O").css("background-color", "red");
    global.turn = true;
    console.log($(event.target.id).text());//Testing purposes
  }
});
```

Now, to answer your question, everywhere you use `text` you're probably making a mistake. You can set CSS on strings. Why string?

> The result of the .text() method is a string containing the combined text of all matched elements
> (from the docs)

So you probably want something else.

Additionally, `$(event.target.id)` is a string, as mentioned above. You can't call `text` on strings, so that's the immediate reason for your error.

**Comment by jrhorn424** [comment]
I suspect `event.target.id` is not actually what you intend. `event.target` is a native DOM element (not a jQuery object). If you're storing an id in a data attribute, you'll want the `data()` method in jQuery. If you're trying to get the value stored in the HTML attribute named id, you'll need to use the jQuery `attr()` method.

**Comment by ajordon** [comment]
In need `event.target.id` because my html is set up to trigger on the #gameboard parent, and I need the exact div that it triggered on.

``` html
    <div id="gameboard">
                <div class ="box" id="top-left"></div>
                <div class ="box" id="top-middle"></div>
                <div class ="box" id="top-right"></div></br>
                <div class ="box" id="middle-left"></div>
                <div class ="box" id="middle-middle"></div>
                <div class ="box" id="middle-right"></div></br>
                <div class ="box" id="bottom-left"></div>
                <div class ="box" id="bottom-middle"></div>
                <div class ="box" id="bottom-right"></div>
            </div>
```

**Comment by gaand** [comment]
I think event.target is the div (techincally it's representation in the DOM) that it triggerd on.

**Comment by RealWeeks** [comment]
@ajordon try dropping in a debugger statement and playing around in the chrome console with .text() and other jquery methods.
