### ISSUE TITLE
Click Tracker

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#90]
Not quite sure how to tell if my click tracker is working properly based off of how it's console logging.

Not sure how to explain. Need to physically show....

**Comment by gaand** [comment]
Please paste the code and what it logs.

**Comment by Jcornmanhomonoff** [comment]
``` js

'use strict';

let turnClick = 0;
//
let players = ['player-x', 'player-o'];
let player = '';


//counts clicks & alternates players
$('.available').on('click', function(){
  let currentCell = $(this);
    if (turnClick % 2 === 0) {
      player = players[0];
    } else {
      player = players[1];
    }
    console.log(turnClick);
});

//changes block color on click & adds player class (x or o)
$('.box').on('click', function(){
  let currentCell = $(this);
  if (currentCell.hasClass('available')) {
    currentCell.removeClass('available');
    currentCell.addClass('player');
  if (player === 'player-x') {
    currentCell.addClass('player-x');
      turnClick++;
  }else {
    currentCell.addClass('player-o');
      turnClick++;
    }
  }
  }
);

```

<img width="1423" alt="screen shot 2016-04-06 at 1 25 24 pm" src="https://cloud.githubusercontent.com/assets/17557070/14326235/258a850a-fbfb-11e5-9552-515aff1b834a.png">

**Comment by Jcornmanhomonoff** [comment]
I'm basically just looking for confirmation that it's working but I'm uncertain based off of how it's showing in the console.

**Comment by RealWeeks** [comment]
looks like it's working

**Comment by RealWeeks** [comment]
Though I'm not sure it intends what you intend it to do

**Comment by gaand** [comment]
Is it alternating what gets displayed?

**Comment by laurenfazah** [comment]
@J-Weeks not necessarily, given the duplicates of some numbers. If you're looking to test a value after it changes, wouldn't it make sense to put that console.log test of `turnClick` right after `turnClick` is operated on?

**Comment by RealWeeks** [comment]
@Jcornmanhomonoff high level question: What do you intend to do with the click tracker? what's it purpose?

**Comment by Jcornmanhomonoff** [comment]
I need to determine who is going next.

**Comment by RDegnen** [comment]
Have you tried determining if it is in fact alternating properly between players turns or are you just curious if its counting properly?

**Comment by Jcornmanhomonoff** [comment]
It is alternating properly. I am just uncertain if the way it's counting is correct. Or if that even matters because it is alternating.

**Comment by laurenfazah** [comment]
Well `++` will always increase by 1, so that _should_ be working.

**Comment by gaand** [comment]
You can use the count to help determine if it's a cat's game.

**Comment by Jcornmanhomonoff** [comment]
When I click on a box it counts that box as 0. When I click it again it counts as 1. If i click it again it continues to count as 1. When I click on another box it stays at 1. If I click on another box it goes to 2. Is this working correctly? The x's and o's are working properly and the boxes are never switched from one class to another. However, as in @gaand's point, I need to make sure there are 9 moves to reference it properly for a cat's game. Is this working the way it should?

**Comment by laurenfazah** [comment]
@Jcornmanhomonoff if this is fixed (which I believe it was), please close. Thanks!
