### ISSUE TITLE
Clicking on a box twice

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/game-project#91]
I'm trying to stop a cell/box from being clicked on twice.  When I click on any box, the box HTML becomes 'O' and no longer changes turns with 'X' - it is always O's turn basically. Also, any box can be clicked on infinite times.

``` javascript
const isTaken = function() {
  if($('#'+boxId).html==='O' || $('#'+boxId).html==='X'){
    return boxTaken===true;
  }
};

const boxClicked = function(boxId) {
  if(getPlayer()==="playerO" || boxTaken!==true) {
    $('.gametile#' + boxId).html('O');
    turns++;
    $('.turnAlert').html('Go Player X');
 } else if(getPlayer()==="playerX" || boxTaken!==true) {
    $('.gametile#' + boxId).html('X');
    turns++;
    $('.turnAlert').html('Go Player O');
  } else {alert("Cell Unavailable");
 }
};
``
```

**Comment by RealWeeks** [comment]
what is boxId?

**Comment by laurenfazah** [comment]
Have you logged within `isTaken()` to see if things are acting the way you expect to in there?

**Comment by susandaiute** [comment]
The id for the cell.

**Comment by RealWeeks** [comment]
What @laurenfazah said. Also trying adding debuggers in each branch of your if/else statement and see if it expects to hit where you think it will.

**Comment by susandaiute** [comment]
console.log is not showing up .

**Comment by laurenfazah** [comment]
Where'd your code go? If a console.log you expect is not showing, that indicates that that line of code is not being executed.

**Comment by RealWeeks** [comment]
@susandaiute did you remove your code snippet?

**Comment by susandaiute** [comment]
Nope, still there on my screen

**Comment by laurenfazah** [comment]
Ermmm....could you repaste it in another comment? Not sure where it went. Or even better, paste what you currently have with the `console.log`.

**Comment by susandaiute** [comment]
I've changed it a bit.  The console log still isn't showing.  Instead of saying:

``` javascript
const isTaken = function() {
  if($('#'+boxId).html==='O' || $('#'+boxId).html==='X'){
    return boxTaken===true;
  }
};

const boxClicked = function(boxId) {
  if(getPlayer()==="playerO" || boxTaken!==true) {
    $('.gametile#' + boxId).html('O');
    turns++;
    $('.turnAlert').html('Go Player X');
 } else if(getPlayer()==="playerX" || boxTaken!==true) {
    $('.gametile#' + boxId).html('X');
    turns++;
    $('.turnAlert').html('Go Player O');
  } else {alert("Cell Unavailable");
 }
};
```

It is now:

`````` javascript
const isTaken = function() {
  if($('#'+boxId).html==='O' || $('#'+boxId).html==='X'){
    return true;
    console.log('boxTaken');
  }
};

const boxClicked = function(boxId) {
  if(getPlayer()==="playerO" || isTaken()!==true) {
    $('.gametile#' + boxId).html('O');
    turns++;
    $('.turnAlert').html('Go Player X');
 } else if(getPlayer()==="playerX" || isTaken()!==true) {
    $('.gametile#' + boxId).html('X');
    turns++;
    $('.turnAlert').html('Go Player O');
  } else {alert("Cell Unavailable");
 }
};
```javascript

The console log isn't showing and the error is saying boxId is not defined.
``````

**Comment by susandaiute** [comment]
I have to head to outcomes, but I'll keep working on this afterwards.  Thanks guys!

**Comment by laurenfazah** [comment]
Remember the power of `return`... also, I'd suggest having that `console.log` be the first thing in that function to test if the function itself is being hit before jumping in to see if your `if` statement is returning `true`.

**Comment by susandaiute** [comment]
I'm not catching on to this.  Any further advice?

**Comment by susandaiute** [comment]
Ross, could we meet when you have a minute?
