### ISSUE TITLE
issues with submit function

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#96]
I'm having issues with the signup... I don't seem like all my variables are being passed through to ajax...

Can someone help me on this?

``` js
  $('#sign-up').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this);
    authApi.signUp(authUi.success, authUi.failure, data);
  });
```

Edited by @gaand to add code block.

**Comment by laurenfazah** [comment]
Have you `console.log`ged `data` to see what is being sent to the `signUp` function? Can you paste the output of that?

**Comment by pvdri** [comment]
hello lauren, thanks.. i get undefined

**Comment by gaand** [comment]
Is that in the submit handler?

**Comment by pvdri** [comment]
yes

**Comment by pvdri** [comment]
i get it on the console.log

**Comment by gaand** [comment]
Would you please paste the code from the submit handler with the console.log?  So what you pasted before but with the change you made that includes `console.log(data);`?

Thanks.

**Comment by pvdri** [comment]
thank you Anthony.... I resolved the issue because my console.log(data) function was in the wrong place..

Thank you Lauren & Antony!
