### ISSUE TITLE
Game patch issue

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/game-project#97]
I keep getting different 400 responses when i try to update my game cells. This is where I make the ajax call:

``` js
'use strict';

const findWin =  require('./findWin.js');
const game = require('./game-data.js');
const move = require('./make-move.js');
const updateApi = require('./update-game-api.js');
const ui = require('./ui.js');

const play = function ($currentBox) {
  if (game.playerOnesTurn) {
    move.makeMoveX($currentBox);
    updateApi.updateGame(ui.gameUpdateSuccess, ui.gameUpdateFailure, game.game.game.cells);
    findWin.findWinOrTie();
  }else if ((!game.playerOnesTurn)) {
    move.makeMoveO($currentBox);
    updateApi.updateGame(ui.gameUpdateSuccess, ui.gameUpdateFailure, game.game.game.cells);
    findWin.findWinOrTie();
  }
};

module.exports = {
  play,
};
```

And there is where I define the ajax call:

``` js
'use strict';

const user1 = require('../auth/user1.js');
const game = require('./game-data.js');

const updateGame = (success, failure, data) => {
  $.ajax({
    method: 'PATCH',
    url: 'http://tic-tac-toe.wdibos.com/' + 'games/' + game.game.game.id,
    data,
    headers: {
      Authorization: 'Token token=' + user1.user.token,
    },
  })
  .done(success)
  .fail(failure);
};

module.exports = {
  updateGame,
};
```

I've tried both altering the way I reference the data when I call the function and also how I call the game id inside the actual ajax function. Pretty sure I'm missing something basic here.

**Comment by laurenfazah** [comment]
Have you console.logged the url you're sending data to?

**Comment by gaand** [comment]
The api is very particular about what you're allowed to send to update the state of the board.  You don't send the whole board, just info about the cell you want to update (or if you want to mark the game `over).

**Comment by gaand** [comment]
Suggestion:  Simplify or refactor your nesting, `game.game.game` seems unintuitive.

**Comment by RealWeeks** [comment]
@louarnos still working on this?

**Comment by louarnos** [comment]
yayyy i need to read the documentation better!!!!
