### ISSUE TITLE
Javascript is not rendering although it appears to be recognized

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#98]
having trouble rendering my javascript. Not working as it previously did. Getting a syntax error I can't figure out.

**Comment by laurenfazah** [comment]
What is the syntax error? What line is it coming from and what do you see before/at/after that line?

**Comment by ghost** [comment]
just says unrecognizable syntax error. line 36.

`
      theWinner(1, 5, 9, move) ||
      theWinner(3, 5, 7, move))
    }
    result = true;
  };
  return result;
};
`

**Comment by RDegnen** [comment]
Unless there are other parenthesis or brackets before in your code somewhere, you have a lot of closing ones but not open ones

**Comment by RealWeeks** [comment]
Larger issue that required moving around function and waiting for the dom to load.
