### ISSUE TITLE
Checking AJAX

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/game-project#99]
I am trying to console.log my errors/successes with my buttons to see if they are working. Having some serious trouble figuring out how to do so....

**Comment by RealWeeks** [comment]
@Jcornmanhomonoff please be more specific with your questions

**Comment by RealWeeks** [comment]
do you not know where to put the console.log?

**Comment by Jcornmanhomonoff** [comment]
precisely

**Comment by gaand** [comment]
Please paste the code from the handler.

**Comment by Jcornmanhomonoff** [comment]
``` js

const addHandlers = () => {
  $('#sign-up').on('submit', function (event) {
    let data = getFormFields(this);
    event.preventDefault();
    authApi.signUp(authUi.success, authUi.failure, data);
  });
  $('#sign-in').on('submit', function (event) {
    let data = getFormFields(this);
    event.preventDefault();
    authApi.signIn(authUi.signInSuccess, authUi.failure, data);
  });
  $('#sign-out').on('submit', function (event) {
    event.preventDefault();
    authApi.signOut(authUi.signOutSuccess, authUi.failure);
  });
};

```

**Comment by laurenfazah** [comment]
So it looks like you've got your success and failure functions sent with `authUi.signInSuccess, authUi.failure`, so find where those are defined and you should see the data you'd want to console.log.

**Comment by RDegnen** [comment]
^
|
|
|
|
See Laurens comment

**Comment by Jcornmanhomonoff** [comment]
I didn't have the 

``` js
const authEvents = require('./auth/events.js');
$(() => {

authEvents.addHandlers();
```

in my index.js
